import type { CalculatorDefinition } from "../types";

export const automotiveR7Calculators: CalculatorDefinition[] = [
  {
    id: "mpg-to-l100km",
    slug: "mpg-to-l100km-converter",
    category: "Automotive",
    categorySlug: "automotive",
    title: "MPG to L/100km Converter",
    shortDescription: "Convert miles per gallon into litres per 100 km.",
    seoTitle: "MPG to L/100km Converter — Fuel Economy Conversion",
    metaDescription: "Free MPG to L/100km converter. Enter US miles per gallon to instantly see the equivalent litres per 100 kilometres used by European and metric fuel economy ratings.",
    primaryKeyword: "mpg to l/100km converter",
    secondaryKeywords: ["mpg to l100km", "fuel economy converter", "miles per gallon to litres per 100km"],
    fields: [
      { id: "mpg", label: "Fuel economy", type: "number", unit: "mpg", required: true, span: 2, min: 0, step: 0.1 },
    ],
    results: [
      { id: "litersPer100km", label: "In L/100km", format: "number", decimals: 2, unit: "L/100km", isPrimary: true },
    ],
    formula: "L/100km = 235.214583 ÷ MPG",
    formulaExplanation: "Miles per gallon and litres per 100 kilometres describe the same thing from opposite ends: one counts distance per unit of fuel, the other counts fuel per fixed distance. Because they are reciprocals rather than a straight scaling, converting requires the fixed factor 235.214583, which bundles the gallon-to-litre and mile-to-kilometre conversions into a single constant. Dividing that constant by your MPG returns the metric figure, and a higher MPG always produces a lower L/100km.",
    explanation: "Comparing a car rated in American miles per gallon with one rated in European litres per 100 kilometres is confusing because the two measures run in opposite directions, and this MPG to L/100km converter removes the guesswork. Enter a fuel economy figure in miles per gallon and it returns the exact metric equivalent, letting you line up specifications from different markets on a single scale.\n\nThe conversion matters whenever you shop across borders, read an imported review, or try to understand a manufacturer's global brochure. A car advertised at 6 L/100km and one advertised at 39 MPG sound unrelated, yet they describe almost identical efficiency. Without a reliable conversion it is easy to misjudge which vehicle actually sips less fuel, and small differences in economy add up to real money over years of driving.\n\nThe key idea is that MPG and L/100km are reciprocal quantities linked by a fixed constant. Miles per gallon rewards higher numbers, since more distance per gallon is better, while litres per 100 kilometres rewards lower numbers, since less fuel for the same distance is better. Because the relationship is not linear, a jump from 20 to 25 MPG saves far more fuel than a jump from 45 to 50 MPG, and viewing the same efficiency in metric terms makes that non-linearity visible and easier to reason about when weighing your options.",
    example: { inputs: { mpg: 30 }, explanation: "235.214583 ÷ 30 ≈ 7.84 L/100km, so a 30 MPG car uses about 7.84 litres to travel 100 kilometres." },
    faqs: [
      {
        question: "Why is the conversion factor 235.214583?",
        answer: "The constant folds two unit conversions into one number. It accounts for the 3.785 litres in a US gallon and the 1.609 kilometres in a mile, arranged so that dividing it by miles per gallon yields litres per 100 kilometres directly. Because MPG and L/100km are reciprocal measures rather than proportional ones, a single multiply will not work, but this fixed divisor handles both steps at once accurately.",
      },
      {
        question: "Does this use US or Imperial gallons?",
        answer: "This converter uses the US gallon, which is the standard for fuel economy ratings in the United States. The Imperial gallon used in the United Kingdom is about 20 percent larger, so an Imperial MPG figure would convert with a different constant near 282.5. If your MPG figure comes from a UK source, be aware it may be Imperial, which would overstate efficiency compared with the US measure.",
      },
      {
        question: "Why is a small MPG gain worth more at low MPG?",
        answer: "Because fuel use is the reciprocal of MPG, the relationship is non-linear. Going from 15 to 20 MPG cuts fuel consumption far more than going from 40 to 45 MPG, even though both are five-MPG gains. Viewing the numbers in L/100km makes this obvious, since the litres-per-distance figure falls steeply at low MPG and only gently at high MPG, which is why efficient cars show diminishing returns.",
      },
      {
        question: "What is a typical L/100km value for an efficient car?",
        answer: "A frugal modern hybrid often sits around 4 to 5 L/100km, a typical petrol sedan around 7 to 9 L/100km, and a large SUV or truck can exceed 12 L/100km. Lower numbers are better in this metric. Because conditions like city traffic, cold weather, and aggressive driving raise consumption, real-world figures usually run somewhat higher than the official rating you convert here.",
      },
      {
        question: "Can I convert L/100km back to MPG?",
        answer: "Yes, the relationship is symmetric because both measures are reciprocals joined by the same constant. To go the other way, divide 235.214583 by the L/100km value and you recover the miles-per-gallon figure. This means the conversion never loses information: any economy expressed in one unit maps to exactly one value in the other, so you can move between American and metric ratings freely and consistently.",
      },
    ],
    relatedCalculators: ["mpg-calculator", "fuel-cost-calculator", "trip-fuel-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard fuel economy unit conversion",
  },
  {
    id: "car-lease-payment",
    slug: "car-lease-payment-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "Car Lease Payment Calculator",
    shortDescription: "Estimate a monthly car lease payment.",
    seoTitle: "Car Lease Payment Calculator — Monthly Lease Cost",
    metaDescription: "Free car lease payment calculator. Enter vehicle price, residual value, down payment, term, and money factor to estimate your monthly lease payment before you sign.",
    primaryKeyword: "car lease payment calculator",
    secondaryKeywords: ["lease payment calculator", "auto lease calculator", "monthly lease cost"],
    fields: [
      { id: "carPrice", label: "Vehicle price", type: "number", unit: "$", required: true, span: 1, min: 0 },
      { id: "residualPercent", label: "Residual value", type: "number", unit: "%", required: true, span: 1, min: 0 },
      { id: "downPayment", label: "Down payment", type: "number", unit: "$", required: false, span: 1, min: 0 },
      { id: "leaseMonths", label: "Lease term", type: "number", unit: "months", required: true, span: 1, min: 1 },
      { id: "moneyFactor", label: "Money factor", type: "number", unit: "", required: false, span: 2, min: 0, step: 0.0001, defaultValue: 0.0025, helpText: "Lease rate factor; roughly APR ÷ 2400. Defaults to 0.0025." },
    ],
    results: [
      { id: "monthlyPayment", label: "Monthly payment", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
    ],
    formula: "payment = depreciation + finance charge",
    formulaExplanation: "A lease payment has two parts. The depreciation portion spreads the value the car loses during the lease over the term: it is the price minus your down payment minus the residual value the car is expected to keep, divided by the number of months. The finance charge is rent on the money tied up, calculated by multiplying the sum of the starting and residual balances by the money factor. Adding the two gives the monthly payment.",
    explanation: "Leasing lets you pay for the portion of a car you use rather than the whole vehicle, and this car lease payment calculator shows what that monthly figure will be before you sit down at the dealership. Enter the vehicle price, the residual value as a percentage, any down payment, the lease term in months, and the money factor, and it returns the estimated monthly payment.\n\nUnderstanding how a lease payment is built protects you from surprises. Unlike a loan, where you finance the full price, a lease charges you mainly for depreciation, the value the car loses while you drive it. A high residual value means the car holds its worth, leaving less to pay, which is why some models lease far more cheaply than others despite a similar sticker price. The money factor, meanwhile, is simply the interest rate of the lease dressed in unfamiliar clothing.\n\nSeeing the payment broken into its causes lets you shop smarter. You can test how a larger down payment lowers the monthly figure, how a higher residual makes a lease more attractive, or how a steeper money factor quietly adds cost. Because the depreciation and finance portions respond differently to each input, adjusting them one at a time reveals which lever actually moves your payment, helping you negotiate the terms that matter and recognise a genuinely good lease deal from a merely cheap-looking one.",
    example: { inputs: { carPrice: 35000, residualPercent: 55, downPayment: 3000, leaseMonths: 36, moneyFactor: 0.0025 }, explanation: "Residual = $19,250; depreciation = (35000−3000−19250)/36 ≈ $354.17; finance = (35000−3000+19250)×0.0025 ≈ $128.13; payment ≈ $482.29/month." },
    faqs: [
      {
        question: "What is a residual value?",
        answer: "The residual value is what the leasing company expects the car to be worth at the end of the lease, usually expressed as a percentage of the original price. It is set by the lessor, not negotiated. A higher residual means the car depreciates less during your lease, so you pay for a smaller drop in value and your monthly payment is lower, which is why cars that hold value well often lease cheaply.",
      },
      {
        question: "What is a money factor and how does it relate to APR?",
        answer: "The money factor is the lease equivalent of an interest rate, written as a small decimal like 0.0025. To approximate the equivalent annual percentage rate, multiply the money factor by 2400. So 0.0025 corresponds to roughly a 6 percent APR. A lower money factor means cheaper financing on the lease, so it is worth asking the dealer for the exact figure they are using in your quote.",
      },
      {
        question: "Does a bigger down payment always help?",
        answer: "A larger down payment, sometimes called a capitalized cost reduction, lowers your monthly payment by reducing both the depreciation and finance portions. However, if the car is stolen or totaled early in the lease, that upfront money is generally not refunded, so you risk losing it. Many advisers suggest keeping the down payment modest and instead prioritising a lower price and money factor for the best overall value.",
      },
      {
        question: "What does this estimate leave out?",
        answer: "This calculator focuses on the base monthly payment from depreciation and finance charges. Real lease quotes also add sales tax, which varies by state, plus acquisition fees, registration, documentation charges, and any dealer add-ons. There may also be mileage limits with per-mile penalties for going over and charges for excess wear at return. Treat the figure here as the core payment before taxes and fees are layered on.",
      },
      {
        question: "How can I lower my lease payment?",
        answer: "Focus on the inputs that drive the payment: negotiate a lower vehicle price, choose a model with a high residual value, and secure a low money factor through good credit or shopping around. A larger down payment reduces the monthly figure but carries risk if the car is lost. Longer terms lower the payment but keep you liable longer, so balance the monthly cost against total commitment.",
      },
    ],
    relatedCalculators: ["car-loan-calculator", "car-payment-affordability-calculator", "car-cost-per-mile-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard lease payment formula (depreciation + finance charge)",
  },
  {
    id: "car-cost-per-mile",
    slug: "car-cost-per-mile-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "Car Cost Per Mile Calculator",
    shortDescription: "Find the true cost of every mile you drive.",
    seoTitle: "Car Cost Per Mile Calculator — True Driving Cost",
    metaDescription: "Free car cost per mile calculator. Divide your total annual vehicle costs by miles driven to see the real cost of each mile for budgeting, reimbursement, or comparison.",
    primaryKeyword: "car cost per mile calculator",
    secondaryKeywords: ["cost per mile calculator", "driving cost per mile", "vehicle cost per mile"],
    fields: [
      { id: "annualCosts", label: "Total annual costs", type: "number", unit: "$", required: true, span: 1, min: 0, helpText: "Fuel, insurance, maintenance, depreciation, and more." },
      { id: "annualMiles", label: "Annual miles driven", type: "number", unit: "mi/yr", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "costPerMile", label: "Cost per mile", format: "currency", currency: "USD", decimals: 4, isPrimary: true },
    ],
    formula: "cost per mile = total annual costs ÷ annual miles",
    formulaExplanation: "Cost per mile turns a lump of yearly spending into a single rate by dividing every dollar you put into the car over a year by the number of miles it carried you. Because it folds fixed costs like insurance and depreciation together with variable costs like fuel and tyres, the result reflects the whole burden of ownership spread across distance. Driving more miles lowers the per-mile figure, since fixed costs are shared over a larger base.",
    explanation: "People rarely know what driving actually costs them per mile, and this car cost per mile calculator answers that question by combining every expense of ownership into one honest rate. Enter your total annual vehicle costs and the miles you drive in a year, and it returns the cost of each mile, a number that reveals the real price of the trips you take for granted.\n\nThe figure is more revealing than fuel cost alone because owning a car involves far more than gas. Insurance, registration, maintenance, tyres, repairs, and especially depreciation all cost money whether or not you drive, and cost per mile spreads those across the distance you cover. That is why a low-mileage driver often pays a surprisingly high amount per mile: the fixed costs are shared over fewer miles, so each one carries a bigger slice.\n\nKnowing your true cost per mile helps in concrete ways. It lets you judge whether a long drive is worth it, set a fair rate when reimbursing yourself or others, compare keeping a car against ride-hailing, and decide whether a second vehicle earns its keep. Because the calculation simply divides total costs by miles, you can plug in different mileage or cost scenarios and immediately see how driving more spreads the fixed burden thinner, or how cutting an expense category lowers the rate for every mile you drive.",
    example: { inputs: { annualCosts: 9000, annualMiles: 12000 }, explanation: "$9,000 in yearly costs ÷ 12,000 miles = $0.75 per mile, covering fuel, insurance, maintenance, and depreciation combined." },
    faqs: [
      {
        question: "What costs should I include in the total?",
        answer: "Include everything the car costs you in a year: fuel or charging, insurance, registration and taxes, routine maintenance, tyres, repairs, and depreciation, which is the value the car loses. If you finance, add loan interest. The more complete your total, the more accurate the per-mile figure. Leaving out depreciation is a common mistake that makes driving look far cheaper than it truly is over time.",
      },
      {
        question: "Why is depreciation so important here?",
        answer: "Depreciation is usually the single largest cost of owning a newer car, yet it is invisible because no bill arrives for it. A car steadily loses value whether it sits or drives, and that lost value is a real cost you pay when you eventually sell or trade it. Including a yearly depreciation estimate in your total is essential for an honest cost per mile, especially for newer vehicles.",
      },
      {
        question: "Why does driving less raise my cost per mile?",
        answer: "Many car costs are fixed: insurance, registration, and depreciation happen regardless of distance. When you divide those fixed costs by fewer miles, each mile absorbs a larger share, so the per-mile rate rises. Conversely, driving more spreads the same fixed costs over more miles, lowering the rate. This is why occasional drivers sometimes find that alternatives like ride-hailing or car sharing can compete with the true cost of ownership.",
      },
      {
        question: "How can I use cost per mile for reimbursement?",
        answer: "If you drive for work or lend your car, cost per mile gives a defensible rate to charge. Multiply your rate by the miles driven for a fair reimbursement that covers wear, fuel, and depreciation rather than just gas. Note that tax authorities publish standard mileage rates that may differ from your personal cost, so check the official figure when reimbursement has tax implications for you.",
      },
      {
        question: "How does this compare to the standard mileage rate?",
        answer: "Government standard mileage rates are averages meant to approximate the cost of operating a typical vehicle, used mainly for tax deductions. Your personal cost per mile can be higher or lower depending on your car's price, fuel economy, insurance, and how many miles you drive. This calculator gives your actual figure, which is more useful for real budgeting decisions, while the standard rate is best reserved for tax purposes.",
      },
    ],
    relatedCalculators: ["fuel-cost-calculator", "car-loan-calculator", "car-lease-payment-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard cost-per-mile method",
  },
  {
    id: "tire-diameter",
    slug: "tire-diameter-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "Tire Diameter Calculator",
    shortDescription: "Find a tire's overall diameter in inches.",
    seoTitle: "Tire Diameter Calculator — Overall Diameter in Inches",
    metaDescription: "Free tire diameter calculator. Enter section width, aspect ratio, and wheel diameter to find the overall tire diameter in inches for fitment and speedometer checks.",
    primaryKeyword: "tire diameter calculator",
    secondaryKeywords: ["overall tire diameter", "tire height calculator", "tire size diameter"],
    fields: [
      { id: "widthMm", label: "Section width", type: "number", unit: "mm", required: true, span: 1, min: 0 },
      { id: "aspectRatio", label: "Aspect ratio", type: "number", unit: "%", required: true, span: 1, min: 0 },
      { id: "wheelDiameterIn", label: "Wheel diameter", type: "number", unit: "in", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "overallDiameterIn", label: "Overall diameter", format: "number", decimals: 2, unit: "in", isPrimary: true },
    ],
    formula: "diameter = wheel + 2 × (width × aspect ÷ 100) ÷ 25.4",
    formulaExplanation: "A tyre's overall diameter is the wheel it wraps plus a sidewall on the top and bottom. The sidewall height in millimetres is the section width multiplied by the aspect ratio percentage, because aspect ratio is defined as the sidewall expressed as a share of width. Dividing that height by 25.4 converts millimetres to inches, and doubling it accounts for both sidewalls before adding the wheel's own diameter, which is already given in inches.",
    explanation: "The overall diameter of a tyre decides whether it fits your car and whether your speedometer stays accurate, and this tire diameter calculator computes it straight from the numbers on the sidewall. Enter the section width in millimetres, the aspect ratio as a percentage, and the wheel diameter in inches, and it returns the tyre's overall diameter in inches, the single dimension that matters most when comparing sizes.\n\nThat figure carries a lot of weight. Overall diameter sets how tall the tyre stands, which affects ground clearance, fender gap, and the effective gearing that determines how hard your engine works at a given speed. It also drives speedometer and odometer accuracy, because those instruments assume a specific rolling distance per revolution. Fit a tyre of a different diameter and every reported speed and distance shifts, subtly but consistently.\n\nThe calculation follows the standard P-metric convention that every tyre size encodes. The first number is the width, the middle number is the aspect ratio describing sidewall height as a percentage of that width, and the last number is the wheel diameter. Multiplying width by aspect ratio gives the sidewall, and adding one at the top and one at the bottom of the wheel yields the overall diameter. Whether you are plus-sizing wheels, fitting a taller all-terrain tyre, or simply checking that a replacement matches your originals, seeing the diameter lets you keep handling and instrument accuracy intact rather than discovering a mismatch after the tyres are mounted.",
    example: { inputs: { widthMm: 225, aspectRatio: 45, wheelDiameterIn: 17 }, explanation: "Sidewall = 225 × 45 ÷ 100 = 101.25 mm; diameter = 17 + 2 × 101.25 ÷ 25.4 ≈ 24.97 in." },
    faqs: [
      {
        question: "How do I read the numbers in a tire size?",
        answer: "In a size like 225/45R17, the 225 is the section width in millimetres, the 45 is the aspect ratio meaning the sidewall is 45 percent of the width, the R marks radial construction, and the 17 is the wheel diameter in inches. Enter the width, aspect ratio, and wheel diameter into this calculator and it returns the tyre's overall diameter, the figure you actually need for fitment.",
      },
      {
        question: "Why does overall diameter matter for my speedometer?",
        answer: "Your speedometer and odometer are calibrated to the rolling distance of the original tyre, which depends on its diameter. A larger diameter travels farther per revolution, making the speedometer read low and the odometer undercount, while a smaller diameter does the opposite. Keeping the new diameter within a few percent of the original preserves accuracy and avoids confusing the electronic systems that rely on wheel speed data.",
      },
      {
        question: "How much can overall diameter safely change?",
        answer: "A common guideline is to keep the overall diameter within about three percent of the original so speedometer error stays small and clearance is preserved. Larger jumps can cause rubbing against the fender or suspension, alter gearing noticeably, and throw off speed readings. When plus-sizing, people deliberately pair a wider tyre with a lower aspect ratio and larger wheel to keep the overall diameter close to stock.",
      },
      {
        question: "Does a lower aspect ratio always mean a smaller diameter?",
        answer: "Not necessarily, because diameter depends on width, aspect ratio, and wheel size together. A lower aspect ratio shortens the sidewall, but if it is paired with a larger wheel or wider tyre, the overall diameter can stay the same or even grow. That is exactly how plus-sizing works: a bigger wheel with a shorter sidewall keeps the overall diameter constant while changing the look and handling feel.",
      },
      {
        question: "Why convert the sidewall from millimetres to inches?",
        answer: "Tyre widths and sidewall heights are specified in millimetres, but wheel diameters and overall tyre diameters are conventionally quoted in inches in many markets. To add the sidewall to the wheel, both must share a unit, so the sidewall height is divided by 25.4, the number of millimetres in an inch. This mixed convention is why the calculation looks slightly awkward, but it produces a diameter in the inches that fitment charts use.",
      },
    ],
    relatedCalculators: ["speedometer-error-calculator", "mpg-calculator", "fuel-cost-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard P-metric tire sizing",
  },
  {
    id: "speedometer-error",
    slug: "speedometer-error-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "Speedometer Error Calculator",
    shortDescription: "See true speed after a tire size change.",
    seoTitle: "Speedometer Error Calculator — True Speed After Tire Change",
    metaDescription: "Free speedometer error calculator. Enter original and new tire diameters and your indicated speed to find your true speed and the percentage speedometer error.",
    primaryKeyword: "speedometer error calculator",
    secondaryKeywords: ["speedometer calibration calculator", "tire size speed error", "true speed calculator"],
    fields: [
      { id: "originalDiameterIn", label: "Original tire diameter", type: "number", unit: "in", required: true, span: 1, min: 0 },
      { id: "newDiameterIn", label: "New tire diameter", type: "number", unit: "in", required: true, span: 1, min: 0 },
      { id: "indicatedSpeed", label: "Indicated speed", type: "number", unit: "mph", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "actualSpeed", label: "Actual speed", format: "number", decimals: 2, unit: "mph", isPrimary: true },
      { id: "errorPercent", label: "Speedometer error", format: "number", decimals: 2, unit: "%", isPrimary: false },
    ],
    formula: "actual = indicated × new diameter ÷ original diameter",
    formulaExplanation: "A speedometer counts wheel revolutions and assumes each turn covers the rolling distance of the original tyre. Fit a tyre of a different diameter and each revolution covers a different distance, so the true speed scales by the ratio of the new diameter to the original. Multiplying the indicated speed by that ratio gives the actual speed, and comparing the two as a percentage of the indicated reading gives the speedometer error introduced by the change.",
    explanation: "When you fit tyres of a different size, your speedometer keeps counting revolutions as if nothing changed, and the result is a reading that no longer matches reality, which this speedometer error calculator quantifies. Enter your original tyre diameter, the new tyre diameter, and the speed shown on your dash, and it returns your true speed along with the percentage error the change introduced.\n\nThe reason the error appears is mechanical and unavoidable. A speedometer measures how fast the wheels turn and multiplies by the rolling distance of one revolution, a distance baked in for the factory tyre. A larger tyre covers more ground per turn, so you are actually going faster than the dash shows, while a smaller tyre covers less, so you are going slower than indicated. The instrument never learns about the swap on its own.\n\nThis matters for more than curiosity. Driving faster than your speedometer suggests can quietly earn speeding tickets, while an undercounting odometer distorts fuel economy figures, service intervals, and resale mileage. Fitting taller off-road tyres or plus-sizing wheels are the usual culprits. By showing both the true speed and the error percentage, the calculator tells you exactly how far off you are and whether the change is small enough to live with or large enough to warrant recalibrating the speedometer through a tuner or dealer.",
    example: { inputs: { originalDiameterIn: 25, newDiameterIn: 26, indicatedSpeed: 60 }, explanation: "60 × 26 ÷ 25 = 62.4 mph true speed, a 4% error, so the dash reads 60 while you are actually doing 62.4." },
    faqs: [
      {
        question: "Why does a bigger tire make my speedometer read low?",
        answer: "A larger tyre has a bigger circumference, so it covers more distance with each revolution. Your speedometer counts revolutions and assumes the original tyre's smaller circumference, so it underestimates how far you travel per turn and therefore shows a speed lower than your true speed. The bigger the diameter increase, the larger the gap, which is why lifted trucks with tall tyres often read several miles per hour slow.",
      },
      {
        question: "Where do I find my tire's actual diameter?",
        answer: "You can measure it directly with a tape from the ground to the top of the tyre, or calculate it from the sidewall size using width, aspect ratio, and wheel diameter. A tyre diameter calculator does this from the printed size. Using the true measured or calculated diameters for both the original and new tyres gives the most accurate speedometer error, since published sizes are nominal approximations.",
      },
      {
        question: "Is a small speedometer error a problem?",
        answer: "Manufacturers typically build in a slight bias so the speedometer reads a little high, keeping drivers legal, and small errors of a percent or two are generally harmless. Larger errors matter more: reading low can lead to unintended speeding, and any error skews your odometer, affecting recorded mileage, warranty limits, and fuel economy math. If the error exceeds a few percent, consider recalibrating the speedometer.",
      },
      {
        question: "Does speedometer error affect my odometer too?",
        answer: "Yes. The odometer relies on the same revolution count as the speedometer, so any diameter change distorts recorded distance by the same ratio. Larger tyres make the odometer undercount miles, which can make a vehicle appear to have driven less than it has, while smaller tyres overcount. This affects service intervals, fuel economy calculations, mileage-based warranties, and the mileage shown at resale, so it is worth accounting for.",
      },
      {
        question: "Can I fix a large speedometer error?",
        answer: "Yes. On many modern vehicles the speedometer can be recalibrated electronically using a programmer, tuner, or dealer service that tells the computer the new tyre size. Some aftermarket modules do the same for older systems. Recalibrating restores accurate speed and distance readings after a significant tyre change. If recalibration is not practical, at least know your error percentage so you can mentally adjust the reading while driving.",
      },
    ],
    relatedCalculators: ["tire-diameter-calculator", "mpg-calculator", "trip-fuel-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard tire circumference and speedometer relationship",
  },
  {
    id: "trip-fuel",
    slug: "trip-fuel-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "Trip Fuel Calculator",
    shortDescription: "Estimate the gallons a trip will need.",
    seoTitle: "Trip Fuel Calculator — Gallons Needed for a Trip",
    metaDescription: "Free trip fuel calculator. Enter trip distance and your vehicle's MPG to find how many gallons of fuel the journey needs, for planning stops and budgeting.",
    primaryKeyword: "trip fuel calculator",
    secondaryKeywords: ["fuel needed calculator", "gallons for a trip", "road trip fuel calculator"],
    fields: [
      { id: "distanceMiles", label: "Trip distance", type: "number", unit: "mi", required: true, span: 1, min: 0 },
      { id: "mpg", label: "Fuel economy", type: "number", unit: "mpg", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "gallonsNeeded", label: "Gallons needed", format: "number", decimals: 2, unit: "gal", isPrimary: true },
    ],
    formula: "gallons = distance ÷ MPG",
    formulaExplanation: "Miles per gallon states exactly how far your vehicle travels on one gallon of fuel, so dividing the trip distance by that figure reverses the relationship and returns the number of gallons required to cover the distance. The larger your MPG, the fewer gallons a given trip demands, and the longer the distance, the more fuel it needs. The calculation assumes steady real-world economy across the whole journey.",
    explanation: "Before a long drive it helps to know how much fuel the trip will actually swallow, and this trip fuel calculator gives that figure from two numbers you already know. Enter the distance you plan to travel and your vehicle's fuel economy in miles per gallon, and it returns the gallons the journey needs, so you can plan fuel stops and budget with confidence.\n\nKnowing gallons in advance is practically useful in several ways. It tells you whether a single tank will cover the route or whether you need to plan refuelling stops, which matters on remote stretches where stations are sparse. It also lets you multiply by the local fuel price to estimate the trip's cost, and it helps you pack the right expectations for how often you will pull over on a road trip with children or a schedule to keep.\n\nThe math is deliberately simple: distance divided by miles per gallon equals gallons. Because MPG is the distance one gallon carries you, dividing your total distance by it counts how many gallons that distance consumes. For the most realistic estimate, use the fuel economy you actually observe rather than the optimistic window-sticker figure, since highway ratings assume ideal conditions. Loaded roof boxes, mountain grades, headwinds, and heavy traffic all raise consumption, so if your route is demanding, nudge the MPG down a little and the calculator will reflect the extra fuel you are likely to burn.",
    example: { inputs: { distanceMiles: 450, mpg: 30 }, explanation: "450 miles ÷ 30 MPG = 15 gallons needed for the trip, before any margin for terrain or traffic." },
    faqs: [
      {
        question: "Which MPG figure should I use?",
        answer: "Use the fuel economy you actually achieve rather than the manufacturer's rating, since real-world driving rarely matches the lab test. If most of the trip is highway, a highway rating is reasonable; if it involves city traffic, hills, or heavy loads, use a lower figure. Tracking your MPG over a few tanks gives the most reliable number, and using it here produces a fuel estimate you can trust for planning.",
      },
      {
        question: "Should I add a safety margin to the gallons?",
        answer: "It is wise to. The calculation assumes steady economy over the whole trip, but real conditions vary, and running a tank to empty is risky. Many drivers plan to refuel with a quarter tank remaining. Adding roughly ten to fifteen percent to the estimated gallons builds in a buffer for detours, traffic, terrain, and the difference between rated and actual economy, so you are unlikely to be caught short.",
      },
      {
        question: "How do I turn gallons into a trip cost?",
        answer: "Multiply the gallons needed by the price per gallon you expect to pay. For example, 15 gallons at four dollars a gallon costs sixty dollars. If prices vary along your route, use an average or the highest likely price to stay on the safe side. A dedicated fuel cost calculator can do this in one step, combining distance, economy, and price into a total for you.",
      },
      {
        question: "Will my actual fuel use match this estimate?",
        answer: "It will be close if your MPG figure is realistic, but expect some variation. Terrain, weather, traffic, air conditioning, cargo weight, and driving style all shift consumption, sometimes noticeably. Long climbs and headwinds increase fuel use, while steady highway cruising decreases it. The estimate is a solid planning baseline; for a long or remote trip, err on the side of carrying more fuel than the bare calculation suggests.",
      },
      {
        question: "Does this work for electric vehicles?",
        answer: "This calculator is built for fuel measured in gallons, so it does not directly apply to electric cars, which measure energy in kilowatt-hours. To estimate an EV's needs, divide the trip distance by the car's efficiency in miles per kilowatt-hour to get the energy required. An EV range calculator is better suited to that task, since it accounts for battery capacity and efficiency rather than gallons of fuel.",
      },
    ],
    relatedCalculators: ["fuel-cost-calculator", "mpg-calculator", "mpg-to-l100km-converter"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "U.S. EPA fuel economy",
    sourceUrl: "https://www.fueleconomy.gov/",
  },
  {
    id: "oil-change-cost",
    slug: "oil-change-cost-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "Oil Change Cost Calculator",
    shortDescription: "Estimate your yearly oil change spending.",
    seoTitle: "Oil Change Cost Calculator — Annual Oil Change Spending",
    metaDescription: "Free oil change cost calculator. Enter annual mileage, oil change interval, and cost per change to see how many changes you need per year and the total annual cost.",
    primaryKeyword: "oil change cost calculator",
    secondaryKeywords: ["annual oil change cost", "oil change interval calculator", "car maintenance cost calculator"],
    fields: [
      { id: "annualMiles", label: "Annual miles driven", type: "number", unit: "mi/yr", required: true, span: 1, min: 0 },
      { id: "intervalMiles", label: "Oil change interval", type: "number", unit: "mi", required: false, span: 1, min: 1, defaultValue: 5000, helpText: "Miles between changes. Defaults to 5,000." },
      { id: "costPerChange", label: "Cost per change", type: "number", unit: "$", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "changesPerYear", label: "Changes per year", format: "number", decimals: 2, unit: "/yr", isPrimary: true },
      { id: "annualCost", label: "Annual oil change cost", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "changes = miles ÷ interval  ·  annual cost = changes × cost each",
    formulaExplanation: "The number of oil changes you need in a year is simply how many times your annual mileage fills up the interval between changes, found by dividing annual miles by the interval in miles. Multiplying that count by the cost of a single change gives the yearly spending on oil changes. A longer interval means fewer changes and lower cost, while more miles driven pushes both the change count and the annual bill upward.",
    explanation: "Oil changes are a small recurring cost that quietly adds up, and this oil change cost calculator shows the yearly total so it stops being a surprise in your maintenance budget. Enter the miles you drive in a year, how many miles you go between changes, and the cost of a single change, and it returns both how many changes you need annually and what they cost in total.\n\nSeeing the number laid out helps in a few ways. It lets you budget maintenance realistically instead of treating each visit as a one-off, and it makes the trade-offs visible. A shorter interval means more frequent changes and a higher annual bill, while a longer interval, often possible with synthetic oil, reduces the number of changes even if each one costs more. The calculator lets you weigh a cheaper conventional oil changed often against a pricier synthetic changed rarely.\n\nThe calculation is straightforward: annual miles divided by the interval gives the number of changes, and multiplying by the cost of each gives the yearly total. Use the interval your manufacturer recommends or the one your oil type supports, since intervals vary widely between conventional and full synthetic oils. Whether you are comparing doing it yourself against a quick-lube shop, deciding if a synthetic upgrade pays off, or simply planning your annual car expenses, having the yearly figure makes the decision concrete rather than guesswork.",
    example: { inputs: { annualMiles: 15000, intervalMiles: 5000, costPerChange: 60 }, explanation: "15,000 ÷ 5,000 = 3 changes per year; 3 × $60 = $180 spent annually on oil changes." },
    faqs: [
      {
        question: "How often should I change my oil?",
        answer: "It depends on your vehicle and oil type. Older guidance of every 3,000 miles applies mostly to conventional oil, while many modern engines running full synthetic can go 7,500 to 10,000 miles or more between changes. Always follow your owner's manual, which sets the interval for your specific engine. Severe conditions like frequent short trips, towing, or extreme temperatures may call for more frequent changes than the standard interval.",
      },
      {
        question: "Does synthetic oil save money overall?",
        answer: "It can, despite costing more per change. Synthetic oil typically allows much longer intervals, so although each change is pricier, you need fewer of them per year. Enter your synthetic interval and cost here and compare the annual total against conventional oil changed more often. Synthetic also offers better protection in extreme temperatures, which many owners value beyond the raw cost comparison, especially for newer or turbocharged engines.",
      },
      {
        question: "Should I count filter and labor in the cost?",
        answer: "Yes. Enter the full price you actually pay for a change, including the oil filter, labor if a shop does it, and any shop fees or taxes. If you change your own oil, include the cost of oil and a filter plus disposal. Using the complete per-change cost ensures the annual total reflects what you really spend rather than just the price of the oil itself.",
      },
      {
        question: "Why is the interval set to 5,000 miles by default?",
        answer: "Five thousand miles is a common middle-ground interval that suits many modern vehicles using semi-synthetic or synthetic blends, so it serves as a reasonable default. However, it is only a starting point. Your actual interval should come from your owner's manual or the oil manufacturer's guidance, which may be shorter for conventional oil or longer for full synthetic. Adjust the interval field to match your real maintenance schedule.",
      },
      {
        question: "How does mileage affect my annual oil change cost?",
        answer: "The more miles you drive, the more often you hit the interval, so the number of changes and the annual cost both rise in direct proportion. A high-mileage driver covering 20,000 miles a year needs far more changes than someone driving 6,000. This is why oil changes, though individually cheap, become a meaningful line item for commuters and rideshare drivers who rack up distance quickly.",
      },
    ],
    relatedCalculators: ["car-cost-per-mile-calculator", "fuel-cost-calculator", "car-loan-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard vehicle maintenance interval math",
  },
  {
    id: "car-payment-affordability",
    slug: "car-payment-affordability-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "Car Payment Affordability Calculator",
    shortDescription: "See how much car payment you can afford.",
    seoTitle: "Car Payment Affordability Calculator — Max Monthly Payment",
    metaDescription: "Free car payment affordability calculator. Enter your monthly income and a target percentage to find the maximum car payment that fits your budget comfortably.",
    primaryKeyword: "car payment affordability calculator",
    secondaryKeywords: ["how much car payment can i afford", "car affordability calculator", "max car payment calculator"],
    fields: [
      { id: "monthlyIncome", label: "Monthly income", type: "number", unit: "$", required: true, span: 1, min: 0, helpText: "Gross or take-home; be consistent." },
      { id: "percentOfIncome", label: "Percent of income", type: "number", unit: "%", required: false, span: 1, min: 0, defaultValue: 15, helpText: "Share to spend on the payment. Defaults to 15%." },
    ],
    results: [
      { id: "maxCarPayment", label: "Max car payment", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
    ],
    formula: "max payment = monthly income × percent ÷ 100",
    formulaExplanation: "The affordable payment is a chosen share of your monthly income, so multiplying your income by the target percentage and dividing by 100 converts that percentage into a dollar ceiling. The idea rests on a budgeting rule of thumb that car payments should stay within a modest slice of income to leave room for fuel, insurance, and everything else. A lower percentage yields a more conservative, safer payment ceiling.",
    explanation: "It is easy to fall in love with a car whose payment quietly strains your budget, and this car payment affordability calculator guards against that by translating a sensible budgeting rule into a firm dollar ceiling. Enter your monthly income and the share you are willing to devote to a car payment, and it returns the maximum monthly payment you can comfortably carry.\n\nThe approach reflects a widely used guideline that your car payment should occupy only a modest portion of your income, often cited around ten to fifteen percent of take-home pay. Staying within that band leaves room for the other costs of driving, insurance, fuel, maintenance, and registration, which the payment itself does not cover, as well as the rest of your living expenses. Shopping by the sticker price or the payment a dealer offers, rather than by what your income supports, is how people end up overextended.\n\nThe math is simple: your income multiplied by your chosen percentage gives the ceiling. Setting the percentage lower produces a more cautious limit, which is prudent if you carry other debts or want a bigger savings cushion. Once you know the maximum payment, you can work backwards with a loan calculator to see what vehicle price that supports at a given rate and term. Starting from what you can afford, rather than from the car you want, keeps the whole purchase grounded in your real financial picture and reduces the risk of a payment that pinches every month.",
    example: { inputs: { monthlyIncome: 5000, percentOfIncome: 15 }, explanation: "$5,000 × 15 ÷ 100 = $750, the maximum monthly car payment this budget rule suggests." },
    faqs: [
      {
        question: "What percentage of income should go to a car payment?",
        answer: "A common guideline suggests keeping the car payment at or below ten to fifteen percent of your monthly take-home pay. More conservative advice caps total car costs, including insurance and fuel, at around twenty percent. The right figure depends on your other obligations and goals. If you carry significant debt or want to save aggressively, choose a lower percentage here to keep the payment ceiling comfortably within reach.",
      },
      {
        question: "Should I use gross or take-home income?",
        answer: "Using take-home pay, the amount that actually lands in your account after taxes and deductions, gives a more realistic picture of what you can spend, since that is the money available for bills. Some guidelines reference gross income, but those tend to allow larger payments. Whichever you choose, be consistent and remember that the percentage guideline assumes the payment sits alongside all your other living costs.",
      },
      {
        question: "Does this include insurance and fuel?",
        answer: "No, this calculator estimates only the loan or lease payment itself. Owning a car also costs insurance, fuel, maintenance, registration, and taxes, which together can rival or exceed the payment. That is why keeping the payment to a modest share of income matters: it leaves headroom for those extras. Budget for the full cost of ownership, not just the monthly payment, before committing to a vehicle.",
      },
      {
        question: "How do I turn a max payment into a car price?",
        answer: "Once you know your maximum monthly payment, use a car loan calculator to work backwards. Enter the payment, an interest rate, and a term, and it reveals the loan amount that payment supports. Add your down payment and trade-in to that loan to get the total car price within reach. This links your income-based budget to an actual price range you can shop within confidently.",
      },
      {
        question: "Is a longer loan term a good way to afford more car?",
        answer: "Stretching the term lowers the monthly payment, which can bring a pricier car within your percentage limit, but it comes at a cost. Longer loans accrue more total interest and keep you owing money for years, sometimes longer than you keep the car. It also raises the risk of owing more than the car is worth. Prefer fitting the car to your budget over stretching the term to fit the car.",
      },
    ],
    relatedCalculators: ["car-loan-calculator", "car-lease-payment-calculator", "car-cost-per-mile-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard budgeting guideline (percent of income)",
  },
  {
    id: "ev-range",
    slug: "ev-range-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "EV Range Calculator",
    shortDescription: "Estimate an electric car's driving range.",
    seoTitle: "EV Range Calculator — Electric Car Range from Battery Size",
    metaDescription: "Free EV range calculator. Enter battery capacity in kWh and efficiency in miles per kWh to estimate how far an electric car can travel on a full charge.",
    primaryKeyword: "ev range calculator",
    secondaryKeywords: ["electric car range calculator", "ev battery range", "electric vehicle range calculator"],
    fields: [
      { id: "batteryKwh", label: "Battery capacity", type: "number", unit: "kWh", required: true, span: 1, min: 0 },
      { id: "efficiencyMilesPerKwh", label: "Efficiency", type: "number", unit: "mi/kWh", required: false, span: 1, min: 0, step: 0.1, defaultValue: 3.5, helpText: "Miles per kWh. Defaults to 3.5." },
    ],
    results: [
      { id: "rangeMiles", label: "Estimated range", format: "number", decimals: 1, unit: "mi", isPrimary: true },
    ],
    formula: "range = battery capacity × efficiency",
    formulaExplanation: "An electric car's range is how far its stored energy can carry it, so multiplying the usable battery capacity in kilowatt-hours by the efficiency in miles per kilowatt-hour gives the distance on a full charge. Efficiency states how many miles each kilowatt-hour delivers, and battery capacity states how many kilowatt-hours are on board, so their product is total miles. A bigger battery or higher efficiency both extend the range this way.",
    explanation: "Range anxiety is often just uncertainty, and this EV range calculator replaces it with a concrete estimate from two numbers that define an electric car's reach. Enter the battery capacity in kilowatt-hours and the efficiency in miles per kilowatt-hour, and it returns how far the car can travel on a full charge, so you can judge whether a given model suits your driving.\n\nThe estimate is useful whether you are shopping for an EV or planning a journey in one you own. Battery capacity is like the size of the fuel tank, while efficiency is the electric equivalent of miles per gallon, telling you how far each unit of energy carries you. Multiplying the two gives range, and seeing it laid out lets you compare a large battery with modest efficiency against a smaller battery in a very efficient car, which can end up neck and neck.\n\nReal-world range depends heavily on conditions, and efficiency is where they show up. Cold weather, high speeds, hilly terrain, running the heater or air conditioning, and heavy loads all lower miles per kilowatt-hour, sometimes dramatically in winter. For a realistic figure, use an efficiency number that reflects your climate and driving rather than the best-case rating from a mild test. By lowering the efficiency input to match harsh conditions, you can see a conservative range you can actually count on, which is far more useful for planning than an optimistic headline number.",
    example: { inputs: { batteryKwh: 75, efficiencyMilesPerKwh: 3.5 }, explanation: "75 kWh × 3.5 mi/kWh = 262.5 miles of estimated range on a full charge under average conditions." },
    faqs: [
      {
        question: "What is a typical EV efficiency in miles per kWh?",
        answer: "Most electric cars achieve roughly 3 to 4 miles per kilowatt-hour in mixed driving, with efficient models exceeding 4 and larger, heavier vehicles falling below 3. Efficiency drops in cold weather, at highway speeds, and with heavy loads or climate control running. Check your car's display or the EPA rating for a baseline, and reduce it somewhat if you often drive in demanding conditions for a realistic range estimate.",
      },
      {
        question: "Should I use total or usable battery capacity?",
        answer: "Use the usable capacity if you know it, since manufacturers reserve a buffer of the total battery to protect longevity, and only the usable portion actually powers the car. Published range figures are based on usable capacity. If only the total capacity is listed, your range estimate will be slightly optimistic. Where possible, enter the usable kilowatt-hours for the most accurate result that matches real driving.",
      },
      {
        question: "Why does cold weather reduce EV range so much?",
        answer: "Cold temperatures slow the battery's chemistry, reducing the energy it can deliver, and heating the cabin draws significant power directly from the battery rather than from waste engine heat as in a gas car. Together these can cut winter range by twenty to forty percent. Preconditioning the car while plugged in and using seat heaters over cabin heat help, but you should still plan for reduced range in cold months.",
      },
      {
        question: "Does driving fast lower my range?",
        answer: "Yes, considerably. Aerodynamic drag rises sharply with speed, so sustained highway driving at high speed consumes far more energy per mile than city or moderate cruising. This is the opposite of a gas car, which is often most efficient on the highway. To maximise EV range on a long trip, moderating your speed makes a noticeable difference, sometimes adding many miles compared with driving at the fastest legal pace.",
      },
      {
        question: "How does this relate to charging time and cost?",
        answer: "Range tells you how far a full charge goes, but charging time depends on the charger's power and the battery size, while charging cost depends on your electricity rate and the car's efficiency. To estimate cost per mile, divide your electricity rate by the efficiency in miles per kilowatt-hour. Range, charging speed, and cost are three separate questions, and this calculator answers the first: how far you can go on a charge.",
      },
    ],
    relatedCalculators: ["ev-savings-calculator", "mpg-calculator", "trip-fuel-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard EV range estimation (capacity × efficiency)",
  },
  {
    id: "horsepower-to-torque",
    slug: "horsepower-to-torque-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "Horsepower to Torque Calculator",
    shortDescription: "Convert horsepower to torque at a given RPM.",
    seoTitle: "Horsepower to Torque Calculator — HP to Lb-Ft at RPM",
    metaDescription: "Free horsepower to torque calculator. Enter horsepower and engine RPM to find torque in pound-feet using the standard 5252 constant relating power and rotation.",
    primaryKeyword: "horsepower to torque calculator",
    secondaryKeywords: ["hp to torque calculator", "torque from horsepower", "convert horsepower to torque"],
    fields: [
      { id: "horsepower", label: "Horsepower", type: "number", unit: "hp", required: true, span: 1, min: 0 },
      { id: "rpm", label: "Engine speed", type: "number", unit: "rpm", required: true, span: 1, min: 1 },
    ],
    results: [
      { id: "torqueLbFt", label: "Torque", format: "number", decimals: 2, unit: "lb-ft", isPrimary: true },
    ],
    formula: "torque = horsepower × 5252 ÷ RPM",
    formulaExplanation: "Horsepower measures the rate of doing work, which combines how much twisting force an engine makes, the torque, with how fast it spins, the RPM. Rearranging the relationship for torque means multiplying horsepower by the constant 5252 and dividing by engine speed. The number 5252 arises from the definition of one horsepower as 33,000 foot-pounds per minute divided by two pi, converting rotational speed in RPM into the units that make torque come out in pound-feet.",
    explanation: "Horsepower and torque describe an engine's output in two linked ways, and this horsepower to torque calculator converts between them at any engine speed using the constant that ties them together. Enter the horsepower and the RPM at which it is produced, and it returns the torque in pound-feet, letting you recover the twisting force behind a power figure.\n\nThe two measures answer different questions. Torque is the rotational force the engine applies right now, the shove you feel when you accelerate, while horsepower is the rate at which that force does work, blending torque with how fast the engine spins. Because they are related through RPM, a single horsepower number is incomplete without knowing the speed at which it occurs, which is exactly what this conversion makes explicit.\n\nThe fixed constant 5252 comes from the definition of horsepower and appears wherever the two are converted. A famous consequence is that on any dyno chart the horsepower and torque curves always cross at 5252 RPM, because that is the speed at which the two values are numerically equal. Understanding the relationship helps when comparing engines, since a high-revving engine can make big horsepower from modest torque, while a low-revving diesel makes strong torque but less peak horsepower. By plugging in a power rating and the RPM it is quoted at, you can see the torque that produces it and better understand an engine's real character.",
    example: { inputs: { horsepower: 300, rpm: 5252 }, explanation: "300 × 5252 ÷ 5252 = 300 lb-ft, illustrating that horsepower and torque are equal exactly at 5252 RPM." },
    faqs: [
      {
        question: "Where does the number 5252 come from?",
        answer: "It comes from the definition of horsepower as 33,000 foot-pounds of work per minute, combined with the geometry of rotation. Converting rotational speed in revolutions per minute into the linear terms of the horsepower definition introduces a factor of two pi, and 33,000 divided by two pi equals approximately 5252. This constant links torque in pound-feet, engine speed in RPM, and horsepower into a single consistent equation used throughout automotive engineering.",
      },
      {
        question: "Why do horsepower and torque curves cross at 5252 RPM?",
        answer: "Because horsepower equals torque times RPM divided by 5252, the two values are numerically equal precisely when RPM equals 5252. Below that speed torque is the larger number, and above it horsepower pulls ahead. This is not a coincidence but a direct result of the formula, which is why every dyno chart plotted in pound-feet and horsepower shows the two lines intersecting at exactly 5252 RPM, regardless of the engine.",
      },
      {
        question: "What is the difference between torque and horsepower?",
        answer: "Torque is the instantaneous twisting force the engine produces, felt as the push during acceleration. Horsepower is the rate at which that force does work over time, so it accounts for how fast the engine spins as well as how hard it pushes. An engine can make the same horsepower with high torque at low RPM or low torque at high RPM, which shapes how the vehicle feels to drive.",
      },
      {
        question: "Which matters more for driving, torque or horsepower?",
        answer: "Both matter, but in different ways. Torque, especially at low RPM, governs how strongly the car pulls from a stop and for towing or hauling. Horsepower, which peaks higher in the rev range, governs top speed and sustained high-speed performance. A truck prioritises low-end torque, while a sports car chases high-RPM horsepower. The best engine for you depends on whether you value effortless pulling power or high-speed capability.",
      },
      {
        question: "Can I convert torque back to horsepower?",
        answer: "Yes, the relationship works both directions. To find horsepower from torque, multiply the torque in pound-feet by the RPM and divide by 5252. This is simply the same equation rearranged. Because the constant is fixed, knowing any two of the three quantities, torque, horsepower, and RPM, lets you solve for the third, which is why dyno software can display torque and horsepower curves from the same measured data.",
      },
    ],
    relatedCalculators: ["horsepower-calculator", "gear-ratio-calculator", "engine-displacement-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard power-torque relationship (5252 constant)",
  },
];
