import type { CalculatorDefinition } from "../types";

export const automotiveWave3Calculators: CalculatorDefinition[] = [
  {
    id: "fuel-cost",
    slug: "fuel-cost-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "Fuel Cost Calculator",
    shortDescription: "Estimate the fuel cost of any trip.",
    seoTitle: "Fuel Cost Calculator — Trip Gas Cost by Distance and MPG",
    metaDescription: "Free fuel cost calculator. Enter trip distance, your vehicle's MPG, and the fuel price to see total gas cost, gallons used, and cost per mile instantly.",
    primaryKeyword: "fuel cost calculator",
    secondaryKeywords: ["gas cost calculator", "trip fuel cost", "cost per mile calculator"],
    fields: [
      { id: "distance", label: "Trip distance", type: "number", unit: "mi", required: true, span: 1, min: 0 },
      { id: "mpg", label: "Fuel economy", type: "number", unit: "mpg", required: true, span: 1, min: 0 },
      { id: "fuelPrice", label: "Fuel price", type: "number", unit: "$/gal", required: true, span: 2, min: 0, step: 0.01 },
    ],
    results: [
      { id: "totalCost", label: "Total fuel cost", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "gallons", label: "Gallons used", format: "number", decimals: 2, unit: "gal", isPrimary: false },
      { id: "costPerMile", label: "Cost per mile", format: "currency", currency: "USD", decimals: 4, isPrimary: false },
    ],
    formula: "gallons = distance ÷ mpg  ·  total cost = gallons × fuel price",
    formulaExplanation: "The trip first converts distance into fuel used by dividing miles by your vehicle's miles-per-gallon, since MPG is exactly how far each gallon carries you. Multiplying those gallons by the price per gallon gives the total spend. Dividing that spend back by distance yields cost per mile, a rate that lets you compare journeys of any length on equal footing.",
    explanation: "Knowing what a drive will cost before you turn the key makes budgeting road trips, commutes, and deliveries far easier, and this fuel cost calculator turns three familiar numbers into a clear dollar figure. You supply the distance you plan to travel, your vehicle's fuel economy in miles per gallon, and the current price of fuel, and it returns the total cost, the gallons you will burn, and the cost of every mile.\n\nFuel is one of the largest running expenses of owning a car, yet drivers rarely translate a route into an actual price until they reach the pump. Seeing the number in advance changes decisions: whether to combine errands, take the more efficient vehicle, or reconsider a long weekend drive when prices spike. Fleet operators and rideshare drivers lean on the same math to price jobs and protect their margins.\n\nThe calculation is grounded in a simple chain: distance divided by MPG gives gallons, gallons times price gives cost, and cost divided by distance gives a per-mile rate. Because each step is transparent, you can adjust any input and instantly watch the total respond, making it easy to test a cheaper fuel station, a more economical car, or a shorter route against your budget.",
    example: { inputs: { distance: 300, mpg: 30, fuelPrice: 4 }, explanation: "300 mi ÷ 30 mpg = 10 gallons; 10 × $4 = $40 total, about $0.1333 per mile." },
    faqs: [
      {
        question: "What information do I need to estimate fuel cost?",
        answer: "You need three numbers: the trip distance in miles, your vehicle's fuel economy in miles per gallon, and the current price of fuel per gallon. From these the calculator works out how many gallons the journey consumes and multiplies by price to reach the total. Your MPG can come from the trip computer, the window sticker, or your own tracking of miles driven per tank.",
      },
      {
        question: "How is cost per mile useful?",
        answer: "Cost per mile expresses fuel spending as a rate that is independent of how far you drive, so you can compare a short city hop against a long highway haul fairly. It is especially handy for rideshare drivers, couriers, and anyone reimbursing mileage, because multiplying the rate by any distance gives an instant fuel estimate without repeating the full calculation each time.",
      },
      {
        question: "Does this include maintenance or depreciation?",
        answer: "No, this tool estimates fuel cost only. Total cost of ownership also includes insurance, maintenance, tyres, depreciation, and financing, which vary widely by vehicle and driver. Treat the fuel figure as one important line in a larger budget. If you need a full running cost, add your own estimates for those other categories on top of the fuel number shown here.",
      },
      {
        question: "Why does real-world fuel cost sometimes differ from the estimate?",
        answer: "Actual MPG shifts with driving style, traffic, terrain, weather, cargo weight, and tyre pressure, so a highway rating rarely matches stop-and-go city driving. Fuel prices also change between stations and over time. For the most accurate estimate, use the MPG you personally observe over recent tanks rather than the manufacturer figure, and enter the price you expect to actually pay.",
      },
      {
        question: "How can I lower my fuel cost per trip?",
        answer: "Improving fuel economy is the most direct lever: keep tyres properly inflated, remove excess weight, drive smoothly, and avoid long idling. Choosing a shorter or less congested route cuts distance, and filling up at cheaper stations lowers the price input. Combining several errands into one trip spreads warm-engine efficiency across more miles, reducing the cost of each individual journey overall.",
      },
    ],
    relatedCalculators: ["mpg-calculator", "ev-savings-calculator", "car-loan-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "U.S. EPA fuel economy",
    sourceUrl: "https://www.fueleconomy.gov/",
  },
  {
    id: "mpg",
    slug: "mpg-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "MPG Calculator",
    shortDescription: "Work out your real fuel economy.",
    seoTitle: "MPG Calculator — Miles Per Gallon and L/100km",
    metaDescription: "Free MPG calculator. Enter miles driven and gallons used to find your true miles per gallon, the L/100km equivalent, and optional cost per mile.",
    primaryKeyword: "mpg calculator",
    secondaryKeywords: ["miles per gallon calculator", "fuel economy calculator", "mpg to l/100km"],
    fields: [
      { id: "miles", label: "Miles driven", type: "number", unit: "mi", required: true, span: 1, min: 0 },
      { id: "gallons", label: "Gallons used", type: "number", unit: "gal", required: true, span: 1, min: 0 },
      { id: "fuelPrice", label: "Fuel price (optional)", type: "number", unit: "$/gal", required: false, span: 2, min: 0, step: 0.01, helpText: "Add a price to also see cost per mile." },
    ],
    results: [
      { id: "mpg", label: "Fuel economy", format: "number", decimals: 2, unit: "mpg", isPrimary: true },
      { id: "lPer100km", label: "In L/100km", format: "number", decimals: 2, unit: "L/100km", isPrimary: false },
      { id: "costPerMile", label: "Cost per mile", format: "currency", currency: "USD", decimals: 4, isPrimary: false },
    ],
    formula: "MPG = miles ÷ gallons  ·  L/100km = 235.215 ÷ MPG",
    formulaExplanation: "Miles per gallon is simply the distance covered divided by the fuel consumed, giving the average reach of each gallon over the tank you measured. The metric equivalent inverts the idea, reporting litres needed to travel 100 kilometres, so the fixed factor 235.215 converts between the two. If you add a fuel price, dividing it by MPG yields the fuel cost of a single mile.",
    explanation: "Your car's window-sticker MPG is an estimate, but the number that matters is the one you actually achieve, and this MPG calculator gives it to you from two figures you can read off at the pump. Enter the miles driven on a tank and the gallons it took to refill, and you get true miles per gallon, the metric L/100km equivalent, and, if you add a fuel price, the cost of each mile.\n\nMeasuring real fuel economy reveals things a factory rating cannot. It shows how your commute, your right foot, and your maintenance habits affect efficiency, and it flags problems early: a sudden drop in MPG can signal underinflated tyres, a dragging brake, or a fouled sensor long before a warning light appears. Tracking it tank after tank turns a vague sense of thirst into hard data.\n\nThe method is straightforward and reliable. Fill the tank, reset the trip meter, drive normally, then refill and record both the miles and the gallons added. Dividing distance by fuel gives MPG, and the calculator handles the metric conversion using the standard 235.215 factor so you can compare against European ratings. Doing this over several tanks smooths out the noise and produces a dependable picture of how your vehicle really performs.",
    example: { inputs: { miles: 300, gallons: 10, fuelPrice: 4 }, explanation: "300 mi ÷ 10 gal = 30 MPG, about 7.84 L/100km, and $0.1333 per mile at $4/gal." },
    faqs: [
      {
        question: "How do I measure miles and gallons accurately?",
        answer: "Fill the tank completely and reset your trip odometer. Drive as you normally would, then return to the same pump and fill up again to the first click. The trip odometer shows miles driven, and the pump shows the gallons added to refill. Using the same pump and fill level each time keeps the measurement consistent, which matters far more than any single tank's exact reading.",
      },
      {
        question: "What is a good MPG figure?",
        answer: "It depends heavily on the vehicle class. A compact hybrid may exceed 50 MPG, an efficient sedan sits around 30 to 40, while large trucks and SUVs often fall between 15 and 25. Rather than chasing a universal target, track your own vehicle over time and watch for changes. A steady figure is healthy; a falling one usually points to a maintenance issue worth investigating.",
      },
      {
        question: "How does MPG relate to L/100km?",
        answer: "They describe the same efficiency from opposite directions. MPG measures distance per unit of fuel, so higher is better, while L/100km measures fuel per fixed distance, so lower is better. Because the relationship is reciprocal rather than linear, you convert with the fixed factor 235.215 divided by MPG. This calculator shows both, which is handy when comparing a US-rated car with a European specification.",
      },
      {
        question: "Why does my MPG change from tank to tank?",
        answer: "Fuel economy responds to how and where you drive. Cold weather, short trips, heavy traffic, hills, roof racks, extra cargo, and aggressive acceleration all lower MPG, while steady highway cruising raises it. Tyre pressure and engine condition matter too. Because of this variation, a single tank can mislead. Averaging several consecutive tanks gives a much more reliable picture of your true fuel economy.",
      },
      {
        question: "Can I calculate cost per mile here too?",
        answer: "Yes. The fuel price field is optional, but if you enter the price you paid per gallon, the calculator divides it by your MPG to show the fuel cost of every mile you drive. That per-mile figure is useful for budgeting, comparing vehicles, or setting mileage reimbursement rates. Leave the price blank and the tool simply reports MPG and the L/100km equivalent without a cost.",
      },
    ],
    relatedCalculators: ["fuel-cost-calculator", "ev-savings-calculator", "tire-size-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "U.S. EPA fuel economy",
    sourceUrl: "https://www.fueleconomy.gov/",
  },
  {
    id: "ev-savings",
    slug: "ev-savings-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "EV Savings Calculator",
    shortDescription: "Compare EV and gas running costs.",
    seoTitle: "EV Savings Calculator — Electric vs Gas Annual Fuel Cost",
    metaDescription: "Free EV savings calculator. Compare the annual cost of driving electric versus gas from your mileage, MPG, efficiency, and energy prices to see your yearly savings.",
    primaryKeyword: "ev savings calculator",
    secondaryKeywords: ["electric vs gas cost calculator", "ev cost calculator", "electric car savings"],
    fields: [
      { id: "annualMiles", label: "Annual miles", type: "number", unit: "mi/yr", required: true, span: 1, min: 0 },
      { id: "gasMpg", label: "Gas car MPG", type: "number", unit: "mpg", required: true, span: 1, min: 0 },
      { id: "gasPrice", label: "Gas price", type: "number", unit: "$/gal", required: true, span: 2, min: 0, step: 0.01 },
      { id: "evEfficiency", label: "EV efficiency", type: "number", unit: "mi/kWh", required: true, span: 1, min: 0, step: 0.1 },
      { id: "electricityRate", label: "Electricity rate", type: "number", unit: "$/kWh", required: true, span: 1, min: 0, step: 0.01 },
    ],
    results: [
      { id: "annualSavings", label: "Annual savings", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "gasCost", label: "Gas annual cost", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "evCost", label: "EV annual cost", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "gas cost = miles ÷ MPG × gas price  ·  EV cost = miles ÷ (mi/kWh) × rate",
    formulaExplanation: "Each side of the comparison converts annual miles into an energy bill. For the gas car, dividing miles by MPG gives gallons burned, which multiplied by the pump price gives the yearly fuel cost. For the electric car, dividing miles by efficiency in miles per kilowatt-hour gives kilowatt-hours drawn, multiplied by the electricity rate for its yearly cost. Subtracting the two reveals the annual saving.",
    explanation: "Switching to electric promises lower running costs, but the real gap depends on your mileage and local energy prices, and this EV savings calculator puts an honest yearly number on it. You enter how far you drive each year, the fuel economy of the gas car you would otherwise use, its fuel price, and then the electric car's efficiency and your electricity rate. The tool returns the annual cost of each option and the savings from going electric.\n\nThe comparison matters because fuel is where electric vehicles most clearly pull ahead. Electricity usually delivers a mile far more cheaply than gasoline, but the advantage swings with how much you drive, how efficient each vehicle is, and the spread between pump prices and your per-kilowatt-hour rate. Someone with a long commute and cheap overnight charging saves dramatically, while a low-mileage driver on expensive electricity may save less than expected.\n\nBy isolating the two energy bills side by side, the calculator makes those trade-offs concrete. You can test a higher gas price, a colder climate that lowers EV efficiency, or a time-of-use electricity plan and see the yearly saving shift at once. It focuses purely on fuel versus charging, giving you a clean baseline to weigh against purchase price, incentives, and maintenance when deciding whether the switch pays off.",
    example: { inputs: { annualMiles: 12000, gasMpg: 30, gasPrice: 4, evEfficiency: 3.5, electricityRate: 0.15 }, explanation: "Gas: 12000 ÷ 30 × $4 = $1,600. EV: 12000 ÷ 3.5 × $0.15 ≈ $514.29. Savings ≈ $1,085.71 per year." },
    faqs: [
      {
        question: "What is EV efficiency in miles per kWh?",
        answer: "Miles per kilowatt-hour tells you how far an electric car travels on one unit of electricity, much like MPG does for fuel. Typical EVs manage roughly 3 to 4 miles per kWh, though this drops in cold weather, at high speeds, or with heavy loads. Check your car's display or the EPA rating for a realistic figure, and lower it a little if you often drive in demanding conditions.",
      },
      {
        question: "Where do I find my electricity rate?",
        answer: "Your electricity rate appears on your utility bill, expressed in dollars or cents per kilowatt-hour. Many households pay somewhere between $0.10 and $0.30 per kWh, but time-of-use plans charge less overnight, which is when most EV owners charge. If your plan varies by time, use the off-peak rate you actually charge at for the most accurate savings estimate rather than the average.",
      },
      {
        question: "Does this include the higher purchase price of an EV?",
        answer: "No, this calculator compares only the running cost of fuel versus charging. Electric vehicles often cost more upfront, though incentives, tax credits, and lower maintenance can narrow the gap. Use the annual fuel saving shown here as one input into a broader decision that also weighs purchase price, financing, battery warranty, and resale value over the years you expect to keep the car.",
      },
      {
        question: "How much can I realistically save each year?",
        answer: "Savings scale with how far you drive and the price spread between gasoline and electricity. A typical driver covering 12,000 miles a year commonly saves several hundred to over a thousand dollars annually on fuel alone. Higher mileage, expensive gas, and cheap overnight charging widen the gap, while low mileage or pricey electricity shrink it. Enter your own figures to see a number tailored to you.",
      },
      {
        question: "Do cold weather and driving style affect the result?",
        answer: "Yes, significantly for the electric side. Cold temperatures reduce battery efficiency and cabin heating draws extra power, so winter miles per kWh can fall noticeably. Fast highway driving and hard acceleration also lower efficiency for both vehicle types. To keep the estimate realistic, use an efficiency figure that reflects your climate and typical driving rather than the best-case number from a mild-weather test.",
      },
    ],
    relatedCalculators: ["fuel-cost-calculator", "mpg-calculator", "car-loan-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "U.S. EPA fuel economy",
    sourceUrl: "https://www.fueleconomy.gov/",
  },
  {
    id: "tire-size",
    slug: "tire-size-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "Tire Size Calculator",
    shortDescription: "Decode a P-metric tire size.",
    seoTitle: "Tire Size Calculator — Overall Diameter and Revs Per Mile",
    metaDescription: "Free tire size calculator. Enter width, aspect ratio, and rim diameter to find overall tire diameter in inches, sidewall height, and revolutions per mile.",
    primaryKeyword: "tire size calculator",
    secondaryKeywords: ["tire diameter calculator", "tire dimension calculator", "revs per mile calculator"],
    fields: [
      { id: "width", label: "Section width", type: "number", unit: "mm", required: true, span: 1, min: 0 },
      { id: "aspectRatio", label: "Aspect ratio", type: "number", unit: "%", required: true, span: 1, min: 0 },
      { id: "rimDiameter", label: "Rim diameter", type: "number", unit: "in", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "diameter", label: "Overall diameter", format: "number", decimals: 2, unit: "in", isPrimary: true },
      { id: "sidewall", label: "Sidewall height", format: "number", decimals: 2, unit: "mm", isPrimary: false },
      { id: "revsPerMile", label: "Revolutions per mile", format: "number", decimals: 0, unit: "rev/mi", isPrimary: false },
    ],
    formula: "diameter = rim × 25.4 + 2 × (width × aspect ÷ 100)",
    formulaExplanation: "A P-metric size like 225/45R17 packs three numbers. Sidewall height in millimetres is the section width times the aspect-ratio percentage, since aspect ratio is the sidewall expressed as a share of width. Overall diameter is the rim diameter converted to millimetres plus two sidewalls, one at the top and one at the bottom. Dividing 63,360 inches per mile by the tyre's circumference gives revolutions per mile.",
    explanation: "The code stamped on a tyre's sidewall hides its real dimensions, and this tire size calculator translates it into the numbers that actually matter when fitting new rubber. Enter the section width in millimetres, the aspect ratio as a percentage, and the rim diameter in inches, and it returns the overall diameter, the sidewall height, and how many times the tyre turns in a mile.\n\nThose figures decide whether a tyre will fit and whether your speedometer stays honest. Overall diameter affects ride height, clearance, and gearing, while revolutions per mile drive the speedometer and odometer readings. Fit a tyre with a different diameter and every speed and distance reading shifts, which is why comparing a prospective size against your current one before buying is so important.\n\nThe math follows the standard P-metric convention. Aspect ratio expresses sidewall height as a percentage of section width, so multiplying the two gives the sidewall in millimetres. The wheel contributes its rim diameter, converted from inches, and the tyre adds a sidewall at the top and bottom, producing the overall diameter. From there the circumference sets the revolutions per mile. Whether you are plus-sizing wheels, chasing a specific look, or restoring factory gearing, seeing these numbers side by side lets you choose a replacement that keeps handling and instrument accuracy intact.",
    example: { inputs: { width: 225, aspectRatio: 45, rimDiameter: 17 }, explanation: "Sidewall = 225 × 45 ÷ 100 = 101.25 mm; diameter = 17 × 25.4 + 2 × 101.25 = 634.3 mm ≈ 24.97 in." },
    faqs: [
      {
        question: "How do I read a tire size like 225/45R17?",
        answer: "The first number, 225, is the section width in millimetres. The second, 45, is the aspect ratio, meaning the sidewall height is 45 percent of the width. The letter R indicates radial construction, and the final number, 17, is the wheel rim diameter in inches. Enter the width, aspect ratio, and rim diameter into this calculator to see the tyre's real overall dimensions.",
      },
      {
        question: "Why does overall tire diameter matter?",
        answer: "Overall diameter determines ride height, ground clearance, and effective gearing, and it directly affects speedometer accuracy. A larger diameter raises the vehicle and makes the speedometer read slightly slow, while a smaller one does the opposite. When replacing tyres, keeping the overall diameter close to the original preserves handling, instrument accuracy, and the electronic systems that rely on wheel speed, such as ABS and traction control.",
      },
      {
        question: "What are revolutions per mile used for?",
        answer: "Revolutions per mile counts how many full turns a tyre makes to cover one mile, derived from its circumference. Speedometers and odometers are calibrated to a specific value, so a tyre with a different count will make those readings inaccurate. It also matters for matching tyres across an axle and for setups that read wheel speed, since mismatched revolutions can confuse the vehicle's electronics.",
      },
      {
        question: "Can I safely change my tire size?",
        answer: "Modest changes are common, especially plus-sizing where a wider tyre on a larger rim keeps the overall diameter similar. The key is to hold overall diameter close to the original, ideally within about three percent, so speedometer accuracy and clearance are preserved. Always confirm the new size fits the wheel well without rubbing and matches the load and speed ratings your vehicle requires before fitting.",
      },
      {
        question: "Does aspect ratio affect ride quality?",
        answer: "Yes. A lower aspect ratio means a shorter, stiffer sidewall, which sharpens steering response and cornering but transmits more road bumps into the cabin. A higher aspect ratio gives a taller, more cushioned sidewall that smooths the ride and better resists pothole damage. Choosing an aspect ratio is a trade-off between handling precision and comfort, alongside its effect on the tyre's overall diameter.",
      },
    ],
    relatedCalculators: ["mpg-calculator", "fuel-cost-calculator", "car-loan-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard P-metric tire sizing",
  },
  {
    id: "car-loan",
    slug: "car-loan-calculator",
    category: "Automotive",
    categorySlug: "automotive",
    title: "Car Loan Calculator",
    shortDescription: "Estimate your monthly car payment.",
    seoTitle: "Car Loan Calculator — Monthly Payment and Total Interest",
    metaDescription: "Free car loan calculator. Enter vehicle price, down payment, trade-in, interest rate, and term to see your monthly payment, total interest, and amount financed.",
    primaryKeyword: "car loan calculator",
    secondaryKeywords: ["auto loan calculator", "monthly car payment calculator", "vehicle finance calculator"],
    fields: [
      { id: "vehiclePrice", label: "Vehicle price", type: "number", unit: "$", required: true, span: 1, min: 0 },
      { id: "downPayment", label: "Down payment", type: "number", unit: "$", required: false, span: 1, min: 0 },
      { id: "tradeIn", label: "Trade-in value", type: "number", unit: "$", required: false, span: 1, min: 0 },
      { id: "rate", label: "Interest rate (APR)", type: "number", unit: "%", required: true, span: 1, min: 0, step: 0.1 },
      { id: "term", label: "Loan term", type: "number", unit: "months", required: true, span: 2, min: 1 },
    ],
    results: [
      { id: "monthlyPayment", label: "Monthly payment", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "totalInterest", label: "Total interest", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "amountFinanced", label: "Amount financed", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "payment = L × r ÷ (1 − (1 + r)^−n)",
    formulaExplanation: "The amount financed is the vehicle price minus any down payment and trade-in. The standard amortization formula then spreads that principal over the term, where r is the monthly rate (APR ÷ 12) and n is the number of months. The denominator discounts every future payment back to today so each equal instalment covers interest first and chips away at principal, until the balance reaches zero at the final payment.",
    explanation: "Financing a car turns one big price into a stream of monthly payments, and this car loan calculator shows exactly what that stream looks like before you sign. Enter the vehicle price, any down payment and trade-in, the annual interest rate, and the term in months, and it returns your monthly payment, the total interest you will pay, and the amount actually being financed.\n\nSeeing all three numbers together prevents the classic mistake of shopping by monthly payment alone. A longer term shrinks the monthly figure but quietly inflates total interest, so a payment that feels affordable can hide a much larger lifetime cost. The amount financed makes the effect of your down payment and trade-in concrete: every dollar you put down is a dollar you never pay interest on, which is why a bigger deposit lowers both the payment and the total.\n\nThe engine uses standard loan amortization, the same math lenders apply. Each equal payment covers the month's interest on the outstanding balance first, then reduces the principal, so early payments are interest-heavy and later ones increasingly pay down the loan. By adjusting the rate, term, or down payment and watching the results move, you can find a structure that fits your budget while keeping the interest you hand to the lender under control.",
    example: { inputs: { vehiclePrice: 30000, downPayment: 5000, tradeIn: 0, rate: 6, term: 60 }, explanation: "Financing $25,000 at 6% APR over 60 months gives about $483.32 a month and roughly $3,999 total interest." },
    faqs: [
      {
        question: "What counts as the amount financed?",
        answer: "The amount financed is the vehicle price minus your down payment and any trade-in value. This is the principal the loan actually covers and the figure interest is charged on. Reducing it with a larger down payment or a higher trade-in directly lowers both your monthly payment and the total interest. If your down payment and trade-in equal or exceed the price, there is nothing left to finance.",
      },
      {
        question: "How does the loan term affect what I pay?",
        answer: "A longer term spreads the balance over more months, so each payment is smaller, but you pay interest for longer and the total interest climbs. A shorter term raises the monthly payment yet cuts the overall cost. This calculator shows both the payment and the total interest so you can weigh a comfortable monthly figure against the true lifetime cost of the loan before deciding.",
      },
      {
        question: "Is APR the same as the interest rate?",
        answer: "They are closely related but not identical. The interest rate is the cost of borrowing the principal, while APR, the annual percentage rate, also folds in certain fees to reflect the loan's true yearly cost. This calculator treats the rate you enter as the annual rate applied monthly. For the most accurate payment, enter the APR your lender quotes, since it captures the effective borrowing cost.",
      },
      {
        question: "Why is total interest so important to check?",
        answer: "Total interest is the extra money you pay the lender on top of the amount financed, and it can be substantial on longer loans. Focusing only on a low monthly payment can disguise a large total, because stretching the term reduces each payment while adding interest month after month. Checking total interest alongside the payment reveals the real price of financing and helps you avoid overpaying.",
      },
      {
        question: "How can I lower my monthly car payment?",
        answer: "You can lower the payment by increasing your down payment or trade-in, which shrinks the amount financed, by securing a lower interest rate through better credit or shopping lenders, or by extending the term. Be cautious with the last option, since a longer term reduces the payment but raises total interest. Adjust each input here to find a balance that fits your budget and total cost.",
      },
    ],
    relatedCalculators: ["fuel-cost-calculator", "ev-savings-calculator", "tire-size-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard loan amortization",
  },
];
