import type { CalculatorDefinition } from "../types";

export const businessWave2Calculators: CalculatorDefinition[] = [
  {
    id: "revenue-calculator",
    slug: "revenue-calculator",
    category: "Business",
    categorySlug: "business",
    title: "Revenue Calculator",
    shortDescription: "Calculate total revenue from unit sales, pricing, and recurring revenue streams.",
    seoTitle: "Revenue Calculator — Calculate Total Business Revenue",
    metaDescription: "Calculate total revenue from product sales and recurring revenue. Supports unit pricing, recurring revenue, and gross revenue totals. Free online tool.",
    primaryKeyword: "revenue calculator",
    secondaryKeywords: ["sales revenue calculator", "total revenue calculator", "gross revenue calculator", "business revenue"],
    sensitivity: "finance",
    fields: [
      {
        id: "unitPrice",
        label: "Price per Unit ($)",
        type: "number",
        placeholder: "e.g. 29.99",
        unit: "$",
        required: true,
      },
      {
        id: "unitsSold",
        label: "Units Sold",
        type: "number",
        placeholder: "e.g. 500",
        required: true,
      },
      {
        id: "recurringRevenue",
        label: "Recurring Monthly Revenue ($)",
        type: "number",
        placeholder: "e.g. 1000",
        unit: "$",
        defaultValue: 0,
        required: false,
        helpText: "Subscription or retainer revenue added to product revenue",
      },
    ],
    results: [
      { id: "productRevenue", label: "Product Revenue", format: "currency", decimals: 2, isPrimary: false },
      { id: "monthlyRevenue", label: "Monthly Revenue (incl. recurring)", format: "currency", decimals: 2, isPrimary: true },
      { id: "annualRevenue", label: "Annual Revenue (projected)", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "Revenue = Units Sold × Price Per Unit + Recurring Revenue",
    formulaExplanation: "Total revenue combines product revenue (units × price) with any recurring revenue (subscriptions, retainers). Annual projection assumes consistent monthly performance over 12 months.",
    formulaSource: "Standard revenue accounting",
    explanation: "Revenue (also called sales or top-line revenue) is the total income a business generates before deducting any expenses. It's the starting point for all financial analysis — you need to know revenue before you can calculate profit, margins, or growth rates.\n\nThis calculator handles two common revenue streams: product/transactional revenue (price × quantity sold) and recurring revenue (monthly subscriptions, retainers, or service contracts). Together, these form gross monthly revenue.\n\nThe distinction between revenue and profit is critical. A business can have high revenue but lose money if costs exceed income. Revenue tells you the scale of the business; profit tells you whether it's actually working. The next step after calculating revenue is subtracting cost of goods sold (COGS) to find gross profit, then subtracting operating expenses to find net profit.",
    example: {
      inputs: { unitPrice: "49.99", unitsSold: "200", recurringRevenue: "2000" },
      explanation: "Product revenue: 200 × $49.99 = $9,998. Plus $2,000 recurring monthly revenue = $11,998 total monthly revenue. Annualized: $143,976.",
    },
    faqs: [
      {
        question: "What is the difference between revenue and profit?",
        answer: "Revenue is the total amount of money a business receives from selling its products or services before deducting any expenses. Profit is what remains after subtracting all costs from revenue. Gross profit = Revenue − Cost of Goods Sold (COGS). Net profit = Revenue − All Expenses (COGS + operating costs + taxes + interest). A business with $1 million in revenue but $1.2 million in expenses has a net loss of $200,000 — revenue alone doesn't indicate business health.",
      },
      {
        question: "What is recurring revenue and why does it matter?",
        answer: "Recurring revenue is income that reliably repeats each month or year without requiring new sales effort — subscriptions, retainers, licenses, and maintenance contracts. It's highly valued because it's predictable and less expensive to maintain than acquiring new customers. SaaS (Software as a Service) businesses measure Monthly Recurring Revenue (MRR) and Annual Recurring Revenue (ARR). Investors often value recurring revenue businesses at higher multiples than transactional businesses because of the predictability and customer lifetime value (LTV) it implies.",
      },
      {
        question: "How do I calculate revenue growth rate?",
        answer: "Revenue growth rate = (Current Period Revenue − Prior Period Revenue) / Prior Period Revenue × 100%. For example, if monthly revenue was $50,000 last year and is now $65,000: growth = ($65,000 − $50,000) / $50,000 × 100% = 30% year-over-year growth. Common benchmarks: early-stage startups should aim for 10%+ monthly growth; established SMBs typically see 10–25% annual growth; mature companies may grow 3–10% annually. Consistent above-market growth is a key indicator of a healthy business.",
      },
      {
        question: "What is the difference between gross revenue and net revenue?",
        answer: "Gross revenue is the total sales amount before any deductions. Net revenue (also called net sales) deducts returns, refunds, discounts, and allowances from gross revenue. For example, if you sell $100,000 of products but customers return $5,000 worth and you gave $2,000 in discounts, your net revenue is $93,000. Financial statements typically report net revenue, making it the more commonly cited figure. SaaS companies may also report net revenue after payment processing fees.",
      },
      {
        question: "How do I project annual revenue from monthly data?",
        answer: "The simplest projection multiplies monthly revenue by 12 (as our calculator does). For growing businesses, this understates future revenue — instead, apply your monthly growth rate: if you're growing 5% monthly, year-end monthly revenue = current × (1.05)^months_remaining. For a more sophisticated annual projection, sum the projected revenue for each of the next 12 months using your growth rate. Always note assumptions in projections — straight-line multiplication assumes no growth, seasonality, or churn.",
      },
    ],
    relatedCalculators: ["profit-margin", "break-even", "ecommerce-profit"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "profit-margin",
    slug: "profit-margin-calculator",
    category: "Business",
    categorySlug: "business",
    title: "Profit Margin Calculator",
    shortDescription: "Calculate gross, operating, and net profit margins to measure business profitability.",
    seoTitle: "Profit Margin Calculator — Gross, Operating & Net Margin",
    metaDescription: "Calculate gross profit margin, operating margin, and net profit margin. See total costs, profit, and profitability ratios instantly. Free business tool.",
    primaryKeyword: "profit margin calculator",
    secondaryKeywords: ["gross profit margin", "net profit margin", "operating margin calculator", "business profitability calculator"],
    sensitivity: "finance",
    fields: [
      {
        id: "revenue",
        label: "Revenue ($)",
        type: "number",
        placeholder: "e.g. 100000",
        unit: "$",
        required: true,
      },
      {
        id: "cogs",
        label: "Cost of Goods Sold (COGS) ($)",
        type: "number",
        placeholder: "e.g. 40000",
        unit: "$",
        required: true,
        helpText: "Direct costs to produce your product or service",
      },
      {
        id: "operatingExpenses",
        label: "Operating Expenses ($)",
        type: "number",
        placeholder: "e.g. 30000",
        unit: "$",
        defaultValue: 0,
        required: false,
        helpText: "Rent, salaries, marketing, admin — costs not directly tied to production",
      },
    ],
    results: [
      { id: "grossProfit", label: "Gross Profit", format: "currency", decimals: 2, isPrimary: false },
      { id: "grossMargin", label: "Gross Margin", format: "percentage", decimals: 1, isPrimary: true },
      { id: "operatingProfit", label: "Operating Profit", format: "currency", decimals: 2, isPrimary: false },
      { id: "operatingMargin", label: "Operating Margin", format: "percentage", decimals: 1, isPrimary: false },
    ],
    formula: "Gross Margin = (Revenue − COGS) / Revenue × 100; Operating Margin = (Revenue − COGS − OpEx) / Revenue × 100",
    formulaExplanation: "Gross margin measures how much of each revenue dollar remains after paying direct production costs. Operating margin further deducts overhead to show operating efficiency. Both are expressed as percentages of revenue.",
    formulaSource: "Generally Accepted Accounting Principles (GAAP)",
    explanation: "Profit margin tells you what percentage of revenue becomes profit — a critical measure of business health and efficiency. Higher margins mean the business keeps more of each dollar earned. Margins vary enormously by industry: software companies often have 70–80% gross margins, while grocery stores may have 25–30%.\n\nGross margin shows product/service profitability before overhead. If your gross margin is below zero, you're losing money on every sale — a fundamental problem. Most successful product companies target 40–70% gross margins. Software and digital products often reach 70–90%.\n\nOperating margin accounts for all the costs of running the business (salaries, rent, marketing, G&A). A healthy operating margin varies by industry — 15% is considered good for retail, while 30%+ is excellent for SaaS. Comparing your margins against industry benchmarks reveals competitive position.\n\nThis calculator focuses on gross and operating margin. Net margin would additionally subtract interest, taxes, and non-operating items.",
    example: {
      inputs: { revenue: "100000", cogs: "40000", operatingExpenses: "30000" },
      explanation: "Revenue $100K − COGS $40K = $60K gross profit (60% gross margin). Subtract $30K operating expenses = $30K operating profit (30% operating margin). This business keeps 30 cents of each dollar after all operational costs.",
    },
    faqs: [
      {
        question: "What is a good profit margin?",
        answer: "Good margins vary significantly by industry. Software/SaaS: gross margins 70–90%, net margins 20–30%. Consulting: gross margins 60–80%. Retail: gross margins 25–50%, net margins 2–6%. Restaurants: gross margins 60–65%, net margins 3–9%. Manufacturing: gross margins 25–35%. Technology hardware: gross margins 35–55%. Compare your margins against industry benchmarks rather than a universal 'good' number. Rising margins over time indicate improving efficiency, even if they're currently below the benchmark.",
      },
      {
        question: "What is the difference between gross margin and net margin?",
        answer: "Gross margin = (Revenue − COGS) / Revenue. It measures product profitability before overhead. Net margin = Net Income / Revenue, where net income is after ALL expenses including COGS, operating expenses, interest, depreciation, and taxes. Gross margin is a better measure of pricing power and product economics. Net margin measures overall business efficiency. A company with high gross margin but low net margin has excessive overhead — a common issue in fast-growing companies investing heavily in sales, marketing, and R&D.",
      },
      {
        question: "How do I improve my profit margin?",
        answer: "Improving margins requires either increasing revenue per unit or decreasing costs per unit. Revenue side: raise prices (test carefully for demand elasticity), upsell to higher-margin products, improve product mix. Cost side: negotiate better supplier terms, reduce waste, automate processes, improve operational efficiency, consolidate vendors. For operating margin: reduce overhead (renegotiate leases, optimize headcount, cut underperforming marketing channels), improve employee productivity, and leverage fixed costs by growing revenue without proportional cost growth.",
      },
      {
        question: "What is COGS vs operating expenses?",
        answer: "COGS (Cost of Goods Sold) are direct costs incurred to produce each unit sold — raw materials, direct labor, manufacturing overhead, and for services, the cost of delivering the service. Operating expenses (OpEx) are indirect costs of running the business not directly tied to production — rent, administrative salaries, marketing, insurance, utilities, and depreciation. The line between them isn't always clear-cut. A sales commission on a product sale might be COGS or OpEx depending on how a company classifies it. Consistency is the key — classify costs the same way each period.",
      },
      {
        question: "How does pricing affect profit margin?",
        answer: "Pricing has a leveraged impact on profit margin because it flows directly to profit without increasing variable costs. If your current price is $100, COGS is $60, and you sell 1,000 units: gross profit = $40,000 (40% margin). Raising the price to $110 (10% increase) with the same COGS and volume: gross profit = $50,000 — a 25% increase in gross profit from just a 10% price increase. This 'pricing leverage' makes pricing one of the highest-ROI levers for improving profitability. Test price increases carefully; even small demand reductions may offset margin gains.",
      },
    ],
    relatedCalculators: ["revenue-calculator", "markup-calculator", "break-even"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "markup-calculator",
    slug: "markup-calculator",
    category: "Business",
    categorySlug: "business",
    title: "Markup Calculator",
    shortDescription: "Calculate selling price from cost and markup percentage, or find markup % from cost and price.",
    seoTitle: "Markup Calculator — Selling Price from Cost & Markup %",
    metaDescription: "Calculate selling price from cost and markup percentage. Or find your markup percentage from cost and selling price. Free online markup calculator.",
    primaryKeyword: "markup calculator",
    secondaryKeywords: ["markup percentage calculator", "selling price calculator", "cost plus pricing", "wholesale to retail markup"],
    sensitivity: "finance",
    fields: [
      {
        id: "cost",
        label: "Cost ($)",
        type: "number",
        placeholder: "e.g. 50",
        unit: "$",
        required: true,
        helpText: "Your cost to acquire or produce the item",
      },
      {
        id: "markupPercent",
        label: "Markup Percentage (%)",
        type: "number",
        placeholder: "e.g. 50",
        unit: "%",
        required: true,
        helpText: "The percentage above cost to add as profit",
      },
    ],
    results: [
      { id: "sellingPrice", label: "Selling Price", format: "currency", decimals: 2, isPrimary: true },
      { id: "profit", label: "Profit ($)", format: "currency", decimals: 2, isPrimary: false },
      { id: "margin", label: "Profit Margin (%)", format: "percentage", decimals: 1, isPrimary: false },
    ],
    formula: "Selling Price = Cost × (1 + Markup% / 100); Margin% = Markup% / (100 + Markup%) × 100",
    formulaExplanation: "Markup is the percentage added to cost to set the selling price. Margin is the percentage of selling price that is profit. They're related but different: a 50% markup yields a 33.3% margin, not a 50% margin.",
    formulaSource: "Standard pricing and cost accounting",
    explanation: "Markup is one of the most fundamental concepts in pricing, yet it's frequently confused with profit margin. Understanding the difference is essential for setting prices that achieve your target profitability.\n\nMarkup is calculated from cost: a 100% markup on a $50 item means selling price = $100 (added $50 to the cost). Margin is calculated from revenue: that same sale has a 50% margin ($50 profit / $100 selling price = 50%).\n\nCommon retail markups vary by industry. Luxury goods: 200–500% markup. Jewelry: 100–300%. Clothing: 50–100%. Electronics: 15–25%. Grocery: 15–25%. The keystone price in retail is a 100% markup (doubling the wholesale cost), traditionally the starting point for retail pricing.\n\nWhen setting prices, work backward from your target margin: if you want a 40% margin, your markup must be: Markup = Margin / (1 − Margin) = 0.40 / 0.60 = 66.7%.",
    example: {
      inputs: { cost: "50", markupPercent: "100" },
      explanation: "A $50 item with 100% markup (keystone pricing): Selling price = $50 × (1 + 100/100) = $100. Profit = $50. Margin = $50/$100 = 50%. Despite a 100% markup, the margin is only 50%.",
    },
    faqs: [
      {
        question: "What is the difference between markup and margin?",
        answer: "Markup is the percentage added to cost: Markup% = (Price − Cost) / Cost × 100. Margin is the percentage of selling price that is profit: Margin% = (Price − Cost) / Price × 100. The same dollar profit gives different percentages because they use different denominators (cost vs. price). Key relationship: Margin = Markup / (1 + Markup). For example, a 100% markup yields a 50% margin; a 50% markup yields a 33.3% margin; a 25% markup yields a 20% margin. Always clarify which measure you're discussing.",
      },
      {
        question: "What markup do I need to achieve a specific margin?",
        answer: "To convert a target margin to the required markup: Markup% = Margin% / (1 − Margin%). For a 30% target margin: Markup = 0.30 / (1 − 0.30) = 0.30 / 0.70 = 42.86% markup. For a 50% target margin: Markup = 0.50 / 0.50 = 100% markup. For a 40% target margin: Markup = 0.40 / 0.60 = 66.7% markup. This conversion is crucial because many businesses set target margins but calculate prices using markup — the formulas look similar but give very different results if mixed up.",
      },
      {
        question: "What is keystone pricing?",
        answer: "Keystone pricing is a traditional retail strategy of marking up products by 100% (doubling the wholesale or cost price). If a retailer buys a product for $30, keystone pricing sets the retail price at $60. This gives a 50% gross margin — historically considered the minimum needed to cover overhead and remain profitable in retail. Today, many products deviate significantly from keystone: fast-moving commodity items may have 20–30% markup; luxury goods may have 200%+. Keystone remains a useful starting baseline for setting initial prices.",
      },
      {
        question: "How do I calculate the markup percentage from cost and selling price?",
        answer: "Markup% = (Selling Price − Cost) / Cost × 100. For example, if cost = $40 and selling price = $60: Markup = ($60 − $40) / $40 × 100 = $20 / $40 × 100 = 50%. This tells you that you added 50% of the cost as profit. To also find the margin: Margin = ($60 − $40) / $60 × 100 = $20 / $60 × 100 = 33.3%. Knowing both metrics helps you compare against industry benchmarks and competitors who may report either figure.",
      },
      {
        question: "How should I set my markup?",
        answer: "Markup should reflect your target margin after all costs, not just COGS. Consider: industry benchmarks (research what margins successful competitors achieve), full cost recovery (ensure markup covers COGS plus allocated overhead, leaving profit), competitive positioning (premium brands can command higher markups), perceived value (what customers believe the product is worth, which may far exceed cost), and product category norms. Test different price points to understand demand elasticity — a 10% price increase that only reduces demand by 5% increases total profit. Avoid the mistake of using industry-average markup without verifying your own cost structure matches.",
      },
    ],
    relatedCalculators: ["profit-margin", "ecommerce-profit", "break-even"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "break-even",
    slug: "break-even-calculator",
    category: "Business",
    categorySlug: "business",
    title: "Break-Even Calculator",
    shortDescription: "Find how many units you must sell to cover costs and start making a profit.",
    seoTitle: "Break-Even Calculator — Units & Revenue to Break Even",
    metaDescription: "Calculate your break-even point: how many units to sell before you start making a profit. Enter fixed costs, variable costs, and price. Free online tool.",
    primaryKeyword: "break-even calculator",
    secondaryKeywords: ["break even analysis", "break even point calculator", "breakeven units", "cost volume profit analysis"],
    sensitivity: "finance",
    fields: [
      {
        id: "fixedCosts",
        label: "Fixed Costs per Month ($)",
        type: "number",
        placeholder: "e.g. 10000",
        unit: "$",
        required: true,
        helpText: "Rent, salaries, insurance — costs that don't change with volume",
      },
      {
        id: "variableCostPerUnit",
        label: "Variable Cost per Unit ($)",
        type: "number",
        placeholder: "e.g. 25",
        unit: "$",
        required: true,
        helpText: "Cost per unit sold: materials, direct labor, packaging",
      },
      {
        id: "pricePerUnit",
        label: "Selling Price per Unit ($)",
        type: "number",
        placeholder: "e.g. 50",
        unit: "$",
        required: true,
      },
    ],
    results: [
      { id: "breakEvenUnits", label: "Break-Even Units", format: "number", decimals: 0, isPrimary: true },
      { id: "breakEvenRevenue", label: "Break-Even Revenue", format: "currency", decimals: 2, isPrimary: false },
      { id: "contributionMargin", label: "Contribution Margin per Unit", format: "currency", decimals: 2, isPrimary: false },
      { id: "contributionMarginRatio", label: "Contribution Margin Ratio", format: "percentage", decimals: 1, isPrimary: false },
    ],
    formula: "Break-Even Units = Fixed Costs / (Price per Unit − Variable Cost per Unit)",
    formulaExplanation: "Each unit sold contributes (Price − Variable Cost) toward covering fixed costs. The break-even point is where total contribution from all units sold exactly equals total fixed costs. Beyond this point, each unit sold generates pure profit.",
    formulaSource: "Cost-Volume-Profit (CVP) analysis framework",
    explanation: "The break-even point is the sales volume at which total revenue equals total costs — the point where you stop losing money and start generating profit. It's one of the most important calculations any business owner or entrepreneur should understand.\n\nThe key concept is the contribution margin: the amount each unit sold contributes toward covering fixed costs after paying its own variable costs. If you sell a product for $50 and it costs $25 in materials and direct labor, each unit contributes $25 toward fixed costs.\n\nBreak-even analysis helps answer critical business questions: How much do I need to sell before my business is profitable? How does a price change affect my break-even? What happens to profit if I increase marketing spend (raising fixed costs)? How much safety margin do I have above break-even?\n\nThe margin of safety — the gap between actual sales and break-even — shows how much sales can fall before losses begin. A business selling 500 units when break-even is 300 has a safety margin of 200 units (40%).",
    example: {
      inputs: { fixedCosts: "10000", variableCostPerUnit: "25", pricePerUnit: "50" },
      explanation: "Contribution margin per unit = $50 − $25 = $25. Break-even units = $10,000 / $25 = 400 units. At 400 units sold, revenue = $20,000 = total costs ($10,000 fixed + $10,000 variable). Unit 401 onwards is profit.",
    },
    faqs: [
      {
        question: "What are fixed costs vs variable costs?",
        answer: "Fixed costs don't change with production or sales volume — rent, insurance, salaried employees, loan payments, and depreciation. Even if you sell nothing, fixed costs still occur. Variable costs change directly with volume — raw materials, packaging, shipping, sales commissions, and direct labor. The more you produce, the higher the total variable cost. Semi-variable costs (utilities, some labor) have both fixed and variable components. Correct classification of costs is crucial: misclassifying variable as fixed makes break-even appear lower than it actually is.",
      },
      {
        question: "What is the contribution margin?",
        answer: "The contribution margin is the selling price minus variable cost per unit — the amount each sale 'contributes' toward covering fixed costs and ultimately profit. If price = $50 and variable cost = $30, contribution margin = $20 per unit. All fixed costs must be covered by accumulated contribution margins before profit begins. The contribution margin ratio (contribution margin / price) shows what percentage of each revenue dollar contributes to covering overhead. A 40% contribution margin ratio means $0.40 of each $1 in sales covers fixed costs and profit.",
      },
      {
        question: "How does pricing affect the break-even point?",
        answer: "Higher prices reduce the break-even point (fewer units needed). Lower prices raise it (more units needed). However, this isn't the full picture — price also affects demand. The goal is maximizing total profit, not just minimizing break-even units. A price increase that reduces demand may push you to break-even faster per unit, but if unit sales drop sharply, total profit could fall. Conversely, a price reduction that increases volume significantly might actually lower your break-even revenue despite needing more units. Run multiple scenarios at different price points.",
      },
      {
        question: "How do I use break-even analysis for a new product launch?",
        answer: "Before launching, estimate: (1) all fixed costs to bring the product to market (development, initial marketing, equipment), (2) variable cost per unit (materials, manufacturing, packaging, fulfillment), (3) target selling price, and (4) realistic achievable sales volume. The break-even calculation tells you whether the achievable sales volume exceeds break-even. If break-even requires 10,000 units/month but your market analysis suggests 2,000 units/month at that price, the business case doesn't work at current cost and price assumptions — you need to reduce costs or increase price.",
      },
      {
        question: "What is the margin of safety?",
        answer: "Margin of safety is the difference between actual (or projected) sales and the break-even point, expressed in units, revenue, or as a percentage. Margin of safety % = (Actual Sales − Break-Even Sales) / Actual Sales × 100. If you're selling 600 units and break-even is 400 units, margin of safety = (600 − 400) / 600 = 33%. This means sales could fall by 33% before you start losing money. A higher margin of safety indicates a more resilient business. During downturns or competitive pressure, margin of safety determines survival.",
      },
    ],
    relatedCalculators: ["profit-margin", "revenue-calculator", "markup-calculator"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "employee-cost",
    slug: "employee-cost-calculator",
    category: "Business",
    categorySlug: "business",
    title: "Employee Cost Calculator",
    shortDescription: "Calculate the true total cost of an employee including salary, benefits, taxes, and overhead.",
    seoTitle: "Employee Cost Calculator — True Cost of Hiring an Employee",
    metaDescription: "Calculate the true total cost of an employee including salary, payroll taxes, benefits, and overhead. See actual cost per hour. Free online tool.",
    primaryKeyword: "employee cost calculator",
    secondaryKeywords: ["cost of employee calculator", "true cost of hiring", "payroll cost calculator", "total compensation calculator"],
    sensitivity: "finance",
    fields: [
      {
        id: "salary",
        label: "Annual Salary ($)",
        type: "number",
        placeholder: "e.g. 60000",
        unit: "$",
        required: true,
      },
      {
        id: "benefitsPercent",
        label: "Benefits (% of salary)",
        type: "number",
        placeholder: "e.g. 20",
        defaultValue: 20,
        unit: "%",
        required: true,
        helpText: "Health insurance, dental, vision, 401k match, PTO — typically 20–30% of salary",
      },
      {
        id: "payrollTaxPercent",
        label: "Payroll Taxes (% of salary)",
        type: "number",
        placeholder: "e.g. 10",
        defaultValue: 10,
        unit: "%",
        required: true,
        helpText: "Employer portion: Social Security (6.2%), Medicare (1.45%), FUTA, SUTA — typically 10–15%",
      },
      {
        id: "overheadPercent",
        label: "Overhead (% of salary)",
        type: "number",
        placeholder: "e.g. 15",
        defaultValue: 15,
        unit: "%",
        required: true,
        helpText: "Office space, equipment, software, management time — typically 10–25%",
      },
    ],
    results: [
      { id: "totalAnnualCost", label: "Total Annual Cost", format: "currency", decimals: 0, isPrimary: true },
      { id: "totalMonthlyCost", label: "Total Monthly Cost", format: "currency", decimals: 0, isPrimary: false },
      { id: "costPerHour", label: "True Cost per Hour", format: "currency", decimals: 2, isPrimary: false },
      { id: "multiplier", label: "Cost Multiplier", format: "number", decimals: 2, isPrimary: false, description: "Total cost ÷ salary" },
    ],
    formula: "Total Cost = Salary × (1 + Benefits% + Payroll Tax% + Overhead%) / 100",
    formulaExplanation: "The true cost of an employee is significantly higher than their salary. Adding benefits, payroll taxes, and overhead typically brings the total to 1.25–1.5× salary, with overhead included pushing it to 1.5–2×.",
    formulaSource: "US Bureau of Labor Statistics, Employer Costs for Employee Compensation",
    sourceUrl: "https://www.bls.gov/news.release/ecec.toc.htm",
    explanation: "When businesses hire an employee at a $60,000 salary, the actual cost to the company is rarely $60,000. Once you add employer-side payroll taxes, health insurance, retirement matching, paid time off (which has a cost even though it's not a direct payment), and a share of office space and equipment, the total typically reaches $80,000–$100,000 or more — 1.3 to 1.7 times the base salary.\n\nUnderstanding the true cost per employee is critical for: pricing services correctly (if an employee's time is sold to clients, you must charge enough to cover their total cost), evaluating outsourcing vs. hiring decisions, planning headcount budgets, and understanding why contractors often charge 2–3× an employee's hourly rate.\n\nFor context, the US Bureau of Labor Statistics found that benefits add approximately 30% on top of wages for private-sector employees. Payroll taxes (employer share of Social Security, Medicare, and unemployment) add another 8–12%. Overhead adds 10–30% depending on the role and company.",
    example: {
      inputs: { salary: "60000", benefitsPercent: "25", payrollTaxPercent: "10", overheadPercent: "15" },
      explanation: "Salary $60,000 + benefits (25%) $15,000 + payroll taxes (10%) $6,000 + overhead (15%) $9,000 = total annual cost $90,000. True hourly cost: $90,000 / 2,080 work hours = $43.27/hour, vs. $28.85 salary rate alone.",
    },
    faqs: [
      {
        question: "Why does an employee cost so much more than their salary?",
        answer: "Multiple layers of cost stack on top of salary. Employer payroll taxes: Social Security (6.2%), Medicare (1.45%), Federal Unemployment (FUTA, 0.6% on first $7,000), and State Unemployment (SUTA, varies by state) — typically 8–12% total. Benefits: health insurance ($5,000–$20,000/year), dental and vision ($500–$2,000), 401k match (3–6% of salary), paid time off (3–4 weeks = 6–8% of salary effectively). Overhead: desk space, computer, software licenses, HR management, training, and a share of management's time. Total: 1.4–2× salary is common.",
      },
      {
        question: "What payroll taxes does an employer pay?",
        answer: "Employers pay the following US federal payroll taxes: Social Security tax — 6.2% of wages up to the Social Security wage base ($160,200 in 2023, subject to annual adjustment). Medicare tax — 1.45% of all wages with no cap. Federal Unemployment (FUTA) — 6% on first $7,000 of each employee's wages per year (reduced to 0.6% for most employers who also pay state unemployment). State Unemployment (SUTA) — varies by state and employer experience rating, typically 1–5%. Total employer payroll tax burden: typically 8–12% of wages.",
      },
      {
        question: "How does this help me decide between hiring vs. using a contractor?",
        answer: "Compare the contractor's rate to the true cost of an employee doing the same work. If you need a developer at $80/hour as a contractor, compare to the true hourly cost of an equivalent employee. A $100,000 salaried developer with 1.5× total cost multiplier = $150,000/year / 2,080 hours = $72/hour actual cost. In this case, the contractor is more expensive per hour. However, contractors offer flexibility (no severance if work ends), no benefits administration, no equipment cost, and expert skills for specific projects. The break-even analysis should factor in project duration, role criticality, and management overhead.",
      },
      {
        question: "What is a fully-loaded employee cost?",
        answer: "Fully-loaded cost is the total cost to the employer including all direct and indirect costs: salary, all employer-paid taxes, all benefits, recruiting costs (amortized), training costs, equipment and software, office space, management time spent on the employee, and any role-specific costs (tools, travel, licenses). Fully-loaded costs are often 1.5–2.5× the base salary. This metric is used in business cases for new hires, outsourcing decisions, and determining whether a role's revenue generation or cost savings justify its total cost.",
      },
      {
        question: "How do I use this to price my services?",
        answer: "If you're a services business (consulting, agency, staffing), your pricing must cover fully-loaded employee costs plus profit margin. Formula: minimum billable rate = (fully-loaded annual cost) / billable hours × (1 / target margin). For example, employee with $90,000 true annual cost, 1,600 billable hours/year, targeting 30% margin: minimum rate = $90,000 / 1,600 / (1 − 0.30) = $80.36/hour. In practice, employees are rarely billable 100% of the time — account for utilization rate (billable hours / total hours) which is typically 60–80% for services firms.",
      },
    ],
    relatedCalculators: ["hourly-wage", "paycheck", "overtime"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "cash-flow",
    slug: "cash-flow-calculator",
    category: "Business",
    categorySlug: "business",
    title: "Cash Flow Calculator",
    shortDescription: "Calculate operating, free, and net cash flow from revenue, expenses, and capital expenditures.",
    seoTitle: "Cash Flow Calculator — Operating & Free Cash Flow",
    metaDescription: "Calculate operating cash flow, free cash flow, and net cash flow from your income statement figures. Essential for business financial health assessment.",
    primaryKeyword: "cash flow calculator",
    secondaryKeywords: ["operating cash flow calculator", "free cash flow calculator", "net cash flow", "business cash flow"],
    sensitivity: "finance",
    fields: [
      {
        id: "revenue",
        label: "Revenue ($)",
        type: "number",
        placeholder: "e.g. 100000",
        unit: "$",
        required: true,
      },
      {
        id: "cogs",
        label: "Cost of Goods Sold ($)",
        type: "number",
        placeholder: "e.g. 40000",
        unit: "$",
        required: true,
      },
      {
        id: "operatingExpenses",
        label: "Operating Expenses ($)",
        type: "number",
        placeholder: "e.g. 30000",
        unit: "$",
        required: true,
      },
      {
        id: "taxes",
        label: "Taxes ($)",
        type: "number",
        placeholder: "e.g. 7000",
        unit: "$",
        defaultValue: 0,
        required: false,
      },
      {
        id: "capex",
        label: "Capital Expenditures ($)",
        type: "number",
        placeholder: "e.g. 5000",
        unit: "$",
        defaultValue: 0,
        required: false,
        helpText: "Equipment, property, and other capital investments",
      },
      {
        id: "depreciation",
        label: "Depreciation & Amortization ($)",
        type: "number",
        placeholder: "e.g. 2000",
        unit: "$",
        defaultValue: 0,
        required: false,
        helpText: "Non-cash expense added back to operating cash flow",
      },
    ],
    results: [
      { id: "operatingCashFlow", label: "Operating Cash Flow", format: "currency", decimals: 0, isPrimary: true },
      { id: "freeCashFlow", label: "Free Cash Flow", format: "currency", decimals: 0, isPrimary: false },
      { id: "netIncome", label: "Net Income (before DA)", format: "currency", decimals: 0, isPrimary: false },
    ],
    formula: "Operating CF = Net Income + Depreciation & Amortization; Free CF = Operating CF − CapEx",
    formulaExplanation: "Operating cash flow starts with net income and adds back non-cash charges (depreciation/amortization). Free cash flow deducts capital expenditures needed to maintain and grow the business. Positive free cash flow indicates the business generates cash after all operational and investment needs.",
    formulaSource: "GAAP Statement of Cash Flows methodology",
    explanation: "Cash flow and profit are not the same — a profitable business can run out of cash, and a cash-flow-positive business may show accounting losses. Understanding the difference is essential for business survival.\n\nOperating cash flow measures cash generated from core business operations, adding back non-cash expenses like depreciation (you record the expense but don't pay it in cash that period). This is the most direct measure of a business's ability to generate actual cash.\n\nFree cash flow is operating cash flow minus capital expenditures (money spent on equipment, property, or other assets). A business with high free cash flow can pay down debt, return money to owners, or invest in growth — it has financial flexibility. Negative free cash flow means the business needs external funding to sustain itself.\n\nInvestors often value businesses based on discounted free cash flow, making it one of the most important financial metrics in business valuation.",
    example: {
      inputs: { revenue: "100000", cogs: "40000", operatingExpenses: "30000", taxes: "7000", capex: "5000", depreciation: "2000" },
      explanation: "Net income = $100K − $40K − $30K − $7K = $23K. Operating cash flow = $23K + $2K D&A = $25K. Free cash flow = $25K − $5K CapEx = $20K. The business generates $20K in free cash flow this period.",
    },
    faqs: [
      {
        question: "Why is cash flow different from profit?",
        answer: "Accounting profit (net income) follows accrual accounting rules: you record revenue when earned and expenses when incurred, regardless of when cash changes hands. Cash flow tracks when money actually moves in or out. Key differences: credit sales show as profit even if not yet paid (accounts receivable); you must pay for inventory before selling it (reducing cash before profit is recognized); buying equipment costs cash immediately but is expensed over years as depreciation (profit shows a small expense; cash flow shows the full outlay in the purchase period). A business can be profitable on paper while running out of cash — a common cause of business failure.",
      },
      {
        question: "What is free cash flow and why is it important?",
        answer: "Free cash flow (FCF) is the cash a business generates after paying for the investments needed to maintain and grow its asset base (capital expenditures). FCF = Operating Cash Flow − Capital Expenditures. It's the 'free' cash available to be used however ownership wishes: paying dividends, buying back shares, paying down debt, or pursuing acquisitions. Consistently positive free cash flow is one of the strongest signals of business quality. Many legendary investors (Warren Buffett, Charlie Munger) focus on FCF because it's harder to manipulate than accounting earnings.",
      },
      {
        question: "What does negative cash flow mean?",
        answer: "Negative operating cash flow means the business is consuming more cash than it generates from operations — a potentially serious situation if sustained. However, negative free cash flow is common and acceptable for growing businesses investing heavily in capital equipment or expansion. Startups routinely have negative operating cash flow during early growth phases. The key questions: Is the negative cash flow funding investments that will generate future positive cash flow? How long can the business sustain negative cash flow before needing new funding? Is the trend improving? Short-term negative cash flow during growth is expected; persistent negative cash flow in a mature business signals structural problems.",
      },
      {
        question: "What is the difference between operating, investing, and financing cash flow?",
        answer: "The standard cash flow statement has three sections. Operating activities: cash from day-to-day business operations (sales, payments to suppliers, employee wages, taxes). This is what our calculator focuses on. Investing activities: cash spent on or received from long-term assets — buying/selling equipment, property, businesses, or investments. Financing activities: cash from or to capital providers — borrowing, repaying loans, issuing stock, paying dividends. Free cash flow = Operating CF − capital expenditure portion of Investing CF. Total cash change = Operating + Investing + Financing cash flows.",
      },
      {
        question: "How do I improve my business cash flow?",
        answer: "Cash flow improvement comes from both operating efficiency and balance sheet management. Accelerate inflows: invoice immediately, offer early payment discounts, switch to advance billing for subscriptions. Slow outflows: negotiate longer payment terms with suppliers, batch purchases to optimize timing. Reduce the cash conversion cycle (days to convert inventory to cash): faster inventory turnover, reducing days sales outstanding (how long customers take to pay), extending days payable outstanding. Long-term: focus on recurring revenue (more predictable cash), optimize capital expenditures (lease vs. buy analysis), and maintain a cash reserve for 2–3 months of operating expenses.",
      },
    ],
    relatedCalculators: ["profit-margin", "revenue-calculator", "break-even"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
];
