import type { CalculatorDefinition } from "../types";

const AREA_UNITS = [
  { value: "sqm", label: "Square Meters (m²)" },
  { value: "sqkm", label: "Square Kilometers (km²)" },
  { value: "sqft", label: "Square Feet (ft²)" },
  { value: "sqyd", label: "Square Yards (yd²)" },
  { value: "acre", label: "Acres" },
  { value: "hectare", label: "Hectares (ha)" },
  { value: "sqcm", label: "Square Centimeters (cm²)" },
  { value: "sqin", label: "Square Inches (in²)" },
  { value: "sqmi", label: "Square Miles (mi²)" },
];

const VOLUME_UNITS = [
  { value: "liter", label: "Liters (L)" },
  { value: "ml", label: "Milliliters (mL)" },
  { value: "cubicMeter", label: "Cubic Meters (m³)" },
  { value: "gallon", label: "Gallons (US)" },
  { value: "quart", label: "Quarts (US)" },
  { value: "pint", label: "Pints (US)" },
  { value: "cup", label: "Cups (US)" },
  { value: "flOz", label: "Fluid Ounces (US fl oz)" },
  { value: "tablespoon", label: "Tablespoons" },
  { value: "teaspoon", label: "Teaspoons" },
  { value: "cubicFt", label: "Cubic Feet (ft³)" },
  { value: "cubicIn", label: "Cubic Inches (in³)" },
  { value: "imperialGallon", label: "Imperial Gallons (UK)" },
];

const PRESSURE_UNITS = [
  { value: "pascal", label: "Pascals (Pa)" },
  { value: "kilopascal", label: "Kilopascals (kPa)" },
  { value: "megapascal", label: "Megapascals (MPa)" },
  { value: "bar", label: "Bar" },
  { value: "psi", label: "Pounds per Square Inch (psi)" },
  { value: "atm", label: "Atmospheres (atm)" },
  { value: "mmHg", label: "Millimeters of Mercury (mmHg)" },
  { value: "inHg", label: "Inches of Mercury (inHg)" },
];

const ENERGY_UNITS = [
  { value: "joule", label: "Joules (J)" },
  { value: "kilojoule", label: "Kilojoules (kJ)" },
  { value: "calorie", label: "Calories (cal)" },
  { value: "kilocalorie", label: "Kilocalories (kcal / food Cal)" },
  { value: "wattHour", label: "Watt-Hours (Wh)" },
  { value: "kilowattHour", label: "Kilowatt-Hours (kWh)" },
  { value: "btu", label: "British Thermal Units (BTU)" },
  { value: "footPound", label: "Foot-Pounds (ft·lb)" },
  { value: "electronVolt", label: "Electron Volts (eV)" },
];

export const convertersWave2Calculators: CalculatorDefinition[] = [
  {
    id: "area-converter",
    slug: "area-converter",
    category: "Converters",
    categorySlug: "converters",
    title: "Area Converter",
    shortDescription: "Convert area between square meters, square feet, acres, hectares, and more.",
    seoTitle: "Area Converter — Square Meters, Feet, Acres, Hectares",
    metaDescription: "Convert area between any units: square meters, square feet, acres, hectares, square miles, and more. Free online area unit converter.",
    primaryKeyword: "area converter",
    secondaryKeywords: ["square meters to square feet", "acres to hectares", "area unit converter", "sq ft to sq m"],
    fields: [
      {
        id: "value",
        label: "Value",
        type: "number",
        placeholder: "Enter area",
        required: true,
      },
      {
        id: "from",
        label: "From",
        type: "select",
        defaultValue: "sqft",
        required: true,
        unitOptions: AREA_UNITS,
      },
      {
        id: "to",
        label: "To",
        type: "select",
        defaultValue: "sqm",
        required: true,
        unitOptions: AREA_UNITS,
      },
    ],
    results: [
      { id: "result", label: "Converted Area", format: "number", decimals: 6, isPrimary: true },
    ],
    formula: "Convert to sq meters (base unit) then to target unit using conversion factors",
    formulaExplanation: "Area conversion works because every area unit is defined as a fixed multiple of the square meter, the SI base unit for area. Since these ratios never change, the converter multiplies the input by its factor to reach square meters, then divides by the target unit's factor to scale out. Key ratios: 1 sq ft = 0.092903 sq m, 1 acre = 4,046.86 sq m, 1 hectare = 10,000 sq m, and 1 sq mile = 2,589,988 sq m.",
    formulaSource: "International System of Units (SI) — NIST",
    sourceUrl: "https://www.nist.gov/pml/owm/metric-si/unit-conversion",
    explanation: "Area measures the two-dimensional size of a surface, and the units used vary widely across countries, industries, and everyday situations. The metric world works in square meters, square kilometers, and hectares, while the United States relies on square feet, square yards, acres, and square miles. An area converter removes the friction of moving between these systems so a plot listed in hectares can be compared instantly with one quoted in acres.\n\nSquare feet dominate US residential real estate — a home is described as 2,000 sq ft rather than 186 square meters. Acres measure land parcels, where one acre equals 43,560 square feet, roughly the playing area of an American football field. Hectares are the international agricultural standard at 10,000 square meters, and square kilometers or square miles handle large geographic regions.\n\nBecause every unit has a fixed, exact ratio to the square meter, this area converter normalises any input to square meters first and then scales to the chosen output, keeping results precise no matter how unusual the pairing. Real estate agents, farmers, surveyors, architects, and students all use an area converter to translate measurements confidently across the metric and US customary systems.",
    example: {
      inputs: { value: "1", from: "acre", to: "sqm" },
      explanation: "1 acre = 4,046.86 square meters. An acre is roughly the area of a standard American football field (excluding end zones).",
    },
    faqs: [
      {
        question: "How many square feet are in an acre?",
        answer: "One acre equals exactly 43,560 square feet. This is a legally defined value in the US. An acre is approximately 209 feet × 209 feet (roughly a square with sides of about 63.6 meters). One square mile contains exactly 640 acres. These fixed ratios are why real estate professionals can quickly convert between acres and square feet mentally: 5 acres = 5 × 43,560 = 217,800 square feet.",
      },
      {
        question: "What is the difference between a hectare and an acre?",
        answer: "A hectare (ha) is a metric unit equal to 10,000 square meters, while an acre is a US customary/imperial unit equal to 4,046.86 square meters. One hectare = approximately 2.471 acres. Hectares are used internationally and in scientific contexts; acres are common in the US and UK for land measurement. A soccer field is about 0.6–0.7 hectares or 1.5–1.75 acres. When buying farmland internationally, check which unit the listing uses.",
      },
      {
        question: "How do I convert square feet to square meters?",
        answer: "Multiply square feet by 0.092903 to get square meters. Alternatively, divide square feet by 10.764 (since 1 sq m = 10.764 sq ft). For mental math: 1,000 sq ft ÷ 10 ≈ 100 sq m (actually 92.9 sq m, so it's a rough approximation). For precise work, always use the exact factor of 0.092903. A 2,000 sq ft home is approximately 185.8 square meters — a common question in international real estate.",
      },
      {
        question: "What is a square mile in acres?",
        answer: "One square mile equals exactly 640 acres. This is a fundamental relationship in the US land measurement system, derived from the township-and-range surveying system used across most of the US. A US township is 6 miles × 6 miles = 36 square miles = 23,040 acres, divided into 36 sections of 640 acres each. This grid system is why rural US roads are often exactly 1 mile apart.",
      },
      {
        question: "How large is a square meter compared to common objects?",
        answer: "A square meter (m²) is a square with sides of 1 meter (about 3.28 feet or 39.4 inches). To visualize: a typical dining table is about 0.9 m², a king-sized bed is about 2.6 m², a single parking space is about 14–16 m², and an average US bedroom is about 14–18 m² (150–200 sq ft). A full tennis court is 260.75 m², a basketball court is 436.6 m², and a standard soccer pitch is 6,000–8,500 m² (0.6–0.85 hectares).",
      },
    ],
    relatedCalculators: ["length-converter", "volume-converter", "paint"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "volume-converter",
    slug: "volume-converter",
    category: "Converters",
    categorySlug: "converters",
    title: "Volume Converter",
    shortDescription: "Convert volume between liters, gallons, cups, fluid ounces, cubic meters, and more.",
    seoTitle: "Volume Converter — Liters, Gallons, Cups, Fluid Ounces",
    metaDescription: "Convert volume between any units: liters, gallons, cups, fluid ounces, milliliters, cubic meters, and more. Free online volume converter.",
    primaryKeyword: "volume converter",
    secondaryKeywords: ["liters to gallons", "ml to cups", "fluid ounce converter", "cubic feet to liters"],
    fields: [
      {
        id: "value",
        label: "Value",
        type: "number",
        placeholder: "Enter volume",
        required: true,
      },
      {
        id: "from",
        label: "From",
        type: "select",
        defaultValue: "gallon",
        required: true,
        unitOptions: VOLUME_UNITS,
      },
      {
        id: "to",
        label: "To",
        type: "select",
        defaultValue: "liter",
        required: true,
        unitOptions: VOLUME_UNITS,
      },
    ],
    results: [
      { id: "result", label: "Converted Volume", format: "number", decimals: 6, isPrimary: true },
    ],
    formula: "Convert to liters (base unit) then to target unit",
    formulaExplanation: "Volume conversion is exact because each unit is a fixed multiple of the liter, which ties directly to the SI cubic meter (1 m³ = 1000 L). The converter scales the input up to liters using its ratio, then down to the requested unit, so no precision is lost across the range. Key ratios: 1 US gallon = 3.78541 L, 1 cup = 0.236588 L, 1 fl oz = 0.0295735 L, and 1 cubic meter = 1000 L.",
    formulaSource: "International System of Units (SI) — NIST",
    sourceUrl: "https://www.nist.gov/pml/owm/metric-si/unit-conversion",
    explanation: "Volume measures the three-dimensional space a substance occupies, and it appears constantly in cooking, chemistry, construction, fuel, and shipping. The difficulty is that volume units differ sharply between the US and the rest of the world, and even within the US the definitions of cup, pint, gallon, and fluid ounce diverge from the imperial (UK) versions. A volume converter resolves this by translating any figure into a shared reference before producing the answer you need.\n\nThe essentials worth remembering: a US gallon is 3.785 liters, while a UK imperial gallon is 4.546 liters — a 20 percent gap that matters when comparing fuel economy internationally. A US cup is about 240 mL, whereas a metric cup used in Australia and Canada is 250 mL, and US and UK fluid ounces also differ slightly.\n\nBecause each unit holds a fixed ratio to the liter, this volume converter normalises every input to liters first, then scales to the target, so even awkward pairings like cubic feet to imperial gallons stay accurate. Home cooks, engineers, lab technicians, and drivers filling up abroad all lean on a volume converter to avoid the costly errors that come from mixing incompatible unit systems.",
    example: {
      inputs: { value: "1", from: "gallon", to: "liter" },
      explanation: "1 US gallon = 3.78541 liters. This is why fuel economy in the US (miles per gallon) differs numerically from countries that use liters per 100 km.",
    },
    faqs: [
      {
        question: "How many cups are in a gallon?",
        answer: "In the US system: 1 gallon = 4 quarts = 8 pints = 16 cups = 128 fluid ounces. So there are exactly 16 US cups in 1 US gallon. A handy mnemonic: Gallon, Quarts, Pints, Cups — each step doubles the count: G=1, Q=4, P=8, C=16. This relationship is exact by definition in the US customary system.",
      },
      {
        question: "What is the difference between a US gallon and a UK (imperial) gallon?",
        answer: "A US gallon is 3.78541 liters, while a UK imperial gallon is 4.54609 liters — about 20% larger. This is why UK cars appear to get better fuel economy in 'miles per gallon' than US cars — the UK gallon is larger, so more miles per gallon is easier. When comparing international fuel efficiency, always clarify which gallon is used. US fluid ounces and UK fluid ounces also differ: 1 US fl oz = 29.5735 mL; 1 UK fl oz = 28.4131 mL.",
      },
      {
        question: "How many milliliters are in a cup?",
        answer: "A US legal cup (used in nutrition labeling) = 240 mL exactly. A US customary cup = 236.588 mL (based on the US gallon definition). An Australian/Canadian metric cup = 250 mL. For most cooking purposes, 240 mL per cup is the practical standard. If you're following a recipe from another country, knowing which cup definition they use can matter for precision baking, though for most home cooking the 10 mL difference between US and metric cups is negligible.",
      },
      {
        question: "How do I convert liters to gallons?",
        answer: "To convert liters to US gallons, divide by 3.78541 (or multiply by 0.264172). For quick mental math: 4 liters ≈ 1 gallon (actual: 4 L = 1.057 gallons, so this is about 5.7% off). More precisely: 10 liters ≈ 2.64 gallons, 20 liters ≈ 5.28 gallons. When filling up a car with fuel abroad, this conversion helps estimate costs: a 50-liter tank holds about 13.2 US gallons.",
      },
      {
        question: "What is the volume of a cubic foot in liters?",
        answer: "One cubic foot = 28.3168 liters (about 28.3 liters). One cubic meter = 1,000 liters = 264.172 US gallons. These conversions are important in construction (concrete volume, water storage tank sizing), HVAC (airflow in cubic feet per minute), and plumbing (pipe capacity in gallons or liters). A typical bathtub holds about 1.5–2.5 cubic feet (42–71 liters) of water when full.",
      },
    ],
    relatedCalculators: ["area-converter", "cooking-measurement", "length-converter"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "pressure-converter",
    slug: "pressure-converter",
    category: "Converters",
    categorySlug: "converters",
    title: "Pressure Converter",
    shortDescription: "Convert pressure between pascals, psi, bar, atmospheres, mmHg, and more.",
    seoTitle: "Pressure Converter — PSI, Bar, Pascal, Atmospheres",
    metaDescription: "Convert pressure between any units: psi, bar, pascal, kilopascal, atmospheres, mmHg, and more. Free online pressure unit converter.",
    primaryKeyword: "pressure converter",
    secondaryKeywords: ["psi to bar", "psi to kpa", "atmospheres to psi", "mmHg to kpa", "pressure unit converter"],
    fields: [
      {
        id: "value",
        label: "Value",
        type: "number",
        placeholder: "Enter pressure",
        required: true,
      },
      {
        id: "from",
        label: "From",
        type: "select",
        defaultValue: "psi",
        required: true,
        unitOptions: PRESSURE_UNITS,
      },
      {
        id: "to",
        label: "To",
        type: "select",
        defaultValue: "bar",
        required: true,
        unitOptions: PRESSURE_UNITS,
      },
    ],
    results: [
      { id: "result", label: "Converted Pressure", format: "number", decimals: 6, isPrimary: true },
    ],
    formula: "Convert to pascals (SI base unit) then to target unit",
    formulaExplanation: "Pressure conversion holds because every pressure unit equals a fixed number of pascals, the SI unit for pressure (one newton per square meter). The converter multiplies the input by its pascal ratio to reach the common base, then divides by the target's ratio to scale out, so results stay exact. Key ratios: 1 psi = 6,894.76 Pa, 1 bar = 100,000 Pa, 1 atm = 101,325 Pa, and 1 mmHg = 133.322 Pa.",
    formulaSource: "International System of Units (SI) — NIST",
    sourceUrl: "https://www.nist.gov/pml/owm/metric-si/unit-conversion",
    explanation: "Pressure is force distributed over an area, and almost every field that measures it has settled on its own preferred unit. Tire inflation is quoted in PSI in the US and in bar across Europe, blood pressure is read in millimeters of mercury, weather reports use hectopascals or millibars, and heavy industry often works in bar or megapascals. A pressure converter lets you move between all of these without memorising dozens of separate relationships.\n\nThe SI unit is the pascal (Pa), defined as one newton per square meter. One standard atmosphere equals 101,325 Pa, the average air pressure at sea level, while one bar is 100,000 Pa — very slightly below an atmosphere. PSI remains entrenched in the US for tires, hydraulics, and compressed air; a typical car tire sits at 32 to 35 PSI, or 2.2 to 2.4 bar.\n\nBecause each unit carries a fixed ratio to the pascal, this pressure converter normalises the input to pascals first and then scales to the chosen output, keeping conversions like PSI to bar or mmHg to kilopascals exact. Engineers, divers, medical staff, meteorologists, and mechanics all rely on a pressure converter to communicate safely across measurement systems.",
    example: {
      inputs: { value: "32", from: "psi", to: "bar" },
      explanation: "32 PSI (typical tire pressure) = 2.206 bar. In European countries, tire pressure is listed in bar, so a tire inflated to 32 PSI in the US should be inflated to 2.2 bar in Europe.",
    },
    faqs: [
      {
        question: "What is the difference between psi and bar?",
        answer: "PSI (pounds per square inch) and bar are both common pressure units. 1 bar = 14.5038 psi, and 1 psi = 0.0689476 bar. Bar is widely used in Europe and internationally; PSI dominates in the US. For tire pressure: US cars show 30–35 PSI; European cars show 2.0–2.4 bar. For scuba diving: a full tank is 200–300 bar (2,900–4,350 PSI). For espresso machines: standard extraction pressure is 9 bar (130 PSI).",
      },
      {
        question: "What is blood pressure measured in mmHg?",
        answer: "Blood pressure is measured in millimeters of mercury (mmHg) — a historical unit from when sphygmomanometers used actual mercury columns. Normal blood pressure is below 120/80 mmHg. In SI units, 1 mmHg = 133.322 pascals. The two numbers in blood pressure are systolic (peak pressure when heart contracts, normal < 120 mmHg) and diastolic (resting pressure between beats, normal < 80 mmHg). Despite the SI unit being kPa, mmHg remains universal in medicine for blood pressure.",
      },
      {
        question: "How does altitude affect atmospheric pressure?",
        answer: "Atmospheric pressure decreases with altitude because there is less air mass above you. At sea level: ~101,325 Pa (1 atm, 14.7 psi). At Denver, CO (5,280 ft / 1,609 m): ~83,000 Pa (0.82 atm). At the top of Mount Everest (8,849 m): ~33,700 Pa (0.33 atm). This lower pressure at altitude means water boils at lower temperatures (about 90°C at 3,000 m vs 100°C at sea level), affects engine performance, and requires supplemental oxygen above ~8,000 m.",
      },
      {
        question: "What is the difference between absolute and gauge pressure?",
        answer: "Absolute pressure is measured relative to a perfect vacuum (zero pressure). Gauge pressure is measured relative to the current atmospheric pressure. Most everyday pressure measurements (tire pressure, blood pressure, compressed air) are gauge pressure — they tell you how much above atmospheric pressure something is. A tire listed at 35 PSI gauge is actually 35 + 14.7 = 49.7 PSI absolute. In scientific and industrial contexts, absolute pressure is often used to avoid ambiguity caused by varying atmospheric pressure with altitude.",
      },
      {
        question: "Why do weathermen use hectopascals (hPa) for air pressure?",
        answer: "Weather forecasts use hectopascals (hPa) where 1 hPa = 100 Pa. This is numerically identical to millibar (mbar), a unit meteorologists used for decades — so switching to hPa preserved familiar numerical values (standard atmospheric pressure remains ~1,013 hPa or mbar). Weather maps show isobars (lines of equal pressure) in hPa; high pressure systems are ~1020–1030 hPa and indicate calm weather, while low pressure systems below ~1000 hPa often bring storms. Hurricanes can reach 870–900 hPa at their center.",
      },
    ],
    relatedCalculators: ["temperature", "energy-converter", "length-converter"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "energy-converter",
    slug: "energy-converter",
    category: "Converters",
    categorySlug: "converters",
    title: "Energy Converter",
    shortDescription: "Convert energy between joules, calories, kilowatt-hours, BTU, and more.",
    seoTitle: "Energy Converter — Joules, Calories, kWh, BTU",
    metaDescription: "Convert energy between joules, kilocalories, kilowatt-hours, BTU, foot-pounds, and more. Free online energy unit converter.",
    primaryKeyword: "energy converter",
    secondaryKeywords: ["joules to calories", "kWh to BTU", "energy unit converter", "calories to joules converter"],
    fields: [
      {
        id: "value",
        label: "Value",
        type: "number",
        placeholder: "Enter energy value",
        required: true,
      },
      {
        id: "from",
        label: "From",
        type: "select",
        defaultValue: "kilocalorie",
        required: true,
        unitOptions: ENERGY_UNITS,
      },
      {
        id: "to",
        label: "To",
        type: "select",
        defaultValue: "joule",
        required: true,
        unitOptions: ENERGY_UNITS,
      },
    ],
    results: [
      { id: "result", label: "Converted Energy", format: "number", decimals: 4, isPrimary: true },
    ],
    formula: "Convert to joules (SI base unit) then to target unit",
    formulaExplanation: "Energy conversion is exact because each unit represents a fixed quantity of joules, the SI unit of energy. The converter multiplies the input by its joule ratio to reach the shared base, then divides by the target unit's ratio to produce the answer, so no accuracy is lost across scales. Key ratios: 1 kcal = 4,184 J, 1 kWh = 3,600,000 J, 1 BTU = 1,055.06 J, and 1 cal = 4.184 J.",
    formulaSource: "International System of Units (SI) — NIST",
    sourceUrl: "https://www.nist.gov/pml/owm/metric-si/unit-conversion",
    explanation: "Energy is a fundamental physical quantity, yet the unit used to describe it depends entirely on context. Physics prefers joules, nutrition labels use kilocalories, electricity bills are calculated in kilowatt-hours, heating and cooling equipment is rated in BTUs, and chemistry often works in calories. An energy converter bridges these worlds so a figure from one domain can be understood in another.\n\nA frequent source of confusion is the calorie versus the Calorie. When a food label lists 200 calories, it means 200 kilocalories — a thousand times larger than the physical calorie of 4.184 joules. One kilowatt-hour is the energy a 1,000-watt appliance uses in an hour, equal to 3.6 million joules, and a typical US home consumes roughly 900 kWh each month. One BTU is the heat needed to warm a pound of water by one degree Fahrenheit, which makes it convenient for furnaces and air conditioners.\n\nBecause every unit has a fixed ratio to the joule, this energy converter normalises the input to joules first and then scales to the target, so pairings from electron volts to kilowatt-hours remain accurate. Physicists, dietitians, HVAC technicians, and utility analysts all depend on an energy converter to compare quantities that would otherwise be impossible to line up.",
    example: {
      inputs: { value: "2000", from: "kilocalorie", to: "joule" },
      explanation: "A 2,000 Calorie (kcal) daily diet equals 8,368,000 joules (8.37 megajoules) of energy. This is enough energy to lift a 1-ton car about 853 meters straight up.",
    },
    faqs: [
      {
        question: "What is the difference between a calorie and a Calorie (kcal)?",
        answer: "A 'calorie' (lowercase, also called a small calorie or gram calorie) is the energy needed to raise 1 gram of water by 1°C — equal to 4.184 joules. A 'Calorie' (uppercase, also called kilocalorie or kcal) is 1,000 times larger: the energy to raise 1 kilogram of water by 1°C. Food labels use Calories (kcal) — when a candy bar says '250 Calories,' it means 250 kcal = 250,000 small calories = 1,046,000 joules. The inconsistency of the same word referring to two different amounts causes endless confusion.",
      },
      {
        question: "How is energy related to power?",
        answer: "Power is the rate of energy use: Power = Energy / Time. A watt is 1 joule per second. A kilowatt-hour (kWh) is the energy used by a 1-kilowatt device for 1 hour: 1 kW × 1 hour = 1 kWh = 3,600,000 joules. Your electricity bill charges per kWh. A 100-watt light bulb running for 10 hours uses 1 kWh. Running it for 100 hours costs about $0.12 at average US electricity rates (~$0.12/kWh).",
      },
      {
        question: "What is a BTU and when is it used?",
        answer: "A BTU (British Thermal Unit) is the energy needed to heat one pound of water by one degree Fahrenheit — equal to 1,055.06 joules. BTUs are used extensively in HVAC (heating, ventilation, and air conditioning) to rate furnace output and air conditioner capacity. A 12,000 BTU/hour air conditioner (1 ton of cooling) can remove 12,000 BTUs of heat per hour. Home furnaces are rated in thousands of BTUs/hour (e.g., 80,000 BTU/hr). The US also uses BTU for gas appliances and natural gas billing.",
      },
      {
        question: "How much energy is in a gallon of gasoline?",
        answer: "A gallon of regular gasoline contains about 132,000 BTU or 139,000 kJ (139 megajoules) of chemical energy. However, internal combustion engines convert only about 20–40% of this to motion — the rest becomes heat. So a gallon effectively delivers 26,000–53,000 BTU of mechanical energy. An electric vehicle uses about 25–35 kWh per 100 miles; at $0.12/kWh, that's $3–4.20 vs. a gas car at 30 mpg spending about $3.60 at $3/gallon for the same 100 miles.",
      },
      {
        question: "What is an electron volt (eV) and when is it used?",
        answer: "An electron volt is the kinetic energy gained by an electron accelerated through 1 volt of electric potential: 1 eV = 1.602 × 10⁻¹⁹ joules. It's an extremely small unit used in atomic and particle physics, where joules are too large to be convenient. Visible light photons have energies of 1.8–3.1 eV. Chemical bond energies are typically 1–10 eV. X-ray photons are thousands of eV (keV). Nuclear reactions involve millions of eV (MeV). The Large Hadron Collider accelerates particles to trillions of eV (TeV).",
      },
    ],
    relatedCalculators: ["temperature", "pressure-converter", "calories-burned"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "cooking-measurement",
    slug: "cooking-measurement-converter",
    category: "Converters",
    categorySlug: "converters",
    title: "Cooking Measurement Converter",
    shortDescription: "Convert between cups, tablespoons, teaspoons, milliliters, and other cooking measurements.",
    seoTitle: "Cooking Measurement Converter — Cups, Tbsp, tsp, mL",
    metaDescription: "Convert cooking measurements: cups to ml, tablespoons to teaspoons, pints to cups, and more. Free online kitchen unit converter for recipes.",
    primaryKeyword: "cooking measurement converter",
    secondaryKeywords: ["cups to ml", "tablespoon to teaspoon", "cooking unit converter", "recipe converter", "measurement converter"],
    fields: [
      {
        id: "value",
        label: "Amount",
        type: "number",
        placeholder: "e.g. 2",
        required: true,
      },
      {
        id: "from",
        label: "From",
        type: "select",
        defaultValue: "cup",
        required: true,
        unitOptions: [
          { value: "ml", label: "Milliliters (mL)" },
          { value: "liter", label: "Liters (L)" },
          { value: "cup", label: "Cups (US)" },
          { value: "tablespoon", label: "Tablespoons (tbsp)" },
          { value: "teaspoon", label: "Teaspoons (tsp)" },
          { value: "flOz", label: "Fluid Ounces (fl oz)" },
          { value: "pint", label: "Pints (US)" },
          { value: "quart", label: "Quarts (US)" },
          { value: "gallon", label: "Gallons (US)" },
          { value: "stick", label: "Sticks of Butter (US)" },
        ],
      },
      {
        id: "to",
        label: "To",
        type: "select",
        defaultValue: "ml",
        required: true,
        unitOptions: [
          { value: "ml", label: "Milliliters (mL)" },
          { value: "liter", label: "Liters (L)" },
          { value: "cup", label: "Cups (US)" },
          { value: "tablespoon", label: "Tablespoons (tbsp)" },
          { value: "teaspoon", label: "Teaspoons (tsp)" },
          { value: "flOz", label: "Fluid Ounces (fl oz)" },
          { value: "pint", label: "Pints (US)" },
          { value: "quart", label: "Quarts (US)" },
          { value: "gallon", label: "Gallons (US)" },
          { value: "stick", label: "Sticks of Butter (US)" },
        ],
      },
    ],
    results: [
      { id: "result", label: "Converted Amount", format: "number", decimals: 4, isPrimary: true },
    ],
    formula: "Convert through mL as common base. Key: 1 cup = 240 mL; 1 tbsp = 15 mL; 1 tsp = 5 mL; 1 stick butter = 8 tbsp = 120 mL",
    formulaExplanation: "Cooking conversion works because each kitchen unit is defined as a fixed multiple of the milliliter, so the converter normalises any amount to mL and then scales to the target. The US customary chain is exact: 1 cup = 16 tbsp = 48 tsp = 8 fl oz = 240 mL, 3 tsp = 1 tbsp, and 1 stick of butter = 8 tbsp = 1/2 cup = 120 mL (about 113 g).",
    formulaSource: "Standard cooking measurement conversions",
    explanation: "A cooking measurement converter is indispensable when you follow recipes from other countries, scale a dish up or down, or find yourself missing a particular measuring tool. The US customary system of cups, tablespoons, and teaspoons differs from the metric measurements used across most of the world, and a reliable cooking measurement converter removes the guesswork.\n\nThe core US relationships are worth memorising: 3 teaspoons make 1 tablespoon, 16 tablespoons make 1 cup, 2 cups make 1 pint, 2 pints make 1 quart, and 4 quarts make 1 gallon. One cup equals 240 mL under the nutrition-label definition, or 236.588 mL by the precise US gallon.\n\nAmerican recipes often list butter in sticks, where one stick equals 1/2 cup, 8 tablespoons, or 113 grams, while European recipes sell butter by weight and specify grams. For dry ingredients, weighing in grams is more accurate than measuring by volume, because density changes with packing — a cup of firmly packed brown sugar weighs far more than a cup of sifted flour. Home cooks, bakers, and anyone adapting international recipes rely on a cooking measurement converter to get consistent, repeatable results.",
    example: {
      inputs: { value: "1", from: "cup", to: "ml" },
      explanation: "1 US cup = 240 mL. If an American recipe calls for 2 cups of flour and your measuring cups show mL, you need 480 mL total.",
    },
    faqs: [
      {
        question: "How many tablespoons are in a cup?",
        answer: "There are exactly 16 tablespoons in 1 US cup. The full breakdown: 1 cup = 16 tablespoons = 48 teaspoons = 8 fluid ounces = 240 mL. For quick half-measures: 1/2 cup = 8 tablespoons; 1/4 cup = 4 tablespoons; 1/8 cup = 2 tablespoons. When a recipe calls for an odd fraction like 1/3 cup, that equals 5 tablespoons plus 1 teaspoon (5.33 tablespoons total).",
      },
      {
        question: "How do I convert cups to milliliters?",
        answer: "1 US cup = 240 mL (the standard used on nutrition labels and in most recipe contexts). So 2 cups = 480 mL, 1/2 cup = 120 mL, 1/4 cup = 60 mL. Note: Australian and Canadian metric cups are 250 mL, not 240 mL. For precise baking from international recipes, check the origin of the recipe to use the right cup size. The 10 mL difference (4%) is negligible for most recipes but can matter in very precise baking.",
      },
      {
        question: "How many sticks of butter is 1 cup?",
        answer: "Two sticks of butter equal 1 cup. One stick = 1/2 cup = 8 tablespoons = 113 grams ≈ 4 oz. In the US, butter is sold in 4-stick packages (1 pound total = 2 cups). European butter is sold by weight; 1 US stick = 113 grams. If a recipe calls for 1 cup of butter, you need 2 sticks; 1/4 cup = half a stick = 4 tablespoons = 56.5 grams.",
      },
      {
        question: "Why are dry ingredient measurements less accurate in cups?",
        answer: "Volume measurements for dry ingredients are inherently imprecise because density varies with how tightly the ingredient is packed. A cup of sifted all-purpose flour weighs about 120g, while a cup of packed flour can weigh up to 160g — a 33% difference that can significantly affect baking. Professional bakers weigh dry ingredients in grams or ounces for consistency. For liquid ingredients, volume measurement is fine since liquids have consistent density. When baking precision matters, use a kitchen scale for dry ingredients.",
      },
      {
        question: "What is the difference between US and metric/Australian cups?",
        answer: "A US cup is 240 mL (based on the US gallon: 1 gallon / 16 = 236.588 mL, rounded to 240 for nutrition). An Australian metric cup is 250 mL. For most recipes, the 10 mL (4%) difference is negligible. However, for very precise baking or large-scale recipes, use cups from the same system as the recipe. If a recipe is from an Australian cookbook and calls for 3 cups of liquid, using 3 US cups gives 720 mL vs. the intended 750 mL — a 4% difference.",
      },
    ],
    relatedCalculators: ["volume-converter", "weight-converter", "bmi"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
];
