import type { CalculatorDefinition } from "../types";

export const cookingWave3Calculators: CalculatorDefinition[] = [
  {
    id: "recipe-scaler",
    slug: "recipe-scaler-calculator",
    category: "Cooking",
    categorySlug: "cooking",
    title: "Recipe Scaler Calculator",
    shortDescription: "Scale any recipe up or down by servings.",
    seoTitle: "Recipe Scaler Calculator — Adjust Servings and Ingredients",
    metaDescription: "Free recipe scaler calculator. Enter original and desired servings to get an exact scaling factor and instantly resize any ingredient amount up or down.",
    primaryKeyword: "recipe scaler calculator",
    secondaryKeywords: ["recipe scaling calculator", "adjust recipe servings", "recipe multiplier calculator"],
    fields: [
      { id: "originalServings", label: "Original servings", type: "number", required: true, span: 1, min: 0, helpText: "Servings the recipe is written for." },
      { id: "desiredServings", label: "Desired servings", type: "number", required: true, span: 1, min: 0 },
      { id: "ingredientAmount", label: "Ingredient amount", type: "number", required: false, span: 2, min: 0, helpText: "Optional — enter one quantity to see its scaled amount." },
    ],
    results: [
      { id: "scaleFactor", label: "Scale factor", format: "number", decimals: 3, unit: "×", isPrimary: true },
      { id: "scaledAmount", label: "Scaled ingredient amount", format: "number", decimals: 3, isPrimary: false },
    ],
    formula: "scale factor = desired servings ÷ original servings",
    formulaExplanation: "Scaling a recipe means keeping every ingredient in the same proportion while changing the total yield. Dividing the desired servings by the original servings gives one factor that every quantity is multiplied by, so ratios stay intact. The method works because a recipe is a set of fixed proportions, and multiplying them all by the same number preserves those proportions at any batch size.",
    explanation: "Scaling a recipe up for a crowd or down for a couple comes down to one number, and this recipe scaler calculator finds it for you and applies it to any ingredient you enter. You supply the servings the recipe was written for and the servings you actually want, and the tool returns the exact scaling factor along with the resized amount of whichever ingredient you type in.\n\nGetting the factor right matters because eyeballing a doubled or halved recipe is where mistakes creep in, especially with awkward numbers like taking a recipe for four up to seven. A recipe scaler calculator removes the mental arithmetic so every quantity stays in the same proportion, keeping the balance of the dish intact whether you are batch-cooking for a party or shrinking a family favourite for a solo dinner.\n\nThe factor works because a recipe is really a set of ratios, and multiplying them all by the same number preserves those ratios at any size. A couple of things do not scale linearly, though: salt, strong spices, and leavening often need a lighter touch when multiplied, and cooking time shifts with pan depth rather than volume. Home cooks, caterers, and meal-preppers all lean on a recipe scaler calculator to resize dishes quickly and taste-check the seasoning afterwards.",
    example: { inputs: { originalServings: 4, desiredServings: 6, ingredientAmount: 2 }, explanation: "6 ÷ 4 = 1.5× scale factor, so 2 cups becomes 2 × 1.5 = 3 cups." },
    faqs: [
      {
        question: "How does the recipe scaler calculate the factor?",
        answer: "The tool divides your desired number of servings by the original number of servings the recipe was written for. That single figure is the scale factor, and multiplying any ingredient by it gives the new amount. Taking a recipe for four up to six produces a factor of 1.5, so every quantity grows by half again. The factor keeps all ingredient ratios perfectly in proportion at the new yield.",
      },
      {
        question: "Do I have to enter an ingredient amount?",
        answer: "No, the ingredient field is optional. If you only want the scale factor, leave it blank and the calculator still returns the multiplier to apply yourself. Entering one quantity is handy when you want to check a specific ingredient, such as how many grams of flour a doubled batch needs. You can re-enter different amounts one at a time to convert each line of a recipe in turn.",
      },
      {
        question: "Does seasoning scale the same way as other ingredients?",
        answer: "Not always. Bulk ingredients like flour, sugar, and liquid scale cleanly with the factor, but salt, strong spices, garlic, and chilli often taste too intense when multiplied straight. A safe habit is to scale them to about three-quarters of the factor, then taste and adjust. Leavening agents such as baking powder can also behave differently in larger batches, so treat those numbers as a starting point rather than a rule.",
      },
      {
        question: "Why doesn't cooking time scale with the recipe?",
        answer: "Cooking time depends on how heat penetrates the food, which is governed by thickness and surface area, not total volume. A doubled cake batter in a deeper tin needs longer, while the same batter spread across two tins bakes in roughly the original time. Because of this, keep an eye on doneness cues — colour, internal temperature, a clean skewer — instead of assuming the time scales by the same factor.",
      },
      {
        question: "Can I scale a recipe down to a single serving?",
        answer: "Yes. Enter the original servings and set the desired servings to one, and the calculator produces a fractional factor to shrink every ingredient. Very small amounts can become hard to measure accurately, so lean on a kitchen scale and measuring spoons for tiny quantities. For ingredients like a single egg that cannot be neatly divided, round sensibly and adjust the surrounding quantities to keep the dish balanced.",
      },
    ],
    relatedCalculators: ["baking-conversion-calculator", "cooking-time-calculator", "cooking-measurement-converter"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard cooking conversions",
  },
  {
    id: "baking-conversion",
    slug: "baking-conversion-calculator",
    category: "Cooking",
    categorySlug: "cooking",
    title: "Baking Conversion Calculator",
    shortDescription: "Convert cups to grams for common baking ingredients.",
    seoTitle: "Baking Conversion Calculator — Cups to Grams and Back",
    metaDescription: "Free baking conversion calculator. Convert cups to grams and grams to cups for flour, sugar, butter, and water using accurate per-ingredient densities.",
    primaryKeyword: "baking conversion calculator",
    secondaryKeywords: ["cups to grams calculator", "grams to cups calculator", "baking measurement converter"],
    fields: [
      {
        id: "ingredient",
        label: "Ingredient",
        type: "select",
        required: true,
        span: 2,
        defaultValue: "flour",
        options: [
          { value: "flour", label: "Flour" },
          { value: "sugar", label: "Sugar" },
          { value: "butter", label: "Butter" },
          { value: "water", label: "Water" },
        ],
      },
      { id: "amount", label: "Amount", type: "number", required: true, span: 2, min: 0 },
      {
        id: "fromUnit",
        label: "From unit",
        type: "select",
        required: true,
        span: 1,
        defaultValue: "cups",
        options: [
          { value: "cups", label: "Cups" },
          { value: "grams", label: "Grams" },
        ],
      },
      {
        id: "toUnit",
        label: "To unit",
        type: "select",
        required: true,
        span: 1,
        defaultValue: "grams",
        options: [
          { value: "cups", label: "Cups" },
          { value: "grams", label: "Grams" },
        ],
      },
    ],
    results: [
      { id: "result", label: "Converted amount", format: "number", decimals: 2, isPrimary: true },
    ],
    formula: "grams = cups × density  ·  cups = grams ÷ density",
    formulaExplanation: "A cup is a fixed volume, but each ingredient has a different mass packed into that volume, so conversion depends on density. Multiplying cups by an ingredient's grams-per-cup density gives its weight, while dividing grams by the same density recovers the volume. The approach works because density is the mass-to-volume ratio, and it differs for flour, sugar, butter, and water, which is why one blanket factor cannot serve them all.",
    explanation: "Baking rewards precision, and this baking conversion calculator turns cup measurements into grams and grams back into cups using the correct density for each ingredient. Cups measure volume while grams measure weight, and because a cup of flour weighs far less than a cup of sugar or butter, a single conversion number will not do — the tool applies the right grams-per-cup figure for flour, sugar, butter, or water automatically.\n\nThis accuracy matters because baking is closer to chemistry than freestyle cooking. A cup of flour can vary by a third depending on how it is scooped and packed, and that difference is enough to leave a cake dry or a dough slack. Weighing ingredients in grams removes that ambiguity, so a baking conversion calculator lets you follow a metric recipe with cup-only measuring tools, or bring a favourite cup recipe onto a kitchen scale for repeatable results every time.\n\nThe conversion works because density is the ratio of mass to volume, and it is fixed for each ingredient. Flour sits near 120 grams per cup, granulated sugar around 200, butter about 227, and water roughly 236. Multiplying cups by that density yields grams, and dividing grams by it returns cups. Bakers, recipe writers, and anyone juggling metric and imperial recipes rely on a baking conversion calculator to swap units without second-guessing.",
    example: { inputs: { ingredient: "flour", amount: 2, fromUnit: "cups", toUnit: "grams" }, explanation: "2 cups of flour × 120 g per cup = 240 g." },
    faqs: [
      {
        question: "Why can't I use one conversion for every ingredient?",
        answer: "Because a cup measures volume, not weight, and different ingredients pack different amounts of mass into the same cup. A cup of flour weighs about 120 grams, but a cup of granulated sugar weighs roughly 200 grams and a cup of butter about 227. Using a single number would throw off any recipe. This calculator stores a separate density for each ingredient so the conversion reflects what you are actually measuring.",
      },
      {
        question: "Which ingredients does the calculator support?",
        answer: "It covers four common baking staples: flour at about 120 grams per cup, granulated sugar at 200, butter at 227, and water at 236 grams per cup. These densities match widely used baking references. If your ingredient is not listed, pick the closest match by texture — most all-purpose and bread flours sit near the flour figure, while syrups and milk behave much like water in weight per cup.",
      },
      {
        question: "How accurate are cup-to-gram conversions?",
        answer: "The gram figures are reliable, but the real variability lives in how you fill a cup. Scooping flour straight from the bag compacts it and can add up to a third more weight than the standard density assumes. For the most consistent results, spoon flour lightly into the cup and level it off, or better still weigh directly in grams. The calculator uses standard densities that suit properly measured cups.",
      },
      {
        question: "Can I convert grams back into cups?",
        answer: "Yes. Set the from-unit to grams and the to-unit to cups, and the calculator divides your gram amount by the ingredient's density to return the equivalent volume. This is useful when a recipe lists weights but you only own measuring cups. Keep in mind that fractional cup results, like 0.75 cups, are easiest to measure with a set of graduated cups or by converting to tablespoons where needed.",
      },
      {
        question: "Does the same weight of flour and sugar fill the same volume?",
        answer: "No. Because sugar is denser than flour, 200 grams of sugar occupies about one cup while 200 grams of flour fills closer to one and two-thirds cups. This is exactly why weight-based baking is more dependable than volume-based baking. Whenever a recipe matters, converting everything to grams with this tool removes the guesswork that comes from swapping ingredients of different densities cup for cup.",
      },
    ],
    relatedCalculators: ["recipe-scaler-calculator", "cooking-time-calculator", "cooking-measurement-converter"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard cooking conversions",
  },
  {
    id: "cooking-time",
    slug: "cooking-time-calculator",
    category: "Cooking",
    categorySlug: "cooking",
    title: "Cooking Time Calculator",
    shortDescription: "Estimate roasting time by meat type and weight.",
    seoTitle: "Cooking Time Calculator — Roasting Time by Weight",
    metaDescription: "Free cooking time calculator. Choose beef, chicken, pork, or turkey and enter the weight to estimate roasting time plus the safe internal target temperature.",
    primaryKeyword: "cooking time calculator",
    secondaryKeywords: ["roasting time calculator", "meat cooking time calculator", "roast timing calculator"],
    fields: [
      {
        id: "meatType",
        label: "Meat type",
        type: "select",
        required: true,
        span: 1,
        defaultValue: "chicken",
        options: [
          { value: "beef", label: "Beef" },
          { value: "chicken", label: "Chicken" },
          { value: "pork", label: "Pork" },
          { value: "turkey", label: "Turkey" },
        ],
      },
      { id: "weight", label: "Weight", type: "number", unit: "lb", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "cookingTime", label: "Estimated cooking time", format: "number", decimals: 0, unit: "min", isPrimary: true },
      { id: "targetTemp", label: "Safe internal temperature", format: "text", isPrimary: false },
    ],
    formula: "cooking time = weight × minutes per pound",
    formulaExplanation: "Roasting time scales with weight because heat has to travel from the surface to the centre, and a heavier joint has more mass to warm through. Multiplying the weight by a per-pound rate for each meat gives a working estimate. The rates differ by meat because target doneness and density vary, which is why the guide always pairs the time with a safe internal temperature to confirm the roast is truly done.",
    explanation: "Timing a roast is guesswork until you anchor it to weight, and this cooking time calculator estimates how long beef, chicken, pork, or turkey needs based on how much it weighs. Pick the meat, enter the weight in pounds, and the tool multiplies by a sensible per-pound rate to give a starting roasting time, alongside the safe internal temperature you should confirm with a thermometer before serving.\n\nThis matters because undercooked poultry and pork carry real food-safety risks, while overcooking dries out an expensive cut. A cooking time calculator gives you a reliable schedule so you can plan when the oven goes on and when the rest of the meal should be ready. Beef and chicken sit around twenty minutes per pound, pork closer to twenty-five, and turkey nearer fifteen, reflecting how each meat behaves in a hot oven.\n\nThe estimate works because heat penetrates a roast from the outside in, so more mass takes proportionally longer to reach a safe centre. The time is a guide, not a guarantee: oven accuracy, bone content, starting temperature, and whether the joint is stuffed all shift the real figure. That is why the calculator pairs every estimate with a target internal temperature — the only foolproof test of doneness. Home cooks planning Sunday lunch or a holiday feast lean on a cooking time calculator to bring the whole meal together on time.",
    example: { inputs: { meatType: "chicken", weight: 3 }, explanation: "3 lb chicken × 20 minutes per pound = 60 minutes, roasted to 74°C (165°F)." },
    faqs: [
      {
        question: "How does the calculator estimate cooking time?",
        answer: "It multiplies the weight you enter by a per-pound roasting rate chosen for the meat type. Beef and chicken use about twenty minutes per pound, pork twenty-five, and turkey fifteen. So a three-pound chicken comes to sixty minutes. These rates assume a standard roasting oven around 180°C, so treat the result as a well-grounded starting point and always verify doneness with a meat thermometer before serving.",
      },
      {
        question: "Why does the calculator show a target temperature?",
        answer: "Time alone never guarantees a roast is safely cooked, because ovens, cuts, and starting temperatures vary. The safe internal temperature is the definitive test: 74°C for chicken and turkey, and 63°C for beef and pork with a rest afterwards. Insert a thermometer into the thickest part, avoiding bone, and cook until it reads the target. Pairing time with temperature is the reliable way to avoid both undercooking and overcooking.",
      },
      {
        question: "Does bone-in meat change the cooking time?",
        answer: "It can. Bone conducts heat differently and changes how quickly the surrounding meat warms, so bone-in roasts sometimes cook a little faster near the bone but slower in dense muscle. Stuffing a bird also adds significant time because the heat must penetrate the filling to a safe temperature too. Use the estimate as a schedule, then rely on a thermometer in the thickest section to decide when it is genuinely ready.",
      },
      {
        question: "Should I rest the meat after cooking?",
        answer: "Yes. Resting lets the juices redistribute and the internal temperature climb a few more degrees through carry-over cooking, which is why you can pull larger roasts slightly before the target. Rest small cuts for around ten minutes and large joints or whole birds for fifteen to thirty under loose foil. Skipping the rest lets juices run out when you carve, leaving the meat drier despite perfect timing in the oven.",
      },
      {
        question: "Can I use this for other meats or oven temperatures?",
        answer: "The calculator covers beef, chicken, pork, and turkey at typical roasting temperatures, and any meat not listed defaults to the beef rate as a rough guide. Cooking at a markedly higher or lower oven temperature will shift the real time, as will fan versus conventional heat. Whenever you change conditions, keep the target internal temperature as your anchor and adjust the schedule around your thermometer readings rather than the clock alone.",
      },
    ],
    relatedCalculators: ["recipe-scaler-calculator", "baking-conversion-calculator", "cooking-measurement-converter"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard roasting guidance",
  },
];
