import type { CalculatorDefinition } from "../types";

export const dateTimeWave2Calculators: CalculatorDefinition[] = [
  {
    id: "date-difference",
    slug: "date-difference-calculator",
    category: "Date & Time",
    categorySlug: "date-time",
    title: "Date Difference Calculator",
    shortDescription: "Calculate the exact difference between two dates in years, months, weeks, and days.",
    seoTitle: "Date Difference Calculator — Days Between Two Dates",
    metaDescription: "Calculate the exact number of days, weeks, months, and years between any two dates. Free online date difference calculator with instant results.",
    primaryKeyword: "date difference calculator",
    secondaryKeywords: ["days between dates", "how many days between", "days calculator", "time between dates"],
    fields: [
      {
        id: "startDate",
        label: "Start Date",
        type: "date",
        required: true,
      },
      {
        id: "endDate",
        label: "End Date",
        type: "date",
        required: true,
      },
    ],
    results: [
      { id: "totalDays", label: "Total Days", format: "number", decimals: 0, isPrimary: true },
      { id: "totalWeeks", label: "Total Weeks", format: "number", decimals: 2, isPrimary: false },
      { id: "totalMonths", label: "Total Months (approx.)", format: "number", decimals: 1, isPrimary: false },
      { id: "years", label: "Years", format: "number", decimals: 0, isPrimary: false },
      { id: "months", label: "Remaining Months", format: "number", decimals: 0, isPrimary: false },
      { id: "days", label: "Remaining Days", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Days = (End Date − Start Date) in milliseconds / 86,400,000",
    formulaExplanation: "The difference is computed by subtracting start date from end date timestamps (milliseconds since Unix epoch) then dividing by milliseconds per day. Years, months, and remaining days are computed by incrementally counting calendar periods.",
    formulaSource: "Standard calendar arithmetic",
    explanation: "The date difference calculator tells you exactly how much time has elapsed between any two dates. This is more complex than it sounds because months have different lengths and leap years add extra days, meaning you can't simply divide days by 30 for months.\n\nThe calculation starts by finding the total number of days between the two dates — this is precise. From there, we can compute total weeks (days / 7) and an approximate month count (days / 30.44). For the year/month/day breakdown, we count actual calendar periods to account for varying month lengths and leap years.\n\nDate differences are essential for countless real-world needs: calculating how old someone is, how many days until an event, how long a project took, contract durations, loan terms, and anniversary tracking.\n\nNote that the total months figure is an approximation based on average month length (30.44 days). For exact month differences, the year/month/day breakdown at the bottom is more precise, using actual calendar counting.",
    example: {
      inputs: { startDate: "2024-01-01", endDate: "2025-01-01" },
      explanation: "From January 1, 2024 to January 1, 2025 is exactly 366 days (2024 is a leap year), which equals 52.3 weeks and exactly 12 months with 0 remaining days.",
    },
    faqs: [
      {
        question: "Why is the month count approximate?",
        answer: "Months have different lengths — January has 31 days, February has 28 or 29, April has 30, etc. There is no universal definition of 'exactly 1 month' in days. Our calculator shows two approaches: an approximate month count based on average month length (30.4375 days, accounting for leap years) and a precise year/month/day breakdown that actually counts through the calendar. For most purposes, the breakdown is more accurate; use the approximate figure only for rough estimates.",
      },
      {
        question: "Does this calculator account for leap years?",
        answer: "Yes. The total days count is completely accurate and automatically accounts for leap years, since it's based on actual date arithmetic (counting milliseconds between calendar dates). A leap year has 366 days instead of 365, so any date range that spans February 29 in a leap year will correctly include that day. Leap years occur every 4 years, except century years unless divisible by 400 — so 2000 was a leap year but 1900 was not.",
      },
      {
        question: "Can I calculate dates far in the past or future?",
        answer: "Yes, this calculator can handle dates across a wide range of years. JavaScript's date arithmetic supports dates from approximately year 271,821 BCE to 275,760 CE — far beyond any practical need. However, for historical dates before the Gregorian calendar reform (October 15, 1582), the calculator uses the proleptic Gregorian calendar, which may not match historical dates recorded in the Julian calendar. If you're working with pre-1582 historical dates, verify results with a specialized historical date converter.",
      },
      {
        question: "How do I calculate dates including or excluding the start date?",
        answer: "Our calculator gives the number of days between the start and end dates, not including the start day itself (this is the standard mathematical convention). To include the start date, add 1 to the result. For example, from January 1 to January 5: the difference is 4 days (Jan 2, 3, 4, 5 passed), but if you're counting inclusive of both endpoints (Jan 1, 2, 3, 4, 5), that's 5 days. For project duration purposes where you want to count each working day, use the inclusive count (add 1).",
      },
      {
        question: "What is the difference between date difference and age calculation?",
        answer: "Both measure time elapsed, but with a key distinction. Date difference simply counts calendar units between two dates. Age calculation (as used in birthday contexts) applies a specific rule: your age increases only when your birthday date is reached. So if today is March 15 and your birthday is June 15, you're still the previous year's age even if 8 months have passed since your last birthday. Our dedicated Age Calculator handles this birthday-based calculation, while this calculator focuses on the raw time difference between any two dates.",
      },
    ],
    slugEs: "calculadora-de-diferencia-de-fechas",
    titleEs: "Calculadora de Diferencia de Fechas",
    shortDescriptionEs: "Calcula la diferencia exacta entre dos fechas en años, meses, semanas y días.",
    seoTitleEs: "Calculadora de Diferencia de Fechas — Días Entre Dos Fechas",
    metaDescriptionEs: "Calcula el número exacto de días, semanas, meses y años entre dos fechas cualesquiera. Calculadora de diferencia de fechas en línea gratuita con resultados instantáneos.",
    primaryKeywordEs: "calculadora de diferencia de fechas",
    secondaryKeywordsEs: ["dias entre fechas", "cuantos dias entre fechas", "calculadora de dias", "tiempo entre fechas"],
    formulaExplanationEs: "La diferencia se calcula restando la fecha de inicio de la fecha final usando sus marcas de tiempo (milisegundos desde la época Unix) y dividiendo luego entre los milisegundos por día. Los años, los meses y los días restantes se obtienen contando de forma incremental los periodos de calendario reales, lo que respeta la longitud desigual de los meses y los años bisiestos en lugar de suponer treinta días por mes.",
    explanationEs: "La calculadora de diferencia de fechas te dice exactamente cuánto tiempo ha transcurrido entre dos fechas cualesquiera. Esto es más complejo de lo que parece porque los meses tienen longitudes diferentes y los años bisiestos añaden días adicionales, lo que significa que no puedes simplemente dividir los días entre 30 para obtener los meses.\n\nEl cálculo comienza encontrando el número total de días entre las dos fechas — esta cifra es precisa. A partir de ahí, se pueden calcular las semanas totales (días / 7) y un conteo aproximado de meses (días / 30,44). Para el desglose de años, meses y días, contamos los periodos de calendario reales para tener en cuenta las distintas longitudes de los meses y los años bisiestos.\n\nLas diferencias de fechas son esenciales para innumerables necesidades del mundo real: calcular la edad de alguien, cuántos días faltan para un evento, cuánto duró un proyecto, la duración de contratos, los plazos de préstamos y el seguimiento de aniversarios.\n\nTen en cuenta que la cifra de meses totales es una aproximación basada en la longitud media de un mes (30,44 días). Para diferencias exactas de meses, el desglose de años, meses y días de la parte inferior es más preciso, ya que utiliza el conteo real del calendario.",
    exampleEs: {
      inputs: { startDate: "2024-01-01", endDate: "2025-01-01" },
      explanation: "Del 1 de enero de 2024 al 1 de enero de 2025 hay exactamente 366 días (2024 es un año bisiesto), lo que equivale a 52,3 semanas y exactamente 12 meses con 0 días restantes.",
    },
    faqsEs: [
      { question: "¿Por qué el conteo de meses es aproximado?", answer: "Los meses tienen longitudes diferentes: enero tiene 31 días, febrero tiene 28 o 29, abril tiene 30, etcétera. No existe una definición universal de 'exactamente 1 mes' en días. Nuestra calculadora muestra dos enfoques: un conteo aproximado de meses basado en la longitud media (30,4375 días, teniendo en cuenta los años bisiestos) y un desglose preciso de años, meses y días que recorre realmente el calendario. Para la mayoría de los propósitos, el desglose es más exacto; usa la cifra aproximada solo para estimaciones rápidas." },
      { question: "¿Esta calculadora tiene en cuenta los años bisiestos?", answer: "Sí. El conteo de días totales es completamente exacto y tiene en cuenta automáticamente los años bisiestos, ya que se basa en la aritmética real de fechas (contando milisegundos entre fechas de calendario). Un año bisiesto tiene 366 días en lugar de 365, por lo que cualquier rango de fechas que abarque el 29 de febrero de un año bisiesto incluirá correctamente ese día. Los años bisiestos ocurren cada 4 años, salvo los años de siglo a menos que sean divisibles entre 400 — así que 2000 fue bisiesto pero 1900 no." },
      { question: "¿Puedo calcular fechas muy lejanas en el pasado o el futuro?", answer: "Sí, esta calculadora puede manejar fechas en un amplio rango de años. La aritmética de fechas de JavaScript admite fechas desde aproximadamente el año 271.821 a. C. hasta el 275.760 d. C. — mucho más allá de cualquier necesidad práctica. Sin embargo, para fechas históricas anteriores a la reforma del calendario gregoriano (15 de octubre de 1582), la calculadora usa el calendario gregoriano proléptico, que puede no coincidir con fechas registradas en el calendario juliano. Si trabajas con fechas anteriores a 1582, verifica los resultados con un convertidor histórico especializado." },
      { question: "¿Cómo calculo fechas incluyendo o excluyendo la fecha de inicio?", answer: "Nuestra calculadora da el número de días entre las fechas de inicio y fin, sin incluir el día de inicio en sí (esta es la convención matemática estándar). Para incluir la fecha de inicio, suma 1 al resultado. Por ejemplo, del 1 al 5 de enero: la diferencia es de 4 días (pasaron el 2, 3, 4 y 5 de enero), pero si cuentas de forma inclusiva ambos extremos (1, 2, 3, 4, 5), son 5 días. Para la duración de proyectos donde quieres contar cada día laborable, usa el conteo inclusivo (suma 1)." },
      { question: "¿Cuál es la diferencia entre la diferencia de fechas y el cálculo de la edad?", answer: "Ambas miden el tiempo transcurrido, pero con una distinción clave. La diferencia de fechas simplemente cuenta unidades de calendario entre dos fechas. El cálculo de la edad (como se usa en contextos de cumpleaños) aplica una regla específica: tu edad aumenta solo cuando se alcanza la fecha de tu cumpleaños. Así, si hoy es 15 de marzo y tu cumpleaños es el 15 de junio, sigues teniendo la edad del año anterior aunque hayan pasado 8 meses desde tu último cumpleaños. Nuestra Calculadora de Edad dedicada gestiona ese cálculo basado en el cumpleaños, mientras que esta se centra en la diferencia de tiempo bruta entre dos fechas cualesquiera." },
    ],
    relatedCalculators: ["age-calculator", "business-days-calculator", "countdown"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "business-days",
    slug: "business-days-calculator",
    category: "Date & Time",
    categorySlug: "date-time",
    title: "Business Days Calculator",
    shortDescription: "Calculate the number of business days (weekdays) between two dates, excluding weekends.",
    seoTitle: "Business Days Calculator — Working Days Between Dates",
    metaDescription: "Count the number of business days (Monday–Friday) between any two dates, excluding weekends. Free online working days calculator.",
    primaryKeyword: "business days calculator",
    secondaryKeywords: ["working days calculator", "weekdays between dates", "business day counter", "workdays calculator"],
    fields: [
      {
        id: "startDate",
        label: "Start Date",
        type: "date",
        required: true,
      },
      {
        id: "endDate",
        label: "End Date",
        type: "date",
        required: true,
      },
    ],
    results: [
      { id: "businessDays", label: "Business Days", format: "number", decimals: 0, isPrimary: true },
      { id: "weekendDays", label: "Weekend Days", format: "number", decimals: 0, isPrimary: false },
      { id: "totalDays", label: "Total Calendar Days", format: "number", decimals: 0, isPrimary: false },
      { id: "weeks", label: "Full Weeks", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Business days = total days − weekend days (Saturday + Sunday in range)",
    formulaExplanation: "Business days count only Monday through Friday. Weekends are excluded by calculating the number of complete weeks (each contributing 5 business days) and adding the weekday count of any partial week at the start or end.",
    formulaSource: "Standard business calendar definition",
    explanation: "Business days (also called working days or weekdays) are the days Monday through Friday, excluding weekends. This distinction matters enormously in business, legal, and financial contexts where deadlines and processing times are measured in business days, not calendar days.\n\nWhen a company says 'allow 5–7 business days for delivery,' they mean working days excluding Saturday and Sunday. A shipment sent on Friday that takes 5 business days will arrive the following Friday, not the following Wednesday. Legal contracts, government agencies, and financial institutions typically define timeframes in business days.\n\nThis calculator counts all weekdays (Monday through Friday) in the date range. Note that public holidays are not automatically excluded because holidays vary by country, region, and industry. If you need to exclude specific holidays, subtract them from the business days result.\n\nFor project management, business day calculations help set realistic timelines, especially across weekends or when a deadline falls mid-week.",
    example: {
      inputs: { startDate: "2025-01-06", endDate: "2025-01-17" },
      explanation: "From Monday January 6 to Friday January 17, 2025: there are 10 calendar days (the 7th through 16th, plus the 17th), including 2 full weekends. Business days = 10 weekdays (2 full work weeks).",
    },
    faqs: [
      {
        question: "Does this calculator exclude public holidays?",
        answer: "No — public holidays are not automatically excluded because they vary significantly by country, state, company, and industry. The calculator counts all Monday–Friday weekdays in the range. To account for public holidays in your specific region, first calculate the business days, then subtract the number of public holidays that fall within the date range. If you're in the US and need to exclude federal holidays, check the Office of Personnel Management's official holiday schedule.",
      },
      {
        question: "When a deadline is '5 business days,' when is it actually due?",
        answer: "Count 5 weekdays forward from the starting date (not including that start date). For example, if the clock starts on Monday: Day 1 = Tuesday, Day 2 = Wednesday, Day 3 = Thursday, Day 4 = Friday, Day 5 = Monday (of the next week). So a 5-business-day deadline starting Monday is due the following Monday. If the starting day is Wednesday: Day 1 = Thursday, Day 2 = Friday, Day 3 = Monday, Day 4 = Tuesday, Day 5 = Wednesday — due the following Wednesday.",
      },
      {
        question: "How many business days are in a year?",
        answer: "A standard year has 52 weeks plus 1 or 2 extra days. Each week contributes 5 business days, giving 260 or 261 business days before holidays. After typical US federal holidays (about 10 per year), there are approximately 250–251 business days annually. The exact count varies by year because different days of the week January 1 falls on affect how weekends and the extra days align. Leap years have one additional day but that adds at most one business day.",
      },
      {
        question: "What is the difference between business days and calendar days?",
        answer: "Calendar days count every day from Monday to Sunday — all 7 days per week. Business days count only Monday through Friday — 5 days per week. A 10-calendar-day period contains either 6 or 8 business days depending on where in the week it falls. Business and legal deadlines often specify which type to use. When the document is silent, context usually clarifies: 'two-day shipping' typically means calendar days, while 'processing time' at a bank typically means business days.",
      },
      {
        question: "How do I add business days to a date to find a future date?",
        answer: "To find a date that is N business days in the future, start from your date and count forward, skipping Saturdays and Sundays. For example, to add 3 business days to Friday, January 10: skip the weekend, count Monday (1), Tuesday (2), Wednesday (3) — your date is Wednesday, January 15. A quick formula: if you have a full number of weeks (divide N by 5), add those weeks first (× 7 calendar days), then add the remaining days, skipping any weekend that might fall in the remainder. Our Date Difference Calculator can verify your result.",
      },
    ],
    slugEs: "calculadora-de-dias-habiles",
    titleEs: "Calculadora de Días Hábiles",
    shortDescriptionEs: "Calcula el número de días hábiles (días laborables) entre dos fechas, excluyendo los fines de semana.",
    seoTitleEs: "Calculadora de Días Hábiles — Días Laborables Entre Fechas",
    metaDescriptionEs: "Cuenta el número de días hábiles (de lunes a viernes) entre dos fechas cualesquiera, excluyendo los fines de semana. Calculadora de días laborables en línea gratuita.",
    primaryKeywordEs: "calculadora de dias habiles",
    secondaryKeywordsEs: ["calculadora de dias laborables", "dias entre semana entre fechas", "contador de dias habiles", "calculadora de dias de trabajo"],
    formulaExplanationEs: "Los días hábiles cuentan solo de lunes a viernes. Los fines de semana se excluyen calculando el número de semanas completas (cada una aporta 5 días hábiles) y sumando el conteo de días laborables de cualquier semana parcial al inicio o al final del rango. Este método es exacto sin importar en qué día de la semana comience el rango, porque el patrón de fines de semana se repite limpiamente cada siete días.",
    explanationEs: "Los días hábiles (también llamados días laborables o días entre semana) son los días de lunes a viernes, excluyendo los fines de semana. Esta distinción importa enormemente en contextos comerciales, legales y financieros, donde los plazos y los tiempos de procesamiento se miden en días hábiles, no en días de calendario.\n\nCuando una empresa dice 'espere de 5 a 7 días hábiles para la entrega', se refiere a días laborables excluyendo el sábado y el domingo. Un envío despachado un viernes que tarda 5 días hábiles llegará el viernes siguiente, no el miércoles siguiente. Los contratos legales, las agencias gubernamentales y las instituciones financieras suelen definir los plazos en días hábiles.\n\nEsta calculadora cuenta todos los días entre semana (de lunes a viernes) en el rango de fechas. Ten en cuenta que los días festivos no se excluyen automáticamente porque varían según el país, la región y el sector. Si necesitas excluir festivos específicos, réstalos del resultado de días hábiles.\n\nPara la gestión de proyectos, los cálculos de días hábiles ayudan a fijar plazos realistas, especialmente cuando cruzan fines de semana o cuando una fecha límite cae a mitad de semana.",
    exampleEs: {
      inputs: { startDate: "2025-01-06", endDate: "2025-01-17" },
      explanation: "Del lunes 6 de enero al viernes 17 de enero de 2025: hay 10 días de calendario (del 7 al 16, más el 17), incluyendo 2 fines de semana completos. Días hábiles = 10 días entre semana (2 semanas laborales completas).",
    },
    faqsEs: [
      { question: "¿Esta calculadora excluye los días festivos?", answer: "No — los días festivos no se excluyen automáticamente porque varían significativamente según el país, el estado, la empresa y el sector. La calculadora cuenta todos los días entre semana de lunes a viernes del rango. Para tener en cuenta los festivos de tu región específica, primero calcula los días hábiles y luego resta el número de festivos que caen dentro del rango de fechas. Si estás en EE. UU. y necesitas excluir los festivos federales, consulta el calendario oficial de la Oficina de Gestión de Personal." },
      { question: "Cuando un plazo es de '5 días hábiles', ¿cuándo vence realmente?", answer: "Cuenta 5 días entre semana hacia adelante desde la fecha de inicio (sin incluir esa fecha de inicio). Por ejemplo, si el reloj empieza un lunes: día 1 = martes, día 2 = miércoles, día 3 = jueves, día 4 = viernes, día 5 = lunes (de la semana siguiente). Así, un plazo de 5 días hábiles que empieza un lunes vence el lunes siguiente. Si el día de inicio es miércoles: día 1 = jueves, día 2 = viernes, día 3 = lunes, día 4 = martes, día 5 = miércoles — vence el miércoles siguiente." },
      { question: "¿Cuántos días hábiles hay en un año?", answer: "Un año estándar tiene 52 semanas más 1 o 2 días adicionales. Cada semana aporta 5 días hábiles, lo que da 260 o 261 días hábiles antes de los festivos. Tras los típicos festivos federales de EE. UU. (unos 10 al año), hay aproximadamente entre 250 y 251 días hábiles al año. El conteo exacto varía según el año porque el día de la semana en que cae el 1 de enero afecta a cómo se alinean los fines de semana y los días adicionales. Los años bisiestos tienen un día más, pero eso añade como mucho un día hábil." },
      { question: "¿Cuál es la diferencia entre días hábiles y días de calendario?", answer: "Los días de calendario cuentan cada día de lunes a domingo — los 7 días de la semana. Los días hábiles cuentan solo de lunes a viernes — 5 días por semana. Un periodo de 10 días de calendario contiene entre 6 y 8 días hábiles según en qué parte de la semana caiga. Los plazos comerciales y legales suelen especificar qué tipo usar. Cuando el documento no lo aclara, el contexto suele orientar: el 'envío en dos días' normalmente significa días de calendario, mientras que el 'tiempo de procesamiento' en un banco normalmente significa días hábiles." },
      { question: "¿Cómo sumo días hábiles a una fecha para encontrar una fecha futura?", answer: "Para encontrar una fecha que esté a N días hábiles en el futuro, parte de tu fecha y cuenta hacia adelante, saltando los sábados y domingos. Por ejemplo, para sumar 3 días hábiles al viernes 10 de enero: salta el fin de semana, cuenta lunes (1), martes (2), miércoles (3) — tu fecha es el miércoles 15 de enero. Una fórmula rápida: si tienes un número entero de semanas (divide N entre 5), suma primero esas semanas (× 7 días de calendario) y luego añade los días restantes, saltando cualquier fin de semana del resto. Nuestra Calculadora de Diferencia de Fechas puede verificar tu resultado." },
    ],
    relatedCalculators: ["date-difference-calculator", "countdown", "overtime-calculator"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "time-duration",
    slug: "time-duration-calculator",
    category: "Date & Time",
    categorySlug: "date-time",
    title: "Time Duration Calculator",
    shortDescription: "Convert hours, minutes, and seconds to total time in multiple formats.",
    seoTitle: "Time Duration Calculator — Convert Hours, Minutes & Seconds",
    metaDescription: "Calculate total time duration from hours, minutes, and seconds. Convert to decimal hours, minutes, or seconds. Perfect for timesheets and billing.",
    primaryKeyword: "time duration calculator",
    secondaryKeywords: ["hours minutes seconds calculator", "timesheet calculator", "time converter", "decimal hours calculator"],
    fields: [
      {
        id: "hours",
        label: "Hours",
        type: "number",
        placeholder: "0",
        min: 0,
        defaultValue: 0,
        required: false,
      },
      {
        id: "minutes",
        label: "Minutes",
        type: "number",
        placeholder: "0",
        min: 0,
        defaultValue: 0,
        required: false,
      },
      {
        id: "seconds",
        label: "Seconds",
        type: "number",
        placeholder: "0",
        min: 0,
        defaultValue: 0,
        required: false,
      },
    ],
    results: [
      { id: "totalHours", label: "Total Hours (decimal)", format: "number", decimals: 4, isPrimary: true },
      { id: "totalMinutes", label: "Total Minutes", format: "number", decimals: 2, isPrimary: false },
      { id: "totalSeconds", label: "Total Seconds", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Total seconds = hours × 3600 + minutes × 60 + seconds; Decimal hours = total seconds / 3600",
    formulaExplanation: "All time components are converted to a common unit (seconds), then converted to the desired output format. Decimal hours are used in billing and payroll: 1 hour 30 minutes = 1.5 hours.",
    formulaSource: "Standard time conversion",
    explanation: "Converting time between hours:minutes:seconds format and decimal hours is a common task in payroll, billing, and productivity tracking. The time duration calculator handles this conversion instantly.\n\nDecimal hours are essential for billing clients (3 hours 45 minutes billed at $150/hour = 3.75 × $150 = $562.50) and for entering time in payroll systems that accept decimal input. Converting manually is error-prone: 2 hours 40 minutes is NOT 2.40 hours — it's 2.667 hours (40/60 = 0.667).\n\nThis calculator also converts total time to minutes or seconds, useful for:\n- Event timing and athletics (where 1:23:45 needs to be compared to 5,025 seconds)\n- Music and video production (where project length is counted in total seconds)\n- Computing data rates and other per-second measurements\n- Scientific experiments where total duration in seconds is required",
    example: {
      inputs: { hours: "2", minutes: "45", seconds: "30" },
      explanation: "2 hours, 45 minutes, 30 seconds = 9,930 total seconds = 165.5 total minutes = 2.7583 decimal hours. Billed at $100/hour, this equals $275.83.",
    },
    faqs: [
      {
        question: "Why is 1 hour 30 minutes not 1.30 hours in decimal?",
        answer: "Minutes are sixtiethths of an hour, not hundredths (tenths). So 30 minutes = 30/60 = 0.5 hours, not 0.30 hours. This is the most common mistake in manual time conversion. The full conversion: decimal hours = hours + (minutes / 60) + (seconds / 3600). Some examples: 15 min = 0.25 hr, 20 min = 0.333 hr, 45 min = 0.75 hr, 50 min = 0.833 hr. Always divide minutes by 60 (not 100) to convert to decimal hours.",
      },
      {
        question: "How do I use decimal hours for payroll and billing?",
        answer: "To bill correctly: convert your time to decimal hours, then multiply by your hourly rate. For example, 3 hours 20 minutes = 3 + (20/60) = 3.333 hours. At $90/hour: 3.333 × $90 = $300. For payroll, weekly hours are totaled in decimal: 8h 30m + 7h 45m + 9h 15m = 8.5 + 7.75 + 9.25 = 25.5 decimal hours. Most payroll software accepts decimal hours directly. Double-checking with this calculator prevents under- or overbilling clients.",
      },
      {
        question: "How do I add multiple time durations together?",
        answer: "The easiest method is to convert everything to seconds, add the seconds together, then convert back to hours:minutes:seconds. For example, 1h 45m + 2h 50m: convert to seconds (6300 + 10200 = 16500 total seconds), then convert back: 16500 / 3600 = 4.583 hours = 4 hours 35 minutes. You can also add hours and minutes separately and carry over: 1+2=3 hours, 45+50=95 minutes → 95−60=35 minutes with 1 hour carried → total 4h 35m.",
      },
      {
        question: "What is the difference between time duration and time of day?",
        answer: "Time duration measures an elapsed period (how long something takes), while time of day indicates a specific point on the clock. Duration: 1 hour 30 minutes means 90 minutes have passed. Time of day: 1:30 means 1:30 AM or 1:30 PM. Duration math (subtracting start time from end time) gives elapsed duration, but crossing midnight requires adding 24 hours to the end time if it's less than the start time. This calculator handles duration only — for clock-time arithmetic, use a dedicated time calculator.",
      },
      {
        question: "How many seconds are in a day, week, or year?",
        answer: "One day = 24 hours × 60 minutes × 60 seconds = 86,400 seconds. One week = 7 × 86,400 = 604,800 seconds. One standard year = 365 × 86,400 = 31,536,000 seconds. One leap year = 366 × 86,400 = 31,622,400 seconds. A common rough estimate: one year ≈ π × 10^7 seconds (about 31.4 million seconds), which is accurate to within 0.5%. These values matter in computing (Unix timestamps count seconds since Jan 1, 1970), physics, and time-critical systems.",
      },
    ],
    slugEs: "calculadora-de-duracion-de-tiempo",
    titleEs: "Calculadora de Duración de Tiempo",
    shortDescriptionEs: "Convierte horas, minutos y segundos a tiempo total en múltiples formatos.",
    seoTitleEs: "Calculadora de Duración de Tiempo — Convierte Horas, Minutos y Segundos",
    metaDescriptionEs: "Calcula la duración total de tiempo a partir de horas, minutos y segundos. Convierte a horas decimales, minutos o segundos. Ideal para hojas de horas y facturación.",
    primaryKeywordEs: "calculadora de duracion de tiempo",
    secondaryKeywordsEs: ["calculadora de horas minutos segundos", "calculadora de hoja de horas", "conversor de tiempo", "calculadora de horas decimales"],
    formulaExplanationEs: "Todos los componentes de tiempo se convierten a una unidad común (segundos) y luego al formato de salida deseado. Las horas decimales se usan en facturación y nóminas: 1 hora y 30 minutos equivalen a 1,5 horas. Convertir primero a segundos evita mezclar los campos del reloj en base sesenta, donde sesenta minutos forman una hora en lugar de cien, de modo que la aritmética resulta directa y libre de errores.",
    explanationEs: "Convertir el tiempo entre el formato horas:minutos:segundos y las horas decimales es una tarea habitual en nóminas, facturación y seguimiento de productividad. La calculadora de duración de tiempo realiza esta conversión al instante.\n\nLas horas decimales son esenciales para facturar a clientes (3 horas y 45 minutos facturadas a 150 $/hora = 3,75 × 150 $ = 562,50 $) y para introducir el tiempo en sistemas de nómina que aceptan entradas decimales. Convertir manualmente es propenso a errores: 2 horas y 40 minutos NO son 2,40 horas — son 2,667 horas (40/60 = 0,667).\n\nEsta calculadora también convierte el tiempo total a minutos o segundos, útil para:\n- Cronometraje de eventos y atletismo (donde 1:23:45 debe compararse con 5.025 segundos)\n- Producción de música y vídeo (donde la duración del proyecto se cuenta en segundos totales)\n- Cálculo de tasas de datos y otras medidas por segundo\n- Experimentos científicos donde se requiere la duración total en segundos",
    exampleEs: {
      inputs: { hours: "2", minutes: "45", seconds: "30" },
      explanation: "2 horas, 45 minutos y 30 segundos = 9.930 segundos totales = 165,5 minutos totales = 2,7583 horas decimales. Facturado a 100 $/hora, esto equivale a 275,83 $.",
    },
    faqsEs: [
      { question: "¿Por qué 1 hora y 30 minutos no son 1,30 horas en decimal?", answer: "Los minutos son sesentavos de una hora, no centésimas (décimas). Así, 30 minutos = 30/60 = 0,5 horas, no 0,30 horas. Este es el error más común en la conversión manual de tiempo. La conversión completa: horas decimales = horas + (minutos / 60) + (segundos / 3600). Algunos ejemplos: 15 min = 0,25 h, 20 min = 0,333 h, 45 min = 0,75 h, 50 min = 0,833 h. Divide siempre los minutos entre 60 (no entre 100) para convertir a horas decimales." },
      { question: "¿Cómo uso las horas decimales para nóminas y facturación?", answer: "Para facturar correctamente: convierte tu tiempo a horas decimales y luego multiplícalo por tu tarifa por hora. Por ejemplo, 3 horas y 20 minutos = 3 + (20/60) = 3,333 horas. A 90 $/hora: 3,333 × 90 $ = 300 $. Para la nómina, las horas semanales se suman en decimal: 8h 30m + 7h 45m + 9h 15m = 8,5 + 7,75 + 9,25 = 25,5 horas decimales. La mayoría del software de nóminas acepta horas decimales directamente. Verificar con esta calculadora evita facturar de menos o de más a los clientes." },
      { question: "¿Cómo sumo varias duraciones de tiempo?", answer: "El método más sencillo es convertir todo a segundos, sumar los segundos y luego reconvertir a horas:minutos:segundos. Por ejemplo, 1h 45m + 2h 50m: convierte a segundos (6300 + 10200 = 16500 segundos totales) y luego reconvierte: 16500 / 3600 = 4,583 horas = 4 horas y 35 minutos. También puedes sumar horas y minutos por separado y arrastrar: 1+2=3 horas, 45+50=95 minutos → 95−60=35 minutos arrastrando 1 hora → total 4h 35m." },
      { question: "¿Cuál es la diferencia entre duración de tiempo y hora del día?", answer: "La duración de tiempo mide un periodo transcurrido (cuánto tarda algo), mientras que la hora del día indica un punto específico del reloj. Duración: 1 hora y 30 minutos significa que han pasado 90 minutos. Hora del día: 1:30 significa la 1:30 de la mañana o de la tarde. La aritmética de duración (restar la hora de inicio de la hora de fin) da la duración transcurrida, pero cruzar la medianoche requiere sumar 24 horas a la hora de fin si es menor que la de inicio. Esta calculadora maneja solo la duración." },
      { question: "¿Cuántos segundos hay en un día, una semana o un año?", answer: "Un día = 24 horas × 60 minutos × 60 segundos = 86.400 segundos. Una semana = 7 × 86.400 = 604.800 segundos. Un año estándar = 365 × 86.400 = 31.536.000 segundos. Un año bisiesto = 366 × 86.400 = 31.622.400 segundos. Una estimación aproximada común: un año ≈ π × 10^7 segundos (unos 31,4 millones de segundos), precisa hasta un 0,5 %. Estos valores importan en informática (las marcas de tiempo Unix cuentan segundos desde el 1 de enero de 1970), en física y en sistemas de tiempo crítico." },
    ],
    relatedCalculators: ["date-difference-calculator", "overtime-calculator", "business-days-calculator"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "overtime",
    slug: "overtime-calculator",
    category: "Date & Time",
    categorySlug: "date-time",
    title: "Overtime Calculator",
    shortDescription: "Calculate overtime pay based on regular hours, total hours worked, and your overtime multiplier.",
    seoTitle: "Overtime Calculator — Calculate Overtime Pay & Total Earnings",
    metaDescription: "Calculate your overtime pay based on hours worked and overtime rate. Supports standard 1.5x and custom multipliers. Free overtime pay calculator.",
    primaryKeyword: "overtime calculator",
    secondaryKeywords: ["overtime pay calculator", "time and a half calculator", "double time calculator", "paycheck calculator"],
    sensitivity: "finance",
    fields: [
      {
        id: "regularHours",
        label: "Regular Hours Threshold",
        type: "number",
        placeholder: "40",
        defaultValue: 40,
        required: true,
        helpText: "Hours before overtime kicks in (usually 40 per week in the US)",
      },
      {
        id: "totalHours",
        label: "Total Hours Worked",
        type: "number",
        placeholder: "e.g. 48",
        required: true,
      },
      {
        id: "hourlyRate",
        label: "Hourly Rate ($)",
        type: "number",
        placeholder: "e.g. 20",
        unit: "$",
        required: true,
      },
      {
        id: "overtimeMultiplier",
        label: "Overtime Multiplier",
        type: "number",
        placeholder: "1.5",
        defaultValue: 1.5,
        required: true,
        helpText: "Standard overtime is 1.5× (time-and-a-half). Some employers pay 2× (double time).",
      },
    ],
    results: [
      { id: "regularPay", label: "Regular Pay", format: "currency", decimals: 2, isPrimary: false },
      { id: "overtimePay", label: "Overtime Pay", format: "currency", decimals: 2, isPrimary: false },
      { id: "totalPay", label: "Total Pay", format: "currency", decimals: 2, isPrimary: true },
      { id: "overtimeHours", label: "Overtime Hours", format: "number", decimals: 2, isPrimary: false },
      { id: "overtimeRate", label: "Overtime Rate", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "Regular pay = min(hours, threshold) × rate; Overtime pay = max(0, hours − threshold) × rate × multiplier",
    formulaExplanation: "Regular pay covers hours up to the threshold (typically 40). Overtime pay covers hours beyond the threshold at the overtime rate (regular rate × multiplier). Most US non-exempt employees are entitled to 1.5× pay for hours over 40 per week under FLSA.",
    formulaSource: "US Fair Labor Standards Act (FLSA)",
    sourceUrl: "https://www.dol.gov/agencies/whd/overtime",
    explanation: "Overtime pay compensates employees for working beyond standard hours. In the United States, the Fair Labor Standards Act (FLSA) requires most employers to pay non-exempt employees at least 1.5 times their regular rate ('time and a half') for all hours worked beyond 40 in a workweek.\n\nSome states have additional overtime rules. California requires overtime for hours over 8 in a single day, not just over 40 in a week. Some employers voluntarily pay double time (2×) for extremely long shifts or weekend work.\n\nThis calculator handles the most common scenario: weekly overtime triggered after a threshold of hours. The formula is straightforward — regular hours × base rate, plus overtime hours × (base rate × multiplier).\n\nNote: This calculator is for estimation purposes. Actual overtime eligibility depends on FLSA exemption status, your state's labor laws, and your employment agreement. Consult HR or a labor attorney for questions about your specific situation.",
    example: {
      inputs: { regularHours: "40", totalHours: "48", hourlyRate: "20", overtimeMultiplier: "1.5" },
      explanation: "48 total hours − 40 regular = 8 overtime hours. Regular pay: 40 × $20 = $800. Overtime pay: 8 × ($20 × 1.5) = 8 × $30 = $240. Total pay: $800 + $240 = $1,040.",
    },
    faqs: [
      {
        question: "Who is eligible for overtime pay in the US?",
        answer: "Under the FLSA, non-exempt employees are entitled to overtime. Most hourly workers are non-exempt. Salaried employees may be exempt if they earn above a certain salary threshold ($684/week as of 2020, subject to change) AND perform executive, administrative, or professional duties. Teachers, lawyers, doctors, and certain other professionals may also be exempt. If you're unsure of your status, the Department of Labor's Wage and Hour Division can help determine whether you're entitled to overtime.",
      },
      {
        question: "What is 'time and a half' and how is it calculated?",
        answer: "Time and a half means 1.5 times your regular hourly rate for each overtime hour worked. If you earn $18/hour normally, your overtime rate is $18 × 1.5 = $27/hour. For every hour beyond the threshold, you earn $27 instead of $18. The 'half' comes from the extra 50% pay: you still earn your regular rate ($18) plus a premium of half that rate ($9) for a total of $27. Over 8 overtime hours at this rate, the premium alone adds up to $9 × 8 = $72 extra earnings.",
      },
      {
        question: "Can my employer require me to work overtime?",
        answer: "Generally yes — in the US, most employers can require overtime as a condition of employment, and refusing can be grounds for discipline or termination. There's no federal law capping the maximum hours an adult can work (unlike many countries). However, employers must pay overtime rates for hours over the FLSA threshold. Some professions have specific restrictions (truck drivers have hours-of-service limits from the FMCSA; healthcare workers may have state-specific rules). Always check your employment contract and state labor laws.",
      },
      {
        question: "How does overtime work for different pay periods?",
        answer: "FLSA overtime is calculated per workweek (a fixed, recurring 7-day period), regardless of whether you're paid weekly, biweekly, or semi-monthly. Even if you're paid biweekly, your employer must calculate overtime for each individual 7-day workweek separately — you can't average two weeks together. So if you work 50 hours in week 1 and 30 in week 2 (80 total), you're entitled to 10 hours of overtime for week 1, not zero overtime based on the 40-hour biweekly average.",
      },
      {
        question: "What is double time and when does it apply?",
        answer: "Double time is 2× the regular hourly rate. It's not required by federal law in the US, but California law requires it for hours over 12 in a single workday and for the 7th consecutive day of a workweek. Some union contracts and employer policies voluntarily provide double time for holiday work, overnight shifts, or hours beyond a certain threshold. If you're working under a collective bargaining agreement or in California, check the specific provisions that apply to your situation.",
      },
    ],
    slugEs: "calculadora-de-horas-extra",
    titleEs: "Calculadora de Horas Extra",
    shortDescriptionEs: "Calcula el pago de horas extra según las horas regulares, el total de horas trabajadas y tu multiplicador de horas extra.",
    seoTitleEs: "Calculadora de Horas Extra — Calcula el Pago de Horas Extra y Ganancias Totales",
    metaDescriptionEs: "Calcula tu pago de horas extra según las horas trabajadas y la tarifa de horas extra. Admite multiplicadores estándar de 1,5× y personalizados. Calculadora de pago de horas extra gratuita.",
    primaryKeywordEs: "calculadora de horas extra",
    secondaryKeywordsEs: ["calculadora de pago de horas extra", "calculadora de tiempo y medio", "calculadora de doble tiempo", "calculadora de nomina"],
    formulaExplanationEs: "El pago regular cubre las horas hasta el umbral (normalmente 40). El pago de horas extra cubre las horas que superan el umbral a la tarifa de horas extra (tarifa regular × multiplicador). La mayoría de los empleados no exentos de EE. UU. tienen derecho a 1,5× la paga por las horas que superan las 40 por semana según la FLSA. Sumar ambos importes da la paga bruta total.",
    explanationEs: "El pago de horas extra compensa a los empleados por trabajar más allá de las horas estándar. En Estados Unidos, la Ley de Normas Laborales Justas (FLSA) exige que la mayoría de los empleadores paguen a los empleados no exentos al menos 1,5 veces su tarifa regular ('tiempo y medio') por todas las horas trabajadas más allá de las 40 en una semana laboral.\n\nAlgunos estados tienen normas de horas extra adicionales. California exige horas extra por las horas que superan las 8 en un solo día, no solo las que superan las 40 en una semana. Algunos empleadores pagan voluntariamente doble tiempo (2×) por turnos extremadamente largos o trabajo en fin de semana.\n\nEsta calculadora maneja el escenario más común: horas extra semanales activadas tras un umbral de horas. La fórmula es sencilla — horas regulares × tarifa base, más horas extra × (tarifa base × multiplicador).\n\nNota: esta calculadora es solo para fines de estimación. La elegibilidad real para las horas extra depende del estatus de exención de la FLSA, de las leyes laborales de tu estado y de tu contrato de trabajo. Consulta a Recursos Humanos o a un abogado laboral para preguntas sobre tu situación específica.",
    exampleEs: {
      inputs: { regularHours: "40", totalHours: "48", hourlyRate: "20", overtimeMultiplier: "1.5" },
      explanation: "48 horas totales − 40 regulares = 8 horas extra. Pago regular: 40 × 20 $ = 800 $. Pago de horas extra: 8 × (20 $ × 1,5) = 8 × 30 $ = 240 $. Pago total: 800 $ + 240 $ = 1.040 $.",
    },
    faqsEs: [
      { question: "¿Quién tiene derecho al pago de horas extra en EE. UU.?", answer: "Según la FLSA, los empleados no exentos tienen derecho a horas extra. La mayoría de los trabajadores por horas son no exentos. Los empleados asalariados pueden estar exentos si ganan por encima de cierto umbral salarial (684 $/semana desde 2020, sujeto a cambios) Y desempeñan funciones ejecutivas, administrativas o profesionales. Los profesores, abogados, médicos y otros profesionales también pueden estar exentos. Si no estás seguro de tu estatus, la División de Horas y Salarios del Departamento de Trabajo puede ayudarte a determinar si tienes derecho a horas extra." },
      { question: "¿Qué es el 'tiempo y medio' y cómo se calcula?", answer: "El tiempo y medio significa 1,5 veces tu tarifa por hora regular por cada hora extra trabajada. Si normalmente ganas 18 $/hora, tu tarifa de horas extra es 18 $ × 1,5 = 27 $/hora. Por cada hora más allá del umbral, ganas 27 $ en lugar de 18 $. El 'medio' proviene del 50 % de paga adicional: sigues ganando tu tarifa regular (18 $) más una prima de la mitad de esa tarifa (9 $) para un total de 27 $. A lo largo de 8 horas extra a esta tarifa, solo la prima suma 9 $ × 8 = 72 $ de ganancias adicionales." },
      { question: "¿Puede mi empleador obligarme a hacer horas extra?", answer: "En general sí — en EE. UU., la mayoría de los empleadores pueden exigir horas extra como condición de empleo, y negarse puede ser motivo de sanción o despido. No hay ninguna ley federal que limite el máximo de horas que un adulto puede trabajar (a diferencia de muchos países). Sin embargo, los empleadores deben pagar tarifas de horas extra por las horas que superan el umbral de la FLSA. Algunas profesiones tienen restricciones específicas (los camioneros tienen límites de horas de servicio de la FMCSA; los trabajadores sanitarios pueden tener normas estatales específicas). Consulta siempre tu contrato de trabajo y las leyes laborales de tu estado." },
      { question: "¿Cómo funcionan las horas extra en distintos periodos de pago?", answer: "Las horas extra de la FLSA se calculan por semana laboral (un periodo fijo y recurrente de 7 días), independientemente de si te pagan semanal, quincenal o bimensualmente. Aunque te paguen cada dos semanas, tu empleador debe calcular las horas extra de cada semana laboral individual de 7 días por separado — no puedes promediar dos semanas juntas. Así, si trabajas 50 horas en la semana 1 y 30 en la semana 2 (80 en total), tienes derecho a 10 horas extra por la semana 1, no a cero horas extra basadas en el promedio quincenal de 40 horas." },
      { question: "¿Qué es el doble tiempo y cuándo se aplica?", answer: "El doble tiempo es 2× la tarifa por hora regular. No lo exige la ley federal en EE. UU., pero la ley de California lo requiere por las horas que superan las 12 en un solo día laboral y por el 7.º día consecutivo de una semana laboral. Algunos convenios sindicales y políticas de empleadores ofrecen voluntariamente doble tiempo por trabajo en festivos, turnos nocturnos u horas que superan cierto umbral. Si trabajas bajo un convenio colectivo o en California, consulta las disposiciones específicas que se aplican a tu situación." },
    ],
    relatedCalculators: ["time-duration", "hourly-wage-calculator", "paycheck-calculator"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "countdown",
    slug: "countdown-calculator",
    category: "Date & Time",
    categorySlug: "date-time",
    title: "Countdown Calculator",
    shortDescription: "Calculate exactly how long until any future date in years, months, weeks, days, hours, and minutes.",
    seoTitle: "Countdown Calculator — Days Until Any Date",
    metaDescription: "Calculate the countdown to any date: how many days, hours, and minutes until your event. Free online countdown timer and date calculator.",
    primaryKeyword: "countdown calculator",
    secondaryKeywords: ["days until calculator", "how many days until", "event countdown", "date countdown timer"],
    fields: [
      {
        id: "targetDate",
        label: "Target Date",
        type: "date",
        required: true,
        helpText: "Enter the future date you want to count down to",
      },
    ],
    results: [
      { id: "totalDays", label: "Total Days Remaining", format: "number", decimals: 0, isPrimary: true },
      { id: "weeks", label: "Weeks", format: "number", decimals: 1, isPrimary: false },
      { id: "months", label: "Months (approx.)", format: "number", decimals: 1, isPrimary: false },
    ],
    formula: "Days remaining = (Target Date − Today) in days",
    formulaExplanation: "Subtracting today's timestamp from the target date's timestamp measures the raw interval between the two moments, and dividing that span by the number of milliseconds in a day converts it into whole days remaining. Reading the current date dynamically each time the calculation runs is what keeps the countdown accurate — the figure reflects the actual present moment rather than a value frozen when the page first loaded, so it never drifts out of date.",
    formulaSource: "Standard calendar/time arithmetic",
    explanation: "A countdown calculator tells you exactly how much time stands between today and any future date, expressed in days, weeks, and months. Whether you are counting down to a wedding, a product launch, a final exam, or a long-awaited holiday, converting a vague sense of 'a few months away' into a precise number of days makes the interval feel real and easier to plan around.\n\nThe method is direct calendar arithmetic: the countdown calculator subtracts today's date from your target date and reports the gap. Because it reads the current date each time it runs, the result is always live — reload the page tomorrow and the number drops by one. It automatically accounts for leap years, so a span crossing February 29 is counted correctly without any manual adjustment.\n\nBeyond curiosity, a countdown serves a genuine psychological purpose: research on goal setting shows that attaching a specific date to an objective increases motivation and follow-through. Students pacing revision, project managers tracking a launch, event planners, and anyone chasing a personal deadline use a countdown calculator to break a long stretch of time into concrete weekly milestones they can actually act on.",
    example: {
      inputs: { targetDate: "2025-12-31" },
      explanation: "If today is February 1, 2025, then December 31, 2025 is 333 days away — about 47.6 weeks or 10.9 months. Knowing there are 333 days until a goal helps break down the work into manageable weekly targets.",
    },
    faqs: [
      {
        question: "What if my target date has already passed?",
        answer: "If the target date is in the past, the calculator will show a negative number of days — indicating how many days ago that date occurred. This is useful for calculating how long it's been since an event. For counting days since a past event, the Date Difference Calculator is more appropriate, as it's designed for historical date ranges. The Countdown Calculator is optimized for future events but will still correctly report negative values for past dates.",
      },
      {
        question: "How accurate is the days remaining count?",
        answer: "The countdown is accurate to the day — it uses your current date (from your device's clock) and calculates the exact number of full calendar days until the target date. It doesn't currently account for time of day: if there are 5 days and 6 hours remaining, it shows 5 days. For hour-level precision in countdowns, you'd need to factor in the specific time of day of the target event. The calculation automatically accounts for leap years, so February 29 in a leap year is correctly included.",
      },
      {
        question: "How many weeks is 100 days?",
        answer: "100 days is exactly 14 weeks and 2 days, or approximately 14.3 weeks. Dividing any number of days by 7 gives the week equivalent. Some common conversions: 30 days ≈ 4.3 weeks; 90 days ≈ 12.9 weeks; 100 days ≈ 14.3 weeks; 180 days ≈ 25.7 weeks; 365 days ≈ 52.1 weeks. These conversions are useful for project planning and breaking long timeframes into weekly milestones.",
      },
      {
        question: "How can I use a countdown for goal setting?",
        answer: "Set your target date first, then divide the total days into milestones. For a 100-day countdown: week 1-2 (research and planning), weeks 3-6 (build foundation), weeks 7-10 (execute main work), weeks 11-13 (refine and polish), week 14 (final preparation). Knowing exactly how many days remain creates urgency and helps prioritize. Many productivity systems (like '100-day challenges' and marathon training plans) use countdowns to structure consistent daily progress toward a defined deadline.",
      },
      {
        question: "What are some popular events people count down to?",
        answer: "Common countdowns include: New Year's Day (January 1), Christmas and major holidays, personal events (birthdays, anniversaries, weddings), professional deadlines (project launches, exam dates, contract renewals), travel (vacation departure, flight departure), sports events (Super Bowl, World Cup, Olympics), academic milestones (graduation, semester start/end), and financial dates (tax deadlines, enrollment periods). Countdowns work for any future date that holds significance — the specificity of a date makes preparation feel more concrete and actionable.",
      },
    ],
    slugEs: "calculadora-de-cuenta-regresiva",
    titleEs: "Calculadora de Cuenta Regresiva",
    shortDescriptionEs: "Calcula exactamente cuánto falta para cualquier fecha futura en años, meses, semanas, días, horas y minutos.",
    seoTitleEs: "Calculadora de Cuenta Regresiva — Días Hasta Cualquier Fecha",
    metaDescriptionEs: "Calcula la cuenta regresiva hasta cualquier fecha: cuántos días, horas y minutos faltan para tu evento. Temporizador de cuenta regresiva y calculadora de fechas en línea gratuita.",
    primaryKeywordEs: "calculadora de cuenta regresiva",
    secondaryKeywordsEs: ["calculadora de dias que faltan", "cuantos dias faltan", "cuenta regresiva de eventos", "temporizador de cuenta regresiva de fechas"],
    formulaExplanationEs: "Restar la marca de tiempo de hoy de la marca de tiempo de la fecha objetivo mide el intervalo bruto entre los dos momentos, y dividir ese lapso entre el número de milisegundos de un día lo convierte en días completos restantes. Leer la fecha actual de forma dinámica cada vez que se ejecuta el cálculo es lo que mantiene la cuenta regresiva precisa — la cifra refleja el momento presente real en lugar de un valor congelado cuando se cargó la página, así que nunca queda desactualizada.",
    explanationEs: "Una calculadora de cuenta regresiva te dice exactamente cuánto tiempo hay entre hoy y cualquier fecha futura, expresado en días, semanas y meses. Ya sea que estés contando los días para una boda, el lanzamiento de un producto, un examen final o unas vacaciones largamente esperadas, convertir una vaga sensación de 'faltan unos meses' en un número preciso de días hace que el intervalo se sienta real y más fácil de planificar.\n\nEl método es aritmética de calendario directa: la calculadora de cuenta regresiva resta la fecha de hoy de tu fecha objetivo e informa la diferencia. Como lee la fecha actual cada vez que se ejecuta, el resultado siempre está actualizado — recarga la página mañana y el número baja en uno. Tiene en cuenta automáticamente los años bisiestos, así que un lapso que cruza el 29 de febrero se cuenta correctamente sin ningún ajuste manual.\n\nMás allá de la curiosidad, una cuenta regresiva cumple un propósito psicológico genuino: la investigación sobre el establecimiento de metas muestra que asociar una fecha específica a un objetivo aumenta la motivación y el seguimiento. Los estudiantes que organizan su repaso, los gestores de proyectos que siguen un lanzamiento, los organizadores de eventos y cualquiera que persiga un plazo personal usan una calculadora de cuenta regresiva para dividir un largo tramo de tiempo en hitos semanales concretos sobre los que realmente pueden actuar.",
    exampleEs: {
      inputs: { targetDate: "2025-12-31" },
      explanation: "Si hoy es 1 de febrero de 2025, entonces el 31 de diciembre de 2025 está a 333 días de distancia — unas 47,6 semanas o 10,9 meses. Saber que faltan 333 días para una meta ayuda a dividir el trabajo en objetivos semanales manejables.",
    },
    faqsEs: [
      { question: "¿Qué pasa si mi fecha objetivo ya ha pasado?", answer: "Si la fecha objetivo está en el pasado, la calculadora mostrará un número negativo de días — indicando cuántos días atrás ocurrió esa fecha. Esto es útil para calcular cuánto tiempo ha pasado desde un evento. Para contar los días desde un evento pasado, la Calculadora de Diferencia de Fechas es más apropiada, ya que está diseñada para rangos de fechas históricos. La Calculadora de Cuenta Regresiva está optimizada para eventos futuros, pero aun así informará correctamente valores negativos para fechas pasadas." },
      { question: "¿Qué precisión tiene el conteo de días restantes?", answer: "La cuenta regresiva es precisa al día — usa tu fecha actual (del reloj de tu dispositivo) y calcula el número exacto de días de calendario completos hasta la fecha objetivo. Actualmente no tiene en cuenta la hora del día: si faltan 5 días y 6 horas, muestra 5 días. Para una precisión a nivel de hora en las cuentas regresivas, tendrías que factorizar la hora específica del evento objetivo. El cálculo tiene en cuenta automáticamente los años bisiestos, así que el 29 de febrero de un año bisiesto se incluye correctamente." },
      { question: "¿Cuántas semanas son 100 días?", answer: "100 días son exactamente 14 semanas y 2 días, o aproximadamente 14,3 semanas. Dividir cualquier número de días entre 7 da el equivalente en semanas. Algunas conversiones comunes: 30 días ≈ 4,3 semanas; 90 días ≈ 12,9 semanas; 100 días ≈ 14,3 semanas; 180 días ≈ 25,7 semanas; 365 días ≈ 52,1 semanas. Estas conversiones son útiles para la planificación de proyectos y para dividir plazos largos en hitos semanales." },
      { question: "¿Cómo puedo usar una cuenta regresiva para establecer metas?", answer: "Fija primero tu fecha objetivo y luego divide el total de días en hitos. Para una cuenta regresiva de 100 días: semanas 1-2 (investigación y planificación), semanas 3-6 (construir la base), semanas 7-10 (ejecutar el trabajo principal), semanas 11-13 (refinar y pulir), semana 14 (preparación final). Saber exactamente cuántos días faltan crea urgencia y ayuda a priorizar. Muchos sistemas de productividad (como los 'desafíos de 100 días' y los planes de entrenamiento para maratón) usan cuentas regresivas para estructurar el progreso diario constante hacia un plazo definido." },
      { question: "¿Cuáles son algunos eventos populares para los que la gente hace cuenta regresiva?", answer: "Las cuentas regresivas comunes incluyen: Año Nuevo (1 de enero), Navidad y festivos importantes, eventos personales (cumpleaños, aniversarios, bodas), plazos profesionales (lanzamientos de proyectos, fechas de exámenes, renovaciones de contratos), viajes (salida de vacaciones, salida de vuelos), eventos deportivos (Super Bowl, Copa del Mundo, Juegos Olímpicos), hitos académicos (graduación, inicio/fin de semestre) y fechas financieras (plazos de impuestos, periodos de inscripción). Las cuentas regresivas funcionan para cualquier fecha futura significativa — la especificidad de una fecha hace que la preparación se sienta más concreta y accionable." },
    ],
    relatedCalculators: ["date-difference-calculator", "age-calculator", "business-days-calculator"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
];
