import type { CalculatorDefinition } from "../types";

export const dateTimeWave2Calculators: CalculatorDefinition[] = [
  {
    id: "date-difference",
    slug: "date-difference-calculator",
    category: "Date & Time",
    categorySlug: "date-time",
    title: "Date Difference Calculator",
    shortDescription: "Calculate the exact difference between two dates in years, months, weeks, and days.",
    seoTitle: "Date Difference Calculator — Days Between Two Dates",
    metaDescription: "Calculate the exact number of days, weeks, months, and years between any two dates. Free online date difference calculator with instant results.",
    primaryKeyword: "date difference calculator",
    secondaryKeywords: ["days between dates", "how many days between", "days calculator", "time between dates"],
    fields: [
      {
        id: "startDate",
        label: "Start Date",
        type: "date",
        required: true,
      },
      {
        id: "endDate",
        label: "End Date",
        type: "date",
        required: true,
      },
    ],
    results: [
      { id: "totalDays", label: "Total Days", format: "number", decimals: 0, isPrimary: true },
      { id: "totalWeeks", label: "Total Weeks", format: "number", decimals: 2, isPrimary: false },
      { id: "totalMonths", label: "Total Months (approx.)", format: "number", decimals: 1, isPrimary: false },
      { id: "years", label: "Years", format: "number", decimals: 0, isPrimary: false },
      { id: "months", label: "Remaining Months", format: "number", decimals: 0, isPrimary: false },
      { id: "days", label: "Remaining Days", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Days = (End Date − Start Date) in milliseconds / 86,400,000",
    formulaExplanation: "The difference is computed by subtracting start date from end date timestamps (milliseconds since Unix epoch) then dividing by milliseconds per day. Years, months, and remaining days are computed by incrementally counting calendar periods.",
    formulaSource: "Standard calendar arithmetic",
    explanation: "The date difference calculator tells you exactly how much time has elapsed between any two dates. This is more complex than it sounds because months have different lengths and leap years add extra days, meaning you can't simply divide days by 30 for months.\n\nThe calculation starts by finding the total number of days between the two dates — this is precise. From there, we can compute total weeks (days / 7) and an approximate month count (days / 30.44). For the year/month/day breakdown, we count actual calendar periods to account for varying month lengths and leap years.\n\nDate differences are essential for countless real-world needs: calculating how old someone is, how many days until an event, how long a project took, contract durations, loan terms, and anniversary tracking.\n\nNote that the total months figure is an approximation based on average month length (30.44 days). For exact month differences, the year/month/day breakdown at the bottom is more precise, using actual calendar counting.",
    example: {
      inputs: { startDate: "2024-01-01", endDate: "2025-01-01" },
      explanation: "From January 1, 2024 to January 1, 2025 is exactly 366 days (2024 is a leap year), which equals 52.3 weeks and exactly 12 months with 0 remaining days.",
    },
    faqs: [
      {
        question: "Why is the month count approximate?",
        answer: "Months have different lengths — January has 31 days, February has 28 or 29, April has 30, etc. There is no universal definition of 'exactly 1 month' in days. Our calculator shows two approaches: an approximate month count based on average month length (30.4375 days, accounting for leap years) and a precise year/month/day breakdown that actually counts through the calendar. For most purposes, the breakdown is more accurate; use the approximate figure only for rough estimates.",
      },
      {
        question: "Does this calculator account for leap years?",
        answer: "Yes. The total days count is completely accurate and automatically accounts for leap years, since it's based on actual date arithmetic (counting milliseconds between calendar dates). A leap year has 366 days instead of 365, so any date range that spans February 29 in a leap year will correctly include that day. Leap years occur every 4 years, except century years unless divisible by 400 — so 2000 was a leap year but 1900 was not.",
      },
      {
        question: "Can I calculate dates far in the past or future?",
        answer: "Yes, this calculator can handle dates across a wide range of years. JavaScript's date arithmetic supports dates from approximately year 271,821 BCE to 275,760 CE — far beyond any practical need. However, for historical dates before the Gregorian calendar reform (October 15, 1582), the calculator uses the proleptic Gregorian calendar, which may not match historical dates recorded in the Julian calendar. If you're working with pre-1582 historical dates, verify results with a specialized historical date converter.",
      },
      {
        question: "How do I calculate dates including or excluding the start date?",
        answer: "Our calculator gives the number of days between the start and end dates, not including the start day itself (this is the standard mathematical convention). To include the start date, add 1 to the result. For example, from January 1 to January 5: the difference is 4 days (Jan 2, 3, 4, 5 passed), but if you're counting inclusive of both endpoints (Jan 1, 2, 3, 4, 5), that's 5 days. For project duration purposes where you want to count each working day, use the inclusive count (add 1).",
      },
      {
        question: "What is the difference between date difference and age calculation?",
        answer: "Both measure time elapsed, but with a key distinction. Date difference simply counts calendar units between two dates. Age calculation (as used in birthday contexts) applies a specific rule: your age increases only when your birthday date is reached. So if today is March 15 and your birthday is June 15, you're still the previous year's age even if 8 months have passed since your last birthday. Our dedicated Age Calculator handles this birthday-based calculation, while this calculator focuses on the raw time difference between any two dates.",
      },
    ],
    relatedCalculators: ["age", "business-days", "countdown"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "business-days",
    slug: "business-days-calculator",
    category: "Date & Time",
    categorySlug: "date-time",
    title: "Business Days Calculator",
    shortDescription: "Calculate the number of business days (weekdays) between two dates, excluding weekends.",
    seoTitle: "Business Days Calculator — Working Days Between Dates",
    metaDescription: "Count the number of business days (Monday–Friday) between any two dates, excluding weekends. Free online working days calculator.",
    primaryKeyword: "business days calculator",
    secondaryKeywords: ["working days calculator", "weekdays between dates", "business day counter", "workdays calculator"],
    fields: [
      {
        id: "startDate",
        label: "Start Date",
        type: "date",
        required: true,
      },
      {
        id: "endDate",
        label: "End Date",
        type: "date",
        required: true,
      },
    ],
    results: [
      { id: "businessDays", label: "Business Days", format: "number", decimals: 0, isPrimary: true },
      { id: "weekendDays", label: "Weekend Days", format: "number", decimals: 0, isPrimary: false },
      { id: "totalDays", label: "Total Calendar Days", format: "number", decimals: 0, isPrimary: false },
      { id: "weeks", label: "Full Weeks", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Business days = total days − weekend days (Saturday + Sunday in range)",
    formulaExplanation: "Business days count only Monday through Friday. Weekends are excluded by calculating the number of complete weeks (each contributing 5 business days) and adding the weekday count of any partial week at the start or end.",
    formulaSource: "Standard business calendar definition",
    explanation: "Business days (also called working days or weekdays) are the days Monday through Friday, excluding weekends. This distinction matters enormously in business, legal, and financial contexts where deadlines and processing times are measured in business days, not calendar days.\n\nWhen a company says 'allow 5–7 business days for delivery,' they mean working days excluding Saturday and Sunday. A shipment sent on Friday that takes 5 business days will arrive the following Friday, not the following Wednesday. Legal contracts, government agencies, and financial institutions typically define timeframes in business days.\n\nThis calculator counts all weekdays (Monday through Friday) in the date range. Note that public holidays are not automatically excluded because holidays vary by country, region, and industry. If you need to exclude specific holidays, subtract them from the business days result.\n\nFor project management, business day calculations help set realistic timelines, especially across weekends or when a deadline falls mid-week.",
    example: {
      inputs: { startDate: "2025-01-06", endDate: "2025-01-17" },
      explanation: "From Monday January 6 to Friday January 17, 2025: there are 10 calendar days (the 7th through 16th, plus the 17th), including 2 full weekends. Business days = 10 weekdays (2 full work weeks).",
    },
    faqs: [
      {
        question: "Does this calculator exclude public holidays?",
        answer: "No — public holidays are not automatically excluded because they vary significantly by country, state, company, and industry. The calculator counts all Monday–Friday weekdays in the range. To account for public holidays in your specific region, first calculate the business days, then subtract the number of public holidays that fall within the date range. If you're in the US and need to exclude federal holidays, check the Office of Personnel Management's official holiday schedule.",
      },
      {
        question: "When a deadline is '5 business days,' when is it actually due?",
        answer: "Count 5 weekdays forward from the starting date (not including that start date). For example, if the clock starts on Monday: Day 1 = Tuesday, Day 2 = Wednesday, Day 3 = Thursday, Day 4 = Friday, Day 5 = Monday (of the next week). So a 5-business-day deadline starting Monday is due the following Monday. If the starting day is Wednesday: Day 1 = Thursday, Day 2 = Friday, Day 3 = Monday, Day 4 = Tuesday, Day 5 = Wednesday — due the following Wednesday.",
      },
      {
        question: "How many business days are in a year?",
        answer: "A standard year has 52 weeks plus 1 or 2 extra days. Each week contributes 5 business days, giving 260 or 261 business days before holidays. After typical US federal holidays (about 10 per year), there are approximately 250–251 business days annually. The exact count varies by year because different days of the week January 1 falls on affect how weekends and the extra days align. Leap years have one additional day but that adds at most one business day.",
      },
      {
        question: "What is the difference between business days and calendar days?",
        answer: "Calendar days count every day from Monday to Sunday — all 7 days per week. Business days count only Monday through Friday — 5 days per week. A 10-calendar-day period contains either 6 or 8 business days depending on where in the week it falls. Business and legal deadlines often specify which type to use. When the document is silent, context usually clarifies: 'two-day shipping' typically means calendar days, while 'processing time' at a bank typically means business days.",
      },
      {
        question: "How do I add business days to a date to find a future date?",
        answer: "To find a date that is N business days in the future, start from your date and count forward, skipping Saturdays and Sundays. For example, to add 3 business days to Friday, January 10: skip the weekend, count Monday (1), Tuesday (2), Wednesday (3) — your date is Wednesday, January 15. A quick formula: if you have a full number of weeks (divide N by 5), add those weeks first (× 7 calendar days), then add the remaining days, skipping any weekend that might fall in the remainder. Our Date Difference Calculator can verify your result.",
      },
    ],
    relatedCalculators: ["date-difference", "countdown", "overtime"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "time-duration",
    slug: "time-duration-calculator",
    category: "Date & Time",
    categorySlug: "date-time",
    title: "Time Duration Calculator",
    shortDescription: "Convert hours, minutes, and seconds to total time in multiple formats.",
    seoTitle: "Time Duration Calculator — Convert Hours, Minutes & Seconds",
    metaDescription: "Calculate total time duration from hours, minutes, and seconds. Convert to decimal hours, minutes, or seconds. Perfect for timesheets and billing.",
    primaryKeyword: "time duration calculator",
    secondaryKeywords: ["hours minutes seconds calculator", "timesheet calculator", "time converter", "decimal hours calculator"],
    fields: [
      {
        id: "hours",
        label: "Hours",
        type: "number",
        placeholder: "0",
        min: 0,
        defaultValue: 0,
        required: false,
      },
      {
        id: "minutes",
        label: "Minutes",
        type: "number",
        placeholder: "0",
        min: 0,
        defaultValue: 0,
        required: false,
      },
      {
        id: "seconds",
        label: "Seconds",
        type: "number",
        placeholder: "0",
        min: 0,
        defaultValue: 0,
        required: false,
      },
    ],
    results: [
      { id: "totalHours", label: "Total Hours (decimal)", format: "number", decimals: 4, isPrimary: true },
      { id: "totalMinutes", label: "Total Minutes", format: "number", decimals: 2, isPrimary: false },
      { id: "totalSeconds", label: "Total Seconds", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Total seconds = hours × 3600 + minutes × 60 + seconds; Decimal hours = total seconds / 3600",
    formulaExplanation: "All time components are converted to a common unit (seconds), then converted to the desired output format. Decimal hours are used in billing and payroll: 1 hour 30 minutes = 1.5 hours.",
    formulaSource: "Standard time conversion",
    explanation: "Converting time between hours:minutes:seconds format and decimal hours is a common task in payroll, billing, and productivity tracking. The time duration calculator handles this conversion instantly.\n\nDecimal hours are essential for billing clients (3 hours 45 minutes billed at $150/hour = 3.75 × $150 = $562.50) and for entering time in payroll systems that accept decimal input. Converting manually is error-prone: 2 hours 40 minutes is NOT 2.40 hours — it's 2.667 hours (40/60 = 0.667).\n\nThis calculator also converts total time to minutes or seconds, useful for:\n- Event timing and athletics (where 1:23:45 needs to be compared to 5,025 seconds)\n- Music and video production (where project length is counted in total seconds)\n- Computing data rates and other per-second measurements\n- Scientific experiments where total duration in seconds is required",
    example: {
      inputs: { hours: "2", minutes: "45", seconds: "30" },
      explanation: "2 hours, 45 minutes, 30 seconds = 9,930 total seconds = 165.5 total minutes = 2.7583 decimal hours. Billed at $100/hour, this equals $275.83.",
    },
    faqs: [
      {
        question: "Why is 1 hour 30 minutes not 1.30 hours in decimal?",
        answer: "Minutes are sixtiethths of an hour, not hundredths (tenths). So 30 minutes = 30/60 = 0.5 hours, not 0.30 hours. This is the most common mistake in manual time conversion. The full conversion: decimal hours = hours + (minutes / 60) + (seconds / 3600). Some examples: 15 min = 0.25 hr, 20 min = 0.333 hr, 45 min = 0.75 hr, 50 min = 0.833 hr. Always divide minutes by 60 (not 100) to convert to decimal hours.",
      },
      {
        question: "How do I use decimal hours for payroll and billing?",
        answer: "To bill correctly: convert your time to decimal hours, then multiply by your hourly rate. For example, 3 hours 20 minutes = 3 + (20/60) = 3.333 hours. At $90/hour: 3.333 × $90 = $300. For payroll, weekly hours are totaled in decimal: 8h 30m + 7h 45m + 9h 15m = 8.5 + 7.75 + 9.25 = 25.5 decimal hours. Most payroll software accepts decimal hours directly. Double-checking with this calculator prevents under- or overbilling clients.",
      },
      {
        question: "How do I add multiple time durations together?",
        answer: "The easiest method is to convert everything to seconds, add the seconds together, then convert back to hours:minutes:seconds. For example, 1h 45m + 2h 50m: convert to seconds (6300 + 10200 = 16500 total seconds), then convert back: 16500 / 3600 = 4.583 hours = 4 hours 35 minutes. You can also add hours and minutes separately and carry over: 1+2=3 hours, 45+50=95 minutes → 95−60=35 minutes with 1 hour carried → total 4h 35m.",
      },
      {
        question: "What is the difference between time duration and time of day?",
        answer: "Time duration measures an elapsed period (how long something takes), while time of day indicates a specific point on the clock. Duration: 1 hour 30 minutes means 90 minutes have passed. Time of day: 1:30 means 1:30 AM or 1:30 PM. Duration math (subtracting start time from end time) gives elapsed duration, but crossing midnight requires adding 24 hours to the end time if it's less than the start time. This calculator handles duration only — for clock-time arithmetic, use a dedicated time calculator.",
      },
      {
        question: "How many seconds are in a day, week, or year?",
        answer: "One day = 24 hours × 60 minutes × 60 seconds = 86,400 seconds. One week = 7 × 86,400 = 604,800 seconds. One standard year = 365 × 86,400 = 31,536,000 seconds. One leap year = 366 × 86,400 = 31,622,400 seconds. A common rough estimate: one year ≈ π × 10^7 seconds (about 31.4 million seconds), which is accurate to within 0.5%. These values matter in computing (Unix timestamps count seconds since Jan 1, 1970), physics, and time-critical systems.",
      },
    ],
    relatedCalculators: ["date-difference", "overtime", "business-days"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "overtime",
    slug: "overtime-calculator",
    category: "Date & Time",
    categorySlug: "date-time",
    title: "Overtime Calculator",
    shortDescription: "Calculate overtime pay based on regular hours, total hours worked, and your overtime multiplier.",
    seoTitle: "Overtime Calculator — Calculate Overtime Pay & Total Earnings",
    metaDescription: "Calculate your overtime pay based on hours worked and overtime rate. Supports standard 1.5x and custom multipliers. Free overtime pay calculator.",
    primaryKeyword: "overtime calculator",
    secondaryKeywords: ["overtime pay calculator", "time and a half calculator", "double time calculator", "paycheck calculator"],
    sensitivity: "finance",
    fields: [
      {
        id: "regularHours",
        label: "Regular Hours Threshold",
        type: "number",
        placeholder: "40",
        defaultValue: 40,
        required: true,
        helpText: "Hours before overtime kicks in (usually 40 per week in the US)",
      },
      {
        id: "totalHours",
        label: "Total Hours Worked",
        type: "number",
        placeholder: "e.g. 48",
        required: true,
      },
      {
        id: "hourlyRate",
        label: "Hourly Rate ($)",
        type: "number",
        placeholder: "e.g. 20",
        unit: "$",
        required: true,
      },
      {
        id: "overtimeMultiplier",
        label: "Overtime Multiplier",
        type: "number",
        placeholder: "1.5",
        defaultValue: 1.5,
        required: true,
        helpText: "Standard overtime is 1.5× (time-and-a-half). Some employers pay 2× (double time).",
      },
    ],
    results: [
      { id: "regularPay", label: "Regular Pay", format: "currency", decimals: 2, isPrimary: false },
      { id: "overtimePay", label: "Overtime Pay", format: "currency", decimals: 2, isPrimary: false },
      { id: "totalPay", label: "Total Pay", format: "currency", decimals: 2, isPrimary: true },
      { id: "overtimeHours", label: "Overtime Hours", format: "number", decimals: 2, isPrimary: false },
      { id: "overtimeRate", label: "Overtime Rate", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "Regular pay = min(hours, threshold) × rate; Overtime pay = max(0, hours − threshold) × rate × multiplier",
    formulaExplanation: "Regular pay covers hours up to the threshold (typically 40). Overtime pay covers hours beyond the threshold at the overtime rate (regular rate × multiplier). Most US non-exempt employees are entitled to 1.5× pay for hours over 40 per week under FLSA.",
    formulaSource: "US Fair Labor Standards Act (FLSA)",
    sourceUrl: "https://www.dol.gov/agencies/whd/overtime",
    explanation: "Overtime pay compensates employees for working beyond standard hours. In the United States, the Fair Labor Standards Act (FLSA) requires most employers to pay non-exempt employees at least 1.5 times their regular rate ('time and a half') for all hours worked beyond 40 in a workweek.\n\nSome states have additional overtime rules. California requires overtime for hours over 8 in a single day, not just over 40 in a week. Some employers voluntarily pay double time (2×) for extremely long shifts or weekend work.\n\nThis calculator handles the most common scenario: weekly overtime triggered after a threshold of hours. The formula is straightforward — regular hours × base rate, plus overtime hours × (base rate × multiplier).\n\nNote: This calculator is for estimation purposes. Actual overtime eligibility depends on FLSA exemption status, your state's labor laws, and your employment agreement. Consult HR or a labor attorney for questions about your specific situation.",
    example: {
      inputs: { regularHours: "40", totalHours: "48", hourlyRate: "20", overtimeMultiplier: "1.5" },
      explanation: "48 total hours − 40 regular = 8 overtime hours. Regular pay: 40 × $20 = $800. Overtime pay: 8 × ($20 × 1.5) = 8 × $30 = $240. Total pay: $800 + $240 = $1,040.",
    },
    faqs: [
      {
        question: "Who is eligible for overtime pay in the US?",
        answer: "Under the FLSA, non-exempt employees are entitled to overtime. Most hourly workers are non-exempt. Salaried employees may be exempt if they earn above a certain salary threshold ($684/week as of 2020, subject to change) AND perform executive, administrative, or professional duties. Teachers, lawyers, doctors, and certain other professionals may also be exempt. If you're unsure of your status, the Department of Labor's Wage and Hour Division can help determine whether you're entitled to overtime.",
      },
      {
        question: "What is 'time and a half' and how is it calculated?",
        answer: "Time and a half means 1.5 times your regular hourly rate for each overtime hour worked. If you earn $18/hour normally, your overtime rate is $18 × 1.5 = $27/hour. For every hour beyond the threshold, you earn $27 instead of $18. The 'half' comes from the extra 50% pay: you still earn your regular rate ($18) plus a premium of half that rate ($9) for a total of $27. Over 8 overtime hours at this rate, the premium alone adds up to $9 × 8 = $72 extra earnings.",
      },
      {
        question: "Can my employer require me to work overtime?",
        answer: "Generally yes — in the US, most employers can require overtime as a condition of employment, and refusing can be grounds for discipline or termination. There's no federal law capping the maximum hours an adult can work (unlike many countries). However, employers must pay overtime rates for hours over the FLSA threshold. Some professions have specific restrictions (truck drivers have hours-of-service limits from the FMCSA; healthcare workers may have state-specific rules). Always check your employment contract and state labor laws.",
      },
      {
        question: "How does overtime work for different pay periods?",
        answer: "FLSA overtime is calculated per workweek (a fixed, recurring 7-day period), regardless of whether you're paid weekly, biweekly, or semi-monthly. Even if you're paid biweekly, your employer must calculate overtime for each individual 7-day workweek separately — you can't average two weeks together. So if you work 50 hours in week 1 and 30 in week 2 (80 total), you're entitled to 10 hours of overtime for week 1, not zero overtime based on the 40-hour biweekly average.",
      },
      {
        question: "What is double time and when does it apply?",
        answer: "Double time is 2× the regular hourly rate. It's not required by federal law in the US, but California law requires it for hours over 12 in a single workday and for the 7th consecutive day of a workweek. Some union contracts and employer policies voluntarily provide double time for holiday work, overnight shifts, or hours beyond a certain threshold. If you're working under a collective bargaining agreement or in California, check the specific provisions that apply to your situation.",
      },
    ],
    relatedCalculators: ["time-duration", "hourly-wage", "paycheck"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "countdown",
    slug: "countdown-calculator",
    category: "Date & Time",
    categorySlug: "date-time",
    title: "Countdown Calculator",
    shortDescription: "Calculate exactly how long until any future date in years, months, weeks, days, hours, and minutes.",
    seoTitle: "Countdown Calculator — Days Until Any Date",
    metaDescription: "Calculate the countdown to any date: how many days, hours, and minutes until your event. Free online countdown timer and date calculator.",
    primaryKeyword: "countdown calculator",
    secondaryKeywords: ["days until calculator", "how many days until", "event countdown", "date countdown timer"],
    fields: [
      {
        id: "targetDate",
        label: "Target Date",
        type: "date",
        required: true,
        helpText: "Enter the future date you want to count down to",
      },
    ],
    results: [
      { id: "totalDays", label: "Total Days Remaining", format: "number", decimals: 0, isPrimary: true },
      { id: "weeks", label: "Weeks", format: "number", decimals: 1, isPrimary: false },
      { id: "months", label: "Months (approx.)", format: "number", decimals: 1, isPrimary: false },
    ],
    formula: "Days remaining = (Target Date − Today) in days",
    formulaExplanation: "Subtracting today's timestamp from the target date's timestamp measures the raw interval between the two moments, and dividing that span by the number of milliseconds in a day converts it into whole days remaining. Reading the current date dynamically each time the calculation runs is what keeps the countdown accurate — the figure reflects the actual present moment rather than a value frozen when the page first loaded, so it never drifts out of date.",
    formulaSource: "Standard calendar/time arithmetic",
    explanation: "A countdown calculator tells you exactly how much time stands between today and any future date, expressed in days, weeks, and months. Whether you are counting down to a wedding, a product launch, a final exam, or a long-awaited holiday, converting a vague sense of 'a few months away' into a precise number of days makes the interval feel real and easier to plan around.\n\nThe method is direct calendar arithmetic: the countdown calculator subtracts today's date from your target date and reports the gap. Because it reads the current date each time it runs, the result is always live — reload the page tomorrow and the number drops by one. It automatically accounts for leap years, so a span crossing February 29 is counted correctly without any manual adjustment.\n\nBeyond curiosity, a countdown serves a genuine psychological purpose: research on goal setting shows that attaching a specific date to an objective increases motivation and follow-through. Students pacing revision, project managers tracking a launch, event planners, and anyone chasing a personal deadline use a countdown calculator to break a long stretch of time into concrete weekly milestones they can actually act on.",
    example: {
      inputs: { targetDate: "2025-12-31" },
      explanation: "If today is February 1, 2025, then December 31, 2025 is 333 days away — about 47.6 weeks or 10.9 months. Knowing there are 333 days until a goal helps break down the work into manageable weekly targets.",
    },
    faqs: [
      {
        question: "What if my target date has already passed?",
        answer: "If the target date is in the past, the calculator will show a negative number of days — indicating how many days ago that date occurred. This is useful for calculating how long it's been since an event. For counting days since a past event, the Date Difference Calculator is more appropriate, as it's designed for historical date ranges. The Countdown Calculator is optimized for future events but will still correctly report negative values for past dates.",
      },
      {
        question: "How accurate is the days remaining count?",
        answer: "The countdown is accurate to the day — it uses your current date (from your device's clock) and calculates the exact number of full calendar days until the target date. It doesn't currently account for time of day: if there are 5 days and 6 hours remaining, it shows 5 days. For hour-level precision in countdowns, you'd need to factor in the specific time of day of the target event. The calculation automatically accounts for leap years, so February 29 in a leap year is correctly included.",
      },
      {
        question: "How many weeks is 100 days?",
        answer: "100 days is exactly 14 weeks and 2 days, or approximately 14.3 weeks. Dividing any number of days by 7 gives the week equivalent. Some common conversions: 30 days ≈ 4.3 weeks; 90 days ≈ 12.9 weeks; 100 days ≈ 14.3 weeks; 180 days ≈ 25.7 weeks; 365 days ≈ 52.1 weeks. These conversions are useful for project planning and breaking long timeframes into weekly milestones.",
      },
      {
        question: "How can I use a countdown for goal setting?",
        answer: "Set your target date first, then divide the total days into milestones. For a 100-day countdown: week 1-2 (research and planning), weeks 3-6 (build foundation), weeks 7-10 (execute main work), weeks 11-13 (refine and polish), week 14 (final preparation). Knowing exactly how many days remain creates urgency and helps prioritize. Many productivity systems (like '100-day challenges' and marathon training plans) use countdowns to structure consistent daily progress toward a defined deadline.",
      },
      {
        question: "What are some popular events people count down to?",
        answer: "Common countdowns include: New Year's Day (January 1), Christmas and major holidays, personal events (birthdays, anniversaries, weddings), professional deadlines (project launches, exam dates, contract renewals), travel (vacation departure, flight departure), sports events (Super Bowl, World Cup, Olympics), academic milestones (graduation, semester start/end), and financial dates (tax deadlines, enrollment periods). Countdowns work for any future date that holds significance — the specificity of a date makes preparation feel more concrete and actionable.",
      },
    ],
    relatedCalculators: ["date-difference", "age", "business-days"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
];
