import type { CalculatorDefinition } from "../types";

export const engineeringR6Calculators: CalculatorDefinition[] = [
  {
    id: "power-dissipation",
    slug: "power-dissipation-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Power Dissipation Calculator",
    shortDescription: "Find power dissipated by a resistor.",
    seoTitle: "Power Dissipation Calculator — I²R Resistor Power",
    metaDescription: "Free power dissipation calculator. Enter current and resistance to find the power a resistor dissipates as heat using the P = I²R formula from Joule's law.",
    primaryKeyword: "power dissipation calculator",
    secondaryKeywords: ["resistor power calculator", "i squared r calculator", "joule heating calculator"],
    fields: [
      { id: "current", label: "Current", type: "number", unit: "A", required: true, span: 1, helpText: "Current flowing through the resistor." },
      { id: "resistance", label: "Resistance", type: "number", unit: "Ω", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "power", label: "Power dissipated", format: "number", decimals: 4, unit: "W", isPrimary: true },
    ],
    formula: "P = I² × R",
    formulaExplanation: "Power dissipation follows Joule's law: the power converted to heat in a resistor equals the current squared multiplied by the resistance. Current appears squared because power is voltage times current and, by Ohm's law, the voltage across the resistor is itself current times resistance. Doubling the current therefore quadruples the heat, which is why current, not resistance, usually dominates thermal problems in real circuits.",
    explanation: "Power dissipation is the rate at which a resistor turns electrical energy into heat, and this power dissipation calculator finds that figure from the current flowing through the component and its resistance. Every resistor, wire, and load with resistance dissipates power whenever current passes through it, and that energy leaves as heat rather than doing useful work, so knowing the amount is essential for keeping components within their thermal limits.\n\nThis matters because every resistor carries a power rating, often a quarter or half a watt, and exceeding it makes the part overheat, drift in value, or burn out. Designers use a power dissipation calculator to choose resistors with enough headroom, to size heat sinks, and to estimate how much energy a circuit wastes. It also explains why long cables warm up and why high-current wiring must be thick.\n\nThe formula works because power equals voltage times current, and Ohm's law lets you replace the voltage across a resistor with current times resistance, giving current squared times resistance. Because current is squared, small increases in current cause large jumps in heat. Electronics engineers, hobbyists, and students rely on a power dissipation calculator to keep parts cool and circuits reliable.",
    example: { inputs: { current: 3, resistance: 4 }, explanation: "P = 3² × 4 = 9 × 4 = 36 W dissipated as heat in the resistor." },
    faqs: [
      {
        question: "How is power dissipation calculated?",
        answer: "Power dissipation in a resistor equals the current through it squared, multiplied by its resistance, written P equals I squared R. This comes from Joule's law and Ohm's law combined. For example, three amps through a four-ohm resistor dissipates nine times four, or thirty-six watts, entirely as heat. Because current is squared, it has a far stronger effect on heating than resistance does.",
      },
      {
        question: "Why is the current term squared?",
        answer: "Power equals voltage multiplied by current, and by Ohm's law the voltage across a resistor equals current times resistance. Substituting that voltage into the power equation replaces one current with resistance times current, leaving current squared times resistance. This squaring means doubling the current quadruples the heat produced, which is why high-current circuits demand careful attention to conductor size and cooling far more than low-current ones do.",
      },
      {
        question: "What is a resistor's power rating?",
        answer: "A resistor's power rating is the maximum power it can safely dissipate as heat without damage, commonly an eighth, quarter, half, one, or two watts for through-hole parts. If the calculated dissipation approaches or exceeds this figure, the resistor overheats, drifts in value, or fails. Good practice keeps the actual dissipation below about half the rating to leave a safety margin for reliability and long life.",
      },
      {
        question: "Does power dissipation cause energy loss?",
        answer: "Yes. The power a resistor dissipates leaves the circuit as heat and cannot be recovered as useful work, so it represents wasted energy. In power electronics and long cable runs, minimising this loss improves efficiency and reduces cooling needs. That is why engineers select low-resistance conductors for high current and why energy-conscious designs try to avoid dropping voltage across resistive elements unnecessarily.",
      },
      {
        question: "Can I calculate power from voltage instead?",
        answer: "Yes. If you know the voltage across the resistor rather than the current, power equals voltage squared divided by resistance, or simply voltage times current. All three forms give the same result and follow from Ohm's law. This calculator uses the current-and-resistance form because current and resistance are often the known quantities, but you can convert your figures using Ohm's law first if needed.",
      },
    ],
    relatedCalculators: ["resistor-calculator", "voltage-divider-calculator", "capacitor-energy-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Joule's law (P = I²R)",
  },
  {
    id: "resistor",
    slug: "resistor-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Resistor Calculator",
    shortDescription: "Combine two resistors in series or parallel.",
    seoTitle: "Resistor Calculator — Series and Parallel Resistance",
    metaDescription: "Free resistor calculator. Enter two resistor values and choose series or parallel to find the equivalent resistance of the combination instantly.",
    primaryKeyword: "resistor calculator",
    secondaryKeywords: ["series parallel resistor calculator", "equivalent resistance calculator", "parallel resistor calculator"],
    fields: [
      { id: "r1", label: "Resistor R1", type: "number", unit: "Ω", required: true, span: 1, min: 0 },
      { id: "r2", label: "Resistor R2", type: "number", unit: "Ω", required: true, span: 1, min: 0 },
      { id: "configuration", label: "Configuration", type: "select", required: true, span: 2, options: [
        { value: "series", label: "Series" },
        { value: "parallel", label: "Parallel" },
      ], defaultValue: "series" },
    ],
    results: [
      { id: "resistance", label: "Equivalent resistance", format: "number", decimals: 4, unit: "Ω", isPrimary: true },
    ],
    formula: "series: R = R1 + R2  ·  parallel: R = (R1 × R2) ÷ (R1 + R2)",
    formulaExplanation: "Resistors in series carry the same current, so their voltage drops add and the equivalent resistance is simply the sum R1 plus R2. Resistors in parallel share the same voltage, so their currents add; this makes the reciprocals of resistance add, which for two resistors simplifies to the product over the sum. The parallel result is always smaller than either resistor because adding a second path lets more total current flow.",
    explanation: "Combining resistors is one of the most common tasks in circuit design, and this resistor calculator finds the equivalent resistance of two resistors wired either in series or in parallel. In series the resistors sit end to end so their values add, while in parallel they sit side by side so the combined resistance drops below the smaller of the two. Selecting the configuration gives the single resistance the pair behaves as.\n\nThis matters because real circuits rarely use a single ideal resistor. Engineers combine standard values to hit a target resistance that no single stock part provides, set bias currents, build attenuators, and share load between components. Knowing the equivalent value lets you predict currents and voltages elsewhere in the circuit, so a resistor calculator saves both breadboard time and arithmetic mistakes.\n\nThe formulas work from two rules: series resistors carry the same current and their voltages add, so resistance sums; parallel resistors share the same voltage and their currents add, so their reciprocals sum, which for a pair reduces to product over sum. Electronics students, technicians, and hardware designers use a resistor calculator to reach precise resistances and to analyse networks quickly and reliably.",
    example: { inputs: { r1: 100, r2: 200, configuration: "parallel" }, explanation: "Parallel: (100 × 200) ÷ (100 + 200) = 20000 ÷ 300 ≈ 66.67 Ω, less than either resistor." },
    faqs: [
      {
        question: "How do resistors add in series?",
        answer: "Resistors in series are connected end to end so the same current flows through each one. Their voltage drops add up, which means the equivalent resistance is simply the sum of the individual values. Two resistors of 100 and 200 ohms in series give 300 ohms. Series connection always increases total resistance, and it is used to build up to values that single resistors do not provide.",
      },
      {
        question: "How do resistors combine in parallel?",
        answer: "Parallel resistors are connected across the same two nodes, sharing the same voltage while their currents add. The reciprocals of the resistances add, so for two resistors the equivalent equals their product divided by their sum. The result is always smaller than the smallest resistor, because offering current more than one path lowers the overall opposition to flow through the combination.",
      },
      {
        question: "Why is parallel resistance smaller than either resistor?",
        answer: "Adding a resistor in parallel gives current an extra route, so more total current flows for the same voltage, which by Ohm's law means less overall resistance. No matter how large the second resistor is, it can only add current and never remove any, so the combined resistance must fall below the smaller of the two. Identical parallel resistors halve the resistance.",
      },
      {
        question: "Can I use this for more than two resistors?",
        answer: "This calculator handles two resistors at a time, but you can chain it for larger networks. Combine the first two, then treat their equivalent as one resistor and combine it with the third, and so on. Work outward from the innermost series or parallel groups. For complex networks that are neither purely series nor parallel, you may need mesh or nodal analysis instead.",
      },
      {
        question: "Why combine resistors instead of buying one value?",
        answer: "Standard resistors come in fixed value series like E12 or E24, so the exact resistance a design needs often falls between available parts. Combining two stock resistors in series or parallel reaches intermediate values precisely and cheaply. It also lets designers share power dissipation across two parts, improve tolerance by averaging, or make use of resistors already on hand rather than ordering a special value.",
      },
    ],
    relatedCalculators: ["power-dissipation-calculator", "voltage-divider-calculator", "capacitor-energy-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard electrical engineering (series/parallel resistance)",
  },
  {
    id: "capacitor-energy",
    slug: "capacitor-energy-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Capacitor Energy Calculator",
    shortDescription: "Find energy stored in a capacitor.",
    seoTitle: "Capacitor Energy Calculator — Stored Energy in Joules",
    metaDescription: "Free capacitor energy calculator. Enter capacitance in farads and voltage to find the energy stored in a capacitor using the E = ½CV² formula.",
    primaryKeyword: "capacitor energy calculator",
    secondaryKeywords: ["energy stored in capacitor calculator", "capacitor joules calculator", "half cv squared calculator"],
    fields: [
      { id: "capacitanceFarads", label: "Capacitance", type: "number", unit: "F", required: true, span: 1, min: 0, helpText: "Capacitance in farads (1 µF = 0.000001 F)." },
      { id: "voltage", label: "Voltage", type: "number", unit: "V", required: true, span: 1 },
    ],
    results: [
      { id: "energy", label: "Stored energy", format: "number", decimals: 6, unit: "J", isPrimary: true },
    ],
    formula: "E = ½ × C × V²",
    formulaExplanation: "The energy stored in a capacitor equals one-half of its capacitance times the voltage squared. Voltage is squared because as charge accumulates on the plates, the voltage rises in proportion, and the work done to add each new bit of charge grows with the voltage already present. The stored energy is the area under the charge-versus-voltage line, which is a triangle, giving the one-half factor.",
    explanation: "A capacitor stores energy in the electric field between its plates, and this capacitor energy calculator finds how much, in joules, from the capacitance and the voltage across it. The larger the capacitance and the higher the voltage, the more energy is held, with voltage counting twice over because it appears squared. That stored energy can be released quickly to deliver a burst of power when the circuit demands it.\n\nThis matters in many applications: camera flashes, defibrillators, power-supply smoothing, motor-start circuits, and energy-recovery systems all rely on capacitors to store and dump energy on cue. Knowing the stored energy tells you how big a flash or pulse you can deliver, how much ride-through a supply has during a dropout, and how dangerous a charged capacitor bank is to handle, since large ones store enough energy to injure.\n\nThe formula works because the voltage on a capacitor rises in step with the charge you add, so the work to charge it fully is the triangular area under the charge-voltage line, giving one-half capacitance times voltage squared. Because voltage is squared, doubling it quadruples the stored energy. Electronics engineers, students, and technicians use a capacitor energy calculator to size storage and assess safety.",
    example: { inputs: { capacitanceFarads: 0.001, voltage: 12 }, explanation: "E = ½ × 0.001 × 12² = 0.5 × 0.001 × 144 = 0.072 J stored." },
    faqs: [
      {
        question: "How much energy does a capacitor store?",
        answer: "A capacitor stores energy equal to one-half its capacitance multiplied by the square of the voltage across it, measured in joules. A one-millifarad capacitor at twelve volts stores half times 0.001 times 144, or 0.072 joules. Larger capacitance and higher voltage both increase the stored energy, but because voltage is squared it has the stronger effect on the total energy held.",
      },
      {
        question: "Why is voltage squared in the formula?",
        answer: "As a capacitor charges, its voltage rises in proportion to the charge stored. The work needed to push each additional bit of charge onto the plates grows with the voltage already there, so the total energy is the triangular area under the charge-versus-voltage graph. That triangle gives one-half capacitance times voltage squared, which is why doubling the voltage quadruples the energy held.",
      },
      {
        question: "What units should I enter?",
        answer: "Enter capacitance in farads and voltage in volts to get energy in joules. Most real capacitors are rated in microfarads, nanofarads, or picofarads, so convert first: one microfarad is 0.000001 farad, one nanofarad is 0.000000001 farad. Entering a microfarad value directly without converting would overstate the energy by a factor of a million, so always convert to farads first.",
      },
      {
        question: "Are charged capacitors dangerous?",
        answer: "They can be. Large capacitors charged to high voltage, such as those in power supplies, camera flashes, or defibrillators, store enough energy to deliver a painful or even lethal shock long after power is removed. Always discharge big capacitors safely through a resistor before handling a circuit. This calculator's energy figure helps you judge the hazard: more stored joules means a more dangerous discharge.",
      },
      {
        question: "How is stored energy different from charge?",
        answer: "Charge is the amount of separated electric charge on the plates, equal to capacitance times voltage, measured in coulombs. Energy is the work stored in the resulting electric field, equal to one-half capacitance times voltage squared, measured in joules. Charge rises linearly with voltage while energy rises with voltage squared, so they are related but distinct quantities describing different aspects of the charged capacitor.",
      },
    ],
    relatedCalculators: ["power-dissipation-calculator", "resistor-calculator", "voltage-divider-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard electrical engineering (E = ½CV²)",
  },
  {
    id: "belt-length",
    slug: "belt-length-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Belt Length Calculator",
    shortDescription: "Find belt length for a two-pulley drive.",
    seoTitle: "Belt Length Calculator — Two-Pulley Drive Belt Length",
    metaDescription: "Free belt length calculator for a two-pulley drive. Enter both pulley diameters and the centre distance to find the required belt length instantly.",
    primaryKeyword: "belt length calculator",
    secondaryKeywords: ["pulley belt length calculator", "v belt length calculator", "drive belt calculator"],
    fields: [
      { id: "pulley1Diameter", label: "Pulley 1 diameter", type: "number", unit: "m", required: true, span: 1 },
      { id: "pulley2Diameter", label: "Pulley 2 diameter", type: "number", unit: "m", required: true, span: 1 },
      { id: "centerDistance", label: "Centre distance", type: "number", unit: "m", required: true, span: 2, min: 0, helpText: "Distance between the two pulley centres." },
    ],
    results: [
      { id: "beltLength", label: "Belt length", format: "number", decimals: 4, unit: "m", isPrimary: true },
    ],
    formula: "L = 2C + (π/2)(D1 + D2) + (D1 − D2)² ÷ (4C)",
    formulaExplanation: "The belt length of an open two-pulley drive has three parts: twice the centre distance for the two straight spans running between the pulleys, half pi times the sum of the diameters for the arcs the belt wraps around each pulley, and a correction term with the squared diameter difference over four times the centre distance that accounts for the belt angling when the pulleys differ in size. Together they trace the full belt path.",
    explanation: "The belt length is the total length of belt needed to wrap around two pulleys and connect them, and this belt length calculator computes it from the two pulley diameters and the distance between their centres. Getting this length right is essential when ordering or cutting a belt: too short and it will not fit or will overtension the bearings, too long and it slips or needs an idler to take up the slack.\n\nThis matters across mechanical drives: conveyor systems, machine tools, HVAC blowers, alternators, and countless industrial machines transmit power through belts and pulleys. Replacing a worn belt or designing a new drive both require the correct length, and buying the nearest standard belt size depends on knowing the theoretical figure first. A belt length calculator removes the guesswork and the risk of a costly mismatch.\n\nThe formula works by tracing the belt's path in three parts: the two straight runs between the pulleys give twice the centre distance, the wrap around each pulley contributes half pi times the summed diameters, and a small correction accounts for the belt angling when the pulleys differ in size. Maintenance engineers, machine builders, and technicians use a belt length calculator to specify replacement belts and design new transmissions accurately.",
    example: { inputs: { pulley1Diameter: 0.2, pulley2Diameter: 0.1, centerDistance: 0.5 }, explanation: "L = 2(0.5) + (π/2)(0.3) + (0.1)² ÷ (4 × 0.5) = 1 + 0.4712 + 0.005 ≈ 1.4762 m." },
    faqs: [
      {
        question: "How is belt length calculated for two pulleys?",
        answer: "For an open belt drive, the length equals twice the centre distance plus half pi times the sum of the two pulley diameters plus the squared difference of the diameters divided by four times the centre distance. The first term covers the straight spans, the second the wrap arcs, and the third corrects for unequal pulley sizes. This gives the total path the belt follows around both wheels.",
      },
      {
        question: "What is the centre distance?",
        answer: "The centre distance is the straight-line distance between the rotational centres of the two pulleys. It sets the length of the two straight belt spans and strongly influences the total belt length. In adjustable drives, the centre distance can often be changed slightly with a tensioner or sliding motor base to take up belt stretch or accommodate a nearby standard belt size.",
      },
      {
        question: "Does pulley size difference affect the length?",
        answer: "Yes. When the two pulleys have different diameters, the belt angles slightly between them rather than running perfectly parallel, which adds a small amount of length captured by the correction term with the squared diameter difference. For pulleys of similar size this term is tiny, but for a large speed-reduction drive with very different diameters it becomes more significant and should not be ignored.",
      },
      {
        question: "Why does my belt need to be a standard size?",
        answer: "Belts are manufactured in standard lengths, so the calculated theoretical length is used to select the nearest available belt. A tensioner or adjustable centre distance then takes up the small difference. Choosing the closest standard size that your drive can tension correctly ensures proper grip, avoids slippage, and keeps bearing loads within limits. This calculator gives the target figure to shop from.",
      },
      {
        question: "Does this formula apply to crossed belts?",
        answer: "No. This formula is for an open belt drive, where both pulleys turn in the same direction and the belt does not cross itself. A crossed belt, which reverses the driven pulley's direction, follows a different equation because the belt wraps a larger arc on each pulley. For crossed configurations, use the dedicated crossed-belt length formula instead of this open-drive one.",
      },
    ],
    relatedCalculators: ["gear-ratio-calculator", "motor-power-calculator", "shaft-power-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard mechanical engineering (open belt drive)",
  },
  {
    id: "hydraulic-pressure",
    slug: "hydraulic-pressure-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Hydraulic Pressure Calculator",
    shortDescription: "Find pressure from force over area.",
    seoTitle: "Hydraulic Pressure Calculator — Pressure from Force and Area",
    metaDescription: "Free hydraulic pressure calculator. Enter force in newtons and area in square metres to find the pressure in pascals using the P = F/A definition.",
    primaryKeyword: "hydraulic pressure calculator",
    secondaryKeywords: ["pressure force area calculator", "pascal pressure calculator", "hydraulic force calculator"],
    fields: [
      { id: "force", label: "Force", type: "number", unit: "N", required: true, span: 1 },
      { id: "area", label: "Area", type: "number", unit: "m²", required: true, span: 1, min: 0, helpText: "Area over which the force acts, e.g. a piston face." },
    ],
    results: [
      { id: "pressure", label: "Pressure", format: "number", decimals: 2, unit: "Pa", isPrimary: true },
    ],
    formula: "P = F ÷ A",
    formulaExplanation: "Pressure is defined as force divided by the area over which it acts, so a given force concentrated on a small area produces high pressure while the same force spread over a large area produces low pressure. In a hydraulic system the fluid transmits this pressure equally in all directions, following Pascal's principle, which lets a small input force on a small piston generate a large output force on a bigger piston.",
    explanation: "Hydraulic pressure is the force a fluid exerts spread over a given area, and this hydraulic pressure calculator finds it by dividing the applied force by the area it acts on, returning the result in pascals. Pressure captures how concentrated a force is: the same push on a tiny piston creates far higher pressure than on a broad one, which is the key to how hydraulic machinery multiplies force so effectively.\n\nThis matters in hydraulics and beyond: car brakes, jacks, presses, excavator arms, and aircraft controls all use pressurised fluid to turn a modest input into a powerful output. Knowing the pressure lets engineers select seals, hoses, and cylinders rated to withstand it, size pumps, and predict the force a cylinder will produce. A hydraulic pressure calculator connects the force, area, and pressure that govern these systems.\n\nThe formula works from the definition of pressure as force per unit area, combined with Pascal's principle that a confined fluid transmits pressure undiminished throughout. Because pressure stays constant through the fluid, a small piston can generate a pressure that a large piston converts back into a much greater force. Mechanical and fluid-power engineers, technicians, and students use a hydraulic pressure calculator to design and troubleshoot fluid systems.",
    example: { inputs: { force: 1000, area: 0.01 }, explanation: "P = 1000 ÷ 0.01 = 100000 Pa, or 100 kilopascals, acting on the piston face." },
    faqs: [
      {
        question: "How is hydraulic pressure calculated?",
        answer: "Pressure equals force divided by the area over which the force is applied, written P equals F over A. A force of 1000 newtons on an area of 0.01 square metres gives 100000 pascals. The smaller the area for a given force, the higher the pressure. This simple definition underlies all hydraulic systems, where pressurised fluid transmits and multiplies force between pistons of different sizes.",
      },
      {
        question: "What is Pascal's principle?",
        answer: "Pascal's principle states that pressure applied to a confined fluid is transmitted equally and undiminished throughout the fluid in every direction. This is why pressing a small piston in a hydraulic system creates the same pressure everywhere, allowing a larger piston elsewhere to produce a much greater force. It is the foundation of hydraulic jacks, presses, and brakes, which multiply force through this pressure equality.",
      },
      {
        question: "What units does this calculator use?",
        answer: "Enter force in newtons and area in square metres, and the pressure comes out in pascals, the SI unit equal to one newton per square metre. Pascals are small, so results are often large; divide by 1000 for kilopascals or by 100000 for bar. One bar is roughly atmospheric pressure. For pounds per square inch, multiply the pascal result by about 0.000145.",
      },
      {
        question: "How does a small force create a large force in hydraulics?",
        answer: "A small force on a small piston creates a certain pressure in the fluid. Because Pascal's principle spreads that pressure equally throughout, a larger piston with more area experiences the same pressure over a bigger surface, producing a proportionally larger force. The trade-off is distance: the large piston moves less than the small one, conserving energy while multiplying force, exactly like a lever.",
      },
      {
        question: "Why does area matter so much for pressure?",
        answer: "Because pressure is force divided by area, halving the area doubles the pressure for the same force, and vice versa. This is why a sharp knife concentrates force on a tiny edge to cut, and why wide tyres spread load to avoid sinking. In hydraulics, choosing piston areas sets both the pressure generated and the force multiplication the system delivers.",
      },
    ],
    relatedCalculators: ["pump-power-calculator", "pipe-flow-rate-calculator", "safety-factor-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard fluid mechanics (P = F/A, Pascal's principle)",
  },
  {
    id: "safety-factor",
    slug: "safety-factor-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Safety Factor Calculator",
    shortDescription: "Find the factor of safety of a design.",
    seoTitle: "Safety Factor Calculator — Factor of Safety from Strength and Stress",
    metaDescription: "Free safety factor calculator. Enter the material's ultimate strength and the applied stress to find the factor of safety for a component or structure.",
    primaryKeyword: "safety factor calculator",
    secondaryKeywords: ["factor of safety calculator", "fos calculator", "design safety factor calculator"],
    fields: [
      { id: "ultimateStrength", label: "Ultimate strength", type: "number", unit: "Pa", required: true, span: 1, helpText: "Maximum stress the material withstands before failure." },
      { id: "appliedStress", label: "Applied stress", type: "number", unit: "Pa", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "safetyFactor", label: "Factor of safety", format: "number", decimals: 3, isPrimary: true },
    ],
    formula: "FoS = ultimate strength ÷ applied stress",
    formulaExplanation: "The factor of safety is the ratio of a material's failure strength to the stress actually applied in service. A value of one means the part is loaded exactly to its limit with no margin, while a value of two means it could carry twice the load before failing. Dividing strength by stress expresses how many times over the design can bear the working load, giving a direct measure of the safety margin built in.",
    explanation: "The factor of safety measures how much stronger a component is than it strictly needs to be, and this safety factor calculator finds it by dividing the material's ultimate strength by the stress the part actually experiences in use. A result above one means the design has margin to spare, while a value at or below one warns that the part is loaded to or beyond its limit and is likely to fail.\n\nThis matters in every load-bearing design: bridges, cranes, pressure vessels, aircraft, lifting gear, and machine parts all carry a specified factor of safety set by codes, standards, or engineering judgement. The margin covers uncertainties in loads, material variability, manufacturing flaws, corrosion, and wear over time. A safety factor calculator lets designers confirm that a chosen material and cross-section keep the part comfortably away from failure.\n\nThe formula works because it compares the stress a material can withstand before failing with the stress it actually sees, expressing the result as a simple multiple. A factor of four means the part could take four times its working load before breaking. Typical values range from around 1.5 for well-understood static loads up to 10 or more for critical or uncertain applications. Structural, mechanical, and aerospace engineers rely on a safety factor calculator to verify designs.",
    example: { inputs: { ultimateStrength: 400, appliedStress: 100 }, explanation: "FoS = 400 ÷ 100 = 4, so the part could carry four times the applied stress before failing." },
    faqs: [
      {
        question: "What is a factor of safety?",
        answer: "The factor of safety is the ratio of a material's or component's failure strength to the actual stress it carries in service. It expresses how many times the working load the part could withstand before failing. A factor of three means the component could take three times its normal load before breaking. It is a core measure of how much margin a design holds against unexpected overload or weakness.",
      },
      {
        question: "What is a good factor of safety?",
        answer: "It depends on the application, the consequences of failure, and how well the loads and materials are understood. Common values range from about 1.5 to 2 for well-characterised static structures, up to 4 or more for dynamic loads, and 10 or higher for life-critical or highly uncertain cases. Design codes often specify the minimum required factor for a given type of structure or component.",
      },
      {
        question: "What does a factor of safety below one mean?",
        answer: "A factor below one means the applied stress exceeds the material's strength, so the component is expected to fail under the load it carries. A factor of exactly one means it is loaded right at its limit with no margin at all, which is unsafe because any variation in load, material, or geometry could cause failure. Designs almost always require a factor comfortably above one.",
      },
      {
        question: "Should I use ultimate or yield strength?",
        answer: "It depends on the failure mode you are guarding against. Use ultimate strength when the concern is fracture or complete rupture, and yield strength when any permanent deformation is unacceptable. Many designs calculate a factor of safety against yield to keep the part fully elastic. This calculator divides by whichever strength value you enter, so choose the one appropriate to your design criterion.",
      },
      {
        question: "Why not just design everything with a huge safety factor?",
        answer: "A very high factor of safety means heavier, bulkier, and more expensive parts, which wastes material and can hurt performance, especially where weight matters like in aircraft or vehicles. Engineering balances safety against cost, weight, and efficiency, choosing a factor large enough to cover real uncertainties without gross over-design. The goal is a margin that is adequate and appropriate, not simply as large as possible.",
      },
    ],
    relatedCalculators: ["stress-strain-calculator", "beam-deflection-calculator", "hydraulic-pressure-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard mechanical engineering (factor of safety)",
  },
  {
    id: "heat-transfer-rate",
    slug: "heat-transfer-rate-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Heat Transfer Rate Calculator",
    shortDescription: "Find conductive heat flow through a wall.",
    seoTitle: "Heat Transfer Rate Calculator — Fourier Conduction",
    metaDescription: "Free heat transfer rate calculator using Fourier's law. Enter thermal conductivity, area, temperature difference, and thickness to find conductive heat flow in watts.",
    primaryKeyword: "heat transfer rate calculator",
    secondaryKeywords: ["conduction heat transfer calculator", "fouriers law calculator", "thermal conduction calculator"],
    fields: [
      { id: "thermalConductivity", label: "Thermal conductivity", type: "number", unit: "W/m·K", required: true, span: 1, helpText: "Material property k." },
      { id: "area", label: "Area", type: "number", unit: "m²", required: true, span: 1, min: 0 },
      { id: "tempDifference", label: "Temperature difference", type: "number", unit: "K", required: true, span: 1 },
      { id: "thickness", label: "Thickness", type: "number", unit: "m", required: true, span: 1, min: 0, helpText: "Thickness of the material the heat crosses." },
    ],
    results: [
      { id: "heatRate", label: "Heat transfer rate", format: "number", decimals: 4, unit: "W", isPrimary: true },
    ],
    formula: "Q = k × A × ΔT ÷ thickness",
    formulaExplanation: "Fourier's law of conduction says the heat flow rate through a material equals its thermal conductivity times the cross-sectional area times the temperature difference across it, divided by its thickness. A bigger temperature gap or larger area drives more heat, a more conductive material passes heat more readily, and greater thickness slows the flow by lengthening the path heat must travel, which is exactly why insulation is made thick and from low-conductivity materials.",
    explanation: "The heat transfer rate tells you how fast thermal energy conducts through a solid barrier, and this heat transfer rate calculator computes it with Fourier's law from the material's thermal conductivity, the area, the temperature difference across it, and its thickness. The result, in watts, is the steady rate at which heat crosses the barrier from the hot side to the cold side, which sets how quickly a space heats up or cools down.\n\nThis matters for insulation and thermal design: building walls, refrigerator panels, furnace linings, electronic heat sinks, and clothing all manage heat flow through conduction. Engineers use the heat transfer rate to size insulation, estimate heating and cooling loads, and keep components within temperature limits. A heat transfer rate calculator quickly shows how conductivity, thickness, and area trade off against one another in a design.\n\nThe formula works because heat conducts faster when the temperature difference driving it is larger, when more area is available, and when the material conducts well, while thicker material lengthens the path and slows the flow. That is why insulation combines low-conductivity materials with generous thickness. Mechanical, building-services, and thermal engineers, along with students, rely on a heat transfer rate calculator to design efficient, comfortable, and safe thermal systems.",
    example: { inputs: { thermalConductivity: 0.5, area: 2, tempDifference: 30, thickness: 0.1 }, explanation: "Q = 0.5 × 2 × 30 ÷ 0.1 = 30 ÷ 0.1 = 300 W conducted through the wall." },
    faqs: [
      {
        question: "What is Fourier's law of conduction?",
        answer: "Fourier's law states that the rate of heat conduction through a material is proportional to the temperature difference across it and the area, and inversely proportional to the thickness, scaled by the material's thermal conductivity. In steady state it gives heat flow equals conductivity times area times temperature difference divided by thickness. It is the fundamental equation governing how heat moves through solid barriers like walls and insulation.",
      },
      {
        question: "What is thermal conductivity?",
        answer: "Thermal conductivity, symbol k, measures how readily a material conducts heat, in watts per metre per kelvin. Metals like copper have high conductivity and move heat quickly, while insulators like foam, wood, and air have low conductivity and resist heat flow. It is an intrinsic material property, so choosing a low-conductivity material is one of the main ways to reduce unwanted heat transfer in a design.",
      },
      {
        question: "How does thickness affect heat transfer?",
        answer: "Thickness appears in the denominator, so doubling the thickness of a material halves the rate of heat conduction through it, all else equal. A longer path gives heat more distance to travel and more resistance to overcome. This is why insulation is made thick: adding material directly reduces heat loss. There are practical and cost limits, so designers balance thickness against space and expense.",
      },
      {
        question: "What units does this calculator use?",
        answer: "Enter thermal conductivity in watts per metre-kelvin, area in square metres, temperature difference in kelvin, and thickness in metres. The heat transfer rate comes out in watts. Because a temperature difference of one kelvin equals one degree Celsius, you can enter the difference in degrees Celsius directly. Keeping all inputs in these consistent SI units ensures the resulting heat flow is correct.",
      },
      {
        question: "Does this account for convection and radiation?",
        answer: "No. This calculator handles only conduction, the transfer of heat through a solid material by direct contact. Real systems often also lose or gain heat by convection to surrounding air and by radiation, which follow different laws. For a complete thermal analysis, especially at surfaces exposed to air, you would combine conduction with convective and radiative terms rather than relying on conduction alone.",
      },
    ],
    relatedCalculators: ["reynolds-number-calculator", "pump-power-calculator", "pipe-flow-rate-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Fourier's law of heat conduction",
  },
  {
    id: "shaft-power",
    slug: "shaft-power-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Shaft Power Calculator",
    shortDescription: "Find mechanical power from torque and RPM.",
    seoTitle: "Shaft Power Calculator — Power from Torque and RPM in Watts",
    metaDescription: "Free shaft power calculator. Enter torque in newton-metres and rotational speed in RPM to find the mechanical power on a rotating shaft in watts.",
    primaryKeyword: "shaft power calculator",
    secondaryKeywords: ["torque to power calculator", "rotational power calculator", "shaft power watts calculator"],
    fields: [
      { id: "torque", label: "Torque", type: "number", unit: "N·m", required: true, span: 1 },
      { id: "rpm", label: "Rotational speed", type: "number", unit: "rpm", required: true, span: 1 },
    ],
    results: [
      { id: "power", label: "Shaft power", format: "number", decimals: 3, unit: "W", isPrimary: true },
    ],
    formula: "P = torque × 2π × rpm ÷ 60",
    formulaExplanation: "Mechanical power on a rotating shaft equals torque times angular velocity. Angular velocity in radians per second is the rotational speed in revolutions per minute multiplied by two pi, because each revolution is two pi radians, and divided by sixty to convert minutes to seconds. Multiplying torque by this angular velocity gives power directly in watts, tying the twisting force and the turning rate into a single measure of work done per second.",
    explanation: "Shaft power is the mechanical power transmitted by a rotating shaft, and this shaft power calculator finds it in watts from the torque on the shaft and its rotational speed in RPM. Power combines how hard the shaft twists with how fast it spins, giving the rate at which it does useful work, which is the true measure of what a motor, engine, or turbine can deliver to a load.\n\nThis matters when specifying and matching rotating machinery: pumps, fans, compressors, gearboxes, and generators are all rated by power because it determines how much work they move per second. Torque or speed on its own can mislead, since a shaft with high torque but low speed may deliver little power. A shaft power calculator gives the combined figure directly in SI watts for clean comparison and sizing.\n\nThe formula works because power equals torque times angular velocity, and angular velocity in radians per second comes from the RPM multiplied by two pi and divided by sixty. This converts revolutions per minute into the radians per second that pair correctly with torque in newton-metres to yield watts. Mechanical engineers, technicians, and students use a shaft power calculator to relate torque, speed, and power across drivetrains and rotating equipment.",
    example: { inputs: { torque: 50, rpm: 3000 }, explanation: "P = 50 × 2π × 3000 ÷ 60 = 5000 × π ≈ 15707.96 W, about 15.7 kW." },
    faqs: [
      {
        question: "How is shaft power calculated from torque and RPM?",
        answer: "Shaft power equals torque multiplied by angular velocity. Convert the rotational speed from RPM to radians per second by multiplying by two pi and dividing by sixty, then multiply by the torque in newton-metres to get power in watts. For example, 50 newton-metres at 3000 RPM gives about 15708 watts. This directly combines the twisting force and turning speed into a single power figure.",
      },
      {
        question: "Why multiply RPM by 2π and divide by 60?",
        answer: "Torque times angular velocity gives power only when angular velocity is in radians per second. Each revolution is two pi radians, so multiplying RPM by two pi converts revolutions to radians, and dividing by sixty converts per minute to per second. The combined factor turns a familiar RPM figure into the radians-per-second value that pairs correctly with newton-metres of torque to produce watts.",
      },
      {
        question: "What is the difference between torque and power?",
        answer: "Torque is the twisting force the shaft applies at any instant, while power is the rate at which that force does work as the shaft turns. A slow shaft with high torque can deliver the same power as a fast shaft with low torque. Power, which folds in the speed, is what ultimately determines how quickly a machine can move its load.",
      },
      {
        question: "How do I convert the result to horsepower or kilowatts?",
        answer: "This calculator gives power in watts. Divide by 1000 to get kilowatts, the standard metric rating for motors. To convert to mechanical horsepower, divide the watts by about 745.7. So 15708 watts is roughly 15.7 kilowatts or about 21 horsepower. Choose whichever unit matches the nameplate or specification you are comparing against for your equipment.",
      },
      {
        question: "Does this give input or output power?",
        answer: "It gives the mechanical power at the shaft corresponding to the torque and speed you enter. Whether that is input or output power depends on where you measure. Real machines lose some power to friction, windage, and heat, so the electrical input to a motor exceeds its shaft output. Divide shaft power by efficiency to estimate input power, or multiply input by efficiency for output.",
      },
    ],
    relatedCalculators: ["motor-power-calculator", "gear-ratio-calculator", "belt-length-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard mechanical engineering (rotational power)",
  },
  {
    id: "pipe-flow-rate",
    slug: "pipe-flow-rate-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Pipe Flow Rate Calculator",
    shortDescription: "Find volumetric flow rate in a pipe.",
    seoTitle: "Pipe Flow Rate Calculator — Volumetric Flow from Velocity and Diameter",
    metaDescription: "Free pipe flow rate calculator. Enter flow velocity and pipe diameter to find the volumetric flow rate in cubic metres per second and litres per second.",
    primaryKeyword: "pipe flow rate calculator",
    secondaryKeywords: ["volumetric flow rate calculator", "pipe flow calculator", "flow rate velocity calculator"],
    fields: [
      { id: "velocity", label: "Flow velocity", type: "number", unit: "m/s", required: true, span: 1 },
      { id: "pipeDiameter", label: "Pipe diameter", type: "number", unit: "m", required: true, span: 1, min: 0, helpText: "Inside diameter of the pipe." },
    ],
    results: [
      { id: "flowRate", label: "Flow rate", format: "number", decimals: 6, unit: "m³/s", isPrimary: true },
      { id: "flowLitersPerSec", label: "Flow rate", format: "number", decimals: 3, unit: "L/s", isPrimary: false },
    ],
    formula: "Q = velocity × π × (diameter ÷ 2)²",
    formulaExplanation: "Volumetric flow rate equals the flow velocity multiplied by the pipe's cross-sectional area. For a round pipe that area is pi times the radius squared, and the radius is half the diameter, so the flow rate is velocity times pi times the diameter over two squared. Multiplying the cubic-metres-per-second result by one thousand converts it to litres per second, since one cubic metre contains a thousand litres.",
    explanation: "The pipe flow rate is the volume of fluid passing through a pipe each second, and this pipe flow rate calculator computes it from the flow velocity and the pipe's inside diameter, giving results in both cubic metres per second and litres per second. Flow rate combines how fast the fluid moves with how wide the pipe is, since a wider pipe carries far more fluid at the same velocity than a narrow one.\n\nThis matters throughout plumbing and process engineering: water supply, irrigation, HVAC, chemical plants, and fuel systems all specify flow rates to ensure enough fluid reaches its destination without excessive velocity that causes noise, erosion, or pressure loss. A pipe flow rate calculator lets you check that a chosen pipe size and velocity deliver the required throughput, or work backwards to find the velocity a target flow demands.\n\nThe formula works because the flow rate is simply the cross-sectional area of the pipe multiplied by how fast the fluid crosses it. For a circular pipe the area is pi times the radius squared, and the radius is half the diameter you enter. Multiplying by a thousand restates the volume in litres. Mechanical, civil, and chemical engineers along with plumbers use a pipe flow rate calculator to size pipes and balance systems.",
    example: { inputs: { velocity: 2, pipeDiameter: 0.1 }, explanation: "Q = 2 × π × (0.05)² = 2 × π × 0.0025 ≈ 0.01571 m³/s, which is about 15.71 L/s." },
    faqs: [
      {
        question: "How is pipe flow rate calculated?",
        answer: "Volumetric flow rate equals the fluid's velocity multiplied by the pipe's cross-sectional area. For a round pipe, the area is pi times the radius squared, where the radius is half the diameter. So flow rate equals velocity times pi times the square of half the diameter. A faster velocity or a wider pipe both increase the volume of fluid delivered each second.",
      },
      {
        question: "What is the difference between flow rate and velocity?",
        answer: "Velocity is how fast the fluid moves along the pipe, in metres per second, while flow rate is the volume delivered per second, which also depends on the pipe's cross-sectional area. The same velocity in a wide pipe gives a much higher flow rate than in a narrow one. Flow rate is what matters for filling tanks and supplying demand; velocity governs pressure loss and erosion.",
      },
      {
        question: "Why does pipe diameter have such a big effect?",
        answer: "Because the cross-sectional area depends on the diameter squared, flow rate rises with the square of the diameter at a fixed velocity. Doubling the pipe diameter quadruples the flow it carries. This strong dependence is why even a modest increase in pipe size can dramatically boost capacity, and why undersized pipes force high velocities that waste pressure and cause noise.",
      },
      {
        question: "What units does this calculator use?",
        answer: "Enter velocity in metres per second and diameter in metres. The primary result is in cubic metres per second, and the calculator also shows litres per second by multiplying by one thousand, since one cubic metre equals a thousand litres. If your diameter is in millimetres, divide by 1000 first. For flow in cubic metres per hour, multiply the result by 3600.",
      },
      {
        question: "Does this assume the pipe is running full?",
        answer: "Yes. The calculation uses the full cross-sectional area of the pipe, so it assumes the pipe is completely filled with fluid moving at the entered velocity, as in a pressurised system. For a partially filled pipe, such as a gravity drain running part full, only the wetted area carries flow, so you would need the actual filled area rather than the full circular area.",
      },
    ],
    relatedCalculators: ["reynolds-number-calculator", "pump-power-calculator", "hydraulic-pressure-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard fluid mechanics (continuity, Q = vA)",
  },
  {
    id: "pump-power",
    slug: "pump-power-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Pump Power Calculator",
    shortDescription: "Find hydraulic power a pump must deliver.",
    seoTitle: "Pump Power Calculator — Hydraulic Power from Flow and Head",
    metaDescription: "Free pump power calculator. Enter flow rate, head, fluid density, and gravity to find the hydraulic power a pump must deliver in watts.",
    primaryKeyword: "pump power calculator",
    secondaryKeywords: ["hydraulic power calculator", "pump horsepower calculator", "water pump power calculator"],
    fields: [
      { id: "flowRate", label: "Flow rate", type: "number", unit: "m³/s", required: true, span: 1 },
      { id: "head", label: "Head", type: "number", unit: "m", required: true, span: 1, helpText: "Vertical height plus friction losses the pump overcomes." },
      { id: "fluidDensity", label: "Fluid density", type: "number", unit: "kg/m³", required: true, span: 1, defaultValue: 1000, helpText: "Water is about 1000 kg/m³." },
      { id: "gravity", label: "Gravity", type: "number", unit: "m/s²", required: true, span: 1, defaultValue: 9.81 },
    ],
    results: [
      { id: "hydraulicPower", label: "Hydraulic power", format: "number", decimals: 3, unit: "W", isPrimary: true },
    ],
    formula: "P = density × gravity × flow rate × head",
    formulaExplanation: "The hydraulic power a pump delivers to a fluid equals the fluid density times gravitational acceleration times the volumetric flow rate times the head. Density times gravity times head gives the pressure the pump must add, and multiplying that pressure by the volume flow rate gives power. In effect the pump raises a given mass of fluid per second through the head height, and this term is the rate of work needed to do so.",
    explanation: "Pump power is the rate at which a pump must add energy to a fluid to move it at a given flow and lift, and this pump power calculator finds the hydraulic power in watts from the flow rate, the head, the fluid density, and gravity. Head captures both the vertical height the fluid rises and the friction it must overcome, so the result is the useful power the pump imparts to the fluid stream.\n\nThis matters when selecting and sizing pumps: water supply, irrigation, drainage, heating circuits, and industrial process lines all need a pump matched to the required flow and head. Undersizing starves the system while oversizing wastes energy and money. A pump power calculator gives the hydraulic power baseline, which you then divide by the pump and motor efficiency to find the actual electrical power the pump will draw.\n\nThe formula works because density times gravity times head is the pressure the pump must generate, and pressure times volumetric flow rate equals power. Physically, the pump lifts a certain mass of fluid each second through the head, and this is the rate of work that requires. Mechanical, civil, and building-services engineers, along with technicians, use a pump power calculator to specify pumps and estimate running energy costs.",
    example: { inputs: { flowRate: 0.05, head: 10, fluidDensity: 1000, gravity: 9.81 }, explanation: "P = 1000 × 9.81 × 0.05 × 10 = 4905 W of hydraulic power delivered to the water." },
    faqs: [
      {
        question: "How is pump power calculated?",
        answer: "Hydraulic pump power equals the fluid density multiplied by gravitational acceleration, the volumetric flow rate, and the head. For water at 1000 kilograms per cubic metre pumping 0.05 cubic metres per second against 10 metres of head, the power is 1000 times 9.81 times 0.05 times 10, or 4905 watts. This is the useful power added to the fluid, before accounting for pump inefficiency.",
      },
      {
        question: "What is pump head?",
        answer: "Head is the total energy per unit weight the pump must add to the fluid, expressed as an equivalent height in metres. It combines the static lift, the vertical distance the fluid rises, with friction losses in the pipes and fittings and any pressure difference to overcome. A higher head means the pump works harder for the same flow, so accurate head figures are essential for correct sizing.",
      },
      {
        question: "Is this the electrical power the pump uses?",
        answer: "No. This calculates the hydraulic power delivered to the fluid, which is the useful output. The electrical power the pump draws is larger, because pumps and motors are not perfectly efficient. Divide the hydraulic power by the combined pump and motor efficiency, often between 0.5 and 0.8, to estimate the actual input power. That input figure is what determines running costs and the required supply.",
      },
      {
        question: "Why do density and gravity appear in the formula?",
        answer: "Density and gravity convert the head, a height, into the pressure the pump must produce, since pressure from a column of fluid equals density times gravity times height. Denser fluids need more power to pump to the same head because each cubic metre weighs more. Water is about 1000 kilograms per cubic metre; oils and slurries differ, so enter the correct density for accurate results.",
      },
      {
        question: "How do I convert the result to horsepower?",
        answer: "The calculator gives hydraulic power in watts. To convert to mechanical horsepower, divide by about 745.7, so 4905 watts is roughly 6.6 horsepower of hydraulic output. Remember this is the fluid power, not the motor rating; the motor must be larger to cover losses. Divide by efficiency first, then convert, to estimate the horsepower the driving motor actually needs.",
      },
    ],
    relatedCalculators: ["pipe-flow-rate-calculator", "hydraulic-pressure-calculator", "reynolds-number-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard fluid mechanics (hydraulic power P = ρgQH)",
  },
];
