import type { CalculatorDefinition } from "../types";

export const engineeringWave3Calculators: CalculatorDefinition[] = [
  {
    id: "gear-ratio",
    slug: "gear-ratio-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Gear Ratio Calculator",
    shortDescription: "Find gear ratio, output speed and torque.",
    seoTitle: "Gear Ratio Calculator — Ratio, Output RPM and Torque",
    metaDescription: "Free gear ratio calculator. Enter driving and driven teeth counts plus input speed and torque to find the gear ratio, output RPM, and output torque instantly.",
    primaryKeyword: "gear ratio calculator",
    secondaryKeywords: ["gear reduction calculator", "output rpm calculator", "torque ratio calculator"],
    fields: [
      { id: "drivingTeeth", label: "Driving gear teeth", type: "number", required: true, span: 1, min: 1, helpText: "Teeth on the input (driver) gear." },
      { id: "drivenTeeth", label: "Driven gear teeth", type: "number", required: true, span: 1, min: 1 },
      { id: "inputRpm", label: "Input speed", type: "number", unit: "rpm", required: true, span: 1 },
      { id: "inputTorque", label: "Input torque", type: "number", unit: "N·m", required: true, span: 1 },
    ],
    results: [
      { id: "ratio", label: "Gear ratio", format: "number", decimals: 3, isPrimary: true },
      { id: "outputRpm", label: "Output speed", format: "number", decimals: 2, unit: "rpm", isPrimary: false },
      { id: "outputTorque", label: "Output torque", format: "number", decimals: 2, unit: "N·m", isPrimary: false },
    ],
    formula: "ratio = driven teeth ÷ driving teeth",
    formulaExplanation: "The gear ratio equals the driven gear teeth divided by the driving gear teeth, because meshing gears must share the same tooth pitch, so tooth counts set how many turns of the driver produce one turn of the driven wheel. Output speed falls by that ratio while output torque rises by it, since power stays roughly constant and speed traded away returns as turning force.",
    explanation: "A gear ratio describes how a pair of meshing gears trades rotational speed for turning force, and this gear ratio calculator returns that ratio along with the output speed and output torque from the teeth counts and input values you enter. When a small driving gear turns a larger driven gear, the output shaft spins slower but delivers more torque, which is exactly how a car climbs a hill or a winch lifts a heavy load.\n\nThis relationship matters because almost every machine with rotating parts relies on it: gearboxes, bicycles, clocks, drills, wind turbines, and conveyor drives all pick tooth counts to hit a target speed or force. Getting the ratio right means the motor runs in its efficient range while the output does the work required, so a gear ratio calculator saves hours of trial and error at the design stage.\n\nThe formula works because meshing gears share the same tooth size, so their tooth counts fix how their rotations relate. Speed drops in proportion to the ratio while torque climbs by the same factor, since the power passing through stays nearly constant. Mechanical engineers, machinists, robotics builders, and students all use a gear ratio calculator to size drivetrains quickly and correctly.",
    example: { inputs: { drivingTeeth: 10, drivenTeeth: 30, inputRpm: 1000, inputTorque: 5 }, explanation: "30 ÷ 10 = 3, so output speed is 1000 ÷ 3 ≈ 333.33 rpm and output torque is 5 × 3 = 15 N·m." },
    faqs: [
      {
        question: "How is the gear ratio calculated?",
        answer: "The gear ratio is the number of teeth on the driven gear divided by the number of teeth on the driving gear. If the driven gear has 30 teeth and the driver has 10, the ratio is 3 to 1. This means the driving gear turns three times for every single turn of the driven gear, a reduction that trades speed for extra torque at the output shaft.",
      },
      {
        question: "Why does output torque increase when speed drops?",
        answer: "Power equals torque multiplied by rotational speed, and an ideal gear pair passes power through with little loss. When the ratio lowers the output speed, torque must rise by the same factor to keep the product roughly constant. That is why a reduction gearbox gives a small motor enough turning force to move a heavy load, at the cost of the output turning more slowly than the input.",
      },
      {
        question: "What is the difference between a driving and driven gear?",
        answer: "The driving gear, also called the driver, is the one connected to the power source such as a motor or pedal. The driven gear is the one it turns, connected to the load. The ratio between their teeth counts determines whether the setup increases speed or increases torque. Swapping which gear drives which inverts the ratio, turning a reduction into an overdrive and vice versa.",
      },
      {
        question: "What does a gear ratio greater than one mean?",
        answer: "A ratio above one is a reduction: the output turns slower than the input but with more torque. A ratio below one is an overdrive, giving higher output speed but less torque. A ratio of exactly one passes speed and torque straight through unchanged. Choosing the number depends on whether your application needs more force, like a winch, or more speed, like a fan.",
      },
      {
        question: "Can I chain multiple gear stages together?",
        answer: "Yes. When gears are arranged in stages, the total ratio is the product of each stage's individual ratio. Two 3-to-1 stages in series give an overall 9-to-1 reduction. Compound gear trains let designers reach very large ratios in a compact space without one enormous gear. Use this calculator stage by stage, then multiply the ratios together to find the complete drivetrain reduction.",
      },
    ],
    relatedCalculators: ["motor-power-calculator", "spring-constant-calculator", "stress-strain-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard mechanical engineering",
  },
  {
    id: "voltage-divider",
    slug: "voltage-divider-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Voltage Divider Calculator",
    shortDescription: "Find output voltage and current of a divider.",
    seoTitle: "Voltage Divider Calculator — Output Voltage and Current",
    metaDescription: "Free voltage divider calculator. Enter input voltage and two resistor values to find the output voltage and series current of a resistive divider instantly.",
    primaryKeyword: "voltage divider calculator",
    secondaryKeywords: ["resistor divider calculator", "vout calculator", "potential divider calculator"],
    fields: [
      { id: "vin", label: "Input voltage", type: "number", unit: "V", required: true, span: 2 },
      { id: "r1", label: "Resistor R1", type: "number", unit: "Ω", required: true, span: 1, min: 0, helpText: "Top resistor, between Vin and the output node." },
      { id: "r2", label: "Resistor R2", type: "number", unit: "Ω", required: true, span: 1, min: 0, helpText: "Bottom resistor, between the output node and ground." },
    ],
    results: [
      { id: "vout", label: "Output voltage", format: "number", decimals: 4, unit: "V", isPrimary: true },
      { id: "current", label: "Series current", format: "number", decimals: 6, unit: "A", isPrimary: false },
    ],
    formula: "Vout = Vin × R2 ÷ (R1 + R2)",
    formulaExplanation: "In a two-resistor divider the same current flows through both resistors, so the input voltage splits across them in proportion to their resistances. The output taken across R2 is therefore Vin scaled by R2 divided by the total resistance R1 plus R2. The series current equals Vin divided by that total resistance, following Ohm's law for the single loop the two resistors form.",
    explanation: "A voltage divider uses two resistors in series to produce a smaller, predictable output voltage from a larger input, and this voltage divider calculator returns that output along with the current flowing through the pair. Tap the connection between the two resistors and you get a fraction of the supply voltage set purely by the ratio of the resistor values, which makes dividers one of the most common building blocks in electronics.\n\nThis matters because dividers appear everywhere: setting reference voltages, scaling a signal down so a microcontroller can safely read it, biasing transistors, and reading sensors like thermistors and light-dependent resistors. Picking the wrong resistor values wastes power or loads the circuit too heavily, so a voltage divider calculator lets you check both the output voltage and the current draw before soldering anything.\n\nThe formula works because both resistors carry the same series current, so the supply voltage splits between them in proportion to their resistances. The output across the lower resistor is simply the input scaled by that resistor's share of the total. Hobbyists, electronics students, and hardware engineers rely on a voltage divider calculator to design reference levels and sensor front-ends with confidence rather than guesswork.",
    example: { inputs: { vin: 12, r1: 1000, r2: 2000 }, explanation: "12 × 2000 ÷ (1000 + 2000) = 12 × 2000 ÷ 3000 = 8 V, with a series current of 12 ÷ 3000 = 0.004 A." },
    faqs: [
      {
        question: "How does a voltage divider work?",
        answer: "Two resistors are placed in series across the input voltage, and the output is taken from the point between them. Because the same current flows through both, the input voltage splits across them in proportion to their resistances. The output equals the input multiplied by the lower resistor divided by the sum of both resistors, giving a stable fraction of the supply set entirely by the resistor ratio.",
      },
      {
        question: "Does connecting a load change the output voltage?",
        answer: "Yes. Attaching a load across the output places its resistance in parallel with R2, which lowers the effective bottom resistance and pulls the output voltage down. To keep the divider accurate, the load resistance should be much larger than R2, or you should account for it in the calculation. This loading effect is the main limitation of a simple resistive divider used as a voltage reference.",
      },
      {
        question: "How much current does a voltage divider draw?",
        answer: "The series current equals the input voltage divided by the sum of the two resistors. Larger resistor values reduce this current and save power, which matters in battery-powered devices, but they also make the divider more sensitive to loading and noise. Smaller resistors give a stiffer, more accurate output at the cost of higher continuous current. Balancing these two concerns is the core design trade-off.",
      },
      {
        question: "What are common uses for a voltage divider?",
        answer: "Voltage dividers set reference voltages, scale high signals down to safe levels for analog-to-digital converters, bias transistor stages, and form half of sensor circuits with thermistors, photoresistors, or potentiometers. They are simple, cheap, and require only two components. For any job needing a fixed fraction of a supply voltage with little current, a resistive divider is usually the first tool an engineer reaches for.",
      },
      {
        question: "Can a voltage divider supply power to a circuit?",
        answer: "Not effectively. A resistive divider is meant to set a reference voltage, not to deliver meaningful current. As soon as a real load draws current, the output sags and the divider wastes power as heat in the resistors. To power a circuit at a lower voltage, use a regulator or a buck converter instead, which hold the output steady under load far more efficiently.",
      },
    ],
    relatedCalculators: ["spring-constant-calculator", "motor-power-calculator", "reynolds-number-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard electrical engineering",
  },
  {
    id: "spring-constant",
    slug: "spring-constant-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Spring Constant Calculator",
    shortDescription: "Find spring stiffness and stored energy.",
    seoTitle: "Spring Constant Calculator — Hooke's Law Stiffness and Energy",
    metaDescription: "Free spring constant calculator using Hooke's law. Enter force and displacement to find the spring constant in N/m and the elastic potential energy stored.",
    primaryKeyword: "spring constant calculator",
    secondaryKeywords: ["hookes law calculator", "spring stiffness calculator", "elastic potential energy calculator"],
    fields: [
      { id: "force", label: "Applied force", type: "number", unit: "N", required: true, span: 1 },
      { id: "displacement", label: "Displacement", type: "number", unit: "m", required: true, span: 1, helpText: "How far the spring stretches or compresses." },
    ],
    results: [
      { id: "springConstant", label: "Spring constant", format: "number", decimals: 3, unit: "N/m", isPrimary: true },
      { id: "energy", label: "Stored energy", format: "number", decimals: 4, unit: "J", isPrimary: false },
    ],
    formula: "k = force ÷ displacement",
    formulaExplanation: "Hooke's law states that the force a spring exerts is proportional to how far it is stretched or compressed, so dividing force by displacement gives the constant of proportionality k, the stiffness. The stored elastic energy is one-half k times displacement squared, because the force builds up linearly from zero as the spring deforms, and energy is the area under that force-versus-distance line.",
    explanation: "The spring constant measures how stiff a spring is, and this spring constant calculator finds it from the force applied and the resulting displacement, then reports the elastic potential energy the spring stores. A high spring constant means a stiff spring that needs a large force to stretch even a little, while a low constant describes a soft, easily deformed spring. The value is expressed in newtons per metre.\n\nThis property matters across mechanical and structural design: vehicle suspensions, mattress support, retractable pens, door mechanisms, weighing scales, and vibration isolators all depend on choosing the right stiffness. Too stiff and the ride is harsh; too soft and the spring bottoms out. A spring constant calculator lets you confirm the stiffness from a simple force-and-stretch measurement instead of guessing.\n\nThe formula works because Hooke's law says the restoring force of a spring grows in direct proportion to its displacement, so the ratio of force to stretch is a fixed constant for that spring. The stored energy follows as one-half the constant times displacement squared, the area under the force-distance graph. Engineers, product designers, and physics students use a spring constant calculator to size springs and predict how much energy they will hold.",
    example: { inputs: { force: 20, displacement: 0.1 }, explanation: "20 N ÷ 0.1 m = 200 N/m, storing ½ × 200 × 0.1² = 1 J of elastic energy." },
    faqs: [
      {
        question: "What is the spring constant?",
        answer: "The spring constant, written k, measures a spring's stiffness. It equals the force needed to stretch or compress the spring divided by how far it moves, and is expressed in newtons per metre. A large value means a stiff spring that resists deformation strongly, while a small value means a soft, flexible spring. It is a fixed property of each spring, set by its material, coil diameter, wire thickness, and number of turns.",
      },
      {
        question: "What is Hooke's law?",
        answer: "Hooke's law states that the force a spring exerts is directly proportional to its displacement from the resting position, as long as the spring is not stretched too far. Written F equals k times x, it means doubling the stretch doubles the force. The law holds within the elastic limit; beyond that point the spring deforms permanently and the simple linear relationship no longer describes its behaviour.",
      },
      {
        question: "How is the stored energy calculated?",
        answer: "Elastic potential energy equals one-half the spring constant multiplied by the displacement squared. Because the restoring force rises linearly from zero as the spring deforms, the energy is the triangular area under the force-versus-distance line. This is why stretching a spring twice as far stores four times the energy. That stored energy is released when the spring returns to its natural length.",
      },
      {
        question: "What are the units of the spring constant?",
        answer: "The spring constant is measured in newtons per metre in SI units, meaning the number of newtons of force required to stretch the spring by one metre. In imperial work you may see pounds per inch instead. To keep this calculator accurate, enter force in newtons and displacement in metres. A displacement given in centimetres should be divided by 100 before entering it.",
      },
      {
        question: "Does Hooke's law work for every spring?",
        answer: "Hooke's law applies only within a spring's elastic range, where deformation is reversible and proportional to force. Stretch a spring beyond its elastic limit and it deforms permanently, so force no longer rises linearly and the constant no longer applies. Real springs also have a maximum load. For accurate results, stay within the manufacturer's specified working range where the linear relationship reliably holds.",
      },
    ],
    relatedCalculators: ["stress-strain-calculator", "beam-deflection-calculator", "gear-ratio-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard physics (Hooke's law)",
  },
  {
    id: "stress-strain",
    slug: "stress-strain-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Stress Strain Calculator",
    shortDescription: "Find stress, strain and Young's modulus.",
    seoTitle: "Stress Strain Calculator — Stress, Strain and Young's Modulus",
    metaDescription: "Free stress strain calculator. Enter force, area, original length, and deformation to find stress in pascals, strain, and Young's modulus of a material.",
    primaryKeyword: "stress strain calculator",
    secondaryKeywords: ["youngs modulus calculator", "tensile stress calculator", "elastic modulus calculator"],
    fields: [
      { id: "force", label: "Applied force", type: "number", unit: "N", required: true, span: 1 },
      { id: "area", label: "Cross-sectional area", type: "number", unit: "m²", required: true, span: 1, min: 0 },
      { id: "originalLength", label: "Original length", type: "number", unit: "m", required: true, span: 1, min: 0 },
      { id: "deformation", label: "Deformation", type: "number", unit: "m", required: true, span: 1, helpText: "Change in length under load." },
    ],
    results: [
      { id: "stress", label: "Stress", format: "number", decimals: 2, unit: "Pa", isPrimary: true },
      { id: "strain", label: "Strain", format: "number", decimals: 6, isPrimary: false },
      { id: "modulus", label: "Young's modulus", format: "number", decimals: 2, unit: "Pa", isPrimary: false },
    ],
    formula: "stress = force ÷ area  ·  strain = deformation ÷ length",
    formulaExplanation: "Stress is force spread over the cross-sectional area, so dividing force by area gives the internal load each unit of material carries. Strain is the fractional change in length, deformation divided by original length, making it a dimensionless measure of how much the material stretched. Young's modulus is stress divided by strain, the stiffness of the material itself, because in the elastic region the two rise in direct proportion.",
    explanation: "Stress and strain describe how a material responds to a load, and this stress strain calculator returns both quantities plus Young's modulus from the force, area, length, and deformation you enter. Stress is the internal force per unit area the material carries, while strain is the fractional amount it stretches. Their ratio, Young's modulus, is a fingerprint of the material's stiffness that lets you predict how any part made from it will behave.\n\nThis matters throughout engineering: bridge cables, aircraft frames, bolts, machine shafts, and building columns must all carry loads without stretching too far or breaking. Comparing calculated stress against a material's known limits tells you whether a design is safe, and comparing strain against tolerances tells you whether it will fit and function. A stress strain calculator turns raw measurements into these decisive numbers quickly.\n\nThe formula works because stress divides force by the area resisting it, and strain divides the length change by the original length, giving a dimensionless deformation. In the elastic region, stress and strain rise together in proportion, so their ratio is the constant Young's modulus. Civil, mechanical, and materials engineers, along with students, rely on a stress strain calculator to check strength and stiffness before committing to a design.",
    example: { inputs: { force: 1000, area: 0.01, originalLength: 2, deformation: 0.001 }, explanation: "Stress = 1000 ÷ 0.01 = 100000 Pa, strain = 0.001 ÷ 2 = 0.0005, so Young's modulus = 100000 ÷ 0.0005 = 200000000 Pa." },
    faqs: [
      {
        question: "What is the difference between stress and strain?",
        answer: "Stress is the internal force per unit area within a loaded material, measured in pascals, and it describes how hard the material is being pushed or pulled. Strain is the resulting fractional change in length, a dimensionless number with no units. Stress is the cause and strain is the effect: apply stress to a material and it responds with strain. Their ratio reveals how stiff the material is.",
      },
      {
        question: "What is Young's modulus?",
        answer: "Young's modulus is the ratio of stress to strain within a material's elastic range, and it measures stiffness. A high modulus, like steel's roughly 200 gigapascals, means the material barely stretches under load. A low modulus, like rubber's, means it deforms easily. Because it is a property of the material itself, not the part's shape, it lets engineers compare candidate materials directly when strength and rigidity matter.",
      },
      {
        question: "What units does this calculator use?",
        answer: "Enter force in newtons, cross-sectional area in square metres, and both the original length and deformation in metres. Stress and Young's modulus then come out in pascals, and strain is dimensionless. Because pascals are small, real results are often large numbers; you may prefer to read them in megapascals or gigapascals by dividing by one million or one billion respectively for easier comparison with reference tables.",
      },
      {
        question: "What is the elastic limit?",
        answer: "The elastic limit is the maximum stress a material can take while still returning to its original shape once the load is removed. Below it, stress and strain stay proportional and Young's modulus applies. Beyond it, the material deforms permanently and eventually fractures. This calculator assumes elastic behaviour, so its Young's modulus result is only meaningful for loads that keep the material within that reversible range.",
      },
      {
        question: "Why does cross-sectional area matter for stress?",
        answer: "Stress is force divided by area, so a thicker part with more cross-sectional area spreads the same force over more material and experiences lower stress. This is why load-bearing components are made thicker where forces concentrate. Doubling the area halves the stress for a given load. Choosing the right area keeps stress safely below the material's limit, which is central to designing parts that will not fail.",
      },
    ],
    relatedCalculators: ["spring-constant-calculator", "beam-deflection-calculator", "gear-ratio-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard mechanical engineering",
  },
  {
    id: "motor-power",
    slug: "motor-power-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Motor Power Calculator",
    shortDescription: "Convert torque and RPM to horsepower and kW.",
    seoTitle: "Motor Power Calculator — Torque and RPM to HP and kW",
    metaDescription: "Free motor power calculator. Enter torque and rotational speed in RPM to find mechanical power output in horsepower and kilowatts instantly for any motor.",
    primaryKeyword: "motor power calculator",
    secondaryKeywords: ["torque to horsepower calculator", "hp calculator", "torque rpm power calculator"],
    fields: [
      { id: "torque", label: "Torque", type: "number", unit: "lb·ft", required: true, span: 1, helpText: "Shaft torque in pound-feet." },
      { id: "rpm", label: "Rotational speed", type: "number", unit: "rpm", required: true, span: 1 },
    ],
    results: [
      { id: "hp", label: "Power", format: "number", decimals: 2, unit: "hp", isPrimary: true },
      { id: "kw", label: "Power", format: "number", decimals: 3, unit: "kW", isPrimary: false },
    ],
    formula: "hp = torque × rpm ÷ 5252",
    formulaExplanation: "Mechanical power is torque times rotational speed. Using pound-feet and revolutions per minute, the constant 5252 converts the product into horsepower, because one horsepower is 33,000 pound-feet per minute and dividing that by two pi radians per revolution yields 5252. Multiplying the horsepower result by 0.7457 converts it to kilowatts, since one horsepower equals 745.7 watts by definition.",
    explanation: "Motor power tells you how much work a rotating machine can do each second, and this motor power calculator converts a torque and a rotational speed into power expressed in both horsepower and kilowatts. Torque is the twisting force on the shaft and RPM is how fast it spins; power combines the two, because a motor that produces high torque at high speed delivers more usable output than one that manages only one of those.\n\nThis matters when selecting or comparing motors and engines: fans, pumps, conveyors, vehicles, and machine tools are all specified by power because it sets how quickly they can move a load. Torque alone or speed alone can mislead, so a motor power calculator gives the single figure that captures true capability, letting you match a motor to the job without over- or under-sizing it.\n\nThe formula works because power equals torque multiplied by rotational speed, and the constant 5252 converts pound-feet and RPM into horsepower cleanly. Multiplying by 0.7457 then restates that figure in kilowatts for metric specifications. Automotive engineers, machine designers, and technicians rely on a motor power calculator to read across between torque curves and power ratings and to compare drives on equal terms.",
    example: { inputs: { torque: 100, rpm: 2000 }, explanation: "100 × 2000 ÷ 5252 ≈ 38.08 hp, which is about 38.08 × 0.7457 ≈ 28.40 kW." },
    faqs: [
      {
        question: "How is horsepower calculated from torque and RPM?",
        answer: "Horsepower equals torque in pound-feet multiplied by rotational speed in RPM, divided by the constant 5252. This constant arises because one horsepower is defined as 33,000 pound-feet of work per minute, and dividing by two pi converts the rotation into that unit. The formula shows that power depends on both how much twisting force a shaft produces and how fast it turns.",
      },
      {
        question: "Why is the constant 5252 used?",
        answer: "The number 5252 comes from the definition of horsepower as 33,000 pound-feet per minute divided by two pi radians in one revolution, which gives roughly 5252. It ties together the customary units of torque in pound-feet and speed in revolutions per minute. Because of this constant, torque and horsepower curves for any engine always cross at exactly 5252 RPM when plotted together.",
      },
      {
        question: "What is the difference between torque and power?",
        answer: "Torque is the instantaneous twisting force a shaft can apply, while power is the rate at which that force does work over time. A motor can have high torque but low power if it turns slowly, or high power from modest torque if it spins fast. Power, combining both, determines how quickly a load can be moved, which is why it is the headline rating for most machines.",
      },
      {
        question: "How do I convert horsepower to kilowatts?",
        answer: "Multiply horsepower by 0.7457 to get kilowatts, because one horsepower equals 745.7 watts by definition. This calculator performs the conversion automatically, showing both units side by side. Kilowatts are the standard metric unit for motor power and appear on most electric motor nameplates worldwide, while horsepower remains common for engines and equipment specified in the United States and older machinery.",
      },
      {
        question: "Does this work for electric motors and engines alike?",
        answer: "Yes. The relationship between torque, speed, and power is the same for any rotating shaft, whether driven by an electric motor, a petrol engine, or a turbine. As long as you supply the shaft torque in pound-feet and the speed in RPM, the calculated power applies. Note that electric motors often quote a continuous rating, while engines quote a peak figure at a specific speed.",
      },
    ],
    relatedCalculators: ["gear-ratio-calculator", "spring-constant-calculator", "stress-strain-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard mechanical engineering",
  },
  {
    id: "beam-deflection",
    slug: "beam-deflection-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Beam Deflection Calculator",
    shortDescription: "Find deflection of a uniformly loaded beam.",
    seoTitle: "Beam Deflection Calculator — Simply Supported Uniform Load",
    metaDescription: "Free beam deflection calculator for a simply supported beam under uniform load. Enter load, span, modulus, and moment of inertia to find maximum deflection.",
    primaryKeyword: "beam deflection calculator",
    secondaryKeywords: ["simply supported beam calculator", "beam deflection formula", "structural deflection calculator"],
    fields: [
      { id: "load", label: "Uniform load", type: "number", unit: "N/m", required: true, span: 1, helpText: "Distributed load per unit length." },
      { id: "length", label: "Beam span", type: "number", unit: "m", required: true, span: 1, min: 0 },
      { id: "modulus", label: "Young's modulus", type: "number", unit: "Pa", required: true, span: 1, min: 0 },
      { id: "inertia", label: "Moment of inertia", type: "number", unit: "m⁴", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "deflection", label: "Maximum deflection", format: "number", decimals: 6, unit: "m", isPrimary: true },
    ],
    formula: "δ = 5 × load × length⁴ ÷ (384 × modulus × inertia)",
    formulaExplanation: "For a simply supported beam carrying a uniform load, the maximum deflection at mid-span is five times the load times span to the fourth power, divided by 384 times the modulus times the moment of inertia. Span appears to the fourth power because deflection accumulates along the length and the bending it causes compounds. Stiffer materials and larger cross-sections, captured by modulus and inertia, resist that bending proportionally.",
    explanation: "Beam deflection is how far a loaded beam sags from its straight position, and this beam deflection calculator finds the maximum deflection of a simply supported beam carrying an evenly distributed load. It uses the load per unit length, the span, the material's Young's modulus, and the cross-section's moment of inertia to return the mid-span sag in metres, the point where a uniformly loaded beam bends the most.\n\nThis matters because floors, bridges, shelves, and machine frames must not sag beyond acceptable limits even when they are strong enough not to break. Excessive deflection cracks finishes, causes bouncy floors, and misaligns machinery, so building codes cap it as a fraction of the span. A beam deflection calculator lets you check a design against those limits before choosing a beam size or material.\n\nThe formula works because deflection grows with the fourth power of the span, so length dominates the result, while a stiffer material and a deeper cross-section resist bending through the modulus and the moment of inertia in the denominator. This is why doubling a beam's span increases sag sixteenfold. Structural and mechanical engineers and students use a beam deflection calculator to size beams that stay comfortably within serviceability limits.",
    example: { inputs: { load: 1000, length: 4, modulus: 200000000000, inertia: 0.0001 }, explanation: "δ = 5 × 1000 × 4⁴ ÷ (384 × 200000000000 × 0.0001) = 1280000 ÷ 7680000 ≈ 0.0001667 m." },
    faqs: [
      {
        question: "What type of beam does this calculator model?",
        answer: "It models a simply supported beam, one resting on a support at each end, carrying a uniformly distributed load across its full length. This is one of the most common cases in structural work, covering floor joists, shelf spans, and simple bridge decks. The maximum deflection occurs at mid-span. Different support conditions, such as a cantilever or fixed ends, use different formulas and would give different results.",
      },
      {
        question: "Why does span have such a large effect on deflection?",
        answer: "Span appears to the fourth power in the deflection formula, so it dominates the result. Doubling the length of a beam while keeping everything else the same increases its deflection by a factor of sixteen. This strong dependence is why long spans need much deeper or stiffer beams, and why adding an intermediate support to shorten the effective span reduces sag so dramatically in practice.",
      },
      {
        question: "What is the moment of inertia?",
        answer: "The moment of inertia, or second moment of area, measures how a cross-section's material is distributed relative to the bending axis. Placing material farther from the neutral axis, as in an I-beam, sharply increases it and resists bending far more efficiently than a solid bar of the same weight. A larger moment of inertia means less deflection, which is why structural shapes are engineered to maximise it.",
      },
      {
        question: "What units should I use?",
        answer: "Enter the distributed load in newtons per metre, the span in metres, Young's modulus in pascals, and the moment of inertia in metres to the fourth power. The deflection then comes out in metres. Because structural deflections are small, the result is often a fraction of a millimetre; multiply by 1000 to read it in millimetres, the unit most commonly used when checking against code limits.",
      },
      {
        question: "How much deflection is acceptable?",
        answer: "Building codes usually limit deflection to a fraction of the span, commonly the span divided by 250 or 360 depending on the element and finish. A beam can be strong enough to avoid breaking yet still sag too much for comfort or to protect brittle finishes like plaster. Always compare the calculated deflection against the relevant serviceability limit for your application rather than strength alone.",
      },
    ],
    relatedCalculators: ["stress-strain-calculator", "spring-constant-calculator", "motor-power-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard mechanical engineering",
  },
  {
    id: "reynolds-number",
    slug: "reynolds-number-calculator",
    category: "Engineering",
    categorySlug: "engineering",
    title: "Reynolds Number Calculator",
    shortDescription: "Find Reynolds number and flow regime.",
    seoTitle: "Reynolds Number Calculator — Laminar or Turbulent Flow",
    metaDescription: "Free Reynolds number calculator. Enter fluid density, velocity, characteristic length, and viscosity to find the Reynolds number and whether flow is laminar or turbulent.",
    primaryKeyword: "reynolds number calculator",
    secondaryKeywords: ["laminar turbulent flow calculator", "fluid flow regime calculator", "reynolds number formula"],
    fields: [
      { id: "density", label: "Fluid density", type: "number", unit: "kg/m³", required: true, span: 1, min: 0 },
      { id: "velocity", label: "Flow velocity", type: "number", unit: "m/s", required: true, span: 1 },
      { id: "length", label: "Characteristic length", type: "number", unit: "m", required: true, span: 1, min: 0, helpText: "Pipe diameter or plate length." },
      { id: "viscosity", label: "Dynamic viscosity", type: "number", unit: "Pa·s", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "reynolds", label: "Reynolds number", format: "number", decimals: 2, isPrimary: true },
      { id: "regime", label: "Flow regime", format: "text", isPrimary: false },
    ],
    formula: "Re = density × velocity × length ÷ viscosity",
    formulaExplanation: "The Reynolds number is the ratio of inertial forces to viscous forces in a flowing fluid, formed by multiplying density, velocity, and a characteristic length and dividing by dynamic viscosity. When inertia dominates, the number is large and flow becomes turbulent; when viscosity dominates, the number is small and flow stays smooth and laminar. Being a ratio of forces, the Reynolds number is dimensionless.",
    explanation: "The Reynolds number predicts whether a fluid will flow smoothly or chaotically, and this Reynolds number calculator computes it from the fluid's density, velocity, a characteristic length, and its dynamic viscosity, then classifies the flow as laminar, transitional, or turbulent. It is a single dimensionless number that captures the balance between the fluid's tendency to keep moving and its internal friction, which together decide the character of the flow.\n\nThis matters throughout fluid engineering: pipe design, pump selection, aircraft and car aerodynamics, heat exchangers, and chemical mixing all depend on knowing the flow regime. Laminar flow is orderly and predictable with low drag, while turbulent flow mixes strongly but resists motion more. A Reynolds number calculator tells you which regime applies so you can choose the right equations, correlations, and safety margins for a design.\n\nThe formula works because the Reynolds number is the ratio of inertial forces, represented by density times velocity times length, to viscous forces represented by viscosity. Below about 2300 the viscous forces keep flow laminar; above roughly 4000 inertia makes it turbulent, with a transitional band between. Mechanical, chemical, and aerospace engineers along with students use a Reynolds number calculator to characterise flow before sizing pipes and analysing drag.",
    example: { inputs: { density: 1000, velocity: 2, length: 0.1, viscosity: 0.001 }, explanation: "Re = 1000 × 2 × 0.1 ÷ 0.001 = 200 ÷ 0.001 = 200000, which is well above 4000, so the flow is turbulent." },
    faqs: [
      {
        question: "What does the Reynolds number tell you?",
        answer: "The Reynolds number indicates whether a fluid flow will be laminar, smooth and orderly, or turbulent, chaotic and mixing. It is the ratio of inertial forces to viscous forces in the fluid. A low value means viscosity keeps the flow smooth, while a high value means inertia overwhelms viscosity and the flow breaks into eddies. This single number guides which physics and design equations apply to a given situation.",
      },
      {
        question: "What are the laminar and turbulent thresholds?",
        answer: "For flow in a pipe, a Reynolds number below about 2300 is generally laminar, above about 4000 is turbulent, and the range between is transitional, where the flow can switch unpredictably between the two states. These thresholds are approximate and depend on geometry and surface roughness, but they provide the standard rule of thumb engineers use to classify pipe flow and select appropriate design correlations.",
      },
      {
        question: "What is the characteristic length?",
        answer: "The characteristic length is a representative dimension of the flow geometry. For flow inside a circular pipe it is the pipe's inside diameter; for flow over a flat plate it is the length along the plate; for a sphere it is the diameter. Choosing the correct characteristic length matters because the Reynolds number, and therefore the predicted regime, changes directly with the length value you enter.",
      },
      {
        question: "What units does this calculator use?",
        answer: "Enter density in kilograms per cubic metre, velocity in metres per second, characteristic length in metres, and dynamic viscosity in pascal-seconds. Because the Reynolds number is a ratio of forces, all the units cancel and the result is dimensionless, just a pure number. Using consistent SI units throughout is essential, since mixing units would produce a value that no longer corresponds to the standard flow-regime thresholds.",
      },
      {
        question: "Why does the flow regime matter in design?",
        answer: "The flow regime determines pressure drop, heat transfer, mixing, and drag, all of which drive engineering decisions. Laminar flow has lower friction losses and predictable behaviour, while turbulent flow enhances mixing and heat transfer but demands more pumping power. Knowing the Reynolds number lets you pick the right friction and heat-transfer correlations, size pumps correctly, and anticipate whether a system will run efficiently or waste energy fighting turbulence.",
      },
    ],
    relatedCalculators: ["motor-power-calculator", "beam-deflection-calculator", "voltage-divider-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard fluid mechanics (Reynolds number)",
  },
];
