import type { CalculatorDefinition } from "../types";

export const environmentWave3Calculators: CalculatorDefinition[] = [
  {
    id: "carbon-footprint",
    slug: "carbon-footprint-calculator",
    category: "Environment",
    categorySlug: "environment",
    title: "Carbon Footprint Calculator",
    shortDescription: "Estimate yearly CO₂ from driving and home electricity.",
    seoTitle: "Carbon Footprint Calculator — Driving and Home Energy CO₂",
    metaDescription: "Free carbon footprint calculator. Enter your annual miles, fuel economy, and monthly electricity use to estimate yearly CO₂ emissions in metric tons from driving and home energy.",
    primaryKeyword: "carbon footprint calculator",
    secondaryKeywords: ["co2 emissions calculator", "household carbon calculator", "personal carbon footprint"],
    fields: [
      { id: "annualMiles", label: "Annual miles driven", type: "number", unit: "mi", required: true, span: 1, min: 0 },
      { id: "mpg", label: "Fuel economy", type: "number", unit: "mpg", required: true, span: 1, min: 0 },
      { id: "monthlyKwh", label: "Monthly electricity use", type: "number", unit: "kWh", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "totalTons", label: "Total footprint", format: "number", decimals: 2, unit: "t CO₂/yr", isPrimary: true },
      { id: "carTons", label: "From driving", format: "number", decimals: 2, unit: "t CO₂/yr", isPrimary: false },
      { id: "homeTons", label: "From home energy", format: "number", decimals: 2, unit: "t CO₂/yr", isPrimary: false },
    ],
    formula: "CO₂ = (miles ÷ mpg × 8.887) + (kWh × 12 × 0.417), in kg ÷ 1000",
    formulaExplanation: "Each gallon of gasoline burned releases about 8.887 kilograms of carbon dioxide, so dividing your annual miles by fuel economy gives gallons, which multiplied by that factor gives driving emissions. Home electricity uses a grid factor of roughly 0.417 kilograms of CO₂ per kilowatt-hour, applied to twelve months of usage. Summing both and dividing by 1,000 converts kilograms into the metric tons commonly quoted.",
    explanation: "A carbon footprint measures the greenhouse gases your activities release, expressed as an equivalent weight of carbon dioxide. This carbon footprint calculator focuses on two of the largest household sources — the car you drive and the electricity your home consumes — and reports your yearly emissions in metric tons of CO₂, split so you can see which source dominates.\n\nDriving emissions come from burning fuel: the fewer miles you cover and the more efficient your vehicle, the less carbon you produce. Home emissions depend on how much grid electricity you use and how clean that grid is. Because both are scaled by published emission factors, the result is a realistic estimate rather than a rough guess, giving you a baseline to act on.\n\nKnowing your footprint matters because it turns an abstract climate concern into concrete numbers you can influence. Switching to a more efficient car, driving less, improving home insulation, or moving to renewable electricity each shifts the figure measurably. Individuals tracking sustainability goals, families comparing lifestyle changes, and students learning about emissions all use a carbon footprint calculator to understand impact and target the changes that cut the most carbon for the least effort in daily life.",
    example: { inputs: { annualMiles: 12000, mpg: 25, monthlyKwh: 900 }, explanation: "12,000 ÷ 25 × 8.887 ÷ 1000 ≈ 4.27 t from driving, plus 900 × 12 × 0.417 ÷ 1000 ≈ 4.50 t from home energy, for about 8.77 t CO₂ per year." },
    faqs: [
      {
        question: "What emission factors does this calculator use?",
        answer: "It uses U.S. EPA equivalency factors: about 8.887 kilograms of CO₂ per gallon of gasoline burned, and roughly 0.417 kilograms of CO₂ per kilowatt-hour of grid electricity. These are national averages, so your true figures vary with fuel type and how clean your local grid is. Regions with heavy renewable or nuclear generation emit far less per kilowatt-hour than coal-dependent grids, so treat the result as a solid estimate.",
      },
      {
        question: "Why is my result split into driving and home energy?",
        answer: "Separating the two sources shows you where your emissions actually come from, which is the first step to cutting them. If driving dominates, carpooling, a more efficient vehicle, or fewer trips will help most. If home energy is larger, insulation, efficient appliances, or renewable electricity make the biggest difference. Seeing both figures side by side lets you prioritise the change that reduces the most carbon for your effort.",
      },
      {
        question: "Does this include my whole carbon footprint?",
        answer: "No. This calculator covers personal driving and home electricity, two major household sources, but a complete footprint also includes flights, natural gas heating, food, goods, and public services. To capture more, add a flight emissions estimate and account for any gas or oil you burn directly. Use this figure as a strong core estimate and layer other categories on top for a fuller picture of your total impact.",
      },
      {
        question: "How can I lower the number this shows?",
        answer: "The driving portion falls when you drive fewer miles or switch to a vehicle with higher fuel economy or an electric drivetrain charged on clean power. The home portion drops when you reduce electricity use through efficient lighting and appliances, better insulation, or by sourcing renewable electricity. Even modest changes, such as trimming a few thousand miles a year, move the tonnage down in a way you can measure here.",
      },
      {
        question: "Are electric vehicles counted as zero emissions?",
        answer: "Not exactly. An electric vehicle produces no tailpipe emissions, so its driving figure here would be near zero if you enter it as such, but the electricity it uses still shows up in your home energy total if you charge at home. The cleanliness of your grid then determines its real footprint. On a renewable-heavy grid an EV is very low carbon; on a coal grid it is cleaner than petrol but not zero.",
      },
    ],
    relatedCalculators: ["flight-emissions-calculator", "home-energy-cost-calculator", "ev-charging-cost-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "U.S. EPA greenhouse gas equivalencies",
    sourceUrl: "https://www.epa.gov/energy/greenhouse-gas-equivalencies-calculator",
  },
  {
    id: "solar-savings",
    slug: "solar-savings-calculator",
    category: "Environment",
    categorySlug: "environment",
    title: "Solar Savings Calculator",
    shortDescription: "Estimate annual and lifetime savings from solar panels.",
    seoTitle: "Solar Savings Calculator — Annual and 25-Year Panel Savings",
    metaDescription: "Free solar savings calculator. Enter your system size, daily sun hours, and electricity rate to estimate annual energy production, yearly bill savings, and 25-year lifetime savings.",
    primaryKeyword: "solar savings calculator",
    secondaryKeywords: ["solar panel savings calculator", "solar energy savings", "solar payback calculator"],
    fields: [
      { id: "systemSizeKw", label: "System size", type: "number", unit: "kW", required: true, span: 1, min: 0 },
      { id: "sunHours", label: "Daily peak sun hours", type: "number", unit: "h", required: true, span: 1, min: 0, step: 0.1 },
      { id: "electricityRate", label: "Electricity rate", type: "number", unit: "$/kWh", required: true, span: 2, min: 0, step: 0.01 },
    ],
    results: [
      { id: "annualSavings", label: "Annual savings", format: "currency", decimals: 2, isPrimary: true },
      { id: "annualKwh", label: "Annual production", format: "number", decimals: 0, unit: "kWh", isPrimary: false },
      { id: "twentyFiveYear", label: "25-year savings", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "annual kWh = size × sun hours × 365  ·  savings = kWh × rate",
    formulaExplanation: "A solar array's output equals its rated size in kilowatts multiplied by the number of peak sun hours it receives each day, since peak sun hours already fold in intensity. Multiplying by 365 scales that daily energy to a full year of kilowatt-hours. Each of those kilowatt-hours displaces grid power you would otherwise buy, so multiplying annual production by your electricity rate gives the yearly dollar saving, and 25 years reflects a typical panel warranty life.",
    explanation: "Solar panels save money by generating electricity you would otherwise buy from the grid, and this solar savings calculator turns three simple inputs into an estimate of how much you could keep. Enter your planned system size, the peak sun hours your location averages, and your electricity rate, and it returns annual energy production, yearly bill savings, and a 25-year lifetime total.\n\nThe logic is straightforward: a larger array in a sunnier location produces more kilowatt-hours, and every kilowatt-hour you generate offsets one you no longer purchase. The higher your electricity rate, the more each generated unit is worth, which is why solar pays back fastest where power is expensive and sunshine is plentiful.\n\nSeeing a 25-year figure matters because solar is a long-term investment; panels typically carry warranties around that length, so lifetime savings tell you whether the upfront cost is worthwhile. Homeowners weighing an installation, renters exploring community solar, and students studying renewable economics all use a solar savings calculator to gauge returns before committing. Remember the estimate assumes steady rates and output; real savings shift with rate inflation, panel degradation, and shading, but this gives a clear, defensible baseline for planning.",
    example: { inputs: { systemSizeKw: 5, sunHours: 5, electricityRate: 0.15 }, explanation: "5 kW × 5 h × 365 = 9,125 kWh a year; at $0.15/kWh that saves $1,368.75 annually and about $34,218.75 over 25 years." },
    faqs: [
      {
        question: "What are peak sun hours and how do I find mine?",
        answer: "Peak sun hours are the equivalent number of hours per day that sunlight hits full strength of 1,000 watts per square metre, bundling a whole day's variable light into one figure. Most of the United States averages between four and six, while sunnier regions reach higher. Solar irradiance maps and installer tools list local values, so enter your area's yearly average for a realistic production estimate here.",
      },
      {
        question: "Does this calculator account for panel degradation?",
        answer: "No, this estimate assumes constant output across all 25 years for simplicity. In reality panels lose roughly half a percent of capacity per year, so late-life production is somewhat lower than year one. It also assumes your electricity rate stays fixed, whereas rates usually rise over time, which pushes savings up. These two effects partly cancel, so the flat estimate remains a reasonable middle-ground figure for planning.",
      },
      {
        question: "Why does a higher electricity rate increase savings?",
        answer: "Solar savings come from avoiding grid purchases, so each kilowatt-hour you generate is worth exactly what you would have paid for it. When your rate is high, every self-generated unit displaces a more expensive purchase, making the same array save more money. This is why solar economics look strongest in regions with costly electricity, and why rising utility prices steadily improve the return on an existing installation over its life.",
      },
      {
        question: "Does this include installation cost or payback time?",
        answer: "No. This tool estimates the savings side only — how much electricity value your panels produce — not the upfront purchase and installation price. To find payback time, divide your net system cost after any incentives by the annual savings shown here. If a system costs $12,000 net and saves about $1,369 a year, payback lands near nine years, after which the remaining savings are effectively free energy.",
      },
      {
        question: "Will I really produce this exact amount of energy?",
        answer: "Actual output varies with shading, panel orientation, roof tilt, temperature, dust, and inverter efficiency, so treat this as a well-grounded estimate rather than a guarantee. South-facing, unshaded arrays in your stated sun hours come closest. Snow, cloud, and soiling reduce output on given days, while cooler sunny weather can lift it. For a firm figure, a site-specific installer assessment refines these inputs to your exact roof.",
      },
    ],
    relatedCalculators: ["home-energy-cost-calculator", "carbon-footprint-calculator", "ev-charging-cost-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard energy calculation",
  },
  {
    id: "flight-emissions",
    slug: "flight-emissions-calculator",
    category: "Environment",
    categorySlug: "environment",
    title: "Flight Emissions Calculator",
    shortDescription: "Estimate CO₂ from a flight by distance and passengers.",
    seoTitle: "Flight Emissions Calculator — Air Travel CO₂ Footprint",
    metaDescription: "Free flight emissions calculator. Enter flight distance in kilometres and number of passengers to estimate the carbon dioxide produced by air travel in kilograms and metric tons.",
    primaryKeyword: "flight emissions calculator",
    secondaryKeywords: ["flight carbon calculator", "air travel co2 calculator", "airplane emissions calculator"],
    fields: [
      { id: "distanceKm", label: "Flight distance", type: "number", unit: "km", required: true, span: 1, min: 0 },
      { id: "passengers", label: "Passengers", type: "number", unit: "people", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "co2Kg", label: "CO₂ emitted", format: "number", decimals: 1, unit: "kg", isPrimary: true },
      { id: "co2Tons", label: "In metric tons", format: "number", decimals: 3, unit: "t CO₂", isPrimary: false },
    ],
    formula: "CO₂ (kg) = distance km × 0.115 × passengers",
    formulaExplanation: "Aircraft burn fuel roughly in proportion to distance flown, and averaged across seat classes and load factors a passenger accounts for about 0.115 kilograms of CO₂ for every kilometre travelled. Multiplying flight distance by that factor gives one traveller's emissions, and multiplying again by the number of passengers scales it to a whole party. Dividing the kilogram figure by 1,000 converts it into the metric tons used for annual carbon budgets.",
    explanation: "Air travel is one of the most carbon-intensive things an individual can do per hour, and this flight emissions calculator estimates the carbon dioxide a journey produces from just two inputs: the flight distance in kilometres and how many passengers are travelling. It reports the result in kilograms for a single trip and in metric tons so you can slot it into a yearly carbon budget.\n\nThe estimate uses a per-passenger-kilometre emission factor that averages the fuel burned across typical aircraft and occupancy. Because emissions scale directly with distance, long-haul flights dominate a traveller's footprint, while short hops add less. Multiplying by passenger count lets a family or group see their combined impact in one figure rather than per seat.\n\nUnderstanding flight emissions matters as more people track and offset their travel. Seeing that a single long-haul return trip can rival an entire year of driving reframes how significant flying is, helping travellers decide whether to fly less, choose direct routes that burn less fuel, or purchase credible offsets. Eco-conscious travellers, event planners weighing venue locations, and students studying transport emissions all use a flight emissions calculator to quantify an otherwise invisible cost and make more informed choices about how they move.",
    example: { inputs: { distanceKm: 1000, passengers: 2 }, explanation: "1,000 km × 0.115 × 2 passengers = 230 kg of CO₂, which is 0.230 metric tons." },
    faqs: [
      {
        question: "What emission factor does this calculator use?",
        answer: "It applies about 0.115 kilograms of CO₂ per passenger-kilometre, a common average drawn from environmental agency figures for typical commercial flights. This blends different aircraft, seat classes, and load factors into one representative number. Business and first-class seats occupy more space and therefore carry a larger share of the fuel, so premium travel exceeds this average, while a full economy cabin on an efficient jet can come in slightly below it.",
      },
      {
        question: "Does distance affect emissions per kilometre?",
        answer: "Yes, in practice. Take-off and climb burn disproportionately more fuel, so very short flights emit more per kilometre than long cruises where the aircraft spends most time in efficient level flight. This calculator uses a single average factor for simplicity, so it slightly understates short hops and slightly overstates some long-haul legs. For rough planning the average works well, but dedicated tools that model flight phases give finer detail.",
      },
      {
        question: "Should I count each leg of a round trip?",
        answer: "Yes. Enter the total distance you actually fly, which for a return journey is roughly double the one-way distance, plus any connecting legs. A traveller flying out and back covers both directions, so both must be included to reflect the true footprint. If you make multiple connections, add up every segment's distance, since each one burns fuel independently regardless of how briefly you stop between them.",
      },
      {
        question: "Does this include the extra warming from high-altitude emissions?",
        answer: "No. This estimate counts only the carbon dioxide from burning jet fuel. Aircraft also create contrails and emit other gases high in the atmosphere that add further warming, an effect often captured by a radiative forcing multiplier of roughly two to three. If you want a fuller climate impact, multiply the CO₂ figure here accordingly, keeping in mind that the multiplier is an area of active scientific refinement.",
      },
      {
        question: "How does flying compare to driving the same distance?",
        answer: "For a solo traveller, a long flight and a car trip of similar length can produce broadly comparable CO₂, but flights cover vastly greater distances in a day, so total trip emissions are usually far higher. A single intercontinental return flight can match or exceed an average car's entire year of emissions. Sharing a car spreads its footprint across passengers, whereas each air passenger already carries their allocated share.",
      },
    ],
    relatedCalculators: ["carbon-footprint-calculator", "ev-charging-cost-calculator", "home-energy-cost-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "U.S. EPA greenhouse gas equivalencies",
    sourceUrl: "https://www.epa.gov/energy/greenhouse-gas-equivalencies-calculator",
  },
  {
    id: "home-energy-cost",
    slug: "home-energy-cost-calculator",
    category: "Environment",
    categorySlug: "environment",
    title: "Home Energy Cost Calculator",
    shortDescription: "Find what an appliance costs to run per month and year.",
    seoTitle: "Home Energy Cost Calculator — Appliance Running Cost",
    metaDescription: "Free home energy cost calculator. Enter an appliance's wattage, daily hours of use, and your electricity rate to find its monthly kilowatt-hours, monthly cost, and annual running cost.",
    primaryKeyword: "home energy cost calculator",
    secondaryKeywords: ["appliance electricity cost calculator", "electricity usage calculator", "watts to cost calculator"],
    fields: [
      { id: "watts", label: "Appliance power", type: "number", unit: "W", required: true, span: 1, min: 0 },
      { id: "hoursPerDay", label: "Hours used per day", type: "number", unit: "h", required: true, span: 1, min: 0, step: 0.1 },
      { id: "rate", label: "Electricity rate", type: "number", unit: "$/kWh", required: true, span: 2, min: 0, step: 0.01 },
    ],
    results: [
      { id: "monthlyCost", label: "Monthly cost", format: "currency", decimals: 2, isPrimary: true },
      { id: "monthlyKwh", label: "Monthly usage", format: "number", decimals: 1, unit: "kWh", isPrimary: false },
      { id: "annualCost", label: "Annual cost", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "monthly kWh = watts × hours/day × 30 ÷ 1000  ·  cost = kWh × rate",
    formulaExplanation: "Electricity is billed by the kilowatt-hour, so an appliance's monthly energy equals its power in watts multiplied by daily running hours and by thirty days, then divided by 1,000 to convert watt-hours into kilowatt-hours. Multiplying that energy by your rate per kilowatt-hour gives the monthly cost, and multiplying the monthly cost by twelve produces the annual figure, showing the full-year expense of leaving a device running.",
    explanation: "Every appliance quietly adds to your electricity bill, and this home energy cost calculator shows exactly how much any single device costs to run. Enter its power draw in watts, how many hours a day you use it, and your electricity rate, and it returns the monthly kilowatt-hours consumed, the monthly cost, and the yearly total.\n\nThe calculation rests on how utilities bill you: not by watts but by kilowatt-hours, the energy used when a 1,000-watt device runs for an hour. A high-wattage appliance used briefly can cost less than a modest one left on all day, which is why both power and hours matter. Converting to a monthly and annual figure makes the running cost tangible rather than abstract.\n\nThis clarity helps you spot the expensive habits worth changing. An old refrigerator, a space heater, or a gaming PC left idle can quietly consume more than you expect, while efficient LED bulbs cost pennies. Households budgeting utilities, renters comparing appliances, and anyone chasing lower bills use a home energy cost calculator to decide what to unplug, replace, or run less. Pair the figures with an appliance's efficiency label and you can prioritise upgrades that pay for themselves through the electricity they save each year.",
    example: { inputs: { watts: 100, hoursPerDay: 5, rate: 0.15 }, explanation: "100 W × 5 h × 30 ÷ 1000 = 15 kWh a month; at $0.15/kWh that is $2.25 monthly and $27.00 per year." },
    faqs: [
      {
        question: "Where do I find an appliance's wattage?",
        answer: "Most appliances list their power draw on a label near the plug, on the back or base of the unit, or in the manual, usually marked in watts or as volts and amps that multiply to watts. Energy guides and manufacturer spec sheets also list it. For devices that cycle on and off, like refrigerators, use the average running wattage rather than the peak startup figure for a realistic estimate.",
      },
      {
        question: "Does this account for appliances that cycle on and off?",
        answer: "Not automatically. The calculator assumes the device draws its stated wattage for the hours you enter. For something like a fridge or air conditioner that runs intermittently, estimate the equivalent full-power hours instead — a fridge rated at 150 watts might only run its compressor eight hours a day even though it is plugged in continuously. Entering that effective run time gives a far more accurate monthly cost.",
      },
      {
        question: "Why is my bill higher than the sum of individual appliances?",
        answer: "This tool costs one appliance at a time, but your bill combines every device plus heating, cooling, standby power, and possible tiered or time-of-use rates. Many gadgets draw phantom power even when switched off, and peak-period pricing can exceed the flat rate you entered. Add up several appliances here and compare against your bill to find the gap, which often reveals always-on loads you had overlooked.",
      },
      {
        question: "How can I use this to cut my electricity costs?",
        answer: "Run the numbers for your biggest or longest-running devices first, since they dominate the bill. Compare the annual cost of an old appliance against an efficient replacement to see the payback on an upgrade. Reducing daily hours, switching to LED lighting, and eliminating standby draw all lower the figures shown here. Targeting the few high-cost items usually saves far more than fussing over minor low-wattage gadgets.",
      },
      {
        question: "Does a 30-day month affect accuracy?",
        answer: "The calculator uses a flat 30-day month for consistency, so months with 28 or 31 days differ slightly, and the annual figure is the monthly cost times twelve rather than a precise 365-day sum. These small rounding choices keep the math simple and the difference is negligible for budgeting. If you need exact billing-period figures, scale the daily cost — watts times hours times rate divided by 1,000 — by the actual number of days.",
      },
    ],
    relatedCalculators: ["solar-savings-calculator", "ev-charging-cost-calculator", "carbon-footprint-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard energy calculation",
  },
  {
    id: "ev-charging-cost",
    slug: "ev-charging-cost-calculator",
    category: "Environment",
    categorySlug: "environment",
    title: "EV Charging Cost Calculator",
    shortDescription: "Estimate the cost to charge an electric vehicle.",
    seoTitle: "EV Charging Cost Calculator — Electric Car Charge Price",
    metaDescription: "Free EV charging cost calculator. Enter your battery capacity, target charge percentage, and electricity rate to estimate the energy used and the cost of charging your electric vehicle.",
    primaryKeyword: "ev charging cost calculator",
    secondaryKeywords: ["electric car charging cost", "ev charge cost calculator", "cost to charge electric vehicle"],
    fields: [
      { id: "batteryKwh", label: "Battery capacity", type: "number", unit: "kWh", required: true, span: 1, min: 0 },
      { id: "chargePercent", label: "Charge added", type: "number", unit: "%", required: true, span: 1, min: 0, max: 100 },
      { id: "electricityRate", label: "Electricity rate", type: "number", unit: "$/kWh", required: true, span: 2, min: 0, step: 0.01 },
    ],
    results: [
      { id: "cost", label: "Charging cost", format: "currency", decimals: 2, isPrimary: true },
      { id: "kwhUsed", label: "Energy used", format: "number", decimals: 1, unit: "kWh", isPrimary: false },
    ],
    formula: "kWh used = battery kWh × (charge % ÷ 100)  ·  cost = kWh × rate",
    formulaExplanation: "The energy needed to charge equals the battery's capacity multiplied by the fraction of it you are filling, so an 80 percent charge draws four-fifths of the pack's rated kilowatt-hours. Multiplying that energy by your electricity rate per kilowatt-hour gives the cost. The calculation ignores charging losses, so real-world energy pulled from the wall runs a little higher than the battery-side figure shown here.",
    explanation: "Charging an electric vehicle is usually far cheaper than filling a fuel tank, and this EV charging cost calculator shows exactly what a charge costs at home. Enter your battery's capacity in kilowatt-hours, the percentage of charge you want to add, and your electricity rate, and it returns the energy drawn and the resulting cost.\n\nThe idea is simple: a battery's capacity tells you how much energy a full charge holds, so filling a portion of it draws that fraction of the total. Multiplying the energy by your rate gives the price. Because home electricity typically costs a fraction of petrol per mile driven, seeing the figure often reassures new EV owners that daily charging is inexpensive.\n\nThis matters for budgeting and for comparing charging options. A home top-up on an off-peak tariff can cost a fraction of a public rapid charger, and knowing the per-charge price helps you decide when and where to plug in. EV owners planning monthly costs, prospective buyers comparing running expenses against a petrol car, and fleet managers estimating charging budgets all rely on an EV charging cost calculator. Remember real energy from the wall is slightly higher than the battery figure because charging is not perfectly efficient, so treat the result as a close lower bound on the true cost.",
    example: { inputs: { batteryKwh: 60, chargePercent: 80, electricityRate: 0.15 }, explanation: "60 kWh × 80% = 48 kWh added; at $0.15/kWh that charge costs $7.20." },
    faqs: [
      {
        question: "Does this include charging losses?",
        answer: "No. The calculator measures energy delivered into the battery, but charging is not perfectly efficient — some power is lost as heat in the charger, cables, and battery, typically around 10 to 15 percent. That means the electricity actually pulled from the wall, and billed by your utility, is a little higher than the figure shown. To approximate real cost, add roughly 10 to 15 percent to the result for a home Level 2 charger.",
      },
      {
        question: "How do I find my car's battery capacity?",
        answer: "Battery capacity is listed in your vehicle's specifications, usually as a total or usable figure in kilowatt-hours. Manufacturer websites, the owner's manual, and the car's information display all report it. Note that usable capacity is slightly less than the nominal pack size because manufacturers reserve a buffer to protect battery health, so use the usable number if given for the most accurate charging cost estimate.",
      },
      {
        question: "Why charge to 80 percent instead of 100?",
        answer: "Many EV makers recommend routine charging to about 80 percent because the final stretch to full charges more slowly and, over time, adds stress that ages the battery faster. Charging to 80 percent daily and reserving 100 percent for long trips preserves battery health and cuts charging time. That is why the calculator lets you enter a target percentage rather than assuming a full charge every session.",
      },
      {
        question: "How does home charging compare to public fast charging?",
        answer: "Home electricity rates are usually far lower than public rapid-charger prices, which include convenience and speed premiums. A charge that costs a few dollars at home can cost several times more at a fast charger. Enter each rate into this calculator to compare directly. For most owners, charging overnight at home on a standard or off-peak tariff is by far the cheapest way to keep the car powered.",
      },
      {
        question: "Can I estimate cost per mile from this?",
        answer: "Yes. Divide the charging cost by the miles that charge adds. If 48 kilowatt-hours cost $7.20 and take you about 180 miles, that is roughly four cents per mile, typically well below the fuel cost of a comparable petrol car. Knowing your vehicle's efficiency in miles per kilowatt-hour lets you convert any charge here into a per-mile running cost for budgeting and comparison.",
      },
    ],
    relatedCalculators: ["home-energy-cost-calculator", "carbon-footprint-calculator", "solar-savings-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard energy calculation",
  },
  {
    id: "water-footprint",
    slug: "water-footprint-calculator",
    category: "Environment",
    categorySlug: "environment",
    title: "Water Footprint Calculator",
    shortDescription: "Estimate your shower water use per week and year.",
    seoTitle: "Water Footprint Calculator — Shower Water Use",
    metaDescription: "Free water footprint calculator. Enter your shower length, showers per week, and showerhead flow rate to estimate the water you use weekly and yearly in litres and gallons.",
    primaryKeyword: "water footprint calculator",
    secondaryKeywords: ["shower water usage calculator", "water usage calculator", "water consumption calculator"],
    fields: [
      { id: "showerMinutes", label: "Shower length", type: "number", unit: "min", required: true, span: 1, min: 0 },
      { id: "showersPerWeek", label: "Showers per week", type: "number", unit: "per week", required: true, span: 1, min: 0 },
      { id: "flowRate", label: "Showerhead flow rate", type: "number", unit: "L/min", required: true, span: 2, min: 0, step: 0.1 },
    ],
    results: [
      { id: "weeklyLitres", label: "Weekly water use", format: "number", decimals: 0, unit: "L", isPrimary: true },
      { id: "annualLitres", label: "Annual water use", format: "number", decimals: 0, unit: "L", isPrimary: false },
      { id: "annualGallons", label: "Annual in gallons", format: "number", decimals: 0, unit: "gal", isPrimary: false },
    ],
    formula: "weekly L = minutes × showers/week × flow rate; annual = weekly × 52",
    formulaExplanation: "A shower's water use equals how long it runs multiplied by the flow rate of the showerhead in litres per minute, giving litres per shower. Multiplying by how many showers you take each week gives weekly consumption, and multiplying that by 52 weeks scales it to a year. Dividing the annual litres by 3.785 converts the figure into US gallons for readers who measure water that way.",
    explanation: "Showers are one of the largest indoor uses of household water, and this water footprint calculator turns three habits into a clear picture of how much you use. Enter your typical shower length, how many showers you take each week, and your showerhead's flow rate, and it reports your weekly and yearly water use in both litres and gallons.\n\nThe math is direct: flow rate times minutes gives the water per shower, and repeating that across your weekly routine and then a full year reveals a total most people underestimate. A long daily shower through a high-flow head can consume tens of thousands of litres annually, while a shorter shower with an efficient head uses a fraction of that.\n\nSeeing the yearly figure makes conservation concrete. Trimming a few minutes, showering slightly less often, or fitting a low-flow head each cuts the total measurably, saving both water and the energy used to heat it. Households facing water restrictions, people on metered supplies wanting lower bills, and anyone reducing their environmental impact use a water footprint calculator to identify easy savings. Because heated shower water also carries an energy and carbon cost, the litres you save here ripple into lower utility bills and a smaller overall footprint across the year.",
    example: { inputs: { showerMinutes: 8, showersPerWeek: 7, flowRate: 9 }, explanation: "8 min × 7 showers × 9 L/min = 504 L a week, about 26,208 L (roughly 6,925 gallons) a year." },
    faqs: [
      {
        question: "What is a typical showerhead flow rate?",
        answer: "Standard showerheads flow around 9 to 12 litres per minute, while water-efficient or low-flow models deliver about 6 to 8 litres per minute. In the United States, federal rules cap new showerheads at 2.5 gallons, or roughly 9.5 litres, per minute. Check your showerhead's packaging or stamped rating, or measure it by timing how long it takes to fill a container of known volume for an accurate figure.",
      },
      {
        question: "How much water can a shorter shower save?",
        answer: "Because usage scales directly with time, every minute you trim saves your flow rate in litres per shower. At 9 litres per minute, cutting a daily shower from eight minutes to five saves 27 litres a day, nearly 10,000 litres a year. Reducing length is often the easiest lever because it needs no new equipment, and the saving compounds across every shower you take through the year.",
      },
      {
        question: "Does this include water used elsewhere in the home?",
        answer: "No. This calculator covers showers only, which are a major but not the sole indoor water use. Toilets, taps, laundry, dishwashing, and any garden or outdoor use add substantially more. To estimate your full household footprint, tally those separately and add them to the shower figure here. Showers are a sensible starting point because they are frequent, easy to measure, and quick to cut.",
      },
      {
        question: "Why does the calculator show both litres and gallons?",
        answer: "Different countries measure water differently: most of the world uses litres, while the United States commonly uses gallons. Showing both lets you compare your usage against local guidance, utility bills, or conservation targets regardless of which unit they use. The conversion applied is 3.785 litres per US gallon, so the gallon figure is simply the annual litres divided by that factor for direct comparison.",
      },
      {
        question: "Does shower water use also affect energy and cost?",
        answer: "Yes. Most shower water is heated, so cutting shower water also cuts the gas or electricity used to warm it, lowering both water and energy bills. Heating water is one of the largest energy uses in a typical home, meaning the litres saved here translate into real money and reduced carbon emissions. This is why efficient showering is one of the most cost-effective household conservation steps available.",
      },
    ],
    relatedCalculators: ["home-energy-cost-calculator", "carbon-footprint-calculator", "solar-savings-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard energy calculation",
  },
];
