import type { CalculatorDefinition } from "../types";

export const everydayWave2Calculators: CalculatorDefinition[] = [
  {
    id: "tip",
    slug: "tip-calculator",
    category: "Everyday Life",
    categorySlug: "everyday",
    title: "Tip Calculator",
    shortDescription: "Calculate the tip amount and total bill for any service. Split among multiple people too.",
    seoTitle: "Tip Calculator — Calculate Tip Amount & Split the Bill",
    metaDescription: "Calculate tip amount, total bill, and per-person share for any service. Supports custom tip percentages and splitting among multiple people.",
    primaryKeyword: "tip calculator",
    secondaryKeywords: ["how much to tip", "restaurant tip calculator", "gratuity calculator", "bill tip calculator"],
    slugEs: "calculadora-de-propinas",
    titleEs: "Calculadora de Propinas",
    shortDescriptionEs: "Calcula el importe de la propina y el total de la cuenta para cualquier servicio. También divide el gasto entre varias personas.",
    seoTitleEs: "Calculadora de Propinas — Calcula la Propina y Divide la Cuenta",
    metaDescriptionEs: "Calcula el importe de la propina, el total de la cuenta y la parte por persona para cualquier servicio. Admite porcentajes personalizados y división entre varias personas.",
    primaryKeywordEs: "calculadora de propinas",
    secondaryKeywordsEs: ["cuánto dejar de propina", "calculadora de propina de restaurante", "calculadora de gratificación"],
    formulaExplanationEs: "Multiplicar la cuenta por el porcentaje de propina dividido entre 100 convierte una tasa en una cifra en dólares, de modo que la gratificación siempre escala con el tamaño de la cuenta: un porcentaje fijo se siente justo tanto si la cuenta es pequeña como grande. Sumar esa propina a la cuenta original da el importe realmente adeudado, y dividir ese total entre el número de comensales reparte de forma equitativa tanto la comida como la propina entre todo el grupo.",
    explanationEs: "Una calculadora de propinas elimina la incertidumbre de la gratificación al calcular al instante el importe de la propina, el nuevo total y la parte de cada persona en cuanto introduces una cuenta y un porcentaje. La propina importa porque en Estados Unidos las gratificaciones forman una gran parte de los ingresos de los trabajadores del servicio, y sin embargo el cálculo mental es fácil de equivocar al final de una comida cuando todos están listos para marcharse. Hacerlo bien significa una paga justa por un buen servicio y evitar dejar una propina insuficiente por accidente.\n\nEl método es aritmética de porcentajes sencilla: la propina es una parte de la cuenta, que se añade encima para producir el total, y luego se divide equitativamente entre los comensales. Esta calculadora aplica las normas habituales de EE. UU. como punto de partida: aproximadamente del 15 al 20 por ciento en restaurantes con servicio de mesa, más por un servicio excepcional y menos donde hay servicio de mostrador. Como por convención se calcula sobre el importe antes de impuestos, aunque calcular sobre el total con impuestos también se acepta ampliamente, mantienes coherencia siempre.\n\nComensales, grupos que dividen una cuenta, clientes de reparto a domicilio y viajeros que consultan la costumbre local recurren a una calculadora de propinas para saldar cuentas de forma rápida y justa.",
    exampleEs: {
      inputs: { billAmount: "80", tipPercent: "20", numPeople: "4" },
      explanation: "Cuenta: 80 $. Propina (20%): 16 $. Total: 96 $. Dividido entre 4: 24 $ por persona.",
    },
    faqsEs: [
      {
        question: "¿Cuánto debo dejar de propina en un restaurante?",
        answer: "La propina habitual en restaurantes de EE. UU. es del 15 al 20% de la cuenta antes de impuestos en establecimientos con servicio de mesa. El quince por ciento se considera aceptable para un servicio adecuado; del 18 al 20% es lo normal para un buen servicio; el 25% o más muestra aprecio por un servicio excelente. Ante un mal servicio, habla con un encargado en lugar de no dejar nada, pues el camarero puede no ser responsable de las demoras de cocina. En muchos otros países la propina es mínima o no es costumbre.",
      },
      {
        question: "¿Debo calcular la propina antes o después de impuestos?",
        answer: "Tradicionalmente, las propinas se calculan sobre el importe de la cuenta antes de impuestos. En la práctica, la mayoría usa el total de la cuenta por comodidad, y la diferencia suele ser pequeña. En una cuenta de 100 $ antes de impuestos con un 8% de impuesto sobre ventas (108 $ en total), una propina del 20% es 20 $ sobre el importe previo o 21,60 $ sobre el total con impuestos: una diferencia de 1,60 $. Ambos enfoques son socialmente aceptables y algunos recibos ya sugieren importes calculados sobre el total.",
      },
      {
        question: "¿Es de mala educación usar una calculadora de propinas?",
        answer: "En absoluto: usar una calculadora de propinas es totalmente apropiado y demuestra interés por calcular de forma justa. Los teléfonos y las calculadoras de los recibos se utilizan habitualmente. Es mucho mejor usar una calculadora y dejar la propina correcta que estimarla mal. En un grupo, usar una calculadora ayuda a asegurar que la propina y la división de la cuenta sean exactas, evitando dejar de menos o calcular de más. Los camareros agradecen que los clientes calculen bien en lugar de redondear hacia abajo.",
      },
      {
        question: "¿Cuándo debo dejar propina en servicios que no son restaurantes?",
        answer: "Guía general de propinas en EE. UU.: peluquería y manicura: del 15 al 20%. Limpieza del hotel: de 2 a 5 $ por noche, dejados a diario. Botones: de 1 a 2 $ por maleta. Taxi o transporte compartido: del 15 al 20%. Reparto de comida: del 10 al 15% o un mínimo de 3 a 5 $. Mudanzas: de 20 a 50 $ por operario en media jornada. Tatuadores: del 15 al 20%. En el servicio de mostrador, como cafés, es opcional: de 0,50 a 1 $ se agradece pero no se espera.",
      },
      {
        question: "¿Cuál es el método rápido para calcular la propina?",
        answer: "Para una propina del 20%: mueve el decimal un lugar a la izquierda (dividir entre 10 para el 10%) y luego duplícalo. 45 $ × 10% = 4,50 $ × 2 = 9,00 $ de propina para el 20%. Para el 15%: calcula el 10% moviendo el decimal y añade la mitad. 45 $ × 10% = 4,50 $ + 2,25 $ = 6,75 $ para el 15%. Para el 18%: resta al 20% un 10% de esa propina. También puedes duplicar el impuesto sobre ventas si ronda el 8 o 9% para una estimación rápida.",
      },
    ],
    fields: [
      {
        id: "billAmount",
        label: "Bill Amount ($)",
        type: "number",
        placeholder: "e.g. 45.00",
        unit: "$",
        required: true,
      },
      {
        id: "tipPercent",
        label: "Tip Percentage (%)",
        type: "number",
        placeholder: "e.g. 18",
        defaultValue: 18,
        unit: "%",
        required: true,
      },
      {
        id: "numPeople",
        label: "Number of People",
        type: "number",
        placeholder: "1",
        defaultValue: 1,
        min: 1,
        required: false,
        helpText: "To split the bill equally",
      },
    ],
    results: [
      { id: "tipAmount", label: "Tip Amount", format: "currency", decimals: 2, isPrimary: false },
      { id: "totalBill", label: "Total Bill", format: "currency", decimals: 2, isPrimary: true },
      { id: "perPerson", label: "Per Person", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "Tip = Bill × (Tip% / 100); Total = Bill + Tip; Per Person = Total / Number of People",
    formulaExplanation: "Multiplying the bill by the tip percentage divided by 100 converts a rate into a dollar figure, so the gratuity always scales with the size of the check — a fixed percentage feels fair whether the bill is small or large. Adding that tip back to the original bill gives the amount actually owed, and dividing that total by the number of diners splits both food and gratuity evenly across the group.",
    formulaSource: "Standard tip/gratuity calculation",
    explanation: "A tip calculator takes the guesswork out of gratuity by instantly working out the tip amount, the new total, and each person's share the moment you enter a bill and a percentage. Tipping matters because in the United States gratuities form a large part of service workers' take-home pay, yet the mental math is easy to fumble at the end of a meal when everyone is ready to leave. Getting it right means fair pay for good service and no awkward under-tipping.\n\nThe method is simple percentage arithmetic: the tip is a share of the bill, added on top to produce the total, then divided evenly among diners. This tip calculator applies standard US norms as a starting point — roughly 15 to 20 percent at sit-down restaurants, more for exceptional service and less where counter service applies. Because it is calculated on the pre-tax amount by convention, though tipping on the post-tax total is also widely accepted, you stay consistent every time.\n\nDiners, groups splitting a check, delivery customers, and travelers checking local custom all reach for a tip calculator to settle up quickly and fairly.",
    example: {
      inputs: { billAmount: "80", tipPercent: "20", numPeople: "4" },
      explanation: "Bill: $80. Tip (20%): $16. Total: $96. Split 4 ways: $24 per person.",
    },
    faqs: [
      {
        question: "How much should I tip at a restaurant?",
        answer: "Standard US restaurant tipping is 15–20% of the pre-tax bill for sit-down restaurants. Fifteen percent is considered acceptable for adequate service; 18–20% is standard for good service; 25% or more shows appreciation for excellent service. For poor service, speak to a manager rather than leaving no tip — servers may not be responsible for kitchen delays. In many other countries (Japan, most of Europe, Australia), tipping is minimal or not customary — locals may even find it offensive. Always research tipping customs when traveling internationally.",
      },
      {
        question: "Should I tip on the pre-tax or post-tax amount?",
        answer: "Traditionally, tips are calculated on the pre-tax amount of the bill. In practice, most people use the total bill amount for convenience, and the difference is usually small. On a $100 pre-tax bill with 8% sales tax ($108 total), a 20% tip is $20 on pre-tax or $21.60 on post-tax — a $1.60 difference. Either approach is socially acceptable. Some restaurant receipts now show 'suggested tip' amounts calculated on the total including tax, making post-tax tipping the de facto standard in many areas.",
      },
      {
        question: "Is it rude to use a tip calculator?",
        answer: "Not at all — using a tip calculator is entirely appropriate and shows care in calculating fairly. Smartphones and restaurant receipt calculators are commonly used. It's far better to use a calculator and tip correctly than to estimate poorly. In a group, using a calculator helps ensure the tip and bill split are accurate, preventing awkward under-tipping or over-calculation. Servers appreciate when customers tip correctly rather than rounding down and leaving less than intended.",
      },
      {
        question: "When should I tip on services other than restaurants?",
        answer: "General US tipping guidelines: Hair/nail salon services: 15–20%. Hotel housekeeping: $2–5 per night, left daily (different staff may clean each day). Bellhops: $1–2 per bag. Taxi/rideshare: 15–20%. Food delivery: 10–15% or $3–5 minimum (delivery workers depend on tips). Movers: $20–50 per mover for a half day, more for longer. Tattoo artists: 15–20%. Personal trainers: optional, $10–50 for regular sessions, more at the holidays. Counter service (coffee, fast food): optional, $0.50–$1 is appreciated but not expected.",
      },
      {
        question: "What is the quick tip calculation method?",
        answer: "For 20% tip: move the decimal one place left (divide by 10 for 10%) then double it. $45 × 10% = $4.50 × 2 = $9.00 tip for 20%. For 15% tip: calculate 10% (move decimal), then add half. $45 × 10% = $4.50 + $2.25 = $6.75 for 15%. For 18%: 20% tip minus 10% of the tip amount. $9.00 − $0.90 = $8.10. Alternatively, double the sales tax if it's approximately 8–9% to get a quick 16–18% tip estimate.",
      },
    ],
    relatedCalculators: ["split-bill-calculator", "percentage-calculator", "sales-tax-calculator"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "split-bill",
    slug: "split-bill-calculator",
    category: "Everyday Life",
    categorySlug: "everyday",
    title: "Split Bill Calculator",
    shortDescription: "Evenly split a restaurant bill or any shared expense among any number of people, including tip.",
    seoTitle: "Split Bill Calculator — Divide Bill & Tip Between Friends",
    metaDescription: "Split any bill evenly between any number of people including tip. Calculate per person cost instantly. Free online bill splitting calculator.",
    primaryKeyword: "split bill calculator",
    secondaryKeywords: ["how to split a bill", "bill splitting calculator", "divide bill calculator", "group dinner calculator"],
    slugEs: "calculadora-para-dividir-la-cuenta",
    titleEs: "Calculadora para Dividir la Cuenta",
    shortDescriptionEs: "Divide equitativamente la cuenta de un restaurante o cualquier gasto compartido entre cualquier número de personas, incluida la propina.",
    seoTitleEs: "Calculadora para Dividir la Cuenta — Reparte Cuenta y Propina",
    metaDescriptionEs: "Divide cualquier cuenta equitativamente entre cualquier número de personas, incluida la propina. Calcula el coste por persona al instante. Calculadora gratuita para dividir cuentas.",
    primaryKeywordEs: "calculadora para dividir la cuenta",
    secondaryKeywordsEs: ["cómo dividir una cuenta", "calculadora para repartir la cuenta", "calculadora de cena en grupo"],
    formulaExplanationEs: "Multiplicar la cuenta por uno más la tasa de propina agrupa el coste de la comida y la gratificación en un único gran total, de modo que nadie se olvida de aportar para la propina. Dividir ese total entre el número de comensales funciona porque una división equitativa asume que cada persona compartió la experiencia por igual, repartiendo cada dólar de la misma forma. Cuando el resultado no cae en un céntimo exacto, una persona absorbe el pequeño resto para que los pagos sumen exactamente.",
    explanationEs: "Una calculadora para dividir la cuenta reparte una cuenta compartida —más la propina— equitativamente entre cualquier número de personas, dando la contribución exacta de cada una en un solo paso. Dividir la cuenta de un restaurante es una de las tareas de cálculo más comunes del día a día, y sorprendentemente fácil de equivocar una vez que se añade la propina y el total ya no se reparte en cantidades limpias. Una calculadora dedicada elimina esa fricción para que nadie pague de menos y el organizador no acabe cubriendo la diferencia.\n\nEl enfoque es cuidadoso con el orden de las operaciones: primero suma la propina a la cuenta y luego divide el gran total entre el número de comensales, lo que garantiza que todos contribuyan de forma proporcional tanto a la comida como a la gratificación. Dividir a partes iguales es lo más justo cuando la gente pidió cosas parecidas; para pedidos muy desiguales, una división por artículos o proporcional es más apropiada, y muchos restaurantes grandes ya añaden una propina automática para grupos de seis o más, así que revisa el recibo antes de sumar otra.\n\nAmigos que saldan una cena de grupo, compañeros de piso que reparten gastos del hogar y colegas que cubren un almuerzo de equipo usan una calculadora para dividir la cuenta y llegar a una respuesta justa y exacta al céntimo en segundos en lugar de discutir sobre recibos.",
    exampleEs: {
      inputs: { totalBill: "120", numPeople: "4", tipPercent: "20" },
      explanation: "Cuenta: 120 $. Propina (20%): 24 $. Total: 144 $. Dividido entre 4: 36 $ por persona, de los cuales 6 $ son propina y 30 $ son comida y bebidas.",
    },
    faqsEs: [
      {
        question: "¿Cómo divido una cuenta cuando cada uno pidió cantidades distintas?",
        answer: "Para que la división a partes iguales sea justa, todos deberían haber pedido cantidades similares. Cuando hay diferencias importantes, las opciones incluyen: división por artículos, donde cada persona paga exactamente lo que pidió más su parte de lo compartido y el mismo porcentaje de propina; división proporcional, donde cada uno paga un porcentaje del total según su subtotal; o negociar dentro del grupo, donde quien más pidió puede ofrecerse a pagar más. Aplicaciones como Splitwise o Venmo facilitan registrar los pedidos.",
      },
      {
        question: "¿La propina se incluye antes o después de dividir?",
        answer: "Calcula siempre la propina primero y luego divide. Calcula: Total = Cuenta + (Cuenta × Propina%). Después: Por Persona = Total ÷ Número de Personas. Así todos contribuyen a la propina de forma proporcional. El error que se debe evitar es dividir primero la cuenta sin propina y que cada uno calcule su propia propina, lo que suele llevar a subestimarla. Nuestra calculadora gestiona el orden correcto automáticamente: la propina se suma al total antes de dividir entre el número de personas.",
      },
      {
        question: "¿Qué pasa si el importe por persona no se divide exactamente?",
        answer: "Cuando el total no se divide en céntimos exactos, el redondeo causa una discrepancia (por ejemplo, 144,37 $ ÷ 4 = 36,0925 $, de modo que tres personas pagan 36,09 $ y una paga 36,10 $). El enfoque habitual: todos pagan el importe redondeado hacia abajo, y quien tenga el mayor resto, o quien se ofrezca, paga un céntimo más. Para pagos en efectivo, que cada uno ponga su parte y quien organice se encargue del pequeño resto. La mayoría de las apps de pago gestionan importes exactos con céntimos.",
      },
      {
        question: "¿Cómo trato a alguien que no bebe alcohol?",
        answer: "Quienes no beben suelen sentirse incómodos con la división equitativa cuando el alcohol infla la cuenta de forma significativa. Enfoques justos: calcular la comida y las bebidas por separado, dividiendo la comida por igual y pagando las bebidas quienes las pidieron. Como alternativa, quienes no beben pagan su parte proporcional según su subtotal personal, mientras los demás reparten el resto. Muchos grupos lo acuerdan antes de pedir para evitar incomodidad. El organizador puede facilitarlo diciendo por adelantado cómo se repartirá.",
      },
      {
        question: "¿Qué aplicaciones facilitan dividir cuentas?",
        answer: "Varias aplicaciones se especializan en dividir cuentas y gastos compartidos: Splitwise (la más popular para gastos de grupo continuos y seguimiento de deudas), Tab (fotografía y divide un recibo por artículo), Venmo y Cash App (pago fácil, aunque aún debes calcular las divisiones), PayPal (reparte solicitudes entre varias personas) y las transferencias bancarias. Para dividir en persona, muchos restaurantes aceptan el pago en varias tarjetas: solo pide dividir la cuenta al pagar. Usar nuestra calculadora primero te da el importe exacto por persona que solicitar.",
      },
    ],
    fields: [
      {
        id: "totalBill",
        label: "Total Bill ($)",
        type: "number",
        placeholder: "e.g. 120",
        unit: "$",
        required: true,
        helpText: "Total before tip",
      },
      {
        id: "numPeople",
        label: "Number of People",
        type: "number",
        placeholder: "e.g. 4",
        min: 1,
        required: true,
      },
      {
        id: "tipPercent",
        label: "Tip Percentage (%)",
        type: "number",
        placeholder: "e.g. 18",
        defaultValue: 18,
        unit: "%",
        required: false,
      },
    ],
    results: [
      { id: "tipAmount", label: "Total Tip", format: "currency", decimals: 2, isPrimary: false },
      { id: "totalWithTip", label: "Total with Tip", format: "currency", decimals: 2, isPrimary: false },
      { id: "perPerson", label: "Per Person", format: "currency", decimals: 2, isPrimary: true },
      { id: "tipPerPerson", label: "Tip Per Person", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "Total with tip = Bill × (1 + Tip%/100); Per person = Total / Number of people",
    formulaExplanation: "Multiplying the bill by one plus the tip rate rolls the food cost and gratuity into a single grand total, so no one forgets to chip in for the tip. Dividing that total by the number of diners works because an even split assumes each person shared the experience equally, spreading every dollar the same way. When the result does not land on a whole cent, one person absorbs the small remainder so the payments still add up exactly.",
    formulaSource: "Standard bill-splitting arithmetic",
    explanation: "A split bill calculator divides a shared check — plus tip — evenly across any number of people, giving each person's exact contribution in one step. Splitting a restaurant bill is one of the most common everyday math tasks, and it is surprisingly easy to get wrong once gratuity is added and the total no longer divides into clean amounts. A dedicated split bill calculator removes that friction so nobody underpays and the organizer is not left covering the gap.\n\nThe approach is deliberate about order of operations: it adds the tip to the bill first, then divides the grand total by the number of diners, which guarantees everyone contributes proportionally to both the food and the gratuity. Splitting evenly is fairest when people ordered similar items; for very unequal orders, an itemized or proportional split is more appropriate, and many large restaurants already add an automatic gratuity for parties of six or more, so check the receipt before adding another tip.\n\nFriends settling a group dinner, roommates sharing household costs, and colleagues covering a team lunch all use a split bill calculator to reach a fair, penny-accurate answer in seconds rather than arguing over receipts.",
    example: {
      inputs: { totalBill: "120", numPeople: "4", tipPercent: "20" },
      explanation: "Bill: $120. Tip (20%): $24. Total: $144. Split 4 ways: $36 per person, of which $6 is tip and $30 is food/drinks.",
    },
    faqs: [
      {
        question: "How do I split a bill when people ordered different amounts?",
        answer: "For equal splits to be fair, people should have ordered roughly similar amounts. When there are significant differences, options include: (1) Itemized split — each person pays for exactly what they ordered plus their share of shared items and the same tip percentage. This is most fair but requires a detailed review of the receipt. (2) Proportional split — each person pays a percentage of the total based on their subtotal. Apps like Splitwise, Tab, or Venmo make this easier by letting people log their orders. (3) Negotiate among the group — the person who ordered the most might volunteer to pay more.",
      },
      {
        question: "Should tip be included before or after splitting?",
        answer: "Always calculate the tip first, then split. Calculate: Total = Bill + (Bill × Tip%). Then: Per Person = Total / Number of People. This ensures everyone contributes to the tip proportionally. The error to avoid: splitting the pre-tip bill first, then each person calculating their own tip — this often leads to underestimation. Our calculator handles the correct order automatically: tip is added to the total before dividing by the number of people.",
      },
      {
        question: "What if the per-person amount doesn't divide evenly?",
        answer: "When the total doesn't divide evenly into whole cents, rounding causes a discrepancy (e.g., $144.37 / 4 = $36.0925, so three people pay $36.09 and one pays $36.10). The standard approach: everyone pays the rounded-down amount, and whoever has the largest remaining amount (or whoever offers) pays one cent more. For cash payments, have everyone put in their share and whoever organized the payment handles any small remainder. Most peer-payment apps (Venmo, Zelle) handle exact amounts including cents, making this trivial.",
      },
      {
        question: "How do I handle someone who doesn't drink alcohol?",
        answer: "Non-drinkers often feel uncomfortable with equal splitting when alcohol significantly inflates the bill. Fair approaches: Calculate food vs. drinks separately — food is split equally; drinks are paid by those who ordered them. Alternatively, teetotalers pay their proportional share based on their personal subtotal, while drinkers split the remaining amount. Many groups pre-agree on this before ordering to avoid awkwardness at payment time. The person who organized the dinner can facilitate by saying upfront 'We'll split evenly' or 'We'll each pay our own drinks.'",
      },
      {
        question: "What apps make splitting bills easier?",
        answer: "Several apps specialize in bill splitting and shared expenses: Splitwise (most popular for ongoing group expenses and tracking IOUs), Tab (photograph and split a receipt by item), Venmo and Cash App (easy payment, but you still need to calculate splits), PayPal (splits requests among multiple people), Zelle (bank-to-bank transfers). For in-person restaurant splitting, many restaurants accept split payment on multiple cards — simply ask to split the bill when you're ready to pay, specifying how you want it divided. Using our calculator first gives you the exact per-person amount to request.",
      },
    ],
    relatedCalculators: ["tip-calculator", "percentage-calculator", "discount-calculator"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "discount",
    slug: "discount-calculator",
    category: "Everyday Life",
    categorySlug: "everyday",
    title: "Discount Calculator",
    shortDescription: "Calculate the sale price after a percentage or fixed discount. See your savings instantly.",
    seoTitle: "Discount Calculator — Sale Price After Discount",
    metaDescription: "Calculate the final price after a percentage or dollar discount. See how much you save instantly. Free online discount and sale price calculator.",
    primaryKeyword: "discount calculator",
    secondaryKeywords: ["sale price calculator", "percent off calculator", "how much is 20% off", "discount percentage calculator"],
    slugEs: "calculadora-de-descuentos",
    titleEs: "Calculadora de Descuentos",
    shortDescriptionEs: "Calcula el precio de venta tras un descuento porcentual o fijo. Consulta tu ahorro al instante.",
    seoTitleEs: "Calculadora de Descuentos — Precio de Venta tras el Descuento",
    metaDescriptionEs: "Calcula el precio final tras un descuento porcentual o en dólares. Consulta cuánto ahorras al instante. Calculadora gratuita de descuento y precio de venta.",
    primaryKeywordEs: "calculadora de descuentos",
    secondaryKeywordsEs: ["calculadora de precio rebajado", "calculadora de porcentaje de descuento", "cuánto es un 20% de descuento"],
    formulaExplanationEs: "Restar la tasa de descuento a uno deja la fracción del precio que aún pagas, así que multiplicar el precio original por esa fracción llega directamente al precio de venta sin un paso de resta aparte. Un descuento fijo en dólares es aún más simple —se resta directamente del precio—, pero representa una parte distinta en un artículo barato que en uno caro, por lo que el método porcentual se aplica primero cuando se indican ambos.",
    explanationEs: "Las calculadoras de descuentos son esenciales para comprar de forma inteligente. Tanto si miras una oferta de '30% de descuento', un 'cupón de 20 $ de descuento' o intentas averiguar si una oferta lo es realmente, esta calculadora te muestra el precio final exacto y cuánto ahorras.\n\nLos minoristas usan descuentos porcentuales con más frecuencia porque escalan con el precio original y parecen mayores. Una oferta de '30% de descuento' en un artículo de 300 $ ahorra 90 $, pero en uno de 30 $ solo son 9 $. Los descuentos fijos en dólares (20 $ de descuento) funcionan distinto: son una mejor oferta en artículos baratos (el 20% de descuento en un artículo de 100 $ son 20 $) y una oferta menor en artículos caros (el 4% de descuento en uno de 500 $ son 20 $).\n\nAl comparar ofertas, calcula el precio final, no solo el importe del descuento. Un artículo con '50% de descuento' sobre un precio original inflado puede no ser más barato que otro con '10% de descuento' sobre un precio justo. Compara siempre precios finales, no porcentajes de descuento.",
    exampleEs: {
      inputs: { originalPrice: "79.99", discountPercent: "25", discountAmount: "0" },
      explanation: "25% de descuento sobre 79,99 $: Ahorro = 79,99 $ × 0,25 = 20,00 $. Precio final = 79,99 $ − 20,00 $ = 59,99 $. El precio de venta se redondea a 59,99 $.",
    },
    faqsEs: [
      {
        question: "¿Cómo calculo un porcentaje de descuento mentalmente?",
        answer: "Para un 10% de descuento: mueve el punto decimal un lugar a la izquierda. 85 $ × 10% = 8,50 $ de descuento. Para un 20%: duplica el importe del 10%. 8,50 $ × 2 = 17 $, así que 85 $ − 17 $ = 68 $. Para un 25%: divide entre 4. 80 $ ÷ 4 = 20 $, así que 60 $ de precio final. Para un 50%: divide entre 2. Para un 30%: 3 × 10%. Para un 15%: 10% más la mitad del 10%. Combinar estos bloques permite calcular la mayoría de descuentos comunes.",
      },
      {
        question: "¿Cómo hallo el precio original si conozco el precio de venta y el descuento?",
        answer: "Reordena la fórmula del descuento: Original = Precio de Venta ÷ (1 − Descuento%/100). Por ejemplo, un artículo de 70 $ ya está marcado con un 30% de descuento. Precio original = 70 $ ÷ (1 − 0,30) = 70 $ ÷ 0,70 = 100 $. Este cálculo es útil cuando se muestra un precio rebajado sin el original, o cuando quieres verificar que el 'precio original' que muestra un minorista era legítimo y no estaba inflado solo para que el descuento pareciera mayor.",
      },
      {
        question: "¿Cómo funcionan los descuentos acumulados?",
        answer: "Los descuentos acumulados (varios descuentos aplicados de forma sucesiva) NO se suman sin más. Un 20% de descuento seguido de un 10% adicional NO es un 30%. Es: primero reduce un 20%, luego reduce el resultado un 10%. Ejemplo: 100 $ → 20% de descuento = 80 $ → 10% de descuento = 72 $. El descuento efectivo combinado es del 28%, no del 30%. Fórmula para dos descuentos acumulados: Efectivo% = 1 − (1 − d1)(1 − d2). Por eso una oferta de '20% más un 10% extra' vale algo menos que un 30% directo.",
      },
      {
        question: "¿Los precios rebajados son siempre un ahorro real?",
        answer: "No siempre. Los minoristas a veces inflan el 'precio original' para que el descuento parezca mayor, una práctica llamada anclaje de precios. Señales de alerta: el artículo lleva meses al precio 'rebajado'; el precio 'original' está muy por encima de lo que cobra cualquier minorista; el artículo aparece al mismo precio 'rebajado' en varias tiendas. Extensiones de navegador y herramientas de historial de precios rastrean si un precio de oferta es realmente inferior a la media histórica. Las rebajas de temporada suelen ofrecer descuentos reales.",
      },
      {
        question: "¿Cómo calculo el porcentaje de descuento si conozco el precio original y el de venta?",
        answer: "Descuento% = (Original − Precio de Venta) ÷ Original × 100. Por ejemplo, un artículo originalmente de 120 $, en oferta a 84 $: Descuento% = (120 $ − 84 $) ÷ 120 $ × 100 = 36 $ ÷ 120 $ × 100 = 30% de descuento. Es útil cuando una etiqueta muestra ambos precios pero no el porcentaje, o al comparar descuentos entre artículos distintos. El ahorro absoluto (36 $) y el porcentaje (30%) cuentan historias diferentes: 36 $ sobre 120 $ frente a 36 $ sobre 1.200 $ representan niveles muy distintos.",
      },
    ],
    fields: [
      {
        id: "originalPrice",
        label: "Original Price ($)",
        type: "number",
        placeholder: "e.g. 79.99",
        unit: "$",
        required: true,
      },
      {
        id: "discountPercent",
        label: "Discount Percentage (%)",
        type: "number",
        placeholder: "e.g. 30",
        unit: "%",
        defaultValue: 0,
        required: false,
        helpText: "Enter percentage off (e.g. 30 for 30% off)",
      },
      {
        id: "discountAmount",
        label: "OR Discount Amount ($)",
        type: "number",
        placeholder: "e.g. 20",
        unit: "$",
        defaultValue: 0,
        required: false,
        helpText: "Enter a fixed dollar discount instead of a percentage",
      },
    ],
    results: [
      { id: "finalPrice", label: "Final Price", format: "currency", decimals: 2, isPrimary: true },
      { id: "savings", label: "You Save", format: "currency", decimals: 2, isPrimary: false },
      { id: "discountPct", label: "Discount Percentage", format: "percentage", decimals: 1, isPrimary: false },
    ],
    formula: "Sale Price = Original Price × (1 − Discount%) ; Savings = Original − Final",
    formulaExplanation: "Subtracting the discount rate from one leaves the fraction of the price you still pay, so multiplying the original price by that fraction lands directly on the sale price without a separate subtraction step. A fixed dollar discount is simpler still — it comes straight off the price — but it represents a different share of a cheap item than an expensive one, which is why the percentage method is applied first when both are supplied.",
    formulaSource: "Standard percentage discount",
    explanation: "Discount calculators are essential for smart shopping. Whether you're looking at a '30% off' sale, a '$20 off coupon,' or trying to figure out if a deal is actually a deal, this calculator shows you the exact final price and how much you're saving.\n\nRetailers use percentage discounts most often because they scale with the original price and feel larger. A '30% off' sale on a $300 item saves $90 — but on a $30 item, that's only $9. Fixed dollar discounts ($20 off) work differently: they're a better deal on cheaper items (20% off a $100 item = $20) and a smaller deal on expensive items (4% off a $500 item = $20).\n\nWhen comparing deals, calculate the final price — not just the discount amount. A 50% off item from an inflated original price may not be cheaper than a 10% off from a fair retail price. Always compare final prices, not discount percentages.",
    example: {
      inputs: { originalPrice: "79.99", discountPercent: "25", discountAmount: "0" },
      explanation: "25% off $79.99: Savings = $79.99 × 0.25 = $20.00. Final price = $79.99 − $20.00 = $59.99. The sale price rounds to $59.99.",
    },
    faqs: [
      {
        question: "How do I calculate a percentage off in my head?",
        answer: "For 10% off: move the decimal point one place left. $85 × 10% = $8.50 off. For 20% off: double the 10% amount. $8.50 × 2 = $17 off, so $85 − $17 = $68. For 25% off: divide by 4. $80 ÷ 4 = $20 off, so $60 final price. For 50% off: divide by 2. For 30% off: 3 × 10%. For 15% off: 10% + half of 10%. For 5% off: half of 10%. Combining these building blocks lets you calculate most common discounts mentally.",
      },
      {
        question: "How do I find the original price if I know the sale price and discount?",
        answer: "Rearrange the discount formula: Original = Sale Price / (1 − Discount%/100). For example, a $70 item is already marked as 30% off. Original price = $70 / (1 − 0.30) = $70 / 0.70 = $100. This calculation is useful when a sale price is shown without the original, or when you want to verify that the 'original price' a retailer shows was legitimate and not inflated just to make the discount look bigger.",
      },
      {
        question: "How do stacked discounts work?",
        answer: "Stacked discounts (multiple discounts applied sequentially) do NOT simply add together. A 20% off followed by an additional 10% off is NOT 30% off. It's: first reduce by 20%, then reduce the result by 10%. Example: $100 → 20% off = $80 → 10% off = $72. The combined effective discount is 28%, not 30%. Formula for two stacked discounts: Effective% = 1 − (1 − d1)(1 − d2). This is why a '20% off + extra 10% off' sale is slightly less valuable than a straight 30% off sale, even though it sounds the same.",
      },
      {
        question: "Are sale prices always actually savings?",
        answer: "Not always. Retailers sometimes inflate the 'original price' to make the discount appear larger — a practice called price anchoring. Red flags: the item has been at the 'sale' price for months; the 'original' price is far above what any retailer charges; the item appears at the same 'sale' price across multiple retailers. Browser extensions like Honey, Capital One Shopping, and CamelCamelCamel (for Amazon) track price history so you can verify whether a 'sale' price is genuinely lower than the historical average. Seasonal sales (Black Friday, end-of-season clearance) typically offer real discounts.",
      },
      {
        question: "How do I calculate the discount percentage if I know original and sale prices?",
        answer: "Discount% = (Original − Sale Price) / Original × 100. For example, an item originally $120, on sale for $84: Discount% = ($120 − $84) / $120 × 100 = $36 / $120 × 100 = 30% off. This is useful when a tag shows both prices but not the percentage, or when comparing discounts across different items. Note that the absolute savings ($36) and the percentage (30%) tell different stories — a $36 savings on a $120 item vs. a $36 savings on a $1,200 item represent very different discount levels (30% vs. 3%).",
      },
    ],
    relatedCalculators: ["percentage-calculator", "sales-tax-calculator", "tip-calculator"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "sales-tax",
    slug: "sales-tax-calculator",
    category: "Everyday Life",
    categorySlug: "everyday",
    title: "Sales Tax Calculator",
    shortDescription: "Calculate the sales tax amount and total price including tax for any purchase.",
    seoTitle: "Sales Tax Calculator — Price Including Tax",
    metaDescription: "Calculate sales tax and total price with tax for any purchase. Works for any tax rate. Free online sales tax calculator with instant results.",
    primaryKeyword: "sales tax calculator",
    secondaryKeywords: ["tax calculator", "how to calculate sales tax", "price plus tax", "total price with tax"],
    slugEs: "calculadora-de-impuesto-sobre-ventas",
    titleEs: "Calculadora de Impuesto sobre Ventas",
    shortDescriptionEs: "Calcula el importe del impuesto sobre ventas y el precio total con impuestos para cualquier compra.",
    seoTitleEs: "Calculadora de Impuesto sobre Ventas — Precio con Impuestos",
    metaDescriptionEs: "Calcula el impuesto sobre ventas y el precio total con impuestos para cualquier compra. Funciona con cualquier tasa. Calculadora gratuita con resultados al instante.",
    primaryKeywordEs: "calculadora de impuesto sobre ventas",
    secondaryKeywordsEs: ["calculadora de impuestos", "cómo calcular el impuesto sobre ventas", "precio con impuestos incluidos"],
    formulaExplanationEs: "Multiplicar el precio por la tasa de impuesto entre 100 convierte el porcentaje del gobierno en los dólares que se añaden en la caja, y sumar ese importe al precio da el total que entregas. La fórmula inversa divide el total con impuestos incluidos entre uno más la tasa, porque el total ya contiene tanto el precio base como su impuesto; restar un porcentaje plano del total se pasaría de largo y subestimaría el verdadero importe antes de impuestos.",
    explanationEs: "Una calculadora de impuesto sobre ventas añade el impuesto al consumo correcto a una compra, mostrando tanto el importe del impuesto como el precio final que pagarás realmente en la caja. El impuesto sobre ventas importa porque, a diferencia del impuesto anual sobre la renta, se aplica transacción a transacción, y la tasa que debes depende por completo de dónde te encuentres: las tasas combinadas estatales y locales en Estados Unidos van del cero a bastante más del diez por ciento. Conocer la cifra exacta ayuda con el presupuesto, el reporte de gastos y comprobar que un recibo se cobró correctamente.\n\nEsta calculadora funciona en dos direcciones. Hacia adelante, convierte un precio antes de impuestos en un total con impuestos incluidos multiplicando el precio por la tasa y añadiéndolo. A la inversa, recupera el precio antes de impuestos a partir de un total con impuestos incluidos dividiendo en lugar de restar, que es la única forma de obtener un importe base exacto para la contabilidad.\n\nCompradores que comparan precios de otros estados, autónomos que registran gastos deducibles y pequeños empresarios que cotizan precios con impuestos incluidos confían en una calculadora de impuesto sobre ventas para evitar los errores de redondeo que surgen al hacer cálculos de porcentajes de cabeza.",
    exampleEs: {
      inputs: { price: "100", taxRate: "8.5" },
      explanation: "Compra de 100 $ al 8,5% de impuesto sobre ventas: Impuesto = 100 $ × 0,085 = 8,50 $. Total = 108,50 $. A la inversa: si gastaste 108,50 $ en total al 8,5%, el precio antes de impuestos era 108,50 $ ÷ 1,085 = 100,00 $.",
    },
    faqsEs: [
      {
        question: "¿Cuál es la tasa de impuesto sobre ventas en mi estado?",
        answer: "Las tasas varían según el estado y la localidad. Estados sin impuesto estatal sobre ventas: Oregón, Montana, Nueva Hampshire, Delaware y Alaska. Otras tasas destacadas (solo estatales, los impuestos locales pueden añadir más): California 7,25%, Tennessee 7%, Texas 6,25%, Washington 6,5%, Nueva York 4% (la ciudad de Nueva York suma un 4,5% para un 8,875% combinado), Colorado 2,9%. Las tasas combinadas pueden alcanzar del 9 al 11% en algunas ciudades. Para la tasa exacta de tu dirección, consulta el Departamento de Ingresos de tu estado.",
      },
      {
        question: "¿Qué artículos están exentos del impuesto sobre ventas?",
        answer: "Las exenciones varían según el estado, pero las comunes incluyen: alimentos (exentos por completo en muchos estados, parcialmente en otros; la comida preparada suele gravarse pero los básicos no), medicamentos con receta (exentos en la mayoría de estados), medicamentos sin receta (variable), ropa (exenta en algunos estados como Pensilvania y Minnesota, y durante los periodos sin impuestos de vuelta al cole), equipos e insumos de fabricación, suministros agrícolas y compras de organizaciones sin ánimo de lucro y entidades gubernamentales. Algunos estados tienen 'vacaciones fiscales' periódicas para artículos concretos.",
      },
      {
        question: "¿Cómo calculo el impuesto sobre ventas a la inversa (hallar el precio antes de impuestos)?",
        answer: "Para hallar el precio antes de impuestos cuando conoces el precio total con impuestos: Precio antes de impuestos = Precio Total ÷ (1 + Tasa/100). Por ejemplo, si pagaste 54,00 $ y la tasa era del 8%: Antes de impuestos = 54 $ ÷ 1,08 = 50 $. Esto difiere de simplemente restar el 8% del total (54 $ × 0,08 = 4,32 $; 54 $ − 4,32 $ = 49,68 $, incorrecto). El método de división da el importe correcto antes de impuestos. Nuestra calculadora muestra este cálculo inverso.",
      },
      {
        question: "¿Pago impuesto sobre ventas en las compras por internet?",
        answer: "Sí, en la mayoría de los casos. Desde el fallo del Tribunal Supremo de 2018 en South Dakota v. Wayfair, los minoristas en línea deben recaudar el impuesto sobre ventas en los estados donde tienen 'nexo económico' (normalmente 100.000 $ en ventas anuales o más de 200 transacciones). La mayoría de grandes minoristas en línea recaudan ahora el impuesto en todos los estados que lo tienen. Debes 'impuesto de uso' en compras donde el vendedor no lo recaudó, a la misma tasa y autodeclarado en tu declaración estatal.",
      },
      {
        question: "¿El impuesto sobre ventas se calcula antes o después de los descuentos?",
        answer: "El impuesto sobre ventas suele calcularse sobre el precio de venta final después de aplicar los descuentos. Si un artículo cuesta 100 $ con un cupón de 20 $, pagas el impuesto sobre 80 $ (el precio con descuento), no sobre 100 $. Sin embargo, esta regla tiene matices: los reembolsos del fabricante pagados tras la venta pueden no reducir el importe gravable en algunos estados, y los paquetes de productos pueden tener un tratamiento fiscal complejo. Para la mayoría de compras minoristas con descuentos estándar, pagas impuesto solo sobre lo que realmente abonas antes de impuestos.",
      },
    ],
    sensitivity: "tax",
    fields: [
      {
        id: "price",
        label: "Price Before Tax ($)",
        type: "number",
        placeholder: "e.g. 99.99",
        unit: "$",
        required: true,
      },
      {
        id: "taxRate",
        label: "Sales Tax Rate (%)",
        type: "number",
        placeholder: "e.g. 8.5",
        unit: "%",
        required: true,
        helpText: "Find your rate at your state/local tax authority. US rates typically range from 0% to 11%.",
      },
    ],
    results: [
      { id: "taxAmount", label: "Sales Tax", format: "currency", decimals: 2, isPrimary: false },
      { id: "totalPrice", label: "Total with Tax", format: "currency", decimals: 2, isPrimary: true },
      { id: "reverseBase", label: "Pre-tax Price (if total is entered above)", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "Tax = Price × (Tax Rate / 100); Total = Price + Tax; Pre-tax = Total / (1 + Tax Rate / 100)",
    formulaExplanation: "Multiplying the price by the tax rate over 100 converts the government's percentage into the dollars added at checkout, and appending that amount to the price gives the total you hand over. The reverse formula divides the tax-inclusive total by one plus the rate because the total already contains both the base price and its tax; subtracting a flat percentage of the total would overshoot and understate the true pre-tax amount.",
    formulaSource: "Standard sales tax calculation",
    explanation: "A sales tax calculator adds the correct consumption tax to a purchase, showing both the tax amount and the final price you will actually pay at the register. Sales tax matters because, unlike annual income tax, it is applied transaction by transaction, and the rate you owe depends entirely on where you are standing — combined state and local rates in the United States range from zero to well above ten percent. Knowing the exact figure helps with budgeting, expense reporting, and checking that a receipt was rung up correctly.\n\nThis sales tax calculator works in two directions. Forward, it turns a pre-tax price into a tax-inclusive total by multiplying the price by the tax rate and adding it on. In reverse, it recovers the pre-tax price from a tax-included total by dividing rather than subtracting, which is the only way to get an accurate base amount for bookkeeping.\n\nShoppers comparing out-of-state prices, freelancers logging deductible expenses, and small business owners quoting tax-inclusive prices all rely on a sales tax calculator to avoid the rounding mistakes that come from doing percentage math in their heads.",
    example: {
      inputs: { price: "100", taxRate: "8.5" },
      explanation: "$100 purchase at 8.5% sales tax: Tax = $100 × 0.085 = $8.50. Total = $108.50. Reverse: if you spent $108.50 total at 8.5% tax, the pre-tax price was $108.50 / 1.085 = $100.00.",
    },
    faqs: [
      {
        question: "What is the sales tax rate in my state?",
        answer: "Sales tax rates vary by state and locality. States with no statewide sales tax: Oregon, Montana, New Hampshire, Delaware, Alaska. Other notable rates (statewide only, local taxes may add more): California 7.25%, Tennessee 7%, Texas 6.25%, Washington 6.5%, New York 4% (NYC adds 4.5% city tax = 8.875% combined), Colorado 2.9%. Combined state + local rates can reach 9–11%+ in some cities. For the precise rate at your specific address, check your state's Department of Revenue website or use the Sales Tax Institute's lookup tool.",
      },
      {
        question: "What items are exempt from sales tax?",
        answer: "Sales tax exemptions vary by state, but common exemptions include: groceries (fully exempt in many states, partially exempt in others — e.g., prepared food is often taxed but grocery staples aren't), prescription medications (exempt in most states), non-prescription medications (varies), clothing (exempt in some states like Pennsylvania and Minnesota, and during back-to-school tax holidays), manufacturing equipment and inputs, agricultural supplies, and purchases by nonprofits and government entities. Some states have periodic 'tax holidays' for specific items like school supplies, energy-efficient appliances, or guns.",
      },
      {
        question: "How do I calculate sales tax in reverse (finding price before tax)?",
        answer: "To find the pre-tax price when you know the total-after-tax price: Pre-tax Price = Total Price / (1 + Tax Rate/100). For example, if you paid $54.00 and the tax rate was 8%: Pre-tax = $54 / 1.08 = $50. This is different from simply subtracting 8% from the total ($54 × 0.08 = $4.32; $54 − $4.32 = $49.68 — incorrect). The division method gives the correct pre-tax amount. Our calculator shows this reverse calculation for any inputs entered.",
      },
      {
        question: "Do I pay sales tax on online purchases?",
        answer: "Yes, in most cases. Since the 2018 Supreme Court ruling in South Dakota v. Wayfair, online retailers are required to collect sales tax in states where they have 'economic nexus' (typically $100,000 in annual sales or 200+ transactions). Most major online retailers (Amazon, Walmart, Target, etc.) now collect sales tax in all states that have it. You owe 'use tax' on purchases where the seller didn't collect sales tax — effectively the same rate as sales tax, self-reported on your state income tax return, though compliance is very low in practice.",
      },
      {
        question: "Is sales tax calculated before or after discounts?",
        answer: "Sales tax is generally calculated on the final selling price after discounts are applied. If an item is $100 with a $20 coupon, you pay sales tax on $80 (the discounted price), not $100. However, this rule has nuances: manufacturer rebates paid after the sale may not reduce the taxable amount in some states; bundled product deals may have complex tax treatment; promotional pricing vs. coupons may be treated differently. For most retail purchases with standard discounts, you safely pay tax only on the amount you actually pay before tax.",
      },
    ],
    relatedCalculators: ["discount-calculator", "tip-calculator", "percentage-calculator"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "unit-price",
    slug: "unit-price-calculator",
    category: "Everyday Life",
    categorySlug: "everyday",
    title: "Unit Price Calculator",
    shortDescription: "Compare the cost per unit of two products to find the better deal.",
    seoTitle: "Unit Price Calculator — Compare Cost Per Unit of Products",
    metaDescription: "Compare cost per unit between two products to find the better value. Works for any unit: per oz, per count, per liter. Free online unit price comparison.",
    primaryKeyword: "unit price calculator",
    secondaryKeywords: ["price per unit calculator", "cost per unit", "which is cheaper per unit", "value comparison calculator"],
    slugEs: "calculadora-de-precio-por-unidad",
    titleEs: "Calculadora de Precio por Unidad",
    shortDescriptionEs: "Compara el coste por unidad de dos productos para encontrar la mejor oferta.",
    seoTitleEs: "Calculadora de Precio por Unidad — Compara el Coste por Unidad",
    metaDescriptionEs: "Compara el coste por unidad entre dos productos para hallar el mejor valor. Funciona con cualquier unidad: por onza, por unidad, por litro. Comparación gratuita.",
    primaryKeywordEs: "calculadora de precio por unidad",
    secondaryKeywordsEs: ["calculadora de coste por unidad", "cuál es más barato por unidad", "calculadora de comparación de valor"],
    formulaExplanationEs: "Dividir el precio total de un envase entre la cantidad que contiene reduce cada opción al mismo denominador —el coste de una sola onza, unidad o litro—, de modo que envases de distinto tamaño pasan a ser directamente comparables. Como la unidad es idéntica en ambos lados, el producto con la cifra menor es genuinamente más barato por unidad y no solo más barato en total, por lo que comparar precios por unidad, y no de etiqueta, revela el mejor valor.",
    explanationEs: "Comparar el precio por unidad es una de las herramientas más potentes para comprar de forma más inteligente en el supermercado y el comercio. En muchas jurisdicciones las tiendas están obligadas por ley a mostrar el precio por unidad en las etiquetas de estantería, pero compararlo entre distintos tamaños y marcas puede seguir siendo confuso.\n\nLa calculadora de precio por unidad elimina la complejidad: introduce el precio y la cantidad de dos productos y te dice al instante cuál ofrece mejor valor por unidad (por onza, por unidad, por litro, etc.).\n\nLos tamaños más grandes suelen ser (aunque no siempre) más baratos por unidad; esa es la lógica de 'comprar a granel'. Sin embargo, no siempre es cierto. La marca de la tienda frente a la marca conocida al mismo tamaño, o un producto en oferta en un tamaño pero no en otro, pueden hacer que el tamaño pequeño sea más barato por unidad. Verifícalo siempre con la calculadora.\n\nMatiz importante: el precio por unidad solo mide la eficiencia de coste. Considera si realmente usarás la cantidad mayor antes de que caduque, y si la calidad de la opción más barata cumple tus estándares.",
    exampleEs: {
      inputs: { price1: "3.99", quantity1: "16", price2: "5.49", quantity2: "24" },
      explanation: "Producto A: 3,99 $ ÷ 16 oz = 0,249 $/oz. Producto B: 5,49 $ ÷ 24 oz = 0,229 $/oz. El Producto B es más barato por onza: pese a costar más en total, ofrece un 8% más de valor por unidad.",
    },
    faqsEs: [
      {
        question: "¿Qué significa precio por unidad?",
        answer: "El precio por unidad es el coste de una unidad estándar de un producto: por onza, por litro, por artículo, por libra, etc. Permite comparar el coste de envases de distinto tamaño de forma equivalente. El precio por unidad es obligatorio por ley en muchos estados y países; busca el número pequeño en las etiquetas de estantería, a menudo impreso bajo el precio de venta mayor. La ley federal no lo exige a nivel nacional, pero muchos minoristas lo ofrecen de forma voluntaria. La unidad debe ser la misma al comparar.",
      },
      {
        question: "¿El tamaño más grande siempre es más barato por unidad?",
        answer: "No, y esto sorprende a muchos compradores. Aunque comprar a granel suele ahorrar dinero por unidad, las excepciones son comunes. Las ofertas en tamaños pequeños pueden abaratarlos por unidad. Las marcas de tienda en tamaños pequeños a veces superan a las marcas conocidas en tamaños grandes. El precio por unidad en algunos productos, sobre todo en clubes de almacén, puede ser mayor que en supermercados en oferta. Promociones de temporada, cupones y ofertas de dos por uno pueden invertir la economía. Comprueba siempre con una calculadora.",
      },
      {
        question: "¿Qué pasa con productos que no son de la misma calidad?",
        answer: "El precio por unidad solo mide el coste por unidad de cantidad; no tiene en cuenta las diferencias de calidad. Una marca de tienda más barata puede tener un precio por unidad menor pero ingredientes, sabor o eficacia distintos. Para productos exactamente equivalentes (misma marca, mismo producto, distinto tamaño), el precio por unidad es definitivo. Para marcas o niveles de calidad diferentes, es un dato en tu decisión, no la respuesta final. En medicamentos, alimentos y herramientas, las diferencias de calidad importan especialmente.",
      },
      {
        question: "¿Cómo comparo productos medidos en unidades distintas?",
        answer: "Primero, convierte a una unidad común. Por ejemplo, comparar una botella de 1 litro con una de 33,8 onzas líquidas (ambas son 1 litro, pues 33,8 oz ≈ 1 L, así que son equivalentes). Para peso frente a volumen líquido, la conversión puede no ser directamente comparable (una libra de cereal no se compara directamente con un litro). Conversiones comunes: 1 libra = 16 onzas; 1 kilogramo = 1.000 gramos; 1 litro = 33,814 onzas líquidas; 1 galón = 128 onzas líquidas. Con todo en la misma unidad, compara los precios por unidad.",
      },
      {
        question: "¿Comprar a granel es siempre la opción financiera inteligente?",
        answer: "No necesariamente. Comprar a granel es inteligente cuando: usarás el producto antes de que caduque; tienes espacio de almacenamiento; el ahorro por unidad es significativo; tu presupuesto absorbe el coste inicial. Es contraproducente cuando: la comida se estropea antes de usarla (anulando el ahorro y generando desperdicio); compras por impulso grandes cantidades que no sueles necesitar; el dinero inmovilizado tiene un coste de oportunidad; pagas una cuota de club de almacén que cuesta más de lo que ahorras. El coste ambiental también importa a muchos. Calcula el precio por unidad y luego considera tu consumo real.",
      },
    ],
    fields: [
      {
        id: "price1",
        label: "Product A Price ($)",
        type: "number",
        placeholder: "e.g. 3.99",
        unit: "$",
        required: true,
      },
      {
        id: "quantity1",
        label: "Product A Quantity",
        type: "number",
        placeholder: "e.g. 16",
        required: true,
        helpText: "Number of units, ounces, count, etc.",
      },
      {
        id: "price2",
        label: "Product B Price ($)",
        type: "number",
        placeholder: "e.g. 5.49",
        unit: "$",
        required: true,
      },
      {
        id: "quantity2",
        label: "Product B Quantity",
        type: "number",
        placeholder: "e.g. 24",
        required: true,
      },
    ],
    results: [
      { id: "unitPrice1", label: "Product A: Cost per Unit", format: "currency", decimals: 4, isPrimary: false },
      { id: "unitPrice2", label: "Product B: Cost per Unit", format: "currency", decimals: 4, isPrimary: false },
      { id: "savings", label: "Savings per Unit (Better Deal)", format: "currency", decimals: 4, isPrimary: false },
      { id: "betterDeal", label: "Better Value", format: "text", isPrimary: true },
    ],
    formula: "Unit Price = Total Price / Quantity; Better Deal = lower unit price wins",
    formulaExplanation: "Dividing a package's total price by the quantity it contains reduces every option to the same denominator — the cost of a single ounce, item, or liter — so packages of different sizes become directly comparable. Because the unit is identical on both sides, the product with the lower figure is genuinely cheaper per unit rather than merely cheaper in total, which is why comparing unit prices, not sticker prices, reveals the better value.",
    formulaSource: "Standard unit-price comparison",
    explanation: "Unit price comparison is one of the most powerful tools for smarter grocery and retail shopping. Stores are required by law in many jurisdictions to display unit prices on shelf labels, but comparing them across different sizes and brands can still be confusing.\n\nThe unit price calculator removes the complexity: enter the price and quantity for two products, and it instantly tells you which is the better value per unit (per ounce, per count, per liter, etc.).\n\nLarger sizes are often (but not always) cheaper per unit — this is the rationale behind 'buy in bulk.' However, this isn't always true. Store brand vs. name brand at the same size, or a product on sale in one size but not another, may make the smaller size cheaper per unit. Always verify with the calculator.\n\nImportant caveat: unit price only measures cost efficiency. Consider whether you'll actually use the larger quantity before it expires, and whether the quality of the cheaper option meets your standards.",
    example: {
      inputs: { price1: "3.99", quantity1: "16", price2: "5.49", quantity2: "24" },
      explanation: "Product A: $3.99 / 16 oz = $0.249/oz. Product B: $5.49 / 24 oz = $0.229/oz. Product B is cheaper per ounce — despite costing more total, it provides 8% better value per unit.",
    },
    faqs: [
      {
        question: "What does unit price mean?",
        answer: "Unit price is the cost of one standard unit of a product — per ounce, per liter, per item, per pound, etc. It lets you compare the cost of differently sized packages on an apples-to-apples basis. Unit pricing is required by law in many US states and countries — look for the small number on grocery store shelf labels (often printed in smaller text below the larger retail price). Federal law doesn't require it nationwide, but many retailers provide it voluntarily. The unit should be the same when comparing (both per ounce, or both per count, etc.).",
      },
      {
        question: "Is the bigger size always cheaper per unit?",
        answer: "No — and this surprises many shoppers. While bulk buying usually saves money per unit, exceptions are common. Sales on smaller sizes can make them cheaper per unit. Store brands in smaller sizes sometimes undercut name brands in larger sizes. Unit pricing for some products (especially at warehouse clubs) can actually be higher than grocery stores on sale. Seasonal promotions, coupons, and buy-one-get-one deals can flip unit economics. Always check with a calculator rather than assuming larger = better value, especially when one size is on sale.",
      },
      {
        question: "What about products that aren't the same quality?",
        answer: "Unit price only measures cost per unit of quantity — it doesn't account for quality differences. A cheaper store brand may have a lower unit price but different ingredients, taste, or effectiveness. For exactly equivalent products (same brand, same product, different sizes), unit price is definitive. For different brands or quality tiers, unit price is one input in your decision, not the final answer. Some products where quality differences matter most: medications (active ingredient concentration matters more than unit price), food (nutritional content matters), and tools (durability affects total cost of ownership).",
      },
      {
        question: "How do I compare products measured in different units?",
        answer: "First, convert to a common unit. For example, comparing a 1-liter bottle to a 33.8 fl oz bottle (both are 1 liter — 33.8 oz ≈ 1 L, so they're equivalent). For weight vs. fluid measurement, conversion may not be directly comparable (a pound of cereal isn't directly comparable to a liter). Common conversions: 1 pound = 16 ounces; 1 kilogram = 1,000 grams; 1 liter = 33.814 fluid ounces; 1 gallon = 128 fluid ounces. Once all quantities are in the same unit, enter them and compare unit prices.",
      },
      {
        question: "Is buying in bulk always the smart financial choice?",
        answer: "Not necessarily. Bulk buying is financially smart when: you'll use the product before it expires; you have storage space; the per-unit savings are meaningful; your budget can absorb the upfront cost. Bulk buying backfires when: food spoils before you use it (negating savings and adding waste); you impulse-buy large quantities of items you don't usually need; the cash tied up in bulk inventory has an opportunity cost; you're paying for a warehouse club membership that costs more than you save. The environmental cost (packaging waste per unit, transportation) also matters to many consumers. Calculate the unit price, then consider usage rate and realistic consumption.",
      },
    ],
    relatedCalculators: ["discount-calculator", "percentage-calculator", "sales-tax-calculator"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
];
