import type { CalculatorDefinition } from "../types";

export const everydayWave2Calculators: CalculatorDefinition[] = [
  {
    id: "tip",
    slug: "tip-calculator",
    category: "Everyday Life",
    categorySlug: "everyday",
    title: "Tip Calculator",
    shortDescription: "Calculate the tip amount and total bill for any service. Split among multiple people too.",
    seoTitle: "Tip Calculator — Calculate Tip Amount & Split the Bill",
    metaDescription: "Calculate tip amount, total bill, and per-person share for any service. Supports custom tip percentages and splitting among multiple people.",
    primaryKeyword: "tip calculator",
    secondaryKeywords: ["how much to tip", "restaurant tip calculator", "gratuity calculator", "bill tip calculator"],
    fields: [
      {
        id: "billAmount",
        label: "Bill Amount ($)",
        type: "number",
        placeholder: "e.g. 45.00",
        unit: "$",
        required: true,
      },
      {
        id: "tipPercent",
        label: "Tip Percentage (%)",
        type: "number",
        placeholder: "e.g. 18",
        defaultValue: 18,
        unit: "%",
        required: true,
      },
      {
        id: "numPeople",
        label: "Number of People",
        type: "number",
        placeholder: "1",
        defaultValue: 1,
        min: 1,
        required: false,
        helpText: "To split the bill equally",
      },
    ],
    results: [
      { id: "tipAmount", label: "Tip Amount", format: "currency", decimals: 2, isPrimary: false },
      { id: "totalBill", label: "Total Bill", format: "currency", decimals: 2, isPrimary: true },
      { id: "perPerson", label: "Per Person", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "Tip = Bill × (Tip% / 100); Total = Bill + Tip; Per Person = Total / Number of People",
    formulaExplanation: "Multiplying the bill by the tip percentage divided by 100 converts a rate into a dollar figure, so the gratuity always scales with the size of the check — a fixed percentage feels fair whether the bill is small or large. Adding that tip back to the original bill gives the amount actually owed, and dividing that total by the number of diners splits both food and gratuity evenly across the group.",
    formulaSource: "Standard tip/gratuity calculation",
    explanation: "A tip calculator takes the guesswork out of gratuity by instantly working out the tip amount, the new total, and each person's share the moment you enter a bill and a percentage. Tipping matters because in the United States gratuities form a large part of service workers' take-home pay, yet the mental math is easy to fumble at the end of a meal when everyone is ready to leave. Getting it right means fair pay for good service and no awkward under-tipping.\n\nThe method is simple percentage arithmetic: the tip is a share of the bill, added on top to produce the total, then divided evenly among diners. This tip calculator applies standard US norms as a starting point — roughly 15 to 20 percent at sit-down restaurants, more for exceptional service and less where counter service applies. Because it is calculated on the pre-tax amount by convention, though tipping on the post-tax total is also widely accepted, you stay consistent every time.\n\nDiners, groups splitting a check, delivery customers, and travelers checking local custom all reach for a tip calculator to settle up quickly and fairly.",
    example: {
      inputs: { billAmount: "80", tipPercent: "20", numPeople: "4" },
      explanation: "Bill: $80. Tip (20%): $16. Total: $96. Split 4 ways: $24 per person.",
    },
    faqs: [
      {
        question: "How much should I tip at a restaurant?",
        answer: "Standard US restaurant tipping is 15–20% of the pre-tax bill for sit-down restaurants. Fifteen percent is considered acceptable for adequate service; 18–20% is standard for good service; 25% or more shows appreciation for excellent service. For poor service, speak to a manager rather than leaving no tip — servers may not be responsible for kitchen delays. In many other countries (Japan, most of Europe, Australia), tipping is minimal or not customary — locals may even find it offensive. Always research tipping customs when traveling internationally.",
      },
      {
        question: "Should I tip on the pre-tax or post-tax amount?",
        answer: "Traditionally, tips are calculated on the pre-tax amount of the bill. In practice, most people use the total bill amount for convenience, and the difference is usually small. On a $100 pre-tax bill with 8% sales tax ($108 total), a 20% tip is $20 on pre-tax or $21.60 on post-tax — a $1.60 difference. Either approach is socially acceptable. Some restaurant receipts now show 'suggested tip' amounts calculated on the total including tax, making post-tax tipping the de facto standard in many areas.",
      },
      {
        question: "Is it rude to use a tip calculator?",
        answer: "Not at all — using a tip calculator is entirely appropriate and shows care in calculating fairly. Smartphones and restaurant receipt calculators are commonly used. It's far better to use a calculator and tip correctly than to estimate poorly. In a group, using a calculator helps ensure the tip and bill split are accurate, preventing awkward under-tipping or over-calculation. Servers appreciate when customers tip correctly rather than rounding down and leaving less than intended.",
      },
      {
        question: "When should I tip on services other than restaurants?",
        answer: "General US tipping guidelines: Hair/nail salon services: 15–20%. Hotel housekeeping: $2–5 per night, left daily (different staff may clean each day). Bellhops: $1–2 per bag. Taxi/rideshare: 15–20%. Food delivery: 10–15% or $3–5 minimum (delivery workers depend on tips). Movers: $20–50 per mover for a half day, more for longer. Tattoo artists: 15–20%. Personal trainers: optional, $10–50 for regular sessions, more at the holidays. Counter service (coffee, fast food): optional, $0.50–$1 is appreciated but not expected.",
      },
      {
        question: "What is the quick tip calculation method?",
        answer: "For 20% tip: move the decimal one place left (divide by 10 for 10%) then double it. $45 × 10% = $4.50 × 2 = $9.00 tip for 20%. For 15% tip: calculate 10% (move decimal), then add half. $45 × 10% = $4.50 + $2.25 = $6.75 for 15%. For 18%: 20% tip minus 10% of the tip amount. $9.00 − $0.90 = $8.10. Alternatively, double the sales tax if it's approximately 8–9% to get a quick 16–18% tip estimate.",
      },
    ],
    relatedCalculators: ["split-bill", "percentage", "sales-tax"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "split-bill",
    slug: "split-bill-calculator",
    category: "Everyday Life",
    categorySlug: "everyday",
    title: "Split Bill Calculator",
    shortDescription: "Evenly split a restaurant bill or any shared expense among any number of people, including tip.",
    seoTitle: "Split Bill Calculator — Divide Bill & Tip Between Friends",
    metaDescription: "Split any bill evenly between any number of people including tip. Calculate per person cost instantly. Free online bill splitting calculator.",
    primaryKeyword: "split bill calculator",
    secondaryKeywords: ["how to split a bill", "bill splitting calculator", "divide bill calculator", "group dinner calculator"],
    fields: [
      {
        id: "totalBill",
        label: "Total Bill ($)",
        type: "number",
        placeholder: "e.g. 120",
        unit: "$",
        required: true,
        helpText: "Total before tip",
      },
      {
        id: "numPeople",
        label: "Number of People",
        type: "number",
        placeholder: "e.g. 4",
        min: 1,
        required: true,
      },
      {
        id: "tipPercent",
        label: "Tip Percentage (%)",
        type: "number",
        placeholder: "e.g. 18",
        defaultValue: 18,
        unit: "%",
        required: false,
      },
    ],
    results: [
      { id: "tipAmount", label: "Total Tip", format: "currency", decimals: 2, isPrimary: false },
      { id: "totalWithTip", label: "Total with Tip", format: "currency", decimals: 2, isPrimary: false },
      { id: "perPerson", label: "Per Person", format: "currency", decimals: 2, isPrimary: true },
      { id: "tipPerPerson", label: "Tip Per Person", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "Total with tip = Bill × (1 + Tip%/100); Per person = Total / Number of people",
    formulaExplanation: "Multiplying the bill by one plus the tip rate rolls the food cost and gratuity into a single grand total, so no one forgets to chip in for the tip. Dividing that total by the number of diners works because an even split assumes each person shared the experience equally, spreading every dollar the same way. When the result does not land on a whole cent, one person absorbs the small remainder so the payments still add up exactly.",
    formulaSource: "Standard bill-splitting arithmetic",
    explanation: "A split bill calculator divides a shared check — plus tip — evenly across any number of people, giving each person's exact contribution in one step. Splitting a restaurant bill is one of the most common everyday math tasks, and it is surprisingly easy to get wrong once gratuity is added and the total no longer divides into clean amounts. A dedicated split bill calculator removes that friction so nobody underpays and the organizer is not left covering the gap.\n\nThe approach is deliberate about order of operations: it adds the tip to the bill first, then divides the grand total by the number of diners, which guarantees everyone contributes proportionally to both the food and the gratuity. Splitting evenly is fairest when people ordered similar items; for very unequal orders, an itemized or proportional split is more appropriate, and many large restaurants already add an automatic gratuity for parties of six or more, so check the receipt before adding another tip.\n\nFriends settling a group dinner, roommates sharing household costs, and colleagues covering a team lunch all use a split bill calculator to reach a fair, penny-accurate answer in seconds rather than arguing over receipts.",
    example: {
      inputs: { totalBill: "120", numPeople: "4", tipPercent: "20" },
      explanation: "Bill: $120. Tip (20%): $24. Total: $144. Split 4 ways: $36 per person, of which $6 is tip and $30 is food/drinks.",
    },
    faqs: [
      {
        question: "How do I split a bill when people ordered different amounts?",
        answer: "For equal splits to be fair, people should have ordered roughly similar amounts. When there are significant differences, options include: (1) Itemized split — each person pays for exactly what they ordered plus their share of shared items and the same tip percentage. This is most fair but requires a detailed review of the receipt. (2) Proportional split — each person pays a percentage of the total based on their subtotal. Apps like Splitwise, Tab, or Venmo make this easier by letting people log their orders. (3) Negotiate among the group — the person who ordered the most might volunteer to pay more.",
      },
      {
        question: "Should tip be included before or after splitting?",
        answer: "Always calculate the tip first, then split. Calculate: Total = Bill + (Bill × Tip%). Then: Per Person = Total / Number of People. This ensures everyone contributes to the tip proportionally. The error to avoid: splitting the pre-tip bill first, then each person calculating their own tip — this often leads to underestimation. Our calculator handles the correct order automatically: tip is added to the total before dividing by the number of people.",
      },
      {
        question: "What if the per-person amount doesn't divide evenly?",
        answer: "When the total doesn't divide evenly into whole cents, rounding causes a discrepancy (e.g., $144.37 / 4 = $36.0925, so three people pay $36.09 and one pays $36.10). The standard approach: everyone pays the rounded-down amount, and whoever has the largest remaining amount (or whoever offers) pays one cent more. For cash payments, have everyone put in their share and whoever organized the payment handles any small remainder. Most peer-payment apps (Venmo, Zelle) handle exact amounts including cents, making this trivial.",
      },
      {
        question: "How do I handle someone who doesn't drink alcohol?",
        answer: "Non-drinkers often feel uncomfortable with equal splitting when alcohol significantly inflates the bill. Fair approaches: Calculate food vs. drinks separately — food is split equally; drinks are paid by those who ordered them. Alternatively, teetotalers pay their proportional share based on their personal subtotal, while drinkers split the remaining amount. Many groups pre-agree on this before ordering to avoid awkwardness at payment time. The person who organized the dinner can facilitate by saying upfront 'We'll split evenly' or 'We'll each pay our own drinks.'",
      },
      {
        question: "What apps make splitting bills easier?",
        answer: "Several apps specialize in bill splitting and shared expenses: Splitwise (most popular for ongoing group expenses and tracking IOUs), Tab (photograph and split a receipt by item), Venmo and Cash App (easy payment, but you still need to calculate splits), PayPal (splits requests among multiple people), Zelle (bank-to-bank transfers). For in-person restaurant splitting, many restaurants accept split payment on multiple cards — simply ask to split the bill when you're ready to pay, specifying how you want it divided. Using our calculator first gives you the exact per-person amount to request.",
      },
    ],
    relatedCalculators: ["tip", "percentage", "discount"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "discount",
    slug: "discount-calculator",
    category: "Everyday Life",
    categorySlug: "everyday",
    title: "Discount Calculator",
    shortDescription: "Calculate the sale price after a percentage or fixed discount. See your savings instantly.",
    seoTitle: "Discount Calculator — Sale Price After Discount",
    metaDescription: "Calculate the final price after a percentage or dollar discount. See how much you save instantly. Free online discount and sale price calculator.",
    primaryKeyword: "discount calculator",
    secondaryKeywords: ["sale price calculator", "percent off calculator", "how much is 20% off", "discount percentage calculator"],
    fields: [
      {
        id: "originalPrice",
        label: "Original Price ($)",
        type: "number",
        placeholder: "e.g. 79.99",
        unit: "$",
        required: true,
      },
      {
        id: "discountPercent",
        label: "Discount Percentage (%)",
        type: "number",
        placeholder: "e.g. 30",
        unit: "%",
        defaultValue: 0,
        required: false,
        helpText: "Enter percentage off (e.g. 30 for 30% off)",
      },
      {
        id: "discountAmount",
        label: "OR Discount Amount ($)",
        type: "number",
        placeholder: "e.g. 20",
        unit: "$",
        defaultValue: 0,
        required: false,
        helpText: "Enter a fixed dollar discount instead of a percentage",
      },
    ],
    results: [
      { id: "finalPrice", label: "Final Price", format: "currency", decimals: 2, isPrimary: true },
      { id: "savings", label: "You Save", format: "currency", decimals: 2, isPrimary: false },
      { id: "discountPct", label: "Discount Percentage", format: "percentage", decimals: 1, isPrimary: false },
    ],
    formula: "Sale Price = Original Price × (1 − Discount%) ; Savings = Original − Final",
    formulaExplanation: "Subtracting the discount rate from one leaves the fraction of the price you still pay, so multiplying the original price by that fraction lands directly on the sale price without a separate subtraction step. A fixed dollar discount is simpler still — it comes straight off the price — but it represents a different share of a cheap item than an expensive one, which is why the percentage method is applied first when both are supplied.",
    formulaSource: "Standard percentage discount",
    explanation: "Discount calculators are essential for smart shopping. Whether you're looking at a '30% off' sale, a '$20 off coupon,' or trying to figure out if a deal is actually a deal, this calculator shows you the exact final price and how much you're saving.\n\nRetailers use percentage discounts most often because they scale with the original price and feel larger. A '30% off' sale on a $300 item saves $90 — but on a $30 item, that's only $9. Fixed dollar discounts ($20 off) work differently: they're a better deal on cheaper items (20% off a $100 item = $20) and a smaller deal on expensive items (4% off a $500 item = $20).\n\nWhen comparing deals, calculate the final price — not just the discount amount. A 50% off item from an inflated original price may not be cheaper than a 10% off from a fair retail price. Always compare final prices, not discount percentages.",
    example: {
      inputs: { originalPrice: "79.99", discountPercent: "25", discountAmount: "0" },
      explanation: "25% off $79.99: Savings = $79.99 × 0.25 = $20.00. Final price = $79.99 − $20.00 = $59.99. The sale price rounds to $59.99.",
    },
    faqs: [
      {
        question: "How do I calculate a percentage off in my head?",
        answer: "For 10% off: move the decimal point one place left. $85 × 10% = $8.50 off. For 20% off: double the 10% amount. $8.50 × 2 = $17 off, so $85 − $17 = $68. For 25% off: divide by 4. $80 ÷ 4 = $20 off, so $60 final price. For 50% off: divide by 2. For 30% off: 3 × 10%. For 15% off: 10% + half of 10%. For 5% off: half of 10%. Combining these building blocks lets you calculate most common discounts mentally.",
      },
      {
        question: "How do I find the original price if I know the sale price and discount?",
        answer: "Rearrange the discount formula: Original = Sale Price / (1 − Discount%/100). For example, a $70 item is already marked as 30% off. Original price = $70 / (1 − 0.30) = $70 / 0.70 = $100. This calculation is useful when a sale price is shown without the original, or when you want to verify that the 'original price' a retailer shows was legitimate and not inflated just to make the discount look bigger.",
      },
      {
        question: "How do stacked discounts work?",
        answer: "Stacked discounts (multiple discounts applied sequentially) do NOT simply add together. A 20% off followed by an additional 10% off is NOT 30% off. It's: first reduce by 20%, then reduce the result by 10%. Example: $100 → 20% off = $80 → 10% off = $72. The combined effective discount is 28%, not 30%. Formula for two stacked discounts: Effective% = 1 − (1 − d1)(1 − d2). This is why a '20% off + extra 10% off' sale is slightly less valuable than a straight 30% off sale, even though it sounds the same.",
      },
      {
        question: "Are sale prices always actually savings?",
        answer: "Not always. Retailers sometimes inflate the 'original price' to make the discount appear larger — a practice called price anchoring. Red flags: the item has been at the 'sale' price for months; the 'original' price is far above what any retailer charges; the item appears at the same 'sale' price across multiple retailers. Browser extensions like Honey, Capital One Shopping, and CamelCamelCamel (for Amazon) track price history so you can verify whether a 'sale' price is genuinely lower than the historical average. Seasonal sales (Black Friday, end-of-season clearance) typically offer real discounts.",
      },
      {
        question: "How do I calculate the discount percentage if I know original and sale prices?",
        answer: "Discount% = (Original − Sale Price) / Original × 100. For example, an item originally $120, on sale for $84: Discount% = ($120 − $84) / $120 × 100 = $36 / $120 × 100 = 30% off. This is useful when a tag shows both prices but not the percentage, or when comparing discounts across different items. Note that the absolute savings ($36) and the percentage (30%) tell different stories — a $36 savings on a $120 item vs. a $36 savings on a $1,200 item represent very different discount levels (30% vs. 3%).",
      },
    ],
    relatedCalculators: ["percentage", "sales-tax", "tip"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "sales-tax",
    slug: "sales-tax-calculator",
    category: "Everyday Life",
    categorySlug: "everyday",
    title: "Sales Tax Calculator",
    shortDescription: "Calculate the sales tax amount and total price including tax for any purchase.",
    seoTitle: "Sales Tax Calculator — Price Including Tax",
    metaDescription: "Calculate sales tax and total price with tax for any purchase. Works for any tax rate. Free online sales tax calculator with instant results.",
    primaryKeyword: "sales tax calculator",
    secondaryKeywords: ["tax calculator", "how to calculate sales tax", "price plus tax", "total price with tax"],
    sensitivity: "tax",
    fields: [
      {
        id: "price",
        label: "Price Before Tax ($)",
        type: "number",
        placeholder: "e.g. 99.99",
        unit: "$",
        required: true,
      },
      {
        id: "taxRate",
        label: "Sales Tax Rate (%)",
        type: "number",
        placeholder: "e.g. 8.5",
        unit: "%",
        required: true,
        helpText: "Find your rate at your state/local tax authority. US rates typically range from 0% to 11%.",
      },
    ],
    results: [
      { id: "taxAmount", label: "Sales Tax", format: "currency", decimals: 2, isPrimary: false },
      { id: "totalPrice", label: "Total with Tax", format: "currency", decimals: 2, isPrimary: true },
      { id: "reverseBase", label: "Pre-tax Price (if total is entered above)", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "Tax = Price × (Tax Rate / 100); Total = Price + Tax; Pre-tax = Total / (1 + Tax Rate / 100)",
    formulaExplanation: "Multiplying the price by the tax rate over 100 converts the government's percentage into the dollars added at checkout, and appending that amount to the price gives the total you hand over. The reverse formula divides the tax-inclusive total by one plus the rate because the total already contains both the base price and its tax; subtracting a flat percentage of the total would overshoot and understate the true pre-tax amount.",
    formulaSource: "Standard sales tax calculation",
    explanation: "A sales tax calculator adds the correct consumption tax to a purchase, showing both the tax amount and the final price you will actually pay at the register. Sales tax matters because, unlike annual income tax, it is applied transaction by transaction, and the rate you owe depends entirely on where you are standing — combined state and local rates in the United States range from zero to well above ten percent. Knowing the exact figure helps with budgeting, expense reporting, and checking that a receipt was rung up correctly.\n\nThis sales tax calculator works in two directions. Forward, it turns a pre-tax price into a tax-inclusive total by multiplying the price by the tax rate and adding it on. In reverse, it recovers the pre-tax price from a tax-included total by dividing rather than subtracting, which is the only way to get an accurate base amount for bookkeeping.\n\nShoppers comparing out-of-state prices, freelancers logging deductible expenses, and small business owners quoting tax-inclusive prices all rely on a sales tax calculator to avoid the rounding mistakes that come from doing percentage math in their heads.",
    example: {
      inputs: { price: "100", taxRate: "8.5" },
      explanation: "$100 purchase at 8.5% sales tax: Tax = $100 × 0.085 = $8.50. Total = $108.50. Reverse: if you spent $108.50 total at 8.5% tax, the pre-tax price was $108.50 / 1.085 = $100.00.",
    },
    faqs: [
      {
        question: "What is the sales tax rate in my state?",
        answer: "Sales tax rates vary by state and locality. States with no statewide sales tax: Oregon, Montana, New Hampshire, Delaware, Alaska. Other notable rates (statewide only, local taxes may add more): California 7.25%, Tennessee 7%, Texas 6.25%, Washington 6.5%, New York 4% (NYC adds 4.5% city tax = 8.875% combined), Colorado 2.9%. Combined state + local rates can reach 9–11%+ in some cities. For the precise rate at your specific address, check your state's Department of Revenue website or use the Sales Tax Institute's lookup tool.",
      },
      {
        question: "What items are exempt from sales tax?",
        answer: "Sales tax exemptions vary by state, but common exemptions include: groceries (fully exempt in many states, partially exempt in others — e.g., prepared food is often taxed but grocery staples aren't), prescription medications (exempt in most states), non-prescription medications (varies), clothing (exempt in some states like Pennsylvania and Minnesota, and during back-to-school tax holidays), manufacturing equipment and inputs, agricultural supplies, and purchases by nonprofits and government entities. Some states have periodic 'tax holidays' for specific items like school supplies, energy-efficient appliances, or guns.",
      },
      {
        question: "How do I calculate sales tax in reverse (finding price before tax)?",
        answer: "To find the pre-tax price when you know the total-after-tax price: Pre-tax Price = Total Price / (1 + Tax Rate/100). For example, if you paid $54.00 and the tax rate was 8%: Pre-tax = $54 / 1.08 = $50. This is different from simply subtracting 8% from the total ($54 × 0.08 = $4.32; $54 − $4.32 = $49.68 — incorrect). The division method gives the correct pre-tax amount. Our calculator shows this reverse calculation for any inputs entered.",
      },
      {
        question: "Do I pay sales tax on online purchases?",
        answer: "Yes, in most cases. Since the 2018 Supreme Court ruling in South Dakota v. Wayfair, online retailers are required to collect sales tax in states where they have 'economic nexus' (typically $100,000 in annual sales or 200+ transactions). Most major online retailers (Amazon, Walmart, Target, etc.) now collect sales tax in all states that have it. You owe 'use tax' on purchases where the seller didn't collect sales tax — effectively the same rate as sales tax, self-reported on your state income tax return, though compliance is very low in practice.",
      },
      {
        question: "Is sales tax calculated before or after discounts?",
        answer: "Sales tax is generally calculated on the final selling price after discounts are applied. If an item is $100 with a $20 coupon, you pay sales tax on $80 (the discounted price), not $100. However, this rule has nuances: manufacturer rebates paid after the sale may not reduce the taxable amount in some states; bundled product deals may have complex tax treatment; promotional pricing vs. coupons may be treated differently. For most retail purchases with standard discounts, you safely pay tax only on the amount you actually pay before tax.",
      },
    ],
    relatedCalculators: ["discount", "tip", "percentage"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "unit-price",
    slug: "unit-price-calculator",
    category: "Everyday Life",
    categorySlug: "everyday",
    title: "Unit Price Calculator",
    shortDescription: "Compare the cost per unit of two products to find the better deal.",
    seoTitle: "Unit Price Calculator — Compare Cost Per Unit of Products",
    metaDescription: "Compare cost per unit between two products to find the better value. Works for any unit: per oz, per count, per liter. Free online unit price comparison.",
    primaryKeyword: "unit price calculator",
    secondaryKeywords: ["price per unit calculator", "cost per unit", "which is cheaper per unit", "value comparison calculator"],
    fields: [
      {
        id: "price1",
        label: "Product A Price ($)",
        type: "number",
        placeholder: "e.g. 3.99",
        unit: "$",
        required: true,
      },
      {
        id: "quantity1",
        label: "Product A Quantity",
        type: "number",
        placeholder: "e.g. 16",
        required: true,
        helpText: "Number of units, ounces, count, etc.",
      },
      {
        id: "price2",
        label: "Product B Price ($)",
        type: "number",
        placeholder: "e.g. 5.49",
        unit: "$",
        required: true,
      },
      {
        id: "quantity2",
        label: "Product B Quantity",
        type: "number",
        placeholder: "e.g. 24",
        required: true,
      },
    ],
    results: [
      { id: "unitPrice1", label: "Product A: Cost per Unit", format: "currency", decimals: 4, isPrimary: false },
      { id: "unitPrice2", label: "Product B: Cost per Unit", format: "currency", decimals: 4, isPrimary: false },
      { id: "savings", label: "Savings per Unit (Better Deal)", format: "currency", decimals: 4, isPrimary: false },
      { id: "betterDeal", label: "Better Value", format: "text", isPrimary: true },
    ],
    formula: "Unit Price = Total Price / Quantity; Better Deal = lower unit price wins",
    formulaExplanation: "Dividing a package's total price by the quantity it contains reduces every option to the same denominator — the cost of a single ounce, item, or liter — so packages of different sizes become directly comparable. Because the unit is identical on both sides, the product with the lower figure is genuinely cheaper per unit rather than merely cheaper in total, which is why comparing unit prices, not sticker prices, reveals the better value.",
    formulaSource: "Standard unit-price comparison",
    explanation: "Unit price comparison is one of the most powerful tools for smarter grocery and retail shopping. Stores are required by law in many jurisdictions to display unit prices on shelf labels, but comparing them across different sizes and brands can still be confusing.\n\nThe unit price calculator removes the complexity: enter the price and quantity for two products, and it instantly tells you which is the better value per unit (per ounce, per count, per liter, etc.).\n\nLarger sizes are often (but not always) cheaper per unit — this is the rationale behind 'buy in bulk.' However, this isn't always true. Store brand vs. name brand at the same size, or a product on sale in one size but not another, may make the smaller size cheaper per unit. Always verify with the calculator.\n\nImportant caveat: unit price only measures cost efficiency. Consider whether you'll actually use the larger quantity before it expires, and whether the quality of the cheaper option meets your standards.",
    example: {
      inputs: { price1: "3.99", quantity1: "16", price2: "5.49", quantity2: "24" },
      explanation: "Product A: $3.99 / 16 oz = $0.249/oz. Product B: $5.49 / 24 oz = $0.229/oz. Product B is cheaper per ounce — despite costing more total, it provides 8% better value per unit.",
    },
    faqs: [
      {
        question: "What does unit price mean?",
        answer: "Unit price is the cost of one standard unit of a product — per ounce, per liter, per item, per pound, etc. It lets you compare the cost of differently sized packages on an apples-to-apples basis. Unit pricing is required by law in many US states and countries — look for the small number on grocery store shelf labels (often printed in smaller text below the larger retail price). Federal law doesn't require it nationwide, but many retailers provide it voluntarily. The unit should be the same when comparing (both per ounce, or both per count, etc.).",
      },
      {
        question: "Is the bigger size always cheaper per unit?",
        answer: "No — and this surprises many shoppers. While bulk buying usually saves money per unit, exceptions are common. Sales on smaller sizes can make them cheaper per unit. Store brands in smaller sizes sometimes undercut name brands in larger sizes. Unit pricing for some products (especially at warehouse clubs) can actually be higher than grocery stores on sale. Seasonal promotions, coupons, and buy-one-get-one deals can flip unit economics. Always check with a calculator rather than assuming larger = better value, especially when one size is on sale.",
      },
      {
        question: "What about products that aren't the same quality?",
        answer: "Unit price only measures cost per unit of quantity — it doesn't account for quality differences. A cheaper store brand may have a lower unit price but different ingredients, taste, or effectiveness. For exactly equivalent products (same brand, same product, different sizes), unit price is definitive. For different brands or quality tiers, unit price is one input in your decision, not the final answer. Some products where quality differences matter most: medications (active ingredient concentration matters more than unit price), food (nutritional content matters), and tools (durability affects total cost of ownership).",
      },
      {
        question: "How do I compare products measured in different units?",
        answer: "First, convert to a common unit. For example, comparing a 1-liter bottle to a 33.8 fl oz bottle (both are 1 liter — 33.8 oz ≈ 1 L, so they're equivalent). For weight vs. fluid measurement, conversion may not be directly comparable (a pound of cereal isn't directly comparable to a liter). Common conversions: 1 pound = 16 ounces; 1 kilogram = 1,000 grams; 1 liter = 33.814 fluid ounces; 1 gallon = 128 fluid ounces. Once all quantities are in the same unit, enter them and compare unit prices.",
      },
      {
        question: "Is buying in bulk always the smart financial choice?",
        answer: "Not necessarily. Bulk buying is financially smart when: you'll use the product before it expires; you have storage space; the per-unit savings are meaningful; your budget can absorb the upfront cost. Bulk buying backfires when: food spoils before you use it (negating savings and adding waste); you impulse-buy large quantities of items you don't usually need; the cash tied up in bulk inventory has an opportunity cost; you're paying for a warehouse club membership that costs more than you save. The environmental cost (packaging waste per unit, transportation) also matters to many consumers. Calculate the unit price, then consider usage rate and realistic consumption.",
      },
    ],
    relatedCalculators: ["discount", "percentage", "sales-tax"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
];
