import type { CalculatorDefinition } from "../types";

export const financeExtraCalculators: CalculatorDefinition[] = [
  {
    id: "loan",
    slug: "loan-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Loan Calculator",
    shortDescription: "Estimate monthly payments on any loan.",
    seoTitle: "Loan Calculator — Free Monthly Payment Estimator",
    metaDescription:
      "Free loan calculator. Estimate the monthly payment, total interest and total cost of any personal, auto or general loan.",
    primaryKeyword: "loan calculator",
    secondaryKeywords: ["personal loan calculator", "auto loan calculator", "monthly loan payment"],
    fields: [
      { id: "amount", label: "Loan amount", type: "number", unit: "$", placeholder: "20000", required: true, span: 1, min: 0 },
      { id: "rate", label: "Interest rate", type: "number", unit: "%", placeholder: "8", required: true, span: 1, min: 0, step: 0.01 },
      { id: "term", label: "Loan term", type: "number", unit: "years", placeholder: "5", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "monthlyPayment", label: "Monthly payment", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "totalInterest", label: "Total interest", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "totalPaid", label: "Total of payments", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "M = P × r ÷ (1 − (1 + r)^−n), r = annual rate ÷ 12, n = years × 12",
    explanation:
      "Your monthly loan payment is the fixed sum that repays a borrowed amount in equal installments over a set term, with each payment covering interest on the balance still owed plus a slice of principal. Seeing that figure before you sign matters because it tells you whether the repayment fits your monthly budget and reveals the true cost of borrowing once interest is stacked up over the years. This loan calculator applies the standard amortization formula, the method every bank and credit union uses, so the schedule is identical to what a lender will quote. Amortization is used because it produces a level payment that keeps interest and principal balanced from the first month to the last, retiring the debt exactly on schedule. Stretching the term with a loan calculator lowers each monthly payment but raises the total interest, since the balance is carried longer, while a shorter term does the reverse. Borrowers use a loan calculator to shop for personal, auto and consolidation loans, compare offers with different rates and terms, and decide how large a payment they can comfortably absorb. The result assumes a fixed rate and no fees, so add any origination charges separately to gauge the full cost.",
    formulaExplanation:
      "This is the present value of an annuity rearranged to solve for the payment. P is the amount borrowed, r the monthly interest rate and n the number of months. Dividing P × r by (1 − (1 + r)^−n) spreads the principal across all n payments while charging interest each month on the balance that remains. Because the balance shrinks with every payment, a constant amount keeps the loan on track to reach zero exactly at term.",
    example: {
      inputs: { amount: 20000, rate: 8, term: 5 },
      explanation: "$20,000 at 8% over 5 years (60 payments) is about $405.53 per month, roughly $4,332 total interest.",
    },
    faqs: [
      { question: "Can I use this for a car loan?", answer: "Yes. Any fixed-rate installment loan — auto, personal, student refinance or debt consolidation — repays on the same amortization math, so the payment this tool returns matches what a lender will quote. For vehicles, remember the sticker figure often excludes tax, title, registration and any dealer add-ons rolled into the financing. Enter the actual amount financed after your down payment and trade-in to get an accurate monthly figure." },
      { question: "How can I lower my monthly payment?", answer: "Three levers move it: borrow less, secure a lower interest rate, or extend the term. A bigger down payment shrinks the principal directly. A stronger credit score or a shorter shopping window earns a better rate. Lengthening the term spreads the balance over more months, which cuts the payment but increases the total interest you pay, so weigh the monthly relief against the lifetime cost." },
      { question: "What is the difference between interest rate and APR?", answer: "The interest rate is the cost of borrowing the principal alone. The APR bundles that rate together with mandatory fees — origination charges, points and some closing costs — into a single yearly percentage, so it is usually higher. Because APR reflects the full cost of the loan, it is the fairer number for comparing two offers. This calculator uses the interest rate, so add fees separately." },
      { question: "Is total interest included in the total of payments?", answer: "Yes. The total of payments is simply the monthly payment multiplied by the number of months, and it equals the amount you borrowed plus all the interest charged over the life of the loan. Subtracting the original loan amount from that total gives you the interest figure shown separately. It is the clearest way to see how much borrowing actually costs beyond the sum you received." },
      { question: "Does paying extra each month help?", answer: "Significantly. Any amount above the scheduled payment goes straight to principal, shrinking the balance that future interest is charged on. Because interest is front-loaded, extra payments made early in the term save the most. Even a modest recurring overpayment can cut months off the schedule and hundreds or thousands in interest. Confirm your lender applies overpayments to principal and charges no prepayment penalty first." },
    ],
    relatedCalculators: ["mortgage-calculator", "simple-interest-calculator", "compound-interest-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "Consumer Financial Protection Bureau (CFPB)",
    sourceUrl: "https://www.consumerfinance.gov/consumer-tools/auto-loans/",
  },
  {
    id: "simple-interest",
    slug: "simple-interest-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Simple Interest Calculator",
    shortDescription: "Calculate simple interest on a principal.",
    seoTitle: "Simple Interest Calculator — Free Online Tool",
    metaDescription:
      "Free simple interest calculator. Find the interest and total amount from principal, rate and time using the simple interest formula.",
    primaryKeyword: "simple interest calculator",
    secondaryKeywords: ["simple interest formula", "interest calculator", "principal interest"],
    fields: [
      { id: "principal", label: "Principal", type: "number", unit: "$", placeholder: "5000", required: true, span: 1, min: 0 },
      { id: "rate", label: "Annual rate", type: "number", unit: "%", placeholder: "5", required: true, span: 1, min: 0, step: 0.01 },
      { id: "years", label: "Time", type: "number", unit: "years", placeholder: "3", required: true, span: 2, min: 0, step: 0.01 },
    ],
    results: [
      { id: "interest", label: "Interest", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "total", label: "Total amount", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Interest = Principal × Rate × Time ÷ 100",
    explanation:
      "Simple interest is the charge or earning calculated only on the original principal, never on interest that has already accrued, which makes it the most transparent way to price short-term borrowing and lending. The interest figure shown here is the flat cost of using a sum of money for a set time, and the total is that principal plus the interest you owe or earn. Knowing it matters because many everyday arrangements — a short personal loan, a car loan, a promissory note between individuals, or a fixed-term deposit — use exactly this method, so the number is not an approximation but the real amount. This simple interest calculator multiplies the principal by the annual rate and the length of time, the definition used because interest here is strictly proportional to how much you borrow and for how long, with nothing compounding on top. Lenders, students and anyone settling a small private loan use a simple interest calculator to check a quoted figure, plan repayments, or compare a flat-rate offer against a compounding one. Because it never adds interest onto interest, a simple interest calculator will always show a lower balance than a compounding account at the same rate over the same period, a gap that widens as the term lengthens.",
    formulaExplanation:
      "Principal is the sum borrowed or invested, rate is the annual percentage cost, and time is the number of years the money is outstanding. Multiplying the three ties interest directly to size and duration — double the principal or double the time and the interest doubles too. Dividing by 100 converts the rate from a percentage into a decimal. Nothing is compounded, so the principal that earns interest stays fixed throughout the term.",
    example: {
      inputs: { principal: 5000, rate: 5, years: 3 },
      explanation: "5000 × 5 × 3 ÷ 100 = $750 interest, for a total of $5,750.",
    },
    faqs: [
      { question: "What is the difference between simple and compound interest?", answer: "Simple interest is charged only on the original principal, so it accrues at a constant amount each period and grows in a straight line. Compound interest is charged on the principal plus all interest already added, so it accelerates over time. Over a single year the two are nearly identical, but across many years compounding pulls far ahead. Borrowers benefit from simple interest; savers benefit from compounding." },
      { question: "Can the time be a fraction of a year?", answer: "Yes. Enter a decimal to represent partial years — 0.5 for six months, 0.25 for a quarter, or 1.5 for eighteen months. Because simple interest is directly proportional to time, halving the period simply halves the interest. This makes the method convenient for short loans and notes measured in months rather than full years, where compounding would add little and complicate the arithmetic." },
      { question: "Where is simple interest actually used?", answer: "It appears in many short-term and fixed arrangements: some personal and auto loans, promissory notes between individuals, certain bonds and Treasury instruments, retailer financing, and short bank certificates. Late-payment charges are often simple interest too. It is favored wherever transparency matters and the term is short enough that compounding would make a negligible difference, since a flat, predictable charge is easier for both sides to agree on and verify." },
      { question: "How do I calculate the total repayment?", answer: "Add the interest to the original principal. The tool does this for you: it computes principal times rate times time divided by 100 to get the interest, then adds the principal back to show the total amount due at the end of the term. That total is what a borrower repays in full at maturity, or what a fixed-term deposit is worth when it matures, assuming no extra payments along the way." },
      { question: "Does simple interest ever benefit the borrower?", answer: "Yes, compared with a compounding loan at the same rate. Because interest never stacks on prior interest, the balance a borrower owes grows more slowly, so the total cost is lower over an identical term. This is why simple-interest financing is attractive for buyers, and why paying such a loan off early is straightforward — you only owe interest for the days the principal was actually outstanding." },
    ],
    relatedCalculators: ["compound-interest-calculator", "loan-calculator", "savings-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "Standard simple interest formula",
  },
  {
    id: "investment",
    slug: "investment-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Investment Calculator",
    shortDescription: "Project the growth of an investment.",
    seoTitle: "Investment Calculator — Free Growth Projection Tool",
    metaDescription:
      "Free investment calculator. Project the future value of a lump sum plus monthly contributions at an expected annual return.",
    primaryKeyword: "investment calculator",
    secondaryKeywords: ["investment growth calculator", "future value calculator", "portfolio growth"],
    fields: [
      { id: "principal", label: "Initial investment", type: "number", unit: "$", placeholder: "10000", required: true, span: 1, min: 0 },
      { id: "contribution", label: "Monthly contribution", type: "number", unit: "$", placeholder: "300", required: false, span: 1, min: 0 },
      { id: "rate", label: "Annual return", type: "number", unit: "%", placeholder: "8", required: true, span: 1, min: 0, step: 0.01 },
      { id: "years", label: "Years", type: "number", placeholder: "15", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "futureValue", label: "Future value", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "totalContributions", label: "Total invested", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "totalEarnings", label: "Total earnings", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "FV = P(1 + i)^n + PMT × [((1 + i)^n − 1) ÷ i], i = annual ÷ 12",
    explanation:
      "The future value shown here is the projected worth of a portfolio that starts with a lump sum and receives steady monthly contributions, all growing at your expected annual return. It matters because it turns an abstract savings habit into a concrete target: you can see what regular investing might become over a decade or two and how much of that balance is your own money versus compounded earnings. This investment calculator grows the starting amount and each contribution at the monthly equivalent of your annual return, then sums them, because a real portfolio earns returns that are themselves reinvested to earn more — the engine of long-term growth. The future-value formula is used precisely because it captures that reinvestment, treating the initial sum as compounding and the contributions as a monthly annuity added on top. Individual investors, retirement savers and advisors use an investment calculator to set contribution levels, test how sensitive the outcome is to the assumed return, and weigh investing a windfall now against drip-feeding it over time. Since markets rise and fall and no return is guaranteed, treat any figure from an investment calculator as a nominal, pre-tax planning estimate; running a conservative and an optimistic rate brackets the realistic range better than trusting a single projection.",
    formulaExplanation:
      "P is the initial investment and i is the monthly return, so P(1 + i)^n compounds the lump sum across n months. Each monthly contribution PMT is its own small deposit that compounds for the months remaining, and the bracketed annuity term ((1 + i)^n − 1) ÷ i sums all of them. Adding the two gives the total. The exponential factors capture returns being reinvested, which is why later years contribute so much more growth than early ones.",
    example: {
      inputs: { principal: 10000, contribution: 300, rate: 8, years: 15 },
      explanation: "$10,000 plus $300/month at 8% for 15 years grows to about $135,000, of which roughly $71,000 is earnings.",
    },
    faqs: [
      { question: "What annual return should I assume?", answer: "It depends entirely on what you hold. A broad, diversified stock index has historically averaged roughly 7–10% a year before inflation over long periods, while bonds return less and cash barely keeps pace with prices. A balanced portfolio sits in between. Choose a rate that matches your actual mix, and lean conservative for planning. Past performance is not a promise, so test a lower rate to see the downside." },
      { question: "Does this account for inflation and taxes?", answer: "No. The projection is nominal and pre-tax, meaning it shows dollars without adjusting for rising prices or the tax owed on gains. Real purchasing power will be lower — at 3% inflation, money roughly halves in value over 24 years. Taxes further reduce returns unless the money sits in a tax-advantaged account like an IRA or 401(k). Subtract an estimate for both to gauge what the balance will truly buy." },
      { question: "How accurate is an investment calculator?", answer: "The arithmetic is exact, but the result is only as good as the return you assume. Real markets do not deliver a smooth, constant rate; they swing, and the order of good and bad years affects outcomes the model cannot show. Treat the figure as a reasonable midpoint for planning, not a forecast. Running several rates and revisiting the projection as your contributions and markets change keeps it useful." },
      { question: "Is it better to invest a lump sum or contribute monthly?", answer: "Mathematically, investing a lump sum sooner usually wins, because the full amount compounds for longer. In practice, spreading contributions — dollar-cost averaging — reduces the risk of buying everything just before a downturn and suits people paid monthly. This tool models both at once: a starting amount plus ongoing deposits. If you have a windfall and a long horizon, investing more of it early tends to produce the larger balance." },
      { question: "How often are contributions compounded here?", answer: "Monthly. Each contribution is treated as an end-of-month deposit that then compounds at the monthly equivalent of your annual return for the rest of the period. This mirrors how most people actually invest — a fixed amount from each paycheck — and how brokerage and retirement accounts credit growth. Compounding more frequently than monthly changes the result only marginally, so the monthly convention is both realistic and accurate enough for planning." },
    ],
    relatedCalculators: ["compound-interest-calculator", "savings-calculator", "roi-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "U.S. SEC — Investor.gov",
    sourceUrl: "https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator",
  },
  {
    id: "savings",
    slug: "savings-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Savings Calculator",
    shortDescription: "See how regular saving adds up over time.",
    seoTitle: "Savings Calculator — Free Savings Growth Tool",
    metaDescription:
      "Free savings calculator. See how a starting balance plus monthly deposits grow with interest, and how much of the total is interest.",
    primaryKeyword: "savings calculator",
    secondaryKeywords: ["savings goal calculator", "monthly savings", "savings interest calculator"],
    fields: [
      { id: "start", label: "Starting balance", type: "number", unit: "$", placeholder: "1000", required: false, span: 1, min: 0 },
      { id: "monthly", label: "Monthly deposit", type: "number", unit: "$", placeholder: "250", required: true, span: 1, min: 0 },
      { id: "rate", label: "Annual interest rate", type: "number", unit: "%", placeholder: "4", required: true, span: 1, min: 0, step: 0.01 },
      { id: "years", label: "Years", type: "number", placeholder: "10", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "futureValue", label: "Future balance", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "totalDeposited", label: "Total deposited", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "interestEarned", label: "Interest earned", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "FV = start(1 + i)^n + deposit × [((1 + i)^n − 1) ÷ i], i = annual ÷ 12",
    explanation:
      "The future balance shown here is what a savings account is projected to hold once a starting amount and a stream of monthly deposits have grown at the account's interest rate. It matters because it makes the payoff of a consistent saving habit visible: you can see a modest weekly or monthly deposit build into a meaningful sum and watch interest quietly do part of the work. This savings calculator compounds your opening balance and every deposit at the monthly equivalent of the annual rate, then reports both the ending balance and how much of it is interest rather than money you put in. Compounding is the reason for the formula — interest is credited to the balance and then earns interest itself, so the account grows a little faster each period. A savings calculator uses the annuity future-value method because your deposits form a regular series, each one compounding for the time that remains. Households use a savings calculator to plan for an emergency fund, a down payment, a holiday or a wedding, to compare accounts by their real yield, and to decide how much to set aside each month. For a fixed-rate account the figure is dependable; on a variable-rate account the true outcome shifts as the rate changes.",
    formulaExplanation:
      "The starting balance compounds on its own as start × (1 + i)^n, where i is the monthly rate and n the number of months. Each monthly deposit is a separate contribution that compounds for the months left before the end, and the bracketed term ((1 + i)^n − 1) ÷ i totals that whole series at once. Summing the two gives the future balance. The exponents encode interest earning interest, which is why later deposits add less than early ones.",
    example: {
      inputs: { start: 1000, monthly: 250, rate: 4, years: 10 },
      explanation: "$1,000 plus $250/month at 4% for 10 years reaches about $38,300, with roughly $6,800 of interest.",
    },
    faqs: [
      { question: "What interest rate should I enter?", answer: "Use the annual percentage yield, or APY, that your savings account, money market or certificate of deposit actually pays, since APY already reflects how often interest compounds. High-yield online savings accounts typically pay several times more than the national average at big banks, so it pays to shop. Rates on variable accounts move with central bank policy, so revisit the projection when your account's rate changes to keep it realistic." },
      { question: "What is a good amount to save each month?", answer: "A common guideline is to save 20% of take-home pay, split between retirement and shorter-term goals, but the right figure is whatever you can sustain consistently. Start with an amount that does not strain your budget and increase it whenever income rises or a debt is paid off. Because deposits compound, raising your monthly contribution early has an outsized effect on the final balance, more than a higher rate usually does." },
      { question: "How much should I keep in an emergency fund?", answer: "Most planners suggest three to six months of essential living expenses, held in an easily accessible savings account rather than invested, so it is there when you need it. If your income is variable or your job less secure, aim for the higher end. Enter your monthly expense target and a realistic timeline here to see the deposit needed to build it, then automate that transfer so the fund grows without effort." },
      { question: "Are deposits and interest applied monthly?", answer: "Yes. This tool treats each deposit as an end-of-month addition and compounds interest monthly, which matches how most savings accounts operate. That timing means a deposit does not earn interest for the month it arrives, only the months after — a small, realistic detail. If your account credits interest daily, the difference over a year is minor, so the monthly convention remains an accurate basis for planning your goal." },
      { question: "Is the projected balance guaranteed?", answer: "For a fixed-rate account or a certificate of deposit held to maturity, the math is dependable and the balance will land where the tool shows, assuming you make every deposit. For a variable-rate savings account, the outcome shifts whenever the bank changes its rate, so treat that figure as an estimate. Either way, deposits held at an insured bank up to the coverage limit carry no risk of loss to the principal." },
    ],
    relatedCalculators: ["compound-interest-calculator", "investment-calculator", "simple-interest-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "U.S. SEC — Investor.gov",
    sourceUrl: "https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator",
  },
  {
    id: "profit-margin",
    slug: "profit-margin-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Profit Margin Calculator",
    shortDescription: "Find profit, margin and markup from revenue and cost.",
    seoTitle: "Profit Margin Calculator — Free Margin & Markup Tool",
    metaDescription:
      "Free profit margin calculator. Enter revenue and cost to get profit, profit margin percentage and markup percentage.",
    primaryKeyword: "profit margin calculator",
    secondaryKeywords: ["margin calculator", "gross margin calculator", "markup vs margin"],
    fields: [
      { id: "revenue", label: "Revenue (selling price)", type: "number", unit: "$", placeholder: "100", required: true, span: 1, min: 0, step: 0.01 },
      { id: "cost", label: "Cost", type: "number", unit: "$", placeholder: "60", required: true, span: 1, min: 0, step: 0.01 },
    ],
    results: [
      { id: "margin", label: "Profit margin", format: "percentage", decimals: 2, isPrimary: true },
      { id: "profit", label: "Profit", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "markup", label: "Markup", format: "percentage", decimals: 2, isPrimary: false },
    ],
    formula: "Margin = (revenue − cost) ÷ revenue × 100 · Markup = (revenue − cost) ÷ cost × 100",
    explanation:
      "Profit margin is the share of each sale you keep as profit after covering the cost of what you sold, expressed as a percentage of the selling price. That percentage matters more than the raw dollar profit because it reveals how efficiently a product turns revenue into earnings and lets you compare items priced very differently on equal terms. This profit margin calculator takes revenue minus cost to find the profit, divides by revenue to give the margin, and also divides by cost to give the markup — the same profit viewed from two angles. Margin is measured against the selling price because that is the money actually flowing in, which is the convention accountants and investors use when they judge a business's health. Because the selling price is always larger than the cost, the profit margin calculator will show a margin that is lower than the markup for the identical sale, the exact reason the two figures are so often confused. Retailers, wholesalers, freelancers and e-commerce sellers use a profit margin calculator to set prices, screen which products are worth stocking, and benchmark themselves against competitors. Whether the result is a gross or net margin depends on the cost you enter — cost of goods alone gives gross margin, while all-in costs give net.",
    formulaExplanation:
      "Revenue minus cost isolates the profit on the sale. Margin divides that profit by revenue, so it answers how much of every sales dollar you keep, which is why the denominator is the selling price. Markup instead divides the same profit by cost, answering how much you added on top of what you paid. Multiplying by 100 makes each a percentage. The shared numerator over different denominators is why margin is always the smaller figure.",
    example: {
      inputs: { revenue: 100, cost: 60 },
      explanation: "Profit = $40. Margin = 40 ÷ 100 = 40%. Markup = 40 ÷ 60 ≈ 66.7%.",
    },
    faqs: [
      { question: "What is a good profit margin?", answer: "It varies enormously by industry, so judge yours against direct peers rather than a single benchmark. Grocery and other retail often survive on net margins in the low single digits, restaurants sit around 3–9%, while software and consulting can exceed 20% or more. As a rough guide across small businesses, a 10% net margin is considered healthy and 20% is strong. What counts is a margin that covers all costs and still funds growth." },
      { question: "What is the difference between margin and markup?", answer: "Both start from the same profit, but they use different denominators. Margin divides profit by the selling price and tells you what fraction of revenue you keep. Markup divides profit by the cost and tells you how much you added over what you paid. For a profitable sale markup is always the larger percentage. A 40% margin equals a roughly 67% markup on the same item, so never quote one thinking it is the other." },
      { question: "Is this gross or net profit margin?", answer: "That depends on the cost you enter. If you use only the cost of goods sold — materials and direct production — the result is gross margin. If you enter all costs, including overhead, marketing, shipping and fees, you get something closer to net margin. Gross margin shows product-level profitability; net margin shows what the business actually keeps after every expense. Be consistent about which costs you include when comparing products." },
      { question: "How do I increase my profit margin?", answer: "Two levers move it: raise the price or lower the cost. Modest price increases often lift margin more than chasing volume, provided demand holds. On the cost side, negotiate with suppliers, cut waste, or find cheaper inputs without hurting quality. Dropping low-margin products and focusing on high-margin ones also raises the blended figure. Track margin per product, not just overall, so you know which items are actually carrying the business." },
      { question: "Can margin ever be negative?", answer: "Yes. If your cost exceeds the selling price, the profit is negative and so is the margin, meaning you lose money on every unit sold. This happens with clearance items priced below cost, mispriced products, or when unexpected costs erode a thin margin. A negative margin is a clear signal to raise the price, reduce the cost, or discontinue the product, unless you are deliberately selling at a loss to attract customers." },
    ],
    relatedCalculators: ["markup-calculator", "break-even-calculator", "ecommerce-profit-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "Standard financial formula",
  },
  {
    id: "markup",
    slug: "markup-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Markup Calculator",
    shortDescription: "Set a selling price from cost and markup.",
    seoTitle: "Markup Calculator — Free Selling Price Calculator",
    metaDescription:
      "Free markup calculator. Enter a cost and markup percentage to get the selling price, profit and resulting profit margin.",
    primaryKeyword: "markup calculator",
    secondaryKeywords: ["markup percentage", "selling price calculator", "cost plus pricing"],
    fields: [
      { id: "cost", label: "Cost", type: "number", unit: "$", placeholder: "60", required: true, span: 1, min: 0, step: 0.01 },
      { id: "markup", label: "Markup", type: "number", unit: "%", placeholder: "50", required: true, span: 1, min: 0, step: 0.01 },
    ],
    results: [
      { id: "price", label: "Selling price", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "profit", label: "Profit", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "margin", label: "Resulting margin", format: "percentage", decimals: 2, isPrimary: false },
    ],
    formula: "Price = cost × (1 + markup ÷ 100)",
    explanation:
      "Markup is the amount you add on top of what a product costs you to arrive at its selling price, stated as a percentage of that cost. The selling price shown here is the direct result of applying your markup, and it matters because pricing is where a business either builds in enough profit to survive or quietly gives it away. This markup calculator multiplies the cost by one plus your markup percentage to find the price, then reports the dollar profit and the margin that price produces. Markup is expressed against cost because that is the number a seller knows first — you buy or make something for a set amount and decide how much to add — which makes cost-plus pricing the most intuitive method for setting prices quickly. A markup calculator is especially useful for spotting that the resulting margin is always smaller than the markup, since margin is measured against the larger selling price. Retailers, distributors, tradespeople and makers use a markup calculator to price inventory consistently, ensure every item clears its costs, and keep pricing uniform across a catalog. Choosing a markup means balancing your target margin, your overhead, and what the market will actually pay, so the price both covers costs and stays competitive.",
    formulaExplanation:
      "Cost is what you paid, and the markup percentage is how much you add relative to that cost. Dividing markup by 100 converts it to a decimal, and adding 1 keeps the original cost while layering the profit on top, so cost × (1 + markup ÷ 100) returns the full selling price. The profit is the difference between that price and the cost, and dividing profit by the price — not the cost — gives the resulting margin.",
    example: {
      inputs: { cost: 60, markup: 50 },
      explanation: "$60 with a 50% markup sells for $90, a $30 profit and a 33.3% margin.",
    },
    faqs: [
      { question: "How do I choose the right markup?", answer: "Work backward from the margin you need to cover overhead and still profit, then check what competitors charge and what customers will pay. Common retail markups run from 50% on fast-moving goods to well over 100% on specialty or low-volume items; keystone pricing, a 100% markup that doubles cost, is a traditional starting point. Higher markups suit products with strong branding or little competition, while thin markups rely on volume to make money." },
      { question: "Why is the resulting margin lower than the markup?", answer: "Because the two are measured against different bases. Markup is the profit as a percentage of cost, while margin is the same profit as a percentage of the higher selling price. Since the price always exceeds the cost, dividing by the larger number yields a smaller percentage. A 50% markup produces a 33.3% margin; a 100% markup produces a 50% margin. Knowing the pairing prevents you from underpricing by confusing the two." },
      { question: "Is markup the same as profit?", answer: "No. Markup is a percentage that describes how much you add over cost, while profit is the actual dollar amount that addition puts in your pocket. A 50% markup on a $60 item adds $30 of profit and sets the price at $90. The percentage is a pricing rule you apply across products; the dollar profit is the concrete result on a single sale. Both matter, but they answer different questions." },
      { question: "How do I convert a target margin into a markup?", answer: "Divide the desired margin by one minus that margin, both as decimals. To hit a 40% margin, compute 0.40 ÷ 0.60, which is about 0.667, or a 66.7% markup. This is handy when you plan around margin — the profit you keep from revenue — but price using markup applied to cost. This tool does the reverse for you: enter a markup and it displays the margin that results, so you can adjust until the margin matches your goal." },
      { question: "Should the same markup apply to every product?", answer: "Usually not. A flat markup ignores differences in demand, competition, handling costs and turnover. Fast sellers can carry a lower markup because volume makes up for it, while slow-moving or premium items justify a higher one. Perishable or bulky goods may need extra markup to cover waste and storage. Vary the markup by product category so each item earns its keep, and use this tool to check the margin each choice produces." },
    ],
    relatedCalculators: ["profit-margin-calculator", "break-even-calculator", "ecommerce-profit-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "Standard cost-plus pricing formula",
  },
  {
    id: "break-even",
    slug: "break-even-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Break-even Calculator",
    shortDescription: "Find the units you must sell to break even.",
    seoTitle: "Break-even Calculator — Free Break-even Point Tool",
    metaDescription:
      "Free break-even calculator. Find how many units you must sell to cover fixed and variable costs, and the revenue at that point.",
    primaryKeyword: "break-even calculator",
    secondaryKeywords: ["break even point", "break even analysis", "breakeven units"],
    fields: [
      { id: "fixedCosts", label: "Fixed costs", type: "number", unit: "$", placeholder: "10000", required: true, span: 2, min: 0, helpText: "Costs that don't change with volume (rent, salaries)." },
      { id: "pricePerUnit", label: "Price per unit", type: "number", unit: "$", placeholder: "40", required: true, span: 1, min: 0, step: 0.01 },
      { id: "variableCost", label: "Variable cost per unit", type: "number", unit: "$", placeholder: "15", required: true, span: 1, min: 0, step: 0.01 },
    ],
    results: [
      { id: "units", label: "Break-even units", format: "number", decimals: 0, unit: "units", isPrimary: true },
      { id: "revenue", label: "Break-even revenue", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "contribution", label: "Contribution margin / unit", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Break-even units = fixed costs ÷ (price − variable cost)",
    explanation:
      "The break-even point is the sales volume at which total revenue exactly equals total costs, so the business makes neither a profit nor a loss. The units figure shown here is how many you must sell just to cover everything, and it matters because it converts a wall of fixed and variable costs into a single, concrete sales target you can plan and push toward. This break-even calculator subtracts the variable cost per unit from the price to find the contribution margin — the amount each sale contributes toward fixed costs — then divides your fixed costs by that margin. The method works because fixed costs stay flat no matter how much you sell, while each unit chips away at them by its contribution, so once enough units have sold to cover the fixed block, the next sale turns profitable. A break-even calculator underpins cost-volume-profit analysis, the framework businesses use to test pricing, plan production and decide whether a product is viable. Founders, product managers and finance teams reach for a break-even calculator when launching a product, setting a price, or evaluating whether higher fixed costs — new equipment, more staff — can be justified by the extra volume needed. If the price does not exceed the variable cost, no volume ever breaks even and there is no answer.",
    formulaExplanation:
      "Fixed costs are expenses that do not change with volume, and the contribution margin is the price minus the variable cost of one unit — the money each sale frees up after covering its own variable cost. Dividing fixed costs by that per-unit contribution counts how many units are needed to absorb the entire fixed block. If price is at or below variable cost, the contribution is zero or negative, so no number of units can ever cover fixed costs.",
    example: {
      inputs: { fixedCosts: 10000, pricePerUnit: 40, variableCost: 15 },
      explanation: "Contribution is $40 − $15 = $25. $10,000 ÷ $25 = 400 units, or $16,000 in revenue.",
    },
    faqs: [
      { question: "What is the difference between fixed and variable costs?", answer: "Fixed costs stay the same no matter how much you sell — rent, salaries, insurance, software subscriptions and loan payments all fall here. Variable costs rise and fall directly with volume, such as raw materials, packaging, shipping, payment processing fees and hourly production labor. Sorting your costs correctly is essential, because break-even depends on it. Some costs are mixed, like a utility with a base charge plus usage; split those into their fixed and variable parts for accuracy." },
      { question: "What is contribution margin?", answer: "It is the selling price of one unit minus its variable cost — the money each sale contributes toward covering fixed costs and, once those are covered, toward profit. In the example, a $40 price and $15 variable cost leave $25 of contribution per unit. A higher contribution margin means fewer units are needed to break even. It is one of the most useful figures in pricing, because it shows exactly how much each additional sale is worth to the business." },
      { question: "What happens if the price is below variable cost?", answer: "Then every unit sold loses money before fixed costs are even considered, so no sales volume can ever break even. The contribution margin is zero or negative, and the calculator returns no result until the price exceeds the variable cost. If you find yourself here, you must raise the price or cut the variable cost per unit. Selling below variable cost only makes sense briefly as a loss leader to win customers you monetize elsewhere." },
      { question: "How do I calculate a break-even point in revenue?", answer: "Multiply the break-even units by the price per unit, which the tool does for you. In the example, 400 units at $40 gives $16,000 of break-even revenue. Alternatively, divide fixed costs by the contribution margin ratio — the contribution margin divided by the price. The revenue figure is handy when you think in sales dollars rather than unit counts, or when a business sells many products and unit-level tracking is impractical." },
      { question: "How does break-even help set prices?", answer: "It shows the sales target every candidate price implies. Raise the price and the contribution margin grows, so fewer units break even, but demand may soften. Lower the price and you need more volume to cover fixed costs. By testing prices against a realistic sales forecast, you find the level that breaks even at an achievable volume while leaving room for profit. It also reveals when a proposed increase in fixed costs demands an unrealistic jump in sales." },
    ],
    relatedCalculators: ["profit-margin-calculator", "markup-calculator", "revenue-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "Standard break-even (cost-volume-profit) analysis",
  },
];
