import type { CalculatorDefinition } from "../types";

export const financeR4Calculators: CalculatorDefinition[] = [
  {
    id: "debt-to-income",
    slug: "debt-to-income-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Debt-to-Income Ratio Calculator",
    shortDescription: "See what share of your income goes to debt.",
    seoTitle: "Debt-to-Income Ratio Calculator — Free DTI Tool",
    metaDescription:
      "Free debt-to-income calculator. Find your DTI ratio from monthly debt and gross income, and see whether lenders view it as healthy or high.",
    primaryKeyword: "debt to income calculator",
    secondaryKeywords: ["dti calculator", "debt to income ratio", "dti ratio calculator"],
    fields: [
      { id: "monthlyDebt", label: "Total monthly debt payments", type: "number", unit: "$", placeholder: "2000", required: true, span: 1, min: 0 },
      { id: "grossMonthlyIncome", label: "Gross monthly income", type: "number", unit: "$", placeholder: "6000", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "dti", label: "Debt-to-income ratio", format: "percentage", decimals: 1, isPrimary: true },
      { id: "rating", label: "Lender rating", format: "text", isPrimary: false },
    ],
    formula: "DTI = total monthly debt ÷ gross monthly income × 100",
    explanation:
      "Your debt-to-income ratio, or DTI, is the share of your gross monthly income that goes toward paying debts, expressed as a percentage. It matters because it is one of the first numbers a lender checks when you apply for a mortgage, car loan or personal loan: it signals how much room your budget has to take on a new payment. This debt-to-income calculator adds up your recurring monthly debt obligations — mortgage or rent, car loans, student loans, minimum credit card payments and similar — and divides that total by your gross monthly income before tax, then multiplies by 100 to get the percentage. Comparing debt to pre-tax income is the standard the lending industry uses, so the figure here lines up with how underwriters actually assess you. The tool also labels the result: under 36% is generally healthy and leaves comfortable margin, 36% to 43% is manageable but tighter, and above 43% is high and often the ceiling for a qualified mortgage. Borrowers use a DTI calculator to gauge whether they are ready to apply, to see how paying down a balance would improve their standing, and to set a realistic borrowing target. Lower is better: a smaller ratio widens your loan options and typically earns better terms, so if yours is high, reducing debt or raising income before applying can meaningfully change the offers you receive.",
    formulaExplanation:
      "Total monthly debt is the sum of every recurring debt payment you owe in a month, and gross monthly income is what you earn before taxes and deductions. Dividing the two shows what fraction of your income is already committed to debt, and multiplying by 100 states it as a percentage lenders can read at a glance. Gross rather than net income is used because it is the consistent, verifiable figure underwriters rely on, so the ratio matches the one a lender will calculate.",
    example: {
      inputs: { monthlyDebt: 2000, grossMonthlyIncome: 6000 },
      explanation: "$2,000 of monthly debt against $6,000 of gross income is a 33.3% DTI — a healthy ratio that leaves room to borrow.",
    },
    faqs: [
      { question: "What counts as a good debt-to-income ratio?", answer: "Lenders generally view a DTI below 36% as healthy, with the debt leaving comfortable room in your budget. Between 36% and 43% is still workable for many loans but signals a tighter budget. Above 43% is considered high and is often the upper limit for a qualified mortgage. The lower your ratio, the stronger you look to lenders and the better the rates and terms you are likely to be offered, so aim well under 36% where you can." },
      { question: "Which debts are included in the calculation?", answer: "Include recurring monthly obligations: your mortgage or rent, auto loans, student loans, personal loans, minimum credit card payments, and court-ordered payments like child support or alimony. Do not include everyday living costs such as groceries, utilities, insurance premiums or streaming subscriptions, since lenders exclude those from DTI. Enter the sum of your qualifying debt payments so the ratio reflects the same figure an underwriter would use when reviewing your application." },
      { question: "Should I use gross or net income?", answer: "Use gross income — your total pay before taxes, retirement contributions and other deductions. This is deliberate: lenders calculate DTI against gross income because it is a standardized, easily verified figure that they can confirm from pay stubs and tax returns. Using net income would produce a higher, non-comparable ratio that does not match how you will be assessed. Enter your monthly gross pay so the result mirrors the lender's own calculation." },
      { question: "How can I lower my debt-to-income ratio?", answer: "You can reduce it two ways: cut your monthly debt or raise your income. Paying off a small loan entirely removes its whole payment from the numerator, which often helps more than chipping at a large balance. Avoiding new debt before applying keeps the ratio from climbing. On the income side, a raise, a side income or adding a co-borrower's income can lift the denominator. Even a modest improvement can move you into a better lending tier." },
      { question: "Does my DTI affect my credit score?", answer: "Not directly — your credit score does not include your income, so DTI is not a scoring factor. However, the two are related: high balances that push up your DTI also raise your credit utilization, which does affect your score. Lenders look at both separately, using your score to judge repayment history and your DTI to judge capacity to take on more debt. Keeping debt low helps both numbers at once." },
    ],
    relatedCalculators: ["loan-calculator", "mortgage-calculator", "credit-card-payoff-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    sensitivity: "finance",
    formulaSource: "Consumer Financial Protection Bureau",
    sourceUrl: "https://www.consumerfinance.gov/",
  },
  {
    id: "rule-of-72",
    slug: "rule-of-72-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Rule of 72 Calculator",
    shortDescription: "Estimate how long it takes an investment to double.",
    seoTitle: "Rule of 72 Calculator — How Long to Double Your Money",
    metaDescription:
      "Free Rule of 72 calculator. Estimate how many years it takes an investment to double at a given annual rate of return using the classic shortcut.",
    primaryKeyword: "rule of 72 calculator",
    secondaryKeywords: ["doubling time calculator", "how long to double money", "rule of 72"],
    fields: [
      { id: "annualRate", label: "Annual rate of return", type: "number", unit: "%", placeholder: "8", required: true, span: 2, min: 0, step: 0.01 },
    ],
    results: [
      { id: "yearsToDouble", label: "Years to double", format: "number", decimals: 1, unit: "years", isPrimary: true },
    ],
    formula: "Years to double ≈ 72 ÷ annual rate of return",
    explanation:
      "The Rule of 72 is a mental-math shortcut that estimates how many years it takes an investment to double at a steady annual rate of return. It matters because doubling time is an intuitive way to grasp the power of compounding without a spreadsheet: divide 72 by your expected annual return, and the answer is roughly the number of years your money needs to double. This Rule of 72 calculator does exactly that division and shows the result. The number 72 is used because it is close to the mathematically exact figure (about 69.3, from the natural logarithm of 2) yet divides cleanly by many common return rates like 6, 8, 9 and 12, which is why generations of investors have kept it in their heads. Savers and investors use the rule to compare opportunities at a glance — an 8% return doubles money in about nine years, while a 4% return takes roughly eighteen — and to appreciate why even a couple of extra percentage points of return dramatically shortens the wait. It is an approximation, most accurate for rates between about 6% and 10%, and it assumes a constant rate with no withdrawals, so treat it as a quick sanity check rather than a precise projection. For exact figures, use a full compound-interest calculation, but for fast intuition the Rule of 72 is hard to beat.",
    formulaExplanation:
      "Compounding growth is exponential, so the time to double is governed by the natural logarithm of 2 divided by the growth rate. That exact constant is about 69.3, but 72 is used instead because it is close enough and divides evenly by many everyday return rates, making the arithmetic something you can do in your head. Dividing 72 by the annual percentage return gives the approximate number of years for the balance to double, which is why higher returns shrink the doubling time so sharply.",
    example: {
      inputs: { annualRate: 8 },
      explanation: "At an 8% annual return, 72 ÷ 8 = 9, so an investment roughly doubles in about nine years.",
    },
    faqs: [
      { question: "How accurate is the Rule of 72?", answer: "It is a close approximation, most accurate for annual returns between about 6% and 10%. In that band it comes within a fraction of a year of the exact answer. For very low rates it slightly underestimates the time, and for very high rates it overestimates. Some people use 70 or 69.3 for continuous compounding, or 73 for higher rates. For everyday planning the standard 72 gives a reliable quick estimate; use a full compound-interest formula when you need precision." },
      { question: "Why is the number 72 used?", answer: "The mathematically exact constant for doubling time is the natural logarithm of 2, roughly 69.3, divided by the growth rate. But 69.3 is awkward to divide by common return figures. The number 72 is very close to it and divides evenly by 2, 3, 4, 6, 8, 9 and 12 — many of the rates investors actually encounter — so it makes the mental arithmetic clean while staying accurate enough for practical use. That balance of simplicity and precision is why 72 became the convention." },
      { question: "Can I use the Rule of 72 for inflation?", answer: "Yes. Applied to an inflation rate, the rule estimates how long it takes for prices to double and, equivalently, for money to lose half its purchasing power. At 3% inflation, 72 ÷ 3 = 24 years for prices to double. This makes it a handy way to see how inflation quietly erodes savings over time. The same shortcut works for any steady rate of growth or decay, not just investment returns." },
      { question: "Does it account for taxes and fees?", answer: "No. The Rule of 72 works on a single net rate of return, so it only reflects taxes and fees if you plug in an after-tax, after-fee rate. Using a gross return will make the doubling look faster than it really is. To be realistic, subtract expected fund fees and any tax drag from your assumed return before dividing, so the doubling time reflects what actually lands in your account rather than the headline rate." },
      { question: "What return should I assume?", answer: "Use a rate that matches the investment. Broad stock market indexes have historically averaged roughly 7–10% a year before inflation over long periods, bonds considerably less, and cash savings less still. Because the rule assumes a constant rate and real markets fluctuate, lean toward a conservative figure for planning. Remember the result is an estimate of average doubling time, not a guarantee that your money will double on any particular schedule." },
    ],
    relatedCalculators: ["compound-interest-calculator", "investment-calculator", "savings-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Rule of 72 (compound-growth heuristic)",
  },
  {
    id: "savings-goal",
    slug: "savings-goal-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Savings Goal Calculator",
    shortDescription: "Find how long it takes to reach a savings target.",
    seoTitle: "Savings Goal Calculator — Time to Reach Your Target",
    metaDescription:
      "Free savings goal calculator. Find how many months it takes to hit a savings target from your current balance, monthly contribution and interest rate.",
    primaryKeyword: "savings goal calculator",
    secondaryKeywords: ["savings target calculator", "how long to save calculator", "time to reach savings goal"],
    fields: [
      { id: "goalAmount", label: "Savings goal", type: "number", unit: "$", placeholder: "20000", required: true, span: 1, min: 0 },
      { id: "currentSavings", label: "Current savings", type: "number", unit: "$", placeholder: "5000", required: true, span: 1, min: 0 },
      { id: "monthlyContribution", label: "Monthly contribution", type: "number", unit: "$", placeholder: "500", required: true, span: 1, min: 0 },
      { id: "annualRate", label: "Annual interest rate", type: "number", unit: "%", placeholder: "6", required: true, span: 1, min: 0, step: 0.01 },
    ],
    results: [
      { id: "monthsToGoal", label: "Months to reach goal", format: "number", decimals: 0, unit: "months", isPrimary: true },
      { id: "yearsToGoal", label: "Years to reach goal", format: "number", decimals: 1, unit: "years", isPrimary: false },
    ],
    formula: "months = ln((goal × r + P) ÷ (current × r + P)) ÷ ln(1 + r), r = annual rate ÷ 12, P = monthly contribution",
    explanation:
      "The months-to-goal figure shown here is how long it will take to reach a savings target, given what you have saved already, how much you add each month, and the interest your balance earns. It matters because a goal with a timeline is far easier to stay committed to than a vague intention, and seeing the finish line helps you judge whether your current pace is fast enough. This savings goal calculator treats your starting balance as a lump sum that compounds while your monthly deposits form a growing annuity, then solves for the number of months at which the two together first reach your target. Modeling both the balance and the contributions with monthly compounding is the accurate way to do it, because interest earned on money already saved shortens the timeline in a way a simple subtraction would miss. Savers use a goal calculator to plan for a house down payment, an emergency fund, a wedding or a large purchase, and to test how a bigger monthly deposit or a higher-yield account pulls the date closer. If you have already met the goal it returns zero months, and if you contribute nothing and the goal is out of reach it returns no result, a prompt to raise your monthly amount. Because interest rates vary and deposits may not be perfectly regular, treat the result as a well-grounded estimate and revisit it as your situation changes.",
    formulaExplanation:
      "Here r is the monthly interest rate and P is your monthly contribution. Your current savings compound at r while each deposit also compounds, so the balance grows as a lump sum plus an annuity. Setting that combined value equal to the goal and solving for time produces the logarithmic expression shown: ln((goal × r + P) ÷ (current × r + P)) ÷ ln(1 + r). When the rate is zero the math simplifies to the gap between goal and current savings divided by the monthly contribution, since no interest is earned.",
    example: {
      inputs: { goalAmount: 20000, currentSavings: 5000, monthlyContribution: 500, annualRate: 6 },
      explanation: "Starting at $5,000, adding $500 a month at 6%, you reach a $20,000 goal in about 27 months — a little over two years.",
    },
    faqs: [
      { question: "How does the interest rate affect the timeline?", answer: "A higher rate shortens the time to your goal because the interest your balance earns does part of the saving for you. On a short timeline the effect is modest, since there is little time to compound, but over several years a higher-yield account can shave months off the wait. Moving savings to a high-yield account or CD rather than a low-interest one is one of the simplest ways to reach a medium-term goal sooner without contributing a dollar more." },
      { question: "What if I can't contribute the same amount every month?", answer: "The calculator assumes a steady monthly contribution, so irregular saving will make your real timeline differ. If your deposits vary, enter a realistic average of what you can set aside each month to get a reasonable estimate. For months you contribute more — from a bonus or tax refund — you will run ahead of schedule; leaner months put you behind. Re-run the tool with an updated average whenever your regular savings capacity changes." },
      { question: "Should I include my existing savings?", answer: "Yes, enter the amount you have already earmarked for this goal as your current savings. It counts fully toward the target and earns interest from day one, so including it gives an accurate, shorter timeline. Do not include money committed to other purposes, such as your emergency fund or retirement accounts, unless you genuinely intend to use it here. Only the balance you will actually apply to this goal should go in the current savings field." },
      { question: "What happens if my goal is unreachable?", answer: "If you contribute nothing and your current savings plus interest cannot grow to the target — for example a zero contribution at a zero rate — the tool returns no result, signaling that the goal is not reachable on the inputs given. The fix is to raise your monthly contribution, extend your view of the timeline, or seek a higher return. Increase the contribution field until a finite number of months appears to see the minimum pace that reaches your goal." },
      { question: "Is the result before or after inflation?", answer: "It is in nominal terms, meaning it tells you when your balance reaches the dollar figure you entered, without adjusting for rising prices. If your goal is years away, the real-world cost of what you are saving for may climb in the meantime, so a fixed target could fall short of its future purchasing power. For distant goals, consider setting the target a little higher, or revisiting it periodically, to keep pace with inflation." },
    ],
    relatedCalculators: ["savings-calculator", "compound-interest-calculator", "cd-interest-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Future value of an annuity",
  },
  {
    id: "future-value",
    slug: "future-value-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Future Value Calculator",
    shortDescription: "Project what a lump sum grows to over time.",
    seoTitle: "Future Value Calculator — Free Compound Growth Tool",
    metaDescription:
      "Free future value calculator. Project what a present sum grows to at a given rate, term and compounding frequency, plus the total interest earned.",
    primaryKeyword: "future value calculator",
    secondaryKeywords: ["fv calculator", "future value of money", "compound growth calculator"],
    fields: [
      { id: "presentValue", label: "Present value", type: "number", unit: "$", placeholder: "10000", required: true, span: 1, min: 0 },
      { id: "annualRate", label: "Annual interest rate", type: "number", unit: "%", placeholder: "6", required: true, span: 1, min: 0, step: 0.01 },
      { id: "years", label: "Number of years", type: "number", unit: "years", placeholder: "10", required: true, span: 1, min: 0, step: 0.01 },
      { id: "compoundsPerYear", label: "Compounds per year", type: "number", placeholder: "12", required: false, span: 1, min: 1 },
    ],
    results: [
      { id: "futureValue", label: "Future value", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "totalInterest", label: "Total interest earned", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "FV = PV × (1 + r ÷ n)^(n × t), r = annual rate, n = compounds per year, t = years",
    explanation:
      "Future value is what a sum of money you have today will be worth at a point in the future, once it has grown at a given interest rate. It matters because it puts a concrete number on the core idea of the time value of money: a dollar invested now becomes more than a dollar later, and the future value tells you exactly how much more. This future value calculator takes your present sum, applies your annual rate divided across the compounding periods, and raises it over the total number of periods to project the ending balance, then shows the interest earned as the difference. Accounting for compounding frequency matters because interest that compounds monthly grows faster than the same rate compounded annually, since each period's interest starts earning interest itself. Investors and savers use future value to project the worth of a deposit, a CD or a lump-sum investment, to compare accounts with different rates and compounding schedules, and to understand why starting early is so powerful — time is the most influential input in the formula. The projection assumes a single upfront deposit with no further contributions and a constant rate, so it is cleanest for a one-time investment; add regular deposits and you would need an annuity calculation instead. It is a nominal figure before inflation and tax, so treat it as a planning estimate of growth rather than guaranteed spending power.",
    formulaExplanation:
      "PV is your present sum and r is the annual rate as a decimal. Dividing r by n gives the interest applied in each compounding period, and there are n × t such periods over t years. Raising (1 + r ÷ n) to that number of periods compounds the deposit repeatedly, with each period's gain added to the base before the next is calculated. Multiplying by the present value scales it to your actual amount; subtracting the present value isolates the interest earned. More frequent compounding raises the exponent and the result.",
    example: {
      inputs: { presentValue: 10000, annualRate: 6, years: 10, compoundsPerYear: 12 },
      explanation: "$10,000 at 6% compounded monthly for 10 years grows to about $18,194, earning roughly $8,194 in interest.",
    },
    faqs: [
      { question: "What is the time value of money?", answer: "It is the principle that a sum of money is worth more now than the same sum in the future, because money you hold today can be invested to earn a return. Future value is the direct expression of this idea: it quantifies how much a present amount grows to over time. The concept underpins nearly all of finance, from savings and loans to bond pricing and business investment decisions, because it lets you compare cash flows that occur at different points in time on equal footing." },
      { question: "How does compounding frequency change the result?", answer: "The more often interest compounds, the larger the future value, because each compounding event lets already-earned interest start earning interest sooner. At the same nominal rate, monthly compounding beats annual, and daily beats monthly, though the gains shrink as frequency rises. The difference is meaningful over long horizons or large sums. Enter the frequency your account actually uses — many savings accounts compound daily or monthly — so the projection matches how your balance really grows." },
      { question: "Does this include regular contributions?", answer: "No. This calculator projects the growth of a single lump sum deposited today with no further additions. If you plan to add money regularly — say a fixed amount each month — the ending balance would be higher, and you would need a future-value-of-an-annuity calculation that layers those deposits on top. Use this tool for one-time investments like a CD or a lump sum, and a savings or retirement calculator when you are contributing on an ongoing basis." },
      { question: "Is the future value adjusted for inflation?", answer: "No, it is a nominal figure stated in future dollars, not adjusted for rising prices. Because inflation erodes purchasing power, the real value of the result will buy less than the same number of dollars today. At 3% inflation, money loses roughly half its purchasing power over about 24 years. To gauge real growth, subtract your expected inflation rate from the return you enter, which gives a rough inflation-adjusted future value in today's terms." },
      { question: "What interest rate should I enter?", answer: "Enter the annual rate you realistically expect the money to earn. For a savings account or CD, use the quoted APY. For an investment, use a conservative long-run estimate for the asset mix you hold — historically higher for stocks, lower for bonds. Because the result is highly sensitive to the rate over long periods, it is wise to test a range of rates rather than a single optimistic figure, so you understand the spread of possible outcomes." },
    ],
    relatedCalculators: ["present-value-calculator", "compound-interest-calculator", "investment-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Compound interest formula",
  },
  {
    id: "present-value",
    slug: "present-value-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Present Value Calculator",
    shortDescription: "Find what a future sum is worth today.",
    seoTitle: "Present Value Calculator — Free Discounting Tool",
    metaDescription:
      "Free present value calculator. Find what a future amount is worth in today's dollars at a given discount rate, term and compounding frequency.",
    primaryKeyword: "present value calculator",
    secondaryKeywords: ["pv calculator", "present value of money", "discounted value calculator"],
    fields: [
      { id: "futureValue", label: "Future value", type: "number", unit: "$", placeholder: "20000", required: true, span: 1, min: 0 },
      { id: "annualRate", label: "Discount rate", type: "number", unit: "%", placeholder: "6", required: true, span: 1, min: 0, step: 0.01 },
      { id: "years", label: "Number of years", type: "number", unit: "years", placeholder: "10", required: true, span: 1, min: 0, step: 0.01 },
      { id: "compoundsPerYear", label: "Compounds per year", type: "number", placeholder: "12", required: false, span: 1, min: 1 },
    ],
    results: [
      { id: "presentValue", label: "Present value", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
    ],
    formula: "PV = FV ÷ (1 + r ÷ n)^(n × t), r = discount rate, n = compounds per year, t = years",
    explanation:
      "Present value is what a sum of money you expect to receive in the future is worth in today's dollars, once you account for the return that money could otherwise earn. It matters because it is the mirror image of future value and a cornerstone of financial decision-making: to compare a payment due later against cash in hand now, you have to discount the future amount back to the present. This present value calculator takes the future sum, the rate you could earn (the discount rate), the number of years and the compounding frequency, and divides out the growth that would have occurred, leaving the equivalent value today. Discounting is used because a dollar promised in ten years is worth less than a dollar now — you lose the chance to invest it in the meantime — and the discount rate captures that opportunity cost. People use present value to decide whether a future payout, a lump-sum versus installment choice, or an investment's promised return is worth it today, and businesses use it to value cash flows, bonds and projects. A higher discount rate or a longer wait shrinks the present value, because more potential growth is being stripped away. The result assumes a single future amount and a constant rate, so it is cleanest for one payment; a stream of future cash flows would be discounted period by period. Treat the figure as the fair value today of that future money under your assumed rate.",
    formulaExplanation:
      "FV is the future amount and r is the discount rate as a decimal. Dividing r by n gives the rate per compounding period, and n × t is the number of periods over t years. Raising (1 + r ÷ n) to that power is the same growth factor used for future value; here you divide the future sum by it rather than multiply, reversing the compounding to strip out the return the money would have earned. What remains is the amount that, invested today at that rate, would grow into the future value entered.",
    example: {
      inputs: { futureValue: 20000, annualRate: 6, years: 10, compoundsPerYear: 12 },
      explanation: "$20,000 due in 10 years, discounted at 6% compounded monthly, is worth about $10,994 in today's dollars.",
    },
    faqs: [
      { question: "What is a discount rate?", answer: "The discount rate is the annual return you assume you could earn on money if you had it today, used to translate a future amount into present terms. It represents the opportunity cost of waiting. Choosing it is a judgment call: some use the rate on a safe investment, others use their expected investment return or a business's cost of capital. A higher discount rate reflects better alternative uses for the money and produces a lower present value, since more potential growth is being given up." },
      { question: "Why is future money worth less today?", answer: "Because money in hand can be put to work immediately. If you could invest a dollar today and earn a return, then a dollar promised in the future is worth less than that dollar now — you are missing out on the growth in between. There is also uncertainty and inflation to consider, both of which make a future promise less valuable than present cash. Present value quantifies exactly how much less, given the return you could otherwise earn." },
      { question: "When would I use present value?", answer: "It is useful whenever you must compare money available at different times. Common cases include deciding between a lump-sum payout and a series of future payments (as with a lottery or pension), judging whether an investment's future return justifies its price today, or valuing a bond. Businesses use it to evaluate projects by discounting expected future cash flows. Any time you need to know what a future dollar is really worth right now, present value is the tool." },
      { question: "How does the time period affect present value?", answer: "The longer you have to wait for the money, the lower its present value, because the discounting compounds over more periods. A sum due in twenty years is worth far less today than the same sum due in two, at the same rate. This is why long-dated future payments can look surprisingly small in present terms. Lengthening the term in this tool, or raising the discount rate, both push the present value down, sometimes sharply." },
      { question: "Is present value the same as net present value?", answer: "No, though they are related. Present value discounts a single future amount back to today. Net present value, or NPV, applies the same discounting to a whole series of future cash flows — often an investment's costs and returns over several years — and sums them, usually subtracting the initial outlay. NPV is the standard tool for evaluating projects and investments. This calculator handles the single-amount case that underlies the more complex NPV computation." },
    ],
    relatedCalculators: ["future-value-calculator", "compound-interest-calculator", "investment-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Present value (discounting)",
  },
  {
    id: "annuity-payment",
    slug: "annuity-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Annuity Payment Calculator",
    shortDescription: "Find the fixed payment that pays off a principal.",
    seoTitle: "Annuity Calculator — Free Fixed Payment Tool",
    metaDescription:
      "Free annuity calculator. Find the fixed periodic payment that amortizes a principal at a given rate and term, plus total paid and total interest.",
    primaryKeyword: "annuity calculator",
    secondaryKeywords: ["annuity payment calculator", "annuity payout calculator", "amortized payment calculator"],
    fields: [
      { id: "principal", label: "Principal amount", type: "number", unit: "$", placeholder: "100000", required: true, span: 1, min: 0 },
      { id: "annualRate", label: "Annual interest rate", type: "number", unit: "%", placeholder: "6", required: true, span: 1, min: 0, step: 0.01 },
      { id: "years", label: "Term", type: "number", unit: "years", placeholder: "30", required: true, span: 1, min: 0, step: 0.01 },
      { id: "paymentsPerYear", label: "Payments per year", type: "number", placeholder: "12", required: false, span: 1, min: 1 },
    ],
    results: [
      { id: "payment", label: "Payment per period", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "totalPaid", label: "Total paid", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "totalInterest", label: "Total interest", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Payment = P × r ÷ (1 − (1 + r)^−N), r = annual rate ÷ payments per year, N = years × payments per year",
    explanation:
      "The payment shown here is the fixed amount, paid at regular intervals, that fully pays off a principal over a set term at a given interest rate. It matters because this single figure underlies mortgages, car loans, personal loans and structured payouts alike: any time a lump sum is settled through equal periodic payments, this is the math that sets the amount. This annuity payment calculator converts your annual rate to the rate per payment period, counts the total number of payments, and applies the amortization formula to find the payment that exactly zeroes the balance by the end of the term, then reports the total you will pay and how much of that is interest. The formula is the standard used across lending because it correctly balances interest and principal in every payment — early payments are mostly interest, later ones mostly principal — so the balance reaches zero precisely on schedule. Borrowers use it to size a loan payment before committing, to compare terms and rates, and to see the true cost of borrowing in the total-interest figure; retirees and planners use the same math in reverse to see what fixed payout a savings pool can sustain. A longer term lowers each payment but raises total interest, while a higher rate raises both. The result assumes a fixed rate and regular equal payments, so it is an accurate baseline; real loans may add fees, taxes or insurance on top.",
    formulaExplanation:
      "P is the principal, r is the interest rate per payment period (annual rate divided by payments per year), and N is the total number of payments. The term (1 − (1 + r)^−N) is the present-value factor for a stream of N equal payments; dividing the principal times r by it yields the payment whose discounted stream exactly equals the principal today. That is why the balance amortizes to zero at the final payment. When the rate is zero, there is no interest and the payment is simply the principal spread evenly across all N periods.",
    example: {
      inputs: { principal: 100000, annualRate: 6, years: 30, paymentsPerYear: 12 },
      explanation: "A $100,000 principal at 6% over 30 years of monthly payments requires about $599.55 a month, totaling roughly $215,838 — about $115,838 of it interest.",
    },
    faqs: [
      { question: "What is an annuity in this context?", answer: "Here an annuity means a series of equal payments made at regular intervals, which is the structure behind most loans and many payout arrangements. Whether you are repaying a mortgage or receiving fixed pension income, the same math applies: a present lump sum is converted into a stream of level payments over time. The word also refers to insurance products that pay income in retirement, and the payment formula on this page is the engine that prices those steady streams." },
      { question: "How does the term affect the payment?", answer: "A longer term lowers each payment because the principal is spread across more periods, but it raises the total interest you pay, since the balance is outstanding for longer. A shorter term does the opposite — higher payments but far less interest overall. This trade-off between affordability and total cost is central to choosing a loan. Try different terms in the tool to see how the periodic payment and the total interest move in opposite directions." },
      { question: "What happens when the interest rate is zero?", answer: "With a zero rate there is no interest to pay, so the payment is simply the principal divided by the total number of payments, and the total interest is zero. This case can arise with promotional financing or interest-free installment plans. The calculator handles it directly rather than dividing by zero in the standard formula. It is a useful benchmark: comparing a real loan's payment against this zero-rate figure shows exactly how much the interest is costing you each period." },
      { question: "Can I use this for retirement payouts?", answer: "Yes. The same formula that sizes a loan payment also determines how much a fixed pool of savings can pay out each period over a set number of years at an assumed return. Enter your savings as the principal, your expected return as the rate, and your payout horizon as the term to see the sustainable regular withdrawal. Keep in mind it assumes a constant return and a fixed end date, so real retirement planning should also account for market swings and longevity." },
      { question: "Does the payment include taxes and fees?", answer: "No. This calculator returns the pure principal-and-interest payment. Real-world loans often bundle additional costs into what you actually pay — a mortgage may add property taxes and insurance to the monthly bill, and many loans carry origination or servicing fees. Those extras are not part of the amortization math shown here. Use this figure as the core payment, then add any known taxes, insurance or fees separately to estimate your true out-of-pocket cost each period." },
    ],
    relatedCalculators: ["loan-calculator", "mortgage-calculator", "retirement-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Amortization / annuity payment formula",
  },
  {
    id: "salary-raise",
    slug: "salary-raise-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Salary Raise Calculator",
    shortDescription: "See your new salary after a percentage raise.",
    seoTitle: "Salary Raise Calculator — Free Pay Increase Tool",
    metaDescription:
      "Free salary raise calculator. See your new salary, the raise amount in dollars, and the monthly increase after a percentage pay rise.",
    primaryKeyword: "salary raise calculator",
    secondaryKeywords: ["pay raise calculator", "salary increase calculator", "raise percentage calculator"],
    fields: [
      { id: "currentSalary", label: "Current annual salary", type: "number", unit: "$", placeholder: "60000", required: true, span: 1, min: 0 },
      { id: "raisePercent", label: "Raise percentage", type: "number", unit: "%", placeholder: "5", required: true, span: 1, min: 0, step: 0.01 },
    ],
    results: [
      { id: "newSalary", label: "New annual salary", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "raiseAmount", label: "Raise amount", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "monthlyIncrease", label: "Monthly increase", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "New salary = current salary × (1 + raise% ÷ 100) · Raise amount = current salary × raise% ÷ 100",
    explanation:
      "The new salary shown here is what you will earn after a raise, expressed as a percentage of your current pay, along with the dollar value of the raise and how much more you will see each month. It matters because raises are almost always quoted as percentages, and turning that percentage into real dollars is what actually tells you how a pay rise affects your budget. This salary raise calculator multiplies your current salary by the raise percentage to find the increase, adds it back to get your new salary, and divides the annual raise by twelve to show the monthly bump. Working from the percentage is the natural way to do it, since that is how employers frame offers and cost-of-living adjustments, and converting to dollars makes the raise concrete. Employees use it to understand an offer, to check that a raise keeps pace with inflation, to compare a percentage increase against a competing job's figure, and to plan how to use the extra income. Keep in mind these are gross figures, before taxes and deductions: your take-home increase will be smaller than the gross monthly figure, since a raise is taxed like the rest of your income and may nudge part of your earnings into a higher bracket. Still, seeing the gross new salary and monthly increase is the essential first step in judging whether a raise meaningfully improves your financial position or merely offsets rising costs.",
    formulaExplanation:
      "The raise percentage is converted to a decimal by dividing by 100, and multiplying your current salary by it gives the raise amount in dollars. Adding that to the current salary — equivalently, multiplying by (1 + raise% ÷ 100) — produces the new salary. Dividing the annual raise by twelve spreads it across the year to show the monthly increase in gross pay. Every figure here is before tax, so it reflects the change to your stated salary rather than to your take-home pay.",
    example: {
      inputs: { currentSalary: 60000, raisePercent: 5 },
      explanation: "A 5% raise on a $60,000 salary adds $3,000, lifting pay to $63,000 — about $250 more per month before tax.",
    },
    faqs: [
      { question: "Is the new salary before or after tax?", answer: "It is before tax — a gross figure. Both the new salary and the monthly increase shown are pre-tax amounts, matching how salaries are quoted and negotiated. Your actual take-home pay will rise by less, because the raise is subject to income tax, payroll taxes and any deductions like retirement contributions. A raise can also push part of your income into a higher tax bracket, though only the amount above the threshold is taxed at the higher rate. Expect the net monthly increase to be somewhat smaller." },
      { question: "Does a raise keep up with inflation?", answer: "Only if the percentage exceeds the inflation rate. A raise below inflation is effectively a pay cut in real terms, since your money buys less than before. To judge this, compare your raise percentage against the current inflation rate: a 5% raise when inflation is 3% is a real gain of about 2%, while a 2% raise in the same environment loses ground. Cost-of-living adjustments are meant to offset inflation, but a merit raise on top is what actually improves your purchasing power." },
      { question: "How do I calculate a raise as a percentage?", answer: "If you know the dollar amount of a raise instead of the percentage, divide the raise by your current salary and multiply by 100. For example, a $3,000 raise on a $60,000 salary is 3,000 ÷ 60,000 × 100 = 5%. This is the reverse of what the calculator does and is handy for comparing offers quoted in different ways, or for checking whether a lump-sum raise matches the percentage your employer stated. The two forms describe the same increase." },
      { question: "Should I negotiate based on percentage or dollars?", answer: "Both framings are useful, and it helps to think in each. Employers usually work in percentages tied to budgets and performance ratings, so knowing the percentage helps you benchmark against typical raises. But the dollar figure is what changes your life, so translate any offer into annual and monthly dollars before deciding. When negotiating, researching the market rate for your role in absolute salary terms, then expressing your ask as both a target salary and a percentage, tends to be most persuasive." },
      { question: "How is the monthly increase calculated?", answer: "The calculator takes the annual raise amount and divides it by twelve to spread it evenly across the year, giving the gross increase to each monthly paycheck. If you are paid biweekly or semimonthly, your per-paycheck increase will differ — divide the annual raise by 26 or 24 respectively instead. Remember this monthly figure is before tax and deductions, so the amount added to your actual deposited pay will be lower. It is a quick way to picture the raise in everyday budgeting terms." },
    ],
    relatedCalculators: ["fica-tax-calculator", "savings-goal-calculator", "investment-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard percentage increase",
  },
  {
    id: "fica-tax",
    slug: "fica-tax-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "FICA Tax Calculator",
    shortDescription: "Estimate Social Security and Medicare withholding.",
    seoTitle: "FICA Tax Calculator — Social Security & Medicare (2024)",
    metaDescription:
      "Free FICA tax calculator. Estimate your 2024 Social Security and Medicare payroll taxes from annual wages, including the additional Medicare tax.",
    primaryKeyword: "fica tax calculator",
    secondaryKeywords: ["payroll tax calculator", "social security tax calculator", "medicare tax calculator"],
    fields: [
      { id: "annualWages", label: "Annual wages", type: "number", unit: "$", placeholder: "100000", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "socialSecurity", label: "Social Security tax", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "medicare", label: "Medicare tax", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "totalFica", label: "Total FICA tax", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "SS = 6.2% × min(wages, $168,600) · Medicare = 1.45% × wages + 0.9% × wages over $200,000 (2024)",
    explanation:
      "FICA tax is the payroll tax that funds Social Security and Medicare, withheld from your wages under the Federal Insurance Contributions Act. The figure shown here is your share of that tax based on your annual wages, using 2024 rates. It matters because FICA is a fixed, unavoidable deduction from earned income that comes out before you ever see your paycheck, and understanding it clarifies the gap between your salary and your take-home pay. This FICA tax calculator applies the 6.2% Social Security rate to your wages up to the 2024 wage base of $168,600 — earnings above that are not subject to Social Security tax — and the 1.45% Medicare rate to all wages, then adds the additional 0.9% Medicare surtax on any wages above $200,000. Splitting the two components this way is necessary because they have different rules: Social Security is capped, while Medicare is uncapped and gains a surtax at higher incomes. Workers use a FICA calculator to understand their paycheck deductions, to verify their employer is withholding correctly, and to plan around the higher effective tax on top earners. Note that these are the employee-side figures; your employer pays a matching 6.2% and 1.45%, and self-employed people pay both halves as self-employment tax. The result reflects 2024 thresholds, which the IRS adjusts most years, so confirm the current wage base and rules before relying on it for a different tax year.",
    formulaExplanation:
      "Social Security tax is 6.2% of your wages but only up to the annual wage base — $168,600 in 2024 — so earnings above that add nothing more to it. Medicare tax is 1.45% of all wages with no cap. On top of that, an additional Medicare tax of 0.9% applies to wages above $200,000, so high earners pay 2.35% on the portion over that threshold. Adding the Social Security and Medicare components gives your total employee FICA withholding for the year.",
    example: {
      inputs: { annualWages: 100000 },
      explanation: "On $100,000 of wages in 2024, Social Security is $6,200 (6.2%) and Medicare is $1,450 (1.45%), for $7,650 in total FICA.",
    },
    faqs: [
      { question: "What is FICA tax?", answer: "FICA stands for the Federal Insurance Contributions Act, the law that requires payroll taxes to fund Social Security and Medicare. It is withheld automatically from your wages by your employer and matched by the employer dollar for dollar. The tax has two parts: Social Security, which funds retirement, disability and survivor benefits, and Medicare, which funds health coverage for people 65 and older. FICA applies to earned income from wages, separate from federal and state income taxes that also come out of your pay." },
      { question: "What is the Social Security wage base?", answer: "The wage base is the maximum amount of earnings subject to Social Security tax in a year — $168,600 for 2024. You pay 6.2% on wages up to that limit, and nothing on earnings above it, so the most any employee pays in Social Security tax in 2024 is about $10,453. Medicare has no such cap. The wage base rises most years with average wage growth, so check the current figure for other tax years before relying on this estimate." },
      { question: "What is the additional Medicare tax?", answer: "It is an extra 0.9% Medicare tax on wages above $200,000, introduced to have higher earners contribute more. Below the threshold you pay the standard 1.45%; on the portion above it, you pay 2.35% in total. Employers begin withholding it once your wages with them pass $200,000, regardless of your filing status, though the actual threshold on your tax return varies by filing status. Unlike the base Medicare tax, employers do not match this additional 0.9%." },
      { question: "Do employers pay FICA too?", answer: "Yes. FICA is split evenly between employee and employer. Your employer matches your 6.2% Social Security and 1.45% Medicare contributions, so a total of 12.4% for Social Security and 2.9% for Medicare goes toward these programs on your behalf. The employer does not match the additional 0.9% Medicare surtax on high earners. This calculator shows the employee half that appears on your pay stub; the employer's matching share is paid separately and does not reduce your wages." },
      { question: "How does FICA work if I'm self-employed?", answer: "Self-employed people pay both the employee and employer halves themselves, through the Self-Employment Contributions Act (SECA) tax — 12.4% for Social Security up to the wage base and 2.9% for Medicare, plus the 0.9% surtax at higher incomes. That is effectively double the employee rate shown here. However, you can deduct the employer-equivalent half when calculating your income tax, and Social Security still only applies up to the annual wage base. This tool models the employee-side withholding for wage earners specifically." },
    ],
    relatedCalculators: ["salary-raise-calculator", "capital-gains-tax-calculator", "loan-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    sensitivity: "finance",
    formulaSource: "IRS — FICA (2024)",
    sourceUrl: "https://www.irs.gov/",
  },
  {
    id: "capital-gains-tax",
    slug: "capital-gains-tax-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Capital Gains Tax Calculator",
    shortDescription: "Estimate tax owed on an investment sale.",
    seoTitle: "Capital Gains Tax Calculator — Free Investment Tax Tool",
    metaDescription:
      "Free capital gains tax calculator. Estimate your capital gain, tax owed and net profit from an asset's purchase price, sale price and tax rate.",
    primaryKeyword: "capital gains tax calculator",
    secondaryKeywords: ["capital gains calculator", "investment tax calculator", "stock gains tax calculator"],
    fields: [
      { id: "purchasePrice", label: "Purchase price (cost basis)", type: "number", unit: "$", placeholder: "10000", required: true, span: 1, min: 0 },
      { id: "salePrice", label: "Sale price", type: "number", unit: "$", placeholder: "15000", required: true, span: 1, min: 0 },
      { id: "taxRate", label: "Capital gains tax rate", type: "number", unit: "%", placeholder: "15", required: true, span: 2, min: 0, step: 0.01 },
    ],
    results: [
      { id: "capitalGain", label: "Capital gain", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "taxOwed", label: "Tax owed", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "netProfit", label: "Net profit after tax", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Capital gain = sale price − purchase price · Tax owed = gain × rate ÷ 100 (if gain > 0) · Net profit = gain − tax",
    explanation:
      "Capital gains tax is the tax you owe on the profit from selling an asset — stocks, a fund, real estate or other property — for more than you paid. The figures shown here are your gain, the tax on it, and what you keep after tax. It matters because the profit on paper is not all yours: the tax can take a meaningful slice, so knowing the after-tax number is what tells you the real return on an investment. This capital gains tax calculator subtracts your purchase price, or cost basis, from your sale price to find the gain, applies your tax rate to that gain, and subtracts the tax to show your net profit. Taxing only the gain — not the whole sale price — is how capital gains work: you are taxed on the increase in value, not on the return of your original investment. If you sold at a loss, the gain is negative and no tax is due, so the tool shows zero tax in that case. Investors use it to estimate the tax hit before selling, to compare holding versus selling, and to see how the difference between short-term and long-term rates changes the outcome. The rate you enter should reflect your situation: short-term gains on assets held a year or less are taxed as ordinary income, while long-term gains get preferential rates. Because actual liability depends on your income, filing status, holding period and other rules, treat this as an estimate and confirm specifics with the IRS or a tax professional.",
    formulaExplanation:
      "The capital gain is simply the sale price minus the purchase price (your cost basis), representing the profit on the asset. Multiplying that gain by your tax rate as a decimal gives the tax owed, but only when the gain is positive — a sale at a loss produces no capital gains tax, so the tool returns zero tax there. Subtracting the tax from the gain leaves your net profit, the amount you actually keep. Only the gain is taxed, because returning your original investment is not income.",
    example: {
      inputs: { purchasePrice: 10000, salePrice: 15000, taxRate: 15 },
      explanation: "Buying at $10,000 and selling at $15,000 is a $5,000 gain; at a 15% rate the tax is $750, leaving $4,250 in net profit.",
    },
    faqs: [
      { question: "What is the difference between short-term and long-term gains?", answer: "The holding period determines the rate. Assets held for one year or less produce short-term capital gains, taxed at your ordinary income tax rate, which can be high. Assets held longer than a year produce long-term capital gains, taxed at preferential rates — 0%, 15% or 20% for most taxpayers depending on income. This large gap is why many investors hold assets past the one-year mark before selling. Enter the rate that matches your holding period for an accurate estimate." },
      { question: "What is a cost basis?", answer: "Your cost basis is what you paid to acquire an asset, used to figure the taxable gain when you sell. It typically includes the purchase price plus any commissions or fees, and for some assets it can be adjusted for things like reinvested dividends or improvements to a property. The gain is the sale price minus this basis. Keeping accurate records of your basis is important, because overstating it understates your gain and could cause problems, while understating it makes you overpay tax." },
      { question: "Do I owe tax if I sold at a loss?", answer: "No capital gains tax is due on a loss, and the calculator shows zero tax when the sale price is below the purchase price. In fact, capital losses can be valuable: they offset capital gains elsewhere in your portfolio, and if losses exceed gains, you can typically deduct a limited amount against ordinary income each year and carry the rest forward. This strategy, called tax-loss harvesting, is a common way to reduce a tax bill, though specific rules apply." },
      { question: "What tax rate should I enter?", answer: "Enter the capital gains rate that applies to your situation. For a long-term gain, that is usually 0%, 15% or 20% depending on your taxable income and filing status, with most middle-income taxpayers at 15%. For a short-term gain, use your ordinary income tax bracket. High earners may also owe an additional 3.8% net investment income tax. If you are unsure, 15% is a reasonable default for long-term gains, but confirm your actual rate for a precise figure." },
      { question: "Are there ways to reduce capital gains tax?", answer: "Several strategies exist. Holding an asset longer than a year qualifies you for lower long-term rates. Offsetting gains with losses through tax-loss harvesting reduces the taxable amount. Holding investments in tax-advantaged accounts like IRAs or 401(k)s defers or avoids the tax entirely. For a home sale, a portion of the gain may be excluded if it was your primary residence. These rules are detailed and situation-specific, so consult IRS guidance or a tax professional before acting." },
    ],
    relatedCalculators: ["fica-tax-calculator", "investment-calculator", "future-value-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    sensitivity: "finance",
    formulaSource: "IRS — capital gains",
    sourceUrl: "https://www.irs.gov/",
  },
  {
    id: "student-loan",
    slug: "student-loan-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Student Loan Calculator",
    shortDescription: "Estimate monthly payments on a student loan.",
    seoTitle: "Student Loan Calculator — Free Repayment Estimate Tool",
    metaDescription:
      "Free student loan calculator. Estimate your monthly payment, total repaid and total interest on a student loan from balance, rate and term.",
    primaryKeyword: "student loan calculator",
    secondaryKeywords: ["student loan payment calculator", "student loan repayment calculator", "college loan calculator"],
    fields: [
      { id: "loanAmount", label: "Loan amount", type: "number", unit: "$", placeholder: "30000", required: true, span: 1, min: 0 },
      { id: "annualRate", label: "Annual interest rate", type: "number", unit: "%", placeholder: "5", required: true, span: 1, min: 0, step: 0.01 },
      { id: "years", label: "Repayment term", type: "number", unit: "years", placeholder: "10", required: true, span: 2, min: 0, step: 0.01 },
    ],
    results: [
      { id: "monthlyPayment", label: "Monthly payment", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "totalPaid", label: "Total repaid", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "totalInterest", label: "Total interest", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Payment = L × r ÷ (1 − (1 + r)^−N), r = annual rate ÷ 12, N = years × 12",
    explanation:
      "The monthly payment shown here is what it takes to repay a student loan in full over a chosen term at a given interest rate, along with the total you will repay and how much of that is interest. It matters because student debt is often a borrower's first large loan, and understanding the monthly commitment and lifetime cost upfront helps you choose a repayment plan and avoid surprises. This student loan calculator converts your annual rate to a monthly rate, counts the number of monthly payments in the term, and uses the standard amortization formula to find the level payment that clears the balance exactly by the end, then reports the total repaid and the interest portion. Amortization is the right model because each payment covers that month's interest first and applies the rest to principal, so early payments chip away slowly and later ones faster — the same way federal and private student loans actually work under a standard plan. Borrowers use it to budget for repayment, to compare a standard 10-year term against longer plans, and to see how extra payments or a lower rate reduce the total interest. A longer term lowers the monthly payment but increases total interest substantially, while paying more than the minimum shortens the payoff and saves interest. This models a standard fixed repayment; income-driven plans, deferment, subsidized interest and loan forgiveness follow different rules, so check your loan servicer's terms for your specific situation.",
    formulaExplanation:
      "L is the loan balance, r is the monthly interest rate (the annual rate divided by 12), and N is the number of monthly payments (years times 12). The factor (1 − (1 + r)^−N) is the present value of a stream of N equal payments; dividing L × r by it gives the fixed monthly payment whose payments, discounted back, exactly equal the loan today, so the balance amortizes to zero. When the rate is zero, the payment is just the balance split evenly across the N months, with no interest added.",
    example: {
      inputs: { loanAmount: 30000, annualRate: 5, years: 10 },
      explanation: "A $30,000 loan at 5% over 10 years costs about $318 a month, totaling roughly $38,184 — about $8,184 of it interest.",
    },
    faqs: [
      { question: "What is a typical student loan term?", answer: "The standard repayment term for federal student loans is 10 years, and it is the plan that minimizes total interest for most borrowers. Extended and graduated plans stretch payments over 20 to 25 years, lowering the monthly amount but sharply raising total interest. Income-driven plans set payments as a share of your income and can lead to forgiveness after a set period. This calculator models a fixed-term standard plan; enter the term your servicer offers to estimate that plan's payment." },
      { question: "Should I choose a longer term to lower my payment?", answer: "A longer term does reduce the monthly payment, which can ease a tight budget, but it significantly increases the total interest you pay because the balance is outstanding for more years. If cash flow is the immediate problem, a longer or income-driven plan can help, but if you can afford the standard payment, the shorter term saves far more money overall. Compare the monthly payment against the total interest in this tool before committing to a longer schedule." },
      { question: "How does interest accrue on student loans?", answer: "Interest accrues daily on your outstanding principal at your loan's rate. Under a standard plan, your fixed monthly payment covers the accrued interest first, and the remainder reduces principal, so early payments are more interest-heavy. On unsubsidized and private loans, interest also accrues while you are in school and during deferment, and unpaid interest may be capitalized — added to principal — which increases the balance you pay interest on. Subsidized federal loans do not accrue interest while you are enrolled at least half-time." },
      { question: "Can I pay off my student loan early?", answer: "Yes, federal and most private student loans have no prepayment penalty, so paying extra reduces your principal and the interest that accrues on it, shortening the payoff and cutting total interest. To make extra payments count against principal rather than future interest, tell your servicer to apply them that way. Even small additional amounts each month can save a meaningful sum over the life of the loan. Re-run this tool with a shorter term to see the effect of paying faster." },
      { question: "What is the difference between subsidized and unsubsidized loans?", answer: "With a subsidized federal loan, the government pays the interest while you are in school at least half-time, during the grace period, and in deferment, so the balance does not grow during those times. With an unsubsidized loan, interest accrues from the moment the loan is disbursed, including while you study, and any unpaid interest can be capitalized into the principal. That difference makes subsidized loans cheaper overall. Both types use the same amortization math once repayment begins." },
    ],
    relatedCalculators: ["loan-calculator", "annuity-calculator", "debt-to-income-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Loan amortization formula",
  },
];
