import type { CalculatorDefinition } from "../types";

export const financeCalculators: CalculatorDefinition[] = [
  {
    id: "mortgage",
    slug: "mortgage-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Mortgage Calculator",
    shortDescription: "Estimate your monthly mortgage payment.",
    seoTitle: "Mortgage Calculator — Free Monthly Payment Estimator",
    metaDescription:
      "Free mortgage calculator. Estimate your monthly payment, total interest and total cost from the home price, down payment, rate and term.",
    primaryKeyword: "mortgage calculator",
    secondaryKeywords: ["monthly mortgage payment", "home loan calculator", "mortgage payment calculator"],
    fields: [
      { id: "homePrice", label: "Home price", type: "number", unit: "$", placeholder: "400000", required: true, span: 1, min: 0 },
      { id: "downPayment", label: "Down payment", type: "number", unit: "$", placeholder: "80000", required: false, span: 1, min: 0 },
      { id: "rate", label: "Interest rate", type: "number", unit: "%", placeholder: "6.5", required: true, span: 1, min: 0, step: 0.01 },
      { id: "term", label: "Loan term", type: "number", unit: "years", placeholder: "30", required: true, span: 1, min: 1 },
    ],
    results: [
      { id: "monthlyPayment", label: "Monthly payment", format: "currency", currency: "USD", decimals: 2, isPrimary: true, description: "Principal & interest" },
      { id: "principal", label: "Loan amount", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "totalInterest", label: "Total interest", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "totalPaid", label: "Total of payments", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "M = P × r ÷ (1 − (1 + r)^−n), where r = annual rate ÷ 12 and n = years × 12",
    explanation:
      "Your monthly mortgage payment is the fixed amount you send your lender each month to repay a home loan, split between interest on the outstanding balance and principal that steadily reduces what you owe. Knowing this number before you shop matters because it decides whether a home fits your budget and how lenders judge affordability against your income. This mortgage calculator derives the loan amount by subtracting your down payment from the home price, then applies the standard fixed-rate amortization formula so every payment across the term is identical. That formula is used because it guarantees the balance reaches exactly zero at the final payment while front-loading interest — early payments are mostly interest, later ones mostly principal. A larger down payment or a shorter term lowers the total interest a mortgage calculator will project, sometimes dramatically. Homebuyers, real estate agents and loan officers rely on a mortgage calculator to compare offers, test how rate changes ripple through the monthly cost, and set a realistic price ceiling. Remember the result covers principal and interest only; property taxes, homeowners insurance, private mortgage insurance and HOA dues are billed separately and can add hundreds of dollars to your true monthly housing cost.",
    formulaExplanation:
      "The payment formula is the present value of an annuity solved for the payment. P is the loan amount, r the monthly rate, and n the total months. Dividing by (1 − (1 + r)^−n) spreads that principal across n payments while charging interest each month on the shrinking balance. Because the balance falls over time, a constant payment keeps interest and principal in step so the loan ends exactly at zero.",
    example: {
      inputs: { homePrice: 400000, downPayment: 80000, rate: 6.5, term: 30 },
      explanation: "A $320,000 loan at 6.5% over 30 years (360 payments) gives a monthly principal-and-interest payment of about $2,022.",
    },
    faqs: [
      { question: "What is a good interest rate on a mortgage?", answer: "A competitive rate depends on the market, your credit score, the loan term and your down payment. Borrowers with strong credit and 20% down typically secure the lowest advertised rates, while lower scores pay a premium. Even a quarter-point difference changes thousands over a 30-year loan. Compare offers from several lenders on the same day, since rates move daily, and always check the APR, which folds in fees." },
      { question: "How much should my down payment be?", answer: "Twenty percent is the classic benchmark because it removes private mortgage insurance and shrinks the loan, but many buyers put down far less. Conventional loans can start near 3%, FHA loans at 3.5%, and some VA and USDA loans require nothing down. A bigger down payment lowers your monthly payment and total interest, yet draining your savings for it can leave you exposed, so balance both goals." },
      { question: "How accurate is this mortgage calculator?", answer: "The math is exact for a fixed-rate loan: it reproduces an amortization schedule to the cent. It is only an estimate of your true housing cost because it excludes property taxes, homeowners and mortgage insurance, HOA fees and closing costs. Adjustable-rate mortgages also reset after their intro period, which this fixed-rate model does not capture. Treat the principal-and-interest figure as reliable and add the escrow items separately." },
      { question: "What is the difference between principal and interest?", answer: "Principal is the portion of each payment that reduces the balance you actually borrowed; interest is the lender's charge for lending it, calculated on the remaining balance. Early in the loan the balance is large, so most of your payment is interest. As the balance falls, more of each fixed payment goes to principal. This is why paying extra toward principal early saves a disproportionate amount of interest." },
      { question: "Can I use this for a refinance?", answer: "Yes. Enter your new loan amount as the home price with a zero down payment, plus the new rate and remaining term, and the tool projects the refinanced payment. Compare it against your current payment to see the monthly savings, then weigh that against closing costs to find your break-even point. A refinance that lowers the payment by extending the term can still raise total interest paid." },
    ],
    slugEs: "calculadora-de-hipoteca",
    titleEs: "Calculadora de Hipoteca",
    shortDescriptionEs: "Estima tu pago mensual de la hipoteca.",
    seoTitleEs: "Calculadora de Hipoteca — Estimador de Pago Mensual Gratuito",
    metaDescriptionEs: "Calculadora de hipoteca gratuita. Estima tu pago mensual, el interés total y el costo total a partir del precio de la vivienda, el enganche, la tasa y el plazo.",
    primaryKeywordEs: "calculadora de hipoteca",
    secondaryKeywordsEs: ["pago mensual de la hipoteca", "calculadora de préstamo hipotecario", "calculadora de pago de hipoteca"],
    formulaExplanationEs: "La fórmula del pago es el valor presente de una anualidad despejado para el pago. P es el monto del préstamo, r la tasa mensual y n el total de meses. Dividir entre (1 − (1 + r)^−n) reparte ese capital entre n pagos mientras cobra intereses cada mes sobre el saldo decreciente. Como el saldo baja con el tiempo, un pago constante mantiene el interés y el capital en equilibrio para que el préstamo termine exactamente en cero.",
    explanationEs: "Tu pago mensual de la hipoteca es la cantidad fija que envías a tu prestamista cada mes para pagar un préstamo hipotecario, dividida entre el interés sobre el saldo pendiente y el capital que reduce de forma constante lo que debes. Conocer este número antes de buscar vivienda importa porque decide si una casa cabe en tu presupuesto y cómo juzgan los prestamistas la asequibilidad frente a tus ingresos. Esta calculadora de hipoteca obtiene el monto del préstamo restando tu enganche del precio de la vivienda, y luego aplica la fórmula estándar de amortización de tasa fija para que cada pago del plazo sea idéntico. Esa fórmula se usa porque garantiza que el saldo llegue exactamente a cero en el último pago mientras concentra el interés al principio: los primeros pagos son casi todo interés, los últimos casi todo capital. Un enganche mayor o un plazo más corto reducen el interés total que proyectará una calculadora de hipoteca, a veces de forma drástica. Compradores, agentes inmobiliarios y oficiales de crédito recurren a una calculadora de hipoteca para comparar ofertas, probar cómo los cambios de tasa repercuten en el costo mensual y fijar un techo de precio realista. Recuerda que el resultado cubre solo capital e interés; los impuestos a la propiedad, el seguro de vivienda, el seguro hipotecario privado y las cuotas de asociación se facturan por separado y pueden sumar cientos de dólares a tu costo real de vivienda.",
    exampleEs: {
      inputs: { homePrice: 400000, downPayment: 80000, rate: 6.5, term: 30 },
      explanation: "Un préstamo de $320,000 al 6.5% a 30 años (360 pagos) da un pago mensual de capital e interés de unos $2,022.",
    },
    faqsEs: [
      { question: "¿Cuál es una buena tasa de interés en una hipoteca?", answer: "Una tasa competitiva depende del mercado, tu puntaje de crédito, el plazo del préstamo y tu enganche. Los prestatarios con crédito sólido y un 20% de enganche suelen conseguir las tasas anunciadas más bajas, mientras que los puntajes menores pagan una prima. Incluso una diferencia de un cuarto de punto cambia miles a lo largo de un préstamo a 30 años. Compara ofertas de varios prestamistas el mismo día, ya que las tasas se mueven a diario, y revisa siempre la APR, que incorpora las comisiones." },
      { question: "¿De cuánto debe ser mi enganche?", answer: "El veinte por ciento es la referencia clásica porque elimina el seguro hipotecario privado y reduce el préstamo, pero muchos compradores dan mucho menos. Los préstamos convencionales pueden empezar cerca del 3%, los préstamos FHA en el 3.5%, y algunos préstamos VA y USDA no requieren enganche. Un enganche mayor reduce tu pago mensual y el interés total, pero vaciar tus ahorros para lograrlo puede dejarte expuesto, así que equilibra ambos objetivos." },
      { question: "¿Qué tan precisa es esta calculadora de hipoteca?", answer: "La matemática es exacta para un préstamo de tasa fija: reproduce una tabla de amortización al centavo. Solo es una estimación de tu costo real de vivienda porque excluye impuestos a la propiedad, seguros de vivienda e hipotecario, cuotas de asociación y costos de cierre. Las hipotecas de tasa ajustable también se recalculan tras su periodo inicial, algo que este modelo de tasa fija no captura. Trata la cifra de capital e interés como fiable y suma las partidas de depósito en garantía por separado." },
      { question: "¿Cuál es la diferencia entre capital e interés?", answer: "El capital es la porción de cada pago que reduce el saldo que realmente pediste prestado; el interés es el cargo del prestamista por prestarlo, calculado sobre el saldo restante. Al inicio del préstamo el saldo es grande, por lo que la mayor parte de tu pago es interés. A medida que el saldo baja, más de cada pago fijo va al capital. Por eso pagar de más hacia el capital al principio ahorra una cantidad desproporcionada de interés." },
      { question: "¿Puedo usar esto para un refinanciamiento?", answer: "Sí. Introduce el monto de tu nuevo préstamo como el precio de la vivienda con un enganche de cero, además de la nueva tasa y el plazo restante, y la herramienta proyecta el pago refinanciado. Compáralo con tu pago actual para ver el ahorro mensual, y luego pondera eso frente a los costos de cierre para hallar tu punto de equilibrio. Un refinanciamiento que baja el pago extendiendo el plazo aún puede aumentar el interés total pagado." },
    ],
    relatedCalculators: ["loan-calculator", "compound-interest-calculator", "roi-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "Consumer Financial Protection Bureau (CFPB)",
    sourceUrl: "https://www.consumerfinance.gov/owning-a-home/",
  },
  {
    id: "compound-interest",
    slug: "compound-interest-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "Compound Interest Calculator",
    shortDescription: "See how savings grow with compound interest.",
    seoTitle: "Compound Interest Calculator — Free Investment Growth Tool",
    metaDescription:
      "Free compound interest calculator. Project the future value of savings or investments with regular contributions, and see total interest earned.",
    primaryKeyword: "compound interest calculator",
    secondaryKeywords: ["investment growth calculator", "future value calculator", "savings growth"],
    fields: [
      { id: "principal", label: "Initial amount", type: "number", unit: "$", placeholder: "10000", required: true, span: 1, min: 0 },
      { id: "contribution", label: "Monthly contribution", type: "number", unit: "$", placeholder: "200", required: false, span: 1, min: 0 },
      { id: "rate", label: "Annual interest rate", type: "number", unit: "%", placeholder: "7", required: true, span: 1, min: 0, step: 0.01 },
      { id: "years", label: "Years", type: "number", placeholder: "20", required: true, span: 1, min: 0 },
      {
        id: "frequency", label: "Compounding", type: "select", required: false, span: 2, defaultValue: "12",
        options: [
          { value: "1", label: "Annually" },
          { value: "2", label: "Semi-annually" },
          { value: "4", label: "Quarterly" },
          { value: "12", label: "Monthly" },
          { value: "365", label: "Daily" },
        ],
      },
    ],
    results: [
      { id: "futureValue", label: "Future value", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "totalContributions", label: "Total contributed", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "totalInterest", label: "Interest earned", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "FV = P(1 + r/n)^(nt) + PMT × [((1 + i)^m − 1) ÷ i]",
    explanation:
      "Compound interest is the growth you earn when interest is added back to your balance and then earns interest of its own, so the account grows faster the longer it runs. The future value shown here is the projected balance once that snowball effect has compounded your initial deposit and every monthly contribution to the end of the period. Understanding it matters because compounding is the single largest driver of long-term wealth, and small differences in rate, time or contribution size lead to strikingly different outcomes. This compound interest calculator applies the exponential growth factor to your starting amount at the frequency you choose, then adds the future value of your contribution stream, treated as a series of monthly deposits. The exponential formula is used because each period multiplies the whole balance — principal plus all prior interest — by the same growth factor, which is precisely what compounding means. Savers, investors and financial planners lean on a compound interest calculator to set retirement targets, weigh a lump sum against steady contributions, and see why starting early beats contributing more later. Because it assumes a constant return, treat the projection from any compound interest calculator as a planning estimate rather than a promise; real markets rise and fall year to year.",
    formulaExplanation:
      "P is the starting principal, r the annual rate, n the compounds per year and t the years, so (1 + r/n)^(nt) is the growth factor applied once per period. Raising it to the total number of periods captures interest repeatedly earning interest. The contribution term sums each monthly deposit's own growth as a geometric series, dividing by the periodic rate i to total every deposit compounded to the end date.",
    example: {
      inputs: { principal: 10000, contribution: 200, rate: 7, years: 20, frequency: "12" },
      explanation: "$10,000 plus $200/month at 7% compounded monthly for 20 years grows to roughly $143,000, of which about $75,000 is interest.",
    },
    faqs: [
      { question: "How is compound interest calculated?", answer: "The balance is multiplied by a growth factor each period rather than earning a flat amount. For the initial deposit, that factor is (1 + r/n) applied nt times, where r is the annual rate, n the compounds per year and t the years. Regular contributions are handled as a separate annuity and added on. Because each period grows the whole balance, interest earned earlier itself earns interest, which is the compounding effect." },
      { question: "What is the difference between simple and compound interest?", answer: "Simple interest is charged only on the original principal, so it grows in a straight line. Compound interest is charged on the principal plus all interest already added, so growth accelerates over time. On a 20-year horizon the gap is enormous: compounding at 7% roughly quadruples a lump sum, while simple interest at the same rate only about doubles it. Longer periods widen the difference." },
      { question: "Does compounding frequency really matter?", answer: "It helps, but less than people expect. Moving from annual to monthly compounding at a typical rate adds only a fraction of a percent to the effective yield, because the extra credits are small. Time in the market and the contribution amount dominate the outcome. Compare accounts by their APY, which already bakes in the compounding frequency, rather than the stated nominal rate alone." },
      { question: "How can I reach a savings goal faster?", answer: "Three levers move the future value: contribute more each month, earn a higher rate, or give the money more time. Time is usually the most powerful because it multiplies every contribution's compounding. Increasing the monthly deposit has a direct, predictable effect, while chasing a higher rate adds risk. Front-loading contributions early in the period also beats adding the same money later." },
      { question: "Are these projections guaranteed?", answer: "No. The calculator assumes a single, constant rate of return for the whole period, but real investments fluctuate and can lose value in any given year. Use it to compare scenarios and set targets, not as a promise of a specific balance. For volatile assets, run a conservative and an optimistic rate to bracket the likely range rather than trusting one figure." },
    ],
    slugEs: "calculadora-de-interes-compuesto",
    titleEs: "Calculadora de Interés Compuesto",
    shortDescriptionEs: "Descubre cómo crecen los ahorros con el interés compuesto.",
    seoTitleEs: "Calculadora de Interés Compuesto — Herramienta de Crecimiento de Inversión",
    metaDescriptionEs: "Calculadora de interés compuesto gratuita. Proyecta el valor futuro de tus ahorros o inversiones con aportaciones periódicas y observa el interés total ganado.",
    primaryKeywordEs: "calculadora de interés compuesto",
    secondaryKeywordsEs: ["calculadora de crecimiento de inversión", "calculadora de valor futuro", "crecimiento de ahorros"],
    formulaExplanationEs: "P es el capital inicial, r la tasa anual, n las capitalizaciones por año y t los años, así que (1 + r/n)^(nt) es el factor de crecimiento aplicado una vez por periodo. Elevarlo al número total de periodos captura el interés que gana interés repetidamente. El término de aportaciones suma el crecimiento propio de cada depósito mensual como una serie geométrica, dividiendo entre la tasa periódica i para totalizar cada depósito capitalizado hasta la fecha final.",
    explanationEs: "El interés compuesto es el crecimiento que ganas cuando el interés se añade de vuelta a tu saldo y luego gana su propio interés, de modo que la cuenta crece más rápido cuanto más tiempo transcurre. El valor futuro que se muestra aquí es el saldo proyectado una vez que ese efecto de bola de nieve ha capitalizado tu depósito inicial y cada aportación mensual hasta el final del periodo. Entenderlo importa porque la capitalización es el mayor motor de riqueza a largo plazo, y pequeñas diferencias en tasa, tiempo o tamaño de la aportación conducen a resultados sorprendentemente distintos. Esta calculadora de interés compuesto aplica el factor de crecimiento exponencial a tu monto inicial con la frecuencia que elijas, y luego suma el valor futuro de tu flujo de aportaciones, tratado como una serie de depósitos mensuales. La fórmula exponencial se usa porque cada periodo multiplica todo el saldo —capital más todo el interés previo— por el mismo factor de crecimiento, que es precisamente lo que significa capitalizar. Ahorradores, inversores y planificadores financieros se apoyan en una calculadora de interés compuesto para fijar metas de jubilación, comparar una suma global frente a aportaciones constantes y ver por qué empezar temprano supera a aportar más tarde. Como asume un rendimiento constante, trata la proyección de cualquier calculadora de interés compuesto como una estimación de planificación, no una promesa; los mercados reales suben y bajan año con año.",
    exampleEs: {
      inputs: { principal: 10000, contribution: 200, rate: 7, years: 20, frequency: "12" },
      explanation: "$10,000 más $200/mes al 7% capitalizado mensualmente durante 20 años crece a aproximadamente $143,000, de los cuales unos $75,000 son interés.",
    },
    faqsEs: [
      { question: "¿Cómo se calcula el interés compuesto?", answer: "El saldo se multiplica por un factor de crecimiento cada periodo en lugar de ganar una cantidad fija. Para el depósito inicial, ese factor es (1 + r/n) aplicado nt veces, donde r es la tasa anual, n las capitalizaciones por año y t los años. Las aportaciones periódicas se manejan como una anualidad separada y se añaden. Como cada periodo hace crecer todo el saldo, el interés ganado antes gana a su vez interés, que es el efecto de capitalización." },
      { question: "¿Cuál es la diferencia entre interés simple y compuesto?", answer: "El interés simple se cobra solo sobre el capital original, así que crece en línea recta. El interés compuesto se cobra sobre el capital más todo el interés ya añadido, así que el crecimiento se acelera con el tiempo. En un horizonte de 20 años la brecha es enorme: capitalizar al 7% aproximadamente cuadruplica una suma global, mientras que el interés simple a la misma tasa solo la duplica aproximadamente. Los periodos más largos amplían la diferencia." },
      { question: "¿Realmente importa la frecuencia de capitalización?", answer: "Ayuda, pero menos de lo que la gente espera. Pasar de capitalización anual a mensual a una tasa típica añade solo una fracción de por ciento al rendimiento efectivo, porque los créditos adicionales son pequeños. El tiempo en el mercado y el monto de la aportación dominan el resultado. Compara cuentas por su APY, que ya incorpora la frecuencia de capitalización, en lugar de la tasa nominal declarada por sí sola." },
      { question: "¿Cómo puedo alcanzar una meta de ahorro más rápido?", answer: "Tres palancas mueven el valor futuro: aportar más cada mes, ganar una tasa más alta o dar al dinero más tiempo. El tiempo suele ser la más poderosa porque multiplica la capitalización de cada aportación. Aumentar el depósito mensual tiene un efecto directo y predecible, mientras que perseguir una tasa más alta añade riesgo. Concentrar las aportaciones al principio del periodo también supera a añadir el mismo dinero más tarde." },
      { question: "¿Están garantizadas estas proyecciones?", answer: "No. La calculadora asume una única tasa de rendimiento constante para todo el periodo, pero las inversiones reales fluctúan y pueden perder valor en cualquier año dado. Úsala para comparar escenarios y fijar metas, no como promesa de un saldo específico. Para activos volátiles, ejecuta una tasa conservadora y otra optimista para acotar el rango probable en lugar de confiar en una sola cifra." },
    ],
    relatedCalculators: ["roi-calculator", "mortgage-calculator", "savings-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "U.S. SEC — Investor.gov",
    sourceUrl: "https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator",
  },
  {
    id: "roi",
    slug: "roi-calculator",
    category: "Finance",
    categorySlug: "finance",
    title: "ROI Calculator",
    shortDescription: "Measure return on investment as a percentage.",
    seoTitle: "ROI Calculator — Free Return on Investment Calculator",
    metaDescription:
      "Free ROI calculator. Work out return on investment and net profit from your initial and final amounts, plus annualized ROI over time.",
    primaryKeyword: "roi calculator",
    secondaryKeywords: ["return on investment calculator", "annualized roi", "investment return"],
    fields: [
      { id: "initial", label: "Initial investment", type: "number", unit: "$", placeholder: "5000", required: true, span: 1, min: 0 },
      { id: "final", label: "Final value", type: "number", unit: "$", placeholder: "8000", required: true, span: 1, min: 0 },
      { id: "years", label: "Holding period", type: "number", unit: "years", placeholder: "3", required: false, span: 2, min: 0, helpText: "Optional — used to calculate annualized ROI." },
    ],
    results: [
      { id: "roi", label: "ROI", format: "percentage", decimals: 2, isPrimary: true },
      { id: "netProfit", label: "Net profit", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "annualized", label: "Annualized ROI", format: "percentage", decimals: 2, isPrimary: false, description: "Requires a holding period" },
    ],
    formula: "ROI (%) = ((final − initial) ÷ initial) × 100",
    explanation:
      "Return on investment is your gain or loss expressed as a percentage of what you originally put in, turning a raw dollar profit into a figure you can compare across deals of any size. That percentage matters because $3,000 of profit tells you little on its own — it is excellent on a $5,000 stake and mediocre on a $500,000 one — while a percentage puts every opportunity on the same footing. This roi calculator divides net profit by the initial investment, the standard definition used precisely because it is simple, universal and dimensionless, so a marketing campaign, a stock position and a rental property can all be ranked by the same number. When you supply a holding period, the roi calculator also reports annualized ROI, which restates the total return as an equivalent yearly rate so a 60% gain over three years can be compared fairly against a 25% gain over one. Business owners, marketers, investors and analysts use an roi calculator to justify spending, choose between projects and report performance to stakeholders. Keep in mind that ROI captures return only — it ignores risk, timing of cash flows and inflation — so pair it with those factors before committing capital.",
    formulaExplanation:
      "ROI subtracts the initial investment from the final value to isolate net profit, then divides by the initial investment so the gain is measured relative to what you risked. Multiplying by 100 turns the ratio into a percentage. Annualized ROI takes the ending-to-starting ratio and raises it to the power of one divided by the number of years, undoing compounding to reveal the steady yearly rate that would produce the same total result.",
    example: {
      inputs: { initial: 5000, final: 8000, years: 3 },
      explanation: "A gain from $5,000 to $8,000 is a $3,000 net profit and a 60% total ROI. Over 3 years, that's about 17% annualized.",
    },
    faqs: [
      { question: "What is a good ROI?", answer: "There is no universal figure — it depends on the asset class, the time frame and the risk taken. As a reference, the broad stock market has returned roughly 7–10% a year on average, so a long-term investment beating that is doing well. A marketing campaign might target several hundred percent. Always judge ROI against a comparable low-risk alternative and against inflation, which quietly erodes real returns." },
      { question: "What is the difference between ROI and annualized ROI?", answer: "Plain ROI is the total percentage gain over the entire holding period, regardless of how long that was. Annualized ROI compresses that total into an equivalent per-year rate, accounting for compounding. A 60% total return sounds large, but spread over three years it is about 17% a year. Use annualized ROI whenever you compare investments held for different lengths of time — otherwise the comparison is misleading." },
      { question: "Does ROI account for risk?", answer: "No. ROI measures return only and says nothing about the chance of loss or the volatility along the way. Two investments can show an identical ROI while one is a government bond and the other a speculative startup. Always read ROI alongside a risk measure — such as the range of possible outcomes or the asset's historical volatility — before deciding whether the return justifies the exposure." },
      { question: "Can I use this for marketing or business projects?", answer: "Yes. Enter the total cost of the initiative as the initial investment and the revenue or value it generated as the final value. The tool then reports the percentage return and net profit, which is exactly how marketers evaluate campaigns and how managers rank competing projects. For campaigns measured on ad spend specifically, a dedicated ROAS calculation isolates revenue per advertising dollar." },
      { question: "How is annualized ROI calculated?", answer: "It takes the ratio of the final value to the initial value, raises that ratio to the power of one divided by the number of years, and subtracts one. This reverses the effect of compounding to find the constant yearly rate that would grow the initial amount to the final amount over the period. It requires a holding period, which is why the field is optional but needed for that result." },
    ],
    slugEs: "calculadora-de-retorno-de-inversion",
    titleEs: "Calculadora de ROI",
    shortDescriptionEs: "Mide el retorno de la inversión como porcentaje.",
    seoTitleEs: "Calculadora de ROI — Retorno de la Inversión Gratuita",
    metaDescriptionEs: "Calculadora de ROI gratuita. Obtén el retorno de la inversión y el beneficio neto a partir de tus montos inicial y final, además del ROI anualizado a lo largo del tiempo.",
    primaryKeywordEs: "calculadora de roi",
    secondaryKeywordsEs: ["calculadora de retorno de la inversión", "roi anualizado", "retorno de la inversión"],
    formulaExplanationEs: "El ROI resta la inversión inicial del valor final para aislar el beneficio neto, y luego lo divide entre la inversión inicial para medir la ganancia en relación con lo que arriesgaste. Multiplicar por 100 convierte el ratio en porcentaje. El ROI anualizado toma el cociente entre el valor final y el inicial y lo eleva a la potencia de uno dividido entre el número de años, deshaciendo la capitalización para revelar la tasa anual constante que produciría el mismo resultado total.",
    explanationEs: "El retorno de la inversión es tu ganancia o pérdida expresada como porcentaje de lo que aportaste originalmente, lo que convierte un beneficio bruto en dólares en una cifra que puedes comparar entre operaciones de cualquier tamaño. Ese porcentaje importa porque $3,000 de beneficio dice poco por sí solo —es excelente sobre una apuesta de $5,000 y mediocre sobre una de $500,000— mientras que un porcentaje pone cada oportunidad en el mismo plano. Esta calculadora de ROI divide el beneficio neto entre la inversión inicial, la definición estándar que se usa precisamente porque es simple, universal y adimensional, de modo que una campaña de marketing, una posición en acciones y una propiedad de alquiler pueden clasificarse por el mismo número. Cuando indicas un periodo de tenencia, la calculadora de ROI también reporta el ROI anualizado, que reformula el retorno total como una tasa anual equivalente para que una ganancia del 60% en tres años se compare de forma justa con una del 25% en uno. Dueños de negocios, especialistas en marketing, inversores y analistas usan una calculadora de ROI para justificar gastos, elegir entre proyectos y reportar el desempeño a las partes interesadas. Ten en cuenta que el ROI captura solo el retorno —ignora el riesgo, el momento de los flujos de efectivo y la inflación— así que combínalo con esos factores antes de comprometer capital.",
    exampleEs: {
      inputs: { initial: 5000, final: 8000, years: 3 },
      explanation: "Una ganancia de $5,000 a $8,000 es un beneficio neto de $3,000 y un ROI total del 60%. En 3 años, eso equivale a cerca del 17% anualizado.",
    },
    faqsEs: [
      { question: "¿Qué es un buen ROI?", answer: "No hay una cifra universal: depende de la clase de activo, el horizonte temporal y el riesgo asumido. Como referencia, el mercado bursátil amplio ha rendido aproximadamente entre el 7% y el 10% anual en promedio, así que una inversión a largo plazo que lo supere lo está haciendo bien. Una campaña de marketing podría apuntar a varios cientos por ciento. Juzga siempre el ROI frente a una alternativa comparable de bajo riesgo y frente a la inflación, que erosiona en silencio los retornos reales." },
      { question: "¿Cuál es la diferencia entre ROI y ROI anualizado?", answer: "El ROI simple es la ganancia porcentual total durante todo el periodo de tenencia, sin importar cuánto duró. El ROI anualizado comprime ese total en una tasa anual equivalente, contemplando la capitalización. Un retorno total del 60% suena grande, pero repartido en tres años es de cerca del 17% anual. Usa el ROI anualizado siempre que compares inversiones mantenidas por periodos distintos; de lo contrario la comparación es engañosa." },
      { question: "¿El ROI contempla el riesgo?", answer: "No. El ROI mide solo el retorno y no dice nada sobre la probabilidad de pérdida ni la volatilidad del camino. Dos inversiones pueden mostrar un ROI idéntico mientras una es un bono del gobierno y la otra una startup especulativa. Lee siempre el ROI junto a una medida de riesgo —como el rango de resultados posibles o la volatilidad histórica del activo— antes de decidir si el retorno justifica la exposición." },
      { question: "¿Puedo usar esto para marketing o proyectos de negocio?", answer: "Sí. Introduce el costo total de la iniciativa como la inversión inicial y los ingresos o el valor que generó como el valor final. La herramienta reporta entonces el retorno porcentual y el beneficio neto, que es exactamente cómo los especialistas en marketing evalúan campañas y cómo los gerentes clasifican proyectos rivales. Para campañas medidas específicamente por la inversión publicitaria, un cálculo dedicado de ROAS aísla los ingresos por cada dólar de publicidad." },
      { question: "¿Cómo se calcula el ROI anualizado?", answer: "Toma el cociente entre el valor final y el valor inicial, lo eleva a la potencia de uno dividido entre el número de años, y le resta uno. Esto revierte el efecto de la capitalización para hallar la tasa anual constante que haría crecer el monto inicial hasta el monto final durante el periodo. Requiere un periodo de tenencia, razón por la que ese campo es opcional pero necesario para ese resultado." },
    ],
    relatedCalculators: ["compound-interest-calculator", "mortgage-calculator", "roas-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "Standard financial formula",
  },
];
