import type { CalculatorDefinition } from "../types";

const SYSTEM_FIELD = {
  id: "system", label: "Unit system", type: "select" as const, required: true, span: 1 as const, defaultValue: "metric",
  unitOptions: [{ value: "metric", label: "Metric (kg/cm)" }, { value: "imperial", label: "Imperial (lb/in)" }],
};
const SEX_FIELD = {
  id: "sex", label: "Biological sex", type: "select" as const, required: true, span: 1 as const, defaultValue: "male",
  unitOptions: [{ value: "male", label: "Male" }, { value: "female", label: "Female" }],
};
const ACTIVITY_FIELD = {
  id: "activityLevel", label: "Activity level", type: "select" as const, required: true, span: 1 as const, defaultValue: "1.2",
  unitOptions: [
    { value: "1.2", label: "Sedentary (little or no exercise)" },
    { value: "1.375", label: "Light (1–3 days/week)" },
    { value: "1.55", label: "Moderate (3–5 days/week)" },
    { value: "1.725", label: "Active (6–7 days/week)" },
    { value: "1.9", label: "Very active (hard exercise + physical job)" },
  ],
};

export const healthWave2Calculators: CalculatorDefinition[] = [
  {
    id: "tdee",
    slug: "tdee-calculator",
    category: "Health",
    categorySlug: "health",
    title: "TDEE Calculator",
    shortDescription: "Calculate your Total Daily Energy Expenditure to manage your weight.",
    seoTitle: "TDEE Calculator — Total Daily Energy Expenditure",
    metaDescription: "Calculate your TDEE (Total Daily Energy Expenditure) to know exactly how many calories to eat for weight loss, maintenance, or muscle gain.",
    primaryKeyword: "TDEE calculator",
    secondaryKeywords: ["total daily energy expenditure", "calorie needs calculator", "maintenance calories"],
    fields: [
      SEX_FIELD,
      { id: "age", label: "Age", type: "number", unit: "years", placeholder: "30", required: true, span: 1 as const, min: 10, max: 120 },
      SYSTEM_FIELD,
      { id: "weight", label: "Weight", type: "number", placeholder: "70", required: true, span: 1 as const, min: 0 },
      { id: "height", label: "Height", type: "number", placeholder: "175", required: true, span: 1 as const, min: 0 },
      ACTIVITY_FIELD,
    ],
    results: [
      { id: "tdee", label: "TDEE (maintenance calories)", format: "number", decimals: 0, isPrimary: true },
      { id: "bmr", label: "BMR (base metabolic rate)", format: "number", decimals: 0, isPrimary: false },
      { id: "weightLoss", label: "Weight loss target (−500 cal)", format: "number", decimals: 0, isPrimary: false },
      { id: "weightGain", label: "Weight gain target (+500 cal)", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "TDEE = BMR × Activity Factor (Mifflin-St Jeor × Harris-Benedict multiplier)",
    formulaExplanation: "BMR is calculated using the Mifflin-St Jeor equation (10×weight_kg + 6.25×height_cm − 5×age + 5 for men, −161 for women). TDEE multiplies BMR by the activity factor: 1.2 (sedentary), 1.375 (light), 1.55 (moderate), 1.725 (active), 1.9 (very active). To lose about 1 lb/week, eat 500 calories below TDEE; to gain, eat 500 above.",
    formulaSource: "Mifflin MD et al., 1990. A new predictive equation for resting energy expenditure in healthy individuals. Am J Clin Nutr.",
    explanation: "Total Daily Energy Expenditure (TDEE) is the total number of calories your body burns in a day, accounting for both your resting metabolic rate and the energy you expend through activity. It is the most important number for anyone trying to change their body composition through diet, because it tells you the precise caloric intake required to maintain your current weight. Eating below your TDEE creates a calorie deficit that causes fat loss; eating above it creates a surplus that supports muscle gain. TDEE is calculated by multiplying your Basal Metabolic Rate (BMR) — the calories your body needs just to survive at rest — by an activity multiplier that accounts for exercise and movement. The Mifflin-St Jeor equation is widely regarded as the most accurate BMR formula for the general population, validated in multiple peer-reviewed studies. One critical caveat: activity multipliers are estimates that assume accurate self-reporting of exercise frequency and intensity, which people tend to overestimate. If you are not losing weight at a calculated deficit, you may be overestimating your activity level or underestimating caloric intake. Track food intake using a food diary or app for one week to calibrate. TDEE is not static — it changes as weight, age, muscle mass, and activity level change, so recalculate every four to eight weeks during an intentional body recomposition phase.",
    example: {
      inputs: { sex: "male", age: 30, system: "metric", weight: 80, height: 180, activityLevel: "1.55" },
      explanation: "A 30-year-old male, 80 kg, 180 cm, moderately active has a BMR of ~1,874 calories and a TDEE of ~2,905 calories. Weight loss target: ~2,405 cal/day.",
    },
    faqs: [
      { question: "What is the difference between BMR and TDEE?", answer: "BMR (Basal Metabolic Rate) is the number of calories your body burns at complete rest — the energy needed to maintain basic functions like breathing, circulation, and cell repair if you did absolutely nothing for 24 hours. TDEE (Total Daily Energy Expenditure) is your actual daily calorie burn, factoring in your activity level. TDEE is always higher than BMR and is the number you should use for diet planning. BMR alone is only useful as the starting point for the TDEE calculation." },
      { question: "Why am I not losing weight at my calculated deficit?", answer: "Several factors can cause a disconnect between predicted and actual weight loss. Most commonly: overestimating activity level (selecting 'active' when you work a desk job and exercise lightly), underestimating caloric intake (portion sizes are consistently larger than people think, and liquid calories from drinks, dressings, and cooking oils are often ignored), or metabolic adaptation (your metabolism slows slightly during extended calorie restriction). Track food intake precisely with a digital food scale and logging app for one week, and ensure your activity level selection accurately reflects your typical week." },
      { question: "How do I choose my activity level accurately?", answer: "Sedentary means a desk job with little or no intentional exercise. Lightly active is 1–3 exercise sessions per week with otherwise sedentary work. Moderately active is 3–5 sessions per week with a mix of cardio and weights. Active is 6–7 hard training days per week, or a physically demanding job. Very active is twice-daily training or extremely labor-intensive work. Most people overestimate their activity. When in doubt, select one level lower than feels right and adjust based on real-world results over four to six weeks." },
      { question: "How fast should I aim to lose weight?", answer: "A deficit of 500 calories per day creates a roughly 1 lb (0.45 kg) weekly loss — a rate widely recommended by dietitians as sustainable and conducive to preserving muscle mass. Faster rates (1,000 cal/day deficit, ~2 lb/week) are more aggressive and require careful attention to protein intake to minimize muscle loss. Very low calorie diets (under 1,200 cal/day for women, 1,500 for men) risk nutrient deficiency, metabolic adaptation, and muscle catabolism. Most evidence supports a 0.5–1% body weight loss per week as the ideal rate." },
      { question: "Does TDEE change as I lose weight?", answer: "Yes — TDEE decreases as you lose weight for two reasons. First, a lighter body burns fewer calories doing the same activities (less mass to move). Second, metabolic adaptation occurs during calorie restriction: the body becomes more efficient, reducing energy expenditure beyond what is predicted by weight alone. This is why weight loss often plateaus after initial success. Every 10–15 lbs lost, recalculate your TDEE and adjust your intake target. Increasing exercise volume or including resistance training helps offset the metabolic slowdown by preserving or building calorie-burning muscle tissue." },
    ],
    relatedCalculators: ["bmi-calculator", "bmr-calculator", "calorie-calculator"],
    status: "active",
    lastReviewed: "2026-08-22",
    sensitivity: "health",
    sourceUrl: "https://www.ncbi.nlm.nih.gov/pubmed/2305711",
  },
  {
    id: "body-fat",
    slug: "body-fat-calculator",
    category: "Health",
    categorySlug: "health",
    title: "Body Fat Percentage Calculator",
    shortDescription: "Estimate body fat percentage using the US Navy circumference method.",
    seoTitle: "Body Fat Percentage Calculator — US Navy Method",
    metaDescription: "Calculate body fat percentage using waist, neck, and hip measurements. Uses the accurate US Navy method for men and women.",
    primaryKeyword: "body fat percentage calculator",
    secondaryKeywords: ["body fat calculator", "body fat measurement", "body composition calculator"],
    fields: [
      SEX_FIELD,
      SYSTEM_FIELD,
      { id: "height", label: "Height", type: "number", placeholder: "175", required: true, span: 1 as const, min: 0 },
      { id: "weight", label: "Weight", type: "number", placeholder: "80", required: true, span: 1 as const, min: 0 },
      { id: "neck", label: "Neck circumference", type: "number", placeholder: "38", required: true, span: 1 as const, min: 0, helpText: "Measure at narrowest point" },
      { id: "waist", label: "Waist circumference", type: "number", placeholder: "84", required: true, span: 1 as const, min: 0, helpText: "Men: at navel. Women: narrowest point" },
      { id: "hip", label: "Hip circumference (women only)", type: "number", placeholder: "96", required: false, span: 1 as const, min: 0, helpText: "At widest point (required for women)" },
    ],
    results: [
      { id: "bodyFat", label: "Body fat %", format: "percentage", decimals: 1, isPrimary: true },
      { id: "fatMass", label: "Fat mass (kg)", format: "number", decimals: 1, isPrimary: false },
      { id: "leanMass", label: "Lean mass (kg)", format: "number", decimals: 1, isPrimary: false },
    ],
    formula: "US Navy: Men: %BF = 86.01·log10(waist−neck) − 70.041·log10(height) + 36.76; Women: %BF = 163.205·log10(waist+hip−neck) − 97.684·log10(height) − 78.387",
    formulaExplanation: "The US Navy circumference method was developed to provide accurate body fat estimates without equipment. All measurements in centimeters feed into logarithmic equations validated against hydrostatic weighing. Men provide waist and neck; women additionally provide hip measurements. The formula accounts for fat distribution differences between sexes.",
    formulaSource: "Hodgdon JA, Beckett MB, 1984. Prediction of percent body fat for US Navy men from body circumferences and height.",
    explanation: "Body fat percentage is one of the most informative measures of physical health and fitness, revealing body composition that weight alone cannot. Two people can have identical BMI yet dramatically different body fat percentages if one has significantly more muscle mass. The US Navy circumference method provides a reliable, equipment-free estimate using simple tape measure readings, validated against gold-standard methods like hydrostatic weighing and DEXA scans. For men, body fat in the 10–20% range is generally considered fit; athletes often fall in the 6–13% range. For women, essential fat (required for hormone function and organ protection) is higher — 10–13% is essential, 14–20% is athletic, 21–24% is fit, and above 32% is obese according to ACE classifications. Body fat percentage is more clinically meaningful than BMI for assessing cardiometabolic risk, as visceral (abdominal) fat is more metabolically active and dangerous than subcutaneous fat stored elsewhere. Unlike scale weight, which fluctuates daily with hydration and food intake, body fat percentage changes slowly and provides a more stable measure of progress during body recomposition programs. Recheck every 4–8 weeks using consistent measurement timing and technique.",
    example: {
      inputs: { sex: "male", system: "metric", height: 178, weight: 82, neck: 38, waist: 86 },
      explanation: "A 178 cm, 82 kg male with a 86 cm waist and 38 cm neck has an estimated body fat of approximately 18%, with ~14.8 kg fat mass and ~67.2 kg lean mass.",
    },
    faqs: [
      { question: "What is a healthy body fat percentage?", answer: "Healthy ranges differ by sex and age. For men: essential fat 2–5%, athletes 6–13%, fit 14–17%, acceptable 18–25%, obese >25%. For women: essential fat 10–13%, athletes 14–20%, fit 21–24%, acceptable 25–31%, obese >32%. These categories (from the American Council on Exercise) are widely used benchmarks. Note that body fat naturally increases with age, so a 55-year-old at 24% body fat (male) is healthier than a 25-year-old at the same percentage by relative fitness standards." },
      { question: "How accurate is the Navy circumference method?", answer: "The US Navy circumference method has an error range of approximately ±3–4 percentage points compared to DEXA scans. This is sufficient for tracking trends over time, even if the absolute number is slightly off. Errors increase for people with unusual fat distribution patterns (high abdominal or hip fat relative to overall fatness). For higher accuracy, consider DEXA scanning (available at imaging centers and some gyms, ~$50–100), hydrostatic weighing (gold standard, available at universities and research facilities), or Bod Pod air displacement plethysmography." },
      { question: "How do I take accurate body measurements?", answer: "Use a flexible measuring tape and measure in the morning before eating or drinking, wearing minimal clothing. Stand upright and relaxed — don't suck in your stomach. For waist: men measure at the navel horizontally; women measure at the natural waist (narrowest point between ribs and hips). For neck: measure just below the larynx (Adam's apple), tilting head slightly down. For hips (women): measure at the widest point of the buttocks. Take two measurements and average them. Consistent technique matters more than absolute precision since you are tracking change over time." },
      { question: "What is visceral versus subcutaneous fat?", answer: "Subcutaneous fat sits just beneath the skin — you can pinch it. Visceral fat surrounds the abdominal organs and is metabolically active, secreting inflammatory compounds linked to insulin resistance, cardiovascular disease, and type 2 diabetes. Waist circumference and waist-to-hip ratio are proxies for visceral fat — a waist above 40 inches for men or 35 inches for women indicates elevated visceral fat even at normal body weight. High-intensity interval training and resistance exercise are particularly effective at reducing visceral fat beyond what diet alone achieves." },
      { question: "Can I have a normal BMI with high body fat?", answer: "Yes — this is called 'normal weight obesity' or 'skinny fat.' Someone who is sedentary, has little muscle mass, and carries proportional fat may have a BMI in the normal range (18.5–24.9) while having body fat above 25% (men) or 32% (women). Conversely, a heavily muscled athlete can have a BMI in the overweight range (25–29.9) with low body fat because muscle is denser than fat. This is why body fat percentage is a more meaningful fitness metric than BMI for many individuals, particularly those who exercise regularly or those who are otherwise sedentary." },
    ],
    relatedCalculators: ["bmi-calculator", "bmr-calculator", "ideal-weight-calculator"],
    status: "active",
    lastReviewed: "2026-08-22",
    sensitivity: "health",
    sourceUrl: "https://www.acefitness.org/resources/everyone/tools-calculators/body-fat-percentage-chart/",
  },
  {
    id: "ideal-weight",
    slug: "ideal-weight-calculator",
    category: "Health",
    categorySlug: "health",
    title: "Ideal Weight Calculator",
    shortDescription: "Find your ideal body weight range based on height using multiple formulas.",
    seoTitle: "Ideal Weight Calculator — Find Your Healthy Weight Range",
    metaDescription: "Calculate ideal body weight using Devine, Robinson, and Miller formulas. Find your healthy weight range by height and sex.",
    primaryKeyword: "ideal weight calculator",
    secondaryKeywords: ["healthy weight calculator", "ideal body weight", "weight for height calculator"],
    fields: [
      SEX_FIELD,
      SYSTEM_FIELD,
      { id: "height", label: "Height", type: "number", placeholder: "175", required: true, span: 1 as const, min: 0 },
    ],
    results: [
      { id: "devine", label: "Devine formula (kg)", format: "number", decimals: 1, isPrimary: true },
      { id: "robinson", label: "Robinson formula (kg)", format: "number", decimals: 1, isPrimary: false },
      { id: "miller", label: "Miller formula (kg)", format: "number", decimals: 1, isPrimary: false },
      { id: "bmi25", label: "BMI 25 target (kg)", format: "number", decimals: 1, isPrimary: false },
    ],
    formula: "Devine: 50 kg (M) / 45.5 kg (F) + 2.3 kg per inch over 5 ft",
    formulaExplanation: "The Devine formula (1974) was originally developed for drug dosing and has become a benchmark. Robinson (1983) and Miller (1983) adjusted Devine for different populations. BMI 25 calculates the weight at which BMI equals 25 (healthy/overweight boundary) for the given height. All formulas are based on height and sex alone and cannot account for body composition, frame size, or ethnicity.",
    formulaSource: "Devine BJ, 1974. Gentamicin therapy. Drug Intelligence & Clinical Pharmacy.",
    explanation: "Ideal weight formulas provide population-level estimates of healthy body weight based on height and sex. They were originally developed for medical purposes — particularly for calculating drug doses — and have been adapted for general health guidance. The most widely cited formulas (Devine, Robinson, Miller) were derived from actuarial and clinical data and generally agree within a few kilograms for the same height and sex. None of these formulas is definitively 'correct' because optimal weight varies significantly based on body composition, frame size, age, ethnicity, and individual health factors. A highly muscular individual may weigh well above any formula's output while being exceptionally healthy; a sedentary person at the formula's target weight may have high body fat and poor metabolic health. The BMI 25 target is included because BMI 25 represents the widely used clinical threshold between healthy weight and overweight, giving you the weight at which you would cross that boundary. The most meaningful goal for most people is not hitting a formula's number but achieving a body fat percentage in the healthy range while building sufficient muscle mass to support metabolic health, joint integrity, and functional independence as you age. Use these numbers as rough orientation, not as rigid targets.",
    example: {
      inputs: { sex: "male", system: "metric", height: 178 },
      explanation: "For a 178 cm (5'10\") male: Devine = 78 kg, Robinson = 78.2 kg, Miller = 77.7 kg, BMI 25 = 79.2 kg. These formulas are very consistent at this height.",
    },
    faqs: [
      { question: "Why do different ideal weight formulas give different results?", answer: "Each formula was derived from a different population sample and purpose. The Devine formula (1974) was created for pharmaceutical dosing, using a small dataset of primarily white American adults. Robinson (1983) and Miller (1983) re-derived coefficients from broader data to better represent diverse populations. They generally agree within 5–10% because they are all fundamentally linear extrapolations from height, but no formula is definitively superior for any individual — they are all simplifications of a complex biological relationship." },
      { question: "What weight should I actually aim for?", answer: "Rather than fixating on an ideal weight formula's number, aim for the weight at which you feel healthy, have good energy, are free from metabolic disease markers (normal blood pressure, blood sugar, cholesterol), and can perform the physical activities you enjoy. For most people, this falls within or near the BMI 18.5–24.9 range, but athletes may be healthier at BMI 26–28 due to high muscle mass. Body fat percentage (10–20% for men, 20–30% for women in general health ranges) is a more meaningful target than weight alone." },
      { question: "Does ideal weight differ by frame size?", answer: "Yes — classic weight charts like the Metropolitan Life tables included small, medium, and large frame categories, typically separated by wrist or elbow breadth measurements. Larger-framed individuals have heavier bones and broader skeletons, supporting more healthy tissue weight. Modern formulas generally don't adjust for frame size, which is one reason they are rough guides rather than individual prescriptions. A useful rule of thumb: wrap your thumb and middle finger around your wrist. If they overlap, you have a small frame; if they just touch, medium; if there is a gap, large — and your healthy weight range shifts a few kilos accordingly." },
      { question: "Should children use this calculator?", answer: "No — ideal weight formulas for adults are not appropriate for children and adolescents. Growth charts and BMI-for-age percentile charts (from the CDC or WHO) are the correct tools for assessing weight in people under 18. Children's healthy weight ranges depend on age, sex, and pubertal stage in ways that adult formulas do not account for. A pediatrician using age- and sex-adjusted growth charts is the appropriate resource for assessing a child's weight status." },
      { question: "What about ideal weight for pregnancy?", answer: "Weight recommendations during pregnancy are based on pre-pregnancy BMI and focus on total gestational weight gain rather than a target weight. The Institute of Medicine recommends: underweight (BMI <18.5): gain 28–40 lbs; normal weight: gain 25–35 lbs; overweight: gain 15–25 lbs; obese: gain 11–20 lbs. These recommendations balance fetal development needs against risks of excessive weight retention postpartum. Discuss your individual targets with your ob-gyn or midwife, who can account for factors specific to your pregnancy." },
    ],
    relatedCalculators: ["bmi-calculator", "body-fat-calculator", "bmr-calculator"],
    status: "active",
    lastReviewed: "2026-08-22",
    sensitivity: "health",
    sourceUrl: "https://www.ncbi.nlm.nih.gov/pubmed/4748548",
  },
  {
    id: "calorie-calculator",
    slug: "calorie-calculator",
    category: "Health",
    categorySlug: "health",
    title: "Calorie Calculator",
    shortDescription: "Calculate how many calories you need daily to reach your weight goal.",
    seoTitle: "Calorie Calculator — Daily Calorie Needs for Weight Loss or Gain",
    metaDescription: "Calculate your daily calorie needs for weight loss, maintenance, or muscle gain. Based on the Mifflin-St Jeor equation and your activity level.",
    primaryKeyword: "calorie calculator",
    secondaryKeywords: ["daily calorie needs", "calories to lose weight", "how many calories should I eat"],
    fields: [
      SEX_FIELD,
      { id: "age", label: "Age", type: "number", unit: "years", placeholder: "30", required: true, span: 1 as const, min: 10, max: 120 },
      SYSTEM_FIELD,
      { id: "weight", label: "Weight", type: "number", placeholder: "70", required: true, span: 1 as const, min: 0 },
      { id: "height", label: "Height", type: "number", placeholder: "170", required: true, span: 1 as const, min: 0 },
      ACTIVITY_FIELD,
      { id: "goal", label: "Goal", type: "select", required: true, span: 1 as const, defaultValue: "maintain", unitOptions: [
        { value: "lose", label: "Lose weight (−500 cal/day)" },
        { value: "maintain", label: "Maintain weight" },
        { value: "gain", label: "Gain weight (+500 cal/day)" },
      ]},
    ],
    results: [
      { id: "targetCalories", label: "Target calories / day", format: "number", decimals: 0, isPrimary: true },
      { id: "maintenance", label: "Maintenance calories", format: "number", decimals: 0, isPrimary: false },
      { id: "deficit", label: "Calorie adjustment", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Target = TDEE ± 500 based on goal; TDEE = Mifflin-St Jeor BMR × Activity Factor",
    formulaExplanation: "BMR uses the Mifflin-St Jeor equation. TDEE multiplies BMR by the activity factor. Goal adjustment adds or subtracts 500 calories: a 500-calorie daily deficit theoretically produces ~1 lb weight loss per week; a 500-calorie surplus supports muscle gain with adequate protein and resistance training.",
    formulaSource: "Mifflin MD, et al. 1990. A new predictive equation for resting energy expenditure in healthy individuals.",
    explanation: "The calorie calculator gives you a science-based daily calorie target aligned with your weight goal. Calories are units of energy, and your body weight is fundamentally governed by the energy balance equation: energy in (food and drink) versus energy out (metabolism and activity). Creating a consistent calorie deficit causes the body to use stored fat for energy, resulting in weight loss. Creating a surplus provides the energy substrate for muscle protein synthesis during resistance training, supporting muscle gain. The 500-calorie-per-day adjustment is the most commonly recommended approach because it creates a theoretical 1 lb (0.45 kg) weekly change — a rate that is sustainable, spares muscle mass, and doesn't trigger extreme hunger responses. More aggressive deficits (1,000 cal/day, ~2 lb/week) are sometimes appropriate under medical supervision but require careful protein intake management. Your target calories are an estimate based on population averages — individual metabolism varies by up to 15–20%. Track your actual weight trend over two to four weeks, and if it diverges from the expected rate, adjust your intake by 100–200 calories in the appropriate direction. Remember that calorie databases have inherent inaccuracies of 10–20%, and restaurant meals especially may contain significantly more calories than estimated.",
    example: {
      inputs: { sex: "female", age: 28, system: "metric", weight: 65, height: 165, activityLevel: "1.375", goal: "lose" },
      explanation: "A 28-year-old woman, 65 kg, 165 cm, lightly active has a TDEE of about 1,967 cal. Weight loss target: ~1,467 cal/day.",
    },
    faqs: [
      { question: "How many calories should I eat to lose weight?", answer: "The standard recommendation is to eat 500 fewer calories per day than your TDEE (maintenance level), creating a theoretical 1 lb per week loss. Most women should not eat below 1,200 calories per day and most men not below 1,500 calories — going lower risks nutrient deficiencies, metabolic slowdown, and unsustainable hunger. For moderate, sustainable loss, a 300–500 calorie daily deficit is ideal. Accuracy matters: most people underestimate their caloric intake by 20–40%, so careful food logging for at least two weeks gives you a reality check on actual intake." },
      { question: "Do calories from different foods matter equally?", answer: "At a purely energy balance level, a calorie is a calorie — eating 2,000 calories of junk food produces the same weight outcome as 2,000 calories of whole foods if all other variables are equal. However, different foods have very different effects on satiety, hormone regulation, and nutrient density. Protein (4 cal/g) has the highest satiety effect and the highest thermic effect (25–30% of calories burned in digestion). Fiber slows digestion and stabilizes blood sugar. Ultra-processed foods are engineered to be hyperpalatable and easy to overconsume. For health and adherence, food quality matters even if it doesn't alter the basic calorie math." },
      { question: "Is it possible to eat too few calories?", answer: "Yes — very low calorie intake (below roughly 1,000 calories/day for most adults) triggers metabolic adaptation: the body downregulates thyroid hormones, reduces spontaneous movement, and slows non-essential metabolic processes to conserve energy. This makes the predicted deficit smaller than calculated. Very low intake also causes muscle catabolism — the body breaks down muscle tissue for energy when calories are very restricted — which reduces metabolic rate long-term. Extreme restriction also risks micronutrient deficiencies, fatigue, impaired immune function, and hormonal disruption. Aim for the largest calorie intake at which you still achieve your target rate of change." },
      { question: "Should I eat back calories I burn exercising?", answer: "Whether to eat back exercise calories depends on how your TDEE was calculated. If you used an accurate activity multiplier that reflects your exercise (e.g., 'moderately active' at 3–5 days of exercise per week), your TDEE already includes those calories and you should not eat them back. If you started with a sedentary TDEE and added unplanned exercise, eating back a portion (50–75%) of the estimated burn is reasonable, since exercise calorie estimates from apps and fitness devices typically overestimate actual burn by 20–50%." },
      { question: "How do I count calories accurately?", answer: "Use a kitchen food scale for all solid foods — volume measurements are highly inaccurate for calorie-dense foods like nuts, cheese, oil, and nut butter. Log everything, including cooking oils, condiments, and beverages. Use a verified food database (USDA FoodData Central is the most accurate; apps like Cronometer or MyFitnessPal pull from it). For packaged foods, use the nutrition label and weigh the actual serving rather than trusting the listed serving size. For restaurant meals, use the restaurant's calorie information if available, or add a 20–30% buffer to online estimates since restaurant portions and cooking methods vary significantly." },
    ],
    relatedCalculators: ["tdee-calculator", "bmi-calculator", "macro-calculator"],
    status: "active",
    lastReviewed: "2026-08-22",
    sensitivity: "health",
    sourceUrl: "https://www.ncbi.nlm.nih.gov/pubmed/2305711",
  },
  {
    id: "protein-calculator",
    slug: "protein-calculator",
    category: "Health",
    categorySlug: "health",
    title: "Protein Calculator",
    shortDescription: "Calculate your daily protein needs based on weight and fitness goal.",
    seoTitle: "Protein Calculator — Daily Protein Intake for Your Goal",
    metaDescription: "Find out how much protein you need daily for weight loss, muscle building, or general health. Based on your body weight and activity goal.",
    primaryKeyword: "protein calculator",
    secondaryKeywords: ["daily protein intake", "how much protein do I need", "protein needs calculator"],
    fields: [
      SYSTEM_FIELD,
      { id: "weight", label: "Weight", type: "number", placeholder: "75", required: true, span: 1 as const, min: 0 },
      { id: "goal", label: "Goal / activity level", type: "select", required: true, span: 1 as const, defaultValue: "maintain", unitOptions: [
        { value: "sedentary", label: "Sedentary (minimal exercise)" },
        { value: "maintain", label: "Active / maintain" },
        { value: "lose", label: "Weight loss (preserve muscle)" },
        { value: "gain", label: "Muscle building" },
        { value: "athlete", label: "Endurance / strength athlete" },
      ]},
    ],
    results: [
      { id: "optimalProtein", label: "Optimal daily protein (g)", format: "number", decimals: 0, isPrimary: true },
      { id: "minProtein", label: "Minimum daily protein (g)", format: "number", decimals: 0, isPrimary: false },
      { id: "maxProtein", label: "Upper range (g)", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Protein (g) = Body Weight (kg) × multiplier (0.8–3.0 g/kg depending on goal)",
    formulaExplanation: "The WHO minimum is 0.8 g/kg/day to prevent deficiency. Active adults benefit from 1.2–2.0 g/kg. During calorie restriction to preserve muscle: 1.4–2.4 g/kg. For muscle building: 1.6–2.2 g/kg. Strength athletes may benefit from up to 2.4–3.1 g/kg. Multipliers represent the range from minimum to optimal based on current peer-reviewed evidence.",
    formulaSource: "Morton RW et al. 2018. A systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength. Br J Sports Med.",
    explanation: "Protein is the most important macronutrient for body composition, serving as the building block for muscle tissue, enzymes, hormones, and immune factors. Unlike carbohydrates and fats, the body has no dedicated storage depot for protein — excess is either used for energy or converted to fat. The minimum protein recommendation of 0.8 g/kg/day (from the WHO/RDA) was set to prevent deficiency, not to optimize muscle mass or health in active individuals. Research consistently shows that active adults benefit from substantially more protein — 1.6–2.0 g/kg/day — particularly when engaging in resistance training. During calorie restriction for weight loss, higher protein intake (1.8–2.4 g/kg) is especially important to preserve lean muscle mass, which keeps metabolism elevated and improves body composition outcomes. The body's ability to use protein for muscle protein synthesis appears to plateau around 2.2 g/kg for most people (excluding some elite strength athletes), so intakes significantly above this offer diminishing returns. Protein timing also matters: distributing intake across three to five meals, with 25–40 g per meal, maximizes muscle protein synthesis throughout the day rather than consuming most protein in one sitting.",
    example: {
      inputs: { system: "metric", weight: 80, goal: "gain" },
      explanation: "An 80 kg person building muscle needs 128–160 g/day (optimal range), with a minimum of 128 g and upper range of 192 g.",
    },
    faqs: [
      { question: "Can you eat too much protein?", answer: "For healthy adults, high protein intakes up to 2.5–3.0 g/kg body weight appear safe based on available evidence and don't damage healthy kidneys. However, individuals with pre-existing kidney disease should limit protein intake as directed by their physician, since damaged kidneys struggle to process protein metabolites. Very high protein intakes (above 3 g/kg) provide no additional muscle-building benefit and crowd out other nutrients. Additionally, high protein from processed meat sources carries independent health risks — lean meats, fish, legumes, and dairy are superior sources." },
      { question: "What are the best protein sources?", answer: "Complete proteins (containing all essential amino acids) include: animal sources (chicken, turkey, beef, fish, eggs, dairy) and some plant sources (soy, quinoa, hemp). Incomplete plant proteins (beans, rice, lentils, nuts) can be combined throughout the day to get all essential amino acids — you don't need to combine them in every meal. For muscle building, leucine-rich proteins (whey, eggs, beef) have the strongest muscle protein synthesis signal. For health more broadly, research supports emphasizing fish, legumes, and poultry over processed red meats." },
      { question: "When should I eat protein for best results?", answer: "Protein timing matters but is secondary to total daily intake. Research supports consuming 25–40 g of protein per meal to maximize per-meal muscle protein synthesis — amounts much below 20 g are less effective, and amounts above 40 g are used for energy rather than muscle building. For resistance training, consuming protein within 2 hours post-workout supports recovery and muscle adaptation, though the window is wider than once believed. A protein-rich breakfast helps manage hunger throughout the day. Most practically: distribute protein intake across three to five meals rather than concentrating it in one or two large meals." },
      { question: "Do plant-based eaters need more protein?", answer: "Plant proteins generally have lower digestibility and different amino acid profiles than animal proteins, which may reduce the effective protein available for muscle protein synthesis. Research suggests plant-based athletes may benefit from targeting the upper end of protein recommendations (1.8–2.2 g/kg) and ensuring adequate leucine intake (found in soy, legumes, and nuts). Well-planned plant-based diets that combine diverse protein sources can absolutely support muscle building — many elite plant-based athletes demonstrate this. Soy protein in particular has a protein quality score comparable to whey." },
      { question: "What about protein powders — are they necessary?", answer: "Protein powders are convenient but not necessary if you can meet your protein target through whole foods. They are particularly useful when: whole food options are limited (travel, busy schedules), appetite is low but protein needs are high, or post-workout intake is needed quickly. Whey protein (from milk) is the best-studied and most rapidly absorbed; casein (also from milk) absorbs slowly and is useful before sleep. Plant-based powders (pea, rice, soy blend) are comparable in muscle-building efficacy to whey when matched for leucine content. Look for third-party tested products (Informed Sport, NSF Certified) to ensure label accuracy." },
    ],
    relatedCalculators: ["macro-calculator", "calorie-calculator", "tdee-calculator"],
    status: "active",
    lastReviewed: "2026-08-22",
    sensitivity: "health",
    sourceUrl: "https://bjsm.bmj.com/content/52/6/376",
  },
  {
    id: "macro-calculator",
    slug: "macro-calculator",
    category: "Health",
    categorySlug: "health",
    title: "Macro Calculator",
    shortDescription: "Calculate protein, carb, and fat targets based on your daily calories and goal.",
    seoTitle: "Macro Calculator — Protein, Carbs & Fat Targets",
    metaDescription: "Calculate your daily macronutrient targets (protein, carbohydrates, fat) from your calorie goal. Supports balanced, low-carb, high-protein, keto, and athletic splits.",
    primaryKeyword: "macro calculator",
    secondaryKeywords: ["macronutrient calculator", "protein carbs fat calculator", "iifym calculator"],
    fields: [
      { id: "calories", label: "Daily calorie target", type: "number", unit: "cal", placeholder: "2200", required: true, span: 1 as const, min: 0 },
      { id: "goal", label: "Macro split", type: "select", required: true, span: 1 as const, defaultValue: "balanced", unitOptions: [
        { value: "balanced", label: "Balanced (30P / 40C / 30F)" },
        { value: "highProtein", label: "High protein (40P / 35C / 25F)" },
        { value: "lowCarb", label: "Low carb (35P / 20C / 45F)" },
        { value: "keto", label: "Keto (25P / 5C / 70F)" },
        { value: "athletic", label: "Athletic performance (25P / 50C / 25F)" },
      ]},
    ],
    results: [
      { id: "protein", label: "Protein (g/day)", format: "number", decimals: 0, isPrimary: true },
      { id: "carbs", label: "Carbohydrates (g/day)", format: "number", decimals: 0, isPrimary: false },
      { id: "fat", label: "Fat (g/day)", format: "number", decimals: 0, isPrimary: false },
      { id: "proteinCal", label: "Calories from protein", format: "number", decimals: 0, isPrimary: false },
      { id: "carbCal", label: "Calories from carbs", format: "number", decimals: 0, isPrimary: false },
      { id: "fatCal", label: "Calories from fat", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Protein: 4 cal/g; Carbohydrates: 4 cal/g; Fat: 9 cal/g. Grams = Calorie allotment / cal per gram",
    formulaExplanation: "The percentage splits are applied to total calories. Dividing protein calories by 4 converts to grams; carbohydrate calories by 4; fat calories by 9. For example, a balanced split on 2,200 calories: 660 protein calories ÷ 4 = 165g protein, 880 carb calories ÷ 4 = 220g carbs, 660 fat calories ÷ 9 = 73g fat.",
    formulaSource: "Dietary Reference Intakes, Institute of Medicine",
    explanation: "Macronutrient tracking — following specific protein, carbohydrate, and fat gram targets — is one of the most effective evidence-based strategies for body composition change and athletic performance. While total calories determine whether you gain or lose weight, macronutrient composition influences body composition (muscle vs. fat), energy levels, training performance, hormonal function, and dietary adherence. Protein targets should be set first based on body weight and goal (see our Protein Calculator), since adequate protein is non-negotiable for preserving muscle during a deficit or building it in a surplus. Carbohydrates are the primary fuel for intense exercise and should be prioritized for athletes and active individuals. Fat is essential for hormone production, fat-soluble vitamin absorption, and cell membrane integrity — very low fat diets (<20% of calories) can impair hormonal health. The IIFYM approach ('If It Fits Your Macros') popularized flexible dieting — hitting macro targets from any food sources, rather than eating only 'clean' foods. Research supports that flexible dieting produces equivalent body composition outcomes to rigid approaches while improving dietary adherence and psychological relationship with food. For best health outcomes, aim to hit your macro targets primarily from whole, minimally processed food sources.",
    example: {
      inputs: { calories: 2400, goal: "highProtein" },
      explanation: "At 2,400 calories with a high-protein split (40/35/25): 240g protein (960 cal), 210g carbs (840 cal), 67g fat (600 cal).",
    },
    faqs: [
      { question: "What is the best macro ratio for weight loss?", answer: "Research shows that no single macro ratio is universally best for weight loss — total calorie deficit determines weight loss, while macros influence body composition, satiety, and adherence. Higher protein intakes (35–40% of calories) during a deficit consistently improve lean mass retention and tend to reduce hunger. Both low-carb and higher-carb diets work when protein is equated and calories are controlled. Choose the macro ratio you can sustain long-term — the best diet is the one you'll actually follow consistently." },
      { question: "What is the ketogenic diet's macro split?", answer: "A standard ketogenic diet is very high fat (65–75% of calories), moderate protein (20–25%), and very low carbohydrate (5–10%, typically under 20–50 g/day). This restriction of carbohydrates forces the body into ketosis — a metabolic state where the liver produces ketone bodies from fat as an alternative fuel. Keto can be effective for weight loss (partly through appetite suppression) and has clinical applications for epilepsy and type 2 diabetes management. It requires eliminating most grains, legumes, and many fruits, which is why adherence is highly individual." },
      { question: "Should I count fiber in carbohydrate totals?", answer: "Fiber is technically a carbohydrate but is not fully digested or absorbed. In the US, total carbohydrates on nutrition labels include fiber. People following low-carb diets often track 'net carbs' (total carbs minus fiber) because fiber doesn't significantly affect blood sugar or ketosis. For general macro tracking, using total carbohydrates is simpler and more consistent with database entries. If you're following strict keto, subtracting fiber from total carbs gives a more accurate picture of metabolically active carbohydrate intake." },
      { question: "How do I track macros practically?", answer: "Use a food tracking app like Cronometer (more accurate food database) or MyFitnessPal. Weigh all solid foods on a kitchen scale — volume measures for calorie-dense foods are unreliable. Log everything before eating, not after, to make adjustments if a meal is off-target. For restaurant meals, use the restaurant's published nutrition data or a comparable database entry with a 20–30% buffer. Focus on hitting protein and total calories most precisely; carb and fat flexibility matters less. It takes most people 2–3 weeks to internalize portion sizes sufficiently that they can eat reasonably close to target without constant weighing." },
      { question: "Do macros matter, or just calories?", answer: "Both matter, but for different outcomes. Calories determine weight change direction (surplus = gain, deficit = loss). Macros determine body composition — the ratio of muscle to fat in that change. Two people on the same calorie deficit but different protein intakes will lose different amounts of muscle versus fat. For body recomposition goals (losing fat while preserving or gaining muscle), macros are critically important. For simple weight loss without performance goals, total calories are the dominant variable. For athletic performance, carbohydrate timing relative to training has meaningful effects on output and recovery." },
    ],
    relatedCalculators: ["calorie-calculator", "protein-calculator", "tdee-calculator"],
    status: "active",
    lastReviewed: "2026-08-22",
    sensitivity: "health",
    sourceUrl: "https://www.dietaryguidelines.gov/",
  },
  {
    id: "water-intake",
    slug: "water-intake-calculator",
    category: "Health",
    categorySlug: "health",
    title: "Water Intake Calculator",
    shortDescription: "Calculate your daily water intake needs based on weight, activity, and climate.",
    seoTitle: "Water Intake Calculator — Daily Hydration Needs",
    metaDescription: "Find out how much water you should drink per day based on your body weight, activity level, and climate. Free daily hydration calculator.",
    primaryKeyword: "water intake calculator",
    secondaryKeywords: ["daily water intake", "how much water should I drink", "hydration calculator"],
    fields: [
      SYSTEM_FIELD,
      { id: "weight", label: "Weight", type: "number", placeholder: "70", required: true, span: 1 as const, min: 0 },
      { id: "activityLevel", label: "Activity level", type: "select", required: true, span: 1 as const, defaultValue: "moderate", unitOptions: [
        { value: "sedentary", label: "Sedentary (office work, minimal exercise)" },
        { value: "moderate", label: "Moderate (light exercise 1–3×/week)" },
        { value: "active", label: "Active (intense exercise most days)" },
        { value: "veryActive", label: "Very active (athlete / hard labor)" },
      ]},
      { id: "climate", label: "Climate", type: "select", required: true, span: 1 as const, defaultValue: "temperate", unitOptions: [
        { value: "cold", label: "Cold / temperate" },
        { value: "temperate", label: "Moderate" },
        { value: "hot", label: "Hot / humid" },
      ]},
    ],
    results: [
      { id: "liters", label: "Daily water (liters)", format: "number", decimals: 1, isPrimary: true },
      { id: "cups", label: "Daily water (cups)", format: "number", decimals: 0, isPrimary: false },
      { id: "ounces", label: "Daily water (fl oz)", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Base = 33 ml/kg; add 500 ml for active, 1000 ml for very active; add 500 ml for hot climate",
    formulaExplanation: "The European Food Safety Authority and Institute of Medicine recommend approximately 30–35 ml/kg/day for sedentary adults as a base. Exercise and heat increase losses through sweat significantly. Each hour of intense exercise can cause 0.5–2 liters of sweat loss. Hot climates add basal losses through perspiration. Note: approximately 20% of water needs are met through food, so these numbers represent total water from all sources.",
    formulaSource: "EFSA Panel on Dietetic Products. 2010. Scientific Opinion on Dietary Reference Values for Water.",
    explanation: "Water is essential for virtually every physiological function: regulating body temperature, transporting nutrients and oxygen, flushing waste products, lubricating joints, enabling digestion, and supporting cognitive function. Adequate hydration is foundational to health, yet chronic mild dehydration is remarkably common and often goes unrecognized because thirst mechanisms can be subtle. The classic '8 glasses a day' (eight 8-oz glasses = 64 oz or about 1.9 liters) is a rough rule of thumb, but actual needs vary substantially based on body size, activity, climate, diet, and health status. A 50 kg sedentary office worker in a cool climate needs far less than a 90 kg athlete training in summer heat. Urine color is a practical hydration gauge: pale yellow indicates adequate hydration; dark yellow or amber signals dehydration. Clear urine can indicate over-hydration, which dilutes electrolytes. Athletes should also consider sodium and electrolyte replacement during extended sweat-loss sessions, since drinking water alone can dilute blood sodium dangerously (hyponatremia) in extreme endurance events. Many foods contribute significantly to water intake — fruits and vegetables are 80–95% water — so diet quality also affects hydration status.",
    example: {
      inputs: { system: "metric", weight: 70, activityLevel: "active", climate: "hot" },
      explanation: "A 70 kg active person in a hot climate: base 2.31 L + 0.5 L activity + 0.5 L climate = ~3.3 liters (14 cups / 112 fl oz) per day.",
    },
    faqs: [
      { question: "How do I know if I'm drinking enough water?", answer: "Urine color is the most practical hydration indicator available. Aim for pale straw yellow (like lemonade). Dark yellow or amber indicates you need more water; very dark (tea-colored) suggests significant dehydration. Completely clear urine may indicate over-hydration. Additional signs of dehydration include thirst (already a mild dehydration signal), dry mouth, headache, fatigue, reduced concentration, and decreased urine frequency (fewer than 4 times per day). Note that B-vitamin supplements can make urine bright yellow regardless of hydration status, so don't rely on color alone when supplementing." },
      { question: "Does coffee and tea count toward daily water intake?", answer: "Yes — despite the common belief that caffeine is dehydrating, research shows that caffeinated beverages (coffee, tea) in normal amounts (up to 4–6 cups per day) contribute net positive fluid to hydration. The mild diuretic effect of caffeine is far outweighed by the fluid volume consumed. Alcoholic beverages are a different matter: alcohol inhibits antidiuretic hormone, causing increased urinary output. Drinking one alcoholic drink reduces net fluid by roughly 50% of the volume consumed. This is why waking after drinking feels dehydrating — it is." },
      { question: "Can you drink too much water?", answer: "Yes — hyponatremia (low blood sodium from excess water intake) is a genuine medical risk, most commonly in endurance athletes who drink large amounts of plain water during prolonged events. Blood sodium dilution causes symptoms ranging from nausea and headache to confusion and, in severe cases, fatal cerebral edema. For everyday drinkers, the kidneys can handle up to about 1 liter per hour, so drinking more than that rate could theoretically be dangerous. In practice, normal thirst-driven drinking rarely causes hyponatremia in healthy people — the risk is specific to extreme exercise situations with forced large-volume water consumption." },
      { question: "Do I need to drink more during exercise?", answer: "Yes — sweat losses during exercise typically range from 0.5 to 2 liters per hour depending on intensity, ambient temperature, humidity, and individual sweat rate. For exercise under one hour, drinking water to thirst is adequate. For exercise over one hour, aim to replace 75–80% of estimated sweat losses during activity (full replacement during exercise can impair performance and cause GI distress). For events over two hours, electrolyte drinks containing sodium help replace salt lost in sweat and maintain the drive to drink. Weigh yourself before and after a long workout: each kilogram lost represents approximately 1 liter of fluid deficit." },
      { question: "Do children and older adults need different amounts?", answer: "Children have a higher body water percentage than adults and need relatively more water per kilogram but in smaller absolute amounts due to smaller body size. They are also more vulnerable to dehydration because their thirst response is less reliable. Older adults (65+) face the opposite problem: the sense of thirst diminishes with age, making it easier to become chronically dehydrated without feeling thirsty. Older adults should drink on a schedule rather than waiting for thirst signals, especially during hot weather or illness. Age-related kidney changes also affect the body's ability to concentrate urine, increasing baseline fluid needs." },
    ],
    relatedCalculators: ["calorie-calculator", "bmr-calculator", "tdee-calculator"],
    status: "active",
    lastReviewed: "2026-08-22",
    sensitivity: "health",
    sourceUrl: "https://efsa.onlinelibrary.wiley.com/doi/10.2903/j.efsa.2010.1459",
  },
  {
    id: "running-pace",
    slug: "running-pace-calculator",
    category: "Health",
    categorySlug: "health",
    title: "Running Pace Calculator",
    shortDescription: "Calculate your running pace per km or mile from distance and finish time.",
    seoTitle: "Running Pace Calculator — Pace Per Mile & Km",
    metaDescription: "Calculate your running pace per km or mile from distance and time. Find your speed in km/h and mph. Free running pace converter.",
    primaryKeyword: "running pace calculator",
    secondaryKeywords: ["pace calculator", "running speed calculator", "min per km calculator"],
    fields: [
      { id: "distance", label: "Distance", type: "number", placeholder: "10", required: true, span: 1 as const, min: 0, step: 0.01 },
      { id: "unit", label: "Distance unit", type: "select", required: true, span: 1 as const, defaultValue: "km", unitOptions: [
        { value: "km", label: "Kilometers" },
        { value: "miles", label: "Miles" },
      ]},
      { id: "hours", label: "Hours", type: "number", unit: "h", placeholder: "0", required: false, span: 1 as const, min: 0, defaultValue: 0 },
      { id: "minutes", label: "Minutes", type: "number", unit: "min", placeholder: "50", required: false, span: 1 as const, min: 0, max: 59, defaultValue: 0 },
      { id: "seconds", label: "Seconds", type: "number", unit: "sec", placeholder: "0", required: false, span: 1 as const, min: 0, max: 59, defaultValue: 0 },
    ],
    results: [
      { id: "pacePerKm", label: "Pace (min/km)", format: "number", decimals: 2, isPrimary: true },
      { id: "pacePerMile", label: "Pace (min/mile)", format: "number", decimals: 2, isPrimary: false },
      { id: "speed", label: "Speed (km/h)", format: "number", decimals: 2, isPrimary: false },
      { id: "speedMph", label: "Speed (mph)", format: "number", decimals: 2, isPrimary: false },
    ],
    formula: "Pace (min/km) = Total seconds ÷ Distance in km ÷ 60",
    formulaExplanation: "Total time is converted to seconds. Distance is converted to km or miles. Pace is total seconds divided by distance, then converted to minutes (divide by 60). Speed in km/h is distance in km divided by time in hours. The pace and speed values are mathematically linked: Speed (km/h) = 60 / Pace (min/km).",
    formulaSource: "Standard athletics calculation",
    explanation: "Running pace is the time it takes to cover a fixed unit of distance, usually expressed as minutes per kilometer or minutes per mile. It is the primary metric runners use to monitor training intensity, plan race strategy, and track fitness improvements over time. Pace and speed are directly related but inverse: a faster pace (lower min/km number) corresponds to a higher speed (higher km/h). Most training programs use pace zones to structure effort levels: easy recovery runs at conversational pace (slow), tempo runs at comfortably hard effort (moderate-fast), and intervals at 5K race pace or faster (fast). For race planning, knowing your pace goal lets you calculate split times to pace yourself evenly rather than starting too fast and fading. A common marathon strategy is negative splitting — running the second half slightly faster than the first — which requires disciplined early-mile pacing. This calculator converts between distance, time, pace, and speed to help you plan training runs and races precisely. Common reference paces: a 30-minute 5K requires 6:00/km pace; a sub-4-hour marathon requires 5:41/km; a Boston Marathon qualifier for a 35-year-old male requires 5:06/km.",
    example: {
      inputs: { distance: 10, unit: "km", hours: 0, minutes: 55, seconds: 0 },
      explanation: "A 10 km run in 55:00 is a pace of 5:30/km (8:51/mile) at 10.9 km/h (6.8 mph).",
    },
    faqs: [
      { question: "What is a good running pace for beginners?", answer: "A good beginner's pace is whatever allows you to run continuously while still being able to hold a conversation — usually 7–9 minutes per kilometer (11–14 min/mile) for most beginners, though highly deconditioned individuals may start even slower. The 80/20 rule of training suggests 80% of runs should be at an easy, conversational effort. Running faster than this before building aerobic base leads to injury and burnout. Speed comes naturally as fitness improves — focus on building consistent mileage and time on feet first." },
      { question: "What pace should I aim for in my first 5K?", answer: "For a first 5K, the goal should be to finish comfortably without walking, not to hit a specific time. If you've been running for 2–3 months, a time between 28–40 minutes is common for first-timers. The Couch to 5K program (C25K) prepares most beginners to finish in 30–45 minutes. Aim to run the first kilometer at a pace that feels easy — most first-timers start too fast and struggle later. A pace of 7:00–8:00/km allows most fit beginners to finish without extreme discomfort." },
      { question: "How do I calculate my race pace for a target finish time?", answer: "Divide your target finish time (in minutes) by the race distance. For a 1:50:00 half marathon (110 minutes): 110 ÷ 21.1 km = 5:12/km pace. For a 4:00:00 marathon: 240 ÷ 42.2 km = 5:41/km. With this calculator, enter your target distance and time to get your required pace. Practice that pace in training at tempo efforts to develop the feel for it before race day. Planning even splits (same pace throughout) is simpler for beginners; experienced runners often experiment with negative splits." },
      { question: "What factors affect running pace?", answer: "Running pace is influenced by: aerobic fitness (VO2 max), running economy (efficiency of movement), heat and humidity (performance drops significantly above 20°C/68°F), altitude (reduced oxygen availability), terrain (hills slow pace, trails vs roads), sleep and recovery status, hydration and nutrition, shoe type (modern carbon-fiber racing shoes improve economy by 4%), and psychological factors. Race day conditions rarely match training conditions exactly, so building in a buffer for heat, wind, or hills is wise when setting realistic goals." },
      { question: "How can I improve my running pace?", answer: "The most evidence-supported approaches to improving pace: increase weekly mileage gradually (no more than 10% per week) to build aerobic base; include one weekly tempo run (sustained comfortably-hard effort for 20–40 minutes) to improve lactate threshold; add strides (short accelerations) after easy runs to develop efficiency at faster cadences; include one interval session per week (e.g., 6×1 km at 5K race effort with equal recovery) to increase VO2 max; and prioritize sleep and recovery, since adaptation occurs between runs, not during them." },
    ],
    relatedCalculators: ["calories-burned-calculator", "bmi-calculator", "heart-rate-calculator"],
    status: "active",
    lastReviewed: "2026-08-22",
    sensitivity: "health",
    sourceUrl: "https://www.runnersworld.com/training/",
  },
  {
    id: "heart-rate",
    slug: "heart-rate-calculator",
    category: "Health",
    categorySlug: "health",
    title: "Heart Rate Zone Calculator",
    shortDescription: "Find your maximum heart rate and training zones using the Karvonen method.",
    seoTitle: "Heart Rate Zone Calculator — Training Zones by Age",
    metaDescription: "Calculate your maximum heart rate and 5 heart rate training zones using the Karvonen method. Optimize your cardio training for fat burn, endurance, and performance.",
    primaryKeyword: "heart rate zone calculator",
    secondaryKeywords: ["heart rate zones", "max heart rate calculator", "training zones by heart rate"],
    fields: [
      { id: "age", label: "Age", type: "number", unit: "years", placeholder: "35", required: true, span: 1 as const, min: 10, max: 100 },
      { id: "restingHR", label: "Resting heart rate (optional)", type: "number", unit: "bpm", placeholder: "60", required: false, span: 1 as const, min: 30, max: 100, defaultValue: 60, helpText: "Measure first thing in the morning for best accuracy" },
    ],
    results: [
      { id: "maxHR", label: "Estimated max heart rate", format: "number", decimals: 0, isPrimary: true },
      { id: "zone1Low", label: "Zone 1 low (warm-up)", format: "number", decimals: 0, isPrimary: false },
      { id: "zone2High", label: "Zone 2 high (fat burn / base)", format: "number", decimals: 0, isPrimary: false },
      { id: "zone3High", label: "Zone 3 high (aerobic / tempo)", format: "number", decimals: 0, isPrimary: false },
      { id: "zone4High", label: "Zone 4 high (lactate threshold)", format: "number", decimals: 0, isPrimary: false },
      { id: "zone5High", label: "Zone 5 (VO2 max)", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Max HR = 220 − age; Zone boundaries via Karvonen: Zone bpm = resting HR + (max HR − resting HR) × %",
    formulaExplanation: "The 220-minus-age formula is a population average with a standard deviation of ±10–12 bpm — individual max HR can differ significantly. The Karvonen method uses Heart Rate Reserve (HRR = maxHR − resting HR) to compute zone boundaries: Zone 1 is 50–60% HRR, Zone 2 is 60–70%, Zone 3 is 70–80%, Zone 4 is 80–90%, Zone 5 is 90–100%. This method is more accurate than simply using percentages of max HR.",
    formulaSource: "Karvonen MJ, Kentala E, Mustala O. 1957. The effects of training on heart rate. Ann Med Exp Biol Fenn.",
    explanation: "Heart rate zones are bands of cardiovascular intensity used to structure aerobic training. Training in different zones produces different physiological adaptations, making heart rate monitoring a powerful tool for matching training effort to specific fitness goals. Zone 1 (50–60% HRR) is warm-up and active recovery — very light effort used to increase blood flow without taxing recovery. Zone 2 (60–70%) is the aerobic base zone: sustainable for hours, it builds mitochondrial density, fat oxidation efficiency, and cardiovascular health — the foundation of endurance. Zone 3 (70–80%) is a moderate aerobic effort that crosses into anaerobic contribution; useful but often overused at the expense of Zone 2 and Zone 5. Zone 4 (80–90%) is near the lactate threshold — the intensity at which lactate accumulates faster than it clears; tempo runs and sustained intervals target this zone to raise the threshold and improve race pace. Zone 5 (90–100%) is maximal effort for short intervals; it develops VO2 max (maximum oxygen consumption capacity), the single greatest predictor of cardiovascular fitness and longevity. Research increasingly shows that 80% of training in Zones 1–2 and 20% in Zones 4–5 (the 80/20 or polarized model) produces superior results to spending most time in Zone 3.",
    example: {
      inputs: { age: 35, restingHR: 58 },
      explanation: "Age 35, resting HR 58: max HR = 185 bpm, HRR = 127. Zone 1: 122–134 bpm, Zone 2: 134–147 bpm, Zone 3: 147–160 bpm, Zone 4: 160–172 bpm, Zone 5: 172–185 bpm.",
    },
    faqs: [
      { question: "Is 220 minus age an accurate way to find max heart rate?", answer: "It is a useful population average but has significant individual variation — the standard deviation is about ±10–12 bpm, meaning roughly two-thirds of people fall within 10 bpm of the formula's prediction, but the remaining third fall outside that range. For general fitness purposes, the formula is adequate. For serious athletes, determining actual max HR through a maximal effort test (e.g., a 3–5 km all-out run with a final hill sprint) is more accurate. Some coaches prefer the formula 207 − (0.7 × age), which has slightly better fit at older ages." },
      { question: "What is Zone 2 training and why is it popular?", answer: "Zone 2 (60–70% HRR, conversational pace) has gained enormous popularity based on research and practitioner advice from figures like Dr. Peter Attia and Iñigo San Millán. At this intensity, mitochondria are maximally stimulated to develop their fat-oxidation capacity — the ability to burn fat efficiently for sustained energy. Most endurance athletes should spend 75–80% of training in Zone 2. Despite its low intensity, high volume Zone 2 training dramatically improves aerobic capacity, metabolic health, insulin sensitivity, and longevity markers. If you can hold a full conversation without shortness of breath, you are likely in Zone 2." },
      { question: "What is my resting heart rate and is it important?", answer: "Resting heart rate (RHR) is your heart rate when completely at rest — typically measured first thing in the morning before getting out of bed. Average RHR for adults is 60–100 bpm. Athletes often have RHRs of 40–60 bpm due to increased cardiac stroke volume (each beat pumps more blood). A lower RHR is generally associated with better cardiovascular fitness and lower cardiac mortality risk. A sudden increase in RHR (5–10 bpm above baseline) often signals incomplete recovery, illness, or overtraining — tracking RHR daily is a valuable monitoring tool." },
      { question: "Can I use my phone or watch for heart rate training?", answer: "Modern optical heart rate sensors in smartwatches (Apple Watch, Garmin, Polar) are accurate enough for Zone 2 and general aerobic training, typically within ±5% under steady-state conditions. Accuracy drops during high-intensity intervals due to motion artifact and the nature of pulse wave measurement. For serious threshold and interval work, a chest strap heart rate monitor (Polar H10, Garmin HRM-Pro) is significantly more accurate and responds more quickly to effort changes. Regardless of device accuracy, consistency in measurement is more important than absolute accuracy — track trends over time." },
      { question: "Is high-intensity interval training better than steady-state cardio?", answer: "Both have distinct benefits and the evidence supports using both, not choosing between them. High-intensity interval training (HIIT, Zone 4–5) produces large VO2 max improvements in less time but is taxing on recovery and can't be done daily. Steady-state Zone 2 builds aerobic base, fat-burning capacity, and mitochondrial density with minimal recovery cost — allowing high training frequency. The most robust model from elite endurance athlete research is the polarized or 80/20 model: 75–80% of sessions in Zone 1–2 (very easy), 5–10% in Zone 3, and 15–20% in Zone 4–5 (high intensity). This produces superior adaptations to training predominantly in the 'moderate' Zone 3 that many recreational athletes default to." },
    ],
    relatedCalculators: ["bmr-calculator", "calories-burned-calculator", "running-pace-calculator"],
    status: "active",
    lastReviewed: "2026-08-22",
    sensitivity: "health",
    sourceUrl: "https://www.heart.org/en/healthy-living/fitness/fitness-basics/target-heart-rates",
  },
  {
    id: "calories-burned",
    slug: "calories-burned-calculator",
    category: "Health",
    categorySlug: "health",
    title: "Calories Burned Calculator",
    shortDescription: "Estimate calories burned during exercise using MET values and body weight.",
    seoTitle: "Calories Burned Calculator — Exercise Calorie Estimator",
    metaDescription: "Calculate calories burned during any activity using MET values and your body weight. Supports running, cycling, swimming, strength training, and more.",
    primaryKeyword: "calories burned calculator",
    secondaryKeywords: ["exercise calorie calculator", "how many calories burned", "workout calorie counter"],
    fields: [
      SYSTEM_FIELD,
      { id: "weight", label: "Weight", type: "number", placeholder: "75", required: true, span: 1 as const, min: 0 },
      { id: "activity", label: "Activity", type: "select", required: true, span: 1 as const, defaultValue: "4", unitOptions: [
        { value: "14.5", label: "Running (10 km/h, 6 min/km)" },
        { value: "11.5", label: "Running (8 km/h, 7:30/km)" },
        { value: "8", label: "Running (slow jog, 6 km/h)" },
        { value: "7.5", label: "Cycling (vigorous, 16–19 mph)" },
        { value: "5.8", label: "Cycling (moderate, 12–14 mph)" },
        { value: "9.8", label: "Swimming laps (vigorous)" },
        { value: "6", label: "Swimming (moderate)" },
        { value: "4", label: "Brisk walking (5–6 km/h)" },
        { value: "2.5", label: "Walking (4 km/h)" },
        { value: "8", label: "Weight training (vigorous)" },
        { value: "3.5", label: "Weight training (moderate)" },
        { value: "8", label: "HIIT / circuit training" },
        { value: "5", label: "Yoga / pilates" },
        { value: "7.8", label: "Jump rope" },
        { value: "4.5", label: "Elliptical (moderate)" },
        { value: "3", label: "Leisurely bike ride" },
        { value: "2.3", label: "Household chores" },
      ]},
      { id: "met", label: "Custom MET value (override)", type: "number", placeholder: "", required: false, span: 1 as const, min: 0, step: 0.1, helpText: "Optional: enter MET value directly. 1 = rest, 3–5 = moderate, 7–9 = vigorous" },
      { id: "duration", label: "Duration", type: "number", unit: "minutes", placeholder: "45", required: true, span: 1 as const, min: 0 },
    ],
    results: [
      { id: "calories", label: "Calories burned", format: "number", decimals: 0, isPrimary: true },
      { id: "caloriesPerHour", label: "Calories per hour", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Calories/min = (MET × 3.5 × weight_kg) / 200 × duration_min",
    formulaExplanation: "The MET (Metabolic Equivalent of Task) is a standardized measure of activity intensity: 1 MET equals the energy expended at rest. Walking briskly is about 4 METs; running vigorously is 11–14 METs. The Ainsworth MET formula converts MET, body weight, and duration into calories: (MET × 3.5 × kg / 200) × minutes gives calories per minute. Total calories is calories per minute times duration.",
    formulaSource: "Ainsworth BE et al., 2011. Compendium of Physical Activities. Med Sci Sports Exerc.",
    explanation: "The Metabolic Equivalent of Task (MET) system is the scientific standard for quantifying the energy cost of physical activities. Each activity has an assigned MET value based on measured oxygen consumption during that activity relative to rest (1 MET). This allows a universal formula to estimate calorie burn from any activity using just body weight and duration — no need for expensive metabolic testing equipment. The formula systematically accounts for the fact that heavier individuals burn more calories doing the same activity (more mass to move) and that higher-intensity activities (higher MET) burn proportionally more. Important caveats: all calorie burn estimates have substantial individual variation (±20–30%) due to differences in fitness level, movement efficiency, and metabolism. Exercise equipment (treadmills, ellipticals) tend to overestimate calorie burn by 10–30%. The afterburn effect (EPOC — excess post-exercise oxygen consumption) after intense exercise adds additional calories not captured here but is often modest (50–200 cal) outside very high-intensity sessions. These estimates are best used for relative comparisons between activities and for rough planning, not as precise measurements.",
    example: {
      inputs: { system: "metric", weight: 75, met: "8", duration: 45 },
      explanation: "A 75 kg person doing vigorous weight training (MET 8) for 45 minutes burns approximately 473 calories.",
    },
    faqs: [
      { question: "Are calorie burn estimates from fitness trackers accurate?", answer: "Fitness tracker and cardio machine calorie estimates are generally 10–30% inaccurate, and sometimes more. Optical heart rate sensors are accurate for steady-state cardio but less so for intervals. Studies consistently show that cardio machines (especially ellipticals) overestimate calorie burn significantly — often by 20–30%. Heart rate-based estimates from devices like Apple Watch are better calibrated but still vary by ±10–15% for most users. The MET method used in this calculator has similar accuracy. For tracking energy balance, use these numbers as estimates and focus on consistency of method rather than absolute accuracy." },
      { question: "What is EPOC and does it significantly increase calorie burn?", answer: "EPOC (Excess Post-Exercise Oxygen Consumption) is the elevated metabolism that persists after exercise as the body restores oxygen stores, clears lactate, repairs muscle, and processes the hormonal response. High-intensity exercise (HIIT, heavy strength training) produces greater and longer EPOC than steady-state cardio. In practice, EPOC adds approximately 6–15% to the calories burned during the session — meaningful but not transformative. A 400-calorie HIIT session might add 24–60 extra calories through EPOC. The benefit is real but often overstated in fitness marketing." },
      { question: "How do I burn more calories exercising?", answer: "The primary variables are intensity (MET value) and duration. A higher-intensity activity burns more per minute; longer duration burns more total. Practically: running burns more than walking; vigorous cycling burns more than leisure cycling. Body weight is also a factor — heavier individuals burn more calories doing the same activity. Beyond these basics: adding resistance training builds muscle mass, which slightly elevates resting metabolic rate; compound exercises (squats, deadlifts, rows) recruit more muscle mass and burn more energy than isolation exercises; combining cardio and strength in circuit training maximizes caloric density per unit time." },
      { question: "What is a MET value and how is it used?", answer: "MET (Metabolic Equivalent of Task) is the ratio of a person's working metabolic rate to their resting metabolic rate. 1 MET equals approximately 3.5 ml O₂/kg/min — the oxygen consumption at rest. An activity with MET 4 requires four times the energy of rest. Light activities are 1.5–3 METs; moderate are 3–6; vigorous are 6+ METs. The Compendium of Physical Activities (Ainsworth et al.) catalogues over 800 activities with their MET values, making it the authoritative reference for exercise energy expenditure research and public health guidelines." },
      { question: "Should I eat back calories burned through exercise?", answer: "This depends on how you calculated your calorie target. If your target already uses a TDEE that accounts for exercise (e.g., 'moderately active' means you've already built exercise into your maintenance calories), don't eat back exercise calories — they're already included. If you used a sedentary TDEE and exercise is additional, eating back 50–75% of estimated exercise calories is reasonable, since exercise devices overestimate burn. Athletes in heavy training should fuel adequately for performance and recovery rather than maintaining a strict deficit during high training volume weeks." },
    ],
    relatedCalculators: ["tdee-calculator", "bmi-calculator", "running-pace-calculator"],
    status: "active",
    lastReviewed: "2026-08-22",
    sensitivity: "health",
    sourceUrl: "https://sites.google.com/site/compendiumofphysicalactivities/",
  },
];
