import type { CalculatorDefinition } from "../types";

export const logisticsWave3Calculators: CalculatorDefinition[] = [
  {
    id: "dimensional-weight",
    slug: "dimensional-weight-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Dimensional Weight Calculator",
    shortDescription: "Find dimensional and billable shipping weight.",
    seoTitle: "Dimensional Weight Calculator — DIM & Billable Weight",
    metaDescription: "Free dimensional weight calculator. Enter package length, width, height, and a DIM divisor to find volumetric weight and the billable weight carriers charge.",
    primaryKeyword: "dimensional weight calculator",
    secondaryKeywords: ["dim weight calculator", "volumetric weight calculator", "billable weight calculator"],
    slugEs: "calculadora-de-peso-volumetrico",
    titleEs: "Calculadora de Peso Volumétrico",
    shortDescriptionEs: "Calcula el peso volumétrico y facturable de envíos.",
    seoTitleEs: "Calculadora de Peso Volumétrico — Peso DIM y Facturable",
    metaDescriptionEs: "Calculadora de peso volumétrico gratuita. Introduce el largo, ancho y alto del paquete y un divisor DIM para hallar el peso volumétrico y el peso facturable que cobran los transportistas.",
    primaryKeywordEs: "calculadora de peso volumetrico",
    secondaryKeywordsEs: ["calculadora de peso dim", "peso volumetrico envios", "calculadora de peso facturable"],
    formulaExplanationEs: "El peso volumétrico cobra el espacio que ocupa un paquete en lugar de su masa, por eso multiplicar las tres dimensiones da el volumen en pulgadas cúbicas y dividir por el divisor DIM del transportista convierte ese volumen en un peso equivalente. La fórmula funciona porque un camión o un avión llena su cubicaje mucho antes de alcanzar su límite de peso, así que los transportistas facturan el mayor entre el peso real y el volumétrico para recuperar el valor del espacio que consume una caja ligera y voluminosa.",
    explanationEs: "El peso volumétrico, a menudo llamado peso DIM, es la forma en que los transportistas modernos cobran por el espacio que ocupa un paquete en lugar de solo por lo que pesa. Esta calculadora de peso volumétrico multiplica el largo, el ancho y el alto, divide por el divisor DIM del transportista y devuelve el peso volumétrico junto con el peso facturable que realmente pagarás. Como los camiones y los aviones se quedan sin espacio antes que sin capacidad de carga, una caja grande pero ligera puede costar mucho más de enviar de lo que sugiere su peso en la báscula.\n\nEntender el peso DIM es importante para cualquiera que envíe productos, desde vendedores de comercio electrónico que fijan precios de cumplimiento hasta equipos de almacén que negocian contratos con transportistas. Introduce tus dimensiones en pulgadas y el divisor que usa tu transportista, y la herramienta muestra si el paquete se factura por peso real o volumétrico, que siempre es el mayor de los dos.\n\nEl cálculo funciona porque el divisor DIM codifica una densidad supuesta: un divisor de 139 trata cada 139 pulgadas cúbicas como una libra. Añade tu peso real y la calculadora elige la cifra facturable automáticamente, para que puedas ajustar el tamaño de las cajas, reducir el relleno y prever los costes de flete antes de que se imprima una etiqueta.",
    exampleEs: { inputs: { length: 12, width: 12, height: 12, divisor: 139 }, explanation: "12 × 12 × 12 = 1.728 in³; 1.728 ÷ 139 ≈ 12,43 lb de peso volumétrico." },
    faqsEs: [
      {
        question: "¿Qué es un divisor DIM y cuál debo usar?",
        answer: "Un divisor DIM convierte el tamaño cúbico en un peso asumiendo una densidad estándar. Los divisores nacionales comunes son 139 para pulgadas y libras, aunque los transportistas usan 138, 166 o equivalentes métricos según el servicio y el contrato. Confirma siempre el divisor exacto en tu acuerdo, porque un divisor más pequeño produce un peso volumétrico mayor y un cargo de envío más alto para la misma caja.",
      },
      {
        question: "¿Cómo se decide el peso facturable?",
        answer: "El peso facturable es simplemente el mayor entre el peso real en báscula de un paquete y su peso volumétrico. Los transportistas comparan los dos y cobran el que sea más alto, así que una caja pesada y compacta se factura por peso real mientras que una caja ligera y voluminosa se factura por peso volumétrico. Introducir tu peso real permite que esta calculadora señale qué cifra aplica y evita sorpresas en la factura.",
      },
      {
        question: "¿Por qué cobran los transportistas por peso volumétrico?",
        answer: "Los vehículos de reparto y los aviones llenan su espacio cúbico disponible mucho antes de alcanzar su carga máxima. Si los transportistas facturaran solo por masa, un remolque lleno de cajas ligeras y sobredimensionadas ganaría mucho menos de lo que vale su capacidad. El peso volumétrico recupera el valor de ese espacio ocupado y anima a los expedidores a usar embalajes del tamaño adecuado y reducir el volumen desperdiciado en toda la red.",
      },
      {
        question: "¿Puedo reducir mi peso volumétrico?",
        answer: "Sí. Como el peso volumétrico depende solo del tamaño de la caja, reducir cualquier dimensión lo baja. Usa embalajes que se ajusten bien al producto, elimina el relleno excesivo y evita cajas sobredimensionadas para artículos pequeños. Incluso recortar un par de pulgadas del lado más largo puede bajar un paquete a un tramo de facturación inferior, así que probar cajas más ajustadas es una de las formas más rápidas de reducir el gasto de envío.",
      },
      {
        question: "¿El peso volumétrico también aplica a la carga y los palés?",
        answer: "Los transportistas de paquetería dependen sobre todo del peso volumétrico, pero el flete de carga fraccionada usa un concepto relacionado llamado densidad para asignar la clase de flete. Los palés y los envíos grandes se tarifan por peso, dimensiones y la eficiencia con la que llenan el espacio. El principio es el mismo: el espacio cuesta dinero. Para envíos en palé, combinar esta herramienta con una calculadora de densidad de flete da una imagen más completa.",
      },
    ],
    fields: [
      { id: "length", label: "Length", type: "number", unit: "in", required: true, span: 1, min: 0 },
      { id: "width", label: "Width", type: "number", unit: "in", required: true, span: 1, min: 0 },
      { id: "height", label: "Height", type: "number", unit: "in", required: true, span: 1, min: 0 },
      { id: "divisor", label: "DIM divisor", type: "number", required: false, span: 1, min: 1, defaultValue: 139, helpText: "Carrier factor (139 for domestic in³/lb). Defaults to 139." },
      { id: "actualWeight", label: "Actual weight", type: "number", unit: "lb", required: false, span: 2, min: 0, helpText: "Optional. Billable weight is the greater of actual and dimensional." },
    ],
    results: [
      { id: "dimWeight", label: "Dimensional weight", format: "number", decimals: 2, unit: "lb", isPrimary: true },
      { id: "billableWeight", label: "Billable weight", format: "number", decimals: 2, unit: "lb", isPrimary: false },
    ],
    formula: "DIM weight = (length × width × height) ÷ divisor",
    formulaExplanation: "Dimensional weight prices the space a parcel occupies rather than its mass, so multiplying the three dimensions gives cubic volume and dividing by the carrier's DIM divisor converts that volume into an equivalent weight. The formula works because a truck or plane fills its cube long before it hits its weight limit, so carriers bill the greater of actual and dimensional weight to recover the value of the room a light, bulky box consumes.",
    explanation: "Dimensional weight, often shortened to DIM weight, is how modern carriers charge for the space a package takes up instead of just how heavy it is. This dimensional weight calculator multiplies length, width, and height, divides by the carrier's DIM divisor, and returns the volumetric weight along with the billable weight you will actually pay for. Because trucks and aircraft run out of room before they run out of payload, a large but lightweight box can cost far more to ship than its scale weight suggests.\n\nUnderstanding DIM weight matters for anyone shipping products, from ecommerce sellers pricing fulfilment to warehouse teams negotiating carrier contracts. Enter your dimensions in inches and the divisor your carrier uses, and the tool shows whether the parcel is billed on actual or dimensional weight, which is always the higher of the two.\n\nThe calculation works because the DIM divisor encodes an assumed density: a divisor of 139 treats every 139 cubic inches as one pound. Add your real package weight and the calculator picks the billable figure automatically, so you can right-size boxes, cut void fill, and forecast freight costs before a shipment ever leaves the dock or a label is printed.",
    example: { inputs: { length: 12, width: 12, height: 12, divisor: 139 }, explanation: "12 × 12 × 12 = 1,728 in³; 1,728 ÷ 139 ≈ 12.43 lb dimensional weight." },
    faqs: [
      {
        question: "What is a DIM divisor and which one do I use?",
        answer: "A DIM divisor converts cubic size into a weight by assuming a standard density. Common domestic divisors are 139 for inches and pounds, though carriers use 138, 166, or metric equivalents depending on the service and contract. Always confirm the exact divisor in your carrier agreement, because a smaller divisor produces a larger dimensional weight and a higher shipping charge for the same box.",
      },
      {
        question: "How is billable weight decided?",
        answer: "Billable weight is simply the greater of a parcel's actual scale weight and its dimensional weight. Carriers compare the two and charge whichever is higher, so a heavy, compact box bills on actual weight while a light, bulky box bills on dimensional weight. Entering your real weight lets this calculator flag which figure applies, helping you avoid surprises when the freight invoice arrives.",
      },
      {
        question: "Why do carriers charge by dimensional weight?",
        answer: "Delivery vehicles and aircraft fill their available cubic space long before they reach their maximum payload. If carriers billed only by mass, a trailer packed with light, oversized boxes would earn far less than its capacity is worth. Dimensional weight recovers the value of that occupied space, encouraging shippers to use right-sized packaging and reduce wasted volume across the entire distribution network.",
      },
      {
        question: "Can I reduce my dimensional weight?",
        answer: "Yes. Because dimensional weight depends only on the box size, shrinking any dimension lowers it. Use packaging that fits the product closely, remove excess void fill, and avoid oversized cartons for small items. Even trimming a couple of inches from the longest side can drop a parcel into a lower billing tier, so testing tighter box sizes is one of the fastest ways to cut shipping spend.",
      },
      {
        question: "Does dimensional weight apply to freight and pallets too?",
        answer: "Parcel carriers rely most heavily on dimensional weight, but less-than-truckload freight uses a related concept called density to assign freight class. Pallets and large shipments are rated on weight, dimensions, and how efficiently they fill space. The principle is the same: space costs money. For pallet shipments, pairing this tool with a freight density calculator gives a fuller picture of your costs.",
      },
    ],
    relatedCalculators: ["cbm-calculator", "freight-density-calculator", "container-loading-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "cbm",
    slug: "cbm-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "CBM Calculator",
    shortDescription: "Calculate cubic metres and volumetric weight.",
    seoTitle: "CBM Calculator — Cubic Metres & Volumetric Weight",
    metaDescription: "Free CBM calculator. Enter carton length, width, height, and quantity in centimetres to find total cubic metres and the volumetric weight used for sea and air.",
    primaryKeyword: "cbm calculator",
    secondaryKeywords: ["cubic meter calculator", "volumetric weight calculator", "shipping volume calculator"],
    slugEs: "calculadora-de-cbm",
    titleEs: "Calculadora de CBM",
    shortDescriptionEs: "Calcula metros cúbicos y peso volumétrico.",
    seoTitleEs: "Calculadora de CBM — Metros Cúbicos y Peso Volumétrico",
    metaDescriptionEs: "Calculadora de CBM gratuita. Introduce el largo, ancho, alto y cantidad de cartones en centímetros para hallar los metros cúbicos totales y el peso volumétrico usado en flete marítimo y aéreo.",
    primaryKeywordEs: "calculadora de cbm",
    secondaryKeywordsEs: ["calculadora de metros cubicos", "calculadora de peso volumetrico", "calculadora de volumen de envio"],
    formulaExplanationEs: "El CBM mide los metros cúbicos que ocupa un envío, así que multiplicar el largo, el ancho y el alto en centímetros da centímetros cúbicos, y dividir por un millón los convierte en metros cúbicos. Multiplicar por la cantidad suma todos los cartones idénticos. La fórmula funciona porque un metro cúbico equivale a un millón de centímetros cúbicos y el flete se tarifa según el espacio consumido. El peso volumétrico aplica el factor estándar de flete aéreo de 167 kilogramos por metro cúbico.",
    explanationEs: "El CBM, abreviatura de metro cúbico, es la unidad estándar para medir cuánto espacio ocupa un envío, y determina el precio del flete marítimo, el flete aéreo y el almacenamiento por igual. Esta calculadora de CBM toma el largo, ancho y alto del cartón en centímetros, los multiplica, divide por un millón para convertir a metros cúbicos y multiplica por el número de cartones idénticos para dar el volumen total de tu envío.\n\nConocer el CBM es importante porque las navieras y los transitarios a menudo facturan por volumen en lugar de por peso, sobre todo para mercancías ligeras pero voluminosas. Una vez que conoces tus metros cúbicos totales, puedes comparar cotizaciones, decidir entre carga fraccionada de contenedor y contenedor completo, y estimar cuántas cajas caben dentro de un contenedor. La herramienta también devuelve el peso volumétrico, aplicando el factor de flete aéreo ampliamente usado de 167 kilogramos por metro cúbico.\n\nLa fórmula funciona porque un metro cúbico es exactamente un millón de centímetros cúbicos, así que la división simplemente reescala tus medidas a la unidad que cotizan los transportistas. Importadores, exportadores y planificadores de almacén confían en cifras de CBM precisas para reservar la cantidad correcta de espacio, negociar tarifas justas y evitar pagar por aire vacío o descubrir demasiado tarde que su carga no cabe en el contenedor reservado.",
    exampleEs: { inputs: { length: 100, width: 100, height: 100, quantity: 1 }, explanation: "100 × 100 × 100 = 1.000.000 cm³; ÷ 1.000.000 × 1 = 1 CBM." },
    faqsEs: [
      {
        question: "¿Qué unidades debo introducir para un cálculo de CBM?",
        answer: "Introduce el largo, ancho y alto en centímetros y la calculadora convierte el resultado a metros cúbicos dividiendo por un millón. Si tus dimensiones están en metros, multiplícalas por 100 primero, o si están en pulgadas, multiplícalas por 2,54 para obtener centímetros. Mantener cada medida en la misma unidad es esencial, porque mezclar centímetros y metros desviará el volumen en órdenes de magnitud.",
      },
      {
        question: "¿Qué es el peso volumétrico y por qué aparece?",
        answer: "El peso volumétrico expresa cuánto pesaría el tamaño de un envío a una densidad estándar, permitiendo que los transportistas cobren de forma justa la carga voluminosa y ligera. Para el flete aéreo el factor común es 167 kilogramos por metro cúbico, así que esta calculadora multiplica tu CBM por 167. Los transportistas facturan entonces el mayor entre el peso volumétrico y el real, por eso un envío grande pero ligero puede costar más de lo que sugiere su peso.",
      },
      {
        question: "¿Cómo uso el CBM para elegir entre LCL y FCL?",
        answer: "El envío de carga fraccionada de contenedor se tarifa por metro cúbico y conviene para volúmenes pequeños, mientras que un contenedor completo es una tarifa plana por toda la caja. A medida que tu CBM total se acerca a la capacidad utilizable de un contenedor, un contenedor completo suele resultar más barato por unidad. Calcular tu CBM exacto primero te permite comparar el coste por metro cúbico del LCL con la tarifa del contenedor completo.",
      },
      {
        question: "¿Cuántos CBM caben en un contenedor de envío?",
        answer: "Un contenedor estándar de 20 pies alberga aproximadamente 33 metros cúbicos de espacio utilizable, uno de 40 pies unos 67, y uno de 40 pies high-cube unos 76. La capacidad real es menor porque las cajas rara vez se apilan sin huecos, así que los planificadores suelen cargar entre el 80 y el 90 por ciento de la cifra teórica. Conocer el CBM de tu envío te permite estimar cuántos contenedores necesitas antes de reservar.",
      },
      {
        question: "¿Debo incluir los palés en mi medición de CBM?",
        answer: "Sí, cuando la mercancía está paletizada debes medir el palé cargado completo, incluida la altura del propio palé y cualquier saliente, porque ese es el espacio que el envío ocupa realmente. Medir solo los cartones subestima el volumen y puede llevar a reservar poco espacio de contenedor. Para cartones sueltos, mide cada cartón y multiplica por la cantidad, que es exactamente lo que hace esta calculadora con su campo de cantidad.",
      },
    ],
    fields: [
      { id: "length", label: "Length", type: "number", unit: "cm", required: true, span: 1, min: 0 },
      { id: "width", label: "Width", type: "number", unit: "cm", required: true, span: 1, min: 0 },
      { id: "height", label: "Height", type: "number", unit: "cm", required: true, span: 1, min: 0 },
      { id: "quantity", label: "Quantity", type: "number", unit: "cartons", required: true, span: 1, min: 0, defaultValue: 1 },
    ],
    results: [
      { id: "cbm", label: "Total volume", format: "number", decimals: 4, unit: "m³", isPrimary: true },
      { id: "volumetricWeight", label: "Volumetric weight", format: "number", decimals: 2, unit: "kg", isPrimary: false },
    ],
    formula: "CBM = (length × width × height) ÷ 1,000,000 × quantity",
    formulaExplanation: "CBM measures the cubic metres a shipment occupies, so multiplying length, width, and height in centimetres gives cubic centimetres, and dividing by one million converts to cubic metres. Multiplying by quantity totals every identical carton. The formula works because one cubic metre equals a million cubic centimetres, and freight is priced on the space consumed. The volumetric weight applies the standard air-freight factor of 167 kilograms per cubic metre.",
    explanation: "CBM, short for cubic metre, is the standard unit for measuring how much space a shipment occupies, and it drives pricing for sea freight, air freight, and warehousing alike. This CBM calculator takes carton length, width, and height in centimetres, multiplies them, divides by one million to convert to cubic metres, and multiplies by the number of identical cartons to give your total shipment volume.\n\nKnowing CBM matters because ocean carriers and freight forwarders often bill on volume rather than weight, especially for light but bulky goods. Once you know your total cubic metres, you can compare quotes, decide between less-than-container-load and full-container shipping, and estimate how many boxes will fit inside a container. The tool also returns volumetric weight, applying the widely used air-freight factor of 167 kilograms per cubic metre.\n\nThe formula works because a cubic metre is exactly one million cubic centimetres, so the division simply rescales your measurements into the unit carriers quote. Importers, exporters, and warehouse planners rely on accurate CBM figures to book the right amount of space, negotiate fair rates, and avoid paying for empty air or discovering too late that their cargo will not fit the container they reserved.",
    example: { inputs: { length: 100, width: 100, height: 100, quantity: 1 }, explanation: "100 × 100 × 100 = 1,000,000 cm³; ÷ 1,000,000 × 1 = 1 CBM." },
    faqs: [
      {
        question: "What units should I enter for a CBM calculation?",
        answer: "Enter length, width, and height in centimetres and the calculator converts the result to cubic metres by dividing by one million. If your dimensions are in metres, multiply by 100 first, or if they are in inches, multiply by 2.54 to get centimetres. Keeping every measurement in the same unit is essential, because mixing centimetres and metres will throw the volume off by orders of magnitude.",
      },
      {
        question: "What is volumetric weight and why does it appear?",
        answer: "Volumetric weight expresses how much a shipment's size would weigh at a standard density, letting carriers charge bulky, lightweight cargo fairly. For air freight the common factor is 167 kilograms per cubic metre, so this calculator multiplies your CBM by 167. Carriers then bill the greater of volumetric and actual weight, which is why a large but light shipment can cost more than its scale weight suggests.",
      },
      {
        question: "How do I use CBM to choose between LCL and FCL?",
        answer: "Less-than-container-load shipping is priced per cubic metre and suits smaller volumes, while a full-container-load is a flat rate for the whole box. As your total CBM approaches a container's usable capacity, a full container usually becomes cheaper per unit. Calculating your exact CBM first lets you compare the per-cubic-metre LCL cost against a full-container rate and pick the more economical option.",
      },
      {
        question: "How many CBM fit in a shipping container?",
        answer: "A standard 20-foot container holds roughly 33 cubic metres of usable space, a 40-foot around 67, and a 40-foot high-cube about 76. Real capacity is lower because boxes rarely stack without gaps, so planners typically load to about 80 to 90 percent of the theoretical figure. Knowing your shipment's CBM lets you estimate how many containers you need before booking.",
      },
      {
        question: "Should I include pallets in my CBM measurement?",
        answer: "Yes, when goods are palletised you should measure the full loaded pallet, including the pallet's own height and any overhang, because that is the space the shipment actually occupies. Measuring only the cartons understates the volume and can lead to under-booking container space. For loose cartons, measure each carton and multiply by quantity, which is exactly what this calculator does with its quantity field.",
      },
    ],
    relatedCalculators: ["dimensional-weight-calculator", "container-loading-calculator", "pallet-count-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "pallet-count",
    slug: "pallet-count-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Pallet Count Calculator",
    shortDescription: "Work out how many pallets an order needs.",
    seoTitle: "Pallet Count Calculator — Pallets Needed for an Order",
    metaDescription: "Free pallet count calculator. Enter total units, units per layer, and layers per pallet to find how many pallets your shipment needs and the units each pallet.",
    primaryKeyword: "pallet count calculator",
    secondaryKeywords: ["pallets needed calculator", "units per pallet calculator", "shipping pallet calculator"],
    slugEs: "calculadora-de-cantidad-de-palets",
    titleEs: "Calculadora de Cantidad de Palets",
    shortDescriptionEs: "Calcula cuántos palets necesita un pedido.",
    seoTitleEs: "Calculadora de Cantidad de Palets — Palets Necesarios",
    metaDescriptionEs: "Calculadora de cantidad de palets gratuita. Introduce las unidades totales, unidades por capa y capas por palet para hallar cuántos palets necesita tu envío y las unidades que lleva cada uno.",
    primaryKeywordEs: "calculadora de cantidad de palets",
    secondaryKeywordsEs: ["calculadora de palets necesarios", "unidades por palet", "calculadora de palets de envio"],
    formulaExplanationEs: "Cada palet lleva las unidades por capa multiplicadas por las capas por palet, así que ese producto es la capacidad de un palet completo. Dividir las unidades totales por esa capacidad da el número de palets, y redondear hacia arriba con la función techo tiene en cuenta cualquier palet parcial, ya que un sobrante de incluso una sola unidad todavía requiere un palet entero. La fórmula funciona porque los palets no se pueden enviar en fracciones.",
    explanationEs: "Saber exactamente cuántos palets requiere un pedido es esencial para reservar transporte, cotizar flete y planificar el espacio de almacén. Esta calculadora de cantidad de palets multiplica las unidades por capa por el número de capas para hallar cuántas unidades caben en un palet, luego divide el total de unidades por esa cifra y redondea hacia arriba para dar el número de palets que necesitas.\n\nEl redondeo importa: como no puedes enviar una fracción de palet, cualquier resto empuja el total al siguiente palet completo. Un envío de 500 cajas que llena palets de 50 necesita exactamente 10 palets, pero 501 cajas necesitarían 11, con el último palet casi vacío. Verlo con claridad te ayuda a ajustar las cantidades de pedido para llenar palets de forma eficiente y evitar pagar por mover palets casi vacíos.\n\nEl cálculo funciona porque la capacidad de un palet es simplemente su huella multiplicada por su altura apilada en cajas, y la función techo refleja la realidad física de que los palets parciales todavía ocupan una posición completa de palet en un camión. Los gerentes de almacén, expedidores y compradores usan los recuentos de palets para reservar el número correcto de plazas de camión, estimar el tiempo de carga y confirmar que un envío de camión completo o fraccionado cabrá físicamente antes de despacharlo.",
    exampleEs: { inputs: { totalUnits: 500, unitsPerLayer: 10, layersPerPallet: 5 }, explanation: "10 × 5 = 50 unidades por palet; 500 ÷ 50 = 10 palets." },
    faqsEs: [
      {
        question: "¿Cómo hallo las unidades por capa y las capas por palet?",
        answer: "Las unidades por capa son cuántas cajas o cartones caben uno al lado del otro en un solo nivel del palet, determinado por la huella de la caja y el tamaño del palet. Las capas por palet son cuántos de esos niveles puedes apilar con seguridad hasta tu altura máxima de carga. Las especificaciones de tu caja o un diagrama de patrón de paletización suelen listar ambas cifras, y el personal de almacén puede confirmarlas.",
      },
      {
        question: "¿Por qué la calculadora redondea hacia arriba a un palet entero?",
        answer: "Porque los palets se envían como unidades completas, no fracciones. Si tus unidades totales no se dividen de forma exacta en palets completos, el sobrante todavía ocupa una posición entera de palet en el camión. La calculadora aplica una función techo para que un resto de incluso una caja añada otro palet. Esto refleja cómo cobran los transportistas y cómo funciona la carga, dándote un recuento preciso para reservar transporte.",
      },
      {
        question: "¿Qué es un palet parcial y cuesta más?",
        answer: "Un palet parcial lleva menos unidades que uno completo pero aún ocupa un espacio entero de palet en un remolque y a menudo genera el mismo cargo de manipulación. Enviar muchos palets parciales desperdicia dinero y capacidad de camión. Si tu pedido deja un palet casi vacío, considera aumentar la cantidad hasta un palet completo o consolidar con otro envío para mejorar la eficiencia y reducir el coste de flete por unidad.",
      },
      {
        question: "¿Cuántos palets caben en un camión?",
        answer: "Un remolque seco estándar de 53 pies suele llevar 26 palets estándar cargados en el suelo en una sola capa, o hasta 52 si se pueden apilar en dos alturas. Los camiones y contenedores más pequeños llevan menos. Una vez que esta calculadora te dice cuántos palets necesita tu pedido, puedes compararlo con la capacidad de un camión para decidir entre un camión completo y un envío fraccionado.",
      },
      {
        question: "¿El peso del palet afecta al recuento?",
        answer: "Esta calculadora cuenta palets por capacidad de unidades, pero el peso puede prevalecer en la práctica. Si apilar hasta el número completo de capas superara el límite de peso seguro de un palet o los límites de eje de un camión, debes reducir capas, lo que aumenta el recuento de palets. Comprueba siempre tanto el recuento por volumen aquí como el peso por palet, y usa el que produzca más palets para mantenerte dentro de límites seguros y legales.",
      },
    ],
    fields: [
      { id: "totalUnits", label: "Total units", type: "number", unit: "units", required: true, span: 2, min: 0 },
      { id: "unitsPerLayer", label: "Units per layer", type: "number", unit: "units", required: true, span: 1, min: 0 },
      { id: "layersPerPallet", label: "Layers per pallet", type: "number", unit: "layers", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "pallets", label: "Pallets needed", format: "number", decimals: 0, unit: "pallets", isPrimary: true },
      { id: "unitsPerPallet", label: "Units per pallet", format: "number", decimals: 0, unit: "units", isPrimary: false },
    ],
    formula: "pallets = ⌈ total units ÷ (units per layer × layers per pallet) ⌉",
    formulaExplanation: "Each pallet holds units per layer multiplied by layers per pallet, so that product is the capacity of one full pallet. Dividing the total units by that capacity gives the number of pallets, and rounding up with the ceiling function accounts for any partial pallet, since a leftover of even a single unit still requires a whole pallet. The formula works because pallets cannot be shipped as fractions.",
    explanation: "Knowing exactly how many pallets an order requires is essential for booking transport, quoting freight, and planning warehouse space. This pallet count calculator multiplies the units per layer by the number of layers to find how many units fit on one pallet, then divides your total unit count by that figure and rounds up to give the number of pallets you need.\n\nThe rounding matters: because you cannot ship a fraction of a pallet, any remainder pushes the total up to the next whole pallet. A shipment of 500 cases that fills pallets of 50 needs exactly 10 pallets, but 501 cases would need 11, with the last pallet nearly empty. Seeing this clearly helps you adjust order quantities to fill pallets efficiently and avoid paying to move mostly-empty ones.\n\nThe calculation works because a pallet's capacity is simply its footprint times its stacked height in cases, and the ceiling function reflects the physical reality that partial pallets still occupy a full pallet position in a truck. Warehouse managers, shippers, and buyers use pallet counts to reserve the right number of truck spaces, estimate loading time, and confirm a full truckload or LTL shipment will physically fit before the goods are dispatched.",
    example: { inputs: { totalUnits: 500, unitsPerLayer: 10, layersPerPallet: 5 }, explanation: "10 × 5 = 50 units per pallet; 500 ÷ 50 = 10 pallets." },
    faqs: [
      {
        question: "How do I find units per layer and layers per pallet?",
        answer: "Units per layer is how many cases or cartons fit side by side in a single tier on the pallet, determined by the case footprint and the pallet size. Layers per pallet is how many of those tiers you can safely stack to your maximum load height. Your case specifications or a pallet pattern diagram usually list both figures, and warehouse staff can confirm them from a sample stack.",
      },
      {
        question: "Why does the calculator round up to a whole pallet?",
        answer: "Because pallets ship as complete units, not fractions. If your total units do not divide evenly into full pallets, the leftover still occupies an entire pallet position on the truck. The calculator applies a ceiling function so a remainder of even one case adds another pallet. This mirrors how carriers charge and how loading works, giving you an accurate count for booking transport.",
      },
      {
        question: "What is a partial pallet and does it cost more?",
        answer: "A partial pallet holds fewer units than a full one but still takes up a full pallet space in a trailer and often incurs the same handling charge. Shipping many partial pallets wastes money and truck capacity. If your order leaves a nearly empty pallet, consider adjusting the quantity up to a full pallet or consolidating with another shipment to improve efficiency and lower your per-unit freight cost.",
      },
      {
        question: "How many pallets fit on a truck?",
        answer: "A standard 53-foot dry van typically holds 26 standard pallets floor-loaded in a single layer, or up to 52 if they can be double-stacked. Smaller trucks and containers hold fewer. Once this calculator tells you how many pallets your order needs, you can compare that against a truck's capacity to decide between a full truckload and a less-than-truckload shipment.",
      },
      {
        question: "Does pallet weight affect the count?",
        answer: "This calculator counts pallets by unit capacity, but weight can override that in practice. If stacking to the full layer count would exceed a pallet's safe weight limit or a truck's axle limits, you must reduce layers, which increases the pallet count. Always check both the volume-based count here and the weight per pallet, then use whichever produces more pallets to stay within safe and legal limits.",
      },
    ],
    relatedCalculators: ["cbm-calculator", "container-loading-calculator", "freight-density-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "freight-density",
    slug: "freight-density-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Freight Density Calculator",
    shortDescription: "Calculate freight density in pounds per cubic foot.",
    seoTitle: "Freight Density Calculator — Pounds per Cubic Foot",
    metaDescription: "Free freight density calculator. Enter weight and dimensions in inches to find density in pounds per cubic foot, the figure used to assign LTL freight class.",
    primaryKeyword: "freight density calculator",
    secondaryKeywords: ["freight class calculator", "pounds per cubic foot calculator", "ltl density calculator"],
    slugEs: "calculadora-de-densidad-de-flete",
    titleEs: "Calculadora de Densidad de Flete",
    shortDescriptionEs: "Calcula la densidad de flete en libras por pie cúbico.",
    seoTitleEs: "Calculadora de Densidad de Flete — Libras por Pie Cúbico",
    metaDescriptionEs: "Calculadora de densidad de flete gratuita. Introduce el peso y las dimensiones en pulgadas para hallar la densidad en libras por pie cúbico, la cifra usada para asignar la clase de flete LTL.",
    primaryKeywordEs: "calculadora de densidad de flete",
    secondaryKeywordsEs: ["calculadora de clase de flete", "libras por pie cubico", "calculadora de densidad ltl"],
    formulaExplanationEs: "La densidad de flete es el peso dividido por el volumen en pies cúbicos. Multiplicar las tres dimensiones en pulgadas da pulgadas cúbicas, y dividir por 1.728 convierte a pies cúbicos porque un pie cúbico contiene doce pulgadas al cubo. Dividir el peso por ese volumen produce libras por pie cúbico. La fórmula funciona porque la densidad describe cuánta masa llena un espacio dado, y los transportistas de carga fraccionada la usan para asignar la clase de flete que fija tu tarifa.",
    explanationEs: "La densidad de flete mide cuánto pesa tu envío en relación con el espacio que ocupa, y es el número más importante en el mundo de la carga fraccionada porque determina en gran medida tu clase de flete y, por tanto, tu tarifa. Esta calculadora de densidad de flete multiplica el largo, ancho y alto de tu envío en pulgadas, lo convierte a pies cúbicos y divide el peso por el volumen para dar la densidad en libras por pie cúbico.\n\nLa densidad importa porque los transportistas LTL clasifican el flete desde la clase 50 para mercancías densas y fáciles de manipular hasta la clase 500 para artículos ligeros y voluminosos. Una densidad alta significa más peso en menos espacio, lo que suele dar una clase más baja y económica, mientras que una densidad baja indica una carga voluminosa que cuesta más mover. Acertar con la cifra te ayuda a cotizar con precisión y evitar cargos costosos por reclasificación tras la recogida.\n\nEl cálculo funciona porque dividir el peso por el volumen da la densidad sobre la que se construyen las tablas de clasificación, y dividir las pulgadas cúbicas por 1.728 simplemente convierte a los pies cúbicos que usan esas tablas. Expedidores, agentes de flete y equipos de almacén calculan la densidad antes de reservar para predecir la clase de flete, comparar cotizaciones de forma justa y embalar la mercancía para alcanzar una clase más favorable cuando sea posible.",
    exampleEs: { inputs: { weight: 30, length: 12, width: 12, height: 12 }, explanation: "12 × 12 × 12 ÷ 1.728 = 1 ft³; 30 ÷ 1 = 30 lb/ft³." },
    faqsEs: [
      {
        question: "¿Por qué se mide la densidad de flete en libras por pie cúbico?",
        answer: "Las libras por pie cúbico son la unidad estándar que usan las tablas de clasificación LTL para mapear un envío a una clase de flete. Captura el compromiso que importa a los transportistas: mercancía más pesada en menos espacio es eficiente de transportar, mientras que el flete ligero y voluminoso desperdicia capacidad del remolque. Expresar la densidad así permite aplicar una escala consistente a cada mercancía, de modo que tu cifra calculada se traduce directamente en una clase esperada.",
      },
      {
        question: "¿Cómo afecta la densidad a la clase de flete y al coste?",
        answer: "La clase de flete va de 50 a 500, y la densidad es el principal factor para muchas mercancías. Una densidad más alta suele significar un número de clase más bajo y una tarifa menor, porque el flete denso usa el espacio del remolque de forma eficiente. Una densidad más baja empuja el número de clase y el coste hacia arriba. Calcular la densidad antes de enviar te permite anticipar la clase, presupuestar con precisión y detectar oportunidades de reembalaje.",
      },
      {
        question: "¿Debo medir el embalaje o el producto desnudo?",
        answer: "Mide siempre el envío exactamente como viajará, incluidos palés, embalaje y cualquier saliente. Los transportistas tarifan el espacio que el flete ocupa realmente, así que el embalaje cuenta. Mide hasta los puntos extremos de largo, ancho y alto, y pesa la carga embalada completa. Usar las dimensiones del producto desnudo subestimaría el volumen, inflaría la densidad y arriesgaría una reclasificación y un cargo ajustado cuando el transportista vuelva a medir.",
      },
      {
        question: "¿Y si mi envío tiene varias piezas?",
        answer: "Para un envío formado por varias piezas, suma los volúmenes individuales para obtener los pies cúbicos totales y suma los pesos individuales para obtener el peso total, luego divide el peso total por el volumen total. Esto da la densidad global que los transportistas usan para un envío de varias piezas. Calcular cada pieza por separado y promediar las densidades daría la respuesta equivocada, así que trabaja siempre desde los totales combinados.",
      },
      {
        question: "¿Cómo convierto las dimensiones a pies cúbicos?",
        answer: "Multiplica el largo, ancho y alto en pulgadas para obtener pulgadas cúbicas, luego divide por 1.728, ya que un pie cúbico equivale a doce pulgadas al cubo. Esta calculadora hace la conversión por ti y también muestra el resultado en pies cúbicos. Si tus medidas ya están en pies, simplemente multiplícalas directamente. Mantener las unidades consistentes es crítico, porque un error de unidades distorsionará la densidad y la clase de flete resultante.",
      },
    ],
    fields: [
      { id: "weight", label: "Weight", type: "number", unit: "lb", required: true, span: 2, min: 0 },
      { id: "length", label: "Length", type: "number", unit: "in", required: true, span: 1, min: 0 },
      { id: "width", label: "Width", type: "number", unit: "in", required: true, span: 1, min: 0 },
      { id: "height", label: "Height", type: "number", unit: "in", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "density", label: "Freight density", format: "number", decimals: 2, unit: "lb/ft³", isPrimary: true },
      { id: "cubicFeet", label: "Cubic feet", format: "number", decimals: 2, unit: "ft³", isPrimary: false },
    ],
    formula: "density = weight ÷ (length × width × height ÷ 1,728)",
    formulaExplanation: "Freight density is weight divided by volume in cubic feet. Multiplying the three dimensions in inches gives cubic inches, and dividing by 1,728 converts to cubic feet because a cubic foot contains twelve inches cubed. Dividing weight by that volume yields pounds per cubic foot. The formula works because density describes how much mass fills a given space, and less-than-truckload carriers use it to assign the freight class that sets your rate.",
    explanation: "Freight density measures how much your shipment weighs relative to the space it occupies, and it is the single most important number in the less-than-truckload world because it largely determines your freight class and therefore your rate. This freight density calculator multiplies your shipment's length, width, and height in inches, converts that to cubic feet, and divides the weight by the volume to give density in pounds per cubic foot.\n\nDensity matters because LTL carriers classify freight from class 50 for dense, easy-to-handle goods up to class 500 for light, bulky items. A high density means more weight in less space, which typically earns a lower, cheaper class, while a low density signals a bulky load that costs more to move. Getting the figure right helps you quote accurately and avoid costly reclassification charges after pickup.\n\nThe calculation works because dividing weight by volume gives the density that classification tables are built around, and dividing cubic inches by 1,728 simply converts to the cubic feet those tables use. Shippers, freight brokers, and warehouse teams calculate density before booking so they can predict the freight class, compare carrier quotes fairly, and package goods to hit a more favourable class where possible.",
    example: { inputs: { weight: 30, length: 12, width: 12, height: 12 }, explanation: "12 × 12 × 12 ÷ 1,728 = 1 ft³; 30 ÷ 1 = 30 lb/ft³." },
    faqs: [
      {
        question: "Why is freight density measured in pounds per cubic foot?",
        answer: "Pounds per cubic foot is the standard unit LTL classification tables use to map a shipment to a freight class. It captures the trade-off carriers care about: heavier goods in less space are efficient to haul, while light, bulky freight wastes trailer capacity. Expressing density this way lets carriers apply one consistent scale across every commodity, so your calculated figure translates directly into an expected class.",
      },
      {
        question: "How does density affect freight class and cost?",
        answer: "Freight class runs from 50 to 500, and density is the primary driver for many commodities. Higher density generally means a lower class number and a lower rate, because dense freight uses trailer space efficiently. Lower density pushes the class number up and the cost with it. Calculating density before you ship lets you anticipate the class, budget accurately, and spot chances to repackage into a cheaper bracket.",
      },
      {
        question: "Should I measure the packaging or the bare product?",
        answer: "Always measure the shipment exactly as it will travel, including pallets, crating, and any overhang. Carriers rate the space the freight actually occupies, so packaging counts. Measure to the extreme points of length, width, and height, and weigh the complete packaged load. Using bare product dimensions would understate the volume, inflate the density, and risk a reclassification and adjusted charge once the carrier re-measures the shipment.",
      },
      {
        question: "What if my shipment has multiple pieces?",
        answer: "For a shipment made of several pieces, add up the individual volumes to get total cubic feet and add the individual weights to get total weight, then divide total weight by total volume. This gives the overall density carriers use for a multi-piece shipment. Calculating each piece separately and averaging the densities would give the wrong answer, so always work from the combined totals for an accurate class.",
      },
      {
        question: "How do I convert dimensions to cubic feet?",
        answer: "Multiply length, width, and height in inches to get cubic inches, then divide by 1,728, since one cubic foot equals twelve inches cubed. This calculator does the conversion for you and also displays the cubic feet result. If your measurements are already in feet, simply multiply them together directly. Keeping units consistent is critical, because a units error will distort the density and the resulting freight class.",
      },
    ],
    relatedCalculators: ["dimensional-weight-calculator", "cbm-calculator", "pallet-count-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "landed-cost",
    slug: "landed-cost-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Landed Cost Calculator",
    shortDescription: "Total the true cost of imported goods.",
    seoTitle: "Landed Cost Calculator — Product, Freight, Duty & Insurance",
    metaDescription: "Free landed cost calculator. Add product cost, freight, duty percentage, and insurance to find the true total landed cost of imported goods before you price.",
    primaryKeyword: "landed cost calculator",
    secondaryKeywords: ["total landed cost calculator", "import cost calculator", "duty and freight calculator"],
    slugEs: "calculadora-de-costo-total-de-importacion",
    titleEs: "Calculadora de Costo Total de Importación",
    shortDescriptionEs: "Suma el costo real de la mercancía importada.",
    seoTitleEs: "Calculadora de Costo Total de Importación — Producto, Flete, Aranceles y Seguro",
    metaDescriptionEs: "Calculadora de costo total de importación gratuita. Suma el costo del producto, el flete, el porcentaje de arancel y el seguro para hallar el costo total real de la mercancía importada antes de fijar su precio.",
    primaryKeywordEs: "calculadora de costo total de importacion",
    secondaryKeywordsEs: ["calculadora de costo en destino", "calculadora de costo de importacion", "calculadora de aranceles y flete"],
    formulaExplanationEs: "El costo total de importación suma cada gasto de llevar la mercancía hasta tu puerta: el producto en sí, el flete para moverlo, el arancel adeudado sobre su valor y el seguro contra pérdidas. El arancel es el costo del producto multiplicado por el porcentaje de la tasa arancelaria. La fórmula funciona porque cada componente es una salida de efectivo real y separada, y sumarlos revela el verdadero costo unitario que debes cubrir antes de cualquier margen, en lugar del precio de etiqueta engañosamente bajo de la mercancía sola.",
    explanationEs: "El costo total de importación es el precio real y completo de llevar la mercancía importada desde un proveedor hasta tu almacén, y casi siempre es más alto que el precio del producto solo. Esta calculadora de costo total de importación suma el costo del producto, el flete, el arancel aplicable y el seguro para revelar el costo real por envío, para que puedas fijar el precio de tu mercancía con un beneficio genuino en lugar de un margen que se evapora silenciosamente cuando llegan las tasas de importación.\n\nPor qué importa: muchos importadores fijan precios de venta frente a la cotización de fábrica y se sorprenden cuando el flete, el arancel aduanero y el seguro erosionan su beneficio esperado. Al calcular el costo total de importación por adelantado, ves el panorama completo antes de comprometerte con un pedido, puedes comparar proveedores por costo total en lugar de precio de titular, y puedes decidir si un envío merece la pena importar.\n\nEl cálculo funciona porque cada elemento es un costo distinto e inevitable de la importación, y el arancel en particular se cobra como un porcentaje del valor de la mercancía, que la calculadora aplica por ti. Los gerentes de abastecimiento, vendedores de comercio electrónico y pequeños importadores confían en el costo total de importación para negociar con proveedores, elegir métodos de envío y fijar precios que sobrevivan al contacto con los costos reales del comercio internacional.",
    exampleEs: { inputs: { productCost: 1000, freight: 200, dutyPercent: 5, insurance: 50 }, explanation: "Arancel = 1.000 × 5% = 50; total = 1.000 + 200 + 50 + 50 = 1.300 $." },
    faqsEs: [
      {
        question: "¿Qué costos componen el costo total de importación?",
        answer: "El costo total de importación combina el precio de compra del producto, el flete para transportarlo, el arancel aduanero adeudado sobre su valor y el seguro que cubre la mercancía en tránsito. Esta calculadora suma los cuatro en un total. Según tus términos comerciales también puedes enfrentar tasas de corretaje, cargos portuarios e impuestos; si aplican, inclúyelos en los campos de flete o seguro para que el total refleje cada costo real.",
      },
      {
        question: "¿Cómo se calcula el importe del arancel?",
        answer: "El arancel se cobra como un porcentaje del valor declarado de la mercancía, así que la calculadora multiplica el costo de tu producto por la tasa arancelaria que introduces. Por ejemplo, un arancel del 5 por ciento sobre 1.000 dólares de mercancía son 50 dólares. La tasa correcta depende de la clasificación arancelaria del producto y su país de origen, que puedes consultar en el arancel de tu país o confirmar con un agente de aduanas.",
      },
      {
        question: "¿Por qué debo calcular el costo total de importación antes de fijar precios?",
        answer: "El precio de fábrica es solo una parte de lo que pagas. El flete, el arancel y el seguro pueden añadir un porcentaje significativo encima, y fijar el precio solo frente al costo del producto puede convertir un beneficio aparente en una pérdida. Calcular el costo total de importación primero te da el verdadero costo por unidad, para que puedas fijar un precio de venta que cubra cada gasto y aún entregue el margen que tu negocio realmente necesita.",
      },
      {
        question: "¿El costo total de importación incluye el envío al cliente?",
        answer: "Normalmente no. El costo total de importación cubre llevar la mercancía desde el proveedor hasta tu almacén o puerto de entrada, incluyendo el flete de entrada, el arancel y el seguro. El costo de enviar un pedido después a tu cliente final es un gasto de salida separado que contabilizas en la etapa de venta. Mantener separados el costo de importación de entrada y el cumplimiento de salida da una visión más clara de ambos.",
      },
      {
        question: "¿Cómo puedo reducir mi costo total de importación?",
        answer: "Puedes reducir el costo total de importación negociando mejores tarifas de producto o flete, consolidando envíos para repartir el flete fijo entre más unidades, eligiendo modos de envío más lentos pero baratos, o abasteciéndote de países con tasas arancelarias más bajas o acuerdos comerciales. Clasificar correctamente la mercancía para reclamar el arancel legal más bajo también ayuda. Modela cada opción en esta calculadora para ver cuál ahorra más antes de comprometerte.",
      },
    ],
    fields: [
      { id: "productCost", label: "Product cost", type: "number", unit: "$", required: true, span: 1, min: 0 },
      { id: "freight", label: "Freight cost", type: "number", unit: "$", required: false, span: 1, min: 0 },
      { id: "dutyPercent", label: "Duty rate", type: "number", unit: "%", required: false, span: 1, min: 0, step: 0.1 },
      { id: "insurance", label: "Insurance", type: "number", unit: "$", required: false, span: 1, min: 0 },
    ],
    results: [
      { id: "landedCost", label: "Total landed cost", format: "currency", decimals: 2, isPrimary: true },
      { id: "duty", label: "Duty amount", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "landed cost = product + freight + (product × duty%) + insurance",
    formulaExplanation: "Landed cost sums every expense of getting goods to your door: the product itself, the freight to move it, the duty owed on its value, and insurance against loss. Duty is the product cost multiplied by the duty rate percentage. The formula works because each component is a real, separate cash outflow, and adding them reveals the true unit cost you must cover before any margin, rather than the misleadingly low sticker price of the goods alone.",
    explanation: "Landed cost is the true, all-in price of getting imported goods from a supplier to your warehouse, and it is almost always higher than the product price alone. This landed cost calculator adds the product cost, freight, applicable duty, and insurance to reveal the real cost per shipment, so you can price your goods for genuine profit rather than a margin that quietly evaporates once import fees arrive.\n\nWhy this matters: many importers set retail prices against the factory quote and are shocked when freight, customs duty, and insurance erode their expected profit. By calculating landed cost up front, you see the complete picture before committing to an order, can compare suppliers on total cost rather than headline price, and can decide whether a shipment is worth importing at all.\n\nThe calculation works because each element is a distinct, unavoidable cost of import, and duty in particular is charged as a percentage of the goods' value, which the calculator applies for you. Sourcing managers, ecommerce sellers, and small importers rely on landed cost to negotiate with suppliers, choose shipping methods, and set prices that survive contact with the real costs of international trade instead of collapsing under hidden fees.",
    example: { inputs: { productCost: 1000, freight: 200, dutyPercent: 5, insurance: 50 }, explanation: "Duty = 1,000 × 5% = 50; total = 1,000 + 200 + 50 + 50 = $1,300." },
    faqs: [
      {
        question: "What costs make up landed cost?",
        answer: "Landed cost combines the product's purchase price, the freight to transport it, the customs duty owed on its value, and insurance covering the goods in transit. This calculator adds all four into one total. Depending on your trade terms you may also face brokerage fees, port charges, and taxes; if those apply, fold them into the freight or insurance fields so the total reflects every real cost.",
      },
      {
        question: "How is the duty amount calculated?",
        answer: "Duty is charged as a percentage of the goods' declared value, so the calculator multiplies your product cost by the duty rate you enter. For example, a 5 percent duty on 1,000 dollars of goods is 50 dollars. The correct rate depends on the product's tariff classification and country of origin, which you can look up in your country's tariff schedule or confirm with a customs broker.",
      },
      {
        question: "Why should I calculate landed cost before pricing?",
        answer: "The factory price is only part of what you pay. Freight, duty, and insurance can add a significant percentage on top, and pricing against the product cost alone can turn an apparent profit into a loss. Calculating landed cost first gives you the true cost per unit, so you can set a retail price that covers every expense and still delivers the margin your business actually needs.",
      },
      {
        question: "Does landed cost include shipping to the customer?",
        answer: "Typically no. Landed cost covers getting goods from the supplier to your warehouse or port of entry, including inbound freight, duty, and insurance. The cost of shipping an order onward to your end customer is a separate outbound expense you account for at the sales stage. Keeping inbound landed cost and outbound fulfilment separate gives a clearer view of both your product margins and your delivery costs.",
      },
      {
        question: "How can I lower my landed cost?",
        answer: "You can reduce landed cost by negotiating better product or freight rates, consolidating shipments to spread fixed freight over more units, choosing slower but cheaper shipping modes, or sourcing from countries with lower duty rates or trade agreements. Correctly classifying goods to claim the lowest lawful tariff also helps. Model each option in this calculator to see which change delivers the biggest saving before you commit.",
      },
    ],
    relatedCalculators: ["cbm-calculator", "container-loading-calculator", "dimensional-weight-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "container-loading",
    slug: "container-loading-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Container Loading Calculator",
    shortDescription: "Find how many containers your cargo needs.",
    seoTitle: "Container Loading Calculator — Containers Needed & Utilization",
    metaDescription: "Free container loading calculator. Enter your cargo volume in CBM and pick a container type to find how many containers you need and how full each one will be.",
    primaryKeyword: "container loading calculator",
    secondaryKeywords: ["container capacity calculator", "how many containers calculator", "cbm to container calculator"],
    slugEs: "calculadora-de-carga-de-contenedores",
    titleEs: "Calculadora de Carga de Contenedores",
    shortDescriptionEs: "Halla cuántos contenedores necesita tu carga.",
    seoTitleEs: "Calculadora de Carga de Contenedores — Contenedores Necesarios y Utilización",
    metaDescriptionEs: "Calculadora de carga de contenedores gratuita. Introduce el volumen de tu carga en CBM y elige un tipo de contenedor para hallar cuántos contenedores necesitas y cuán lleno estará cada uno.",
    primaryKeywordEs: "calculadora de carga de contenedores",
    secondaryKeywordsEs: ["calculadora de capacidad de contenedor", "cuantos contenedores necesito", "calculadora de cbm a contenedor"],
    formulaExplanationEs: "Cada tipo de contenedor tiene una capacidad utilizable en metros cúbicos: unos 33 para uno de 20 pies, 67 para uno de 40 pies y 76 para uno de 40 pies high-cube. Dividir el volumen de tu carga por esa capacidad y redondear hacia arriba da el número de contenedores, ya que una fracción de contenedor todavía necesita uno entero. La utilización es el volumen de la carga dividido por la capacidad total reservada, mostrando con qué eficiencia llenas el espacio que pagas.",
    explanationEs: "Reservar el número correcto de contenedores de envío es un equilibrio entre no pagar por espacio vacío y no dejar carga atrás. Esta calculadora de carga de contenedores toma el volumen total de tu carga en metros cúbicos, lo compara con la capacidad utilizable del tipo de contenedor que selecciones, y devuelve cuántos contenedores necesitas junto con cuán llenos estarán en promedio.\n\nEsto importa porque los contenedores se reservan como unidades completas a una tarifa plana, así que incluso un pequeño exceso obliga a un segundo contenedor que puede quedar casi vacío. Ver el porcentaje de utilización te ayuda a decidir si recortar tu pedido, consolidar envíos o subir a un tipo de contenedor más grande como un high-cube para meter todo en menos cajas y reducir tu costo por unidad enviada.\n\nEl cálculo funciona porque cada contenedor tiene un volumen utilizable bien establecido, y dividir el CBM de la carga por esa capacidad y luego redondear hacia arriba refleja la realidad física de que los contenedores parciales todavía cuentan como uno. Ten en cuenta que estas cifras suponen que el volumen es el factor limitante; la carga densa puede alcanzar antes el límite de peso de un contenedor. Importadores, exportadores y transitarios usan las estimaciones de carga de contenedores para reservar capacidad con precisión, comparar opciones de envío y confirmar que un envío cabrá antes de comprometerse con una tarifa.",
    exampleEs: { inputs: { cargoCbm: 100, containerType: "40ft" }, explanation: "100 ÷ 67 = 1,49, redondeado a 2 contenedores; 100 ÷ 134 ≈ 74,6% de utilización." },
    faqsEs: [
      {
        question: "¿Cuánta carga cabe en cada tipo de contenedor?",
        answer: "Esta calculadora usa capacidades utilizables de unos 33 metros cúbicos para un contenedor estándar de 20 pies, 67 para uno estándar de 40 pies y 76 para uno de 40 pies high-cube. Estas son cifras prácticas de carga en lugar del volumen interno máximo, ya que las cajas nunca se apilan a la perfección. Elegir el tipo correcto para el volumen de tu carga ayuda a minimizar el número de contenedores y el espacio vacío que acabas pagando.",
      },
      {
        question: "¿Por qué redondear a un contenedor entero?",
        answer: "Los contenedores se reservan y tarifan como unidades completas, así que cualquier carga que exceda la capacidad de un contenedor requiere un segundo, aunque solo lo llene a medias. La calculadora redondea hacia arriba para reflejar esto, dando el número real que debes reservar. La cifra de utilización muestra entonces cuán llenos están esos contenedores, que es tu señal para considerar consolidar o cambiar de tamaño y evitar enviar una caja casi vacía.",
      },
      {
        question: "¿Qué me dice el porcentaje de utilización?",
        answer: "La utilización es el volumen de tu carga dividido por la capacidad total de los contenedores que reservas, mostrado como porcentaje. Una cifra alta significa que usas el espacio de forma eficiente, mientras que una cifra baja advierte que pagas por mucho espacio vacío. Si la utilización es baja, podrías reducir tu pedido, añadir más mercancía o elegir un tipo de contenedor que empaquete tu carga en menos cajas más llenas.",
      },
      {
        question: "¿Esto tiene en cuenta cómo se empaquetan realmente los artículos?",
        answer: "La calculadora estima según el volumen total, que supone que la carga llena el contenedor de forma eficiente. En realidad, las formas de las cajas, las reglas de apilamiento y los artículos irregulares dejan huecos, así que la capacidad real suele ser del 80 al 90 por ciento de la cifra teórica. Trata el resultado como una estimación de planificación e incluye un margen, sobre todo para mercancías de forma extraña que no se apilan bien.",
      },
      {
        question: "¿Y si mi carga es pesada en lugar de voluminosa?",
        answer: "Esta herramienta supone que el volumen limita tu carga, pero la carga densa puede alcanzar la carga útil máxima de un contenedor antes de llenar el espacio. Cada contenedor tiene un límite de peso, a menudo alrededor de 28 toneladas para uno de 20 pies y algo más para uno de 40 pies. Si tu mercancía es pesada, comprueba también el peso total frente a ese límite, y usa la restricción que requiera más contenedores para mantenerte legal y seguro.",
      },
    ],
    fields: [
      { id: "cargoCbm", label: "Cargo volume", type: "number", unit: "m³", required: true, span: 1, min: 0 },
      {
        id: "containerType",
        label: "Container type",
        type: "select",
        required: true,
        span: 1,
        defaultValue: "40ft",
        options: [
          { value: "20ft", label: "20ft standard (33 m³)" },
          { value: "40ft", label: "40ft standard (67 m³)" },
          { value: "40hc", label: "40ft high-cube (76 m³)" },
        ],
      },
    ],
    results: [
      { id: "containersNeeded", label: "Containers needed", format: "number", decimals: 0, unit: "containers", isPrimary: true },
      { id: "containerCapacity", label: "Capacity each", format: "number", decimals: 0, unit: "m³", isPrimary: false },
      { id: "utilizationPercent", label: "Utilization", format: "percentage", decimals: 1, isPrimary: false },
    ],
    formula: "containers = ⌈ cargo CBM ÷ container capacity ⌉",
    formulaExplanation: "Each container type has a usable capacity in cubic metres: about 33 for a 20-foot, 67 for a 40-foot, and 76 for a 40-foot high-cube. Dividing your cargo volume by that capacity and rounding up gives the number of containers, since a fraction of a container still needs a whole one. Utilization is the cargo volume divided by the total capacity booked, showing how efficiently you fill the space you pay for.",
    explanation: "Booking the right number of shipping containers is a balance between not paying for empty space and not leaving cargo behind. This container loading calculator takes your total cargo volume in cubic metres, compares it against the usable capacity of the container type you select, and returns how many containers you need along with how full they will be on average.\n\nThis matters because containers are booked as whole units at a flat rate, so even a small overflow forces a second container that may sit mostly empty. Seeing the utilization percentage helps you decide whether to trim your order, consolidate shipments, or step up to a larger container type such as a high-cube to fit everything into fewer boxes and lower your cost per unit shipped.\n\nThe calculation works because each container has a well-established usable volume, and dividing cargo CBM by that capacity then rounding up reflects the physical reality that partial containers still count as one. Note that these figures assume volume is the limiting factor; dense cargo may hit a container's weight limit first. Importers, exporters, and freight forwarders use container loading estimates to book capacity accurately, compare shipping options, and confirm a shipment will fit before committing to a rate.",
    example: { inputs: { cargoCbm: 100, containerType: "40ft" }, explanation: "100 ÷ 67 = 1.49, rounded up to 2 containers; 100 ÷ 134 ≈ 74.6% utilization." },
    faqs: [
      {
        question: "How much cargo fits in each container type?",
        answer: "This calculator uses usable capacities of about 33 cubic metres for a 20-foot standard container, 67 for a 40-foot standard, and 76 for a 40-foot high-cube. These are practical loading figures rather than the maximum internal volume, since boxes never stack perfectly. Choosing the right type for your cargo volume helps you minimise the number of containers and the empty space you end up paying to ship.",
      },
      {
        question: "Why round up to a whole container?",
        answer: "Containers are booked and priced as complete units, so any cargo that exceeds one container's capacity requires a second, even if it only half-fills it. The calculator rounds up to reflect this, giving the true number you must reserve. The utilization figure then shows how full those containers are, which is your cue to consider consolidating or resizing to avoid shipping a nearly empty box.",
      },
      {
        question: "What does the utilization percentage tell me?",
        answer: "Utilization is your cargo volume divided by the total capacity of the containers you book, shown as a percentage. A high figure means you are using the space efficiently, while a low figure warns that you are paying for a lot of empty room. If utilization is low, you might reduce your order, add more goods, or pick a container type that packs your cargo into fewer, fuller boxes.",
      },
      {
        question: "Does this account for how items actually pack?",
        answer: "The calculator estimates based on total volume, which assumes cargo fills the container efficiently. In reality, box shapes, stacking rules, and irregular items leave gaps, so real capacity is often 80 to 90 percent of the theoretical figure. Treat the result as a planning estimate and build in a margin, especially for oddly shaped goods that will not stack neatly into the available cubic space.",
      },
      {
        question: "What if my cargo is heavy rather than bulky?",
        answer: "This tool assumes volume limits your load, but dense cargo can hit a container's maximum payload before it fills the space. Each container has a weight limit, often around 28 tonnes for a 20-foot and slightly more for a 40-foot. If your goods are heavy, check the total weight against that limit too, and use whichever constraint requires more containers to stay legal and safe.",
      },
    ],
    relatedCalculators: ["cbm-calculator", "pallet-count-calculator", "landed-cost-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard freight/logistics formula",
  },
];
