import type { CalculatorDefinition } from "../types";

export const logisticsR7Calculators: CalculatorDefinition[] = [
  {
    id: "cost-per-mile",
    slug: "cost-per-mile-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Cost Per Mile Calculator",
    shortDescription: "Find your trucking cost per mile.",
    seoTitle: "Cost Per Mile Calculator — Trucking Cost Per Mile",
    metaDescription: "Free cost per mile calculator. Enter total operating cost and miles driven to find your trucking cost per mile, the key number for pricing freight and setting rates.",
    primaryKeyword: "cost per mile calculator",
    secondaryKeywords: ["trucking cost per mile calculator", "cpm calculator", "freight cost per mile calculator"],
    fields: [
      { id: "totalCost", label: "Total cost", type: "number", unit: "$", required: true, span: 1, min: 0 },
      { id: "miles", label: "Miles driven", type: "number", unit: "mi", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "costPerMile", label: "Cost per mile", format: "currency", decimals: 2, isPrimary: true },
    ],
    formula: "cost per mile = total cost ÷ miles",
    formulaExplanation: "Cost per mile divides every dollar you spend to run a trip or a fleet by the miles those dollars cover, converting a lump sum into a rate you can compare against the revenue each mile earns. The formula works because trucking costs, whether fixed like insurance or variable like fuel, are ultimately paid off over distance, so spreading total cost across total miles reveals the true unit economics of moving freight one mile down the road.",
    explanation: "Cost per mile is the single most important number in trucking economics, because it tells you exactly what it costs to move a truck one mile before you can decide what to charge. This cost per mile calculator divides your total operating cost by the miles driven, turning a pile of expenses into a clean per-mile rate you can compare directly against the rate carriers and brokers offer per mile.\n\nKnowing your cost per mile matters because freight is quoted per mile, and without this figure you are pricing blind. Owner-operators, fleet managers, and dispatchers use it to decide whether a load pays, to spot unprofitable lanes, and to negotiate from a position of knowledge rather than guesswork. Total cost should include fuel, maintenance, tyres, insurance, permits, driver pay, and truck payments over the same period as the miles.\n\nThe calculation works because both fixed costs, which you pay whether you roll or not, and variable costs, which rise with distance, are recovered over the miles you drive. Spreading the total across the miles gives the break-even rate every mile must beat to earn a profit. Track this number monthly, watch how it moves as fuel and maintenance shift, and use it as the floor beneath every rate you agree to so that no load quietly loses money for the business.",
    example: { inputs: { totalCost: 1500, miles: 600 }, explanation: "1,500 ÷ 600 = $2.50 per mile." },
    faqs: [
      {
        question: "What costs should I include in the total?",
        answer: "Include every expense of operating the truck over the same period as the miles: fuel, maintenance, tyres, insurance, licensing and permits, driver wages, truck and trailer payments, and a share of overhead like dispatch and accounting. Leaving out fixed costs such as insurance or the truck payment understates your true cost per mile and can trick you into accepting loads that actually lose money once every bill is counted.",
      },
      {
        question: "What is a good cost per mile for trucking?",
        answer: "There is no single figure, because it depends on equipment, lane, fuel prices, and how you count fixed costs, but many owner-operators land somewhere between 1.50 and 2.00 dollars per mile all in. What matters most is that your revenue per mile comfortably exceeds your cost per mile. Calculate your own number honestly and compare it to the rates on offer rather than chasing an industry average.",
      },
      {
        question: "Should I calculate cost per mile per truck or per fleet?",
        answer: "Both views help. A fleet-wide number gives a quick health check across the whole operation, while a per-truck figure exposes which units or drivers run efficiently and which drag down the average. Start with the fleet total for pricing, then break it down by truck to find maintenance-heavy vehicles, fuel-thirsty routes, or empty miles you can cut to lower the overall cost per mile.",
      },
      {
        question: "How do deadhead miles affect cost per mile?",
        answer: "Deadhead or empty miles cost fuel and wear but earn no revenue, so they raise your effective cost per loaded mile. If you divide total cost by loaded miles only, deadhead is buried in the rate you must charge. Track empty miles separately and work to reduce them through backhauls and better load planning, because every empty mile you eliminate lowers the cost each paying mile has to cover.",
      },
      {
        question: "How often should I recalculate cost per mile?",
        answer: "Recalculate at least monthly, and immediately whenever a major cost shifts, such as a fuel price spike, an insurance renewal, or a big repair. Costs drift constantly, and a rate that was profitable last quarter can slip into loss without you noticing. Reviewing your cost per mile regularly keeps your pricing floor accurate and ensures every load you book still clears the true cost of running the truck.",
      },
    ],
    relatedCalculators: ["fuel-surcharge-calculator", "delivery-time-estimator-calculator", "landed-cost-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "fuel-surcharge",
    slug: "fuel-surcharge-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Fuel Surcharge Calculator",
    shortDescription: "Add a fuel surcharge to a base freight rate.",
    seoTitle: "Fuel Surcharge Calculator — Freight Fuel Surcharge",
    metaDescription: "Free fuel surcharge calculator. Enter a base rate and surcharge percentage to find the fuel surcharge amount and the total rate carriers bill for a shipment.",
    primaryKeyword: "fuel surcharge calculator",
    secondaryKeywords: ["freight fuel surcharge calculator", "fsc calculator", "trucking fuel surcharge calculator"],
    fields: [
      { id: "baseRate", label: "Base rate", type: "number", unit: "$", required: true, span: 1, min: 0 },
      { id: "surchargePercent", label: "Surcharge rate", type: "number", unit: "%", required: true, span: 1, min: 0, step: 0.1 },
    ],
    results: [
      { id: "surcharge", label: "Fuel surcharge", format: "currency", decimals: 2, isPrimary: true },
      { id: "totalRate", label: "Total rate", format: "currency", decimals: 2, isPrimary: false },
    ],
    formula: "surcharge = base rate × surcharge% ÷ 100; total = base + surcharge",
    formulaExplanation: "A fuel surcharge is a percentage of the base freight rate that carriers add to recover volatile diesel costs, so multiplying the base rate by the surcharge percentage and dividing by one hundred converts that percentage into a dollar figure. Adding it back to the base gives the total rate billed. The formula works because fuel cost rises and falls independently of the underlying line-haul price, so expressing it as a separate percentage lets the charge move with fuel prices without renegotiating the base rate.",
    explanation: "A fuel surcharge is a separate, adjustable fee that carriers add on top of the base freight rate to cover swings in diesel prices, and it appears on almost every trucking and freight invoice. This fuel surcharge calculator multiplies the base rate by the surcharge percentage to show the surcharge amount and the total rate you will actually pay, so there are no surprises when the bill lands.\n\nUnderstanding the fuel surcharge matters because fuel is one of the largest and most volatile costs in transportation. Rather than constantly renegotiating base rates as diesel prices move, carriers and shippers agree on a base line-haul rate plus a fuel surcharge that floats with fuel prices, usually tied to a published diesel index. Shippers use this tool to verify invoices, and carriers use it to quote transparent, defensible pricing.\n\nThe calculation works because the surcharge is defined as a percentage of the base rate, so converting that percentage to dollars and adding it back gives the all-in charge. Keeping the surcharge separate protects both sides: shippers see exactly how much of their cost is fuel, and carriers recover rising fuel expenses without eroding their line-haul margin. Whether you are budgeting freight spend, auditing a carrier invoice, or building a rate quote, calculating the fuel surcharge up front ensures the total rate reflects current fuel conditions fairly and accurately.",
    example: { inputs: { baseRate: 1000, surchargePercent: 12 }, explanation: "1,000 × 12% = 120 surcharge; 1,000 + 120 = $1,120 total." },
    faqs: [
      {
        question: "How is a freight fuel surcharge calculated?",
        answer: "The most common method applies a percentage to the base freight rate, which is exactly what this calculator does. That percentage is often derived from a published diesel price index, rising as fuel gets more expensive and falling when it drops. Some carriers instead use a cents-per-mile surcharge tied to a fuel price table. Either way, the goal is to recover fuel costs separately from the base line-haul rate.",
      },
      {
        question: "Why do carriers charge a separate fuel surcharge?",
        answer: "Diesel prices are volatile and can change week to week, so building fuel into a fixed base rate would force constant renegotiation. A separate fuel surcharge lets the base rate stay stable while the fuel component floats with actual prices. This protects carriers from losing money when fuel spikes and gives shippers transparency, since they can see precisely how much of their freight cost is driven by fuel at any given time.",
      },
      {
        question: "How is the surcharge percentage set?",
        answer: "The percentage is usually pegged to a published diesel benchmark, most often a national or regional on-highway diesel average. Carriers and shippers agree on a base fuel price and a scale that raises the surcharge percentage as the index climbs above that baseline. When you receive a quote, ask which index and schedule apply so you can verify the surcharge percentage matches current published fuel prices.",
      },
      {
        question: "Does the fuel surcharge apply to the whole invoice?",
        answer: "Typically the surcharge is calculated on the base line-haul rate, not on accessorial charges like detention, liftgate, or residential fees. This calculator applies the percentage to the base rate you enter, so make sure that figure is the line-haul portion. If your carrier applies the surcharge differently, enter the amount they base it on so the result matches how your invoice is actually built.",
      },
      {
        question: "Can I negotiate the fuel surcharge?",
        answer: "Yes. While the surcharge is meant to track fuel prices, the base fuel price, the index used, and the percentage scale are all negotiable in a carrier contract. Shippers with volume can negotiate a lower surcharge scale or a higher baseline before the surcharge kicks in. Understanding how the surcharge is calculated puts you in a stronger position to question and adjust it during rate negotiations.",
      },
    ],
    relatedCalculators: ["cost-per-mile-calculator", "landed-cost-calculator", "dimensional-weight-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "delivery-time-estimate",
    slug: "delivery-time-estimator-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Delivery Time Estimator",
    shortDescription: "Estimate delivery time from distance and speed.",
    seoTitle: "Delivery Time Estimator — Transit Time Calculator",
    metaDescription: "Free delivery time estimator. Enter distance, average speed, and rest hours to estimate total transit time and driving hours for a shipment or route.",
    primaryKeyword: "delivery time estimator",
    secondaryKeywords: ["transit time calculator", "delivery time calculator", "eta calculator freight"],
    fields: [
      { id: "distanceMiles", label: "Distance", type: "number", unit: "mi", required: true, span: 1, min: 0 },
      { id: "avgSpeedMph", label: "Average speed", type: "number", unit: "mph", required: true, span: 1, min: 0 },
      { id: "restHours", label: "Rest hours", type: "number", unit: "hr", required: false, span: 2, min: 0, defaultValue: 0, helpText: "Total breaks and rest stops. Defaults to 0." },
    ],
    results: [
      { id: "totalHours", label: "Total transit time", format: "number", decimals: 2, unit: "hr", isPrimary: true },
      { id: "drivingHours", label: "Driving time", format: "number", decimals: 2, unit: "hr", isPrimary: false },
    ],
    formula: "total hours = distance ÷ average speed + rest hours",
    formulaExplanation: "Driving time is distance divided by average speed, the basic relationship between how far you travel and how fast you cover it. Adding rest hours accounts for the mandatory breaks, meals, and overnight stops that a real trip requires but that pure driving math ignores. The formula works because distance and speed determine the wheels-turning portion of a journey, while separate rest time reflects the legal and human limits that stretch the total transit time well beyond the raw driving hours.",
    explanation: "Estimating delivery time accurately keeps customers informed, dispatchers realistic, and schedules achievable. This delivery time estimator divides the route distance by the average speed to find driving hours, then adds any rest hours you expect for breaks and overnight stops to give the total transit time from origin to destination.\n\nThis matters because a naive distance-divided-by-speed estimate ignores the reality of long-haul transport, where drivers must stop for fuel, meals, and legally mandated rest. Quoting a delivery time based on driving hours alone sets everyone up for missed appointments. By separating pure driving time from rest time, the tool gives both a best-case driving figure and a realistic door-to-door estimate you can actually promise a customer.\n\nThe calculation works because speed is simply distance over time, so distance over speed returns time, and the rest hours you add reflect the pauses that stretch a journey. Use a realistic average speed that accounts for traffic, terrain, and stops rather than a highway top speed, and estimate rest hours from the hours-of-service rules and the trip length. Dispatchers, ecommerce sellers, and logistics planners rely on transit time estimates to set delivery windows, plan driver schedules, and coordinate loading and unloading appointments so freight arrives when it is expected.",
    example: { inputs: { distanceMiles: 300, avgSpeedMph: 60, restHours: 2 }, explanation: "300 ÷ 60 = 5 driving hours; + 2 rest = 7 hours total." },
    faqs: [
      {
        question: "What average speed should I use?",
        answer: "Use a realistic effective speed rather than the highway limit. For long-haul trucking, an average of 50 to 55 miles per hour often reflects real conditions once you factor in traffic, terrain, city driving, and minor stops. For local delivery, the average is much lower. Choosing a speed that matches the route and vehicle produces a driving time estimate that holds up against what actually happens on the road.",
      },
      {
        question: "How do I estimate rest hours for a trip?",
        answer: "Base rest hours on the trip length and applicable hours-of-service rules. Drivers typically need a break after several hours of driving and a longer overnight rest on multi-day hauls, often around ten hours off after eleven hours of driving in the United States. Add up the breaks, meals, and overnight stops the journey will require, and enter that total so the transit estimate reflects legally required and practical rest.",
      },
      {
        question: "Why separate driving time from rest time?",
        answer: "Driving time tells you the minimum wheels-turning duration, while total transit time tells you when freight will actually arrive. Separating them lets you see both the theoretical best case and the realistic promise. It also helps you spot whether adding a second driver or adjusting the schedule could cut delivery time, since only the rest portion, not the driving portion, can be reduced by team driving or route changes.",
      },
      {
        question: "Does this estimator account for traffic and weather?",
        answer: "Not directly, but you control for them through the average speed you enter. Lowering the average speed effectively builds in congestion, road works, and adverse weather. For a route with known bottlenecks or seasonal conditions, choose a more conservative speed. Treat the result as a planning estimate and add a buffer for unpredictable delays, especially when you are committing to a customer delivery window.",
      },
      {
        question: "Can I use this for multi-stop routes?",
        answer: "For a single leg, enter that leg's distance and speed. For a multi-stop route, either sum the total distance and add rest and service time at each stop into the rest hours field, or calculate each leg separately and add the results. Remember to include time spent loading and unloading at each stop, since that dwell time adds to the total journey just as driver rest does.",
      },
    ],
    relatedCalculators: ["cost-per-mile-calculator", "fuel-surcharge-calculator", "order-picking-time-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "truck-load-utilization",
    slug: "truck-load-utilization-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Truck Load Utilization Calculator",
    shortDescription: "Measure how full your truck is by volume.",
    seoTitle: "Truck Load Utilization Calculator — Trailer Fill Rate",
    metaDescription: "Free truck load utilization calculator. Enter used cubic feet and trailer capacity to find your load utilization percentage and cut wasted space.",
    primaryKeyword: "truck load utilization calculator",
    secondaryKeywords: ["trailer utilization calculator", "truck fill rate calculator", "load factor calculator"],
    fields: [
      { id: "usedCubicFeet", label: "Used space", type: "number", unit: "ft³", required: true, span: 1, min: 0 },
      { id: "truckCapacityCubicFeet", label: "Truck capacity", type: "number", unit: "ft³", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "utilization", label: "Load utilization", format: "percentage", decimals: 1, isPrimary: true },
    ],
    formula: "utilization = used cubic feet ÷ truck capacity × 100",
    formulaExplanation: "Load utilization divides the cubic feet of cargo actually loaded by the truck's total cubic capacity and multiplies by one hundred to express the result as a percentage. The formula works because a trailer is a fixed volume, and the share of that volume you fill directly measures how efficiently you are using the space you pay to move. A higher percentage means fewer trucks and less wasted air, which is the core lever for cutting cost per unit shipped.",
    explanation: "Truck load utilization measures how much of a trailer's available space your cargo actually fills, expressed as a percentage of total capacity. This truck load utilization calculator divides the used cubic feet by the trailer's cubic capacity and multiplies by one hundred, giving you a clear fill rate that reveals how efficiently each truck is loaded.\n\nUtilization matters because every truck you dispatch costs roughly the same whether it is full or half empty. A trailer running at 60 percent utilization is paying to move a lot of air, which inflates your cost per unit and your carbon footprint. Tracking the fill rate helps shippers and fleet managers spot underloaded trucks, consolidate shipments, and decide whether goods can be combined into fewer, fuller loads to lower freight spend.\n\nThe calculation works because a trailer is a fixed volume, so the ratio of cargo volume to trailer volume is a direct efficiency measure. Note that utilization can be limited by weight as well as space; a truck may reach its legal weight limit while still looking half empty by volume, especially for dense goods. Use volume utilization to find bulky, space-wasting loads and pair it with a weight check for the full picture. Logistics teams monitor utilization across shipments to benchmark performance, justify packaging changes, and set targets that squeeze more value from every mile a truck runs.",
    example: { inputs: { usedCubicFeet: 1500, truckCapacityCubicFeet: 3000 }, explanation: "1,500 ÷ 3,000 × 100 = 50% utilization." },
    faqs: [
      {
        question: "What is a good truck load utilization percentage?",
        answer: "Higher is generally better, and many operations target 80 percent or more by volume, but the right figure depends on your freight. Dense goods may fill the weight limit long before the space, so 100 percent volume utilization is not always achievable or desirable. Use the percentage as a trend and a comparison tool: rising utilization means you are consolidating well, while a low figure flags trucks moving mostly empty space.",
      },
      {
        question: "How do I find my trailer's cubic capacity?",
        answer: "Multiply the usable internal length, width, and height of the trailer in feet. A typical 53-foot dry van offers roughly 3,800 to 4,000 cubic feet of usable space, though the exact figure varies by trailer. Use interior dimensions, not exterior, and account for any intrusions like wheel wells. Enter that capacity here so the utilization percentage compares your cargo against the real space available inside the trailer.",
      },
      {
        question: "Should utilization be measured by volume or weight?",
        answer: "Both matter, and the binding constraint depends on the cargo. Light, bulky goods fill the volume first, so volume utilization is the key metric. Dense, heavy goods hit the weight limit while space remains, so weight utilization matters more. This calculator measures volume. For a complete view, also compare your load weight against the trailer's legal payload, and manage to whichever limit you reach first.",
      },
      {
        question: "How can I improve load utilization?",
        answer: "Consolidate shipments so trucks leave fuller, use pallet patterns and packaging that stack efficiently, and combine orders heading the same direction. Reducing oversized packaging and void fill frees space for more product. Planning software that optimises how boxes and pallets fit the trailer can lift utilization significantly. Even small gains compound, because each percentage point of better fill means fewer trucks and lower cost per unit shipped.",
      },
      {
        question: "Why does empty space cost so much?",
        answer: "A truck's cost, including driver, fuel, and equipment, is largely fixed per trip regardless of how full it is. When a trailer runs half empty, you pay nearly the full cost to move half the freight, doubling your effective cost per unit. Empty space also means more trucks on the road to move the same goods, raising fuel use and emissions. Maximising utilization spreads fixed costs over more cargo.",
      },
    ],
    relatedCalculators: ["warehouse-space-calculator", "pallet-count-calculator", "cbm-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "warehouse-space",
    slug: "warehouse-space-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Warehouse Space Calculator",
    shortDescription: "Estimate warehouse floor space for pallets.",
    seoTitle: "Warehouse Space Calculator — Pallet Storage Square Feet",
    metaDescription: "Free warehouse space calculator. Enter pallet count and square feet per pallet to estimate the total floor space your inventory needs for storage planning.",
    primaryKeyword: "warehouse space calculator",
    secondaryKeywords: ["pallet storage calculator", "warehouse square footage calculator", "storage space calculator"],
    fields: [
      { id: "palletCount", label: "Pallet count", type: "number", unit: "pallets", required: true, span: 1, min: 0 },
      { id: "sqFtPerPallet", label: "Sq ft per pallet", type: "number", unit: "ft²", required: false, span: 1, min: 0, step: 0.1, defaultValue: 13.4, helpText: "Footprint incl. aisle allowance. Defaults to 13.4." },
    ],
    results: [
      { id: "totalSqFt", label: "Total floor space", format: "number", decimals: 0, unit: "ft²", isPrimary: true },
    ],
    formula: "total sq ft = pallet count × square feet per pallet",
    formulaExplanation: "Total floor space multiplies the number of pallets by the square footage each pallet occupies, including a share of aisle and access space. The formula works because storage footprint scales linearly with pallet count once you fix the space each pallet position demands. A standard 48-by-40-inch pallet covers about 13.4 square feet of pure footprint, so multiplying by the pallet count converts an inventory quantity into the physical floor area a facility must provide.",
    explanation: "Planning warehouse space starts with knowing how much floor area your pallets will occupy. This warehouse space calculator multiplies the number of pallets by the square footage each pallet requires, giving a quick estimate of total floor space so you can size a facility, plan a layout, or budget for storage.\n\nThis matters because warehouse space is expensive and often the largest fixed cost in a distribution operation. Underestimating leads to congestion, blocked aisles, and safety hazards, while overestimating wastes rent on empty floor. A standard 48-by-40-inch pallet has a footprint of about 13.4 square feet, but the practical space per pallet is higher once you add aisles, so adjust the per-pallet figure to match how you actually store and access goods.\n\nThe calculation works because floor space scales directly with pallet count when each pallet position takes a fixed area. The default of 13.4 square feet reflects the bare footprint; if your pallets are floor-stacked with wide aisles, use a larger figure, and if you rack pallets several tiers high, the effective floor area per pallet drops because you store vertically. Warehouse managers, third-party logistics providers, and businesses planning a move use this estimate to compare facilities, negotiate storage contracts, and confirm that inventory will fit before signing a lease or committing to a layout.",
    example: { inputs: { palletCount: 100, sqFtPerPallet: 13.4 }, explanation: "100 × 13.4 = 1,340 square feet of pallet footprint." },
    faqs: [
      {
        question: "How much floor space does one pallet need?",
        answer: "A standard 48-by-40-inch pallet has a footprint of about 13.4 square feet, which is the default this calculator uses. In practice you need more once you add aisles for forklifts and picking access, often pushing the effective space to 20 or more square feet per pallet for floor storage. Adjust the per-pallet figure to reflect your aisle width and handling equipment for a realistic total.",
      },
      {
        question: "Should I include aisle space in the per-pallet figure?",
        answer: "For a true floor-space estimate, yes. The bare 13.4 square feet covers only the pallet itself, not the aisles forklifts need to reach it. To size a real warehouse, raise the per-pallet figure to include a share of aisle and staging space, commonly a 40 to 60 percent add-on. Enter that larger number here so the total reflects the usable area your operation genuinely requires.",
      },
      {
        question: "How does racking change the space I need?",
        answer: "Racking lets you store pallets vertically, so several pallets share the same floor footprint. If you rack three pallets high, the effective floor area per pallet position drops to roughly a third of the ground footprint plus aisle space. To model this, divide your per-pallet square footage by the number of tiers you rack, which dramatically reduces the floor space a given pallet count demands.",
      },
      {
        question: "What size warehouse do I need for my inventory?",
        answer: "Start by multiplying your pallet count by a realistic per-pallet area that includes aisles, then add space for receiving, shipping, staging, offices, and equipment, often another 20 to 30 percent on top. This calculator gives the pallet storage portion; layer the support areas on afterwards. Comparing that total against candidate facilities helps you avoid leasing a space that is too tight or wastefully large.",
      },
      {
        question: "Does pallet type affect the calculation?",
        answer: "Yes. The default assumes a standard 48-by-40-inch pallet at 13.4 square feet, but Euro pallets, half pallets, and oversized pallets have different footprints. Measure the length and width of your actual pallet, multiply them, and convert to square feet to get the correct per-pallet figure. Using the right footprint for your pallet type ensures the total floor space estimate matches what your inventory will really occupy.",
      },
    ],
    relatedCalculators: ["pallet-count-calculator", "truck-load-utilization-calculator", "pallet-stack-height-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "order-picking-time",
    slug: "order-picking-time-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Order Picking Time Calculator",
    shortDescription: "Estimate how long an order takes to pick.",
    seoTitle: "Order Picking Time Calculator — Warehouse Pick Time",
    metaDescription: "Free order picking time calculator. Enter the number of items and seconds per item to estimate total picking time in minutes for labour and throughput planning.",
    primaryKeyword: "order picking time calculator",
    secondaryKeywords: ["pick time calculator", "warehouse picking calculator", "picking productivity calculator"],
    fields: [
      { id: "numberOfItems", label: "Number of items", type: "number", unit: "items", required: true, span: 1, min: 0 },
      { id: "secondsPerItem", label: "Seconds per item", type: "number", unit: "sec", required: false, span: 1, min: 0, defaultValue: 30, helpText: "Average pick time per line. Defaults to 30." },
    ],
    results: [
      { id: "totalMinutes", label: "Total picking time", format: "number", decimals: 1, unit: "min", isPrimary: true },
    ],
    formula: "total minutes = items × seconds per item ÷ 60",
    formulaExplanation: "Total picking time multiplies the number of items by the average seconds each takes to pick, then divides by sixty to convert seconds into minutes. The formula works because picking is a repetitive task where each line item consumes a roughly consistent amount of time to locate, grab, and confirm. Multiplying the count by the per-item rate estimates total labour time, and the division simply expresses that time in the minutes warehouse planners use to schedule shifts and set throughput targets.",
    explanation: "Order picking is often the most labour-intensive activity in a warehouse, and estimating how long it takes is essential for staffing, scheduling, and hitting shipping deadlines. This order picking time calculator multiplies the number of items by the average seconds each takes to pick, then converts to minutes, giving a fast estimate of the labour time an order requires.\n\nThis matters because picking can absorb half or more of warehouse labour costs. Knowing the time per order lets managers schedule the right number of pickers, set realistic cut-off times for same-day shipping, and identify orders large enough to warrant batch or zone picking. It also provides a baseline to measure process improvements against, so you can quantify the gain from better slotting, pick paths, or technology.\n\nThe calculation works because picking time scales with the number of line items when each takes a fairly consistent time to locate, retrieve, and confirm. The default of 30 seconds per item is a reasonable starting point, but your real rate depends on warehouse size, storage method, travel distance, and whether pickers use paper, scanners, or voice systems. Measure your own average and enter it for accuracy. Warehouse supervisors, fulfilment teams, and operations analysts use pick time estimates to balance workloads, plan capacity for peak seasons, and build the throughput models that keep orders flowing out the door on schedule.",
    example: { inputs: { numberOfItems: 120, secondsPerItem: 30 }, explanation: "120 × 30 = 3,600 seconds; ÷ 60 = 60 minutes." },
    faqs: [
      {
        question: "What is a realistic seconds-per-item pick rate?",
        answer: "It varies widely with warehouse layout, storage method, and technology, but many operations fall between 20 and 60 seconds per item, with the default of 30 a common middle ground. Small, dense warehouses with short travel and scanners pick faster, while large facilities with long walks pick slower. The best figure is your own measured average, timed across a representative sample of orders and pickers.",
      },
      {
        question: "Does this include travel time between locations?",
        answer: "The per-item figure should bake in an average share of travel time, since walking between pick locations is a major part of picking. If your seconds-per-item rate is measured door to door across whole orders, travel is already included. If it only counts the grab itself, raise the figure to account for travel, or the estimate will understate the true time each order takes to complete.",
      },
      {
        question: "How can I reduce order picking time?",
        answer: "Slot fast-moving items near the packing area and at ergonomic heights, optimise pick paths to cut travel, and batch or zone pick to handle multiple orders per trip. Barcode scanners, pick-to-light, and voice picking speed confirmation and reduce errors. Each of these lowers your seconds-per-item rate. Measure the rate before and after a change using this calculator to quantify how much time the improvement actually saves.",
      },
      {
        question: "Should I use this per order or per shift?",
        answer: "Both work. For a single order, enter that order's item count to estimate its pick time. For a shift, sum the items across all orders to estimate total picking labour, which helps you decide how many pickers you need. Dividing total items by picker capacity per hour tells you whether your current staffing can clear the workload before shipping cut-off.",
      },
      {
        question: "Why does picking dominate warehouse labour cost?",
        answer: "Picking is repetitive, travel-heavy, and touches every single order, so it accumulates more labour hours than receiving, put-away, or shipping. Studies commonly attribute half or more of warehouse labour to picking. Because it is so large a share, even small per-item time savings translate into significant cost reductions across thousands of orders, which is why operations invest heavily in slotting, layout, and picking technology.",
      },
    ],
    relatedCalculators: ["warehouse-space-calculator", "delivery-time-estimator-calculator", "safety-stock-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "safety-stock",
    slug: "safety-stock-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Safety Stock Calculator",
    shortDescription: "Calculate buffer inventory to avoid stockouts.",
    seoTitle: "Safety Stock Calculator — Buffer Inventory Level",
    metaDescription: "Free safety stock calculator. Enter maximum and average daily usage plus lead time to find the buffer inventory needed to protect against stockouts.",
    primaryKeyword: "safety stock calculator",
    secondaryKeywords: ["buffer stock calculator", "safety stock formula calculator", "inventory buffer calculator"],
    fields: [
      { id: "maxDailyUsage", label: "Max daily usage", type: "number", unit: "units", required: true, span: 1, min: 0 },
      { id: "avgDailyUsage", label: "Average daily usage", type: "number", unit: "units", required: true, span: 1, min: 0 },
      { id: "leadTimeDays", label: "Lead time", type: "number", unit: "days", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "safetyStock", label: "Safety stock", format: "number", decimals: 0, unit: "units", isPrimary: true },
    ],
    formula: "safety stock = (max daily usage − average daily usage) × lead time",
    formulaExplanation: "This safety stock formula multiplies the gap between peak and average daily demand by the supplier lead time in days. The formula works because the risk of a stockout comes from demand running hotter than expected while you wait for replenishment. The difference between maximum and average usage captures how much extra you could consume on a bad day, and multiplying by lead time totals that excess across the whole reorder window you must cover with a buffer.",
    explanation: "Safety stock is the buffer inventory you hold to protect against running out when demand spikes or a delivery runs late. This safety stock calculator uses the classic formula, multiplying the difference between your maximum and average daily usage by the lead time, to find how many extra units you should keep on hand as insurance against stockouts.\n\nThis matters because stockouts cost sales, damage customer trust, and disrupt production, while too much safety stock ties up cash and warehouse space. Getting the buffer right strikes the balance. The calculation focuses on demand variability: the gap between a busy day and an average day tells you how much extra you might consume, and the lead time tells you how long you are exposed to that risk while waiting for a replenishment order to arrive.\n\nThe formula works because the danger window is the lead time, and the worst case within it is demand running at its maximum rather than its average. Multiplying the daily excess by the number of lead-time days totals the extra units needed to survive a demand spike without a stockout. This straightforward method suits many products, though items with highly variable lead times may warrant a more advanced statistical formula. Inventory planners, purchasing managers, and small business owners use safety stock levels to set reorder points, size replenishment orders, and keep shelves stocked through demand swings without drowning in excess inventory.",
    example: { inputs: { maxDailyUsage: 100, avgDailyUsage: 70, leadTimeDays: 5 }, explanation: "(100 − 70) × 5 = 30 × 5 = 150 units of safety stock." },
    faqs: [
      {
        question: "What is safety stock and why do I need it?",
        answer: "Safety stock is extra inventory held as a cushion against uncertainty in demand and supply. Without it, a sudden sales spike or a delayed delivery leaves you unable to fulfil orders, costing revenue and customer goodwill. With it, you can absorb those surprises and keep selling while a replenishment order is in transit. The right level protects service without over-investing cash in inventory that sits idle on the shelf.",
      },
      {
        question: "How is the safety stock formula derived?",
        answer: "This version multiplies the difference between maximum and average daily usage by the lead time. The logic is that demand above average during the lead-time window is what drains your buffer, so the daily excess times the number of exposed days gives the units needed to cover a worst-case spike. It is a simple, widely taught method that works well when lead time is fairly stable and demand is the main source of variability.",
      },
      {
        question: "Does this formula account for variable lead time?",
        answer: "No, this version assumes lead time is fixed and focuses on demand variability. If your supplier delivery times swing significantly, this method can understate the buffer you need. In that case, a statistical formula using the standard deviation of both demand and lead time, combined with a target service level and a Z-score, gives a more robust figure. Use this calculator as a solid starting estimate and refine it if lead times are erratic.",
      },
      {
        question: "How does safety stock relate to the reorder point?",
        answer: "The reorder point is the inventory level that triggers a new order, and it equals the expected demand during lead time plus safety stock. So safety stock is a building block of the reorder point. Calculate your safety stock here, add the average usage expected across the lead time, and you have the level at which to reorder so replenishment arrives before the buffer is exhausted.",
      },
      {
        question: "What happens if I hold too much safety stock?",
        answer: "Excess safety stock ties up working capital, consumes warehouse space, and increases carrying costs like insurance, handling, and obsolescence risk, especially for perishable or fast-changing products. The goal is the minimum buffer that meets your target service level, not the maximum you can fit. Review your usage and lead-time inputs regularly, because demand patterns shift, and a buffer sized for last year's peak may be far larger than this year needs.",
      },
    ],
    relatedCalculators: ["order-picking-time-calculator", "warehouse-space-calculator", "pallet-count-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard inventory management formula",
  },
  {
    id: "freight-class",
    slug: "freight-class-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Freight Class Calculator",
    shortDescription: "Find shipment density for LTL freight class.",
    seoTitle: "Freight Class Calculator — LTL Density in PCF",
    metaDescription: "Free freight class calculator. Enter weight and dimensions to find shipment density in pounds per cubic foot, the figure that drives your LTL freight class.",
    primaryKeyword: "freight class calculator",
    secondaryKeywords: ["ltl freight class calculator", "freight density calculator", "nmfc class calculator"],
    fields: [
      { id: "weightLbs", label: "Weight", type: "number", unit: "lb", required: true, span: 2, min: 0 },
      { id: "lengthIn", label: "Length", type: "number", unit: "in", required: true, span: 1, min: 0 },
      { id: "widthIn", label: "Width", type: "number", unit: "in", required: true, span: 1, min: 0 },
      { id: "heightIn", label: "Height", type: "number", unit: "in", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "densityPcf", label: "Density", format: "number", decimals: 2, unit: "lb/ft³", isPrimary: true },
    ],
    formula: "density = weight ÷ (length × width × height ÷ 1,728)",
    formulaExplanation: "Freight class density divides the shipment weight by its volume in cubic feet, where volume comes from multiplying the three dimensions in inches and dividing by 1,728, the number of cubic inches in a cubic foot. The formula works because less-than-truckload carriers assign freight class largely on density, since it captures how efficiently a shipment uses trailer space. A higher density in pounds per cubic foot generally maps to a lower, cheaper class, making this figure the starting point for classifying and pricing LTL freight.",
    explanation: "Freight class determines what you pay to ship less-than-truckload freight, and density in pounds per cubic foot is the single most important factor behind it. This freight class calculator multiplies your shipment's length, width, and height, converts the result to cubic feet, and divides the weight by that volume to give the density carriers use as the starting point for assigning a class.\n\nThis matters because the national freight classification system rates commodities from class 50 for dense, durable goods up to class 500 for light, bulky items, and higher classes cost more. For many products, density alone determines the class, so knowing your pounds per cubic foot lets you predict the class, quote accurately, and avoid the reclassification charges that hit when a carrier re-measures a shipment and finds it lighter or bulkier than declared.\n\nThe calculation works because dividing cubic inches by 1,728 converts to the cubic feet that classification tables use, and dividing weight by volume yields the density those tables are built around. Denser freight packs trailers efficiently and earns a lower class, while low-density freight wastes space and climbs the scale. Note that some commodities are classed by factors beyond density, such as handling, stowability, and liability, so density gives the class for density-based items but not every one. Shippers, brokers, and warehouse teams calculate density before booking to estimate class, compare carrier quotes fairly, and package goods to reach a cheaper class where possible.",
    example: { inputs: { weightLbs: 30, lengthIn: 12, widthIn: 12, heightIn: 12 }, explanation: "12 × 12 × 12 ÷ 1,728 = 1 ft³; 30 ÷ 1 = 30 lb/ft³." },
    faqs: [
      {
        question: "How does density map to a freight class?",
        answer: "Freight classes run from 50 to 500, and density-based tables assign lower classes to denser freight. Roughly, 30 or more pounds per cubic foot often lands around class 60 to 70, while under 1 pound per cubic foot can reach class 400 or higher. The exact mapping comes from the national classification tables, so use your calculated density to look up the corresponding class in the current schedule your carrier follows.",
      },
      {
        question: "Is freight class always based on density?",
        answer: "Not always. For many commodities density is the primary driver, but the classification system also weighs handling, stowability, and liability. Fragile, hazardous, or hard-to-stack goods may carry a higher class than density alone suggests, and some items have a fixed class regardless of density. Use this calculator to get the density and the density-based class, then check the specific commodity listing, because those other factors can override a pure density result.",
      },
      {
        question: "What happens if I declare the wrong class?",
        answer: "If a carrier inspects your shipment and finds the actual density or commodity differs from what you declared, they reclassify it and issue an adjusted, usually higher, charge plus possible fees. Reclassification is a common and avoidable cost. Measuring and weighing your shipment accurately, then calculating density with this tool before you book, helps you declare the correct class up front and avoid unexpected charges after pickup.",
      },
      {
        question: "Should I measure the packaged shipment or the product?",
        answer: "Always measure the shipment exactly as it ships, including pallets, crating, and any overhang, and weigh the complete packaged load. Carriers rate the space the freight actually occupies, so packaging counts toward both volume and weight. Measuring the bare product understates volume and inflates density, which can produce the wrong class and trigger a reclassification when the carrier re-measures the real, packaged dimensions on the dock.",
      },
      {
        question: "How do I lower my freight class?",
        answer: "Since density drives many classes, increasing density lowers the class and the cost. Use tighter packaging to reduce volume without adding much weight, consolidate loose items onto a single well-packed pallet, and remove excess void space. Stackable, sturdy packaging can also improve handling and stowability factors. Recalculate density after repackaging to confirm you have crossed into a lower class bracket before you book the shipment.",
      },
    ],
    relatedCalculators: ["freight-density-calculator", "dimensional-weight-calculator", "chargeable-weight-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard freight/logistics formula",
  },
  {
    id: "chargeable-weight",
    slug: "chargeable-weight-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Chargeable Weight Calculator",
    shortDescription: "Find air freight chargeable weight.",
    seoTitle: "Chargeable Weight Calculator — Air Freight Volumetric Weight",
    metaDescription: "Free chargeable weight calculator. Enter actual weight and dimensions in centimetres to find volumetric and chargeable weight for air freight pricing.",
    primaryKeyword: "chargeable weight calculator",
    secondaryKeywords: ["volumetric weight calculator", "air freight weight calculator", "dimensional weight calculator kg"],
    fields: [
      { id: "actualWeightKg", label: "Actual weight", type: "number", unit: "kg", required: true, span: 2, min: 0 },
      { id: "lengthCm", label: "Length", type: "number", unit: "cm", required: true, span: 1, min: 0 },
      { id: "widthCm", label: "Width", type: "number", unit: "cm", required: true, span: 1, min: 0 },
      { id: "heightCm", label: "Height", type: "number", unit: "cm", required: true, span: 1, min: 0 },
      { id: "divisor", label: "Volumetric divisor", type: "number", required: false, span: 1, min: 1, defaultValue: 5000, helpText: "Air freight factor. Defaults to 5000." },
    ],
    results: [
      { id: "chargeableWeight", label: "Chargeable weight", format: "number", decimals: 2, unit: "kg", isPrimary: true },
      { id: "volumetricWeight", label: "Volumetric weight", format: "number", decimals: 2, unit: "kg", isPrimary: false },
    ],
    formula: "chargeable = max(actual weight, (L × W × H) ÷ divisor)",
    formulaExplanation: "Chargeable weight is the greater of actual weight and volumetric weight, where volumetric weight multiplies length, width, and height in centimetres and divides by a divisor, commonly 5,000 for air freight. The formula works because aircraft run out of space before payload for light, bulky cargo, so carriers bill the higher of mass and volume-equivalent weight. Taking the maximum ensures they recover the value of either the weight or the space a shipment consumes, whichever costs them more.",
    explanation: "Chargeable weight is the figure air freight carriers actually bill you on, and it is the greater of your shipment's real weight and its volumetric weight. This chargeable weight calculator multiplies your package dimensions in centimetres, divides by the air freight divisor, and compares the result against the actual weight to show both the volumetric weight and the chargeable weight you will pay for.\n\nThis matters because a light but bulky shipment costs an airline the same cargo space as a heavy one, so carriers charge on whichever is higher: mass or volume. Shippers who quote against actual weight alone are frequently surprised when the freight invoice bills a much higher volumetric figure. Calculating chargeable weight up front lets you compare quotes accurately, choose the right packaging, and forecast air freight costs before booking.\n\nThe calculation works because the volumetric divisor, typically 5,000 for international air freight in centimetres and kilograms, encodes an assumed density: every 5,000 cubic centimetres counts as one kilogram. Multiplying the dimensions and dividing by the divisor converts volume into a weight the carrier can compare against the scale weight. Taking the maximum reflects the carrier's need to recover either the payload or the space, whichever is more valuable. Exporters, ecommerce sellers, and freight forwarders rely on chargeable weight to price shipments, decide between air and sea, and right-size cartons so they do not pay for empty air on every kilogram shipped.",
    example: { inputs: { actualWeightKg: 10, lengthCm: 100, widthCm: 50, heightCm: 50, divisor: 5000 }, explanation: "100 × 50 × 50 ÷ 5,000 = 50 kg volumetric; max(10, 50) = 50 kg chargeable." },
    faqs: [
      {
        question: "What divisor should I use for air freight?",
        answer: "The standard international air freight divisor is 5,000 when dimensions are in centimetres and weight in kilograms, which this calculator uses by default. It reflects an industry density of 167 kilograms per cubic metre. Some express carriers use different divisors, such as 6,000, which produces a lower volumetric weight. Always confirm the divisor in your carrier's rate agreement, since a smaller divisor yields a larger, more expensive chargeable weight.",
      },
      {
        question: "Why is chargeable weight the greater of the two?",
        answer: "Aircraft have limited space and limited payload, and for light, bulky cargo the space runs out first. If carriers billed only by mass, a plane full of oversized, lightweight boxes would earn far less than its capacity is worth. Charging the greater of actual and volumetric weight ensures the carrier recovers the value of whichever resource, weight or space, the shipment consumes more of, which for bulky goods is the volume.",
      },
      {
        question: "How is volumetric weight different from actual weight?",
        answer: "Actual weight is what the shipment reads on a scale, while volumetric weight expresses how much that shipment's size would weigh at a standard density. A dense, compact box has volumetric weight below its actual weight, so it bills on actual weight. A large, light box has volumetric weight above its actual weight, so it bills on volume. The chargeable weight is simply whichever of the two is larger.",
      },
      {
        question: "Does chargeable weight apply to sea freight too?",
        answer: "Sea freight uses a related but different approach. Ocean carriers often bill on the greater of weight in tonnes or volume in cubic metres, using a ratio commonly around one tonne per cubic metre, rather than the air divisor. So the principle of charging for weight or space, whichever is greater, carries over, but the specific factor differs. This calculator is set up for air freight; use a CBM-based method for sea shipments.",
      },
      {
        question: "How can I reduce my chargeable weight?",
        answer: "If your shipment bills on volumetric weight, shrinking the box lowers the charge. Use packaging that fits the goods closely, remove excess void fill, and avoid oversized cartons. Because volumetric weight depends only on dimensions, trimming any side reduces it. If instead you bill on actual weight, the box is already efficient and reducing size will not help. Calculate both figures here to see which lever actually lowers your cost.",
      },
    ],
    relatedCalculators: ["dimensional-weight-calculator", "freight-class-calculator", "cbm-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "IATA air freight volumetric standard",
  },
  {
    id: "pallet-stack-height",
    slug: "pallet-stack-height-calculator",
    category: "Logistics",
    categorySlug: "logistics",
    title: "Pallet Stack Height Calculator",
    shortDescription: "Find the total height of a loaded pallet.",
    seoTitle: "Pallet Stack Height Calculator — Loaded Pallet Height",
    metaDescription: "Free pallet stack height calculator. Enter box height, boxes per stack, and pallet base height to find the total loaded pallet height for container and truck fit.",
    primaryKeyword: "pallet stack height calculator",
    secondaryKeywords: ["loaded pallet height calculator", "pallet height calculator", "carton stacking calculator"],
    fields: [
      { id: "boxHeightIn", label: "Box height", type: "number", unit: "in", required: true, span: 1, min: 0 },
      { id: "boxesPerStack", label: "Boxes per stack", type: "number", unit: "boxes", required: true, span: 1, min: 0 },
      { id: "palletBaseIn", label: "Pallet base height", type: "number", unit: "in", required: false, span: 2, min: 0, defaultValue: 6, helpText: "Height of the empty pallet. Defaults to 6." },
    ],
    results: [
      { id: "totalHeightIn", label: "Total stack height", format: "number", decimals: 1, unit: "in", isPrimary: true },
    ],
    formula: "total height = pallet base + box height × boxes per stack",
    formulaExplanation: "Total stack height adds the height of the empty pallet base to the combined height of the boxes stacked on it, found by multiplying one box's height by the number of boxes in the stack. The formula works because a loaded pallet is simply the pallet plus its vertical column of cartons, so summing the base and the stacked cartons gives the overall height that must clear doorways, container ceilings, and racking. A standard pallet base adds about six inches before any cargo.",
    explanation: "The total height of a loaded pallet determines whether it fits inside a container, clears a trailer roof, and slots into your warehouse racking. This pallet stack height calculator adds the pallet's own base height to the combined height of the boxes stacked on top, giving the overall loaded height you need for planning storage and transport.\n\nThis matters because height limits are everywhere in logistics: shipping containers, truck trailers, warehouse rack beams, and doorways all impose a maximum. Exceeding them means a pallet will not fit, forcing last-minute restacking, wasted space, or a rejected load. Calculating the stack height before you build the pallet lets you choose the right number of cartons per column so the finished pallet stays within every clearance it must pass through.\n\nThe calculation works because a loaded pallet is just the empty pallet plus a vertical column of identical boxes, so multiplying box height by the number of boxes and adding the pallet base gives the total. A standard wooden pallet adds about six inches before any cargo, which is the default here; adjust it for your specific pallet type. Warehouse planners, shippers, and container loaders use stack height to maximise how many pallets fit per container tier, confirm double-stacking is possible, and ensure loaded pallets clear the equipment and openings they travel through without costly surprises at the loading dock.",
    example: { inputs: { boxHeightIn: 10, boxesPerStack: 5, palletBaseIn: 6 }, explanation: "6 + 10 × 5 = 6 + 50 = 56 inches total height." },
    faqs: [
      {
        question: "What is the standard pallet base height?",
        answer: "A standard wooden pallet, such as the 48-by-40-inch GMA pallet common in North America, is about 6 inches tall empty, which is the default this calculator uses. Euro pallets and other types differ slightly, often around 5 to 6 inches. Measure your actual pallet if precision matters, because the base height is added to every stack and small differences can decide whether a loaded pallet clears a container or racking beam.",
      },
      {
        question: "How tall can a loaded pallet be?",
        answer: "It depends on the constraint. A standard shipping container interior is about 90 inches tall, so a single pallet tier must stay under that, and double-stacking requires each pallet to be roughly half. Trailers and warehouse racking impose their own limits. Common warehouse practice caps loaded pallets around 60 to 72 inches for stability and safe handling. Check the specific height limit of the container, truck, or rack your pallet must fit.",
      },
      {
        question: "Should I stack all boxes the same way?",
        answer: "For this simple calculation, yes, it assumes a uniform column of identical boxes stacked flat. In practice, interlocking or column-stacking patterns affect stability more than height, and mixing box sizes complicates the math. If your pallet has layers of different heights, add each layer's height separately rather than multiplying by a single box height. Uniform stacking gives the cleanest height estimate and the most stable, predictable load.",
      },
      {
        question: "How does stack height affect double-stacking?",
        answer: "Double-stacking means placing one loaded pallet on top of another, so the combined height of both must fit under the container or trailer ceiling. If a single loaded pallet is 56 inches and the container interior is 90 inches, two stacked pallets at 112 inches will not fit. Calculate the single-pallet height first, double it, and compare against the clearance to confirm whether double-stacking is physically possible.",
      },
      {
        question: "Why does pallet height matter for shipping cost?",
        answer: "Height determines how many pallet tiers fit in a container or trailer, which drives how much cargo moves per shipment and therefore your cost per unit. Shorter, well-planned stacks may allow double-stacking that doubles the pallets per floor position. Overheight pallets waste the space above them and can force extra shipments. Optimising stack height to just fit the available clearance maximises how much freight each container or truck carries.",
      },
    ],
    relatedCalculators: ["pallet-count-calculator", "warehouse-space-calculator", "truck-load-utilization-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard freight/logistics formula",
  },
];
