import type { CalculatorDefinition } from "../types";

export const mathWave2Calculators: CalculatorDefinition[] = [
  {
    id: "standard-deviation",
    slug: "standard-deviation-calculator",
    category: "Math",
    categorySlug: "math",
    title: "Standard Deviation Calculator",
    shortDescription: "Calculate the standard deviation, variance, and mean of a data set.",
    seoTitle: "Standard Deviation Calculator — Free Online Stats Tool",
    metaDescription: "Calculate standard deviation, variance, and mean of any data set. Supports both population and sample standard deviation. Free and instant.",
    primaryKeyword: "standard deviation calculator",
    secondaryKeywords: ["variance calculator", "statistics calculator", "population standard deviation", "sample standard deviation"],
    fields: [
      {
        id: "numbers",
        label: "Data Set",
        type: "text",
        placeholder: "e.g. 2, 4, 4, 4, 5, 5, 7, 9",
        required: true,
        helpText: "Enter numbers separated by commas, spaces, or new lines",
      },
      {
        id: "type",
        label: "Type",
        type: "select",
        defaultValue: "sample",
        required: true,
        unitOptions: [
          { value: "sample", label: "Sample (n−1)" },
          { value: "population", label: "Population (n)" },
        ],
      },
    ],
    results: [
      { id: "stdDev", label: "Standard Deviation", format: "number", decimals: 4, isPrimary: true },
      { id: "variance", label: "Variance", format: "number", decimals: 4, isPrimary: false },
      { id: "mean", label: "Mean", format: "number", decimals: 4, isPrimary: false },
      { id: "count", label: "Count (n)", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "σ = √(Σ(x − μ)² / N) for population; s = √(Σ(x − x̄)² / (n−1)) for sample",
    formulaExplanation: "Squaring each deviation (x − mean) removes negative signs so distances above and below the mean do not cancel, and it penalizes large gaps more heavily. Averaging those squares gives the variance, and taking the square root returns the answer to the original units. Sample data divides by n−1 instead of N because using the sample mean slightly understates spread, and Bessel's correction offsets that bias.",
    formulaSource: "Introductory Statistics, OpenStax",
    sourceUrl: "https://openstax.org/books/introductory-statistics/pages/1-introduction",
    explanation: "Standard deviation is one of the most fundamental statistics, measuring how much individual values in a dataset deviate from the average. A low standard deviation indicates values cluster close to the mean; a high standard deviation signals wide spread.\n\nThe choice between population and sample standard deviation depends on your data. If you have data for every member of a group (e.g., all students in a class), use population standard deviation. If your data is a sample drawn from a larger group (e.g., 50 students surveyed from all students in a country), use sample standard deviation. The sample formula uses n−1 in the denominator (Bessel's correction) to produce an unbiased estimate of the true population standard deviation.\n\nIn practice, standard deviation is used everywhere: quality control (is a manufacturing process consistent?), finance (how volatile is a stock?), education (how spread are test scores?), and science (how precise are measurements?). Combined with the mean, standard deviation defines the normal distribution — roughly 68% of data falls within one standard deviation of the mean, 95% within two, and 99.7% within three (the 68-95-99.7 rule).",
    example: {
      inputs: { numbers: "2, 4, 4, 4, 5, 5, 7, 9", type: "population" },
      explanation: "For the dataset {2, 4, 4, 4, 5, 5, 7, 9}, the mean is 5. Subtracting the mean and squaring each value, then averaging those squares gives a variance of 4. The square root of 4 is 2, so the population standard deviation is 2.",
    },
    faqs: [
      {
        question: "What is the difference between population and sample standard deviation?",
        answer: "Population standard deviation (σ) is used when your dataset contains every member of the group you're studying. It divides the sum of squared deviations by N. Sample standard deviation (s) is used when your dataset is a subset of a larger population. It divides by n−1 (Bessel's correction) to avoid underestimating the true population standard deviation. In most real-world research scenarios, you're working with a sample, so use n−1.",
      },
      {
        question: "What does a standard deviation of 0 mean?",
        answer: "A standard deviation of exactly zero means every value in your dataset is identical — there is no variation whatsoever. For example, the dataset {5, 5, 5, 5} has a standard deviation of 0. In practice, a very low standard deviation (close to zero) indicates very little variability in your data, which could mean a highly consistent manufacturing process, very similar test scores, or stable measurements.",
      },
      {
        question: "How do I interpret standard deviation in real life?",
        answer: "Standard deviation tells you the 'typical' distance of data points from the average. For example, if test scores average 75 with a standard deviation of 10, most students scored between 65 and 85. In finance, a stock with high standard deviation is more volatile. In manufacturing, low standard deviation means consistent product quality. The 68-95-99.7 rule states that for normally distributed data, about 68% of values fall within one standard deviation of the mean.",
      },
      {
        question: "Why is standard deviation preferred over variance?",
        answer: "Standard deviation is preferred because it's expressed in the same units as the original data, making it intuitively interpretable. Variance is expressed in squared units, which can be difficult to relate to the original measurements. For example, if you measure heights in centimeters, the variance would be in cm², but standard deviation remains in cm. Standard deviation is also more directly used in statistical tests, confidence intervals, and the normal distribution.",
      },
      {
        question: "Can standard deviation be negative?",
        answer: "No, standard deviation can never be negative. It's calculated as the square root of variance, and variance is a sum of squared values (which are always non-negative) divided by a positive number. The minimum possible standard deviation is 0, which occurs only when all values in the dataset are identical. If you ever get a negative result, there's an error in the calculation — always double-check your inputs.",
      },
    ],
    relatedCalculators: ["average", "mean-median-mode", "z-score"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "mean-median-mode",
    slug: "mean-median-mode-calculator",
    category: "Math",
    categorySlug: "math",
    title: "Mean, Median & Mode Calculator",
    shortDescription: "Find the mean, median, mode, range, and sum of any data set instantly.",
    seoTitle: "Mean, Median & Mode Calculator — Free Statistics Tool",
    metaDescription: "Calculate mean, median, mode, range, and sum of any data set. Enter numbers separated by commas for instant results. Free online statistics calculator.",
    primaryKeyword: "mean median mode calculator",
    secondaryKeywords: ["average calculator", "statistics calculator", "mode calculator", "median calculator"],
    fields: [
      {
        id: "numbers",
        label: "Data Set",
        type: "text",
        placeholder: "e.g. 3, 7, 7, 2, 9, 4",
        required: true,
        helpText: "Enter numbers separated by commas, spaces, or new lines",
      },
    ],
    results: [
      { id: "mean", label: "Mean (Average)", format: "number", decimals: 4, isPrimary: true },
      { id: "median", label: "Median", format: "number", decimals: 4, isPrimary: false },
      { id: "mode", label: "Mode", format: "text", isPrimary: false },
      { id: "range", label: "Range", format: "number", decimals: 4, isPrimary: false },
      { id: "sum", label: "Sum", format: "number", decimals: 4, isPrimary: false },
      { id: "count", label: "Count", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "Mean = Σx / n; Median = middle value (sorted); Mode = most frequent value; Range = max − min",
    formulaExplanation: "Each measure captures the center differently, which is why they are combined. The mean divides the total by the count, so every value pulls on the result, making it precise but outlier-sensitive. The median takes the middle of the sorted list, ignoring how extreme the ends are, so it resists outliers. The mode counts frequency, so it works even for categories. Range subtracts the smallest value from the largest to show overall spread.",
    formulaSource: "Introductory Statistics, OpenStax",
    sourceUrl: "https://openstax.org/books/introductory-statistics/pages/2-introduction",
    explanation: "Mean, median, and mode are the three measures of central tendency, and each summarizes a dataset with a single representative value in a different way. Knowing when to reach for each one is the core skill behind honest data analysis, which is why a mean median mode reading is usually reported as a group rather than in isolation.\n\nThe mean (arithmetic average) adds all values and divides by the count. It's the most commonly used measure but is sensitive to outliers. A few very high or very low values can pull the mean away from where most data falls.\n\nThe median is the middle value when data is sorted. It's robust to outliers and better represents 'typical' values in skewed distributions. For example, median income is often reported instead of mean income because a few billionaires can make the mean much higher than what most people earn.\n\nThe mode is the most frequently occurring value — the only measure that works for categorical (non-numerical) data. A dataset can have no mode, one mode (unimodal), two modes (bimodal), or many modes (multimodal).\n\nTogether with range — the spread from the minimum to the maximum — these statistics give a quick yet powerful summary of any distribution's shape and center. Analysts, teachers, economists, and researchers lean on mean median mode figures to spot skew, compare groups, and choose the single number that best describes their data before running deeper tests.",
    example: {
      inputs: { numbers: "3, 7, 7, 2, 9, 4" },
      explanation: "For {2, 3, 4, 7, 7, 9}: mean = 32/6 ≈ 5.33; median = (4+7)/2 = 5.5 (average of 3rd and 4th values); mode = 7 (appears twice); range = 9−2 = 7.",
    },
    faqs: [
      {
        question: "When should I use mean vs median vs mode?",
        answer: "Use mean when data is symmetrically distributed without significant outliers — it uses all data points and is most precise. Use median when data is skewed or has outliers (like income, home prices, or ages) — it better represents the 'typical' value. Use mode for categorical data (like most popular product color) or when you want the most common value in a dataset. In many analyses, reporting all three gives the most complete picture.",
      },
      {
        question: "What if my data set has no mode or multiple modes?",
        answer: "A dataset has no mode if every value appears exactly once — no value is more frequent than any other. A dataset has two modes (bimodal) if two values tie for the most frequent occurrence, and multimodal if more than two values tie. Our calculator reports all modes. Having no mode simply means there's no single most common value — this is actually common in continuous numerical data where repetition is unlikely.",
      },
      {
        question: "How does adding an outlier affect mean vs median?",
        answer: "Adding an extreme outlier can dramatically shift the mean but barely affects the median. For example, in {2, 3, 4, 5, 6} the mean is 4. Adding 1000 makes it {2, 3, 4, 5, 6, 1000} with a mean of 170 — far from where most data sits. But the median only shifts from 4 to (4+5)/2 = 4.5. This resilience makes median the preferred measure when outliers are expected, such as in income or housing price distributions.",
      },
      {
        question: "What is the relationship between mean, median, and skewness?",
        answer: "The relationship between mean and median reveals the shape of a distribution. If mean > median, the distribution is right-skewed (positively skewed) with a long tail toward higher values — common in income data. If mean < median, it's left-skewed (negatively skewed) with a long tail toward lower values. If mean ≈ median, the distribution is roughly symmetric. In a perfectly symmetric bell curve (normal distribution), mean, median, and mode are all equal.",
      },
      {
        question: "Can the mean, median, and mode all be different numbers?",
        answer: "Yes, and this is common in real data. For example, in the set {1, 1, 2, 3, 10}: mode = 1 (appears twice), median = 2 (middle value), and mean = 17/5 = 3.4. The large outlier (10) pulls the mean up significantly, while the repeated small value (1) anchors the mode at the lower end. This is why statisticians report multiple measures of central tendency — each tells a different story about the data's distribution.",
      },
    ],
    relatedCalculators: ["average", "standard-deviation", "z-score"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "z-score",
    slug: "z-score-calculator",
    category: "Math",
    categorySlug: "math",
    title: "Z-Score Calculator",
    shortDescription: "Calculate the z-score (standard score) to see how many standard deviations a value is from the mean.",
    seoTitle: "Z-Score Calculator — Standard Score & Percentile Tool",
    metaDescription: "Calculate the z-score of any value to find how many standard deviations it is from the mean. Includes percentile interpretation. Free online stats tool.",
    primaryKeyword: "z-score calculator",
    secondaryKeywords: ["standard score calculator", "z score formula", "percentile calculator", "normal distribution calculator"],
    fields: [
      {
        id: "value",
        label: "Value (x)",
        type: "number",
        placeholder: "e.g. 85",
        required: true,
      },
      {
        id: "mean",
        label: "Mean (μ)",
        type: "number",
        placeholder: "e.g. 70",
        required: true,
      },
      {
        id: "stdDev",
        label: "Standard Deviation (σ)",
        type: "number",
        placeholder: "e.g. 10",
        required: true,
      },
    ],
    results: [
      { id: "zScore", label: "Z-Score", format: "number", decimals: 4, isPrimary: true },
      { id: "deviation", label: "Deviation from Mean", format: "number", decimals: 4, isPrimary: false },
    ],
    formula: "z = (x − μ) / σ",
    formulaExplanation: "Subtracting the mean μ from the value x shifts the center of the data to zero, so the result tells you the raw distance above or below average. Dividing by the standard deviation σ rescales that distance into standard-deviation units, which lets you compare values from different datasets on one common scale. A positive z-score sits above the mean, a negative one below, and zero equals the mean exactly.",
    formulaSource: "NIST/SEMATECH e-Handbook of Statistical Methods",
    sourceUrl: "https://www.itl.nist.gov/div898/handbook/eda/section3/eda364.htm",
    explanation: "The z-score, also called the standard score, is a fundamental tool in statistics for comparing values from different distributions or understanding where a value falls relative to a group.\n\nA z-score tells you exactly how many standard deviations above or below the mean a particular value is. A z-score of +2 means the value is 2 standard deviations above the mean; a z-score of −1.5 means it's 1.5 standard deviations below the mean.\n\nZ-scores enable comparison across different scales. For example, if a student scored 85 on a math test (mean 70, SD 10) and 72 on an English test (mean 65, SD 5), their math z-score is +1.5 and English z-score is +1.4 — so they performed slightly better in math relative to their peers, even though the raw scores differ.\n\nUsing the standard normal distribution table (Z-table), z-scores also map to percentile ranks. A z-score of +1.96 corresponds roughly to the 97.5th percentile. In many fields — medicine, education, finance — z-scores are used to identify outliers, normalize data, and build statistical tests. Because the calculation strips away the original units, a z-score places any measurement on one common scale, which is exactly what makes standardized comparison across different tests and datasets possible.",
    example: {
      inputs: { value: "85", mean: "70", stdDev: "10" },
      explanation: "A test score of 85 with a class mean of 70 and standard deviation of 10 gives z = (85 − 70) / 10 = 1.5. This means the score is 1.5 standard deviations above average, placing it roughly at the 93rd percentile.",
    },
    faqs: [
      {
        question: "What is a good or bad z-score?",
        answer: "There's no universally 'good' or 'bad' z-score — it depends entirely on context. In education, a high positive z-score means scoring above average, which is typically desirable. In quality control, z-scores far from 0 (either positive or negative) might indicate defects. In medical testing, z-scores far from 0 often flag abnormal results. Generally, z-scores between −2 and +2 include about 95% of values in a normal distribution, so anything beyond ±2 is considered unusual.",
      },
      {
        question: "How do I convert a z-score to a percentile?",
        answer: "Z-scores map to percentiles through the standard normal distribution. A z-score of 0 is at the 50th percentile (exactly average). A z-score of +1 is approximately the 84th percentile. A z-score of +2 is about the 97.7th percentile. A z-score of −1 is approximately the 16th percentile. For precise conversions, you'd use a standard normal distribution table (Z-table) or a statistical calculator. The general pattern: higher z-score = higher percentile rank.",
      },
      {
        question: "What does a negative z-score mean?",
        answer: "A negative z-score means the value is below the mean. For example, a z-score of −1.5 means the value is 1.5 standard deviations below average. Whether this is concerning depends on context: a body temperature z-score of −2 might indicate hypothermia, while a z-score of −0.5 on a test just means slightly below average. The magnitude (absolute value) tells you how far from average; the sign tells you the direction (above or below).",
      },
      {
        question: "Can z-scores be used with any data distribution?",
        answer: "Z-scores can be calculated for any numerical data, but their percentile interpretations only apply precisely when the data follows a normal (bell curve) distribution. For heavily skewed distributions or those with multiple peaks, a z-score of +2 may not correspond to the 97.7th percentile. In those cases, z-scores still measure distance from the mean in standard deviation units, which is useful for comparison and outlier detection — but interpret percentile mappings with caution.",
      },
      {
        question: "How are z-scores used in real-world applications?",
        answer: "Z-scores are used across many fields. In medicine, bone density z-scores compare a patient's density to age-matched peers, with z-scores below −2 indicating clinical concern. In finance, z-scores (Altman Z-score) help predict corporate bankruptcy risk. In education, standardized tests are often reported as z-scores or derived scores. In manufacturing, z-scores measure process capability (how many standard deviations between the mean and specification limits). In machine learning, z-score normalization (standardization) scales features to have mean 0 and standard deviation 1.",
      },
    ],
    relatedCalculators: ["standard-deviation", "mean-median-mode", "probability"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "combinations",
    slug: "combinations-calculator",
    category: "Math",
    categorySlug: "math",
    title: "Combinations Calculator (nCr)",
    shortDescription: "Calculate the number of ways to choose r items from a set of n items, where order doesn't matter.",
    seoTitle: "Combinations Calculator (nCr) — Free Combinatorics Tool",
    metaDescription: "Calculate combinations nCr — the number of ways to choose r items from n without regard to order. Free online calculator with formula and examples.",
    primaryKeyword: "combinations calculator",
    secondaryKeywords: ["nCr calculator", "combinatorics calculator", "choose function", "binomial coefficient"],
    fields: [
      {
        id: "n",
        label: "Total Items (n)",
        type: "number",
        placeholder: "e.g. 10",
        min: 0,
        required: true,
      },
      {
        id: "r",
        label: "Items to Choose (r)",
        type: "number",
        placeholder: "e.g. 3",
        min: 0,
        required: true,
      },
    ],
    results: [
      { id: "combinations", label: "Combinations C(n,r)", format: "number", decimals: 0, isPrimary: true },
      { id: "permutations", label: "Permutations P(n,r)", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "C(n, r) = n! / (r! × (n − r)!)",
    formulaExplanation: "The n! in the numerator counts every ordered arrangement of all items. Because a combination ignores order, you divide by r! to erase the different orderings of the r chosen items, and by (n−r)! to erase the orderings of the items left behind. What remains is the count of distinct groups. Permutations skip the r! step, since there order still matters, which is why they always exceed combinations.",
    formulaSource: "Concrete Mathematics, Graham, Knuth & Patashnik",
    explanation: "Combinations answer the question: 'In how many ways can I choose r items from a group of n, if the order I pick them doesn't matter?' This is written as C(n, r), nCr, or the binomial coefficient (n choose r).\n\nThe key distinction is between combinations and permutations. If you're choosing 3 people from a group of 10 for a committee (where it doesn't matter who is first, second, or third), use combinations: C(10, 3) = 120. But if you're assigning 3 people to the roles of President, VP, and Treasurer (where order matters), use permutations: P(10, 3) = 720.\n\nCombinations appear everywhere in probability, statistics, and everyday life. Lottery odds are calculated using combinations (choosing 6 numbers from 49). In genetics, combinations count the number of possible gene combinations. In card games, combinations determine the number of possible hands.\n\nThe formula uses factorials (n! = n × (n−1) × (n−2) × ... × 1). For large values, the numbers grow extremely quickly — C(50, 25) is over 126 trillion, which is why lotteries are so hard to win. Because order is ignored, a combinations count always comes out smaller than the matching permutation count, and that gap widens sharply as r grows.",
    example: {
      inputs: { n: "10", r: "3" },
      explanation: "Choosing 3 players from a squad of 10 for a mini-game: C(10, 3) = 10! / (3! × 7!) = (10 × 9 × 8) / (3 × 2 × 1) = 720 / 6 = 120 ways.",
    },
    faqs: [
      {
        question: "What is the difference between combinations and permutations?",
        answer: "The key difference is whether order matters. Combinations are used when the selection itself is what counts, regardless of the order items are arranged. Permutations are used when the order or arrangement of selected items matters. For example, choosing 3 flavors from 10 for a sampler plate is a combination (the plate is the same regardless of selection order). Arranging those 3 flavors in order from favorite to least favorite is a permutation. Permutations always equal or exceed combinations for the same n and r.",
      },
      {
        question: "What does C(n, 0) and C(n, n) equal?",
        answer: "C(n, 0) always equals 1 — there is exactly one way to choose nothing from any set. Similarly, C(n, n) always equals 1 — there is exactly one way to choose everything. These are important edge cases in combinatorics. C(n, 1) = n, because there are n ways to choose a single item from n items. These base cases are fundamental to Pascal's Triangle, where each number is the sum of the two numbers above it.",
      },
      {
        question: "How do combinations relate to Pascal's Triangle?",
        answer: "Pascal's Triangle is a direct representation of combinations. Each entry in the triangle at row n, position r equals C(n, r). For example, row 4 is: 1, 4, 6, 4, 1 — which are C(4,0)=1, C(4,1)=4, C(4,2)=6, C(4,3)=4, C(4,4)=1. Pascal's Triangle reveals the symmetry of combinations: C(n, r) = C(n, n−r). This symmetry makes sense intuitively: choosing r items to include is equivalent to choosing n−r items to exclude.",
      },
      {
        question: "What is the binomial coefficient and how does it relate to combinations?",
        answer: "The binomial coefficient is just another name for C(n, r), written as (n choose r). It's called 'binomial' because it appears in the Binomial Theorem: (a + b)^n expands into a sum of terms, each with a binomial coefficient. For example, (a + b)^3 = C(3,0)a³ + C(3,1)a²b + C(3,2)ab² + C(3,3)b³ = a³ + 3a²b + 3ab² + b³. These coefficients (1, 3, 3, 1) match the third row of Pascal's Triangle.",
      },
      {
        question: "How do I calculate combinations when n and r are very large?",
        answer: "Standard factorial calculations become impractical for large values because the numbers grow astronomically fast (100! has 158 digits). Practical approaches include: canceling common factors before multiplying (C(100, 3) = (100 × 99 × 98) / (3 × 2 × 1) rather than computing 100! fully), using logarithms of factorials for computation, or using specialized big-integer libraries. Many statistical software packages handle large combinations precisely. For approximate values, Stirling's approximation can estimate factorials: n! ≈ √(2πn)(n/e)^n.",
      },
    ],
    relatedCalculators: ["probability", "factorial", "percentage"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "probability",
    slug: "probability-calculator",
    category: "Math",
    categorySlug: "math",
    title: "Probability Calculator",
    shortDescription: "Calculate the probability of an event occurring given favorable and total outcomes.",
    seoTitle: "Probability Calculator — Fraction, Decimal & Percentage",
    metaDescription: "Calculate probability as a fraction, decimal, and percentage. Enter favorable outcomes and total outcomes for instant results. Free online probability calculator.",
    primaryKeyword: "probability calculator",
    secondaryKeywords: ["chance calculator", "odds calculator", "likelihood calculator", "event probability"],
    fields: [
      {
        id: "favorable",
        label: "Favorable Outcomes",
        type: "number",
        placeholder: "e.g. 3",
        min: 0,
        required: true,
      },
      {
        id: "total",
        label: "Total Outcomes",
        type: "number",
        placeholder: "e.g. 10",
        min: 1,
        required: true,
      },
    ],
    results: [
      { id: "probability", label: "Probability", format: "number", decimals: 6, isPrimary: true },
      { id: "percentage", label: "Percentage", format: "percentage", decimals: 2, isPrimary: false },
      { id: "complement", label: "Probability of NOT occurring", format: "number", decimals: 6, isPrimary: false },
    ],
    formula: "P(E) = Favorable Outcomes / Total Outcomes",
    formulaExplanation: "Classical probability assumes every outcome is equally likely, so the chance of an event is simply the share of outcomes that count as favorable. Dividing favorable outcomes by the total forces the answer between 0 and 1, because you can never have more favorable cases than total cases. The complement, 1 − P(E), works because every trial either produces the event or does not, so both possibilities must sum to one.",
    formulaSource: "Probability Theory, Kolmogorov axioms",
    explanation: "Probability quantifies the likelihood that a specific event will occur. It ranges from 0 (the event will never happen) to 1 (the event will definitely happen), and is often expressed as a percentage (0% to 100%).\n\nThe classical definition of probability — often called 'equally likely outcomes' — applies when every possible outcome has the same chance of occurring. For example, rolling a fair die has 6 equally likely outcomes. The probability of rolling a 4 is 1/6 ≈ 0.167 or 16.7%.\n\nProbability underpins virtually every field: actuaries use it to set insurance premiums, doctors use it to interpret diagnostic test accuracy, gamblers use it to assess bets, weather forecasters express predictions as probabilities, and financial analysts use it to model market risk.\n\nBeyond the basic formula, more complex probability calculations involve independent events (P(A and B) = P(A) × P(B)), mutually exclusive events (P(A or B) = P(A) + P(B)), and conditional probability (P(A|B) = P(A and B) / P(B)). The fundamental single-event case shown here is the starting point. Mastering these probability basics is the foundation for everything from insurance pricing to game strategy, and it is the first step before tackling compound or conditional problems.",
    example: {
      inputs: { favorable: "3", total: "52" },
      explanation: "Drawing a King from a standard 52-card deck: there are 4 Kings but we want any specific suit, say the King of Hearts: probability = 1/52 ≈ 0.0192 or 1.92%. Drawing any King: 4 favorable / 52 total = 0.0769 or 7.69%.",
    },
    faqs: [
      {
        question: "What is the difference between probability and odds?",
        answer: "Probability and odds are related but different expressions of likelihood. Probability = favorable / total, ranging from 0 to 1. Odds = favorable / unfavorable (not total). For example, if you have 3 favorable outcomes out of 10 total, probability = 3/10 = 0.3, but odds = 3/7 ≈ 0.429 (or '3 to 7'). When odds are quoted 'for' an event, a higher number is better; when odds are quoted 'against,' a higher number means less likely. Sports betting uses odds; scientific and statistical work typically uses probability.",
      },
      {
        question: "What does a probability of 0 or 1 mean?",
        answer: "A probability of exactly 0 means the event is impossible — it cannot occur under any circumstances. For example, rolling a 7 on a standard 6-sided die has probability 0. A probability of exactly 1 means the event is certain — it will definitely occur. For example, rolling a number between 1 and 6 on a standard die has probability 1. In practice, few real-world events have probability exactly 0 or 1; most fall somewhere in between, expressing degrees of uncertainty.",
      },
      {
        question: "How do I calculate the probability of multiple events?",
        answer: "For independent events (one doesn't affect the other), use multiplication: P(A and B) = P(A) × P(B). For example, flipping two heads in a row: (1/2) × (1/2) = 1/4. For mutually exclusive events (both can't happen simultaneously), use addition: P(A or B) = P(A) + P(B). For non-exclusive events, use: P(A or B) = P(A) + P(B) − P(A and B). The complement rule P(not A) = 1 − P(A) is useful for calculating 'at least one' probabilities.",
      },
      {
        question: "What is conditional probability?",
        answer: "Conditional probability is the probability of an event given that another event has already occurred, written P(A|B) = 'probability of A given B.' It's calculated as P(A|B) = P(A and B) / P(B). For example, the probability of drawing a King given you already drew a red card: P(King|Red) = P(King and Red) / P(Red) = (2/52) / (26/52) = 2/26 ≈ 7.7%. Conditional probability is the foundation of Bayes' Theorem, which is used in medical diagnostics, spam filtering, and AI.",
      },
      {
        question: "Why doesn't probability tell me what will actually happen?",
        answer: "Probability describes long-run frequency and uncertainty, not individual outcomes. Even with a 99% probability, the remaining 1% can occur on any single trial. This is a fundamental feature, not a flaw — it reflects the inherent randomness in the universe. The Law of Large Numbers guarantees that as you repeat an experiment many times, the observed frequency approaches the theoretical probability. But in the short run, any outcome is possible regardless of its probability. This is why 'low probability' events still happen regularly in practice.",
      },
    ],
    relatedCalculators: ["combinations", "factorial", "percentage"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "factorial",
    slug: "factorial-calculator",
    category: "Math",
    categorySlug: "math",
    title: "Factorial Calculator (n!)",
    shortDescription: "Calculate the factorial of any non-negative integer. See results for large values too.",
    seoTitle: "Factorial Calculator — n! Instant Results Online",
    metaDescription: "Calculate n factorial (n!) instantly. Shows the factorial value and step-by-step formula. Handles large numbers. Free online math calculator.",
    primaryKeyword: "factorial calculator",
    secondaryKeywords: ["n factorial", "n! calculator", "combinatorics factorial", "permutations calculator"],
    fields: [
      {
        id: "n",
        label: "n",
        type: "number",
        placeholder: "e.g. 10",
        min: 0,
        max: 170,
        required: true,
        helpText: "Enter a non-negative integer (0–170). Note: 170! is the largest factorial JavaScript can represent.",
      },
    ],
    results: [
      { id: "result", label: "n!", format: "number", decimals: 0, isPrimary: true },
    ],
    formula: "n! = n × (n−1) × (n−2) × ... × 2 × 1; 0! = 1",
    formulaExplanation: "A factorial counts how many ways n distinct items can be arranged in order: the first slot has n choices, the next n−1, and so on down to the last, so the choices multiply together. That is why the definition is a running product from n down to 1. Setting 0! = 1 keeps the empty-product rule consistent and lets combination and permutation formulas stay correct at their edge cases.",
    formulaSource: "Standard mathematical definition",
    explanation: "The factorial function, denoted n!, multiplies a positive integer n by every positive integer smaller than itself down to 1. For example, 5! = 5 × 4 × 3 × 2 × 1 = 120.\n\nBy mathematical convention, 0! = 1. This might seem counterintuitive, but it follows from the empty product rule (a product of no numbers equals the multiplicative identity, 1) and ensures that formulas for combinations and permutations work correctly for edge cases.\n\nFactorials grow astonishingly fast — 10! is already 3,628,800, and 20! exceeds 2.4 quintillion. This explosive growth is directly responsible for how difficult it becomes to win lotteries or brute-force cryptographic keys. The number 52! (possible shuffles of a standard deck of cards) is approximately 8 × 10^67 — a number larger than the number of atoms in the observable universe, meaning every shuffle in history has almost certainly been unique.\n\nFactorials appear everywhere in mathematics: in combinatorics (counting arrangements), in Taylor series expansions (sin x = x − x³/3! + x⁵/5! − ...), in the Gamma function (which extends factorials to non-integers), and in statistics. This mix of a one-line definition and explosive growth is what makes the factorial one of the first big ideas students meet in combinatorics and one of the most useful tools for counting arrangements.",
    example: {
      inputs: { n: "8" },
      explanation: "8! = 8 × 7 × 6 × 5 × 4 × 3 × 2 × 1 = 40,320. This is also the number of ways to arrange 8 books on a shelf in a different order each time.",
    },
    faqs: [
      {
        question: "Why does 0! equal 1?",
        answer: "Zero factorial equals 1 by definition, and there are several ways to understand why this makes sense. Mathematically, it follows the 'empty product' convention: a product containing no factors equals 1 (just as a sum of no terms equals 0). Practically, it ensures the combination formula C(n, 0) = 1 works correctly — there is exactly one way to choose nothing from a set. It also satisfies the recurrence relation n! = n × (n−1)!: plugging in n=1 gives 1! = 1 × 0!, so 0! must be 1.",
      },
      {
        question: "What is the largest factorial a calculator can compute?",
        answer: "This depends on the numerical precision of the calculator. Standard double-precision floating-point numbers (used in most computing, including JavaScript) can represent factorials up to 170! (≈7.26 × 10^306) before exceeding the maximum representable value and becoming 'Infinity.' For exact integer results of larger factorials, you need big-integer arithmetic. Python's built-in integers handle arbitrarily large factorials. 171! ≈ 1.24 × 10^309, which exceeds the IEEE 754 double-precision maximum of about 1.80 × 10^308.",
      },
      {
        question: "How are factorials used in combinations and permutations?",
        answer: "Factorials are the building blocks of counting arrangements. Permutations (ordered arrangements) of r items from n: P(n, r) = n! / (n−r)!. Combinations (unordered selections) of r items from n: C(n, r) = n! / (r! × (n−r)!). For example, arranging 3 books from a shelf of 5 in different orders: P(5,3) = 5!/2! = 60. Choosing any 3 books from 5 regardless of order: C(5,3) = 5!/(3!×2!) = 10. Factorials also appear in probability distributions like the Poisson distribution.",
      },
      {
        question: "What is the Gamma function and how does it relate to factorial?",
        answer: "The Gamma function Γ(n) is an extension of the factorial function to non-integer and complex numbers. For positive integers, Γ(n) = (n−1)!. So Γ(5) = 4! = 24. The Gamma function is defined through an integral formula that works for all positive real numbers and complex numbers with a positive real part. This allows us to compute 'factorials' of non-integers: for example, Γ(1.5) = 0.5! × 2 ≈ 0.886. The Gamma function appears throughout statistics, physics, and engineering.",
      },
      {
        question: "Why do factorials grow so incredibly fast?",
        answer: "Factorials grow super-exponentially because each additional factor is larger than the previous one. Exponential growth (like 2^n) multiplies by the same factor each time. Factorial growth multiplies by an ever-increasing factor. By Stirling's approximation, n! ≈ √(2πn) × (n/e)^n, which grows much faster than any exponential function. This rapid growth is why the number of possible arrangements of large sets is astronomically large — 52 playing cards can be shuffled into more unique arrangements than there are atoms in the observable universe.",
      },
    ],
    relatedCalculators: ["combinations", "probability", "exponent"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "exponent",
    slug: "exponent-calculator",
    category: "Math",
    categorySlug: "math",
    title: "Exponent Calculator",
    shortDescription: "Calculate base raised to a power (bⁿ). Handles any real exponent including fractions and negatives.",
    seoTitle: "Exponent Calculator — bⁿ Power Calculator Free Online",
    metaDescription: "Calculate any base raised to any power. Handles negative exponents, fractional powers, and large numbers. Free online exponent calculator.",
    primaryKeyword: "exponent calculator",
    secondaryKeywords: ["power calculator", "base exponent calculator", "b to the power of n", "scientific notation calculator"],
    fields: [
      {
        id: "base",
        label: "Base (b)",
        type: "number",
        placeholder: "e.g. 2",
        required: true,
      },
      {
        id: "exponent",
        label: "Exponent (n)",
        type: "number",
        placeholder: "e.g. 10",
        required: true,
      },
    ],
    results: [
      { id: "result", label: "Result (bⁿ)", format: "number", decimals: 6, isPrimary: true },
      { id: "inverse", label: "Inverse (b⁻ⁿ)", format: "number", decimals: 6, isPrimary: false },
    ],
    formula: "bⁿ = b × b × b × ... (n times); b⁻ⁿ = 1/bⁿ; b^(1/n) = ⁿ√b",
    formulaExplanation: "An exponent records repeated multiplication, so bⁿ simply means b used as a factor n times. The rules follow from that meaning: adding exponents combines repeated factors, and a zero exponent leaves an empty product of 1. A negative exponent inverts the result because it undoes multiplication, giving 1/bⁿ. A fractional exponent asks which number, multiplied by itself the denominator's number of times, rebuilds the base — that is a root.",
    formulaSource: "Standard mathematical definition",
    explanation: "Exponentiation is a mathematical operation where a base number is multiplied by itself a specified number of times. It is the third core operation built on repetition — addition repeats counting, multiplication repeats addition, and an exponent repeats multiplication. The expression b^n (read 'b to the power of n' or 'b raised to the nth power') means: multiply b by itself n times.\n\nExponents follow important rules that make calculations easier: b^m × b^n = b^(m+n), (b^m)^n = b^(m×n), b^0 = 1 (for any non-zero b), b^(-n) = 1/b^n, and b^(1/n) = the nth root of b.\n\nFractional exponents are particularly powerful: 4^(0.5) = √4 = 2, 8^(1/3) = ∛8 = 2, 32^(0.2) = ⁵√32 = 2. This connects exponentiation to roots.\n\nExponents also tame very large and very small numbers through scientific notation, where a value is written as a number times a power of 10. Writing 300,000,000 as 3 × 10^8, or 0.0000004 as 4 × 10^(−7), keeps figures compact and readable across science and engineering.\n\nExponential growth appears everywhere in nature and technology: compound interest, population growth, radioactive decay, and Moore's Law (the doubling of transistors roughly every 18 months). A firm grasp of exponents is essential for science, engineering, finance, and computer science.",
    example: {
      inputs: { base: "2", exponent: "10" },
      explanation: "2^10 = 2 × 2 × 2 × 2 × 2 × 2 × 2 × 2 × 2 × 2 = 1,024. This is why 1 kilobyte = 2^10 = 1,024 bytes in binary computing.",
    },
    faqs: [
      {
        question: "What is anything to the power of 0?",
        answer: "Any non-zero number raised to the power of 0 equals 1. This follows from the exponent rule b^n / b^n = b^(n−n) = b^0, and any number divided by itself is 1. So b^0 = 1 for any b ≠ 0. The expression 0^0 is mathematically indeterminate (it leads to conflicting values depending on how you approach it), but in many combinatorial contexts, it's defined as 1 for convenience. This rule is essential for polynomials and the binomial theorem.",
      },
      {
        question: "How do negative exponents work?",
        answer: "A negative exponent means take the reciprocal of the positive exponent result: b^(-n) = 1/b^n. For example, 2^(-3) = 1/2^3 = 1/8 = 0.125. Negative exponents are not negative numbers — they represent fractions less than 1 (for bases greater than 1). This rule is fundamental in scientific notation: 10^(-3) = 0.001 (one thousandth). Negative exponents also appear in physics for units like m/s² = m × s^(-2).",
      },
      {
        question: "What are fractional exponents?",
        answer: "Fractional exponents represent roots. The rule is b^(1/n) = the nth root of b, and b^(m/n) = (nth root of b)^m = nth root of b^m. For example: 4^(1/2) = √4 = 2; 8^(1/3) = ∛8 = 2; 16^(3/4) = (fourth root of 16)^3 = 2^3 = 8. This connects the exponent operation to root extraction and explains why square roots, cube roots, etc. are just special cases of exponentiation with fractional powers.",
      },
      {
        question: "What is the difference between exponential growth and linear growth?",
        answer: "Linear growth adds the same amount each time (e.g., saving $100 per month: $100, $200, $300...). Exponential growth multiplies by the same factor each time (e.g., 10% compound interest: $1,000, $1,100, $1,210, $1,331...). In the short term, linear and exponential growth may look similar. Over time, exponential growth becomes enormously larger — this is why compound interest is so powerful, and why viral diseases spread so rapidly. Mathematically, any exponential eventually outpaces any polynomial (including linear).",
      },
      {
        question: "What happens when you raise a negative number to a fractional exponent?",
        answer: "Raising a negative number to a fractional exponent with an even denominator produces a complex (imaginary) number in standard math, since you'd need to take an even root of a negative number. For example, (-4)^(1/2) = √(-4) = 2i (where i is the imaginary unit). For odd denominators, the result is real: (-8)^(1/3) = ∛(-8) = -2. Most calculators, including ours, return NaN (not a number) for cases that would yield complex results, since complex number support requires a different representation.",
      },
    ],
    relatedCalculators: ["square-root", "logarithm", "scientific-calculator"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "logarithm",
    slug: "logarithm-calculator",
    category: "Math",
    categorySlug: "math",
    title: "Logarithm Calculator",
    shortDescription: "Calculate the logarithm of any number to any base, including natural log (ln) and log base 10.",
    seoTitle: "Logarithm Calculator — log, ln, log₂ Free Online Tool",
    metaDescription: "Calculate logarithms to any base — common log (base 10), natural log (base e), binary log (base 2), or custom base. Free online logarithm calculator.",
    primaryKeyword: "logarithm calculator",
    secondaryKeywords: ["log calculator", "ln calculator", "natural log calculator", "log base 10 calculator", "log base 2"],
    fields: [
      {
        id: "value",
        label: "Value (x)",
        type: "number",
        placeholder: "e.g. 100",
        min: 0,
        required: true,
      },
      {
        id: "base",
        label: "Base",
        type: "number",
        placeholder: "e.g. 10 (use 2.71828 for natural log)",
        defaultValue: 10,
        required: true,
        helpText: "Use 10 for log₁₀, 2.71828 (e) for ln, or 2 for log₂",
      },
    ],
    results: [
      { id: "result", label: "log_b(x)", format: "number", decimals: 6, isPrimary: true },
    ],
    formula: "log_b(x) = ln(x) / ln(b); ln(x) = log_e(x)",
    formulaExplanation: "A logarithm reverses exponentiation, so log_b(x) is the exponent that turns the base b into x — that is why b raised to log_b(x) returns x. Calculators rarely store a table for every base, so the change-of-base formula rewrites the logarithm as a ratio of two logs in a base they do know, usually natural log or base 10. Dividing ln(x) by ln(b) cancels the shared base and leaves the answer.",
    formulaSource: "Standard mathematical definition",
    explanation: "The logarithm is the inverse operation of exponentiation. If 10^3 = 1000, then log₁₀(1000) = 3. If 2^8 = 256, then log₂(256) = 8. Logarithms answer the question: 'What exponent do I need to raise base b to, in order to get x?'\n\nThree logarithms are especially common. Log base 10 (common log, log₁₀ or just 'log') is used in pH scales, the Richter scale for earthquakes, and decibels for sound. Natural log (ln, log base e where e ≈ 2.718) appears throughout calculus, physics, and the mathematics of growth and decay — interest, population, radioactive decay all involve natural logs. Log base 2 (log₂) is fundamental to information theory and computer science — binary systems, data compression, and algorithm complexity (O(log n)) all use log₂.\n\nThe change-of-base formula (log_b(x) = ln(x)/ln(b)) allows any logarithm to be computed using the natural log or common log, which is how calculators and computers implement it.\n\nBefore electronic calculators, logarithms were the fastest way to multiply large numbers by hand: printed log tables and the slide rule turned multiplication into simple addition. That same inverse relationship with exponents is why the logarithm remains the natural tool for solving any equation where the unknown sits in the exponent, from carbon dating to compound-interest problems.",
    example: {
      inputs: { value: "1000", base: "10" },
      explanation: "log₁₀(1000) = 3 because 10³ = 1,000. The common logarithm of 1,000 is 3. This is why the pH scale spans from 0 to 14 with each step representing a 10× difference in acidity.",
    },
    faqs: [
      {
        question: "What is the natural logarithm (ln) and why is it special?",
        answer: "The natural logarithm uses the mathematical constant e (≈ 2.71828) as its base. What makes e special is that it's the unique number where the function e^x has a derivative equal to itself — it models continuous growth and decay perfectly. The natural log appears in compound interest (when compounded continuously), probability distributions (normal distribution, Poisson), entropy in information theory, and countless physics equations. While log base 10 is convenient for human calculation, ln is the 'natural' choice mathematically and scientifically.",
      },
      {
        question: "Why does log of a negative number not exist (in real numbers)?",
        answer: "No real number exponent can make a positive base produce a negative result. Since b^x is always positive for positive b (e.g., 10^x is always positive), there's no real x such that b^x = negative number. Therefore, the logarithm of a negative number is undefined in real numbers. In complex number mathematics, logarithms of negative numbers can be defined (using complex exponents), but for everyday calculations, log(x) requires x > 0. Attempting log(0) is also undefined — it would require an exponent of −∞.",
      },
      {
        question: "How do logarithmic scales work in the real world?",
        answer: "Logarithmic scales compress large ranges into manageable numbers. The Richter scale: each step is 10× more energy — a magnitude 7 earthquake is 10× stronger than magnitude 6, and 1,000× stronger than magnitude 4. Sound decibels: every 10 dB increase is 10× more sound intensity. pH: each unit represents a 10× change in hydrogen ion concentration; pH 4 is 100× more acidic than pH 6. These scales allow us to compare quantities spanning many orders of magnitude on a single, human-readable scale.",
      },
      {
        question: "What are the key logarithm rules I should know?",
        answer: "The four fundamental logarithm rules are: Product rule — log(a × b) = log(a) + log(b); Quotient rule — log(a/b) = log(a) − log(b); Power rule — log(a^n) = n × log(a); Change of base — log_b(x) = log_a(x) / log_a(b). These rules were historically important because they turned multiplication into addition (used in slide rules and log tables). Today, they're essential for solving exponential equations: if 2^x = 50, then x = log₂(50) = log(50)/log(2) ≈ 5.64.",
      },
      {
        question: "What is log base 2 used for in computing?",
        answer: "Log base 2 (log₂) is fundamental in computer science and information theory. Binary counting uses base 2, so log₂(n) tells you how many bits are needed to represent n states: log₂(256) = 8 bits (1 byte), log₂(65,536) = 16 bits. Algorithm complexity often grows as O(log n) — binary search, balanced binary trees, and divide-and-conquer algorithms all have log₂ complexity. In information theory, log₂ measures information in bits: the probability p of an event carries −log₂(p) bits of information.",
      },
    ],
    relatedCalculators: ["exponent", "scientific-calculator", "square-root"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
  {
    id: "modulo",
    slug: "modulo-calculator",
    category: "Math",
    categorySlug: "math",
    title: "Modulo Calculator",
    shortDescription: "Calculate the remainder of a division operation (a mod b) with the quotient.",
    seoTitle: "Modulo Calculator — Remainder of Division (a mod b)",
    metaDescription: "Calculate the modulo (remainder) of any division. Shows quotient, remainder, and full division result. Essential for programming and number theory.",
    primaryKeyword: "modulo calculator",
    secondaryKeywords: ["remainder calculator", "mod calculator", "modulus calculator", "division remainder"],
    fields: [
      {
        id: "dividend",
        label: "Dividend (a)",
        type: "number",
        placeholder: "e.g. 17",
        required: true,
      },
      {
        id: "divisor",
        label: "Divisor (b)",
        type: "number",
        placeholder: "e.g. 5",
        required: true,
      },
    ],
    results: [
      { id: "remainder", label: "Remainder (a mod b)", format: "number", decimals: 0, isPrimary: true },
      { id: "quotient", label: "Quotient", format: "number", decimals: 0, isPrimary: false },
      { id: "result", label: "Division Result", format: "number", decimals: 6, isPrimary: false },
    ],
    formula: "a mod b = a − b × ⌊a/b⌋; Quotient = ⌊a/b⌋",
    formulaExplanation: "Division splits a into a whole-number quotient and a leftover part. The floor of a/b is how many complete times b fits inside a, and multiplying that quotient back by b and subtracting it from a leaves exactly what could not be evenly divided — the remainder. This guarantees the identity a = b × quotient + remainder, with the remainder always smaller in size than the divisor b.",
    formulaSource: "Standard mathematical definition",
    explanation: "The modulo operation (often written as %, mod, or a mod b) returns the remainder when dividing one number by another. For example, 17 mod 5 = 2, because 17 = 5 × 3 + 2 (five goes into 17 three times, with 2 left over).\n\nModulo is one of the most fundamental operations in programming and number theory. In code, it's typically the % operator. It's used constantly in everyday programming: determining if a number is even (n % 2 == 0), wrapping around arrays (index = i % length), clock arithmetic (hours = (current + elapsed) % 12), and color cycling in UIs.\n\nIn mathematics, modular arithmetic (working with remainders) is the foundation of cryptography. The RSA encryption algorithm, which secures most internet communications, is built entirely on modular exponentiation. The last digits of large exponential calculations, determined by mod, create the one-way functions that make encryption secure.\n\nModulo also appears in checksum algorithms (credit card number validation), hash functions, random number generators, and scheduling problems. Whenever a value must wrap within a fixed range — an hour on a clock, a day of the week, a pixel column, or a slot in a hash table — the modulo operation is usually the cleanest way to express that wrap-around in a single step.",
    example: {
      inputs: { dividend: "17", divisor: "5" },
      explanation: "17 ÷ 5 = 3 remainder 2. So 17 mod 5 = 2, and the quotient is 3. Verification: 5 × 3 + 2 = 15 + 2 = 17 ✓",
    },
    faqs: [
      {
        question: "What is modulo used for in programming?",
        answer: "Modulo is one of the most frequently used operations in programming. Common uses include: checking if a number is even or odd (n % 2 == 0 means even); wrapping indices for circular data structures (array[i % length] cycles through an array indefinitely); clock arithmetic (hour = (current_hour + hours_to_add) % 12); generating repeating patterns; implementing hash tables (hash % table_size maps any hash to a valid index); and creating cycles in animations (frame % total_frames). It's also central to cryptographic algorithms.",
      },
      {
        question: "How does modulo work with negative numbers?",
        answer: "Modulo with negative numbers can give different results depending on the programming language or mathematical convention used. In most mathematical contexts, the result has the same sign as the divisor (b). In Python: −7 mod 3 = 2. In C/Java/JavaScript, % gives the remainder with the sign of the dividend: −7 % 3 = −1. Our calculator uses the mathematical floor-based definition. The two are equivalent for positive numbers; for negative numbers, adjust with: if (result < 0) result += b to get the positive modulo.",
      },
      {
        question: "What is modular arithmetic?",
        answer: "Modular arithmetic is a system of integer arithmetic where numbers 'wrap around' upon reaching a certain value (the modulus). On a 12-hour clock, after 12 comes 1 (not 13) — that's mod 12. Days of the week cycle mod 7. Modular arithmetic follows its own algebra: you can add, subtract, and multiply numbers modulo m, and the results stay within 0 to m−1. This system has deep applications in cryptography, computer science, calendaring algorithms, and abstract algebra (group theory and ring theory).",
      },
      {
        question: "What is the difference between modulo and remainder?",
        answer: "For positive numbers, modulo and remainder are the same. The distinction arises with negative numbers. The mathematical modulo operation (used in number theory) always returns a non-negative result in [0, b−1]. The programming remainder (%) typically returns a result with the same sign as the dividend. For example: −7 mod 3 = 2 (mathematical), but −7 % 3 = −1 (C-style remainder). Both are useful; the mathematical modulo is preferred in cryptography and number theory, while the C-style remainder is what most programming languages implement with %.",
      },
      {
        question: "How is modulo used in cryptography?",
        answer: "Modular arithmetic is the mathematical backbone of modern cryptography. RSA encryption uses modular exponentiation: given large primes p and q, their product n = pq creates a 'trapdoor' — it's easy to compute m^e mod n (encrypt), but computationally infeasible to reverse without knowing the private key. The Diffie-Hellman key exchange uses discrete logarithms in modular arithmetic. AES encryption uses operations in a finite field (arithmetic modulo an irreducible polynomial). Without modular arithmetic, public-key cryptography — and therefore secure web browsing, banking, and messaging — would not be possible.",
      },
    ],
    relatedCalculators: ["factorial", "combinations", "percentage"],
    status: "active",
    lastReviewed: "2025-01-01",
  },
];
