import type { CalculatorDefinition } from "../types";

export const realEstateWave3Calculators: CalculatorDefinition[] = [
  {
    id: "cap-rate",
    slug: "cap-rate-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Cap Rate Calculator",
    shortDescription: "Measure a rental property's return from income and price.",
    seoTitle: "Cap Rate Calculator — Net Operating Income and Yield",
    metaDescription: "Free cap rate calculator for rental property. Enter price, rent, vacancy, and expenses to find capitalization rate, net operating income, and gross rent multiplier.",
    primaryKeyword: "cap rate calculator",
    secondaryKeywords: ["capitalization rate calculator", "net operating income calculator", "rental property cap rate"],
    fields: [
      { id: "propertyValue", label: "Property value", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 500000" },
      { id: "annualRent", label: "Annual rental income", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 40000" },
      { id: "vacancyRate", label: "Vacancy rate", type: "number", unit: "%", required: false, span: 1, min: 0, helpText: "Share of the year the unit sits empty." },
      { id: "annualExpenses", label: "Annual operating expenses", type: "number", unit: "$", required: false, span: 1, min: 0, helpText: "Taxes, insurance, maintenance, management." },
    ],
    results: [
      { id: "capRate", label: "Cap rate", format: "percentage", decimals: 2, isPrimary: true },
      { id: "noi", label: "Net operating income", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "grm", label: "Gross rent multiplier", format: "number", decimals: 2, isPrimary: false },
    ],
    formula: "Cap rate = NOI ÷ property value × 100",
    formulaExplanation: "Net operating income is annual rent minus vacancy losses and operating expenses, so it isolates the cash the property throws off before financing. Dividing that income by the purchase price expresses the return as a percentage, letting you compare buildings of very different sizes on equal footing. The gross rent multiplier ignores expenses and simply relates price to rent, offering a rougher but faster screening ratio.",
    explanation: "Capitalization rate, universally shortened to cap rate, is the yardstick investors use to judge how much income a rental property produces relative to its price. A cap rate calculator strips a deal down to its essentials: annual rent, expected vacancy, running costs, and the price you would pay. From those numbers it derives net operating income, the profit left after expenses but before any mortgage, and then divides that figure by the property value to give a clean percentage return.\n\nThe measure matters because it lets you compare a duplex against an apartment block or a property in one city against another without being distracted by loan terms or purchase size. A higher cap rate signals more income per dollar invested, though it often comes paired with higher risk or a weaker location. A lower cap rate usually reflects a prime, stable asset that buyers accept for safety.\n\nThe formula works because dividing recurring income by price normalises every deal into the same yield language, the way a bond quotes a coupon. Alongside cap rate, the gross rent multiplier offers a quick price-to-rent screen. Investors, agents, and lenders lean on a cap rate calculator constantly to filter listings before committing to deeper due diligence.",
    example: { inputs: { propertyValue: 500000, annualRent: 40000, vacancyRate: 5, annualExpenses: 8000 }, explanation: "Effective rent is $40,000 × (1 − 0.05) = $38,000. Subtract $8,000 in expenses for a net operating income of $30,000. Cap rate = $30,000 ÷ $500,000 = 6%, and the gross rent multiplier is $500,000 ÷ $40,000 = 12.5." },
    faqs: [
      {
        question: "What counts as a good cap rate?",
        answer: "There is no single correct number because cap rates trade off return against risk. Many investors treat 5% to 10% as a typical range, with lower figures reflecting prime, stable markets and higher figures compensating for older buildings or weaker locations. Compare any property's cap rate against recent sales of similar assets in the same area, since local demand and interest rates shift the benchmark constantly.",
      },
      {
        question: "Does cap rate include my mortgage payment?",
        answer: "No, and that is deliberate. Cap rate is built on net operating income, which subtracts operating expenses but excludes financing costs like mortgage principal and interest. Leaving debt out lets you compare the property itself, independent of how any particular buyer chooses to fund it. To judge your actual leveraged return you would instead look at cash-on-cash return, which factors in your loan and down payment.",
      },
      {
        question: "Which expenses belong in net operating income?",
        answer: "Include recurring costs of owning and running the property: property taxes, insurance, maintenance and repairs, property management fees, utilities you cover, and reasonable reserves for vacancy. Exclude your mortgage payment, income taxes, and large one-off capital improvements like a new roof. Keeping the expense list consistent from deal to deal is what makes cap rate a fair, apples-to-apples comparison tool across a portfolio.",
      },
      {
        question: "How does the gross rent multiplier differ from cap rate?",
        answer: "The gross rent multiplier divides price by gross annual rent and ignores expenses entirely, so it is a faster but blunter screen. A lower multiplier suggests a cheaper property relative to its rent. Cap rate is more accurate because it accounts for vacancy and operating costs through net operating income. Use the multiplier to sift many listings quickly, then compute cap rate on the finalists.",
      },
      {
        question: "Why do cap rates move when interest rates change?",
        answer: "When borrowing gets more expensive, investors demand higher yields to justify a purchase, so prices soften and cap rates rise. When rates fall, cheap financing pushes buyers to accept lower yields and prices climb, compressing cap rates. This inverse relationship means the same rental income can support very different valuations across the market cycle, which is why current-market comparisons matter more than historical averages.",
      },
    ],
    relatedCalculators: ["loan-to-value-calculator", "property-tax-calculator", "mortgage-refinance-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard real estate formula",
  },
  {
    id: "rent-vs-buy",
    slug: "rent-vs-buy-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Rent vs Buy Calculator",
    shortDescription: "Compare the monthly cost of renting against owning.",
    seoTitle: "Rent vs Buy Calculator — Monthly Cost Comparison",
    metaDescription: "Free rent vs buy calculator. Compare the true monthly cost of owning a home, including mortgage, property tax, and maintenance, against renting to decide faster.",
    primaryKeyword: "rent vs buy calculator",
    secondaryKeywords: ["rent or buy calculator", "buy vs rent home calculator", "cost of owning a home"],
    fields: [
      { id: "homePrice", label: "Home price", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 400000" },
      { id: "downPayment", label: "Down payment", type: "number", unit: "$", required: false, span: 1, min: 0, placeholder: "e.g. 80000" },
      { id: "rate", label: "Mortgage interest rate", type: "number", unit: "%", required: true, span: 1, min: 0, placeholder: "e.g. 6.5" },
      { id: "term", label: "Loan term", type: "number", unit: "years", required: true, span: 1, min: 1, placeholder: "e.g. 30" },
      { id: "propertyTaxRate", label: "Property tax rate", type: "number", unit: "%", required: false, span: 1, min: 0, helpText: "Annual tax as a percent of home price." },
      { id: "monthlyRent", label: "Monthly rent", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 2000" },
    ],
    results: [
      { id: "buyMonthly", label: "Monthly cost to buy", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "rentMonthly", label: "Monthly rent", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "difference", label: "Buy − rent", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Buy monthly = mortgage P&I + property tax + ~1%/yr maintenance",
    formulaExplanation: "The mortgage principal and interest come from the standard amortization formula on the financed amount, spreading repayment evenly across the term. Property tax is estimated as a yearly percentage of the home price divided into monthly instalments, and a maintenance allowance of roughly one percent of value per year covers upkeep. Summing these gives the ongoing monthly cost of ownership, which the tool then subtracts from your rent to reveal the gap.",
    explanation: "Deciding whether to rent or buy is one of the largest financial choices most people face, and the honest answer rarely comes from comparing rent against a mortgage payment alone. A rent vs buy calculator builds a fairer picture by adding the hidden monthly costs of ownership that renters never see: property taxes and ongoing maintenance on top of the loan itself. It then places that total beside your current rent so the real difference is visible.\n\nOwning carries costs that a lease bundles away or shifts to a landlord. Property taxes recur every year, upkeep and repairs typically run around one percent of the home's value annually, and financing spreads the purchase across decades of interest. Renting trades those obligations for a single predictable payment, though it builds no equity in return.\n\nThe comparison works because it converts both paths into a like-for-like monthly figure, letting you see immediately whether buying costs more or less each month than renting today. Numbers alone will not settle the decision, since equity growth, tax treatment, and how long you plan to stay all matter, but seeing the monthly gap clearly is the essential first step buyers and renters alike should take before committing.",
    example: { inputs: { homePrice: 400000, downPayment: 80000, rate: 6.5, term: 30, propertyTaxRate: 1.2, monthlyRent: 2000 }, explanation: "A $320,000 loan at 6.5% over 30 years costs about $2,023 a month in principal and interest. Adding roughly $400 in monthly property tax and $333 in maintenance gives about $2,756 to buy, versus $2,000 to rent — a gap of around $756 a month." },
    faqs: [
      {
        question: "Does buying always beat renting in the long run?",
        answer: "Not always. Buying tends to win when you stay put long enough for appreciation and equity to outweigh transaction costs, often five years or more. If you move sooner, agent fees, closing costs, and early-year interest can leave renting ahead. Local price trends, interest rates, and how the gap between rent and ownership costs is invested all tilt the outcome one way or the other.",
      },
      {
        question: "What costs of owning does the calculator include?",
        answer: "It sums three recurring pieces: mortgage principal and interest on the financed amount, estimated annual property tax spread monthly, and a maintenance allowance of about one percent of the home's value per year. It does not include homeowners insurance, HOA dues, private mortgage insurance, or closing costs, so treat the result as a strong baseline and add those figures for your specific property to sharpen the comparison.",
      },
      {
        question: "Why include maintenance when renters do not pay it?",
        answer: "That is precisely the point. Renters offload repairs and upkeep to their landlord, while owners shoulder them directly. Ignoring maintenance would understate the true cost of owning and make buying look artificially cheap. A common rule of thumb sets annual upkeep near one percent of the home's value, covering everything from a failed water heater to routine servicing, which is why the calculator bakes it into the monthly figure.",
      },
      {
        question: "Should I count the equity I build by buying?",
        answer: "Yes, when making the final call. A portion of every mortgage payment reduces your loan balance, effectively saving money you recover when you sell, and the property may appreciate as well. This calculator compares raw monthly cash cost rather than net wealth, so a buy figure that looks higher can still be the better long-term deal once equity and price growth are considered.",
      },
      {
        question: "How does my down payment change the comparison?",
        answer: "A larger down payment shrinks the financed amount, which lowers the monthly principal and interest and can make buying more competitive with renting on a cash basis. It also ties up more capital upfront that could otherwise be invested elsewhere. The calculator subtracts your down payment from the price to size the loan, so experimenting with different amounts shows how much the monthly cost of ownership shifts.",
      },
    ],
    relatedCalculators: ["down-payment-calculator", "closing-costs-calculator", "property-tax-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "Standard amortization formula",
    sourceUrl: "https://www.consumerfinance.gov/owning-a-home/",
  },
  {
    id: "loan-to-value",
    slug: "loan-to-value-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Loan-to-Value (LTV) Calculator",
    shortDescription: "Find your LTV ratio, equity, and equity percentage.",
    seoTitle: "Loan-to-Value (LTV) Calculator — Ratio and Home Equity",
    metaDescription: "Free loan-to-value calculator. Enter your loan amount and property value to find your LTV ratio, dollar equity, and equity percentage for mortgage and refinance decisions.",
    primaryKeyword: "loan to value calculator",
    secondaryKeywords: ["ltv calculator", "home equity calculator", "ltv ratio calculator"],
    fields: [
      { id: "loanAmount", label: "Loan amount", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 320000" },
      { id: "propertyValue", label: "Property value", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 400000" },
    ],
    results: [
      { id: "ltv", label: "Loan-to-value", format: "percentage", decimals: 2, isPrimary: true },
      { id: "equity", label: "Equity", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "equityPercent", label: "Equity %", format: "percentage", decimals: 2, isPrimary: false },
    ],
    formula: "LTV = loan ÷ value × 100",
    formulaExplanation: "Loan-to-value divides the outstanding loan by the property's value, expressing the borrowed share as a percentage. Because the property secures the debt, this ratio tells a lender how much cushion exists if they ever have to sell after a default. Equity is simply the value the loan does not cover, so equity plus loan always equals the full property value, and the equity percentage is the mirror image of LTV.",
    explanation: "Loan-to-value, almost always written as LTV, is the ratio lenders scrutinise most when deciding whether to approve a mortgage and on what terms. An LTV calculator takes two numbers, the size of your loan and the value of the property securing it, and returns the borrowed percentage along with the equity you hold in both dollars and percent. A lower LTV means you have put more skin in the game and the lender carries less risk.\n\nThe ratio drives real outcomes. Most conventional loans want LTV at or below 80% to avoid private mortgage insurance, and the best interest rates are reserved for borrowers with plenty of equity. Cross above roughly 80% and lenders typically add insurance premiums or decline the application, because a thin equity cushion leaves them exposed if prices fall.\n\nThe calculation works because the property acts as collateral, so the lender needs to know how much of its value is at stake relative to their own resale safety margin. Homebuyers use LTV to see how large a down payment they need, while owners refinancing or tapping a home equity line use it to confirm they qualify. Keeping an eye on your LTV as you repay and as values rise reveals when better borrowing terms open up.",
    example: { inputs: { loanAmount: 320000, propertyValue: 400000 }, explanation: "A $320,000 loan against a $400,000 property gives an LTV of $320,000 ÷ $400,000 = 80%. The remaining $80,000 is your equity, which is 20% of the property's value." },
    faqs: [
      {
        question: "Why does an 80% LTV matter so much?",
        answer: "Eighty percent is the industry threshold for conventional mortgages. At or below it, you generally avoid private mortgage insurance and qualify for the strongest interest rates, because your 20% equity gives the lender a comfortable safety margin. Rise above 80% and lenders usually require mortgage insurance to offset their added risk, increasing your monthly payment until repayment or rising home values bring the ratio back down.",
      },
      {
        question: "How is LTV different from equity?",
        answer: "They are two sides of the same coin. LTV is the percentage of the property's value that you have borrowed, while equity is the portion you actually own. They always add up to 100%, so an 80% LTV means 20% equity. Equity can be expressed in dollars, the value your loan does not cover, or as a percentage, which is simply 100 minus your LTV.",
      },
      {
        question: "Can my LTV change after I buy?",
        answer: "Yes, in both directions. Every mortgage payment reduces your loan balance, lowering LTV over time, and rising home values increase the denominator, lowering it further. A falling market does the opposite and can push LTV up, occasionally leaving owners underwater when the loan exceeds the value. Because LTV shifts, it is worth recalculating before refinancing or requesting removal of mortgage insurance.",
      },
      {
        question: "What LTV do I need to refinance?",
        answer: "Requirements vary by loan type, but many conventional refinances look for an LTV of 80% or lower to secure the best rates and skip mortgage insurance. Some cash-out refinances cap LTV around 80% as well, while certain government-backed programs allow higher ratios. Calculate your current LTV first using your remaining balance and an up-to-date valuation, then compare it against your target lender's published limits.",
      },
      {
        question: "Does the property value mean purchase price or appraisal?",
        answer: "Lenders generally use the lower of the purchase price and the appraised value when buying, and the current appraised value when refinancing. For a quick estimate, enter your best figure for what the property is worth today. If you are close to an important threshold like 80%, an official appraisal can matter, since even a small valuation difference can move your LTV across a lender's cutoff.",
      },
    ],
    relatedCalculators: ["down-payment-calculator", "mortgage-refinance-calculator", "cap-rate-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Consumer Financial Protection Bureau",
    sourceUrl: "https://www.consumerfinance.gov/owning-a-home/",
  },
  {
    id: "down-payment",
    slug: "down-payment-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Down Payment Calculator",
    shortDescription: "Turn a home price and percentage into cash and loan amounts.",
    seoTitle: "Down Payment Calculator — Cash Needed and Loan Amount",
    metaDescription: "Free down payment calculator. Enter a home price and down payment percentage to see the cash you need upfront and the resulting mortgage loan amount instantly.",
    primaryKeyword: "down payment calculator",
    secondaryKeywords: ["home down payment calculator", "mortgage down payment calculator", "how much down payment"],
    fields: [
      { id: "homePrice", label: "Home price", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 400000" },
      { id: "downPaymentPercent", label: "Down payment percentage", type: "number", unit: "%", required: true, span: 1, min: 0, max: 100, placeholder: "e.g. 20" },
    ],
    results: [
      { id: "downPayment", label: "Down payment", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "loanAmount", label: "Loan amount", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Down payment = price × percent",
    formulaExplanation: "Multiplying the home price by your chosen percentage converts a proportion into the exact cash you must bring to closing. Because the down payment and the mortgage together cover the full purchase price, subtracting that cash from the price leaves the amount you need to finance. Raising the percentage shifts money from the loan to your upfront outlay, shrinking the balance you borrow and the interest you eventually pay.",
    explanation: "The down payment is the slice of a home's price you pay in cash upfront, and it shapes almost everything about the mortgage that follows. A down payment calculator translates a percentage into a concrete dollar figure so you can see exactly how much you must save, then shows the loan amount left to finance once that cash is applied. Enter a $400,000 home and a 20% target and the split appears at once.\n\nThe size of your down payment ripples through the whole deal. A larger one lowers your loan-to-value ratio, often helping you dodge private mortgage insurance, unlock better interest rates, and shrink both the balance and the total interest paid across the life of the loan. A smaller one preserves cash for moving, repairs, or emergencies but usually costs more each month.\n\nThe math works because the down payment and the mortgage always add up to the purchase price, so fixing one determines the other. Choosing a percentage is a balancing act between the appeal of buying sooner with less saved and the long-run savings of borrowing less. First-time buyers especially benefit from testing several percentages, since seeing the cash requirement and resulting loan side by side makes the trade-offs concrete rather than abstract.",
    example: { inputs: { homePrice: 400000, downPaymentPercent: 20 }, explanation: "A 20% down payment on a $400,000 home is $400,000 × 0.20 = $80,000 in cash. Subtracting that from the price leaves a loan amount of $320,000 to finance." },
    faqs: [
      {
        question: "How much down payment do I actually need?",
        answer: "It depends on the loan. Twenty percent is the classic target because it avoids private mortgage insurance and secures strong rates, but many programs accept far less: conventional loans can start near 3%, and some government-backed options go lower still. A bigger down payment lowers your monthly cost and total interest, while a smaller one lets you buy sooner. Match the figure to your savings and monthly budget.",
      },
      {
        question: "What happens if I put down less than 20%?",
        answer: "You can usually still buy, but lenders typically require private mortgage insurance, an extra monthly premium that protects them against default. Your loan-to-value ratio starts higher, your monthly payment is larger, and you pay more interest overall because you financed more. As you repay the balance or the home appreciates, you can often request that the insurance be removed once your equity reaches roughly 20%.",
      },
      {
        question: "Does the down payment cover closing costs too?",
        answer: "No. The down payment is applied directly to the home's purchase price, while closing costs are separate fees for the loan, title, and services, usually running around 2% to 5% of the price. Budget for both, since you need the down payment plus closing costs in cash at settlement. Estimating each separately prevents an unpleasant surprise when the final figure to close arrives.",
      },
      {
        question: "Is a bigger down payment always better?",
        answer: "Not necessarily. A larger down payment cuts your loan, monthly payment, and lifetime interest, which is genuinely valuable. But draining your savings to reach it can leave you without reserves for repairs, moving, or emergencies, and the cash might earn more invested elsewhere. The right amount balances the guaranteed savings of borrowing less against the security and flexibility of keeping a healthy cash cushion.",
      },
      {
        question: "Can down payment money come from a gift?",
        answer: "Often, yes. Many loan programs allow gift funds from family toward a down payment, though lenders usually require a gift letter confirming the money is not a loan and may ask to trace its source. Rules on how much can be gifted and whether any of your own funds are required vary by loan type, so confirm the specifics with your lender before relying on gifted cash.",
      },
    ],
    relatedCalculators: ["loan-to-value-calculator", "closing-costs-calculator", "rent-vs-buy-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Consumer Financial Protection Bureau",
    sourceUrl: "https://www.consumerfinance.gov/owning-a-home/",
  },
  {
    id: "closing-costs",
    slug: "closing-costs-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Closing Costs Calculator",
    shortDescription: "Estimate the fees you pay to finalize a home purchase.",
    seoTitle: "Closing Costs Calculator — Estimate Home Buying Fees",
    metaDescription: "Free closing costs calculator. Enter a home price and rate to estimate the fees due at settlement, with a typical low and high range of 2% to 5% of the price.",
    primaryKeyword: "closing costs calculator",
    secondaryKeywords: ["home closing costs calculator", "closing cost estimator", "buyer closing costs"],
    fields: [
      { id: "homePrice", label: "Home price", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 400000" },
      { id: "rate", label: "Closing cost rate", type: "number", unit: "%", required: false, span: 1, min: 0, defaultValue: 3, helpText: "Typically 2–5% of price." },
    ],
    results: [
      { id: "estimated", label: "Estimated closing costs", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "low", label: "Low (2%)", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "high", label: "High (5%)", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Closing costs ≈ price × rate%",
    formulaExplanation: "Closing costs bundle many separate fees that each tend to scale with the size of the transaction, so estimating them as a single percentage of the home price gives a reliable ballpark. Multiplying price by your chosen rate produces the central estimate, while applying the typical two and five percent bounds brackets the likely range. The wider the band, the more your final bill depends on lender, location, and the services you use.",
    explanation: "Closing costs are the collection of fees a buyer pays to finalise a home purchase, due in cash at settlement on top of the down payment. A closing costs calculator estimates this bill by applying a percentage to the home price, since the many individual charges tend to rise and fall with the size of the deal. It also brackets the estimate with a typical low and high range so you can plan for the realistic spread rather than a single optimistic figure.\n\nThe charges folded into closing costs are varied: loan origination and underwriting fees, appraisal and inspection, title search and insurance, escrow and recording fees, prepaid property taxes, and homeowners insurance. Individually they seem small, but together they commonly total between two and five percent of the purchase price, a sum large enough to derail an unprepared buyer at the last moment.\n\nThe percentage approach works because most of these fees scale with the transaction, making a proportion of price a dependable first estimate. Knowing the number early lets you save the right amount, compare lender quotes, and decide whether to negotiate seller concessions. Every buyer should size up closing costs alongside their down payment well before settlement, because underestimating them is one of the most common and stressful surprises in the home-buying process.",
    example: { inputs: { homePrice: 400000, rate: 3 }, explanation: "At a 3% rate, closing costs on a $400,000 home are about $400,000 × 0.03 = $12,000. The typical range runs from 2% ($8,000) to 5% ($20,000), so budget within that band." },
    faqs: [
      {
        question: "What is included in closing costs?",
        answer: "Closing costs bundle the fees needed to complete the sale and set up the loan: origination and underwriting charges, appraisal, home inspection, title search and title insurance, escrow and recording fees, attorney fees where required, and prepaid items like property taxes and homeowners insurance. The exact mix varies by lender, state, and property, which is why the total is best estimated as a percentage of price rather than a fixed amount.",
      },
      {
        question: "How much are closing costs usually?",
        answer: "For buyers, closing costs commonly fall between 2% and 5% of the home's purchase price. On a $400,000 home that is roughly $8,000 to $20,000. Where you land within the range depends on your lender's fees, local taxes and title costs, and whether you buy discount points to lower your rate. Getting a loan estimate from your lender turns this rough band into precise figures.",
      },
      {
        question: "Can I roll closing costs into my mortgage?",
        answer: "Sometimes. Certain loan programs and lenders allow you to finance some closing costs into the loan or accept a slightly higher interest rate in exchange for lender credits that offset them. This reduces the cash you need at settlement but increases your loan balance or monthly payment. It is a trade between upfront affordability and long-term cost, so weigh it against simply paying the fees directly if you can.",
      },
      {
        question: "Who pays closing costs, the buyer or seller?",
        answer: "Both parties typically have closing costs, but they differ. Buyers usually cover loan-related fees, appraisal, inspection, and prepaid taxes and insurance, while sellers often pay real estate agent commissions and certain transfer taxes. In negotiations, buyers sometimes ask sellers for concessions that cover part of the buyer's closing costs. Local custom and the strength of the market heavily influence who ultimately pays which fees.",
      },
      {
        question: "Are closing costs separate from the down payment?",
        answer: "Yes. The down payment is applied to the home's purchase price and builds your equity, while closing costs are fees for the loan and the transaction itself. You need both amounts in cash at settlement, and neither replaces the other. Budgeting them separately is important, because focusing only on the down payment can leave you thousands of dollars short when the final closing statement arrives.",
      },
    ],
    relatedCalculators: ["down-payment-calculator", "rent-vs-buy-calculator", "loan-to-value-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Consumer Financial Protection Bureau",
    sourceUrl: "https://www.consumerfinance.gov/owning-a-home/",
  },
  {
    id: "property-tax",
    slug: "property-tax-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Property Tax Calculator",
    shortDescription: "Estimate annual and monthly property tax from assessed value.",
    seoTitle: "Property Tax Calculator — Annual and Monthly Estimate",
    metaDescription: "Free property tax calculator. Enter your assessed value and tax rate to estimate your annual property tax bill and the monthly amount to set aside in escrow.",
    primaryKeyword: "property tax calculator",
    secondaryKeywords: ["real estate tax calculator", "property tax estimator", "annual property tax calculator"],
    fields: [
      { id: "assessedValue", label: "Assessed value", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 300000" },
      { id: "taxRate", label: "Tax rate", type: "number", unit: "%", required: true, span: 1, min: 0, placeholder: "e.g. 1.2" },
    ],
    results: [
      { id: "annualTax", label: "Annual property tax", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "monthlyTax", label: "Monthly property tax", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Annual tax = assessed value × tax rate%",
    formulaExplanation: "Property tax is levied as a percentage of a home's assessed value, so multiplying that value by the rate yields the yearly bill. Dividing the annual figure by twelve gives the monthly amount, which matters because most lenders collect it in an escrow account alongside the mortgage payment. A higher assessed value or rate raises the bill proportionally, which is why appeals and local rate changes move the number directly.",
    explanation: "Property tax is an annual levy that local governments charge based on the value of your home, and it funds schools, roads, emergency services, and other community needs. A property tax calculator estimates the bill by multiplying your assessed value by the local tax rate, then splits it into a monthly figure so you can see what to set aside each month. Because most lenders collect property tax through escrow, that monthly number folds directly into your housing payment.\n\nTwo inputs drive the result. The assessed value is the figure your local assessor assigns to the property, which may differ from what you paid or could sell for. The tax rate, sometimes expressed as a millage, is set by your municipality and can vary sharply from one town or county to the next. Multiply them and you have the annual obligation.\n\nThe calculation works because property tax is fundamentally proportional: a fixed rate applied to value. That makes it easy to see how a reassessment or a rate change would move your bill, and why two similar homes in different districts can owe very different amounts. Buyers should always factor property tax into affordability, since it recurs for as long as you own and can rise over time as assessments and local budgets change.",
    example: { inputs: { assessedValue: 300000, taxRate: 1.2 }, explanation: "A 1.2% rate on a $300,000 assessed value is $300,000 × 0.012 = $3,600 per year. Divided by twelve, that is $300 per month to set aside for property tax." },
    faqs: [
      {
        question: "What is assessed value and how is it set?",
        answer: "Assessed value is the dollar figure a local tax assessor assigns to your property to calculate tax, and it may differ from the market price or what you paid. Assessors use methods like comparable sales, replacement cost, or income potential, and many jurisdictions reassess periodically or apply a fixed ratio to market value. Because the tax is based on this number, an inaccurate assessment directly inflates your bill.",
      },
      {
        question: "How do I find my property tax rate?",
        answer: "Tax rates are set by local governments and are usually published on your county or municipal assessor's or treasurer's website, often as a percentage or as a millage rate. Your annual tax bill and mortgage escrow statement also list the effective rate. Rates vary widely by location because they reflect local budgets for schools and services, so always use the figure for your specific district rather than a state average.",
      },
      {
        question: "Why is property tax collected monthly in escrow?",
        answer: "Many lenders divide your annual property tax into twelve and collect it alongside your mortgage payment, holding it in an escrow account and paying the tax authority when it comes due. This spreads a large yearly bill into manageable monthly amounts and protects the lender by ensuring the tax is paid, since unpaid property taxes can create a lien that outranks the mortgage on the property.",
      },
      {
        question: "Can I lower my property tax bill?",
        answer: "Sometimes. If you believe your assessed value is too high, most jurisdictions let you file an appeal with evidence such as recent comparable sales or an independent appraisal. Many areas also offer exemptions that reduce taxable value for primary residences, seniors, veterans, or people with disabilities. Check your assessor's office for available exemptions and appeal deadlines, since these programs can meaningfully cut the bill for those who qualify.",
      },
      {
        question: "Does property tax change over time?",
        answer: "Yes. Your bill can rise or fall when the local government adjusts its tax rate, when your property is reassessed to a new value, or when nearby development shifts the market. Some jurisdictions cap how fast assessments can climb each year, while others reassess at every sale. Because the tax recurs annually and can grow, factor potential increases into your long-term budget rather than assuming today's figure is fixed.",
      },
    ],
    relatedCalculators: ["cap-rate-calculator", "rent-vs-buy-calculator", "closing-costs-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard real estate formula",
  },
  {
    id: "mortgage-refinance",
    slug: "mortgage-refinance-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Mortgage Refinance Calculator",
    shortDescription: "See your new payment, monthly savings, and break-even point.",
    seoTitle: "Mortgage Refinance Calculator — Savings and Break-Even",
    metaDescription: "Free mortgage refinance calculator. Compare your current payment to a new rate and term to find your new payment, monthly savings, and break-even point in months.",
    primaryKeyword: "mortgage refinance calculator",
    secondaryKeywords: ["refinance calculator", "refinance savings calculator", "refinance break even calculator"],
    fields: [
      { id: "currentBalance", label: "Current loan balance", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 300000" },
      { id: "currentPayment", label: "Current monthly payment", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 1800" },
      { id: "newRate", label: "New interest rate", type: "number", unit: "%", required: true, span: 1, min: 0, placeholder: "e.g. 5" },
      { id: "newTerm", label: "New loan term", type: "number", unit: "years", required: true, span: 1, min: 1, placeholder: "e.g. 30" },
      { id: "closingCosts", label: "Refinance closing costs", type: "number", unit: "$", required: false, span: 1, min: 0, placeholder: "e.g. 6000" },
    ],
    results: [
      { id: "newPayment", label: "New payment", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "monthlySavings", label: "Monthly savings", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
      { id: "breakevenMonths", label: "Break-even", format: "number", decimals: 0, unit: "months", isPrimary: false },
    ],
    formula: "New payment via amortization; break-even = closing costs ÷ monthly savings",
    formulaExplanation: "The new principal and interest payment comes from the standard amortization formula applied to your current balance at the new rate and term, spreading repayment evenly. Subtracting that payment from your existing one gives the monthly saving. Dividing the closing costs by that saving tells you how many months of lower payments it takes to recoup the upfront expense, which is the moment refinancing starts putting money back in your pocket.",
    explanation: "Refinancing replaces your existing mortgage with a new loan, usually to capture a lower interest rate, shorten or extend the term, or free up monthly cash. A mortgage refinance calculator makes the decision concrete by computing your new principal and interest payment from your current balance, then comparing it against what you pay today to reveal the monthly saving and, crucially, how long it takes to earn back the cost of refinancing.\n\nThat last figure, the break-even point, is what separates a smart refinance from a costly one. Refinancing is not free: closing costs for the new loan often run into the thousands. Dividing those costs by your monthly saving shows how many months you must keep the loan before the savings overtake the upfront expense. If you plan to sell or refinance again before that point, the deal may not pay off.\n\nThe math works because the new payment follows the same amortization logic as any mortgage, so a lower rate or different term produces a predictable new figure. Weighing the monthly saving against the break-even horizon lets you judge whether a refinance genuinely helps. Owners should also consider that extending the term can lower the payment while raising total interest, so the monthly saving alone never tells the whole story.",
    example: { inputs: { currentBalance: 300000, currentPayment: 1800, newRate: 5, newTerm: 30, closingCosts: 6000 }, explanation: "Refinancing $300,000 at 5% over 30 years yields a new payment of about $1,610 a month, roughly $190 less than the current $1,800. Recovering the $6,000 in closing costs takes about $6,000 ÷ $190 ≈ 32 months to break even." },
    faqs: [
      {
        question: "What is the break-even point on a refinance?",
        answer: "The break-even point is the number of months it takes for your accumulated monthly savings to equal the closing costs you paid to refinance. Divide the closing costs by the monthly saving to find it. If your break-even is 32 months, you need to keep the new loan at least that long to come out ahead. Refinancing rarely pays off if you plan to move or refinance again sooner.",
      },
      {
        question: "Does a lower monthly payment always mean I save money?",
        answer: "Not always. A lower payment can come from a genuinely lower rate, which does save money, or from stretching the balance over a longer term, which reduces the monthly figure while increasing the total interest you pay over the life of the loan. Look beyond the payment to the interest rate, the new term, and the total cost. A smaller payment on a longer loan can quietly cost more overall.",
      },
      {
        question: "What closing costs come with refinancing?",
        answer: "Refinancing carries many of the same fees as an original mortgage: loan origination, appraisal, title search and insurance, recording, and sometimes points to buy down the rate. These commonly total a few percent of the loan balance. Some lenders offer no-closing-cost refinances that fold the fees into the balance or the rate instead, which lowers upfront cash but raises the loan or monthly payment, so compare total cost carefully.",
      },
      {
        question: "Should I refinance to a shorter term?",
        answer: "Refinancing from a 30-year to a 15-year term usually raises your monthly payment but sharply reduces total interest and builds equity faster, which suits owners who can afford the higher payment and want to own outright sooner. Extending the term does the opposite, lowering payments while increasing lifetime interest. The right choice depends on your budget and goals, so compare both the monthly figure and the total interest before deciding.",
      },
      {
        question: "When is refinancing usually worth it?",
        answer: "Refinancing tends to make sense when you can lower your interest rate meaningfully, you plan to stay in the home past the break-even point, and the monthly savings justify the closing costs. It can also help if you want to switch from an adjustable to a fixed rate, remove mortgage insurance after gaining equity, or shorten the term. Run the numbers on your specific loan rather than relying on a general rate-drop rule of thumb.",
      },
    ],
    relatedCalculators: ["loan-to-value-calculator", "rent-vs-buy-calculator", "closing-costs-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    sensitivity: "finance",
    formulaSource: "Standard amortization formula",
    sourceUrl: "https://www.consumerfinance.gov/owning-a-home/",
  },
];
