import type { CalculatorDefinition } from "../types";

export const realestateR6Calculators: CalculatorDefinition[] = [
  {
    id: "price-per-square-foot",
    slug: "price-per-square-foot-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Price Per Square Foot Calculator",
    shortDescription: "Turn a property price and size into a per-square-foot figure.",
    seoTitle: "Price Per Square Foot Calculator — Compare Home Values",
    metaDescription: "Free price per square foot calculator. Enter a property price and its square footage to find the cost per square foot and compare homes of different sizes fairly.",
    primaryKeyword: "price per square foot calculator",
    secondaryKeywords: ["cost per square foot calculator", "home price per sq ft", "real estate price per square foot"],
    fields: [
      { id: "propertyPrice", label: "Property price", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 400000" },
      { id: "squareFeet", label: "Square feet", type: "number", unit: "sq ft", required: true, span: 1, min: 0, placeholder: "e.g. 2000" },
    ],
    results: [
      { id: "pricePerSqFt", label: "Price per square foot", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
    ],
    formula: "Price per square foot = property price ÷ square feet",
    formulaExplanation: "Dividing the total price by the finished floor area distributes the cost evenly across every square foot, converting one large headline number into a rate you can compare directly. Because the rate is independent of a home's overall size, a compact condo and a sprawling house become directly comparable. A higher figure signals a more expensive market, premium finishes, or a desirable location, while a lower figure points to relative value or a property that may need work.",
    explanation: "Price per square foot is the single most common yardstick real estate agents, appraisers, and buyers use to compare homes that differ in size. A price per square foot calculator takes a property's asking price and its finished floor area and divides one by the other, producing a rate that strips away the distortion of raw price. A $400,000 home and an $800,000 home tell you little on their own, but knowing one costs $200 per square foot and the other $250 reveals which is priced more richly for what you actually get.\n\nThe measure matters because square footage is the closest thing real estate has to a universal unit. Reducing every listing to a cost per square foot lets you line up properties across a neighbourhood, judge whether an asking price is ambitious or fair, and spot outliers worth a second look. Appraisers lean on it heavily when selecting comparable sales, and sellers use it to position a home against nearby competition.\n\nThe calculation works because dividing price by area normalises size out of the equation, the same way price per ounce normalises grocery packaging. It is not a complete valuation, since it ignores lot size, condition, layout, and location within a market, but it is the fastest, most widely understood screen available. Always compare per-square-foot figures within the same area and property type, because the benchmark shifts dramatically between markets.",
    example: { inputs: { propertyPrice: 400000, squareFeet: 2000 }, explanation: "A $400,000 home with 2,000 square feet of finished space works out to $400,000 ÷ 2,000 = $200 per square foot, a figure you can compare directly against nearby listings of any size." },
    faqs: [
      {
        question: "What is a good price per square foot?",
        answer: "There is no universal number because the figure depends entirely on the local market. A price that is a bargain in a coastal city might be steep in a rural town. What matters is how a property compares to recent sales of similar homes in the same neighbourhood. Pull several comparable listings, compute their per-square-foot rates, and judge your target against that local range rather than any national average.",
      },
      {
        question: "Should I include unfinished space in the square footage?",
        answer: "Generally no. Standard practice counts finished, heated living area and excludes unfinished basements, garages, attics, and outdoor spaces. Including them would inflate the size and understate the true price per square foot, making comparisons misleading. To keep figures consistent, use the same finished-area definition across every property you compare, ideally the gross living area reported on listings or appraisals rather than a rough estimate.",
      },
      {
        question: "Why do two similar homes have different prices per square foot?",
        answer: "Price per square foot captures only size, so everything else it ignores shows up as a difference. A renovated kitchen, a better lot, a garage, a superior view, or simply a smaller home spreading fixed costs like the kitchen and bathrooms over fewer feet can all move the rate. Smaller homes often show a higher per-square-foot figure because their expensive rooms are divided across less total area.",
      },
      {
        question: "Is price per square foot enough to value a home?",
        answer: "No, it is a screening tool rather than a full appraisal. It ignores lot size, condition, age, layout, location within a neighbourhood, and market timing, all of which materially affect value. Use it to sift listings quickly and flag properties that look overpriced or underpriced, then dig into a proper comparable-sales analysis on the finalists before making an offer or setting a listing price.",
      },
      {
        question: "How do builders and buyers use this figure differently?",
        answer: "Buyers use price per square foot to compare existing homes and judge whether an asking price is reasonable against nearby sales. Builders and those pricing new construction think in cost per square foot to build, covering materials and labour, then add land and profit. The two figures answer different questions, so a construction cost per square foot should not be compared directly against a resale market price per square foot.",
      },
    ],
    relatedCalculators: ["cap-rate-calculator", "property-tax-calculator", "rental-yield-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard real estate formula",
  },
  {
    id: "gross-rent-multiplier",
    slug: "gross-rent-multiplier-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Gross Rent Multiplier (GRM) Calculator",
    shortDescription: "Screen rental deals by dividing price by annual gross rent.",
    seoTitle: "Gross Rent Multiplier Calculator — GRM for Rentals",
    metaDescription: "Free gross rent multiplier calculator. Divide a property's price by its annual gross rent to find the GRM and quickly screen rental investments against local benchmarks.",
    primaryKeyword: "gross rent multiplier calculator",
    secondaryKeywords: ["grm calculator", "gross rent multiplier formula", "rental property grm"],
    fields: [
      { id: "propertyPrice", label: "Property price", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 500000" },
      { id: "annualGrossRent", label: "Annual gross rent", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 40000" },
    ],
    results: [
      { id: "grm", label: "Gross rent multiplier", format: "number", decimals: 2, isPrimary: true },
    ],
    formula: "GRM = property price ÷ annual gross rent",
    formulaExplanation: "Dividing the purchase price by the gross annual rent tells you how many years of rent, before any expenses, it would take to equal the price. Because the ratio uses gross rent rather than net income, it deliberately skips vacancy and operating costs to stay fast and simple. A lower multiplier means the property is cheaper relative to the rent it collects, which is usually more attractive; a higher multiplier signals a pricier asset per rental dollar.",
    explanation: "The gross rent multiplier, universally shortened to GRM, is a quick screening ratio real estate investors use to compare rental properties before committing to detailed analysis. A GRM calculator divides a property's price by its annual gross rent, returning a single number that expresses how many years of rent would equal the purchase price if every dollar collected went straight to paying it off. It is deliberately crude, ignoring expenses and vacancy, which is exactly what makes it fast.\n\nGRM earns its place as the first filter in a deal funnel. Faced with dozens of listings, an investor can compute each one's multiplier in seconds and immediately rank them by how expensive they are relative to the rent they produce. A property with a GRM of 8 is priced at eight years of gross rent, while one at 14 costs far more per rental dollar. Lower is generally better, though a very low figure can hint at a rough neighbourhood or hidden problems worth investigating.\n\nThe ratio works because gross rent is easy to find and hard to dispute, so it provides a consistent basis for comparison across many properties. Its weakness is the flip side of its strength: by ignoring operating costs, taxes, and vacancy, it can flatter a property with heavy expenses. Smart investors use GRM to sort a long list quickly, then move to cap rate and cash flow analysis on the survivors, where the real economics of a deal come into focus.",
    example: { inputs: { propertyPrice: 500000, annualGrossRent: 40000 }, explanation: "A property priced at $500,000 that collects $40,000 in annual gross rent has a GRM of $500,000 ÷ $40,000 = 12.5, meaning the price equals about twelve and a half years of gross rent." },
    faqs: [
      {
        question: "What is a good gross rent multiplier?",
        answer: "It varies by market, but many investors consider a GRM between 4 and 10 attractive, with lower numbers indicating a cheaper property relative to its rent. High-demand urban markets often carry higher multipliers, while affordable regions run lower. Because the benchmark is local, compare a property's GRM against recent sales of similar rentals in the same area rather than applying a fixed rule everywhere.",
      },
      {
        question: "How is GRM different from cap rate?",
        answer: "GRM uses gross rent and ignores expenses, making it a fast but rough screen, while cap rate uses net operating income after operating costs and vacancy, giving a more accurate return picture. GRM answers how expensive a property is per rental dollar; cap rate answers what yield it actually produces. Investors typically screen with GRM first, then compute cap rate on the properties that pass.",
      },
      {
        question: "Should I use monthly or annual rent in the formula?",
        answer: "This calculator uses annual gross rent, so multiply monthly rent by twelve before entering it, or add up a full year of collected rent across all units. Consistency is what matters: always use the same period across every property you compare. Mixing monthly and annual figures would produce wildly different multipliers and make your comparisons meaningless, so double-check the period before reading anything into the result.",
      },
      {
        question: "Why does GRM ignore expenses?",
        answer: "By design. GRM trades accuracy for speed, using only gross rent because it is easy to obtain and consistent across listings. That lets an investor rank many properties quickly without hunting down each one's tax, insurance, and maintenance figures. The trade-off is that a property with unusually high expenses can look better on GRM than it deserves, which is why deeper metrics follow once GRM narrows the field.",
      },
      {
        question: "Can GRM be used for commercial property?",
        answer: "It can, but with more caution. Commercial leases vary widely in who pays expenses, so gross rent may not be comparable between properties the way it is for similar residential rentals. For commercial deals, net operating income and cap rate are usually more reliable. GRM still offers a quick first glance, but treat it as a rough indicator and lean on expense-adjusted metrics for any serious commercial analysis.",
      },
    ],
    relatedCalculators: ["cap-rate-calculator", "rental-yield-calculator", "rental-property-roi-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    sensitivity: "finance",
    formulaSource: "Standard real estate formula",
  },
  {
    id: "cash-on-cash-return",
    slug: "cash-on-cash-return-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Cash-on-Cash Return Calculator",
    shortDescription: "Measure the annual cash return on the cash you actually invested.",
    seoTitle: "Cash-on-Cash Return Calculator — Rental Cash Yield",
    metaDescription: "Free cash-on-cash return calculator. Divide annual pre-tax cash flow by the cash you invested to find your true cash yield on a rental or investment property.",
    primaryKeyword: "cash on cash return calculator",
    secondaryKeywords: ["cash-on-cash calculator", "coc return calculator", "rental cash flow return"],
    fields: [
      { id: "annualPreTaxCashFlow", label: "Annual pre-tax cash flow", type: "number", unit: "$", required: true, span: 1, placeholder: "e.g. 8000" },
      { id: "totalCashInvested", label: "Total cash invested", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 100000" },
    ],
    results: [
      { id: "cocReturn", label: "Cash-on-cash return", format: "percentage", decimals: 2, isPrimary: true },
    ],
    formula: "Cash-on-cash return = annual pre-tax cash flow ÷ total cash invested × 100",
    formulaExplanation: "Dividing the yearly cash flow the property produces by the actual cash you put in measures how hard your own money is working, expressed as a percentage. Unlike cap rate, which ignores financing, this ratio counts only the dollars you personally committed, so a mortgage that reduces your upfront outlay can raise the return. It reflects leverage directly: borrowing more lowers the cash invested and can magnify the percentage, for better or worse.",
    explanation: "Cash-on-cash return is the metric leveraged real estate investors care about most, because it answers a personal question: how much cash does this deal put back in my pocket each year for every dollar I actually invested? A cash-on-cash return calculator divides the property's annual pre-tax cash flow by the total cash you committed, including down payment, closing costs, and any upfront repairs, then expresses the result as a percentage you can compare against other uses of your money.\n\nWhat separates this measure from cap rate is financing. Cap rate treats a property as if bought outright, but almost no investor pays all cash. Cash-on-cash return counts only the money you personally sank into the deal, so a mortgage that lets you control a large asset with a modest down payment can lift the percentage well above the property's unleveraged yield. That is the power, and the risk, of leverage made visible in a single number.\n\nThe calculation works because it ties the reward directly to your own capital at stake, letting you compare a rental against a stock portfolio, a bond, or a different property on equal terms. It is a first-year snapshot rather than a lifetime return, ignoring appreciation, loan paydown, and tax benefits, but it is the clearest gauge of immediate cash efficiency. Investors use it to judge whether a deal's cash flow justifies tying up their capital rather than deploying it elsewhere.",
    example: { inputs: { annualPreTaxCashFlow: 8000, totalCashInvested: 100000 }, explanation: "A property generating $8,000 of pre-tax cash flow a year on $100,000 of cash invested returns $8,000 ÷ $100,000 = 8%, meaning your invested cash earns eight percent annually before taxes." },
    faqs: [
      {
        question: "What counts as cash invested?",
        answer: "Include every dollar you put into the deal upfront: the down payment, closing costs, loan fees, and any immediate repairs or renovations needed to make the property rentable. It excludes the portion of the purchase financed by your mortgage, since that is the lender's money, not yours. Adding all your out-of-pocket costs gives an accurate denominator, so the return reflects the true efficiency of your own capital.",
      },
      {
        question: "How is cash-on-cash return different from ROI?",
        answer: "Cash-on-cash return measures only annual cash flow against the cash you invested, giving a clean yearly yield. Broader return on investment often folds in appreciation, loan principal paydown, and tax effects, producing a fuller but more complex picture. Cash-on-cash is favoured for its simplicity and focus on real spendable income, while total ROI better captures long-term wealth building. Both are useful for different questions.",
      },
      {
        question: "What is a good cash-on-cash return?",
        answer: "Expectations vary by strategy and market, but many rental investors target somewhere between 8% and 12%, judging deals against alternatives like stocks or bonds. A higher figure is more attractive but may carry more risk or a tougher location. Because financing and local conditions shift the number, compare a property's cash-on-cash return against your own required return and other deals you could pursue rather than a fixed threshold.",
      },
      {
        question: "Does the calculator include my mortgage?",
        answer: "Indirectly, and that is the point. The annual pre-tax cash flow you enter should already subtract your mortgage payments along with all operating expenses, so financing costs are baked into the numerator. Meanwhile the cash invested reflects only your down payment and upfront costs, not the loan. This is precisely why cash-on-cash return captures the effect of leverage, unlike cap rate, which ignores debt entirely.",
      },
      {
        question: "Why does leverage change the return so much?",
        answer: "Borrowing lets you control a large, income-producing asset with a small slice of your own cash. Because the return divides cash flow by only that slice, a smaller down payment can sharply raise the percentage, as long as the property still cash flows after the loan payment. Leverage cuts both ways, though: if cash flow turns negative, the same math magnifies losses, so higher leverage means higher risk alongside higher potential return.",
      },
    ],
    relatedCalculators: ["cap-rate-calculator", "rental-property-roi-calculator", "rental-yield-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    sensitivity: "finance",
    formulaSource: "Standard real estate formula",
  },
  {
    id: "net-operating-income",
    slug: "net-operating-income-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Net Operating Income (NOI) Calculator",
    shortDescription: "Find a property's income after operating expenses, before financing.",
    seoTitle: "Net Operating Income Calculator — NOI for Rentals",
    metaDescription: "Free net operating income calculator. Subtract operating expenses from gross operating income to find NOI, the foundation of cap rate and property valuation.",
    primaryKeyword: "net operating income calculator",
    secondaryKeywords: ["noi calculator", "net operating income formula", "rental noi calculator"],
    fields: [
      { id: "grossOperatingIncome", label: "Gross operating income", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 50000" },
      { id: "operatingExpenses", label: "Operating expenses", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 18000" },
    ],
    results: [
      { id: "noi", label: "Net operating income", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
    ],
    formula: "NOI = gross operating income − operating expenses",
    formulaExplanation: "Subtracting operating expenses from gross operating income isolates the profit a property generates from its operations alone, before any mortgage or income tax. Gross operating income is the rent actually collected after vacancy plus any other property income, and operating expenses cover the recurring costs of running the building. What remains is the cash the asset itself produces, the figure lenders and appraisers use to value income property and the numerator behind cap rate.",
    explanation: "Net operating income, almost always written as NOI, is the bedrock number in commercial and rental real estate. A net operating income calculator subtracts a property's operating expenses from its gross operating income to reveal the profit the building produces from operations alone, before any mortgage payment or income tax. Nearly every other valuation metric, from cap rate to debt coverage, is built on top of this single figure, which is why getting it right matters so much.\n\nGross operating income is the money the property actually brings in: rent collected after allowing for vacancy, plus extras like parking, laundry, or storage fees. Operating expenses are the recurring costs of keeping it running: property taxes, insurance, maintenance and repairs, management fees, and utilities the owner covers. Crucially, NOI excludes financing costs and capital expenditures, because those depend on the buyer and distort a property-to-property comparison.\n\nThe calculation works because it separates the performance of the asset from the way any particular owner finances or is taxed on it. Two investors with very different loans see the same NOI on the same building, which is what makes it a fair basis for valuation. Lenders use it to size loans and check debt coverage, appraisers use it to derive value from cap rates, and investors use it as the starting point for judging whether a deal's operations can support its price and its debt.",
    example: { inputs: { grossOperatingIncome: 50000, operatingExpenses: 18000 }, explanation: "A property with $50,000 in gross operating income and $18,000 in operating expenses has an NOI of $50,000 − $18,000 = $32,000, the annual income available before any mortgage payment." },
    faqs: [
      {
        question: "What expenses are included in NOI?",
        answer: "Operating expenses cover the recurring costs of running the property: property taxes, insurance, maintenance and repairs, property management fees, utilities the owner pays, and reasonable reserves. They exclude mortgage principal and interest, income taxes, depreciation, and large one-off capital improvements like a new roof. Keeping this line consistent is essential, because including financing or capital costs would understate NOI and make comparisons between properties unreliable.",
      },
      {
        question: "Why does NOI exclude mortgage payments?",
        answer: "NOI measures the property's own earning power, independent of how any buyer finances it. Two investors might purchase the same building with completely different loans, yet the building's operations are identical. By leaving out mortgage principal and interest, NOI stays a clean, comparable figure that lenders and appraisers can use to value the asset itself. Your leveraged return is captured separately by metrics like cash-on-cash return.",
      },
      {
        question: "How does NOI relate to cap rate?",
        answer: "NOI is the numerator of the cap rate formula: cap rate equals NOI divided by property value. That makes NOI the foundation of income-property valuation, because appraisers estimate value by dividing NOI by a market cap rate. A small change in NOI moves the implied value significantly, which is why owners focus on raising income and trimming operating expenses to increase both NOI and the property's worth.",
      },
      {
        question: "What is gross operating income exactly?",
        answer: "Gross operating income is the total revenue the property realistically collects: scheduled rent minus a vacancy and credit-loss allowance, plus other income such as parking, laundry, storage, or pet fees. It is not the theoretical rent if every unit were always full, but the effective income you can count on. Starting from a realistic collected figure rather than a best-case number keeps the resulting NOI honest and useful.",
      },
      {
        question: "Can NOI be negative?",
        answer: "Yes. If a property's operating expenses exceed its gross operating income, NOI turns negative, meaning the building loses money from operations before any mortgage is even considered. That is a serious warning sign, often pointing to high vacancy, runaway costs, or under-market rents. This calculator will show a negative result in those cases, signalling that the property's operations need to be fixed before it can support debt or produce a return.",
      },
    ],
    relatedCalculators: ["cap-rate-calculator", "rental-property-roi-calculator", "rental-yield-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    sensitivity: "finance",
    formulaSource: "Standard real estate formula",
  },
  {
    id: "vacancy-rate",
    slug: "vacancy-rate-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Vacancy Rate Calculator",
    shortDescription: "Find the share of units sitting empty and your occupancy rate.",
    seoTitle: "Vacancy Rate Calculator — Occupancy for Rentals",
    metaDescription: "Free vacancy rate calculator. Divide vacant units by total units to find your vacancy rate and occupancy rate for rental property performance and underwriting.",
    primaryKeyword: "vacancy rate calculator",
    secondaryKeywords: ["occupancy rate calculator", "rental vacancy rate", "vacancy rate formula"],
    fields: [
      { id: "vacantUnits", label: "Vacant units", type: "number", unit: "units", required: true, span: 1, min: 0, placeholder: "e.g. 3" },
      { id: "totalUnits", label: "Total units", type: "number", unit: "units", required: true, span: 1, min: 0, placeholder: "e.g. 50" },
    ],
    results: [
      { id: "vacancyRate", label: "Vacancy rate", format: "percentage", decimals: 2, isPrimary: true },
      { id: "occupancyRate", label: "Occupancy rate", format: "percentage", decimals: 2, isPrimary: false },
    ],
    formula: "Vacancy rate = vacant units ÷ total units × 100; occupancy = 100 − vacancy",
    formulaExplanation: "Dividing vacant units by the total number of units gives the fraction of the property that is currently generating no rent, expressed as a percentage. Because every unit is either occupied or vacant, the occupancy rate is simply the remainder, one hundred percent minus the vacancy rate. Together the two figures describe how fully a property is earning, which drives effective rental income and, through it, net operating income and value.",
    explanation: "Vacancy rate is the share of a rental property's units that sit empty and earn no rent, and it is one of the most closely watched health indicators in real estate. A vacancy rate calculator divides the number of vacant units by the total number of units and returns both the vacancy rate and its mirror image, the occupancy rate. For a landlord, an underwriter, or an analyst, these two percentages capture at a glance how fully a property is performing.\n\nThe number matters because empty units are pure lost income while expenses like taxes, insurance, and maintenance keep running regardless. A property may look profitable at full occupancy, but a persistently high vacancy rate quietly erodes the rent that supports its value and its debt. Lenders build an assumed vacancy allowance into their underwriting precisely because no property stays perfectly full forever, and a realistic vacancy figure keeps income projections honest.\n\nThe calculation works because occupancy is binary at the unit level: each unit is either rented or not, so counting the empties against the total gives a clean proportion. Comparing a property's vacancy rate against the local market average reveals whether its emptiness is a market-wide condition or a property-specific problem with pricing, management, or condition. Investors track the trend over time, since a rising vacancy rate is often the first sign that rents are set too high or that a neighbourhood's demand is softening.",
    example: { inputs: { vacantUnits: 3, totalUnits: 50 }, explanation: "A 50-unit building with 3 empty units has a vacancy rate of 3 ÷ 50 = 6%, which means an occupancy rate of 94% — the share of units currently producing rent." },
    faqs: [
      {
        question: "What is a healthy vacancy rate?",
        answer: "It depends on the market and property type, but many stabilised residential rentals aim for vacancy in the low-to-mid single digits, often around 5%. Some vacancy is normal and even healthy, since it reflects natural tenant turnover and gives room to raise rents. A rate well above the local average signals a problem with pricing, condition, or management, while near-zero vacancy may mean rents are set too low.",
      },
      {
        question: "How is vacancy rate different from occupancy rate?",
        answer: "They are two sides of the same measurement. Vacancy rate is the percentage of units empty, while occupancy rate is the percentage filled, and the two always sum to one hundred percent. If a property is 6% vacant, it is 94% occupied. Investors and lenders may quote either figure, so this calculator shows both to avoid confusion and let you present the number in whichever form your audience expects.",
      },
      {
        question: "Should I measure vacancy by units or by rent?",
        answer: "This calculator uses a simple unit count, which works well when units are similar in size and rent. For properties with very different unit types, an economic vacancy rate weighted by potential rent gives a more accurate picture, because one empty large unit costs more than one empty small one. For a quick operational snapshot the unit count is fine; for detailed underwriting, consider the rent-weighted version too.",
      },
      {
        question: "Why do lenders assume a vacancy allowance?",
        answer: "No property stays fully occupied indefinitely, so lenders deduct an assumed vacancy allowance from potential rent when underwriting a loan. This produces a conservative, realistic income figure rather than a best-case one, protecting the lender if some units sit empty. Building a vacancy assumption into projections keeps net operating income honest, which in turn affects how large a loan the property can support and how it is valued.",
      },
      {
        question: "How can I lower my vacancy rate?",
        answer: "Common levers include pricing units in line with the local market rather than above it, keeping the property well maintained and attractive, responding quickly to enquiries, and offering lease terms that encourage renewals. Reducing tenant turnover is often cheaper than filling empties, since each vacancy carries make-ready costs and lost rent. Tracking your vacancy trend against the market helps you spot whether a rise stems from your property or from broader demand.",
      },
    ],
    relatedCalculators: ["cap-rate-calculator", "rental-yield-calculator", "net-operating-income-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard real estate formula",
  },
  {
    id: "rent-affordability",
    slug: "rent-affordability-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Rent Affordability Calculator",
    shortDescription: "Find the maximum monthly rent your income comfortably supports.",
    seoTitle: "Rent Affordability Calculator — How Much Rent You Can Afford",
    metaDescription: "Free rent affordability calculator. Enter your annual income and a rent-to-income percentage to find the maximum monthly rent you can comfortably afford.",
    primaryKeyword: "rent affordability calculator",
    secondaryKeywords: ["how much rent can i afford", "rent to income calculator", "affordable rent calculator"],
    fields: [
      { id: "annualIncome", label: "Annual income", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 60000" },
      { id: "rentToIncomePercent", label: "Rent-to-income percentage", type: "number", unit: "%", required: false, span: 1, min: 0, max: 100, defaultValue: 30, helpText: "The classic rule of thumb is 30%." },
    ],
    results: [
      { id: "maxMonthlyRent", label: "Maximum monthly rent", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
    ],
    formula: "Max monthly rent = (annual income ÷ 12) × (rent-to-income % ÷ 100)",
    formulaExplanation: "Dividing annual income by twelve converts it to monthly income, and multiplying by your chosen rent-to-income share carves out the slice you are willing to devote to housing. The classic thirty percent guideline leaves the remaining seventy percent for savings, debt, food, transport, and everything else. Adjusting the percentage lets you tighten or loosen the budget to reflect your other obligations, so the result is a ceiling tailored to your own finances rather than a one-size figure.",
    explanation: "Knowing how much rent you can comfortably afford is the first step in any apartment search, and it prevents the painful mistake of falling for a place that quietly strains your budget every month. A rent affordability calculator turns your annual income and a chosen rent-to-income percentage into a clear monthly ceiling, so you can filter listings with confidence and negotiate leases knowing exactly where your limit sits.\n\nThe widely cited rule of thumb is to spend no more than thirty percent of gross income on rent, a guideline landlords themselves often use when screening applicants. The calculator converts your yearly income to a monthly figure and applies your percentage, producing the maximum rent that keeps housing in balance with the rest of your life. If you carry heavy debt or want to save aggressively, you can dial the percentage down; if you live in an expensive city and prioritise location, you might stretch it up, eyes open to the trade-off.\n\nThe math works because rent is best judged as a proportion of income rather than an absolute number: fifteen hundred dollars is comfortable on one salary and crushing on another. Framing affordability as a share keeps the decision grounded in your actual earnings. Treat the result as a ceiling, not a target, and remember that utilities, renters insurance, and other living costs sit on top of rent, so leaving headroom below the maximum is usually the wiser move.",
    example: { inputs: { annualIncome: 60000, rentToIncomePercent: 30 }, explanation: "On a $60,000 salary, monthly income is $5,000. Applying the 30% rule gives a maximum rent of $5,000 × 0.30 = $1,500 per month before utilities and other costs." },
    faqs: [
      {
        question: "Is the 30% rule still a good guideline?",
        answer: "It remains a useful starting point and is widely used by landlords and lenders, but it is a rough guide rather than a law. In expensive cities many renters spend more, while those with heavy debt or ambitious savings goals may want to spend less. Treat 30% as a default, then adjust the percentage in the calculator to reflect your real obligations and priorities for a figure that fits your life.",
      },
      {
        question: "Should I use gross or net income?",
        answer: "The classic 30% rule is based on gross income, your pay before taxes, which is also what most landlords use when screening. That keeps the calculator consistent with common practice. However, budgeting from take-home pay gives a more conservative and often more realistic picture, since taxes and deductions shrink what actually lands in your account. If you want a tighter limit, enter your after-tax annual figure instead.",
      },
      {
        question: "Does this include utilities and other housing costs?",
        answer: "No. The result is the maximum base rent, and costs like electricity, gas, water, internet, renters insurance, and parking sit on top of it. Because those extras can add a meaningful amount each month, it is wise to aim below the calculated ceiling rather than at it. Leaving a cushion ensures the full cost of your housing, not just the rent line, stays within a comfortable share of your income.",
      },
      {
        question: "What if my rent would exceed 30% of income?",
        answer: "It is not automatically unaffordable, but it deserves scrutiny. Spending more on rent means less for savings, debt repayment, and unexpected costs, which raises financial risk. If you must exceed the guideline, look for savings elsewhere in your budget, consider a roommate to split costs, or search a wider area for cheaper options. The calculator lets you raise the percentage so you can see exactly how much a higher share would allow.",
      },
      {
        question: "How do landlords use rent-to-income ratios?",
        answer: "Many landlords require that your gross monthly income be at least three times the rent, which is the same as keeping rent at or below about a third of income. Some ask for a signed pay stub or proof of earnings to verify it. Knowing your affordable range in advance helps you target listings you will actually qualify for and strengthens your application by showing the numbers work comfortably.",
      },
    ],
    relatedCalculators: ["rent-vs-buy-calculator", "down-payment-calculator", "closing-costs-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    sensitivity: "finance",
    formulaSource: "Standard rent-to-income guideline (30% rule)",
  },
  {
    id: "mortgage-payoff",
    slug: "mortgage-payoff-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Mortgage Payoff Calculator",
    shortDescription: "See how many months to clear your loan and the interest it costs.",
    seoTitle: "Mortgage Payoff Calculator — Months to Pay Off and Interest",
    metaDescription: "Free mortgage payoff calculator. Enter your balance, monthly payment, and rate to find how many months until the loan is paid off and the total interest you will pay.",
    primaryKeyword: "mortgage payoff calculator",
    secondaryKeywords: ["loan payoff calculator", "mortgage payoff time", "early mortgage payoff calculator"],
    fields: [
      { id: "currentBalance", label: "Current balance", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 200000" },
      { id: "monthlyPayment", label: "Monthly payment", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 1200" },
      { id: "annualRate", label: "Annual interest rate", type: "number", unit: "%", required: true, span: 1, min: 0, placeholder: "e.g. 5" },
    ],
    results: [
      { id: "monthsToPayoff", label: "Months to payoff", format: "number", decimals: 1, unit: "months", isPrimary: true },
      { id: "totalInterest", label: "Total interest", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Months = −ln(1 − balance × r ÷ payment) ÷ ln(1 + r), where r = annual rate ÷ 12",
    formulaExplanation: "The monthly interest rate r is the annual rate divided by twelve. Each payment first covers the interest accrued on the remaining balance, and whatever is left chips away at principal. Solving the amortization equation for the number of payments gives the logarithmic formula shown, which returns how many months it takes to reach a zero balance. Multiplying the payment by that many months and subtracting the starting balance reveals the total interest paid over the life of the loan.",
    explanation: "A mortgage payoff calculator answers two questions every borrower eventually asks: how long until this loan is gone, and how much interest will it cost me along the way? By entering your current balance, your monthly payment, and your interest rate, you get the number of months remaining until the balance hits zero, plus the total interest you will hand the lender before you are free of the debt.\n\nThe result is powerful because it makes the effect of your payment size tangible. Every dollar above the minimum goes straight to principal, and because interest is charged on the shrinking balance, paying a little extra each month can shave years off the loan and save a striking amount of interest. Running the numbers at your current payment, then at a higher one, shows exactly how much time and money accelerating your payoff would buy.\n\nThe calculation works by inverting the standard amortization formula. Normally that formula sets a payment for a fixed term; here we know the payment and solve for the term instead, using a logarithm to find how many months of payments drive the balance to zero. One important guardrail: if your monthly payment does not exceed the interest accruing each month, the balance never falls and the loan can never be paid off, so the calculator returns no result in that case to flag an impossible scenario.",
    example: { inputs: { currentBalance: 200000, monthlyPayment: 1200, annualRate: 5 }, explanation: "A $200,000 balance at 5% paid down at $1,200 a month takes about 285 months, roughly 24 years, to clear. Over that time you pay about $142,170 in total interest on top of the principal." },
    faqs: [
      {
        question: "Why does paying a little extra save so much interest?",
        answer: "Interest is charged on your remaining balance, so any payment above the interest due reduces principal immediately. A smaller balance then accrues less interest the following month, which compounds in your favour over time. Even a modest extra amount each month can cut years off the loan and save tens of thousands in interest, because you are attacking the principal that would otherwise keep generating interest for decades.",
      },
      {
        question: "What happens if my payment is too low to pay off the loan?",
        answer: "If your monthly payment is less than or equal to the interest that accrues each month, none of it reaches the principal and the balance never shrinks. In that situation the loan mathematically never pays off, and the calculator returns no result to flag the problem. It is a warning that your payment must exceed the monthly interest, ideally by a healthy margin, for the debt to actually decline.",
      },
      {
        question: "Does this calculator account for escrow, taxes, or insurance?",
        answer: "No. It works purely on the loan's principal and interest, so enter only the portion of your payment that goes toward the mortgage itself, not the amount collected for property taxes, homeowners insurance, or private mortgage insurance in escrow. Using your full escrow-inclusive payment would overstate how fast the loan shrinks, so isolate the principal-and-interest figure for an accurate payoff timeline.",
      },
      {
        question: "How is total interest calculated?",
        answer: "Once the calculator knows how many months it takes to reach a zero balance, it multiplies your monthly payment by that number of months to get the total amount you will pay, then subtracts the starting balance, since that portion is principal you originally borrowed. What remains is the interest. This shows the true lifetime cost of the debt and how dramatically it falls when you shorten the payoff period.",
      },
      {
        question: "Should I pay off my mortgage early or invest instead?",
        answer: "It depends on your interest rate, expected investment returns, tax situation, and appetite for risk. Paying off a mortgage delivers a guaranteed return equal to your interest rate and peace of mind, while investing might earn more but carries uncertainty. Many people balance both. Use this calculator to see the guaranteed interest savings from early payoff, then weigh that against what the same money might earn elsewhere.",
      },
    ],
    relatedCalculators: ["mortgage-refinance-calculator", "loan-to-value-calculator", "home-appreciation-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    sensitivity: "finance",
    formulaSource: "Standard amortization formula",
    sourceUrl: "https://www.consumerfinance.gov/owning-a-home/",
  },
  {
    id: "home-appreciation",
    slug: "home-appreciation-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Home Appreciation Calculator",
    shortDescription: "Project a home's future value and gain from an annual growth rate.",
    seoTitle: "Home Appreciation Calculator — Future Home Value",
    metaDescription: "Free home appreciation calculator. Enter a current value, annual appreciation rate, and years to project a home's future value and total gain from compounding growth.",
    primaryKeyword: "home appreciation calculator",
    secondaryKeywords: ["home value appreciation calculator", "house appreciation calculator", "property appreciation calculator"],
    fields: [
      { id: "currentValue", label: "Current value", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 300000" },
      { id: "annualAppreciationRate", label: "Annual appreciation rate", type: "number", unit: "%", required: true, span: 1, placeholder: "e.g. 4" },
      { id: "years", label: "Years", type: "number", unit: "years", required: true, span: 1, min: 0, placeholder: "e.g. 10" },
    ],
    results: [
      { id: "futureValue", label: "Future value", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "totalGain", label: "Total gain", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Future value = current value × (1 + rate ÷ 100)^years",
    formulaExplanation: "Raising one plus the annual rate to the power of the number of years compounds the growth, because each year's appreciation is applied to the previous year's larger value rather than the original. Multiplying the current value by that compounding factor projects what the home could be worth. Subtracting the current value from the projection isolates the total gain, the dollar increase produced purely by appreciation over the holding period, before any costs of selling.",
    explanation: "Home appreciation is the increase in a property's value over time, and projecting it helps owners and buyers picture the wealth a home might build. A home appreciation calculator takes a current value, an assumed annual growth rate, and a number of years, then compounds them to estimate the future value and the total gain. It turns a vague sense that property tends to rise into a concrete, if hypothetical, dollar figure.\n\nThe key idea is compounding. Appreciation does not stack in flat, equal dollar amounts; instead each year's growth is calculated on the value the home reached the year before. A four percent gain on a three-hundred-thousand-dollar home is larger in later years than in the first, because the base keeps growing. Over a decade or two this compounding effect produces gains that a simple straight-line estimate would badly understate.\n\nThe formula works the same way compound interest does, raising one plus the growth rate to the power of the years and multiplying by today's value. That said, real home prices do not rise smoothly; they surge, stall, and sometimes fall with the economy, interest rates, and local demand. Treat the result as a scenario built on your chosen assumption rather than a prediction. Its real value is in comparing outcomes: seeing how different rates or holding periods change the projection helps you set realistic expectations and weigh a home as a long-term asset.",
    example: { inputs: { currentValue: 300000, annualAppreciationRate: 4, years: 10 }, explanation: "A $300,000 home appreciating 4% a year for 10 years grows to $300,000 × 1.04^10 ≈ $444,073, a total gain of about $144,073 from compounding rather than simple growth." },
    faqs: [
      {
        question: "What is a realistic home appreciation rate?",
        answer: "Long-run national home price growth has historically averaged somewhere around three to five percent a year, though this varies enormously by location and era. Some markets boom well above that for stretches, while others stagnate or decline. Because appreciation is so local and cyclical, use a conservative rate for planning and test a range of assumptions rather than banking on any single optimistic figure for the future.",
      },
      {
        question: "Why does compounding matter for home value?",
        answer: "Compounding means each year's appreciation builds on the prior year's higher value, not the original price, so gains accelerate over time. A straight-line estimate that simply multiplies a yearly dollar increase by the number of years understates the true growth. Over long holding periods the difference is substantial, which is why this calculator raises the growth rate to a power rather than adding a flat amount each year.",
      },
      {
        question: "Does this calculator account for inflation?",
        answer: "No, it projects nominal value using the rate you enter. If you want to see real, inflation-adjusted growth, subtract your expected inflation rate from the appreciation rate before entering it. For example, a six percent nominal rate with three percent inflation implies roughly three percent real growth. Working in real terms gives a clearer sense of how much genuine purchasing power the home gains rather than just headline dollars.",
      },
      {
        question: "Is home appreciation guaranteed?",
        answer: "Absolutely not. Home prices can and do fall, as many owners learned in past downturns, and they can stagnate for years. Appreciation depends on interest rates, local job growth, housing supply, and broader economic conditions, none of which are guaranteed. This calculator shows a scenario based on your assumption, not a promise. Treat property as a long-term asset with real risk, and avoid decisions that rely on continuous price growth.",
      },
      {
        question: "How should I use the total gain figure?",
        answer: "The total gain shows the projected increase in value from appreciation alone, before the costs of selling like agent commissions, closing fees, and any capital gains tax. It is useful for comparing scenarios and understanding a home's potential as an investment, but it is not net profit in your pocket. Subtract selling costs and remember you still need somewhere to live to gauge the real financial benefit.",
      },
    ],
    relatedCalculators: ["cap-rate-calculator", "rental-property-roi-calculator", "mortgage-payoff-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard compound growth formula",
  },
  {
    id: "rental-property-roi",
    slug: "rental-property-roi-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Rental Property ROI Calculator",
    shortDescription: "Measure a rental's annual return relative to its purchase price.",
    seoTitle: "Rental Property ROI Calculator — Return on Investment",
    metaDescription: "Free rental property ROI calculator. Subtract expenses from income and divide by purchase price to find your annual return and cash flow on a rental property.",
    primaryKeyword: "rental property roi calculator",
    secondaryKeywords: ["rental roi calculator", "investment property roi", "rental property return calculator"],
    fields: [
      { id: "annualRentalIncome", label: "Annual rental income", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 24000" },
      { id: "annualExpenses", label: "Annual expenses", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 9000" },
      { id: "purchasePrice", label: "Purchase price", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 250000" },
    ],
    results: [
      { id: "roi", label: "Return on investment", format: "percentage", decimals: 2, isPrimary: true },
      { id: "annualCashFlow", label: "Annual cash flow", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "ROI = (annual income − annual expenses) ÷ purchase price × 100",
    formulaExplanation: "Subtracting annual expenses from annual rental income gives the yearly cash flow the property produces, and dividing that by the purchase price expresses it as a percentage return on the full price paid. Because the denominator is the total price rather than only the cash invested, this measure reflects an unleveraged return, treating the property as if bought outright. It offers a simple, comparable gauge of how efficiently the asset converts its price into income.",
    explanation: "Return on investment, or ROI, is the plain-language way most people judge whether a rental property is worth owning. A rental property ROI calculator subtracts the annual expenses from the annual rental income to find the yearly cash flow, then divides that by the purchase price to express the return as a percentage. In one figure it tells you how hard the property's price is working to generate income.\n\nThe measure is popular because it is intuitive and easy to compare. A property returning eight percent on its price is producing more income per dollar than one returning four percent, all else equal. Framing the return against the full purchase price gives an unleveraged view, treating the property as if you paid all cash, which strips out the distortions of different financing arrangements and lets you compare deals on the asset's own merits.\n\nThe calculation works because it ties recurring net income directly to the cost of acquiring the asset, the same logic behind a bond's yield. It does have limits: by using purchase price rather than the cash you actually put down, it does not capture the amplifying effect of a mortgage, and by looking at a single year it ignores appreciation and loan paydown. Even so, it is an excellent first-pass screen. Pair it with cash-on-cash return for the leveraged view and cap rate for market comparison, and you have a rounded picture of a rental's performance.",
    example: { inputs: { annualRentalIncome: 24000, annualExpenses: 9000, purchasePrice: 250000 }, explanation: "A rental collecting $24,000 a year with $9,000 in expenses produces $15,000 of cash flow. Divided by the $250,000 price, that is an ROI of 6%, with an annual cash flow of $15,000." },
    faqs: [
      {
        question: "How is this ROI different from cash-on-cash return?",
        answer: "This ROI divides annual cash flow by the full purchase price, giving an unleveraged return as if you bought with all cash. Cash-on-cash return instead divides by only the cash you actually invested, such as your down payment and closing costs, capturing the effect of a mortgage. ROI is best for comparing properties on their own merits, while cash-on-cash shows how leverage magnifies the return on your personal capital.",
      },
      {
        question: "What expenses should I include?",
        answer: "Include the recurring annual costs of owning and operating the rental: property taxes, insurance, maintenance and repairs, property management fees, and any utilities or HOA dues you cover, plus a realistic allowance for vacancy. If you want an unleveraged operating return, leave out mortgage payments, since including them turns this into a cash flow after financing. Keeping the expense list consistent lets you compare properties fairly.",
      },
      {
        question: "What counts as a good rental ROI?",
        answer: "There is no universal target, but many investors look for something in the mid-single digits or higher on an unleveraged basis, judging it against alternatives like stocks, bonds, or other properties. A higher ROI is more attractive but may reflect greater risk, a weaker location, or deferred maintenance. Because markets differ, compare a property's ROI against similar rentals in the same area rather than a fixed nationwide benchmark.",
      },
      {
        question: "Does this include appreciation?",
        answer: "No. This calculator measures only the annual income return relative to price, ignoring any increase in the property's value over time. Appreciation can be a large part of real estate's total return, but it is uncertain and market-dependent, so keeping it separate makes the income return cleaner and more comparable. To estimate value growth, use a home appreciation calculator alongside this one for a fuller picture of total return.",
      },
      {
        question: "Should I use purchase price or current value?",
        answer: "For evaluating a potential purchase, use the price you would pay, since that is the capital being committed. For reviewing a property you already own, some investors instead divide by its current value to see the return on the equity tied up today, which may have grown. Both are valid but answer different questions, so be consistent about which basis you use when comparing multiple properties.",
      },
    ],
    relatedCalculators: ["cap-rate-calculator", "cash-on-cash-return-calculator", "rental-yield-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    sensitivity: "finance",
    formulaSource: "Standard real estate formula",
  },
  {
    id: "seller-net-proceeds",
    slug: "seller-net-proceeds-calculator",
    category: "Real Estate",
    categorySlug: "real-estate",
    title: "Seller Net Proceeds Calculator",
    shortDescription: "See what you walk away with after paying off the loan and costs.",
    seoTitle: "Seller Net Proceeds Calculator — Home Sale Payout",
    metaDescription: "Free seller net proceeds calculator. Subtract your mortgage balance, agent commission, and closing costs from the sale price to see what you actually take home.",
    primaryKeyword: "seller net proceeds calculator",
    secondaryKeywords: ["net proceeds calculator", "home sale proceeds calculator", "seller net sheet calculator"],
    fields: [
      { id: "salePrice", label: "Sale price", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 500000" },
      { id: "mortgageBalance", label: "Mortgage balance", type: "number", unit: "$", required: true, span: 1, min: 0, placeholder: "e.g. 300000" },
      { id: "commissionPercent", label: "Agent commission", type: "number", unit: "%", required: false, span: 1, min: 0, defaultValue: 6, helpText: "Total commission, often around 5–6%." },
      { id: "otherClosingCosts", label: "Other closing costs", type: "number", unit: "$", required: false, span: 1, min: 0, placeholder: "e.g. 4000" },
    ],
    results: [
      { id: "netProceeds", label: "Net proceeds", format: "currency", currency: "USD", decimals: 2, isPrimary: true },
      { id: "totalCosts", label: "Total selling costs", format: "currency", currency: "USD", decimals: 2, isPrimary: false },
    ],
    formula: "Net proceeds = sale price − mortgage balance − (sale price × commission%) − other closing costs",
    formulaExplanation: "Starting from the sale price, the calculator subtracts three things that stand between the headline number and your bank account: the outstanding mortgage balance you must repay, the agent commission computed as a percentage of the sale price, and any other closing costs such as transfer taxes and title fees. What remains is your net proceeds, the cash you actually take home. The total selling costs figure sums the commission and closing costs so you can see exactly how much the sale itself consumes.",
    explanation: "The sale price on a for-sale sign is rarely the amount a seller actually pockets. A seller net proceeds calculator bridges that gap by subtracting everything that comes out of the sale before you get paid: the remaining mortgage balance, the real estate agent commission, and other closing costs like transfer taxes and title fees. The result is your net proceeds, the real cash you walk away with, along with a clear tally of what the sale itself costs you.\n\nThe biggest deductions are usually the loan payoff and the commission. Whatever you still owe on the mortgage must be settled at closing from the sale price, and agent commissions, often around five to six percent split between the buyer's and seller's agents, take a meaningful slice off the top. Layer on closing costs and the difference between the sale price and your take-home can be tens of thousands of dollars, which surprises many first-time sellers.\n\nThe calculation works by starting from the gross sale price and peeling away each obligation in turn until only your money is left. Seeing the breakdown early helps you price realistically, judge whether an offer clears your remaining loan with room to spare, and plan the down payment on your next home. It also makes the cost of selling visible, which is useful when weighing whether to sell now, negotiate a lower commission, or wait for more equity to build.",
    example: { inputs: { salePrice: 500000, mortgageBalance: 300000, commissionPercent: 6, otherClosingCosts: 4000 }, explanation: "On a $500,000 sale, a 6% commission is $30,000 and closing costs add $4,000, for $34,000 in selling costs. After also repaying the $300,000 mortgage, net proceeds are $500,000 − $300,000 − $34,000 = $166,000." },
    faqs: [
      {
        question: "What is typically deducted from my sale price?",
        answer: "The main deductions are your remaining mortgage balance, which is paid off at closing, and the agent commission, often around five to six percent of the sale price. Other closing costs can include transfer or excise taxes, title insurance, escrow or attorney fees, and any seller concessions or repair credits. Property taxes may be prorated too. This calculator captures the loan payoff, commission, and a combined figure for other closing costs.",
      },
      {
        question: "How much is the real estate agent commission?",
        answer: "Commission is negotiable but has traditionally run around five to six percent of the sale price, usually split between the listing and buyer's agents. On a $500,000 home a 6% commission is $30,000, a substantial sum, which is why the rate is worth discussing with your agent. Recent industry changes have made commissions more openly negotiable, so entering your actual agreed percentage gives the most accurate net proceeds.",
      },
      {
        question: "Does this include capital gains tax?",
        answer: "No. The calculator shows net proceeds before any income or capital gains tax you might owe on the sale. Many primary-home sellers qualify for a large capital gains exclusion, but investment properties and larger gains can trigger tax. Because tax depends on your specific situation, cost basis, and how long you owned the home, treat the net proceeds as pre-tax cash and consult a tax professional to estimate any liability.",
      },
      {
        question: "Can my net proceeds be negative?",
        answer: "Yes. If your sale price does not cover the mortgage balance plus selling costs, the result is negative, meaning you would need to bring cash to closing to complete the sale. This situation, sometimes called being underwater or upside down, happens when a loan exceeds the home's sale value. The calculator will show a negative figure so you can see the shortfall before committing to a sale at that price.",
      },
      {
        question: "How can I increase my net proceeds?",
        answer: "The largest levers are the sale price, the commission rate, and your loan payoff. Negotiating a lower commission, making cost-effective improvements that lift the sale price, and timing the sale after more of the mortgage is paid down all raise net proceeds. Shopping for lower title and closing fees helps at the margin. Running different scenarios in this calculator shows how each change flows through to the cash you actually take home.",
      },
    ],
    relatedCalculators: ["closing-costs-calculator", "loan-to-value-calculator", "down-payment-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    sensitivity: "finance",
    formulaSource: "Standard real estate formula",
  },
];
