import type { CalculatorDefinition } from "../types";

export const scienceMoreCalculators: CalculatorDefinition[] = [
  {
    id: "wavelength",
    slug: "wavelength-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Wavelength Calculator",
    shortDescription: "Find wavelength and period from wave speed and frequency.",
    seoTitle: "Wavelength Calculator — Wave Speed and Frequency to Wavelength",
    metaDescription: "Free wavelength calculator. Enter wave speed and frequency to find wavelength in metres and the wave period in seconds instantly. Ideal for sound, light, and radio problems.",
    primaryKeyword: "wavelength calculator",
    secondaryKeywords: ["wave speed frequency wavelength", "wavelength formula calculator", "frequency to wavelength"],
    fields: [
      { id: "waveSpeed", label: "Wave speed", type: "number", unit: "m/s", required: true, span: 1, min: 0, helpText: "Sound ≈ 340 m/s, light ≈ 3×10⁸ m/s." },
      { id: "frequency", label: "Frequency", type: "number", unit: "Hz", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "wavelength", label: "Wavelength", format: "number", decimals: 4, unit: "m", isPrimary: true },
      { id: "period", label: "Period", format: "number", decimals: 6, unit: "s", isPrimary: false },
    ],
    formula: "wavelength = wave speed ÷ frequency",
    formulaExplanation: "Wavelength equals wave speed divided by frequency because a wave advances exactly one wavelength during each complete cycle, so fitting more cycles into every second at the same speed packs the waves closer together. Frequency and wavelength are therefore inversely related for a fixed speed. The period, the time for one cycle, is simply one divided by frequency, since frequency counts how many cycles occur every second.",
    explanation: "A wavelength is the physical distance between two matching points on a wave — crest to crest, or trough to trough — and this wavelength calculator finds it from the wave speed and the frequency you enter. It also reports the period, the time each full cycle takes. Every wave, whether sound rippling through air, light crossing space, or a ripple on water, obeys the same relationship: the faster it travels or the fewer cycles it completes each second, the longer each wave stretches out.\n\nKnowing wavelength matters across physics and engineering. Radio engineers size antennas to a fraction of a signal's wavelength, musicians and acousticians link pitch to the length of vibrating columns, and optical designers match lenses to the colours of light they must bend. Because the three quantities are locked together, fixing any two determines the wavelength, so the tool removes the division and unit juggling that trip people up.\n\nThe relationship holds because speed equals wavelength times frequency, a direct consequence of a wave advancing one full wavelength during each cycle. Students checking homework, ham-radio operators tuning gear, and researchers working with sound or light all reach for a wavelength calculator to move from a measured speed and frequency to an exact answer.",
    example: { inputs: { waveSpeed: 340, frequency: 170 }, explanation: "340 m/s ÷ 170 Hz = 2 m, and the period is 1 ÷ 170 ≈ 0.0059 s." },
    faqs: [
      {
        question: "What units should I use for wave speed and frequency?",
        answer: "Enter wave speed in metres per second and frequency in hertz, which counts cycles per second, and the wavelength comes out in metres. The period is returned in seconds. If your frequency is given in kilohertz or megahertz, multiply by one thousand or one million first, because keeping every input in base SI units guarantees the wavelength and period both come out correctly without extra scaling.",
      },
      {
        question: "How are wavelength and frequency related?",
        answer: "For a wave travelling at a fixed speed, wavelength and frequency are inversely proportional: as one rises, the other falls. Double the frequency and each wave becomes half as long, because the same speed now has to fit twice as many cycles into every second. This trade-off explains why high-pitched sounds and high-frequency radio signals have short wavelengths while low tones stretch out far longer.",
      },
      {
        question: "What is the period of a wave?",
        answer: "The period is the time it takes a wave to complete one full cycle, measured in seconds, and it is simply the reciprocal of frequency. A wave at two hertz repeats twice each second, so its period is half a second. Period and wavelength describe the same wave from different angles: one in time, the other in space, and both fall out of the frequency you enter.",
      },
      {
        question: "Does this work for both sound and light?",
        answer: "Yes. The wave equation applies to every kind of wave, so you only need the correct speed for your medium. Sound travels at roughly 340 metres per second in air, while light and other electromagnetic waves move at about 300 million metres per second in a vacuum. Enter the appropriate speed for your situation and the calculator returns the matching wavelength and period for sound, light, or water waves.",
      },
      {
        question: "Why does a speed of 340 and frequency of 170 give 2 metres?",
        answer: "Dividing the wave speed by the frequency gives the wavelength, so 340 metres per second divided by 170 hertz equals exactly 2 metres. This is a typical sound-wave example, since 340 metres per second is close to the speed of sound in air. The period works out as one divided by 170, roughly 0.0059 seconds, the time each cycle of that wave takes to pass.",
      },
    ],
    relatedCalculators: ["electric-power-calculator", "kinetic-energy-calculator", "ohms-law-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard physics (wave equation)",
  },
  {
    id: "electric-power",
    slug: "electric-power-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Electric Power Calculator",
    shortDescription: "Find electrical power and resistance from voltage and current.",
    seoTitle: "Electric Power Calculator — Voltage and Current to Watts",
    metaDescription: "Free electric power calculator. Enter voltage and current to find power in watts and the resistance in ohms instantly. Perfect for circuits, devices, and energy use.",
    primaryKeyword: "electric power calculator",
    secondaryKeywords: ["watts calculator", "voltage current power calculator", "electrical power formula"],
    fields: [
      { id: "voltage", label: "Voltage", type: "number", unit: "V", required: true, span: 1 },
      { id: "current", label: "Current", type: "number", unit: "A", required: true, span: 1 },
    ],
    results: [
      { id: "power", label: "Power", format: "number", decimals: 2, unit: "W", isPrimary: true },
      { id: "resistance", label: "Resistance", format: "number", decimals: 2, unit: "Ω", isPrimary: false },
    ],
    formula: "power = voltage × current",
    formulaExplanation: "Power equals voltage multiplied by current because voltage is the energy carried per unit of charge and current is the charge flowing per second, so multiplying them gives energy delivered per second, which is power in watts. Resistance follows from Ohm's law as voltage divided by current, revealing how strongly the component opposes the flow. Together these two results describe both the energy use and the electrical character of the component.",
    explanation: "Electrical power is the rate at which a circuit converts energy into heat, light, or motion, and this electric power calculator finds it directly from the voltage across a component and the current flowing through it. It also returns the resistance implied by those two values, giving a fuller picture of how the component behaves. Power is what your electricity meter measures, what determines whether a wire runs cool or hot, and what a device's rating on its label actually describes.\n\nUnderstanding power matters whenever you size a supply, choose a fuse, or estimate running costs. A phone charger, a kettle, and an electric motor differ mainly in how much power they draw, and getting that figure wrong can mean an overloaded circuit or a component that overheats. Because power is simply voltage multiplied by current, the calculator removes the arithmetic and lets you compare devices at a glance.\n\nThe relationship holds because each coulomb of charge carries an amount of energy set by the voltage, and current counts how many coulombs pass every second, so their product is energy per second — power in watts. Electricians, hobbyists, and students use an electric power calculator to check ratings, plan wiring, and understand exactly how much energy their circuits consume.",
    example: { inputs: { voltage: 12, current: 2 }, explanation: "12 V × 2 A = 24 W, and the resistance is 12 ÷ 2 = 6 Ω." },
    faqs: [
      {
        question: "What units does this calculator use?",
        answer: "Enter voltage in volts and current in amperes, and the power comes out in watts, the SI unit of power. The resistance is returned in ohms. If your current is measured in milliamps, divide by one thousand to convert it to amperes first. Keeping voltage in volts and current in amperes ensures the power reads correctly in watts without any additional scaling on your part.",
      },
      {
        question: "How is electrical power different from energy?",
        answer: "Power is the rate at which energy is used, measured in watts, while energy is the total amount consumed over time, measured in joules or kilowatt-hours. A 100-watt bulb draws energy at a steady rate, and running it for longer uses more energy without changing its power. Your electricity bill charges for energy, so it multiplies each device's power by the hours you run it.",
      },
      {
        question: "Why does the calculator also show resistance?",
        answer: "Resistance is closely tied to power in a circuit, so showing it gives you a fuller picture from the same two inputs. Using Ohm's law, resistance equals voltage divided by current, revealing how strongly the component limits the flow of charge. Knowing resistance alongside power helps you check whether a value looks reasonable and lets you cross-reference results against a resistor's marked rating or a datasheet figure.",
      },
      {
        question: "Can I calculate power without knowing current?",
        answer: "This calculator needs both voltage and current, but if you know voltage and resistance instead, you can find power with the equivalent formula voltage squared divided by resistance. Likewise, current squared times resistance gives power when you know current and resistance. These forms all come from combining the power equation with Ohm's law, so any two of voltage, current, and resistance are enough to determine the power.",
      },
      {
        question: "What happens if the current is zero?",
        answer: "If the current is zero, no charge is flowing, so the power is zero regardless of the voltage present — an open switch delivers no energy. The resistance in that case is undefined, because dividing voltage by zero current has no finite value, so the calculator returns a dash for resistance. A zero-current reading simply means the circuit is open or the component is not conducting.",
      },
    ],
    relatedCalculators: ["ohms-law-calculator", "wavelength-calculator", "gravitational-force-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard physics (electrical power)",
  },
  {
    id: "gravitational-force",
    slug: "gravitational-force-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Gravitational Force Calculator",
    shortDescription: "Find the gravitational attraction between two masses.",
    seoTitle: "Gravitational Force Calculator — Newton's Law of Gravitation",
    metaDescription: "Free gravitational force calculator. Enter two masses and their distance to find the gravitational attraction in newtons using Newton's law of gravitation. Fast and accurate.",
    primaryKeyword: "gravitational force calculator",
    secondaryKeywords: ["newtons law of gravitation calculator", "gravity force calculator", "force between two masses"],
    fields: [
      { id: "mass1", label: "First mass", type: "number", unit: "kg", required: true, span: 1, min: 0 },
      { id: "mass2", label: "Second mass", type: "number", unit: "kg", required: true, span: 1, min: 0 },
      { id: "distance", label: "Distance between centres", type: "number", unit: "m", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "force", label: "Gravitational force", format: "number", decimals: 6, unit: "N", isPrimary: true },
    ],
    formula: "F = G × mass₁ × mass₂ ÷ distance²",
    formulaExplanation: "Newton's law of gravitation multiplies the two masses together, divides by the square of the distance between their centres, and scales the result by the gravitational constant G, about 6.674 times ten to the minus eleven. The masses multiply because each attracts the other, and the distance is squared because gravity weakens over the growing surface of a sphere as it spreads outward from a mass into space.",
    explanation: "Gravitational force is the universal attraction that pulls any two masses toward each other, and this gravitational force calculator finds it from the two masses and the distance separating their centres. From the falling of an apple to the orbits of planets, the same law governs them all: every object with mass tugs on every other, with a strength that grows with the masses and weakens sharply as they move apart.\n\nThis calculation matters far beyond the classroom. It explains why the Moon orbits the Earth, why you weigh slightly less on a mountaintop, and how spacecraft are steered using the pull of distant worlds. Because the force depends on the product of the masses and the square of the distance, small changes in separation have a large effect, which the calculator makes easy to explore without wrestling with the tiny gravitational constant by hand.\n\nThe law works because gravity spreads out over the surface of an expanding sphere, so its strength falls with the square of the distance, while doubling either mass simply doubles the pull. Physics students, astronomy enthusiasts, and engineers planning orbits all rely on a gravitational force calculator to turn masses and a distance into a precise force in newtons using Newton's famous equation.",
    example: { inputs: { mass1: 70, mass2: 5.972e24, distance: 6371000 }, explanation: "A 70 kg person and the Earth (5.972×10²⁴ kg) at its radius of 6,371,000 m attract with about 686.9 N — the person's weight." },
    faqs: [
      {
        question: "What units should I enter?",
        answer: "Use kilograms for both masses and metres for the distance between their centres, and the force comes out in newtons. The gravitational constant built into the calculator assumes these SI units, so mixing in grams or kilometres would throw the result off by large factors. Convert any non-standard units first: one tonne is a thousand kilograms, and one kilometre is a thousand metres, keeping every figure consistent.",
      },
      {
        question: "Why is the gravitational force usually so small?",
        answer: "Gravity is by far the weakest of the fundamental forces, and the gravitational constant is extremely tiny, around 6.674 times ten to the minus eleven. As a result, everyday objects attract each other with forces far too small to feel. Gravity only becomes noticeable when at least one mass is enormous, like a planet or a star, which is why we sense Earth's pull but not a nearby building's.",
      },
      {
        question: "How does distance affect the force?",
        answer: "The force follows an inverse-square law, so it weakens with the square of the distance between the masses. Double the separation and the force drops to a quarter; triple it and the force falls to a ninth. This rapid decline explains why gravity, though infinite in range, becomes negligible over large distances, and why proximity matters so much when comparing the pull between orbiting bodies.",
      },
      {
        question: "Does this measure the distance between surfaces or centres?",
        answer: "Newton's law uses the distance between the centres of mass of the two objects, not the gap between their surfaces. For spherical bodies like planets, the entire mass acts as if concentrated at the centre, so you measure from centre to centre. When finding your weight on Earth, for example, the distance is the planet's radius, not your height above the ground.",
      },
      {
        question: "Can I use this to find my weight?",
        answer: "Yes. Enter your mass, the Earth's mass of about 5.97 times ten to the twenty-fourth kilograms, and the Earth's radius of roughly 6,371,000 metres, and the force returned is your weight in newtons. The result matches multiplying your mass by 9.81, the familiar gravitational acceleration, because that acceleration is itself derived from this same law applied at the Earth's surface.",
      },
    ],
    relatedCalculators: ["kinetic-energy-calculator", "thermal-expansion-calculator", "density-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard physics (Newton's law of gravitation)",
  },
  {
    id: "thermal-expansion",
    slug: "thermal-expansion-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Thermal Expansion Calculator",
    shortDescription: "Find how much a material expands when heated.",
    seoTitle: "Thermal Expansion Calculator — Length Change from Heat",
    metaDescription: "Free thermal expansion calculator. Enter original length, expansion coefficient, and temperature change to find the change in length and new length in metres. Great for engineering.",
    primaryKeyword: "thermal expansion calculator",
    secondaryKeywords: ["linear expansion calculator", "coefficient of thermal expansion", "length change temperature"],
    fields: [
      { id: "originalLength", label: "Original length", type: "number", unit: "m", required: true, span: 1, min: 0 },
      { id: "coefficient", label: "Expansion coefficient", type: "number", unit: "/°C", required: true, span: 1, step: 0.000001, min: 0, helpText: "Steel ≈ 0.000012, aluminium ≈ 0.000023." },
      { id: "tempChange", label: "Temperature change", type: "number", unit: "°C", required: true, span: 2 },
    ],
    results: [
      { id: "expansion", label: "Change in length", format: "number", decimals: 6, unit: "m", isPrimary: true },
      { id: "newLength", label: "New length", format: "number", decimals: 6, unit: "m", isPrimary: false },
    ],
    formula: "ΔL = coefficient × original length × temperature change",
    formulaExplanation: "Linear thermal expansion multiplies the coefficient of expansion by the original length and by the temperature change, because each degree stretches the material by a fixed fraction of its length set by that coefficient. Longer objects therefore move more, and larger temperature swings move them further. Adding this change to the original length gives the new length. The relationship stays accurate as long as the temperature change is moderate and the material behaves uniformly.",
    explanation: "Most materials grow when heated and shrink when cooled, and this thermal expansion calculator finds exactly how much a solid changes length from its original length, its expansion coefficient, and the temperature change. It reports both the change in length and the resulting new length, so you can see the effect of a temperature swing at a glance. This subtle stretching is why bridges have expansion joints, why railway tracks can buckle in a heatwave, and why a stuck metal lid loosens under hot water.\n\nAccounting for expansion matters in almost every branch of engineering. Pipes, power lines, and long spans must be designed with room to move, and precision instruments must compensate so that a warm afternoon does not throw off their readings. Because the change depends on the material, the tool uses a coefficient specific to each substance, letting you compare how steel, aluminium, or glass respond to the same heating.\n\nThe formula works because each degree of temperature change stretches the material by a fixed fraction of its length, set by the coefficient, so longer objects and larger temperature swings both produce proportionally bigger movements. Engineers, machinists, and physics students rely on a thermal expansion calculator to predict clearances, avoid damaging stress, and understand how everyday structures cope with the changing seasons.",
    example: { inputs: { originalLength: 10, coefficient: 0.000012, tempChange: 50 }, explanation: "0.000012 × 10 × 50 = 0.006 m of expansion, so the new length is 10.006 m." },
    faqs: [
      {
        question: "What units should I use?",
        answer: "Enter the original length in metres, the temperature change in degrees Celsius or kelvin, and the coefficient in units of per degree Celsius, which is how expansion coefficients are normally tabulated. The change in length and the new length then come out in metres. Because a Celsius degree and a kelvin are the same size, you can use either scale for the temperature change without affecting the result.",
      },
      {
        question: "Where do I find the expansion coefficient?",
        answer: "Coefficients of linear thermal expansion are published in engineering handbooks and material datasheets for every common substance. Typical values are around 0.000012 per degree Celsius for steel, 0.000023 for aluminium, and 0.000009 for glass. Look up the figure for your specific material and enter it directly. Using an accurate, material-specific coefficient is essential, since even small differences noticeably change the predicted expansion over long lengths.",
      },
      {
        question: "Why do materials expand when heated?",
        answer: "Heating a material makes its atoms vibrate more vigorously, so on average they push slightly further apart, and the whole object grows. Cooling reverses this, drawing the atoms closer and shrinking the material. The expansion coefficient captures how strongly a particular substance responds, since the strength of its atomic bonds sets how far the atoms move for each degree of temperature change applied to it.",
      },
      {
        question: "Does this handle contraction when cooling?",
        answer: "Yes. Enter a negative temperature change to model cooling, and the calculator returns a negative expansion, meaning the material contracts, along with a new length shorter than the original. The same formula covers both directions, because heating and cooling are simply positive and negative temperature changes. This makes the tool useful for predicting how components shrink in cold conditions as well as how they grow in the heat.",
      },
      {
        question: "What is the difference between linear and volumetric expansion?",
        answer: "This calculator handles linear expansion, the change in a single length or dimension. Volumetric expansion describes how an object's whole volume grows, and for a solid its coefficient is roughly three times the linear one, since expansion happens along all three dimensions at once. Use linear expansion for rods, pipes, and rails, and volumetric expansion when you care about the total space a heated body occupies.",
      },
    ],
    relatedCalculators: ["density-calculator", "pressure-volume-calculator", "gravitational-force-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard physics (thermal expansion)",
  },
  {
    id: "pressure-volume",
    slug: "pressure-volume-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Pressure Volume Calculator",
    shortDescription: "Find a gas's new volume using Boyle's law.",
    seoTitle: "Pressure Volume Calculator — Boyle's Law (P₁V₁ = P₂V₂)",
    metaDescription: "Free pressure volume calculator using Boyle's law. Enter initial pressure, initial volume, and final pressure to find the new gas volume instantly. Ideal for chemistry and diving.",
    primaryKeyword: "pressure volume calculator",
    secondaryKeywords: ["boyles law calculator", "p1v1 p2v2 calculator", "gas volume calculator"],
    fields: [
      { id: "pressure1", label: "Initial pressure", type: "number", unit: "atm", required: true, span: 1, min: 0 },
      { id: "volume1", label: "Initial volume", type: "number", unit: "L", required: true, span: 1, min: 0 },
      { id: "pressure2", label: "Final pressure", type: "number", unit: "atm", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "newVolume", label: "New volume", format: "number", decimals: 4, unit: "L", isPrimary: true },
    ],
    formula: "P₁ × V₁ = P₂ × V₂",
    formulaExplanation: "Boyle's law states that pressure times volume stays constant for a fixed amount of gas at constant temperature, so the initial pressure times the initial volume equals the final pressure times the final volume. Rearranging gives the new volume as the initial pressure times the initial volume, divided by the final pressure. Pressure and volume are inversely proportional, because compressing a gas into less space makes its molecules collide with the walls more often.",
    explanation: "Boyle's law describes how the volume of a fixed amount of gas responds to a change in pressure at constant temperature, and this pressure volume calculator applies it to find the new volume from an initial pressure, an initial volume, and a final pressure. Squeeze a gas harder and it shrinks; ease the pressure and it expands, always so that pressure and volume trade off in exact proportion. It is the principle behind a syringe, a bicycle pump, and the way your lungs draw air.\n\nThis relationship matters in chemistry, medicine, diving, and engineering alike. Anaesthetists track gas volumes as pressures change, divers must understand how air in their lungs and equipment behaves at depth, and engineers designing pneumatic systems rely on it constantly. Because pressure and volume are inversely linked, the calculator lets you predict one from the other without repeatedly rearranging the equation by hand.\n\nThe law works because, at a fixed temperature, squeezing a gas into a smaller space makes its molecules strike the walls more often, raising the pressure in exact inverse proportion to the volume. Students, divers, and lab technicians use a pressure volume calculator to model how gases behave under changing pressure and to solve Boyle's law problems quickly and reliably.",
    example: { inputs: { pressure1: 2, volume1: 3, pressure2: 6 }, explanation: "2 × 3 = 6, so the new volume is 6 ÷ 6 = 1 L — tripling the pressure cuts the volume to a third." },
    faqs: [
      {
        question: "What units should I use for pressure and volume?",
        answer: "You can use any units you like for pressure and volume, as long as you are consistent, because Boyle's law depends only on ratios. If the two pressures are in atmospheres and the initial volume is in litres, the new volume comes out in litres. Common choices are atmospheres, pascals, or bar for pressure and litres or cubic metres for volume; just keep both pressures in the same unit.",
      },
      {
        question: "Does temperature need to stay constant?",
        answer: "Yes. Boyle's law only holds when the temperature and the amount of gas stay fixed. If the temperature changes as well, you need the combined gas law or the ideal gas law, which account for temperature and moles too. In practice, keep the process slow enough for heat to equalise, or ensure the gas returns to the same temperature, so that pressure and volume trade off cleanly as the law assumes.",
      },
      {
        question: "Why are pressure and volume inversely related?",
        answer: "At a constant temperature, the gas molecules move at the same average speed no matter the container size. Compressing the gas into a smaller volume packs the molecules closer, so they strike the walls more frequently and the pressure rises. Expanding the gas does the opposite. This trade-off keeps the product of pressure and volume constant, which is exactly what Boyle's law expresses in a single simple equation.",
      },
      {
        question: "What does the example with 2, 3, and 6 show?",
        answer: "Starting with a pressure of 2 and a volume of 3, the product is 6. Raising the final pressure to 6 forces the volume down to 1, because 6 times 1 also equals 6, keeping the pressure-volume product constant. Tripling the pressure has cut the volume to a third, a clear illustration of the inverse relationship at the heart of Boyle's law.",
      },
      {
        question: "Where does Boyle's law apply in real life?",
        answer: "Boyle's law appears wherever gases are compressed or expanded at steady temperature. It explains how a syringe draws fluid, how a bicycle pump forces air into a tyre, and how scuba divers must exhale as they rise so expanding lung air does not injure them. Weather balloons, pneumatic tools, and internal combustion engines all rely on the same predictable trade-off between a gas's pressure and its volume.",
      },
    ],
    relatedCalculators: ["thermal-expansion-calculator", "density-calculator", "wavelength-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard physics (Boyle's law)",
  },
];
