import type { CalculatorDefinition } from "../types";

export const scienceR5Calculators: CalculatorDefinition[] = [
  {
    id: "molarity",
    slug: "molarity-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Molarity Calculator",
    shortDescription: "Find solution concentration from moles and volume.",
    seoTitle: "Molarity Calculator — Moles per Litre Concentration",
    metaDescription: "Free molarity calculator. Enter moles of solute and solution volume in litres to find molar concentration instantly in mol/L. Perfect for chemistry lab work and homework.",
    primaryKeyword: "molarity calculator",
    secondaryKeywords: ["molar concentration calculator", "moles per litre calculator", "solution concentration calculator"],
    fields: [
      { id: "moles", label: "Moles of solute", type: "number", unit: "mol", required: true, span: 1, min: 0 },
      { id: "volumeLiters", label: "Solution volume", type: "number", unit: "L", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "molarity", label: "Molarity", format: "number", decimals: 4, unit: "mol/L", isPrimary: true },
    ],
    formula: "M = moles ÷ volume (L)",
    formulaExplanation: "Molarity expresses concentration as the number of moles of solute dissolved in each litre of solution, so dividing total moles by total volume gives the amount of substance packed into a unit of liquid. The formula works because moles count the actual number of particles present while litres measure the space they occupy, and their ratio stays fixed for a well-mixed homogeneous solution. That constant ratio is what lets chemists scale a recipe up or down while keeping reactivity the same.",
    explanation: "Molarity is the workhorse concentration unit of chemistry, and this molarity calculator returns it instantly from the moles of solute and the volume of solution you enter. Reported in moles per litre, molarity tells you exactly how many particles of a dissolved substance sit in each litre of liquid, which is the figure most reactions, titrations, and dilution problems demand.\n\nUnderstanding molarity matters because reaction stoichiometry is counted in particles, not grams. Two solutions of equal molarity contain the same number of reactive units per litre even when their masses differ wildly, so a chemist reaching for a molarity calculator can predict how much of one reagent will neutralise or combine with another. It underpins everything from preparing a buffer to dosing a reagent in industry.\n\nThe formula works because molarity is simply moles divided by litres, an intensive ratio that stays constant no matter how much solution you scoop out. Students, lab technicians, pharmacists, and researchers all rely on a molarity calculator to prepare standard solutions accurately, avoid arithmetic slips, and move quickly between concentration, volume, and amount of substance when planning an experiment.",
    example: { inputs: { moles: 2, volumeLiters: 4 }, explanation: "2 mol ÷ 4 L = 0.5 mol/L, a 0.5 M solution." },
    faqs: [
      {
        question: "What units should I enter for moles and volume?",
        answer: "Enter the amount of solute in moles and the total solution volume in litres, and the result comes out directly in moles per litre, the standard unit of molarity. If your volume is in millilitres, divide by 1,000 first, because 1,000 mL equals one litre. Keeping to moles and litres guarantees the concentration figure matches the values printed on reagent bottles and textbook tables.",
      },
      {
        question: "How do I convert grams of solute into moles?",
        answer: "Divide the mass in grams by the substance's molar mass in grams per mole, which you read off the periodic table by summing the atomic masses in the formula. For example, sodium chloride has a molar mass near 58.44 g/mol, so 58.44 g equals one mole. Once you have moles, enter that figure here along with the volume to obtain molarity.",
      },
      {
        question: "What is the difference between molarity and molality?",
        answer: "Molarity divides moles of solute by litres of solution, while molality divides moles of solute by kilograms of solvent. Molarity is easier to measure with volumetric glassware but shifts slightly with temperature because liquids expand. Molality ignores temperature entirely since mass does not change. For most bench chemistry and titrations, molarity is the practical choice this calculator provides.",
      },
      {
        question: "Why does molarity change when I add more water?",
        answer: "Adding water increases the solution volume while the number of moles of solute stays the same, so the ratio of moles to litres falls and the solution becomes more dilute. This is the basis of the dilution equation M1V1 = M2V2. If you want a specific target molarity, calculate the final volume needed and top up carefully to that mark.",
      },
      {
        question: "Can molarity be greater than one?",
        answer: "Yes. A molarity above one simply means more than one mole of solute is dissolved per litre of solution, which is common for concentrated acids and stock reagents. Concentrated hydrochloric acid, for instance, is around 12 M. The upper limit is set by the substance's solubility, the point at which no more solute will dissolve and any excess settles out as solid.",
      },
    ],
    relatedCalculators: ["density-calculator", "ph-calculator", "ohms-law-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard chemistry (molar concentration)",
  },
  {
    id: "half-life",
    slug: "half-life-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Half-Life Calculator",
    shortDescription: "Find the amount remaining after radioactive decay.",
    seoTitle: "Half-Life Calculator — Radioactive Decay Remaining Amount",
    metaDescription: "Free half-life calculator. Enter the initial amount, half-life, and elapsed time to find how much substance remains and the percentage left after decay.",
    primaryKeyword: "half life calculator",
    secondaryKeywords: ["radioactive decay calculator", "half life decay formula", "remaining amount calculator"],
    fields: [
      { id: "initialAmount", label: "Initial amount", type: "number", required: true, span: 2, min: 0, helpText: "Any unit — grams, atoms, becquerels. The answer keeps the same unit." },
      { id: "halfLifeValue", label: "Half-life", type: "number", required: true, span: 1, min: 0, helpText: "Use the same time unit for both fields." },
      { id: "elapsedTime", label: "Elapsed time", type: "number", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "remaining", label: "Amount remaining", format: "number", decimals: 4, isPrimary: true },
      { id: "fractionRemaining", label: "Fraction remaining", format: "percentage", decimals: 2, isPrimary: false },
    ],
    formula: "N = N₀ × 0.5^(t ÷ t½)",
    formulaExplanation: "Radioactive decay is a first-order process, meaning a fixed fraction of the remaining atoms decays in every equal interval rather than a fixed number. The half-life is the interval over which exactly half of whatever is present decays, so after each half-life the quantity is multiplied by one half again. Raising 0.5 to the power of the number of half-lives elapsed, t divided by t½, captures this repeated halving continuously, which is why the amount left falls along a smooth exponential curve instead of dropping in steps.",
    explanation: "Half-life describes how quickly an unstable substance decays, and this half-life calculator tells you exactly how much is left after a given time. Enter the initial amount, the half-life of the isotope, and the elapsed time in the same time unit, and it returns both the remaining quantity and the percentage of the original that survives.\n\nHalf-life matters far beyond nuclear physics. It sets the timeline for carbon dating ancient artefacts, dictates how long a medical tracer stays active in the body, governs the storage of radioactive waste, and even models how a drug concentration falls between doses. Because decay is exponential rather than linear, intuition often misleads people, so a half-life calculator keeps the maths honest.\n\nThe formula works because each half-life multiplies the remaining amount by one half, and the elapsed time divided by the half-life counts how many of those halvings have occurred. After one half-life, half remains; after two, a quarter; after three, an eighth, and so on along a smooth exponential curve. Students, chemists, radiologists, and archaeologists all use a half-life calculator to turn an isotope's decay constant into a concrete, usable answer.",
    example: { inputs: { initialAmount: 100, halfLifeValue: 5, elapsedTime: 15 }, explanation: "After 3 half-lives (15 ÷ 5), 100 × 0.5³ = 12.5 units remain, or 12.5%." },
    faqs: [
      {
        question: "Do the half-life and elapsed time need the same units?",
        answer: "Yes, and this is the most common mistake. Both the half-life and the elapsed time must be expressed in the same unit of time, whether seconds, days, or years, because the formula only uses their ratio. If the half-life is 8 days, enter the elapsed time in days too. Mixing units, such as a half-life in years with a time in days, produces a wildly wrong result.",
      },
      {
        question: "What unit is the remaining amount reported in?",
        answer: "The remaining amount keeps whatever unit you used for the initial amount, because the formula multiplies by a pure fraction. Enter grams and you get grams back; enter number of atoms or becquerels of activity and the answer stays in those units. The separate percentage output is unit-free and simply tells you what fraction of the original quantity still survives after the elapsed time.",
      },
      {
        question: "Why does the substance never fully disappear?",
        answer: "Exponential decay halves the remaining amount in each half-life but never reaches exactly zero, because half of any positive quantity is still positive. In theory a trace always lingers. In practice, after roughly ten half-lives less than 0.1% remains, which is usually treated as effectively gone. This is why safe-storage guidance for radioactive waste is often quoted as about ten half-lives.",
      },
      {
        question: "Can I use this calculator for drug dosing or medicine?",
        answer: "The same exponential model describes how many drugs clear from the bloodstream, so the biological half-life predicts how a concentration falls between doses. However, real pharmacology involves absorption, distribution, and individual metabolism that this simple calculator does not model. Use it to understand the concept, but always follow a clinician's dosing instructions and never adjust medication based on a general decay estimate.",
      },
      {
        question: "How is half-life related to the decay constant?",
        answer: "The half-life and the decay constant λ are two ways of describing the same rate. They are linked by t½ = ln(2) ÷ λ, where ln(2) is about 0.693. A larger decay constant means faster decay and a shorter half-life. This calculator works directly from the half-life, which is usually the value quoted in reference tables, so you do not need the decay constant.",
      },
    ],
    relatedCalculators: ["ph-calculator", "density-calculator", "kinetic-energy-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (exponential radioactive decay law)",
  },
  {
    id: "potential-energy",
    slug: "potential-energy-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Potential Energy Calculator",
    shortDescription: "Gravitational potential energy from mass and height.",
    seoTitle: "Potential Energy Calculator — Gravitational PE (mgh)",
    metaDescription: "Free gravitational potential energy calculator. Enter mass, height, and gravity to find potential energy in joules using PE = mgh. Ideal for physics homework.",
    primaryKeyword: "potential energy calculator",
    secondaryKeywords: ["gravitational potential energy calculator", "mgh calculator", "pe formula calculator"],
    fields: [
      { id: "mass", label: "Mass", type: "number", unit: "kg", required: true, span: 1, min: 0 },
      { id: "height", label: "Height", type: "number", unit: "m", required: true, span: 1, min: 0 },
      { id: "gravity", label: "Gravity", type: "number", unit: "m/s²", required: false, span: 2, defaultValue: 9.81, helpText: "Defaults to Earth's 9.81 m/s². Use 1.62 for the Moon, 3.71 for Mars." },
    ],
    results: [
      { id: "potentialEnergy", label: "Potential energy", format: "number", decimals: 2, unit: "J", isPrimary: true },
    ],
    formula: "PE = m × g × h",
    formulaExplanation: "Gravitational potential energy is the work done against gravity to lift an object, and work equals force times distance. The downward force of gravity on a mass is m times g, so raising it through a height h stores exactly m·g·h joules of energy. The formula works because the gravitational field near Earth's surface is effectively uniform, making the force constant over the lift, so the energy stored grows in direct proportion to both the mass raised and the height it is raised through.",
    explanation: "Potential energy is the energy an object stores because of its position in a gravitational field, and this potential energy calculator finds it from the mass, the height, and the strength of gravity. It uses the classic PE = mgh relationship and reports the result in joules, the SI unit of energy.\n\nGravitational potential energy matters because it converts directly into other forms. A raised weight in a grandfather clock, water held behind a hydroelectric dam, and a roller-coaster car at the top of a hill all bank potential energy that becomes kinetic energy as they descend. Estimating that stored energy is essential for engineers sizing a dam, physics students solving conservation-of-energy problems, and anyone analysing how much work it takes to lift a load.\n\nThe formula works because lifting an object against gravity does work equal to the constant gravitational force, m times g, multiplied by the height climbed. Doubling either the mass or the height doubles the stored energy. By letting you change the gravity value, this potential energy calculator also handles the Moon, Mars, or any other body, so you can compare how much energy the same lift stores in different gravitational environments.",
    example: { inputs: { mass: 2, height: 10, gravity: 9.81 }, explanation: "2 kg × 9.81 m/s² × 10 m = 196.2 J of stored energy." },
    faqs: [
      {
        question: "What value of gravity should I use?",
        answer: "For everyday problems on Earth, use 9.81 m/s², the standard average surface gravity, which is already the default. On the Moon use about 1.62 m/s², on Mars about 3.71 m/s², and on Jupiter roughly 24.79 m/s². Changing this field lets the same mass and height give different stored energy, which is why potential energy depends on the gravitational environment, not just the object.",
      },
      {
        question: "Where is the height measured from?",
        answer: "Height is measured from whatever reference level you choose to call zero, usually the ground, a tabletop, or the lowest point of the motion. Potential energy is always relative to that reference, so only differences in height carry physical meaning. As long as you are consistent about where zero sits, the change in potential energy between two positions comes out correctly.",
      },
      {
        question: "Why is potential energy measured in joules?",
        answer: "The joule is the SI unit of energy, defined as one newton of force acting over one metre. Because PE = mgh multiplies a mass in kilograms by an acceleration in metres per second squared and a height in metres, the units combine to kilogram-metres-squared per second-squared, which is exactly a joule. Keeping your inputs in kilograms and metres therefore returns energy directly in joules.",
      },
      {
        question: "How does potential energy relate to kinetic energy?",
        answer: "When an object falls, its potential energy converts into kinetic energy while total mechanical energy stays constant, ignoring air resistance. At the top of a drop the energy is all potential; at the bottom it is all kinetic. This is the principle of conservation of energy, and it lets you find the speed at the bottom by setting mgh equal to one-half m v squared.",
      },
      {
        question: "Does the mgh formula work for very tall heights?",
        answer: "The mgh formula assumes gravity is constant, which holds well near a planet's surface but breaks down over very large heights, such as satellite orbits, where gravity weakens with distance. For those cases physicists use the more general gravitational potential energy formula involving the inverse of distance. For buildings, hills, and everyday lifts, mgh is accurate and this calculator is appropriate.",
      },
    ],
    relatedCalculators: ["kinetic-energy-calculator", "force-calculator", "gravitational-force-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (gravitational potential energy)",
  },
  {
    id: "momentum",
    slug: "momentum-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Momentum Calculator",
    shortDescription: "Calculate linear momentum from mass and velocity.",
    seoTitle: "Momentum Calculator — Linear Momentum (p = mv)",
    metaDescription: "Free momentum calculator. Enter mass and velocity to find linear momentum in kilogram-metres per second using p = mv. Perfect for physics homework and collisions.",
    primaryKeyword: "momentum calculator",
    secondaryKeywords: ["linear momentum calculator", "p=mv calculator", "mass velocity momentum"],
    fields: [
      { id: "mass", label: "Mass", type: "number", unit: "kg", required: true, span: 1, min: 0 },
      { id: "velocity", label: "Velocity", type: "number", unit: "m/s", required: true, span: 1, helpText: "Can be negative to indicate the opposite direction." },
    ],
    results: [
      { id: "momentum", label: "Momentum", format: "number", decimals: 2, unit: "kg·m/s", isPrimary: true },
    ],
    formula: "p = m × v",
    formulaExplanation: "Momentum is the quantity of motion an object carries, defined as its mass multiplied by its velocity, so a heavier or faster object has more of it. The formula works because momentum measures how much effort is needed to stop the object, and that effort scales with both how much matter is moving and how fast it moves. Because velocity is a vector, momentum has direction too, which is why a sign or direction accompanies the number and why momentum is conserved in collisions.",
    explanation: "Momentum captures how much motion an object carries, and this momentum calculator finds it by multiplying mass by velocity. The result, reported in kilogram-metres per second, tells you how hard the object would be to stop and how much punch it delivers in a collision.\n\nMomentum matters because it is conserved: in any collision or explosion with no outside forces, the total momentum before equals the total momentum after. That single principle lets physicists and engineers predict the outcome of car crashes, rocket launches, billiard-ball collisions, and recoiling firearms without tracking every internal force. A momentum calculator turns raw mass and velocity figures into the conserved quantity that makes those predictions possible.\n\nThe formula works because momentum is the product of how much matter is moving and how fast it moves, so doubling either the mass or the velocity doubles the momentum. Velocity is a vector, so momentum has direction as well as size; entering a negative velocity here represents motion in the opposite direction, which is essential when adding the momenta of objects moving toward each other. Students, crash analysts, and sports scientists all reach for a momentum calculator to quantify motion precisely.",
    example: { inputs: { mass: 3, velocity: 4 }, explanation: "3 kg × 4 m/s = 12 kg·m/s of momentum." },
    faqs: [
      {
        question: "What units does the momentum result use?",
        answer: "With mass in kilograms and velocity in metres per second, momentum comes out in kilogram-metres per second, the SI unit. There is no separate named unit for momentum as there is for force or energy. If your velocity is in kilometres per hour, convert it to metres per second first by dividing by 3.6, so that the momentum figure is expressed in the standard SI combination.",
      },
      {
        question: "Why can velocity and momentum be negative?",
        answer: "Velocity is a vector, meaning it has direction, and momentum inherits that direction. A negative value simply indicates motion opposite to whatever you chose as the positive direction. This sign is crucial in collision problems: two objects moving toward each other carry momenta of opposite sign, and adding them, respecting the signs, gives the correct total momentum of the system before impact.",
      },
      {
        question: "How is momentum different from kinetic energy?",
        answer: "Both describe motion but differently. Momentum equals mass times velocity and is a vector conserved in every collision. Kinetic energy equals one-half mass times velocity squared, is a scalar, and is only conserved in perfectly elastic collisions. Because kinetic energy depends on velocity squared, doubling speed quadruples energy but only doubles momentum, so the two quantities respond differently to changes in speed.",
      },
      {
        question: "What does conservation of momentum mean?",
        answer: "Conservation of momentum states that when no external force acts on a system, its total momentum stays constant no matter what happens inside it. In a collision, the combined momentum of all objects before impact equals the combined momentum afterward. This lets you solve for an unknown final velocity, and it explains rocket propulsion, recoil, and the way pool balls transfer motion on impact.",
      },
      {
        question: "Does a stationary object have momentum?",
        answer: "No. If velocity is zero, then mass times velocity is zero, so a stationary object has no momentum regardless of how heavy it is. Momentum exists only while something moves. This is why a parked truck exerts no impact force from motion, yet the same truck at highway speed carries enormous momentum that takes a large force acting over time to stop.",
      },
    ],
    relatedCalculators: ["kinetic-energy-calculator", "force-calculator", "gravitational-force-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (linear momentum)",
  },
  {
    id: "acceleration",
    slug: "acceleration-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Acceleration Calculator",
    shortDescription: "Find acceleration from change in velocity over time.",
    seoTitle: "Acceleration Calculator — Change in Velocity Over Time",
    metaDescription: "Free acceleration calculator. Enter initial velocity, final velocity, and time to find acceleration in metres per second squared. Perfect for physics homework.",
    primaryKeyword: "acceleration calculator",
    secondaryKeywords: ["average acceleration calculator", "velocity time acceleration", "change in velocity calculator"],
    fields: [
      { id: "initialVelocity", label: "Initial velocity", type: "number", unit: "m/s", required: true, span: 1 },
      { id: "finalVelocity", label: "Final velocity", type: "number", unit: "m/s", required: true, span: 1 },
      { id: "time", label: "Time taken", type: "number", unit: "s", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "acceleration", label: "Acceleration", format: "number", decimals: 3, unit: "m/s²", isPrimary: true },
    ],
    formula: "a = (v_f − v_i) ÷ t",
    formulaExplanation: "Acceleration is the rate at which velocity changes, so it equals the change in velocity divided by the time taken for that change. Subtracting the initial velocity from the final velocity gives how much the speed changed, and dividing by the elapsed time spreads that change evenly across the interval to give the average acceleration. The formula works because acceleration is defined as the slope of the velocity-time graph, and over any interval that slope is simply the rise in velocity over the run in time.",
    explanation: "Acceleration measures how quickly an object's velocity changes, and this acceleration calculator finds it from the starting velocity, the final velocity, and the time the change took. The answer, in metres per second squared, tells you how many metres per second the object gains or loses each second.\n\nAcceleration is central to almost every motion problem. It links force to motion through Newton's second law, F = ma, so knowing an object's acceleration lets you find the force acting on it or predict how its speed evolves. Car makers quote nought-to-sixty times, which are acceleration figures; engineers design brakes around deceleration; and physics students use acceleration to connect the equations of motion. A quick acceleration calculator removes the arithmetic and the sign errors.\n\nThe formula works because acceleration is defined as the change in velocity divided by the time over which it happens. A positive result means the object is speeding up in the direction of motion, while a negative result signals deceleration or acceleration in the opposite direction. Because velocities can be negative, this acceleration calculator handles objects that reverse direction too, making it a reliable tool for homework, lab reports, and real-world motion analysis alike.",
    example: { inputs: { initialVelocity: 0, finalVelocity: 20, time: 4 }, explanation: "(20 − 0) ÷ 4 = 5 m/s²; the object gains 5 m/s of speed every second." },
    faqs: [
      {
        question: "What does a negative acceleration mean?",
        answer: "A negative acceleration means the velocity is decreasing in the direction you defined as positive, commonly called deceleration or braking. It can also mean the object is accelerating in the opposite direction. The sign always depends on your chosen positive direction, so a car slowing down while moving forward shows negative acceleration, as does one speeding up while moving backward. Context tells you which situation applies.",
      },
      {
        question: "Why is acceleration measured in metres per second squared?",
        answer: "Acceleration is a change in velocity, measured in metres per second, divided by time, measured in seconds. Dividing metres per second by seconds gives metres per second per second, written metres per second squared. This unit tells you how many metres per second of speed the object gains during each second. Earth's gravity, for reference, produces an acceleration of about 9.81 m/s² on falling objects.",
      },
      {
        question: "Is this average or instantaneous acceleration?",
        answer: "This calculator gives average acceleration over the whole time interval, because it uses the total change in velocity divided by the total time. If the acceleration was constant throughout, the average equals the instantaneous value at every moment. If the acceleration varied, the result is the single steady value that would have produced the same overall change in velocity across that interval.",
      },
      {
        question: "How do I find the force from acceleration?",
        answer: "Use Newton's second law, F = m × a, multiplying the object's mass in kilograms by the acceleration you calculated here. The result is the net force in newtons required to produce that acceleration. This is one of the most useful links in mechanics, connecting the kinematics of motion to the dynamics of the forces causing it, and it works in any consistent set of units.",
      },
      {
        question: "What if the time entered is zero?",
        answer: "If the time is zero the calculation is undefined, because you cannot divide a change in velocity by zero time; the calculator returns a dash to signal this. Physically, an instantaneous change in velocity would require infinite acceleration and infinite force, which is impossible. Enter the actual non-zero duration over which the velocity changed to obtain a meaningful average acceleration value.",
      },
    ],
    relatedCalculators: ["force-calculator", "kinetic-energy-calculator", "gravitational-force-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (kinematics, average acceleration)",
  },
  {
    id: "ideal-gas",
    slug: "ideal-gas-law-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Ideal Gas Law Calculator",
    shortDescription: "Find moles of gas from pressure, volume, temperature.",
    seoTitle: "Ideal Gas Law Calculator — Moles from PV = nRT",
    metaDescription: "Free ideal gas law calculator. Enter pressure in atm, volume in litres, and temperature in kelvin to find the moles of gas using PV = nRT. Great for chemistry.",
    primaryKeyword: "ideal gas law calculator",
    secondaryKeywords: ["pv=nrt calculator", "moles of gas calculator", "gas law calculator"],
    fields: [
      { id: "pressure", label: "Pressure", type: "number", unit: "atm", required: true, span: 1, min: 0 },
      { id: "volume", label: "Volume", type: "number", unit: "L", required: true, span: 1, min: 0 },
      { id: "temperature", label: "Temperature", type: "number", unit: "K", required: true, span: 2, min: 0, helpText: "Absolute temperature in kelvin. Add 273.15 to a Celsius value." },
    ],
    results: [
      { id: "moles", label: "Amount of gas", format: "number", decimals: 4, unit: "mol", isPrimary: true },
    ],
    formula: "n = (P × V) ÷ (R × T),  R = 0.082057 L·atm/(mol·K)",
    formulaExplanation: "The ideal gas law, PV = nRT, ties together the pressure, volume, temperature, and amount of a gas through the universal gas constant R. Rearranging to n = PV ÷ RT isolates the number of moles, because the product of pressure and volume measures the total energy the gas exerts on its surroundings, while RT measures the energy carried per mole at that temperature. Dividing one by the other counts how many moles are present. The law works because an ideal gas is modelled as many tiny non-interacting particles in constant random motion.",
    explanation: "The ideal gas law is the master equation of gas behaviour, and this ideal gas law calculator uses it to find how many moles of gas fill a container from the pressure, volume, and temperature you measure. It applies the constant R equal to 0.082057 litre-atmospheres per mole-kelvin, so with pressure in atmospheres, volume in litres, and temperature in kelvin, the answer comes out in moles.\n\nThe ideal gas law matters because it links four quantities that are otherwise hard to relate. Given any three, you can find the fourth, which is why chemists use it to work out reaction yields, engineers use it to size pressure vessels, and meteorologists use it to model the atmosphere. Rearranged as n = PV divided by RT, it turns easily measured bulk properties into the amount of substance present, a figure you cannot read off a gauge directly.\n\nThe law works because an ideal gas is treated as countless tiny particles that neither attract nor repel and occupy negligible volume. Under everyday conditions of moderate pressure and temperature well above the boiling point, real gases follow it closely. A good ideal gas law calculator therefore gives accurate results for classroom problems and many practical situations, only losing accuracy at very high pressures or very low temperatures where gases start to condense.",
    example: { inputs: { pressure: 1, volume: 22.414, temperature: 273.15 }, explanation: "At standard temperature and pressure, (1 × 22.414) ÷ (0.082057 × 273.15) ≈ 1 mol." },
    faqs: [
      {
        question: "Why must temperature be in kelvin?",
        answer: "The ideal gas law requires absolute temperature, measured from absolute zero, because pressure and volume are proportional to the true thermal energy of the particles. The Celsius and Fahrenheit scales have arbitrary zero points that would break that proportionality and even allow negative values. Convert Celsius to kelvin by adding 273.15. Using kelvin ensures a doubling of temperature genuinely doubles the associated pressure or volume.",
      },
      {
        question: "What value of the gas constant does this use?",
        answer: "This calculator uses R equal to 0.082057 litre-atmospheres per mole-kelvin, which matches inputs given in atmospheres, litres, and kelvin. The gas constant takes different numerical values in other unit systems, such as 8.314 joules per mole-kelvin when using pascals and cubic metres. Sticking to the atmospheres, litres, and kelvin combination this tool expects guarantees the moles result is correct.",
      },
      {
        question: "How do I convert other pressure units to atmospheres?",
        answer: "One atmosphere equals 101.325 kilopascals, 760 millimetres of mercury, or 14.696 pounds per square inch. To convert, divide your pressure by the appropriate factor: kilopascals divided by 101.325, or millimetres of mercury divided by 760, gives atmospheres. Entering pressure in atmospheres keeps it consistent with the gas constant this calculator uses, so the moles figure comes out accurately.",
      },
      {
        question: "When does the ideal gas law break down?",
        answer: "The ideal gas law assumes particles have no volume and do not interact, which holds well at low pressure and high temperature. It becomes inaccurate at very high pressures, where particle volume matters, and at low temperatures near condensation, where attractive forces dominate. For those conditions scientists use real-gas equations such as the van der Waals equation. For most everyday chemistry, the ideal approximation is excellent.",
      },
      {
        question: "Can I rearrange this to find pressure or volume instead?",
        answer: "Yes, the same law rearranges to solve for any variable. This calculator solves for moles, but PV = nRT can be rewritten as P = nRT ÷ V or V = nRT ÷ P when you know the other quantities. The relationships behind the gas laws, such as Boyle's and Charles's laws, are all special cases of this single equation with one variable held constant.",
      },
    ],
    relatedCalculators: ["density-calculator", "molarity-calculator", "ph-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard chemistry (ideal gas law, PV = nRT)",
  },
  {
    id: "projectile-motion",
    slug: "projectile-motion-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Projectile Motion Calculator",
    shortDescription: "Range, height, and flight time of a projectile.",
    seoTitle: "Projectile Motion Calculator — Range, Height, Flight Time",
    metaDescription: "Free projectile motion calculator. Enter launch speed and angle to find the range, maximum height, and time of flight of a projectile. Perfect for physics homework.",
    primaryKeyword: "projectile motion calculator",
    secondaryKeywords: ["projectile range calculator", "launch angle calculator", "trajectory calculator"],
    fields: [
      { id: "initialVelocity", label: "Launch speed", type: "number", unit: "m/s", required: true, span: 1, min: 0 },
      { id: "angleDegrees", label: "Launch angle", type: "number", unit: "°", required: true, span: 1, min: 0, max: 90 },
      { id: "gravity", label: "Gravity", type: "number", unit: "m/s²", required: false, span: 2, defaultValue: 9.81, helpText: "Defaults to Earth's 9.81 m/s². Assumes level ground and no air resistance." },
    ],
    results: [
      { id: "range", label: "Horizontal range", format: "number", decimals: 2, unit: "m", isPrimary: true },
      { id: "maxHeight", label: "Maximum height", format: "number", decimals: 2, unit: "m", isPrimary: false },
      { id: "flightTime", label: "Time of flight", format: "duration", decimals: 2, isPrimary: false },
    ],
    formula: "Range = v²·sin(2θ)/g · Height = v²·sin²θ/(2g) · Time = 2v·sinθ/g",
    formulaExplanation: "A projectile launched over level ground follows a parabola because gravity accelerates it downward while its horizontal speed stays constant. Splitting the launch velocity into horizontal and vertical components with sine and cosine lets each direction be handled separately. The vertical motion sets how long the projectile stays airborne and how high it climbs, while the constant horizontal component carried over that time sets the range. Combining the two yields the compact formulas above, which is why the maximum range occurs at a launch angle of forty-five degrees.",
    explanation: "Projectile motion describes the curved path of anything thrown, launched, or fired near Earth's surface, and this projectile motion calculator finds its three key measurements: how far it travels, how high it climbs, and how long it stays in the air. Enter the launch speed and angle, and the tool splits the motion into horizontal and vertical parts to solve each.\n\nProjectile motion matters across sport, engineering, and defence. It governs the arc of a basketball, the reach of a water fountain, the flight of a golf ball, and the trajectory of a launched rocket in its early phase. Because horizontal and vertical motion are independent, a single set of formulas covers them all, and a projectile motion calculator applies those formulas instantly without tedious trigonometry.\n\nThe calculator assumes level ground and ignores air resistance, the standard idealisation taught in introductory physics. Under those conditions the path is a perfect parabola, and the maximum range for a given speed occurs at a launch angle of forty-five degrees. The vertical component of velocity determines the time aloft and the peak height, while the constant horizontal component carried over that time sets the range. Students, coaches, and engineers use a projectile motion calculator to predict trajectories, compare launch angles, and understand why steeper or flatter shots behave the way they do.",
    example: { inputs: { initialVelocity: 20, angleDegrees: 45, gravity: 9.81 }, explanation: "At 20 m/s and 45°, the range is about 40.77 m, the peak height about 10.19 m, and the flight time about 2.88 s." },
    faqs: [
      {
        question: "Why is 45 degrees the angle for maximum range?",
        answer: "The range depends on sin(2θ), which reaches its largest value of one when 2θ equals 90 degrees, meaning θ is 45 degrees. At that angle the launch speed is shared most effectively between climbing high enough to stay airborne and moving forward fast. Steeper angles gain height but sacrifice horizontal reach, while flatter angles move quickly forward but fall back to the ground too soon.",
      },
      {
        question: "Does this calculator account for air resistance?",
        answer: "No. This calculator uses the idealised model taught in introductory physics, which assumes no air resistance and level ground, producing a perfectly symmetric parabolic path. Real projectiles experience drag that shortens the range, lowers the peak, and skews the trajectory, especially for light or fast objects. The results here are accurate for dense, slow projectiles and for understanding the underlying principles, but treat them as upper-limit estimates.",
      },
      {
        question: "What happens at a launch angle of 90 degrees?",
        answer: "At 90 degrees the projectile is fired straight up, so sin(2θ) becomes zero and the horizontal range is zero; it goes up and comes straight back down. Meanwhile the maximum height and flight time reach their largest values because all the launch speed goes into vertical motion. This is a useful check on the formulas and matches the intuition of throwing a ball directly upward.",
      },
      {
        question: "Are complementary angles giving the same range a coincidence?",
        answer: "No, it follows directly from the mathematics. Because sin(2θ) equals sin(180 − 2θ), two launch angles that add up to 90 degrees, such as 30 and 60 degrees, produce identical ranges at the same speed. The higher angle simply trades a longer, taller flight for the same horizontal distance. This complementary-angle property is a classic result of the projectile range formula.",
      },
      {
        question: "How do I change the calculator for the Moon or Mars?",
        answer: "Edit the gravity field. Earth's default is 9.81 m/s², but the Moon's surface gravity is about 1.62 m/s² and Mars is about 3.71 m/s². Weaker gravity keeps a projectile aloft far longer and lets it travel much farther for the same launch speed, which is why astronauts could hit golf balls enormous distances on the Moon. Enter the appropriate value to model any world.",
      },
    ],
    relatedCalculators: ["kinetic-energy-calculator", "gravitational-force-calculator", "force-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (projectile kinematics, no air resistance)",
  },
  {
    id: "specific-heat",
    slug: "specific-heat-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Specific Heat Calculator",
    shortDescription: "Heat energy from mass, specific heat, temperature change.",
    seoTitle: "Specific Heat Calculator — Heat Energy (Q = mcΔT)",
    metaDescription: "Free specific heat calculator. Enter mass, specific heat capacity, and temperature change to find the heat energy in joules using Q = mcΔT. Ideal for chemistry.",
    primaryKeyword: "specific heat calculator",
    secondaryKeywords: ["heat energy calculator", "q=mcat calculator", "specific heat capacity calculator"],
    fields: [
      { id: "mass", label: "Mass", type: "number", unit: "g", required: true, span: 1, min: 0 },
      { id: "specificHeat", label: "Specific heat capacity", type: "number", unit: "J/g°C", required: true, span: 1, min: 0, helpText: "Water is 4.18 J/g°C." },
      { id: "tempChange", label: "Temperature change", type: "number", unit: "°C", required: true, span: 2, helpText: "Final temperature minus starting temperature." },
    ],
    results: [
      { id: "heatEnergy", label: "Heat energy", format: "number", decimals: 2, unit: "J", isPrimary: true },
    ],
    formula: "Q = m × c × ΔT",
    formulaExplanation: "The heat needed to change a substance's temperature is the product of how much of it there is, how resistant it is to temperature change, and how large the change is. Specific heat capacity c is the energy needed to raise one gram by one degree, so multiplying it by the mass gives the energy per degree for the whole sample, and multiplying again by the temperature change ΔT gives the total energy transferred. The formula works because, away from phase changes, the heat absorbed is directly proportional to both the mass and the temperature rise.",
    explanation: "Specific heat capacity measures how much energy a material needs to warm up, and this specific heat calculator uses it to find the heat energy involved when a substance changes temperature. Enter the mass, the specific heat capacity, and the temperature change, and it returns the energy in joules using the equation Q = mcΔT.\n\nThis calculation matters because different materials store heat very differently. Water has an unusually high specific heat of about 4.18 joules per gram per degree Celsius, which is why oceans moderate climate and why it takes so long to boil a pot. Metals, by contrast, heat and cool rapidly. Engineers sizing heating systems, chemists running calorimetry experiments, and cooks understanding how pans behave all depend on the relationship a specific heat calculator makes concrete.\n\nThe formula works because the heat absorbed or released is directly proportional to the mass, to the material's specific heat capacity, and to the size of the temperature change. A positive temperature change means the substance is being heated and absorbs energy; a negative change means it is cooling and releases energy, which this calculator shows as a negative result. Students and professionals use a specific heat calculator to balance energy in thermodynamics problems, design efficient thermal systems, and interpret experiments accurately.",
    example: { inputs: { mass: 100, specificHeat: 4.18, tempChange: 20 }, explanation: "100 g × 4.18 J/g°C × 20°C = 8,360 J to heat that water by 20 degrees." },
    faqs: [
      {
        question: "What units should I use for each input?",
        answer: "Enter mass in grams, specific heat capacity in joules per gram per degree Celsius, and temperature change in degrees Celsius, and the heat energy comes out in joules. Because a change of one degree Celsius equals a change of one kelvin, you can use either scale for the temperature difference. Keeping mass in grams matches the common tabulated specific heat values and yields energy directly in joules.",
      },
      {
        question: "Where do I find the specific heat capacity of a material?",
        answer: "Specific heat capacities are tabulated in physics and chemistry references. Common values include about 4.18 J/g°C for water, 0.90 for aluminium, 0.39 for copper, and 0.45 for iron. Water's exceptionally high value explains its role in cooling and climate. Look up the value for your material and enter it here; using the correct specific heat is essential for an accurate heat energy result.",
      },
      {
        question: "Why is my heat energy negative?",
        answer: "A negative result appears when the temperature change is negative, meaning the substance cooled down, with the final temperature lower than the starting temperature. The negative sign indicates that the material released heat to its surroundings rather than absorbing it. The magnitude still tells you how much energy was involved; only the direction of energy flow differs. Heating gives a positive value, cooling a negative one.",
      },
      {
        question: "Does this formula work during boiling or melting?",
        answer: "No. The Q = mcΔT formula only applies while a substance stays in one phase and its temperature actually changes. During melting or boiling the temperature holds steady while energy goes into breaking bonds, which requires a separate calculation using latent heat, Q = mL. Use this specific heat calculator for warming or cooling within a single phase, and switch to latent heat for phase transitions.",
      },
      {
        question: "How is specific heat different from heat capacity?",
        answer: "Specific heat capacity is the energy needed to raise one gram, or one kilogram, of a substance by one degree, an intensive property that depends only on the material. Heat capacity, without the word specific, refers to a particular object and equals its mass multiplied by its specific heat, so it depends on how much of the substance you have. This calculator uses specific heat and multiplies by your mass.",
      },
    ],
    relatedCalculators: ["density-calculator", "ideal-gas-law-calculator", "kinetic-energy-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard chemistry (calorimetry, Q = mcΔT)",
  },
  {
    id: "coulombs-law",
    slug: "coulombs-law-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Coulomb's Law Calculator",
    shortDescription: "Electrostatic force between two point charges.",
    seoTitle: "Coulomb's Law Calculator — Force Between Two Charges",
    metaDescription: "Free Coulomb's law calculator. Enter two charges in coulombs and their separation in metres to find the electrostatic force between them in newtons. Great for physics.",
    primaryKeyword: "coulombs law calculator",
    secondaryKeywords: ["electrostatic force calculator", "charge force calculator", "coulomb force calculator"],
    fields: [
      { id: "charge1", label: "Charge 1", type: "number", unit: "C", required: true, span: 1, helpText: "In coulombs. Use scientific notation like 1e-6 for microcoulombs." },
      { id: "charge2", label: "Charge 2", type: "number", unit: "C", required: true, span: 1 },
      { id: "distance", label: "Separation", type: "number", unit: "m", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "force", label: "Electrostatic force", format: "number", decimals: 4, unit: "N", isPrimary: true },
    ],
    formula: "F = k · q₁ · q₂ ÷ r²,  k = 8.9875 × 10⁹ N·m²/C²",
    formulaExplanation: "Coulomb's law says the electric force between two point charges is proportional to the product of the charges and inversely proportional to the square of the distance between them. The product of the charges appears because each charge's field acts on the other, and the inverse-square dependence arises because the field spreads out over the surface of a sphere whose area grows with the square of the radius. The constant k sets the strength of the electrostatic interaction in a vacuum. A positive result means repulsion, a negative result attraction.",
    explanation: "Coulomb's law governs the force between electric charges, and this Coulomb's law calculator finds that force from the two charge values and the distance separating them. Using the electrostatic constant k of about 8.9875 billion newton-metres-squared per coulomb-squared, it returns the force in newtons for charges in coulombs and separation in metres.\n\nThis force is one of the fundamental interactions of nature and shapes the world at every scale below the astronomical. It holds electrons to nuclei, binds atoms into molecules, and explains static cling, lightning, and the behaviour of capacitors. Engineers designing electronics and physicists modelling matter both need to quantify it, and a Coulomb's law calculator does so instantly without wrestling with the very large constant and the awkward powers of ten typical of charge values.\n\nThe law works because each charge creates an electric field that pushes or pulls the other, with the strength falling off as the square of the distance, just like gravity. Like charges of the same sign produce a positive, repulsive force, while opposite charges give a negative result, signalling attraction. Because real charges are often measured in microcoulombs or nanocoulombs, this Coulomb's law calculator accepts scientific notation, letting students and engineers explore how dramatically the force grows as charges are brought closer together.",
    example: { inputs: { charge1: "1e-6", charge2: "1e-6", distance: 0.1 }, explanation: "Two 1 µC charges 0.1 m apart: 8.9875e9 × 1e-6 × 1e-6 ÷ 0.01 ≈ 0.899 N of repulsion." },
    faqs: [
      {
        question: "How do I enter very small charges like microcoulombs?",
        answer: "Use scientific notation. One microcoulomb is 1e-6 coulombs, one nanocoulomb is 1e-9, and one picocoulomb is 1e-12. Type the value in this exponential form directly into the charge fields. Real-world charges are almost always tiny fractions of a coulomb, since one coulomb is an enormous amount of charge, so scientific notation keeps the numbers manageable and the force result accurate.",
      },
      {
        question: "What does a negative force result mean?",
        answer: "The sign of the force follows the product of the two charges. If both charges have the same sign, the product is positive and the force is repulsive, pushing them apart. If the charges have opposite signs, the product is negative and the force is attractive, pulling them together. So a negative result signals attraction between opposite charges, while a positive result signals repulsion between like charges.",
      },
      {
        question: "Why does the force fall off with the square of distance?",
        answer: "Coulomb's law is an inverse-square law because the electric field radiating from a point charge spreads over the surface of an expanding sphere, whose area grows with the square of the radius. Doubling the separation therefore spreads the influence over four times the area, cutting the force to a quarter. This same inverse-square geometry governs gravity and the intensity of light from a point source.",
      },
      {
        question: "How is Coulomb's law similar to gravity?",
        answer: "Both are inverse-square laws with the same mathematical form: a constant times the product of the two source quantities divided by distance squared. Gravity uses masses and is always attractive, while Coulomb's law uses charges and can attract or repel. Electrostatic force is vastly stronger than gravity between fundamental particles, which is why chemistry and electronics are dominated by electric forces rather than gravitational ones.",
      },
      {
        question: "Does this calculator work inside materials or only in a vacuum?",
        answer: "It uses the constant k for a vacuum, which is also very close to the value in air. Inside other materials, the surrounding medium reduces the force by a factor called the relative permittivity or dielectric constant. Water, for example, weakens electrostatic forces dramatically. For force between charges in a dielectric, divide the vacuum result by that material's dielectric constant to get the reduced value.",
      },
    ],
    relatedCalculators: ["ohms-law-calculator", "gravitational-force-calculator", "force-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (Coulomb's law)",
  },
  {
    id: "mass-energy",
    slug: "mass-energy-equivalence-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Mass-Energy Equivalence Calculator",
    shortDescription: "Convert mass to energy with E = mc².",
    seoTitle: "Mass-Energy Equivalence Calculator — E = mc²",
    metaDescription: "Free E = mc² calculator. Enter a mass in kilograms to find the equivalent energy in joules and megajoules using Einstein's mass-energy equivalence. Great for physics.",
    primaryKeyword: "e=mc2 calculator",
    secondaryKeywords: ["mass energy equivalence calculator", "einstein energy calculator", "mass to energy calculator"],
    fields: [
      { id: "mass", label: "Mass", type: "number", unit: "kg", required: true, span: 2, min: 0, helpText: "In kilograms. Use scientific notation like 1e-3 for one gram." },
    ],
    results: [
      { id: "energy", label: "Equivalent energy", format: "number", decimals: 2, unit: "J", isPrimary: true },
      { id: "energyMegajoules", label: "In megajoules", format: "number", decimals: 2, unit: "MJ", isPrimary: false },
    ],
    formula: "E = m × c²,  c = 299,792,458 m/s",
    formulaExplanation: "Einstein's mass-energy equivalence states that mass and energy are two forms of the same thing, related by the square of the speed of light. Multiplying a mass by c squared converts it into its energy equivalent, and because the speed of light is so enormous, roughly three hundred million metres per second, squaring it produces a colossal factor. That is why even a minuscule mass corresponds to a vast amount of energy. The formula works because the speed of light is the fundamental conversion rate between the units of mass and the units of energy in relativity.",
    explanation: "Mass-energy equivalence is Einstein's most famous result, and this E = mc² calculator converts a mass into the staggering amount of energy locked inside it. Enter a mass in kilograms and the tool multiplies it by the speed of light squared, returning the equivalent energy in joules and, for convenience, in megajoules.\n\nThis relationship matters because it reveals that mass is a highly concentrated form of energy. It explains where the Sun's power comes from, since fusion converts a tiny fraction of hydrogen's mass into radiant energy, and it underlies nuclear reactors and weapons, where small mass differences release enormous energy. Even chemical reactions convert mass to energy, though far too little to notice. An E = mc² calculator makes the scale of this conversion tangible.\n\nThe formula works because the speed of light, about 299,792,458 metres per second, is the exchange rate between mass and energy. Squaring such a huge number yields a factor of roughly 9 × 10¹⁶, so a single gram of matter, fully converted, would release about 90 trillion joules, comparable to a large explosion. This calculator lets students, physics enthusiasts, and educators explore that idea by turning any mass into its energy equivalent and appreciating why nuclear processes are so much more powerful than chemical ones.",
    example: { inputs: { mass: 1 }, explanation: "1 kg × (299,792,458 m/s)² ≈ 8.99 × 10¹⁶ J, about 90 petajoules of energy." },
    faqs: [
      {
        question: "Why is the energy from a tiny mass so enormous?",
        answer: "Because the speed of light is squared in the formula. The speed of light is roughly 300 million metres per second, and squaring it gives a factor near 9 × 10¹⁶. Multiplying even a gram of mass by that colossal number yields an astronomical energy. This is why nuclear reactions, which convert a measurable fraction of mass, release millions of times more energy than chemical reactions do.",
      },
      {
        question: "Does E = mc² mean any mass can become energy?",
        answer: "In principle every kilogram of mass corresponds to that much energy, but converting mass fully into energy is extremely difficult. It happens completely only when matter meets antimatter and annihilates. Nuclear fission and fusion convert only a small percentage of the mass involved, and ordinary chemical reactions convert a vanishingly tiny fraction. The formula gives the theoretical maximum energy available if full conversion were achieved.",
      },
      {
        question: "What units does this calculator use?",
        answer: "Enter mass in kilograms and the equivalent energy is returned in joules, the SI unit of energy, and also in megajoules for readability, where one megajoule equals one million joules. Because the numbers are so large, results are best read in scientific notation. To enter smaller masses, use scientific notation such as 1e-3 kilograms for one gram or 1e-6 for one milligram.",
      },
      {
        question: "How does this relate to nuclear power?",
        answer: "In a nuclear reactor or a star, the products of fission or fusion have slightly less mass than the reactants. That missing mass, called the mass defect, is converted into energy exactly as E = mc² predicts. Although the mass difference is a small fraction of the total, multiplying it by the speed of light squared releases the immense energy that powers reactors and the Sun alike.",
      },
      {
        question: "Is this the complete energy equation from relativity?",
        answer: "E = mc² gives the rest energy of an object, the energy it has purely by virtue of its mass while stationary. The full relativistic energy equation also includes a term for momentum, E² = (mc²)² + (pc)², which matters for objects moving near the speed of light or for massless particles like photons. For an object at rest, that momentum term vanishes and the equation reduces to the familiar E = mc².",
      },
    ],
    relatedCalculators: ["kinetic-energy-calculator", "gravitational-force-calculator", "force-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Special relativity (Einstein's mass-energy equivalence)",
  },
];
