import type { CalculatorDefinition } from "../types";

export const scienceWave3Calculators: CalculatorDefinition[] = [
  {
    id: "ohms-law",
    slug: "ohms-law-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Ohm's Law Calculator",
    shortDescription: "Solve voltage, current, resistance and power.",
    seoTitle: "Ohm's Law Calculator — Voltage, Current, Resistance, Power",
    metaDescription: "Free Ohm's law calculator. Enter any two of voltage, current, or resistance to instantly solve the third value plus power. Perfect for circuits and electronics.",
    primaryKeyword: "ohms law calculator",
    secondaryKeywords: ["voltage current resistance calculator", "electrical power calculator", "circuit calculator"],
    fields: [
      { id: "voltage", label: "Voltage", type: "number", unit: "V", required: false, span: 1, helpText: "Enter any two of the three." },
      { id: "current", label: "Current", type: "number", unit: "A", required: false, span: 1 },
      { id: "resistance", label: "Resistance", type: "number", unit: "Ω", required: false, span: 2 },
    ],
    results: [
      { id: "power", label: "Power", format: "number", decimals: 2, unit: "W", isPrimary: true },
      { id: "voltage", label: "Voltage", format: "number", decimals: 2, unit: "V", isPrimary: false },
      { id: "current", label: "Current", format: "number", decimals: 2, unit: "A", isPrimary: false },
      { id: "resistance", label: "Resistance", format: "number", decimals: 2, unit: "Ω", isPrimary: false },
    ],
    formula: "V = I × R  ·  P = V × I",
    formulaExplanation: "Ohm's law says the current through a conductor is proportional to the voltage across it and inversely proportional to its resistance, because resistance is the constant of proportionality that limits electron flow. Rearranging V = I × R lets you recover whichever quantity is unknown. Power follows as P = V × I, since power is the rate at which each coulomb of charge delivers its voltage-worth of energy.",
    explanation: "Ohm's law is the single most important relationship in electronics, tying together voltage, current, and resistance in one clean equation. This ohms law calculator lets you enter any two of the three quantities and instantly returns the missing one along with the power dissipated. Voltage is the electrical pressure pushing charge through a circuit, current is the rate of charge flow, and resistance is how strongly the material opposes that flow.\n\nUnderstanding this trio matters because almost every practical circuit decision depends on it: sizing a resistor to protect an LED, choosing wire gauge so it does not overheat, or confirming a power supply can deliver enough current. When you know two values, the third is fixed, so a good ohms law calculator removes the mental arithmetic and the risk of a slipped decimal that could fry a component.\n\nThe formula works because resistance behaves as a constant ratio between voltage and current in ohmic materials. Hobbyists, electricians, and engineers all reach for an ohms law calculator daily, whether they are debugging a breadboard, planning household wiring, or teaching the fundamentals of electricity to students for the first time.",
    example: { inputs: { voltage: 12, current: 2 }, explanation: "12 V across 2 A gives R = 12 ÷ 2 = 6 Ω and P = 12 × 2 = 24 W." },
    faqs: [
      {
        question: "How many values do I need to enter?",
        answer: "You need to enter exactly two of the three quantities — voltage, current, or resistance. From those two the calculator solves the remaining unknown using Ohm's law and then computes power. If you enter only one value the system cannot determine the circuit, and if you enter all three inconsistently the power figure will simply reflect the numbers you typed rather than a corrected result.",
      },
      {
        question: "What units does this calculator use?",
        answer: "Voltage is in volts (V), current in amperes (A), resistance in ohms (Ω), and power in watts (W). These are the standard SI units for electrical circuits. If your values are in milliamps or kilohms, convert them first: 1,000 mA equals 1 A and 1,000 Ω equals 1 kΩ. Keeping everything in base units ensures the power result comes out correctly in watts.",
      },
      {
        question: "How is power calculated from voltage and current?",
        answer: "Power equals voltage multiplied by current, written P = V × I. This tells you how fast electrical energy is being converted to heat, light, or motion. You can also express power as I² × R or V² ÷ R by substituting Ohm's law. Power matters when sizing components, because a resistor must be rated to dissipate at least the wattage it will actually handle without overheating.",
      },
      {
        question: "Does Ohm's law apply to every component?",
        answer: "Ohm's law applies cleanly to ohmic materials like most resistors and metal conductors, where resistance stays constant regardless of voltage. It does not hold for non-ohmic components such as diodes, transistors, and light bulbs, whose resistance changes with temperature or applied voltage. For those parts you use their specific characteristic curves, but Ohm's law still governs the resistors and wiring around them in the circuit.",
      },
      {
        question: "What happens if resistance is zero?",
        answer: "A resistance of zero represents a short circuit, and Ohm's law predicts that current would become infinite for any non-zero voltage since I = V ÷ R. In reality wires have small resistance, so current spikes to a very high value that can blow fuses, damage components, or start a fire. That is exactly why circuits include fuses and current-limiting resistors to cap the flow.",
      },
    ],
    relatedCalculators: ["force-calculator", "kinetic-energy-calculator", "speed-distance-time-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard physics (Ohm's law)",
    slugEs: "calculadora-de-ley-de-ohm",
    titleEs: "Calculadora de Ley de Ohm",
    shortDescriptionEs: "Resuelve voltaje, corriente, resistencia y potencia.",
    seoTitleEs: "Calculadora de Ley de Ohm — Voltaje, Corriente, Resistencia, Potencia",
    metaDescriptionEs: "Calculadora gratuita de la ley de Ohm. Introduce dos de tres (voltaje, corriente o resistencia) para resolver al instante el tercer valor y la potencia. Ideal para circuitos y electrónica.",
    primaryKeywordEs: "calculadora de ley de ohm",
    secondaryKeywordsEs: ["calculadora de voltaje corriente resistencia", "calculadora de potencia eléctrica", "calculadora de circuitos"],
    formulaExplanationEs: "La ley de Ohm afirma que la corriente que atraviesa un conductor es proporcional al voltaje aplicado e inversamente proporcional a su resistencia, porque la resistencia es la constante de proporcionalidad que limita el flujo de electrones. Al reordenar V = I × R puedes recuperar la magnitud desconocida a partir de las otras dos. La potencia se obtiene como P = V × I, ya que la potencia es la velocidad a la que cada culombio de carga entrega su energía por el circuito.",
    explanationEs: "La ley de Ohm es la relación más importante de la electrónica, ya que une voltaje, corriente y resistencia en una sola ecuación limpia. Esta calculadora de ley de Ohm te permite introducir dos de las tres magnitudes y devuelve al instante la que falta junto con la potencia disipada. El voltaje es la presión eléctrica que empuja la carga por el circuito, la corriente es la velocidad de flujo de carga y la resistencia mide con qué fuerza el material se opone a ese flujo.\n\nComprender este trío importa porque casi toda decisión práctica de un circuito depende de él: dimensionar una resistencia para proteger un LED, elegir el calibre del cable para que no se sobrecaliente o confirmar que una fuente entrega suficiente corriente. Cuando conoces dos valores, el tercero queda fijado, así que una buena calculadora elimina el cálculo mental y el riesgo de un decimal mal puesto que podría quemar un componente.\n\nLa fórmula funciona porque la resistencia se comporta como una relación constante entre voltaje y corriente en los materiales óhmicos. Aficionados, electricistas e ingenieros recurren a diario a una calculadora de ley de Ohm, ya sea depurando una placa de pruebas, planificando la instalación de una vivienda o enseñando los fundamentos de la electricidad.",
    exampleEs: { inputs: { voltage: 12, current: 2 }, explanation: "12 V con 2 A dan R = 12 ÷ 2 = 6 Ω y P = 12 × 2 = 24 W." },
    faqsEs: [
      {
        question: "¿Cuántos valores necesito introducir?",
        answer: "Necesitas introducir exactamente dos de las tres magnitudes: voltaje, corriente o resistencia. A partir de esos dos la calculadora resuelve la incógnita restante mediante la ley de Ohm y después calcula la potencia. Si solo introduces un valor el sistema no puede determinar el circuito, y si introduces los tres de forma incoherente la potencia reflejará simplemente los números que escribiste.",
      },
      {
        question: "¿Qué unidades usa esta calculadora?",
        answer: "El voltaje se expresa en voltios (V), la corriente en amperios (A), la resistencia en ohmios (Ω) y la potencia en vatios (W). Son las unidades SI estándar para circuitos eléctricos. Si tus valores están en miliamperios o kiloohmios, conviértelos primero: 1000 mA equivalen a 1 A y 1000 Ω equivalen a 1 kΩ. Mantener todo en unidades base garantiza que la potencia salga correcta en vatios.",
      },
      {
        question: "¿Cómo se calcula la potencia a partir del voltaje y la corriente?",
        answer: "La potencia es igual al voltaje multiplicado por la corriente, escrito P = V × I. Esto indica con qué rapidez se convierte la energía eléctrica en calor, luz o movimiento. También puedes expresar la potencia como I² × R o V² ÷ R sustituyendo con la ley de Ohm. La potencia importa al dimensionar componentes, porque una resistencia debe soportar al menos los vatios que manejará sin sobrecalentarse.",
      },
      {
        question: "¿Se aplica la ley de Ohm a todos los componentes?",
        answer: "La ley de Ohm se aplica limpiamente a materiales óhmicos como la mayoría de las resistencias y los conductores metálicos, donde la resistencia permanece constante sin importar el voltaje. No se cumple en componentes no óhmicos como diodos, transistores y bombillas, cuya resistencia cambia con la temperatura o el voltaje aplicado. Para esas piezas se usan sus curvas características específicas, pero la ley sigue gobernando las resistencias y el cableado del circuito.",
      },
      {
        question: "¿Qué ocurre si la resistencia es cero?",
        answer: "Una resistencia de cero representa un cortocircuito, y la ley de Ohm predice que la corriente se volvería infinita para cualquier voltaje distinto de cero, ya que I = V ÷ R. En la realidad los cables tienen una pequeña resistencia, por lo que la corriente sube a un valor muy alto que puede fundir fusibles, dañar componentes o provocar un incendio. Por eso los circuitos incluyen fusibles y resistencias limitadoras.",
      },
    ],
  },
  {
    id: "density",
    slug: "density-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Density Calculator",
    shortDescription: "Find density from mass and volume.",
    seoTitle: "Density Calculator — Mass and Volume to Density",
    metaDescription: "Free density calculator. Enter mass and volume to find density instantly in kg/m³ and g/cm³. Ideal for physics, chemistry, and material science problems.",
    primaryKeyword: "density calculator",
    secondaryKeywords: ["mass volume density calculator", "density formula calculator", "kg/m3 to g/cm3"],
    fields: [
      { id: "mass", label: "Mass", type: "number", unit: "kg", required: true, span: 1, min: 0 },
      { id: "volume", label: "Volume", type: "number", unit: "m³", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "density", label: "Density", format: "number", decimals: 4, unit: "kg/m³", isPrimary: true },
      { id: "gPerCm3", label: "In g/cm³", format: "number", decimals: 6, unit: "g/cm³", isPrimary: false },
    ],
    formula: "ρ = mass ÷ volume",
    formulaExplanation: "Density measures how much mass is packed into a given volume, so dividing mass by volume gives the amount of matter per unit space. The formula works because mass and volume are both extensive properties that scale together for a uniform substance, leaving their ratio constant. That ratio is an intensive property, unique to each material regardless of how much of it you have, which is why it identifies substances so reliably.",
    explanation: "Density is a core property of matter that tells you how tightly mass is packed into a volume, and this density calculator returns it instantly from the mass and volume you enter. It reports the answer in kilograms per cubic metre and also converts to grams per cubic centimetre, the unit chemists and students most often use. A dense material like lead crams a lot of mass into a small space, while a light material like cork spreads little mass across a larger volume.\n\nDensity matters because it predicts behaviour without weighing an entire object: whether something floats or sinks, which of two liquids layers on top, and what a metal is likely made of. Buoyancy, ship design, and even blood-test interpretation all hinge on comparing densities, so a quick density calculator saves time in the lab and the workshop alike.\n\nThe formula works because density is simply mass divided by volume, an intrinsic ratio that stays the same whether you measure a gram or a tonne of the substance. Engineers, geologists, jewellers, and physics students all rely on a density calculator to identify materials, check purity, and solve textbook problems with confidence.",
    example: { inputs: { mass: 10, volume: 2 }, explanation: "10 kg ÷ 2 m³ = 5 kg/m³." },
    faqs: [
      {
        question: "What units should I use for mass and volume?",
        answer: "Enter mass in kilograms and volume in cubic metres to get density directly in kilograms per cubic metre. The calculator also converts that result to grams per cubic centimetre for convenience. If your measurements are in grams and cubic centimetres, you can convert first, but keeping to the labelled SI units guarantees both output figures are correct without any extra scaling on your part.",
      },
      {
        question: "Why does the calculator show both kg/m³ and g/cm³?",
        answer: "Different fields prefer different units. Engineers and physicists usually work in kilograms per cubic metre, the SI standard, while chemists and students commonly quote grams per cubic centimetre because water conveniently sits at about 1 g/cm³. Showing both lets you compare your result against reference tables no matter which convention they use. The conversion factor is 1,000: one g/cm³ equals 1,000 kg/m³.",
      },
      {
        question: "How does density predict whether something floats?",
        answer: "An object floats in a fluid if its density is lower than the fluid's density, and sinks if it is higher. Water has a density near 1,000 kg/m³, so any material below that, like wood or ice, floats, while denser materials like iron sink. This is why comparing an object's density to water is such a quick, reliable buoyancy check without any complex force diagrams.",
      },
      {
        question: "Does temperature change a material's density?",
        answer: "Yes. Most substances expand when heated, spreading the same mass over a larger volume, which lowers density. This is why warm air rises and why liquids stratify by temperature. Water is a famous exception, reaching maximum density near 4°C before expanding as it freezes. For precise work, always note the temperature at which a reference density was measured and match your conditions to it.",
      },
      {
        question: "Can I use this to identify an unknown material?",
        answer: "Often, yes. Measure the object's mass and volume, compute its density here, and compare the figure against a table of known material densities. A close match strongly suggests the material's identity, since density is an intensive property unique to each substance. Be careful with alloys, porous samples, or trapped air, which can shift the reading, and confirm with a second property when precision matters.",
      },
    ],
    relatedCalculators: ["ohms-law-calculator", "force-calculator", "ph-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard physics (density)",
    slugEs: "calculadora-de-densidad",
    titleEs: "Calculadora de Densidad",
    shortDescriptionEs: "Halla la densidad a partir de la masa y el volumen.",
    seoTitleEs: "Calculadora de Densidad — Masa y Volumen a Densidad",
    metaDescriptionEs: "Calculadora gratuita de densidad. Introduce la masa y el volumen para hallar la densidad al instante en kg/m³ y g/cm³. Ideal para física, química y ciencia de materiales.",
    primaryKeywordEs: "calculadora de densidad",
    secondaryKeywordsEs: ["calculadora de masa volumen densidad", "calculadora de fórmula de densidad", "kg/m3 a g/cm3"],
    formulaExplanationEs: "La densidad mide cuánta masa se concentra en un volumen dado, por lo que dividir la masa entre el volumen da la cantidad de materia por unidad de espacio. La fórmula funciona porque tanto la masa como el volumen son propiedades extensivas que escalan juntas en una sustancia uniforme, dejando su cociente constante. Ese cociente es una propiedad intensiva, única de cada material sin importar la cantidad que tengas, por lo que identifica las sustancias de forma tan fiable.",
    explanationEs: "La densidad es una propiedad fundamental de la materia que indica con qué firmeza se concentra la masa en un volumen, y esta calculadora de densidad la devuelve al instante a partir de la masa y el volumen que introduzcas. Muestra la respuesta en kilogramos por metro cúbico y también la convierte a gramos por centímetro cúbico, la unidad que químicos y estudiantes usan con más frecuencia. Un material denso como el plomo concentra mucha masa en poco espacio, mientras que uno ligero como el corcho reparte poca masa en un volumen mayor.\n\nLa densidad importa porque predice el comportamiento sin pesar el objeto entero: si algo flota o se hunde, cuál de dos líquidos queda arriba y de qué está hecho probablemente un metal. La flotabilidad, el diseño de barcos e incluso la interpretación de análisis de sangre dependen de comparar densidades, así que una calculadora rápida ahorra tiempo en el laboratorio y en el taller.\n\nLa fórmula funciona porque la densidad es simplemente masa dividida entre volumen, una relación intrínseca que se mantiene igual midas un gramo o una tonelada de la sustancia. Ingenieros, geólogos, joyeros y estudiantes recurren a una calculadora de densidad para identificar materiales, comprobar la pureza y resolver problemas de libro de texto con confianza.",
    exampleEs: { inputs: { mass: 10, volume: 2 }, explanation: "10 kg ÷ 2 m³ = 5 kg/m³." },
    faqsEs: [
      {
        question: "¿Qué unidades debo usar para la masa y el volumen?",
        answer: "Introduce la masa en kilogramos y el volumen en metros cúbicos para obtener la densidad directamente en kilogramos por metro cúbico. La calculadora también convierte ese resultado a gramos por centímetro cúbico por comodidad. Si tus medidas están en gramos y centímetros cúbicos, puedes convertirlas primero, pero mantener las unidades SI indicadas garantiza que ambas cifras de salida sean correctas sin escalado adicional.",
      },
      {
        question: "¿Por qué la calculadora muestra kg/m³ y g/cm³?",
        answer: "Cada campo prefiere unidades distintas. Ingenieros y físicos suelen trabajar en kilogramos por metro cúbico, el estándar SI, mientras que químicos y estudiantes citan gramos por centímetro cúbico porque el agua queda convenientemente cerca de 1 g/cm³. Mostrar ambas te permite comparar tu resultado con tablas de referencia sin importar el convenio. El factor de conversión es 1000: un g/cm³ equivale a 1000 kg/m³.",
      },
      {
        question: "¿Cómo predice la densidad si algo flota?",
        answer: "Un objeto flota en un fluido si su densidad es menor que la del fluido, y se hunde si es mayor. El agua tiene una densidad cercana a 1000 kg/m³, así que cualquier material por debajo, como la madera o el hielo, flota, mientras que materiales más densos como el hierro se hunden. Por eso comparar la densidad de un objeto con la del agua es una prueba de flotabilidad rápida y fiable.",
      },
      {
        question: "¿La temperatura cambia la densidad de un material?",
        answer: "Sí. La mayoría de las sustancias se expanden al calentarse, repartiendo la misma masa en un volumen mayor, lo que reduce la densidad. Por eso el aire caliente sube y los líquidos se estratifican por temperatura. El agua es una excepción famosa, alcanzando su densidad máxima cerca de 4 °C antes de expandirse al congelarse. Para trabajos precisos, anota siempre la temperatura a la que se midió una densidad de referencia.",
      },
      {
        question: "¿Puedo usar esto para identificar un material desconocido?",
        answer: "A menudo, sí. Mide la masa y el volumen del objeto, calcula su densidad aquí y compara la cifra con una tabla de densidades conocidas. Una coincidencia cercana sugiere con fuerza la identidad del material, ya que la densidad es una propiedad intensiva única de cada sustancia. Ten cuidado con las aleaciones, las muestras porosas o el aire atrapado, que pueden alterar la lectura, y confirma con una segunda propiedad cuando la precisión importe.",
      },
    ],
  },
  {
    id: "force",
    slug: "force-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Force Calculator",
    shortDescription: "Calculate force from mass and acceleration.",
    seoTitle: "Force Calculator — Newton's Second Law (F = ma)",
    metaDescription: "Free force calculator using Newton's second law. Enter mass and acceleration to find force in newtons and pounds-force instantly. Perfect for physics homework.",
    primaryKeyword: "force calculator",
    secondaryKeywords: ["newtons second law calculator", "f=ma calculator", "mass acceleration force"],
    fields: [
      { id: "mass", label: "Mass", type: "number", unit: "kg", required: true, span: 1, min: 0 },
      { id: "acceleration", label: "Acceleration", type: "number", unit: "m/s²", required: true, span: 1 },
    ],
    results: [
      { id: "force", label: "Force", format: "number", decimals: 2, unit: "N", isPrimary: true },
      { id: "lbf", label: "In pounds-force", format: "number", decimals: 2, unit: "lbf", isPrimary: false },
    ],
    formula: "F = mass × acceleration",
    formulaExplanation: "Newton's second law states that force equals mass times acceleration because force is what changes an object's motion, and heavier objects need proportionally more force to reach the same acceleration. Multiplying mass by acceleration captures both how much matter must be moved and how quickly its velocity must change. The result is measured in newtons, where one newton accelerates one kilogram at one metre per second squared.",
    explanation: "Force is the push or pull that changes how an object moves, and this force calculator applies Newton's second law to turn a mass and an acceleration into a precise answer in newtons and pounds-force. Whenever something speeds up, slows down, or changes direction, a net force is acting on it, and the equation F equals mass times acceleration quantifies exactly how strong that force is.\n\nThis relationship matters because it underpins almost all of mechanics: it explains why a loaded truck needs a longer braking distance, how much thrust a rocket requires to lift off, and why seatbelts must withstand large forces in a crash. By separating mass from acceleration, a force calculator makes it easy to see how each factor contributes, so you can double a mass or halve an acceleration and read off the effect immediately.\n\nThe formula works because acceleration is the direct measure of how motion is changing, and mass is the resistance to that change, so their product is the force responsible. Students, engineers, and physics teachers use a force calculator to check homework, design mechanisms, and predict how real objects will respond when a known force is applied.",
    example: { inputs: { mass: 10, acceleration: 9.81 }, explanation: "10 kg × 9.81 m/s² = 98.1 N." },
    faqs: [
      {
        question: "What is a newton and how big is it?",
        answer: "A newton is the SI unit of force, defined as the force needed to accelerate a one-kilogram mass at one metre per second squared. It is a fairly small unit in everyday terms: holding a small apple against gravity takes roughly one newton. The weight of a person or a car runs into hundreds or thousands of newtons, which is why forces in engineering are often quoted in kilonewtons.",
      },
      {
        question: "Why does the calculator also show pounds-force?",
        answer: "Pounds-force is the customary unit still used widely in the United States and in many engineering specifications. Showing it alongside newtons lets you communicate results to audiences on either measurement system without a separate conversion step. One pound-force equals about 4.448 newtons, so the calculator divides your newton result by that factor to produce the pounds-force figure automatically for you.",
      },
      {
        question: "What acceleration should I use for weight?",
        answer: "To find an object's weight, use Earth's gravitational acceleration of about 9.81 metres per second squared as the acceleration value. Weight is simply the force gravity exerts on a mass, so a 10-kilogram object weighs roughly 98.1 newtons. On the Moon you would use about 1.62 m/s² instead, which is why the same mass weighs far less there despite having identical mass.",
      },
      {
        question: "Can force or acceleration be negative?",
        answer: "Yes. A negative acceleration simply means the object is slowing down or accelerating in the opposite direction to the one you chose as positive. Feeding a negative acceleration into the calculator produces a negative force, indicating the force points the other way — for example, the braking force that decelerates a car. The magnitude tells you how strong the force is; the sign tells you its direction.",
      },
      {
        question: "How does mass differ from weight?",
        answer: "Mass measures how much matter an object contains and stays the same everywhere, while weight is the force gravity exerts on that mass and changes with location. This calculator computes force, so when the acceleration is gravity the output is weight in newtons. Confusing the two is common because everyday scales report mass in kilograms, but strictly speaking they infer mass from the weight they detect.",
      },
    ],
    relatedCalculators: ["kinetic-energy-calculator", "ohms-law-calculator", "speed-distance-time-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard physics (Newton's second law)",
    slugEs: "calculadora-de-fuerza",
    titleEs: "Calculadora de Fuerza",
    shortDescriptionEs: "Calcula la fuerza a partir de la masa y la aceleración.",
    seoTitleEs: "Calculadora de Fuerza — Segunda Ley de Newton (F = ma)",
    metaDescriptionEs: "Calculadora gratuita de fuerza con la segunda ley de Newton. Introduce masa y aceleración para hallar la fuerza en newtons y libras-fuerza al instante. Ideal para tareas de física.",
    primaryKeywordEs: "calculadora de fuerza",
    secondaryKeywordsEs: ["calculadora de segunda ley de newton", "calculadora f=ma", "masa aceleración fuerza"],
    formulaExplanationEs: "La segunda ley de Newton establece que la fuerza es igual a la masa por la aceleración, porque la fuerza es lo que cambia el movimiento de un objeto, y los objetos más pesados necesitan proporcionalmente más fuerza para alcanzar la misma aceleración. Multiplicar la masa por la aceleración capta tanto cuánta materia hay que mover como con qué rapidez debe cambiar su velocidad. El resultado se mide en newtons, donde un newton acelera un kilogramo a un metro por segundo al cuadrado.",
    explanationEs: "La fuerza es el empuje o tirón que cambia cómo se mueve un objeto, y esta calculadora de fuerza aplica la segunda ley de Newton para convertir una masa y una aceleración en una respuesta precisa en newtons y libras-fuerza. Siempre que algo acelera, frena o cambia de dirección, actúa sobre él una fuerza neta, y la ecuación F igual a masa por aceleración cuantifica exactamente cuán intensa es esa fuerza.\n\nEsta relación importa porque sustenta casi toda la mecánica: explica por qué un camión cargado necesita una distancia de frenado mayor, cuánto empuje requiere un cohete para despegar y por qué los cinturones de seguridad deben resistir grandes fuerzas en un choque. Al separar la masa de la aceleración, una calculadora de fuerza facilita ver cómo contribuye cada factor, de modo que puedes duplicar una masa o reducir a la mitad una aceleración y leer el efecto de inmediato.\n\nLa fórmula funciona porque la aceleración es la medida directa de cómo cambia el movimiento, y la masa es la resistencia a ese cambio, así que su producto es la fuerza responsable. Estudiantes, ingenieros y profesores de física usan una calculadora de fuerza para revisar tareas, diseñar mecanismos y predecir cómo responderán los objetos reales cuando se les aplica una fuerza conocida.",
    exampleEs: { inputs: { mass: 10, acceleration: 9.81 }, explanation: "10 kg × 9,81 m/s² = 98,1 N." },
    faqsEs: [
      {
        question: "¿Qué es un newton y cómo de grande es?",
        answer: "Un newton es la unidad SI de fuerza, definida como la fuerza necesaria para acelerar una masa de un kilogramo a un metro por segundo al cuadrado. Es una unidad bastante pequeña en términos cotidianos: sostener una manzana pequeña contra la gravedad requiere aproximadamente un newton. El peso de una persona o un coche alcanza cientos o miles de newtons, por lo que las fuerzas en ingeniería a menudo se expresan en kilonewtons.",
      },
      {
        question: "¿Por qué la calculadora también muestra libras-fuerza?",
        answer: "La libra-fuerza es la unidad tradicional aún muy usada en Estados Unidos y en muchas especificaciones de ingeniería. Mostrarla junto a los newtons te permite comunicar resultados a públicos de cualquier sistema de medida sin un paso de conversión aparte. Una libra-fuerza equivale a unos 4,448 newtons, así que la calculadora divide tu resultado en newtons entre ese factor para producir automáticamente la cifra en libras-fuerza.",
      },
      {
        question: "¿Qué aceleración debo usar para el peso?",
        answer: "Para hallar el peso de un objeto, usa la aceleración gravitatoria de la Tierra, de unos 9,81 metros por segundo al cuadrado, como valor de aceleración. El peso es simplemente la fuerza que la gravedad ejerce sobre una masa, así que un objeto de 10 kilogramos pesa unos 98,1 newtons. En la Luna usarías unos 1,62 m/s², por lo que la misma masa pesa mucho menos allí pese a tener idéntica masa.",
      },
      {
        question: "¿Pueden ser negativas la fuerza o la aceleración?",
        answer: "Sí. Una aceleración negativa significa simplemente que el objeto está frenando o acelerando en la dirección opuesta a la que elegiste como positiva. Introducir una aceleración negativa produce una fuerza negativa, lo que indica que la fuerza apunta al otro lado; por ejemplo, la fuerza de frenado que desacelera un coche. La magnitud te dice cuán intensa es la fuerza; el signo indica su dirección.",
      },
      {
        question: "¿En qué se diferencia la masa del peso?",
        answer: "La masa mide cuánta materia contiene un objeto y es la misma en todas partes, mientras que el peso es la fuerza que la gravedad ejerce sobre esa masa y cambia con la ubicación. Esta calculadora calcula fuerza, así que cuando la aceleración es la gravedad la salida es el peso en newtons. Confundir ambas es común porque las balanzas cotidianas informan la masa en kilogramos, aunque en rigor la infieren del peso que detectan.",
      },
    ],
  },
  {
    id: "kinetic-energy",
    slug: "kinetic-energy-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Kinetic Energy Calculator",
    shortDescription: "Compute kinetic energy and momentum.",
    seoTitle: "Kinetic Energy Calculator — Energy and Momentum",
    metaDescription: "Free kinetic energy calculator. Enter mass and velocity to find kinetic energy in joules and momentum instantly. Great for physics homework and motion problems.",
    primaryKeyword: "kinetic energy calculator",
    secondaryKeywords: ["kinetic energy formula", "momentum calculator", "energy of motion calculator"],
    fields: [
      { id: "mass", label: "Mass", type: "number", unit: "kg", required: true, span: 1, min: 0 },
      { id: "velocity", label: "Velocity", type: "number", unit: "m/s", required: true, span: 1 },
    ],
    results: [
      { id: "ke", label: "Kinetic energy", format: "number", decimals: 2, unit: "J", isPrimary: true },
      { id: "momentum", label: "Momentum", format: "number", decimals: 2, unit: "kg·m/s", isPrimary: false },
    ],
    formula: "KE = ½ × mass × velocity²",
    formulaExplanation: "Kinetic energy is the work needed to accelerate a mass from rest to its current speed, and integrating force over distance yields the one-half mass times velocity squared form. The velocity is squared because doubling speed both doubles the distance covered per second and doubles the momentum change, so energy grows fourfold. Momentum, by contrast, is just mass times velocity and scales linearly with speed.",
    explanation: "Kinetic energy is the energy an object carries because it is moving, and this kinetic energy calculator returns it in joules from a mass and a velocity, along with the object's momentum. The faster and heavier something moves, the more kinetic energy it holds, which is precisely the energy that must be absorbed to bring it to a stop. That is why a speeding car is so much harder to halt than a slow one of the same mass.\n\nThis quantity matters across science and safety: it explains crash severity, the destructive power of a hurricane, the reach of a thrown ball, and how much braking a vehicle needs. Because velocity is squared in the formula, a kinetic energy calculator makes the dramatic effect of speed obvious — doubling velocity quadruples the energy, a fact that shapes speed limits and impact standards.\n\nThe formula works because kinetic energy equals the accumulated work done accelerating the mass, and that work grows with the square of speed. Momentum, shown alongside, tracks mass times velocity and governs collisions. Physics students, engineers, and safety analysts turn to a kinetic energy calculator to solve motion problems and understand how moving objects behave when they interact.",
    example: { inputs: { mass: 2, velocity: 3 }, explanation: "½ × 2 × 3² = ½ × 2 × 9 = 9 J." },
    faqs: [
      {
        question: "Why is velocity squared in the kinetic energy formula?",
        answer: "Velocity is squared because kinetic energy equals the total work done to accelerate an object, and that work grows with both the force applied and the distance covered, each of which rises with speed. The practical result is dramatic: doubling velocity quadruples kinetic energy, and tripling it multiplies energy by nine. This is why small increases in speed cause disproportionately larger increases in impact energy and stopping distance.",
      },
      {
        question: "What is the difference between kinetic energy and momentum?",
        answer: "Kinetic energy measures the energy of motion and depends on the square of velocity, while momentum measures the quantity of motion and depends on velocity linearly. Momentum is conserved in every collision, whereas kinetic energy is only conserved in perfectly elastic ones. The calculator shows both because engineers and physicists need momentum to analyse collisions and kinetic energy to understand how much damage or work the motion can produce.",
      },
      {
        question: "What units does this calculator use?",
        answer: "Enter mass in kilograms and velocity in metres per second. Kinetic energy is then returned in joules, the SI unit of energy, and momentum in kilogram-metres per second. One joule is the energy of a two-kilogram mass moving at one metre per second. If your velocity is given in kilometres per hour, convert it first by dividing by 3.6 to keep the result accurate.",
      },
      {
        question: "Can kinetic energy be negative?",
        answer: "No. Kinetic energy is always zero or positive because it depends on velocity squared, and squaring any number gives a non-negative result. An object at rest has zero kinetic energy, and any motion gives a positive value regardless of direction. Momentum, by contrast, can be negative because it carries direction, so a value's sign there indicates which way the object is travelling.",
      },
      {
        question: "How does kinetic energy relate to stopping distance?",
        answer: "Braking must remove all of an object's kinetic energy, and since that energy scales with the square of speed, stopping distance rises sharply as speed increases. A car travelling twice as fast carries four times the kinetic energy and needs roughly four times the distance to stop under the same braking force. This squared relationship is the physical reason speed limits have such a large effect on crash outcomes.",
      },
    ],
    relatedCalculators: ["force-calculator", "speed-distance-time-calculator", "ohms-law-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard physics (kinetic energy)",
    slugEs: "calculadora-de-energia-cinetica",
    titleEs: "Calculadora de Energía Cinética",
    shortDescriptionEs: "Calcula la energía cinética y el momento lineal.",
    seoTitleEs: "Calculadora de Energía Cinética — Energía y Momento",
    metaDescriptionEs: "Calculadora gratuita de energía cinética. Introduce masa y velocidad para hallar la energía cinética en julios y el momento al instante. Ideal para tareas de física y problemas de movimiento.",
    primaryKeywordEs: "calculadora de energía cinética",
    secondaryKeywordsEs: ["fórmula de energía cinética", "calculadora de momento", "calculadora de energía de movimiento"],
    formulaExplanationEs: "La energía cinética es el trabajo necesario para acelerar una masa desde el reposo hasta su velocidad actual, e integrar la fuerza a lo largo de la distancia produce la forma un medio de masa por velocidad al cuadrado. La velocidad se eleva al cuadrado porque duplicar la rapidez duplica tanto la distancia recorrida por segundo como el cambio de momento, de modo que la energía crece cuatro veces. El momento, en cambio, es solo masa por velocidad y escala linealmente con la rapidez.",
    explanationEs: "La energía cinética es la energía que un objeto posee por estar en movimiento, y esta calculadora de energía cinética la devuelve en julios a partir de una masa y una velocidad, junto con el momento lineal del objeto. Cuanto más rápido y pesado se mueva algo, más energía cinética contiene, que es precisamente la energía que hay que absorber para detenerlo. Por eso un coche a gran velocidad es mucho más difícil de frenar que uno lento de la misma masa.\n\nEsta magnitud importa en la ciencia y la seguridad: explica la gravedad de un choque, el poder destructivo de un huracán, el alcance de una pelota lanzada y cuánto frenado necesita un vehículo. Como la velocidad se eleva al cuadrado en la fórmula, una calculadora de energía cinética deja obvio el efecto dramático de la rapidez: duplicar la velocidad cuadruplica la energía, un hecho que da forma a los límites de velocidad y a las normas de impacto.\n\nLa fórmula funciona porque la energía cinética es igual al trabajo acumulado al acelerar la masa, y ese trabajo crece con el cuadrado de la rapidez. El momento, mostrado al lado, sigue la masa por la velocidad y gobierna las colisiones. Estudiantes, ingenieros y analistas de seguridad recurren a una calculadora de energía cinética para resolver problemas de movimiento y entender cómo se comportan los objetos en movimiento.",
    exampleEs: { inputs: { mass: 2, velocity: 3 }, explanation: "½ × 2 × 3² = ½ × 2 × 9 = 9 J." },
    faqsEs: [
      {
        question: "¿Por qué se eleva al cuadrado la velocidad en la fórmula?",
        answer: "La velocidad se eleva al cuadrado porque la energía cinética es igual al trabajo total realizado para acelerar un objeto, y ese trabajo crece tanto con la fuerza aplicada como con la distancia recorrida, cada una de las cuales aumenta con la rapidez. El resultado práctico es dramático: duplicar la velocidad cuadruplica la energía cinética, y triplicarla la multiplica por nueve. Por eso pequeños aumentos de velocidad causan aumentos desproporcionados de energía de impacto.",
      },
      {
        question: "¿Cuál es la diferencia entre energía cinética y momento?",
        answer: "La energía cinética mide la energía del movimiento y depende del cuadrado de la velocidad, mientras que el momento mide la cantidad de movimiento y depende linealmente de la velocidad. El momento se conserva en toda colisión, mientras que la energía cinética solo se conserva en las perfectamente elásticas. La calculadora muestra ambos porque los físicos necesitan el momento para analizar colisiones y la energía cinética para entender cuánto daño puede producir el movimiento.",
      },
      {
        question: "¿Qué unidades usa esta calculadora?",
        answer: "Introduce la masa en kilogramos y la velocidad en metros por segundo. La energía cinética se devuelve entonces en julios, la unidad SI de energía, y el momento en kilogramos-metro por segundo. Un julio es la energía de una masa de dos kilogramos moviéndose a un metro por segundo. Si tu velocidad está en kilómetros por hora, conviértela primero dividiendo entre 3,6 para mantener el resultado exacto.",
      },
      {
        question: "¿Puede ser negativa la energía cinética?",
        answer: "No. La energía cinética siempre es cero o positiva porque depende de la velocidad al cuadrado, y elevar al cuadrado cualquier número da un resultado no negativo. Un objeto en reposo tiene energía cinética cero, y cualquier movimiento da un valor positivo sin importar la dirección. El momento, en cambio, puede ser negativo porque lleva dirección, así que allí el signo indica hacia dónde viaja el objeto.",
      },
      {
        question: "¿Cómo se relaciona la energía cinética con la distancia de frenado?",
        answer: "El frenado debe eliminar toda la energía cinética de un objeto, y como esa energía escala con el cuadrado de la rapidez, la distancia de frenado aumenta con fuerza al crecer la velocidad. Un coche que viaja al doble de rapidez lleva cuatro veces la energía cinética y necesita aproximadamente cuatro veces la distancia para detenerse con la misma fuerza de frenado. Esta relación cuadrática es la razón física de que los límites de velocidad influyan tanto.",
      },
    ],
  },
  {
    id: "ph",
    slug: "ph-calculator",
    category: "Science",
    categorySlug: "science",
    title: "pH Calculator",
    shortDescription: "Find pH and pOH from hydrogen ion concentration.",
    seoTitle: "pH Calculator — Hydrogen Ion Concentration to pH and pOH",
    metaDescription: "Free pH calculator. Enter hydrogen ion concentration in mol/L to find pH, pOH, and whether a solution is acidic, neutral, or basic. Instant chemistry results.",
    primaryKeyword: "ph calculator",
    secondaryKeywords: ["hydrogen ion concentration calculator", "poh calculator", "acid base calculator"],
    fields: [
      { id: "concentration", label: "[H⁺] concentration", type: "number", unit: "mol/L", required: true, span: 2, step: 0.0001, min: 0, helpText: "Hydrogen ion concentration in moles per litre." },
    ],
    results: [
      { id: "ph", label: "pH", format: "number", decimals: 2, isPrimary: true },
      { id: "poh", label: "pOH", format: "number", decimals: 2, isPrimary: false },
      { id: "classification", label: "Classification", format: "text", isPrimary: false },
    ],
    formula: "pH = −log₁₀[H⁺]  ·  pOH = 14 − pH",
    formulaExplanation: "pH is the negative base-ten logarithm of hydrogen ion concentration because those concentrations span many orders of magnitude, and a logarithm compresses that huge range into a convenient 0-to-14 scale. The negative sign makes acidic solutions, which have high concentrations, correspond to low pH numbers. pOH sums with pH to 14 at 25°C because water's self-ionisation fixes the product of hydrogen and hydroxide ion concentrations.",
    explanation: "pH tells you how acidic or basic a solution is, and this pH calculator converts a hydrogen ion concentration in moles per litre into a pH value, its matching pOH, and a plain-language classification of acidic, neutral, or basic. Because hydrogen ion concentrations range across many powers of ten, the logarithmic pH scale packs them neatly between 0 and 14, where 7 is neutral, lower numbers are acidic, and higher numbers are basic.\n\nGetting pH right matters everywhere from the lab bench to daily life: it governs enzyme activity in the body, the safety of drinking water, the health of soil and aquariums, and the outcome of countless chemical reactions. A reliable pH calculator removes the tricky logarithm arithmetic and the easy-to-miss sign, so you can move straight from a measured concentration to an interpretable result.\n\nThe formula works because pH is the negative logarithm of hydrogen ion concentration, turning tiny fractional numbers into a readable scale, while pOH completes the picture since the two always sum to 14 in water at room temperature. Chemistry students, lab technicians, and environmental scientists all lean on a pH calculator to check acidity quickly and accurately.",
    example: { inputs: { concentration: 0.001 }, explanation: "−log₁₀(0.001) = 3, so pH = 3 (acidic) and pOH = 11." },
    faqs: [
      {
        question: "What does the pH scale actually measure?",
        answer: "The pH scale measures the concentration of hydrogen ions in a solution on a logarithmic scale, indicating how acidic or basic it is. It typically runs from 0 to 14, with 7 being neutral, values below 7 acidic, and values above 7 basic. Because it is logarithmic, each whole-number step represents a tenfold change in hydrogen ion concentration, so pH 4 is ten times more acidic than pH 5.",
      },
      {
        question: "How are pH and pOH related?",
        answer: "In water at 25°C, pH and pOH always add up to 14. This comes from the self-ionisation of water, where the product of hydrogen and hydroxide ion concentrations is fixed at 10⁻¹⁴. So if you know one, you immediately know the other: a solution with pH 3 has pOH 11. The calculator computes pOH by subtracting the pH from 14 automatically for you.",
      },
      {
        question: "What concentration gives a neutral pH?",
        answer: "A neutral solution at 25°C has a hydrogen ion concentration of 1×10⁻⁷ moles per litre, which produces a pH of exactly 7. At this concentration the hydrogen and hydroxide ions are perfectly balanced, so the solution is neither acidic nor basic. Pure water sits at this point. Entering 0.0000001 mol/L into the calculator returns a pH of 7 and a classification of neutral.",
      },
      {
        question: "Can pH be negative or above 14?",
        answer: "Yes, though it is uncommon in everyday settings. Very concentrated strong acids can have hydrogen ion concentrations above 1 mol/L, producing a negative pH, while extremely concentrated strong bases can push pH above 14. The 0-to-14 range is simply the span covering most aqueous solutions, not a hard limit. The calculator handles values outside that window correctly using the same logarithmic formula.",
      },
      {
        question: "Why is the pH scale logarithmic instead of linear?",
        answer: "Hydrogen ion concentrations in real solutions vary across an enormous range, from around 1 mol/L in strong acids to 10⁻¹⁴ mol/L in strong bases. A linear scale would be unusable across so many orders of magnitude. The logarithmic pH scale compresses that range into simple numbers between 0 and 14, making comparisons easy while still capturing the vast underlying differences in acidity between solutions.",
      },
    ],
    relatedCalculators: ["density-calculator", "ohms-law-calculator", "force-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard chemistry (pH scale)",
    slugEs: "calculadora-de-ph",
    titleEs: "Calculadora de pH",
    shortDescriptionEs: "Halla el pH y el pOH a partir de la concentración de iones de hidrógeno.",
    seoTitleEs: "Calculadora de pH — Concentración de Iones de Hidrógeno a pH y pOH",
    metaDescriptionEs: "Calculadora gratuita de pH. Introduce la concentración de iones de hidrógeno en mol/L para hallar el pH, el pOH y si una disolución es ácida, neutra o básica. Resultados de química al instante.",
    primaryKeywordEs: "calculadora de ph",
    secondaryKeywordsEs: ["calculadora de concentración de iones de hidrógeno", "calculadora de poh", "calculadora ácido base"],
    formulaExplanationEs: "El pH es el logaritmo negativo en base diez de la concentración de iones de hidrógeno porque esas concentraciones abarcan muchos órdenes de magnitud, y un logaritmo comprime ese enorme rango en una cómoda escala de 0 a 14. El signo negativo hace que las disoluciones ácidas, que tienen concentraciones altas, correspondan a números de pH bajos. El pOH suma con el pH un total de 14 a 25 °C porque la autoionización del agua fija el producto de las concentraciones de iones de hidrógeno e hidróxido.",
    explanationEs: "El pH te dice cuán ácida o básica es una disolución, y esta calculadora de pH convierte una concentración de iones de hidrógeno en moles por litro en un valor de pH, su pOH correspondiente y una clasificación en lenguaje sencillo de ácida, neutra o básica. Como las concentraciones de iones de hidrógeno abarcan muchas potencias de diez, la escala logarítmica del pH las empaqueta ordenadamente entre 0 y 14, donde 7 es neutro, los números menores son ácidos y los mayores son básicos.\n\nAcertar con el pH importa en todas partes, desde el laboratorio hasta la vida diaria: gobierna la actividad enzimática del cuerpo, la seguridad del agua potable, la salud del suelo y los acuarios, y el resultado de innumerables reacciones químicas. Una calculadora de pH fiable elimina la complicada aritmética del logaritmo y el signo fácil de pasar por alto, para que pases directamente de una concentración medida a un resultado interpretable.\n\nLa fórmula funciona porque el pH es el logaritmo negativo de la concentración de iones de hidrógeno, convirtiendo números fraccionarios diminutos en una escala legible, mientras que el pOH completa la imagen ya que ambos suman siempre 14 en el agua a temperatura ambiente. Estudiantes de química, técnicos de laboratorio y científicos ambientales se apoyan en una calculadora de pH para comprobar la acidez con rapidez y precisión.",
    exampleEs: { inputs: { concentration: 0.001 }, explanation: "−log₁₀(0,001) = 3, así que pH = 3 (ácido) y pOH = 11." },
    faqsEs: [
      {
        question: "¿Qué mide realmente la escala de pH?",
        answer: "La escala de pH mide la concentración de iones de hidrógeno en una disolución en una escala logarítmica, indicando cuán ácida o básica es. Normalmente va de 0 a 14, con 7 como neutro, los valores por debajo de 7 ácidos y los superiores a 7 básicos. Como es logarítmica, cada paso de un número entero representa un cambio de diez veces en la concentración de iones de hidrógeno, así que el pH 4 es diez veces más ácido que el pH 5.",
      },
      {
        question: "¿Cómo se relacionan el pH y el pOH?",
        answer: "En el agua a 25 °C, el pH y el pOH siempre suman 14. Esto proviene de la autoionización del agua, donde el producto de las concentraciones de iones de hidrógeno e hidróxido es fijo en 10⁻¹⁴. Así que si conoces uno, conoces de inmediato el otro: una disolución con pH 3 tiene pOH 11. La calculadora calcula el pOH restando el pH de 14 automáticamente por ti.",
      },
      {
        question: "¿Qué concentración da un pH neutro?",
        answer: "Una disolución neutra a 25 °C tiene una concentración de iones de hidrógeno de 1×10⁻⁷ moles por litro, que produce un pH de exactamente 7. A esta concentración los iones de hidrógeno e hidróxido están perfectamente equilibrados, así que la disolución no es ni ácida ni básica. El agua pura se sitúa en este punto. Introducir 0,0000001 mol/L en la calculadora devuelve un pH de 7 y una clasificación de neutra.",
      },
      {
        question: "¿Puede el pH ser negativo o mayor que 14?",
        answer: "Sí, aunque es poco común en entornos cotidianos. Los ácidos fuertes muy concentrados pueden tener concentraciones de iones de hidrógeno superiores a 1 mol/L, produciendo un pH negativo, mientras que las bases fuertes extremadamente concentradas pueden empujar el pH por encima de 14. El rango de 0 a 14 es simplemente el que cubre la mayoría de las disoluciones acuosas, no un límite rígido. La calculadora maneja correctamente los valores fuera de esa ventana.",
      },
      {
        question: "¿Por qué la escala de pH es logarítmica en lugar de lineal?",
        answer: "Las concentraciones de iones de hidrógeno en disoluciones reales varían en un rango enorme, desde alrededor de 1 mol/L en ácidos fuertes hasta 10⁻¹⁴ mol/L en bases fuertes. Una escala lineal sería inservible a través de tantos órdenes de magnitud. La escala logarítmica de pH comprime ese rango en números simples entre 0 y 14, facilitando las comparaciones mientras aún capta las enormes diferencias subyacentes de acidez entre disoluciones.",
      },
    ],
  },
  {
    id: "speed-distance-time",
    slug: "speed-distance-time-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Speed Distance Time Calculator",
    shortDescription: "Solve for speed, distance or time.",
    seoTitle: "Speed Distance Time Calculator — Solve Any of the Three",
    metaDescription: "Free speed distance time calculator. Enter any two of speed, distance, or time to solve the third, with results in km/h, mph, and m/s. Fast and accurate.",
    primaryKeyword: "speed distance time calculator",
    secondaryKeywords: ["average speed calculator", "distance calculator", "travel time calculator"],
    fields: [
      { id: "speed", label: "Speed", type: "number", unit: "km/h", required: false, span: 1, helpText: "Enter any two of the three." },
      { id: "distance", label: "Distance", type: "number", unit: "km", required: false, span: 1 },
      { id: "time", label: "Time", type: "number", unit: "h", required: false, span: 2 },
    ],
    results: [
      { id: "speed", label: "Speed", format: "number", decimals: 2, unit: "km/h", isPrimary: true },
      { id: "distance", label: "Distance", format: "number", decimals: 2, unit: "km", isPrimary: false },
      { id: "time", label: "Time", format: "number", decimals: 2, unit: "h", isPrimary: false },
      { id: "mph", label: "Speed in mph", format: "number", decimals: 2, unit: "mph", isPrimary: false },
      { id: "ms", label: "Speed in m/s", format: "number", decimals: 2, unit: "m/s", isPrimary: false },
    ],
    formula: "speed = distance ÷ time",
    formulaExplanation: "Speed is defined as the distance travelled per unit of time, so dividing distance by time gives the average rate of travel. Rearranging the same relationship lets you find distance as speed times time, or time as distance divided by speed. The formula works because it is the definition of average speed itself, assuming steady motion over the interval, which is why any two of the three quantities fix the third.",
    explanation: "Speed, distance, and time are locked together by one simple relationship, and this speed distance time calculator lets you enter any two of them to solve for the missing value automatically. Whether you know how far you travelled and how long it took, or you know your speed and need to work out arrival time, the tool rearranges the equation for you and even converts the speed into kilometres per hour, miles per hour, and metres per second.\n\nThis matters for everyday planning and technical work alike: drivers estimating journey times, runners tracking pace, pilots and sailors plotting routes, and physics students solving motion problems all depend on it. A dependable speed distance time calculator removes the guesswork of dividing or multiplying under time pressure and the risk of mixing up which quantity to solve for.\n\nThe formula works because speed is by definition the distance covered in a given time, so the three values form a fixed triangle where knowing two always determines the third. By offering multiple speed units side by side, a speed distance time calculator bridges metric and imperial systems in one step, making it useful for travel, sport, engineering, and classroom exercises around the world.",
    example: { inputs: { distance: 100, time: 2 }, explanation: "100 km ÷ 2 h = 50 km/h (about 31.07 mph)." },
    faqs: [
      {
        question: "Which two values do I need to enter?",
        answer: "Enter any two of the three quantities — speed, distance, or time — and the calculator solves the remaining one. For example, supply distance and time to find speed, or supply speed and time to find distance. It also converts the resulting speed into miles per hour and metres per second. If you enter only one value the relationship is undetermined and no unique answer can be produced.",
      },
      {
        question: "Does this give average speed or instantaneous speed?",
        answer: "It gives average speed over the whole journey, calculated as total distance divided by total time. It does not capture moment-to-moment changes, so if you sped up and slowed down along the way, the figure represents the constant speed that would have covered the same distance in the same time. Instantaneous speed, like a speedometer reading, requires measuring distance over a very small time interval instead.",
      },
      {
        question: "What units does the calculator use?",
        answer: "Speed is entered in kilometres per hour, distance in kilometres, and time in hours. The primary speed result appears in km/h, and the calculator also converts it to miles per hour and metres per second for convenience. To convert time such as 90 minutes into hours, divide by 60 to get 1.5 hours before entering it, which keeps every result consistent and accurate.",
      },
      {
        question: "How do I convert between km/h, mph, and m/s?",
        answer: "To convert kilometres per hour to miles per hour, multiply by about 0.6214. To convert km/h to metres per second, divide by 3.6. The calculator performs both conversions automatically, showing all three units side by side so you never have to do the arithmetic yourself. This is especially handy when comparing metric road signs with imperial vehicles or converting figures for a physics problem.",
      },
      {
        question: "How do I handle time given in minutes?",
        answer: "Convert minutes into hours before entering the time, because the calculator expects hours. Divide the number of minutes by 60: 30 minutes becomes 0.5 hours, and 90 minutes becomes 1.5 hours. Entering minutes directly would make the speed appear sixty times too small. Once the time is in hours, the speed, distance, and unit conversions all come out correctly for your journey.",
      },
    ],
    relatedCalculators: ["kinetic-energy-calculator", "force-calculator", "ohms-law-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard physics (kinematics)",
    slugEs: "calculadora-de-velocidad-distancia-tiempo",
    titleEs: "Calculadora de Velocidad Distancia Tiempo",
    shortDescriptionEs: "Resuelve la velocidad, la distancia o el tiempo.",
    seoTitleEs: "Calculadora de Velocidad Distancia Tiempo — Resuelve Cualquiera de los Tres",
    metaDescriptionEs: "Calculadora gratuita de velocidad distancia tiempo. Introduce dos de tres (velocidad, distancia o tiempo) para resolver el tercero, con resultados en km/h, mph y m/s. Rápida y precisa.",
    primaryKeywordEs: "calculadora de velocidad distancia tiempo",
    secondaryKeywordsEs: ["calculadora de velocidad media", "calculadora de distancia", "calculadora de tiempo de viaje"],
    formulaExplanationEs: "La velocidad se define como la distancia recorrida por unidad de tiempo, así que dividir la distancia entre el tiempo da el ritmo medio de viaje. Reordenar la misma relación te permite hallar la distancia como velocidad por tiempo, o el tiempo como distancia dividida entre velocidad. La fórmula funciona porque es la definición misma de velocidad media, suponiendo movimiento constante durante el intervalo, y por eso dos cualesquiera de las tres magnitudes fijan la tercera.",
    explanationEs: "La velocidad, la distancia y el tiempo están unidos por una relación sencilla, y esta calculadora de velocidad distancia tiempo te permite introducir dos de ellas para resolver automáticamente el valor que falta. Ya sea que sepas qué distancia recorriste y cuánto tardaste, o que conozcas tu velocidad y necesites calcular la hora de llegada, la herramienta reordena la ecuación por ti e incluso convierte la velocidad en kilómetros por hora, millas por hora y metros por segundo.\n\nEsto importa tanto para la planificación cotidiana como para el trabajo técnico: conductores que estiman tiempos de viaje, corredores que controlan su ritmo, pilotos y navegantes que trazan rutas y estudiantes de física que resuelven problemas de movimiento dependen de ella. Una calculadora fiable elimina la incertidumbre de dividir o multiplicar con prisa y el riesgo de confundir qué magnitud despejar.\n\nLa fórmula funciona porque la velocidad es por definición la distancia recorrida en un tiempo dado, así que los tres valores forman un triángulo fijo donde conocer dos siempre determina el tercero. Al ofrecer varias unidades de velocidad lado a lado, una calculadora de velocidad distancia tiempo conecta los sistemas métrico e imperial en un solo paso, útil para viajes, deporte, ingeniería y ejercicios de clase.",
    exampleEs: { inputs: { distance: 100, time: 2 }, explanation: "100 km ÷ 2 h = 50 km/h (unas 31,07 mph)." },
    faqsEs: [
      {
        question: "¿Qué dos valores necesito introducir?",
        answer: "Introduce dos cualesquiera de las tres magnitudes (velocidad, distancia o tiempo) y la calculadora resuelve la restante. Por ejemplo, aporta distancia y tiempo para hallar la velocidad, o velocidad y tiempo para hallar la distancia. También convierte la velocidad resultante en millas por hora y metros por segundo. Si introduces solo un valor la relación queda indeterminada y no puede producirse una respuesta única.",
      },
      {
        question: "¿Esto da la velocidad media o la instantánea?",
        answer: "Da la velocidad media de todo el trayecto, calculada como la distancia total dividida entre el tiempo total. No capta los cambios de momento a momento, así que si aceleraste y frenaste por el camino, la cifra representa la velocidad constante que habría cubierto la misma distancia en el mismo tiempo. La velocidad instantánea, como la del velocímetro, requiere medir la distancia en un intervalo de tiempo muy pequeño.",
      },
      {
        question: "¿Qué unidades usa la calculadora?",
        answer: "La velocidad se introduce en kilómetros por hora, la distancia en kilómetros y el tiempo en horas. El resultado principal de velocidad aparece en km/h, y la calculadora también lo convierte a millas por hora y metros por segundo por comodidad. Para convertir un tiempo como 90 minutos en horas, divide entre 60 para obtener 1,5 horas antes de introducirlo, lo que mantiene cada resultado coherente.",
      },
      {
        question: "¿Cómo convierto entre km/h, mph y m/s?",
        answer: "Para convertir kilómetros por hora en millas por hora, multiplica por unos 0,6214. Para convertir km/h en metros por segundo, divide entre 3,6. La calculadora realiza ambas conversiones automáticamente, mostrando las tres unidades lado a lado para que nunca tengas que hacer la aritmética. Esto resulta especialmente práctico al comparar señales de carretera métricas con vehículos imperiales o al convertir cifras para un problema de física.",
      },
      {
        question: "¿Cómo manejo el tiempo dado en minutos?",
        answer: "Convierte los minutos en horas antes de introducir el tiempo, porque la calculadora espera horas. Divide el número de minutos entre 60: 30 minutos se convierten en 0,5 horas, y 90 minutos en 1,5 horas. Introducir minutos directamente haría que la velocidad pareciera sesenta veces menor. Una vez que el tiempo esté en horas, la velocidad, la distancia y las conversiones de unidad salen correctamente para tu trayecto.",
      },
    ],
  },
];
