import type { CalculatorDefinition } from "../types";

export const scienceR7Calculators: CalculatorDefinition[] = [
  {
    id: "work-done",
    slug: "work-done-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Work Done Calculator",
    shortDescription: "Calculate mechanical work from force and distance.",
    seoTitle: "Work Done Calculator — Force × Distance in Joules",
    metaDescription: "Free work done calculator. Enter force in newtons and distance in metres to find mechanical work in joules instantly. Ideal for physics homework and energy problems.",
    primaryKeyword: "work done calculator",
    secondaryKeywords: ["work formula calculator", "force times distance calculator", "mechanical work joules"],
    fields: [
      { id: "force", label: "Force", type: "number", unit: "N", required: true, span: 1 },
      { id: "distance", label: "Distance", type: "number", unit: "m", required: true, span: 1 },
    ],
    results: [
      { id: "work", label: "Work done", format: "number", decimals: 2, unit: "J", isPrimary: true },
    ],
    formula: "W = force × distance",
    formulaExplanation: "Work in physics is the energy transferred when a force moves an object through a distance, so multiplying force by the distance travelled along its direction gives the joules of energy delivered. The formula works because a constant force applied over a longer path does proportionally more work, and a larger force over the same path does proportionally more too. When force and motion are aligned, their simple product captures exactly how much mechanical energy changed hands, which is why work is measured in joules, the same unit as energy.",
    explanation: "Work done is one of the most fundamental ideas in mechanics, describing the energy transferred to or from an object when a force pushes it through a distance. This work done calculator multiplies the force you apply, in newtons, by the distance the object moves, in metres, to return the result in joules. If nothing moves, no work is done no matter how hard you push, which is why holding a heavy box still transfers no mechanical work even though it feels tiring.\n\nThis quantity matters because work is the bridge between force and energy: it tells you how much energy a machine, a person, or an engine delivers to accomplish a task. Lifting a load, dragging a crate, or compressing a spring all involve work, and calculating it lets engineers size motors, estimate fuel needs, and verify energy budgets. A work done calculator removes the arithmetic so you can focus on the physics.\n\nThe formula works because energy transfer scales with both the strength of the force and the length of the path over which it acts. Students, teachers, and engineers rely on a work done calculator to solve textbook problems, check designs, and build an intuition for how force and displacement combine to move energy from one place to another.",
    example: { inputs: { force: 100, distance: 5 }, explanation: "100 N × 5 m = 500 J of work done." },
    faqs: [
      {
        question: "What units should I use for force and distance?",
        answer: "Enter force in newtons and distance in metres, and the calculator returns work in joules, the SI unit of energy. One joule is the work done by a one-newton force acting over one metre. If your force is in kilonewtons or your distance in centimetres, convert to base units first so the result comes out correctly, since mixing units would scale the joule figure incorrectly.",
      },
      {
        question: "Why is no work done when nothing moves?",
        answer: "Work requires displacement, so if the distance is zero, the product of force and distance is zero regardless of how large the force is. Holding a weight steady involves plenty of muscular effort but transfers no mechanical work to the object because it does not move. In physics, work specifically measures energy delivered through motion, not the biological effort or strain that a person happens to feel.",
      },
      {
        question: "Can work done be negative?",
        answer: "Yes. Work is negative when the force acts opposite to the direction of motion, meaning it removes energy from the object rather than adding it. Friction and braking are classic examples: they oppose movement and do negative work, slowing things down. Entering a negative distance or opposing force into the calculator produces a negative result, correctly indicating that energy is being taken away instead of supplied.",
      },
      {
        question: "How does work relate to energy?",
        answer: "Work and energy share the same unit, the joule, because work is literally the transfer of energy by a force. The work-energy theorem states that the net work done on an object equals its change in kinetic energy. So calculating work tells you how much an object's energy has changed, whether it speeds up, slows down, or gains potential energy by being lifted against gravity.",
      },
      {
        question: "Does this formula assume force and motion are aligned?",
        answer: "Yes. This simple version assumes the force acts in the same direction as the displacement. When a force is applied at an angle, only the component along the direction of motion does work, so the full formula multiplies by the cosine of the angle between them. For straight pushes and pulls aligned with the movement, that cosine is one and the basic force-times-distance product applies directly.",
      },
    ],
    relatedCalculators: ["kinetic-energy-calculator", "force-calculator", "density-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (work-energy principle)",
  },
  {
    id: "efficiency",
    slug: "efficiency-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Efficiency Calculator",
    shortDescription: "Find energy efficiency as a percentage.",
    seoTitle: "Efficiency Calculator — Useful Output ÷ Input as a Percentage",
    metaDescription: "Free efficiency calculator. Enter useful output energy and total input energy to find efficiency as a percentage instantly. Perfect for physics and engineering problems.",
    primaryKeyword: "efficiency calculator",
    secondaryKeywords: ["energy efficiency calculator", "mechanical efficiency formula", "output input ratio calculator"],
    fields: [
      { id: "outputEnergy", label: "Useful output energy", type: "number", unit: "J", required: true, span: 1, min: 0 },
      { id: "inputEnergy", label: "Total input energy", type: "number", unit: "J", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "efficiency", label: "Efficiency", format: "percentage", decimals: 2, isPrimary: true },
    ],
    formula: "efficiency = (useful output ÷ total input) × 100%",
    formulaExplanation: "Efficiency measures what fraction of the energy you put into a device comes back out as useful work, so dividing useful output by total input and multiplying by 100 expresses that fraction as a percentage. The formula works because energy is conserved: every joule supplied either does useful work or is lost, usually as heat, sound, or friction. The ratio therefore shows how much of the input actually served its purpose, and it can never exceed 100 percent because a machine cannot produce more useful energy than it consumes.",
    explanation: "Efficiency tells you how good a machine or process is at turning the energy it consumes into useful output, and this efficiency calculator expresses that as a clean percentage from the output and input energies you enter. A perfectly efficient device would convert every joule of input into useful work, scoring 100 percent, but in the real world some energy always escapes as heat, friction, sound, or vibration, so practical efficiencies are always lower.\n\nThis figure matters because it drives cost, performance, and sustainability. A more efficient engine burns less fuel for the same output, a better power supply wastes less electricity, and an efficient appliance saves money and reduces emissions over its lifetime. Comparing efficiencies lets engineers, buyers, and students judge competing designs objectively rather than by guesswork, and an efficiency calculator makes that comparison instant.\n\nThe formula works because energy is conserved, so useful output divided by total input reveals exactly the share of energy that did its intended job. The remainder is the loss. Whether you are analysing a motor, a solar panel, a light bulb, or a simple machine like a pulley, an efficiency calculator turns raw energy figures into an intuitive percentage you can act on and compare across systems.",
    example: { inputs: { outputEnergy: 750, inputEnergy: 1000 }, explanation: "(750 ÷ 1000) × 100 = 75% efficiency; 250 J were lost." },
    faqs: [
      {
        question: "Can efficiency ever be more than 100 percent?",
        answer: "No. Because energy is conserved, a device can never deliver more useful output energy than the total energy supplied to it, so efficiency is always at or below 100 percent. A result above 100 percent would mean energy was created from nothing, which is impossible. If your calculation exceeds 100 percent, recheck your figures — you have likely mislabelled the input and output or missed a hidden energy source.",
      },
      {
        question: "What counts as useful output versus input?",
        answer: "Input is the total energy you supply to the device, such as the electricity, fuel, or mechanical energy fed in. Useful output is only the portion that performs the intended task, like the light from a bulb or the motion from a motor. Energy lost as waste heat, sound, or friction is not counted as useful output, which is exactly why real efficiencies fall below one hundred percent.",
      },
      {
        question: "Why does the calculator return NaN for zero input?",
        answer: "Efficiency divides useful output by total input, and dividing by zero is mathematically undefined, so the calculator returns a non-numeric result to signal that the calculation cannot proceed. A device with zero input energy has no meaningful efficiency because it is not consuming anything to convert. Enter a positive input value representing the actual energy supplied to obtain a valid efficiency percentage for your system.",
      },
      {
        question: "What is a typical efficiency for common machines?",
        answer: "Efficiency varies widely by technology. Electric motors often reach 85 to 95 percent, while petrol car engines convert only around 20 to 35 percent of fuel energy into motion, wasting the rest as heat. Incandescent bulbs are famously inefficient at roughly 5 percent, whereas LED lights exceed 40 percent. Comparing these figures shows why some technologies replace others on energy-saving grounds alone.",
      },
      {
        question: "Does this work for power as well as energy?",
        answer: "Yes. Efficiency is a ratio, so you can divide useful output power by total input power and multiply by 100 to get the same percentage, as long as both quantities use the same unit and time basis. Whether you measure in joules of energy or watts of power, the ratio is dimensionless and yields an identical efficiency figure for a steady, continuously operating device.",
      },
    ],
    relatedCalculators: ["work-done-calculator", "kinetic-energy-calculator", "force-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (conservation of energy)",
  },
  {
    id: "hydrostatic-pressure",
    slug: "hydrostatic-pressure-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Hydrostatic Pressure Calculator",
    shortDescription: "Find fluid pressure at a given depth.",
    seoTitle: "Hydrostatic Pressure Calculator — Fluid Pressure at Depth",
    metaDescription: "Free hydrostatic pressure calculator. Enter fluid density, depth, and gravity to find pressure in pascals instantly. Ideal for physics, diving, and engineering problems.",
    primaryKeyword: "hydrostatic pressure calculator",
    secondaryKeywords: ["fluid pressure calculator", "water pressure at depth", "pressure depth formula"],
    fields: [
      { id: "fluidDensity", label: "Fluid density", type: "number", unit: "kg/m³", required: true, span: 1, min: 0 },
      { id: "depth", label: "Depth", type: "number", unit: "m", required: true, span: 1, min: 0 },
      { id: "gravity", label: "Gravity", type: "number", unit: "m/s²", required: false, span: 2, defaultValue: 9.81, helpText: "Defaults to Earth's 9.81 m/s² if left blank." },
    ],
    results: [
      { id: "pressure", label: "Hydrostatic pressure", format: "number", decimals: 2, unit: "Pa", isPrimary: true },
    ],
    formula: "P = density × gravity × depth",
    formulaExplanation: "Hydrostatic pressure is the weight of the fluid column pressing down on a point, so multiplying fluid density by gravitational acceleration by depth gives the force per unit area at that depth. The formula works because a taller column of fluid contains more mass above the point, and a denser fluid packs more mass into the same height, both of which increase the downward force. Gravity converts that stacked mass into weight, and dividing by area is already built into using density, yielding pressure directly in pascals.",
    explanation: "Hydrostatic pressure is the pressure exerted by a fluid at rest due to the weight of the fluid above a given point, and this hydrostatic pressure calculator returns it from the fluid's density, the depth, and gravity. The deeper you go, the more fluid sits overhead, so the pressure climbs steadily with depth. This is why your ears pop at the bottom of a swimming pool and why submarines must be built to withstand crushing loads far below the surface.\n\nThis calculation matters across engineering, diving, and earth science. Dam walls are thicker at the base because pressure is greatest there, divers track pressure to manage their air and avoid injury, and tank designers use it to size walls that will not rupture. A hydrostatic pressure calculator makes these estimates quick, letting you compare fluids and depths without wrestling the formula by hand each time.\n\nThe formula works because pressure at depth equals the weight of the column of fluid pressing on each unit of area, which grows with density, gravity, and depth. Note that this gives the pressure due to the fluid alone; to find absolute pressure you add atmospheric pressure at the surface. Students, engineers, and divers all rely on a hydrostatic pressure calculator to predict how fluids push on the structures and bodies immersed in them.",
    example: { inputs: { fluidDensity: 1000, depth: 10, gravity: 9.81 }, explanation: "1000 kg/m³ × 9.81 m/s² × 10 m = 98,100 Pa (about one extra atmosphere)." },
    faqs: [
      {
        question: "Does this include atmospheric pressure?",
        answer: "No. This calculator returns the gauge pressure caused by the fluid column alone, not the absolute pressure. To find absolute pressure at that depth, add the atmospheric pressure acting on the fluid surface, roughly 101,325 pascals at sea level. Gauge pressure is what most engineering and diving calculations use because it represents the pressure above the surrounding atmosphere, which is the load a submerged structure actually experiences.",
      },
      {
        question: "What density should I use for water?",
        answer: "Fresh water has a density of about 1,000 kilograms per cubic metre, while seawater is denser at roughly 1,025 kilograms per cubic metre because of dissolved salts. Using the correct value matters for accuracy, since denser fluid produces higher pressure at the same depth. For other liquids, look up their density: mercury, for example, is about 13,600 kilograms per cubic metre and produces far greater pressure.",
      },
      {
        question: "Why does pressure not depend on the container's shape?",
        answer: "Hydrostatic pressure depends only on depth, density, and gravity, not on the width or shape of the container. This is known as the hydrostatic paradox: a narrow tube and a wide tank filled to the same depth exert the same pressure at the bottom. Pressure results from the height of the fluid column above a point, so only vertical depth matters, not how much total fluid surrounds it.",
      },
      {
        question: "How much does pressure increase per metre of water?",
        answer: "In fresh water, pressure rises by about 9,810 pascals for every metre of depth, which is close to one-tenth of an atmosphere per metre. This means that at ten metres deep, the fluid adds roughly one full atmosphere of pressure on top of the air pressure at the surface. Divers use this rule of thumb constantly to gauge the loads their bodies and equipment face.",
      },
      {
        question: "Can I use this for gases or only liquids?",
        answer: "The formula assumes constant density, which works well for liquids because they barely compress. Gases compress significantly under their own weight, so their density changes with height and this simple formula becomes inaccurate over large vertical distances. For thin gas layers or small depth changes it gives a reasonable approximation, but atmospheric pressure over kilometres requires a more complex model that accounts for varying density.",
      },
    ],
    relatedCalculators: ["density-calculator", "force-calculator", "work-done-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (Pascal's principle)",
  },
  {
    id: "heat-index",
    slug: "heat-index-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Heat Index Calculator",
    shortDescription: "Find the 'feels like' temperature from heat and humidity.",
    seoTitle: "Heat Index Calculator — 'Feels Like' Temperature (NWS Formula)",
    metaDescription: "Free heat index calculator using the NWS Rothfusz regression. Enter temperature and humidity to find the 'feels like' apparent temperature in Fahrenheit instantly.",
    primaryKeyword: "heat index calculator",
    secondaryKeywords: ["feels like temperature calculator", "apparent temperature calculator", "heat humidity index"],
    fields: [
      { id: "temperatureF", label: "Air temperature", type: "number", unit: "°F", required: true, span: 1 },
      { id: "humidityPercent", label: "Relative humidity", type: "number", unit: "%", required: true, span: 1, min: 0, max: 100 },
    ],
    results: [
      { id: "heatIndexF", label: "Heat index", format: "number", decimals: 1, unit: "°F", isPrimary: true },
    ],
    formula: "HI = −42.379 + 2.049·T + 10.143·R − 0.225·T·R − … (NWS Rothfusz regression)",
    formulaExplanation: "The heat index blends air temperature and relative humidity into a single apparent temperature because humid air slows the evaporation of sweat, the body's main cooling mechanism, making hot days feel hotter than the thermometer alone suggests. The National Weather Service Rothfusz regression is a multi-term polynomial fitted to detailed studies of human heat balance, so each term captures how temperature and moisture interact. The formula is only valid at or above 80°F; below that, sweat evaporation is efficient enough that the felt temperature simply equals the measured air temperature.",
    explanation: "The heat index, often called the 'feels like' temperature, combines air temperature and relative humidity to estimate how hot conditions actually feel to the human body. This heat index calculator uses the official National Weather Service Rothfusz regression, the same equation behind the warnings you see on hot summer days. When humidity is high, sweat evaporates slowly, so your body struggles to shed heat and the air feels far hotter than the thermometer reads.\n\nThis matters for health and safety. High heat index values signal real danger of heat exhaustion and heat stroke, especially for outdoor workers, athletes, children, and older adults. Event organisers, coaches, and employers use the heat index to decide when to schedule breaks, cancel activities, or issue warnings. Knowing the apparent temperature rather than just the raw reading helps people take humidity seriously as a hazard, not just an inconvenience.\n\nThe formula works because it was fitted to research on human thermoregulation, weighting temperature and moisture the way the body experiences them. It applies at or above 80°F, where humidity meaningfully impairs cooling; below that threshold this calculator returns the air temperature itself, since evaporation keeps pace. Meteorologists, planners, and anyone facing a hot, muggy forecast rely on a heat index calculator to judge the true risk of the conditions ahead.",
    example: { inputs: { temperatureF: 90, humidityPercent: 70 }, explanation: "At 90°F and 70% humidity the air feels like about 106°F — well into the caution range." },
    faqs: [
      {
        question: "Why does humidity make it feel hotter?",
        answer: "Your body cools itself mainly by sweating, and sweat carries heat away as it evaporates from your skin. When the air is already saturated with moisture, evaporation slows dramatically, so less heat leaves your body and you feel hotter than the actual temperature. That is why a humid 90-degree day feels far more oppressive than a dry one, and why the heat index folds humidity into a single felt temperature.",
      },
      {
        question: "Why does the calculator return the air temperature below 80°F?",
        answer: "The National Weather Service Rothfusz regression was developed and validated only for temperatures at or above 80 degrees Fahrenheit, where humidity meaningfully impairs the body's cooling. Below that threshold sweat evaporates efficiently regardless of moisture, so the apparent temperature is essentially the same as the measured air temperature. To stay accurate, this calculator returns the air temperature directly when you enter a value under 80 degrees.",
      },
      {
        question: "What heat index values are dangerous?",
        answer: "The National Weather Service flags caution from about 80 to 90 degrees, extreme caution from 90 to 103, danger from 103 to 124, and extreme danger above 124 degrees Fahrenheit. As the index rises, the risks of heat cramps, heat exhaustion, and life-threatening heat stroke increase, especially with prolonged exposure or physical activity. Use these bands to decide when to rest, hydrate, seek shade, or stop outdoor work entirely.",
      },
      {
        question: "Does the heat index account for sun and wind?",
        answer: "No. The standard heat index assumes shady, light-wind conditions, so direct sunlight can add as much as 15 degrees Fahrenheit to the felt temperature. Wind can lower it slightly by aiding evaporation, though hot wind can also increase heat stress. Because it ignores these factors, treat the heat index as a baseline and stay extra cautious when you are exposed to strong sun or still, stagnant air.",
      },
      {
        question: "What units does this calculator use?",
        answer: "This calculator uses Fahrenheit for temperature and a percentage from 0 to 100 for relative humidity, matching the National Weather Service formula it is built on. If your temperature is in Celsius, convert it first by multiplying by 1.8 and adding 32. The resulting heat index is also reported in Fahrenheit, the standard unit for heat advisories issued across the United States.",
      },
    ],
    relatedCalculators: ["wind-chill-calculator", "dew-point-calculator", "density-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "NWS Rothfusz heat index regression",
    sourceUrl: "https://www.weather.gov/ama/heatindex",
  },
  {
    id: "wind-chill",
    slug: "wind-chill-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Wind Chill Calculator",
    shortDescription: "Find the 'feels like' temperature in cold, windy weather.",
    seoTitle: "Wind Chill Calculator — 'Feels Like' Cold Temperature (NWS)",
    metaDescription: "Free wind chill calculator using the NWS formula. Enter temperature and wind speed to find the 'feels like' wind chill temperature in Fahrenheit instantly.",
    primaryKeyword: "wind chill calculator",
    secondaryKeywords: ["feels like cold calculator", "wind chill temperature formula", "wind chill factor calculator"],
    fields: [
      { id: "temperatureF", label: "Air temperature", type: "number", unit: "°F", required: true, span: 1 },
      { id: "windSpeedMph", label: "Wind speed", type: "number", unit: "mph", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "windChillF", label: "Wind chill", format: "number", decimals: 1, unit: "°F", isPrimary: true },
    ],
    formula: "WC = 35.74 + 0.6215·T − 35.75·V^0.16 + 0.4275·T·V^0.16 (NWS)",
    formulaExplanation: "Wind chill expresses how cold the air feels because wind strips away the thin layer of warm air your body heats around its skin, accelerating heat loss and making a cold day feel colder. The National Weather Service formula raises wind speed to the 0.16 power because heat loss rises quickly at first and then levels off as the wind increases. The temperature and wind terms combine to model the actual rate of heat loss from exposed skin, producing an equivalent 'feels like' temperature that captures the danger of frostbite better than the thermometer alone.",
    explanation: "Wind chill is the 'feels like' temperature on a cold day, capturing how wind makes frigid air feel even colder against your skin. This wind chill calculator uses the official National Weather Service formula, which was revised in 2001 to better reflect how quickly exposed human skin loses heat. As wind speeds up, it carries away the warm boundary layer your body maintains, so heat escapes faster and the effective temperature drops well below the thermometer reading.\n\nThis matters because wind chill is a direct measure of frostbite and hypothermia risk. On a still day, cold is uncomfortable but manageable; add a stiff wind and exposed skin can freeze in minutes. Meteorologists issue wind chill advisories and warnings on this basis, and workers, commuters, and outdoor enthusiasts use it to decide how to dress and how long they can safely stay outside. A wind chill calculator turns raw temperature and wind readings into an actionable danger level.\n\nThe formula works by modelling heat loss from bare skin as a function of both temperature and wind speed, with wind's effect tapering off at higher speeds. Because it reflects physiology rather than just physics, the wind chill can be many degrees below the actual air temperature. Anyone facing cold, blustery conditions relies on a wind chill calculator to understand the true severity of the weather and protect against cold-weather injury.",
    example: { inputs: { temperatureF: 30, windSpeedMph: 15 }, explanation: "At 30°F with a 15 mph wind the air feels like about 19°F." },
    faqs: [
      {
        question: "How does wind make cold feel colder?",
        answer: "Your body warms a thin layer of air right against your skin, which acts as insulation. Wind constantly blows that warm layer away and replaces it with cold air, forcing your body to keep reheating fresh air and losing heat faster. The stronger the wind, the quicker this heat loss, which is why a windy cold day feels far more biting than a calm one at the same temperature.",
      },
      {
        question: "Does wind chill affect objects or only people?",
        answer: "Wind chill describes how cold the air feels to exposed human skin, based on the rate of heat loss from a warm body. Inanimate objects like car radiators or water pipes cannot cool below the actual air temperature no matter how hard the wind blows, because they generate no heat of their own. Wind speeds their cooling toward the air temperature but never past it, so wind chill applies to living, heat-producing bodies.",
      },
      {
        question: "At what wind chill does frostbite become a risk?",
        answer: "The National Weather Service warns that frostbite can occur on exposed skin within about 30 minutes when the wind chill falls to around minus 18 degrees Fahrenheit, and within just a few minutes at minus 40 and below. The colder the wind chill, the faster skin freezes. Cover exposed skin, limit time outdoors, and watch for numbness or waxy white patches that signal the earliest stages of frostbite.",
      },
      {
        question: "Why does the formula only apply in cold weather?",
        answer: "The National Weather Service wind chill formula is defined for temperatures at or below 50 degrees Fahrenheit and wind speeds above about 3 miles per hour, because wind chill is only meaningful when the air is cold enough to draw heat from the body. In warm conditions, moving air feels cooling and pleasant rather than dangerous, so a different concept, the heat index, is used to describe hot-weather comfort instead.",
      },
      {
        question: "What units does this calculator use?",
        answer: "This calculator uses Fahrenheit for temperature and miles per hour for wind speed, matching the National Weather Service formula. If your temperature is in Celsius, convert it by multiplying by 1.8 and adding 32, and convert wind speed from kilometres per hour to miles per hour by dividing by 1.609. The resulting wind chill is reported in Fahrenheit, the standard unit for United States cold-weather advisories.",
      },
    ],
    relatedCalculators: ["heat-index-calculator", "dew-point-calculator", "kinetic-energy-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "NWS wind chill temperature index (2001)",
    sourceUrl: "https://www.weather.gov/safety/cold-wind-chill-chart",
  },
  {
    id: "dew-point",
    slug: "dew-point-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Dew Point Calculator",
    shortDescription: "Find the dew point from temperature and humidity.",
    seoTitle: "Dew Point Calculator — Temperature & Humidity to Dew Point",
    metaDescription: "Free dew point calculator using the Magnus formula. Enter air temperature and relative humidity to find the dew point in Celsius instantly. Great for weather and comfort.",
    primaryKeyword: "dew point calculator",
    secondaryKeywords: ["dew point formula calculator", "humidity dew point", "magnus formula calculator"],
    fields: [
      { id: "temperatureC", label: "Air temperature", type: "number", unit: "°C", required: true, span: 1 },
      { id: "humidityPercent", label: "Relative humidity", type: "number", unit: "%", required: true, span: 1, min: 0, max: 100 },
    ],
    results: [
      { id: "dewPointC", label: "Dew point", format: "number", decimals: 1, unit: "°C", isPrimary: true },
    ],
    formula: "γ = (a·T)/(b+T) + ln(RH/100);  dew point = b·γ/(a−γ),  a = 17.27, b = 237.7",
    formulaExplanation: "The dew point is the temperature at which air becomes fully saturated and water vapour begins to condense, so it depends on both how warm the air is and how much moisture it holds. The Magnus formula works by relating saturation vapour pressure to temperature through an exponential fit, then using relative humidity to find the temperature at which the current moisture content would saturate the air. The intermediate term gamma combines the temperature effect and the logarithm of humidity, and solving for the saturation temperature yields the dew point directly in Celsius.",
    explanation: "The dew point is the temperature to which air must cool for water vapour to start condensing into dew, fog, or clouds. This dew point calculator uses the widely trusted Magnus formula to derive it from the air temperature and relative humidity you enter. Unlike relative humidity, which changes as the air warms or cools, the dew point is an absolute measure of how much moisture the air actually contains, which makes it the meteorologist's favourite gauge of muggy or dry conditions.\n\nThis matters for comfort, weather, and building science. A high dew point above roughly 20°C feels sticky and oppressive because your sweat cannot evaporate, while a low dew point feels crisp and dry. Forecasters use it to predict fog, frost, and thunderstorms, and engineers use it to prevent condensation that causes mould, corrosion, and window fogging. A dew point calculator turns a temperature and humidity reading into this single, meaningful comfort and moisture indicator.\n\nThe formula works by finding the temperature at which the air's current moisture content would saturate it completely. Because the dew point can never exceed the air temperature, cooling air toward its dew point raises relative humidity until condensation begins. Weather watchers, HVAC designers, farmers, and pilots all rely on a dew point calculator to anticipate moisture behaviour and judge how the air will really feel.",
    example: { inputs: { temperatureC: 25, humidityPercent: 60 }, explanation: "At 25°C and 60% humidity the dew point is about 16.7°C — a mildly humid, comfortable feel." },
    faqs: [
      {
        question: "How is dew point different from relative humidity?",
        answer: "Relative humidity is the percentage of moisture the air holds compared with the most it could hold at that temperature, so it changes as the air warms or cools even when the actual moisture stays fixed. Dew point is an absolute temperature that reflects the real amount of water vapour present. Because it does not swing with temperature, dew point is a more reliable indicator of how humid or muggy the air genuinely feels.",
      },
      {
        question: "What dew point feels comfortable?",
        answer: "A dew point below about 10 degrees Celsius feels dry and comfortable, while 10 to 16 degrees feels pleasant to slightly humid. From 16 to 20 degrees the air starts to feel sticky, and above 20 degrees it becomes oppressive and uncomfortable because sweat evaporates poorly. Dew points above 24 degrees are rare and feel oppressively tropical. These bands make dew point a handy shorthand for describing summer comfort.",
      },
      {
        question: "Can the dew point be higher than the air temperature?",
        answer: "No. The dew point can equal the air temperature, which happens at 100 percent relative humidity when the air is fully saturated and fog or dew forms, but it can never exceed it. If it could, the air would hold more moisture than physically possible. As air cools toward its dew point, relative humidity rises to 100 percent, and any further cooling forces water vapour to condense out.",
      },
      {
        question: "Why does dew form on grass overnight?",
        answer: "On clear, calm nights the ground radiates heat away and cools faster than the air above it. When surfaces like grass or car windows drop below the dew point of the surrounding air, the water vapour touching them condenses into liquid droplets we call dew. If the dew point is below freezing, that same process produces frost instead, as the vapour deposits directly as ice crystals.",
      },
      {
        question: "What units does this calculator use?",
        answer: "This calculator takes air temperature in degrees Celsius and relative humidity as a percentage from 0 to 100, and it returns the dew point in degrees Celsius. If your temperature is in Fahrenheit, convert it by subtracting 32 and dividing by 1.8 before entering it. The Magnus coefficients used here, 17.27 and 237.7, are the standard values that keep the result accurate across typical everyday weather conditions.",
      },
    ],
    relatedCalculators: ["heat-index-calculator", "wind-chill-calculator", "density-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Magnus-Tetens dew point approximation (NWS)",
    sourceUrl: "https://www.weather.gov/epz/wxcalc_rh",
  },
  {
    id: "terminal-velocity",
    slug: "terminal-velocity-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Terminal Velocity Calculator",
    shortDescription: "Find the maximum falling speed through a fluid.",
    seoTitle: "Terminal Velocity Calculator — Maximum Falling Speed",
    metaDescription: "Free terminal velocity calculator. Enter mass, drag coefficient, area, and fluid density to find the maximum falling speed in m/s. Great for physics and skydiving.",
    primaryKeyword: "terminal velocity calculator",
    secondaryKeywords: ["falling speed calculator", "drag terminal velocity formula", "skydiver terminal velocity"],
    fields: [
      { id: "mass", label: "Mass", type: "number", unit: "kg", required: true, span: 1, min: 0 },
      { id: "dragCoefficient", label: "Drag coefficient", type: "number", required: true, span: 1, min: 0, helpText: "Dimensionless; ~1.0 for a spread skydiver, ~0.5 for a sphere." },
      { id: "crossSectionalArea", label: "Cross-sectional area", type: "number", unit: "m²", required: true, span: 1, min: 0 },
      { id: "fluidDensity", label: "Fluid density", type: "number", unit: "kg/m³", required: false, span: 1, defaultValue: 1.225, helpText: "Defaults to air at 1.225 kg/m³." },
      { id: "gravity", label: "Gravity", type: "number", unit: "m/s²", required: false, span: 2, defaultValue: 9.81, helpText: "Defaults to Earth's 9.81 m/s²." },
    ],
    results: [
      { id: "terminalVelocity", label: "Terminal velocity", format: "number", decimals: 2, unit: "m/s", isPrimary: true },
    ],
    formula: "vₜ = √( 2·m·g ÷ (ρ·A·C_d) )",
    formulaExplanation: "Terminal velocity is the steady speed a falling object reaches when air resistance grows strong enough to exactly balance gravity, so acceleration stops. Setting the drag force equal to weight and solving for speed gives the square root of twice the weight divided by the product of fluid density, cross-sectional area, and drag coefficient. The formula works because drag rises with the square of speed, so a falling object accelerates only until drag catches up with its weight; a heavier object needs more speed to generate matching drag, while a larger or blunter shape reaches balance sooner.",
    explanation: "Terminal velocity is the constant maximum speed an object reaches as it falls through a fluid such as air, when the upward drag force finally balances the downward pull of gravity. This terminal velocity calculator computes it from the object's mass, its drag coefficient, its cross-sectional area, and the fluid density. Once these forces balance, the object stops accelerating and falls at a steady speed, which is why a skydiver does not keep speeding up indefinitely.\n\nThis matters in skydiving, ballistics, meteorology, and engineering. It explains why a spread-eagled skydiver falls at around 120 miles per hour but slows dramatically once a parachute vastly increases area and drag, why raindrops of different sizes hit the ground at survivable speeds, and how designers predict the descent of everything from seeds to spacecraft. A terminal velocity calculator lets you explore how mass, shape, and air density each shift that limiting speed.\n\nThe formula works because drag force increases with the square of speed, so an object accelerates only until drag equals its weight, then falls steadily. Heavier or more streamlined objects reach higher terminal velocities, while larger frontal area, denser fluid, or a blunter shape lowers it. Physics students, skydivers, and engineers use a terminal velocity calculator to understand and predict how objects settle into their steady falling speed.",
    example: { inputs: { mass: 80, dragCoefficient: 1.0, crossSectionalArea: 0.7, fluidDensity: 1.225, gravity: 9.81 }, explanation: "An 80 kg skydiver with Cd 1.0 and 0.7 m² area reaches about 42.8 m/s (~154 km/h)." },
    faqs: [
      {
        question: "Why does a falling object stop accelerating?",
        answer: "As an object falls, air resistance, or drag, increases with the square of its speed. It keeps accelerating until the upward drag force grows large enough to exactly cancel the downward force of gravity. At that point the net force is zero, so by Newton's second law the acceleration is zero and the object falls at a constant speed, its terminal velocity, for the rest of the descent.",
      },
      {
        question: "What is the drag coefficient and what value should I use?",
        answer: "The drag coefficient is a dimensionless number describing how streamlined a shape is, with lower values meaning less resistance. A smooth sphere is about 0.5, a flat plate facing the flow around 1.1, and a belly-to-earth skydiver roughly 1.0. Streamlined shapes like a diving falcon or a bullet have much smaller coefficients. Choose a value that matches your object's shape and orientation for an accurate terminal velocity.",
      },
      {
        question: "Why do heavier objects fall faster in air?",
        answer: "In a vacuum, all objects fall at the same rate regardless of mass, but in air, drag depends on size and shape rather than mass. A heavier object of the same shape must reach a higher speed before drag grows enough to balance its greater weight, so it settles at a higher terminal velocity. This is why a marble falls faster than a feather in air, even though they would drop together in a vacuum.",
      },
      {
        question: "How does a parachute change terminal velocity?",
        answer: "A parachute dramatically increases both the cross-sectional area and the effective drag coefficient of a falling system. Because terminal velocity is inversely proportional to the square root of area and drag coefficient, this large increase sharply reduces the steady falling speed. A skydiver falling at roughly 55 metres per second can slow to around 5 metres per second under an open canopy, making a safe landing possible.",
      },
      {
        question: "What fluid density should I enter?",
        answer: "For an object falling through air at sea level, use about 1.225 kilograms per cubic metre, which is this calculator's default. Air is thinner at high altitude, lowering density and raising terminal velocity, while denser fluids like water dramatically reduce it. If you are modelling a fall through water, use roughly 1,000 kilograms per cubic metre instead, and the object will reach a far lower steady speed.",
      },
    ],
    relatedCalculators: ["kinetic-energy-calculator", "force-calculator", "escape-velocity-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (drag equation)",
  },
  {
    id: "escape-velocity",
    slug: "escape-velocity-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Escape Velocity Calculator",
    shortDescription: "Find the speed needed to escape a planet's gravity.",
    seoTitle: "Escape Velocity Calculator — Speed to Escape Gravity",
    metaDescription: "Free escape velocity calculator. Enter a planet or star's mass and radius to find the escape velocity in m/s instantly. Perfect for astronomy and physics problems.",
    primaryKeyword: "escape velocity calculator",
    secondaryKeywords: ["escape speed calculator", "gravity escape velocity formula", "planet escape velocity"],
    fields: [
      { id: "mass", label: "Mass of body", type: "number", unit: "kg", required: true, span: 1, min: 0, helpText: "Earth ≈ 5.972e24 kg." },
      { id: "radius", label: "Radius", type: "number", unit: "m", required: true, span: 1, min: 0, helpText: "Earth ≈ 6.371e6 m." },
    ],
    results: [
      { id: "escapeVelocity", label: "Escape velocity", format: "number", decimals: 2, unit: "m/s", isPrimary: true },
    ],
    formula: "vₑ = √( 2·G·M ÷ r ),  G = 6.674×10⁻¹¹",
    formulaExplanation: "Escape velocity is the minimum speed an object needs to break free of a body's gravity without further propulsion, and it comes from setting the object's kinetic energy equal to the gravitational potential energy binding it. Solving that energy balance gives the square root of twice the gravitational constant times the body's mass divided by its radius. The formula works because a more massive body pulls harder and requires more speed, while starting farther from the centre, at a larger radius, weakens the pull and lowers the escape speed. Notably it does not depend on the escaping object's own mass.",
    explanation: "Escape velocity is the minimum speed an object must reach to break free of a planet, moon, or star's gravitational pull and never fall back, without any additional thrust. This escape velocity calculator computes it from the celestial body's mass and radius using Newton's law of gravitation. For Earth this speed is about 11.2 kilometres per second, roughly 33 times the speed of sound, which is why launching into space demands such enormous rockets.\n\nThis concept matters for spaceflight, astronomy, and planetary science. Mission planners use escape velocity to work out the energy a spacecraft needs to leave Earth or land on and depart from another world. It also explains why small bodies like the Moon cannot hold onto an atmosphere, since gas molecules easily exceed the low escape speed, while massive planets like Jupiter retain thick atmospheres. A black hole, in the extreme, has an escape velocity exceeding the speed of light.\n\nThe formula works by balancing kinetic energy against gravitational potential energy, so escape velocity rises with the body's mass and falls as the launch radius increases. Remarkably, it does not depend on the mass of the escaping object, so a pebble and a spacecraft need the same speed. Astronomers, engineers, and physics students rely on an escape velocity calculator to compare worlds and plan the energy budgets of space missions.",
    example: { inputs: { mass: 5.972e24, radius: 6.371e6 }, explanation: "For Earth's mass and radius the escape velocity is about 11,186 m/s (11.2 km/s)." },
    faqs: [
      {
        question: "Does escape velocity depend on the object's mass?",
        answer: "No, and this surprises many people. The escaping object's own mass cancels out of the equation because both its kinetic energy and its gravitational potential energy scale with that mass in the same way. This means a tiny pebble and a massive spacecraft need exactly the same speed to escape a given body. Only the mass and radius of the body being escaped from determine the required velocity.",
      },
      {
        question: "Why is Earth's escape velocity about 11.2 km/s?",
        answer: "Plugging Earth's mass of roughly 5.972×10²⁴ kilograms and radius of about 6,371 kilometres into the formula yields around 11,186 metres per second, or 11.2 kilometres per second. This is the speed an object launched straight up would need to coast away forever without further power. It reflects the balance between Earth's substantial mass, which pulls objects back, and its radius, which sets the starting distance from the centre.",
      },
      {
        question: "Do rockets actually reach escape velocity at launch?",
        answer: "Not instantly. Escape velocity is the speed needed to coast away with no further thrust from the surface, but rockets burn fuel continuously, so they can leave more gradually by maintaining thrust. Most launches first reach orbital velocity, about 7.9 kilometres per second, to circle Earth, and only missions leaving Earth entirely build up to escape velocity. Continuous propulsion means a rocket never has to hit that full speed in one sudden burst.",
      },
      {
        question: "How does radius affect escape velocity?",
        answer: "Escape velocity is inversely proportional to the square root of the radius, so starting farther from a body's centre lowers the speed required to escape. Launching from a mountaintop or from orbit needs slightly less than launching from the surface. This also means that for two bodies of equal mass, the more compact one with the smaller radius has the higher escape velocity, because its surface sits deeper in the gravity well.",
      },
      {
        question: "What is the connection to black holes?",
        answer: "A black hole is an object so compact that its escape velocity at the event horizon reaches the speed of light. Because nothing can travel faster than light, nothing, not even light itself, can escape once it crosses that boundary. Applying the same formula with an extremely large mass packed into a tiny radius drives the escape velocity up to and beyond light speed, which is the defining feature of a black hole.",
      },
    ],
    relatedCalculators: ["terminal-velocity-calculator", "kinetic-energy-calculator", "force-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (Newtonian gravitation)",
  },
  {
    id: "thin-lens",
    slug: "thin-lens-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Thin Lens Calculator",
    shortDescription: "Find focal length from object and image distance.",
    seoTitle: "Thin Lens Calculator — Focal Length from Object & Image Distance",
    metaDescription: "Free thin lens calculator. Enter object distance and image distance to find the focal length in centimetres using the thin lens equation. Ideal for optics problems.",
    primaryKeyword: "thin lens calculator",
    secondaryKeywords: ["lens equation calculator", "focal length calculator", "optics thin lens formula"],
    fields: [
      { id: "objectDistance", label: "Object distance", type: "number", unit: "cm", required: true, span: 1, helpText: "Distance from lens to object." },
      { id: "imageDistance", label: "Image distance", type: "number", unit: "cm", required: true, span: 1, helpText: "Distance from lens to image." },
    ],
    results: [
      { id: "focalLength", label: "Focal length", format: "number", decimals: 2, unit: "cm", isPrimary: true },
    ],
    formula: "1/f = 1/dₒ + 1/dᵢ",
    formulaExplanation: "The thin lens equation relates the focal length of a lens to the distances of the object and its image because a lens bends light by a fixed amount set by its shape, focusing rays from a given object distance to a matching image distance. Adding the reciprocals of the object and image distances gives the reciprocal of the focal length, so the focal length is one divided by that sum. The formula works for lenses thin enough that their thickness is negligible, letting all the bending be treated as happening at a single plane, which keeps the geometry of converging rays simple.",
    explanation: "The thin lens equation is the cornerstone of geometric optics, linking a lens's focal length to where an object sits and where its image forms. This thin lens calculator takes the object distance and image distance you measure and returns the focal length in centimetres. The focal length describes how strongly a lens bends light: a short focal length bends rays sharply, while a long one bends them gently, and it stays fixed for a given lens regardless of what you view through it.\n\nThis matters throughout photography, vision science, and instrument design. It determines where a camera must focus, how eyeglasses correct blurry vision, and how microscopes and telescopes magnify. By relating three measurable distances, the equation lets you predict image position, design lens systems, and diagnose focusing problems. A thin lens calculator removes the fiddly reciprocal arithmetic, so you can move quickly from measured distances to the focal length that characterises the lens.\n\nThe formula works because a thin lens bends incoming light by a fixed amount, so rays from an object at a given distance always converge to a predictable image distance. Adding the reciprocals of those two distances yields the reciprocal of the focal length. Following the sign convention, where real images and converging lenses take positive values, students, photographers, and optical engineers rely on a thin lens calculator to design and understand imaging systems.",
    example: { inputs: { objectDistance: 30, imageDistance: 15 }, explanation: "1/f = 1/30 + 1/15 = 1/10, so the focal length is 10 cm." },
    faqs: [
      {
        question: "What sign convention does this calculator use?",
        answer: "This calculator follows the common convention where distances measured on the real side of the lens are positive. For a converging lens forming a real image, both the object distance and image distance are positive, giving a positive focal length. If you are working with virtual images or diverging lenses, enter the appropriate negative distances, and the resulting focal length sign will correctly indicate whether the lens converges or diverges light.",
      },
      {
        question: "What does the focal length tell me about a lens?",
        answer: "Focal length measures how strongly a lens converges or diverges light. A short focal length bends rays sharply and produces a wide field of view with strong magnification changes, while a long focal length bends light gently and narrows the field. In cameras, short focal lengths give wide-angle shots and long ones give telephoto zoom. The focal length is a fixed property of the lens set by its shape and material.",
      },
      {
        question: "What is the difference between a real and virtual image?",
        answer: "A real image forms where light rays actually converge and can be projected onto a screen, like the image inside a camera or on a cinema screen. A virtual image forms where rays only appear to originate, such as the upright, magnified view through a magnifying glass, and cannot be projected. The sign of the image distance tells you which type you have: positive for real, negative for virtual, in this convention.",
      },
      {
        question: "Why is it called the thin lens equation?",
        answer: "The equation assumes the lens is thin enough that its physical thickness is negligible compared with the object and image distances. This lets all the light bending be treated as if it happens at a single plane in the centre of the lens, which greatly simplifies the geometry. Real thick lenses require more complex modelling with principal planes, but for most everyday lenses the thin lens approximation is accurate and convenient.",
      },
      {
        question: "Can I use this equation to find magnification?",
        answer: "Yes, once you know the object and image distances you can find magnification separately as the negative ratio of image distance to object distance. A magnification magnitude greater than one means the image is enlarged, while less than one means it is reduced, and a negative sign indicates the image is inverted. This calculator focuses on focal length, but the same two distances feed directly into that magnification relationship.",
      },
    ],
    relatedCalculators: ["speed-distance-time-calculator", "density-calculator", "kinetic-energy-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (thin lens equation)",
  },
  {
    id: "doppler-effect",
    slug: "doppler-effect-calculator",
    category: "Science",
    categorySlug: "science",
    title: "Doppler Effect Calculator",
    shortDescription: "Find the observed frequency from a moving source.",
    seoTitle: "Doppler Effect Calculator — Observed Frequency of a Moving Source",
    metaDescription: "Free Doppler effect calculator. Enter source frequency, source speed, and direction to find the observed frequency in Hz. Great for sound and physics problems.",
    primaryKeyword: "doppler effect calculator",
    secondaryKeywords: ["doppler shift calculator", "observed frequency calculator", "sound frequency doppler"],
    fields: [
      { id: "sourceFrequency", label: "Source frequency", type: "number", unit: "Hz", required: true, span: 1, min: 0 },
      { id: "sourceSpeed", label: "Source speed", type: "number", unit: "m/s", required: true, span: 1, min: 0 },
      { id: "speedOfSound", label: "Speed of sound", type: "number", unit: "m/s", required: false, span: 1, defaultValue: 343, helpText: "Defaults to 343 m/s (air at 20°C)." },
      {
        id: "direction",
        label: "Source direction",
        type: "select",
        required: true,
        span: 1,
        defaultValue: "approaching",
        options: [
          { value: "approaching", label: "Approaching the observer" },
          { value: "receding", label: "Receding from the observer" },
        ],
      },
    ],
    results: [
      { id: "observedFrequency", label: "Observed frequency", format: "number", decimals: 2, unit: "Hz", isPrimary: true },
    ],
    formula: "approaching: f' = f · c/(c − vₛ)   ·   receding: f' = f · c/(c + vₛ)",
    formulaExplanation: "The Doppler effect changes the frequency an observer hears because a moving source compresses the sound waves ahead of it and stretches those behind it. When the source approaches, each successive wave crest is emitted a little closer, so the waves bunch up, the wavelength shortens, and the observed frequency rises; dividing by (c minus the source speed) captures this compression. When the source recedes, the crests spread out and the frequency drops, so the formula divides by (c plus the source speed). The speed of sound sets how fast the waves travel relative to the moving source.",
    explanation: "The Doppler effect is the change in the frequency of a wave that an observer detects when the source is moving relative to them. This Doppler effect calculator computes the observed frequency for sound from a moving source and a stationary observer, using the source frequency, the source's speed, the speed of sound, and whether the source is approaching or receding. It is the physics behind the familiar rise and fall in pitch of a passing siren or racing car.\n\nThis matters well beyond everyday sound. Doppler radar tracks the motion of storms and speeding vehicles, medical ultrasound measures blood flow, and astronomers use the Doppler shift of light to discover that distant galaxies are receding, evidence that the universe is expanding. Understanding how motion shifts frequency lets engineers and scientists turn a pitch or colour change into a precise measurement of speed.\n\nThe formula works because a source moving toward you emits each wave crest from a slightly closer position, bunching the waves into a higher frequency, while a receding source stretches them into a lower one. Selecting the direction tells the calculator whether to divide by the speed of sound minus or plus the source speed. Physics students, engineers, and anyone curious about that shifting siren pitch rely on a Doppler effect calculator to quantify exactly how much the frequency changes.",
    example: { inputs: { sourceFrequency: 440, sourceSpeed: 30, speedOfSound: 343, direction: "approaching" }, explanation: "A 440 Hz source approaching at 30 m/s is heard at about 482 Hz — a noticeably higher pitch." },
    faqs: [
      {
        question: "Why does a passing siren change pitch?",
        answer: "As an emergency vehicle approaches, its sound waves are compressed into a shorter wavelength, raising the frequency you hear so the siren sounds higher pitched. The instant it passes and starts moving away, the waves stretch out, lowering the frequency and dropping the pitch. The abrupt shift you notice as the vehicle goes by is the Doppler effect switching from the approaching case to the receding case in real time.",
      },
      {
        question: "Does this calculator assume the observer is stationary?",
        answer: "Yes. This version models a moving source and a stationary observer, which covers the most common situations like a passing siren or car heard by someone standing still. If the observer is also moving, the full Doppler formula adds terms for the observer's velocity as well. For a first analysis, the stationary-observer case captures the essential frequency shift and is accurate whenever you are not moving toward or away from the source.",
      },
      {
        question: "What speed of sound should I use?",
        answer: "The speed of sound in air is about 343 metres per second at 20 degrees Celsius, which is this calculator's default. It rises with temperature, reaching roughly 349 metres per second at 30 degrees and falling to about 331 at freezing. Sound also travels much faster in water, around 1,480 metres per second, and faster still in solids, so adjust the value if your medium is not room-temperature air.",
      },
      {
        question: "What happens as the source approaches the speed of sound?",
        answer: "As the source speed nears the speed of sound, the denominator in the approaching formula shrinks toward zero, so the observed frequency climbs steeply toward very high values. Physically, the waves pile up almost on top of one another just ahead of the source. When the source actually reaches the speed of sound, the waves stack into a shock wave, producing the sonic boom heard when aircraft break the sound barrier.",
      },
      {
        question: "Does the Doppler effect apply to light too?",
        answer: "Yes. Light waves shift in frequency with relative motion just as sound does, though the exact formula involves relativity. A source moving away shifts light toward the red end of the spectrum, a redshift, while an approaching source causes a blueshift. Astronomers measure these shifts to determine how fast stars and galaxies move, and the widespread redshift of distant galaxies is key evidence that the universe is expanding.",
      },
    ],
    relatedCalculators: ["speed-distance-time-calculator", "kinetic-energy-calculator", "force-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard physics (Doppler effect)",
  },
];
