import type { CalculatorDefinition } from "../types";

export const sportsR8Calculators: CalculatorDefinition[] = [
  {
    id: "running-calories",
    slug: "running-calories-calculator",
    category: "Sports",
    categorySlug: "sports",
    title: "Running Calories Calculator",
    shortDescription: "Estimate calories burned on a run from weight and distance.",
    seoTitle: "Running Calories Calculator — Calories Burned Running",
    metaDescription: "Free running calories calculator. Enter your bodyweight and the distance you ran to estimate how many calories you burned, using the standard distance-based method.",
    primaryKeyword: "running calories calculator",
    secondaryKeywords: ["calories burned running", "run calorie calculator", "running energy calculator"],
    fields: [
      { id: "weightKg", label: "Body weight", type: "number", unit: "kg", required: true, span: 1, min: 0 },
      { id: "distanceKm", label: "Distance run", type: "number", unit: "km", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "caloriesBurned", label: "Calories burned", format: "number", decimals: 0, unit: "kcal", isPrimary: true },
    ],
    formula: "calories = weight (kg) × distance (km) × 1.036",
    formulaExplanation: "Running cost is dominated by the work of moving your bodyweight forward, so the energy you burn scales with both how heavy you are and how far you travel. The constant 1.036 represents roughly one kilocalorie per kilogram carried over each kilometre, a figure that holds across a wide range of running paces because the energy per kilometre stays broadly constant. Multiplying weight by distance by this factor gives a quick, pace-independent estimate of the total energy expended.",
    explanation: "This running calories calculator estimates how much energy you burned on a run from just two numbers: your bodyweight in kilograms and the distance you covered in kilometres. Unlike calculators that need your pace and time, this method uses the well-established observation that the calorie cost of running depends mainly on how far you move your body, not how fast you do it, which makes it fast and forgiving to use.\n\nKnowing your running calorie burn matters for anyone managing their weight, planning nutrition, or fuelling training. Because running is one of the most energy-dense forms of everyday exercise, an accurate estimate helps you set a sensible calorie deficit for fat loss or, conversely, replace the energy you spent so you recover well and keep training consistently. Comparing the burn from different run lengths also shows how much extra distance actually costs you.\n\nThe calculation works because the energy required to run a kilometre is close to a fixed proportion of your bodyweight, so scaling weight by distance by the constant 1.036 gives a reliable ballpark. It is an estimate rather than a laboratory measurement, since hills, wind, and running economy shift the true figure, but it is a genuinely useful guide for planning meals and tracking activity.",
    example: { inputs: { weightKg: 70, distanceKm: 10 }, explanation: "70 × 10 × 1.036 = 725.2, so about 725 kcal burned over a 10 km run." },
    faqs: [
      {
        question: "Why does pace not appear in this calculator?",
        answer: "The energy cost of running comes mostly from moving your bodyweight a given distance, and research shows the calories per kilometre stay roughly constant across a wide range of paces. Running faster gets you there sooner but burns a similar total, because you spend less time working harder. That is why this distance-based method needs only your weight and distance, and still produces a realistic estimate of the calories you burned.",
      },
      {
        question: "How does bodyweight change the result?",
        answer: "A heavier runner has to move more mass with every stride, so they burn more calories covering the same distance than a lighter runner does. The formula multiplies directly by your weight in kilograms, which is why entering an accurate figure matters. Two people running the same route will get different results, with the heavier person expending more energy, so always use your real current weight for a trustworthy estimate.",
      },
      {
        question: "Is walking the same distance the same burn?",
        answer: "Not quite. Walking a kilometre burns somewhat fewer calories than running the same kilometre, because running involves a bouncing, airborne phase that costs extra energy your muscles must generate. This calculator is tuned for running, so applying it to a walk would slightly overestimate the burn. For mixed sessions, treat the running and walking portions separately, or use a dedicated walking estimate for the walked segments.",
      },
      {
        question: "How accurate is the estimate?",
        answer: "It gives a solid ballpark rather than a precise count. Real energy use varies with running economy, terrain, gradient, wind, temperature, and individual metabolism, none of which a simple weight-and-distance formula can capture. Treat the number as a planning guide rather than an exact measurement, and if your goal is a reliable calorie deficit, avoid eating back every estimated calorie since these figures tend to run slightly optimistic.",
      },
      {
        question: "Do hills increase the calories burned?",
        answer: "Yes. Running uphill demands extra work to lift your bodyweight against gravity, so a hilly route burns more than a flat one of the same distance, while downhill sections recover only a little of that cost. This calculator assumes broadly flat terrain, so on a hilly run it will underestimate the true burn. Add a rough allowance for significant climbing, or use a GPS device that factors in elevation.",
      },
    ],
    relatedCalculators: ["running-pace-calculator", "vo2-max-calculator", "cycling-calories-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard sports science (distance-based running energy)",
  },
  {
    id: "marathon-time-predictor",
    slug: "marathon-time-predictor-calculator",
    category: "Sports",
    categorySlug: "sports",
    title: "Marathon Time Predictor",
    shortDescription: "Predict your marathon time from a recent race result.",
    seoTitle: "Marathon Time Predictor — Riegel Race Time Estimate",
    metaDescription: "Free marathon time predictor using the Riegel formula. Enter a recent distance and time plus your target distance to estimate your marathon finishing time.",
    primaryKeyword: "marathon time predictor",
    secondaryKeywords: ["marathon predictor calculator", "riegel marathon calculator", "race time prediction"],
    fields: [
      { id: "recentDistanceKm", label: "Recent race distance", type: "number", unit: "km", required: true, span: 1, min: 0 },
      { id: "recentTimeMinutes", label: "Recent race time", type: "number", unit: "min", required: true, span: 1, min: 0, helpText: "Your finishing time for that race, in minutes." },
      { id: "targetDistanceKm", label: "Target distance", type: "number", unit: "km", required: true, span: 2, min: 0, helpText: "42.195 km for a full marathon." },
    ],
    results: [
      { id: "predictedMinutes", label: "Predicted time", format: "number", decimals: 1, unit: "min", isPrimary: true },
    ],
    formula: "T2 = T1 × (D2 ÷ D1)^1.06",
    formulaExplanation: "The Riegel model projects a finishing time by scaling a known race to a new distance and raising the distance ratio to the power 1.06. That exponent, a little above one, encodes the fact that pace fades as distance grows, since nobody can hold a short race's speed over a marathon. Multiplying your recent time by this factor stretches it in proportion to how much longer the target race is, giving a realistic prediction rather than a naive linear scale-up.",
    explanation: "This marathon time predictor estimates how long a marathon, or any target distance, might take you based on a race you have recently completed. It applies the Riegel formula: enter the distance and time of a recent result and the distance you are aiming at, and it projects a finishing time. Times are handled in minutes so the numbers stay easy to read and enter.\n\nPredicting a marathon time matters because pacing a 42.195-kilometre race well is difficult, and starting too fast is the classic mistake that leads to hitting the wall. A grounded prediction from a recent half-marathon or 10K gives you a target pace to rehearse in training and to hold on race day. Coaches use it to set goal paces, and runners use it to choose a realistic finish-time ambition rather than an arbitrary round number.\n\nThe formula works because running pace slows in a predictable way as distance increases, and the exponent 1.06 captures that fade accurately across common racing distances. The prediction assumes you have trained appropriately for the longer event, so it is most reliable when your recent race is reasonably close in distance and your endurance base supports the marathon. Treat the output as an informed goal to train toward, not a guarantee, since fuelling, heat, and course profile all shape the real result.",
    example: { inputs: { recentDistanceKm: 21.0975, recentTimeMinutes: 100, targetDistanceKm: 42.195 }, explanation: "100 × (42.195 ÷ 21.0975)^1.06 = 100 × 2.085 ≈ 208.5 minutes, about 3 hours 28 minutes." },
    faqs: [
      {
        question: "What is the Riegel formula?",
        answer: "The Riegel formula, published by Peter Riegel, predicts race times across distances by multiplying a known time by the distance ratio raised to the power 1.06. The exponent reflects that runners slow slightly as races lengthen. It is trusted because it is simple and matches real results well from about 1,500 metres up to the marathon, making it a standard tool for setting realistic goal paces from a recent performance.",
      },
      {
        question: "Which recent race should I use as input?",
        answer: "Use a recent, well-paced race at a distance not too far from your target for the most reliable prediction. A half-marathon is an excellent basis for a marathon estimate because the endurance demands overlap closely. A short 5K can also work but tends to produce an optimistic marathon time, since it assumes endurance you may not yet have. Pick a result that genuinely reflects your current fitness rather than a personal best from months ago.",
      },
      {
        question: "Why enter time in minutes?",
        answer: "The calculator works in minutes to keep entry and output simple and consistent. Convert your finishing time first by multiplying hours by sixty and adding the remaining minutes and any fractional seconds. A half-marathon of one hour forty minutes becomes 100 minutes. The predicted time is also returned in minutes, which you can convert back into hours and minutes to plan a familiar marathon goal pace and split strategy.",
      },
      {
        question: "How accurate is a marathon prediction?",
        answer: "Predictions are most accurate when your input race is close in distance and you have completed marathon-specific endurance training. Jumping from a 5K straight to a marathon estimate assumes stamina you may lack, so the projection can be too fast. The marathon is also uniquely exposed to fuelling and the wall, which no formula models. Use it as a target to train toward, and expect heat, hills, and pacing to move the real time.",
      },
      {
        question: "Can I predict shorter races too?",
        answer: "Yes. The formula works in both directions, so you can project down from a marathon to a half-marathon or 10K as well as up. Predicting a shorter, faster race from a longer result usually gives a slightly conservative target, because your speed over short distances may beat what an endurance-based formula assumes. Either way, base the prediction on a recent race that reflects your present fitness for the most useful result.",
      },
    ],
    relatedCalculators: ["running-pace-calculator", "race-time-predictor-calculator", "vo2-max-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Riegel model (race prediction)",
  },
  {
    id: "race-finish-time",
    slug: "race-finish-time-calculator",
    category: "Sports",
    categorySlug: "sports",
    title: "Race Finish Time Calculator",
    shortDescription: "Work out your finish time from distance and target pace.",
    seoTitle: "Race Finish Time Calculator — Finish Time from Pace",
    metaDescription: "Free race finish time calculator. Enter the race distance and your target pace per kilometre to find your finishing time in minutes and as a duration.",
    primaryKeyword: "race finish time calculator",
    secondaryKeywords: ["finish time calculator", "race time from pace", "running finish time"],
    fields: [
      { id: "distanceKm", label: "Race distance", type: "number", unit: "km", required: true, span: 1, min: 0 },
      { id: "paceMinPerKm", label: "Target pace", type: "number", unit: "min/km", required: true, span: 1, min: 0, step: 0.01 },
    ],
    results: [
      { id: "finishMinutes", label: "Finish time", format: "number", decimals: 1, unit: "min", isPrimary: true },
      { id: "finishTime", label: "Finish time (duration)", format: "duration", isPrimary: false },
    ],
    formula: "finish time = distance (km) × pace (min/km)",
    formulaExplanation: "Finishing time is simply the distance you cover multiplied by how long each unit of that distance takes. If you hold a pace of a certain number of minutes per kilometre, then every kilometre adds exactly that many minutes to your total, so multiplying pace by the number of kilometres gives the whole-race time. The same result is shown both as a decimal number of minutes and formatted as an hours-minutes-seconds duration for convenience.",
    explanation: "This race finish time calculator tells you how long a race will take if you hold a chosen pace. Enter the race distance in kilometres and your target pace in minutes per kilometre, and it returns your projected finishing time both as a number of minutes and as a familiar hours-minutes-seconds duration. It is the essential tool for turning a pace goal into a finish-line time.\n\nWorking out your finish time in advance matters for race planning and pacing discipline. Once you know that a given pace yields a particular finishing time, you can decide whether that pace is realistic, set your watch to keep you honest, and brief your support crew on when to expect you. Runners chasing a specific time goal work backwards from it to find the exact pace they must sustain, and this calculator makes that link explicit.\n\nThe calculation is straightforward but powerful: time equals distance multiplied by pace, because pace is time per unit distance. Holding five minutes per kilometre over ten kilometres takes fifty minutes, regardless of how the effort feels along the way. By showing the result as a clean duration as well as a raw minute count, the tool lets you compare instantly against your goal time, previous results, and the qualifying standards or cut-offs that many races impose.",
    example: { inputs: { distanceKm: 10, paceMinPerKm: 5.5 }, explanation: "10 × 5.5 = 55 minutes, shown as a duration of 55:00 for a 10 km race at 5:30 per km." },
    faqs: [
      {
        question: "How do I convert a pace like 5:30 into a number?",
        answer: "Paces are often written in minutes and seconds, such as 5:30 per kilometre, but this calculator expects a decimal. Convert the seconds portion by dividing by sixty and adding it to the minutes: 5:30 becomes 5.5, and 4:45 becomes 4.75. Entering 5:30 as 5.3 would be wrong, since thirty seconds is half a minute, not three-tenths. Always convert the seconds to a fraction of a minute before entering your pace.",
      },
      {
        question: "Does the finish time assume even pacing?",
        answer: "Yes. The calculation assumes you hold the entered pace steadily for the whole distance, so it gives the time for a perfectly even effort. Real races rarely go exactly to plan, with faster and slower kilometres balancing out or drifting. An even pace is generally the most efficient way to race, so the estimate doubles as a target: aim to run each kilometre at the entered pace to hit the projected finishing time.",
      },
      {
        question: "Can I use this for any distance?",
        answer: "Yes. Enter any race distance in kilometres, from a short 5K to an ultramarathon, along with the pace you intend to hold. The formula does not change with distance. Bear in mind that holding a given pace becomes harder the longer you run, so choose a pace you can realistically sustain for the whole event rather than your speed over a short, fresh effort, or the finish time will be unattainable.",
      },
      {
        question: "How is the duration result different from the minutes?",
        answer: "The two results show the same finishing time in different formats. The minutes figure is a decimal number, handy for further calculations, while the duration formats that same value into hours, minutes, and seconds, which is how race times are normally read and reported. A finish of 95.5 minutes appears as a duration of 1:35:30. Use whichever representation suits your purpose, whether planning splits or comparing against a goal time.",
      },
      {
        question: "How do I find the pace I need for a goal time?",
        answer: "To work backwards from a target finishing time, divide that time in minutes by the race distance in kilometres, and the result is the pace you must hold. For a sub-fifty-minute 10K, fifty divided by ten gives five minutes per kilometre. You can also enter trial paces here and adjust until the finish time matches your goal, which is a quick way to zero in on the exact pace required.",
      },
    ],
    relatedCalculators: ["running-pace-calculator", "target-pace-calculator", "marathon-time-predictor-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard sports science (pace–distance–time)",
  },
  {
    id: "power-to-weight-ratio",
    slug: "power-to-weight-ratio-calculator",
    category: "Sports",
    categorySlug: "sports",
    title: "Power-to-Weight Ratio Calculator",
    shortDescription: "Calculate cycling power-to-weight in watts per kilogram.",
    seoTitle: "Power-to-Weight Ratio Calculator — Watts per Kg",
    metaDescription: "Free power-to-weight ratio calculator for cyclists. Enter your power output in watts and your bodyweight to find your watts per kilogram, the key climbing metric.",
    primaryKeyword: "power to weight ratio calculator",
    secondaryKeywords: ["watts per kg calculator", "cycling power to weight", "w/kg calculator"],
    fields: [
      { id: "powerWatts", label: "Power output", type: "number", unit: "W", required: true, span: 1, min: 0 },
      { id: "weightKg", label: "Body weight", type: "number", unit: "kg", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "wattsPerKg", label: "Power-to-weight", format: "number", decimals: 2, unit: "W/kg", isPrimary: true },
    ],
    formula: "power-to-weight = power (W) ÷ weight (kg)",
    formulaExplanation: "Power-to-weight ratio divides the power you produce by the mass you must move, giving watts per kilogram. It matters because climbing and accelerating are fights against your own weight, so what counts is not raw power alone but power relative to how heavy you are. Dividing watts by kilograms normalises output across riders of different sizes, letting a light rider with modest power match a heavier, more powerful one on a steep gradient.",
    explanation: "Power-to-weight ratio is the single most important performance metric in cycling, especially for climbing, and this calculator works it out from your power output in watts and your bodyweight in kilograms. The result, expressed in watts per kilogram, tells you how much power you generate for every kilogram you have to haul up the road, which is what really determines how fast you go uphill.\n\nThe metric matters because on any climb or acceleration you are working against gravity and inertia acting on your total mass. A rider producing 300 watts at 60 kilograms will out-climb a rider producing the same 300 watts at 80 kilograms, because the lighter rider spreads that power over less weight. This is why professional climbers are famously lean, and why comparing raw wattage between riders of different sizes is misleading without normalising for weight.\n\nThe calculation is a simple division, but its implications are profound for training and racing. Cyclists track their watts per kilogram at threshold to benchmark fitness, judge whether to focus on gaining power or losing weight, and compare themselves against category standards, where recreational riders sit around two to three watts per kilogram and elite professionals exceed six at threshold. Whether you are chasing a personal best up a local climb or planning a training block, knowing your power-to-weight ratio turns abstract numbers into a clear measure of climbing ability.",
    example: { inputs: { powerWatts: 300, weightKg: 75 }, explanation: "300 ÷ 75 = 4.00 W/kg, a strong figure typical of a fit amateur racer at threshold." },
    faqs: [
      {
        question: "Why is watts per kilogram more useful than raw watts?",
        answer: "Raw watts measure the power you produce, but climbing and accelerating are struggles against your bodyweight, so what matters is power relative to mass. A heavier rider needs more watts to climb at the same speed as a lighter one. Expressing power per kilogram lets you compare riders of different sizes fairly and predicts climbing performance far better than raw power alone, which is why coaches and racers focus on this ratio.",
      },
      {
        question: "What power figure should I enter?",
        answer: "For a meaningful benchmark, enter your functional threshold power, the highest average power you can sustain for about an hour, rather than a brief sprint peak. Threshold watts per kilogram is the standard used to compare riders and rank fitness. You can also enter power for a specific effort, such as a twenty-minute climb, as long as you interpret the result in that context and compare like with like on future tests.",
      },
      {
        question: "What is a good power-to-weight ratio?",
        answer: "It depends heavily on the duration and your level. At threshold, untrained riders sit around two watts per kilogram, keen amateurs three to four, strong club racers four to five, and elite professionals above six. Short sprint efforts produce much higher figures. Rather than fixate on category tables, track your own watts per kilogram over time, since a rising number at the same effort is clear proof your cycling fitness is improving.",
      },
      {
        question: "Should I gain power or lose weight to improve it?",
        answer: "Both raise the ratio, but the right choice depends on your situation. If you carry excess weight, losing it can lift watts per kilogram quickly without touching your power, though never at the expense of health or the energy to train. If you are already lean, building power through structured training is the sustainable path. Many riders make the biggest gains by improving power while holding a healthy, performance-supporting weight steady.",
      },
      {
        question: "Does power-to-weight matter on flat roads?",
        answer: "It matters far less on the flat, where aerodynamic drag dominates and raw power and body position count for more than weight. A heavier, powerful rider often excels on flat time trials and in sprints. Power-to-weight ratio comes into its own on climbs and steep accelerations, where gravity makes mass the limiting factor. So judge your strengths by terrain: watts per kilogram for the hills, raw watts and aerodynamics for the flats.",
      },
    ],
    relatedCalculators: ["cycling-speed-calculator", "cycling-calories-calculator", "vo2-max-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard cycling science (power-to-weight ratio)",
  },
  {
    id: "target-pace",
    slug: "target-pace-calculator",
    category: "Sports",
    categorySlug: "sports",
    title: "Target Pace Calculator",
    shortDescription: "Find the pace you need to hit a goal time.",
    seoTitle: "Target Pace Calculator — Pace Needed for a Goal Time",
    metaDescription: "Free target pace calculator. Enter your goal distance and goal time to find the pace per kilometre and speed you need to hold to finish on target.",
    primaryKeyword: "target pace calculator",
    secondaryKeywords: ["goal pace calculator", "pace needed calculator", "running goal pace"],
    fields: [
      { id: "goalDistanceKm", label: "Goal distance", type: "number", unit: "km", required: true, span: 1, min: 0 },
      { id: "goalTimeMinutes", label: "Goal time", type: "number", unit: "min", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "paceMinPerKm", label: "Required pace", format: "number", decimals: 2, unit: "min/km", isPrimary: true },
      { id: "speedKmh", label: "Required speed", format: "number", decimals: 2, unit: "km/h", isPrimary: false },
    ],
    formula: "pace = goal time ÷ goal distance",
    formulaExplanation: "Target pace is the goal time divided by the goal distance, giving the minutes you can afford to spend on each kilometre and still finish on schedule. Because pace is time per unit distance, splitting the total time evenly across the distance yields the steady pace required. Speed is the same relationship inverted, distance over time, converted to kilometres per hour by dividing the time in minutes by sixty first.",
    explanation: "This target pace calculator answers the runner's most practical question: what pace do I need to run to hit my goal time? Enter the distance of your race or run and the finishing time you are aiming for, and it returns the required pace in minutes per kilometre along with the equivalent steady speed in kilometres per hour. It turns a finish-time ambition into a concrete number to hold on the road.\n\nRacing to a time goal is really an exercise in pacing, and knowing your target pace before you start is what keeps you from going out too fast and fading, or drifting too slow to make up later. With the exact pace in hand, you can set your watch, rehearse the rhythm in training, and check yourself at each kilometre marker. It also lets you judge honestly whether a goal is realistic given how that pace feels in practice.\n\nThe calculation divides your goal time evenly across the distance, because holding a constant pace is both the simplest and usually the most efficient way to race. The speed figure gives the same information for anyone who thinks in kilometres per hour or sets a treadmill. Whether you are chasing a sub-two-hour half-marathon or a personal best over 5K, a target pace calculator translates the dream into the discipline of a single, repeatable pace.",
    example: { inputs: { goalDistanceKm: 10, goalTimeMinutes: 50 }, explanation: "50 ÷ 10 = 5.00 min/km, and a speed of 12.00 km/h, to break fifty minutes for 10 km." },
    faqs: [
      {
        question: "How do I read the pace as minutes and seconds?",
        answer: "The pace is shown as a decimal number of minutes per kilometre, so convert the fractional part into seconds by multiplying it by sixty. A pace of 5.5 means five minutes and thirty seconds per kilometre, and 4.75 means four minutes and forty-five seconds. Do not read 5.5 as five minutes fifty seconds. Once converted, you can set the minutes-and-seconds pace on your running watch to keep yourself on target.",
      },
      {
        question: "Is holding an even pace really best?",
        answer: "For most runners and most distances, an even pace is the most efficient way to race and the easiest to execute. Starting too fast burns energy you cannot recover and usually leads to a painful slowdown, while starting too slow wastes time you cannot make up. This calculator gives the even pace that exactly meets your goal, so aiming to run each kilometre at that pace is a sound and proven strategy.",
      },
      {
        question: "Should I adjust the pace for hills?",
        answer: "The calculator gives the average pace needed across the whole distance, assuming flat terrain. On a hilly course you will naturally run slower up climbs and faster down descents, so aim to average the target pace overall rather than forcing it on every gradient. Effort, not pace, should stay roughly even on hills. Bank a little time on flat and downhill sections to offset the slower climbs and still hit your goal.",
      },
      {
        question: "What does the speed figure add?",
        answer: "The speed result expresses the same target as kilometres per hour instead of minutes per kilometre, which some runners find more intuitive and which matches how treadmills are set. If you train on a treadmill, you can dial in the speed directly to rehearse your goal pace. It is also handy for comparing running effort against cycling or other sports that report speed rather than pace, giving you a common frame of reference.",
      },
      {
        question: "How do I know if my goal time is realistic?",
        answer: "Enter your goal and look at the required pace, then compare it honestly with paces you already sustain in training and recent races. If the target pace is far faster than anything you have held for a similar distance, the goal may be too ambitious for now. A good goal stretches you by a modest margin. You can also use a race time predictor from a recent result to sanity-check the ambition.",
      },
    ],
    relatedCalculators: ["running-pace-calculator", "race-finish-time-calculator", "marathon-time-predictor-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard sports science (pace–distance–time)",
  },
  {
    id: "swim-pace-per-100",
    slug: "swim-pace-per-100-calculator",
    category: "Sports",
    categorySlug: "sports",
    title: "Swim Pace per 100 Calculator",
    shortDescription: "Find your swim pace per 100 metres from a swim.",
    seoTitle: "Swim Pace per 100 Calculator — Pace per 100 m",
    metaDescription: "Free swim pace per 100 calculator. Enter the total metres you swam and the total minutes it took to find your pace per 100 metres, the standard swim benchmark.",
    primaryKeyword: "swim pace per 100 calculator",
    secondaryKeywords: ["pace per 100m calculator", "swim pace calculator", "swimming pace per 100"],
    fields: [
      { id: "totalMeters", label: "Total distance", type: "number", unit: "m", required: true, span: 1, min: 0 },
      { id: "totalMinutes", label: "Total time", type: "number", unit: "min", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "pacePer100m", label: "Pace per 100 m", format: "number", decimals: 2, unit: "min/100m", isPrimary: true },
    ],
    formula: "pace per 100 m = total minutes ÷ total metres × 100",
    formulaExplanation: "Pace per hundred metres normalises a swim of any length to a standard reference so efforts compare fairly. Dividing your total time by the total distance gives the minutes spent on each metre, and multiplying by one hundred scales that up to the time a full hundred-metre segment would take at the same rate. Because pools and swim sets are built in hundreds of metres, this unit translates directly into practical training splits and send-off times.",
    explanation: "Pace per 100 metres is the universal language of swimming, and this calculator converts any swim into that benchmark. Enter the total distance you covered in metres and the total time it took in minutes, and it returns your pace per hundred metres, letting you compare a short set against a long continuous swim on exactly equal terms.\n\nThe metric matters because swimming distances are almost always multiples of a pool length, and coaches write sets and send-off times in seconds or minutes per hundred metres. Expressing every swim the same way lets you track conditioning across sessions, set realistic interval targets, and pace a long swim evenly instead of fading. Triathletes in particular rely on it to judge whether their race-day swim pace is sustainable before committing to it in open water.\n\nThe calculation spreads your total time across your total distance and rescales it to a hundred-metre reference, which is why it works for any swim length you enter. A falling pace per hundred metres at the same effort is clear evidence your swimming is improving, making this one of the cleanest ways to measure progress in the water. Whether you swim in a pool or open water, knowing your pace per hundred turns a distance and a stopwatch reading into a meaningful, comparable figure you can build training around.",
    example: { inputs: { totalMeters: 1500, totalMinutes: 30 }, explanation: "30 ÷ 1500 × 100 = 2.00 minutes per 100 m, a steady 2:00/100 m pace over 1,500 m." },
    faqs: [
      {
        question: "How do I read the pace in minutes and seconds?",
        answer: "The result is a decimal number of minutes per hundred metres, so convert the fractional part to seconds by multiplying by sixty. A pace of 1.5 means one minute thirty seconds per hundred metres, and 1.75 means one minute forty-five seconds. Do not read 1.5 as one minute fifty seconds. Swimmers usually talk in minutes and seconds per hundred, so this conversion lets you compare directly with your normal training splits.",
      },
      {
        question: "Why is 100 metres the standard reference?",
        answer: "Swimming sets and races are built from pool lengths, and a hundred metres is a natural unit that most training and competition distances are multiples of. Expressing pace per hundred lets you compare a fifty-metre sprint against a fifteen-hundred-metre distance swim on equal terms, and it matches how coaches prescribe send-off times. That shared reference is why swimmers everywhere describe their speed in seconds or minutes per hundred rather than in raw metres per second.",
      },
      {
        question: "Does this work for a 25-metre pool?",
        answer: "Yes. Enter the actual total distance you swam in metres, whatever the pool length, and the total time. If you swam sixty lengths of a twenty-five-metre pool, that is 1,500 metres. The pace-per-hundred formula depends only on total distance and total time, not on how many lengths made up the swim, so it applies equally to short-course, long-course, and open-water swims once you know the true distance.",
      },
      {
        question: "What is a good pace per 100 metres?",
        answer: "It depends on your level and the swim length. Many recreational swimmers hold around two minutes per hundred metres, competent club swimmers closer to ninety seconds, and elite swimmers well under a minute over shorter distances. Rather than chase a universal target, track your own pace per hundred over time. A lower figure at the same perceived effort is clear proof your swimming fitness and technique are improving.",
      },
      {
        question: "Should I include rest in the total time?",
        answer: "That depends on what you want to measure. For a continuous swim with no stops, the total time is simply your swim time and the pace reflects your true swimming speed. If your session included rest between intervals, decide whether to count that rest: including it gives an overall average for the whole session, while excluding it isolates your swimming pace. For comparing fitness, use continuous swim time without rest.",
      },
    ],
    relatedCalculators: ["swim-pace-calculator", "running-pace-calculator", "cycling-speed-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard sports science (swim pace)",
  },
  {
    id: "wilks-score",
    slug: "wilks-score-calculator",
    category: "Sports",
    categorySlug: "sports",
    title: "Wilks Score Calculator",
    shortDescription: "Compare powerlifting strength across bodyweights.",
    seoTitle: "Wilks Score Calculator — Powerlifting Strength Score",
    metaDescription: "Free Wilks score calculator for powerlifters. Enter your bodyweight, total lifted, and sex to compute your Wilks coefficient score and compare strength fairly.",
    primaryKeyword: "wilks score calculator",
    secondaryKeywords: ["wilks calculator", "powerlifting score calculator", "wilks coefficient calculator"],
    fields: [
      { id: "bodyWeightKg", label: "Body weight", type: "number", unit: "kg", required: true, span: 1, min: 0 },
      { id: "liftedKg", label: "Total lifted", type: "number", unit: "kg", required: true, span: 1, min: 0, helpText: "Your competition total or a single lift, in kilograms." },
      { id: "sex", label: "Sex", type: "select", required: true, span: 2, options: [ { value: "male", label: "Male" }, { value: "female", label: "Female" } ] },
    ],
    results: [
      { id: "wilksScore", label: "Wilks score", format: "number", decimals: 1, unit: "pts", isPrimary: true },
    ],
    formula: "Wilks = lifted (kg) × 500 ÷ (a + b·w + c·w² + d·w³ + e·w⁴ + f·w⁵)",
    formulaExplanation: "The Wilks score multiplies the weight lifted by a coefficient that depends on the lifter's bodyweight through a fifth-order polynomial, with separate constants for men and women. The polynomial in the denominator models how raw strength rises with bodyweight but at a diminishing rate, so lighter lifters get a larger coefficient to level the field. Multiplying the total by five hundred over that polynomial produces a single number that lets lifters of any size be ranked fairly.",
    explanation: "The Wilks score is powerlifting's answer to a hard question: how do you compare the strength of a 60-kilogram lifter with that of a 120-kilogram lifter when the heavier athlete will almost always lift more in absolute terms? This calculator computes it from your bodyweight, the total you lifted, and your sex, returning a single points figure that allows fair comparison across every weight class.\n\nHeavier people can generally lift more, but not in direct proportion to their extra mass, so raw totals favour the biggest athletes. The Wilks formula corrects for this by scaling your lift with a coefficient derived from a fifth-order polynomial fitted to elite performance data, with separate constants for men and women. A lighter lifter earns a higher coefficient, so a modest absolute total from a small athlete can outscore a larger total from a heavy one, reflecting relative strength.\n\nThe result is widely used to decide best-lifter awards at meets, to rank athletes across categories, and to let individuals track their own progress as bodyweight fluctuates. A score around 300 marks a solid intermediate lifter, 400 is advanced, and elite competitors push past 500. Because it isolates strength relative to size, the Wilks score is a fairer benchmark of pound-for-pound ability than any raw total, and this calculator makes it instantly available for training logs and competition planning.",
    example: { inputs: { bodyWeightKg: 90, liftedKg: 200, sex: "male" }, explanation: "At 90 kg the male coefficient is about 0.639, so 200 × 0.639 ≈ 127.7 Wilks points." },
    faqs: [
      {
        question: "What does the Wilks score actually measure?",
        answer: "The Wilks score measures strength relative to bodyweight, letting lifters of different sizes be compared fairly. Because heavier athletes naturally lift more in absolute terms, a raw total rewards size as much as strength. The Wilks coefficient scales each lift by a factor based on bodyweight, so the number reflects pound-for-pound ability. A higher Wilks score means you are stronger for your size, regardless of which weight class you compete in.",
      },
      {
        question: "Why are the coefficients different for men and women?",
        answer: "Men and women differ in average muscle mass and strength relative to bodyweight, so a single formula would not compare them fairly. The Wilks system uses separate sets of polynomial constants, each fitted to elite performance data for that sex, so scores are calibrated within each group. This lets a female lifter's score be compared meaningfully with a male lifter's, since both are measured against the appropriate standard for their sex.",
      },
      {
        question: "Should I enter a single lift or my full total?",
        answer: "You can enter either, as long as you interpret the result consistently. In competition the Wilks score is usually applied to the powerlifting total, the combined best squat, bench press, and deadlift. If you enter a single lift instead, the score reflects that lift's strength for your bodyweight rather than overall powerlifting standing. For comparing against published Wilks benchmarks and best-lifter awards, use your full three-lift total.",
      },
      {
        question: "What is considered a good Wilks score?",
        answer: "Rough guidelines place a novice around 200, a solid intermediate near 300, an advanced lifter around 400, and elite competitors above 500, with world-class totals pushing well beyond. These bands vary by sex and federation, so treat them as approximate. The most useful comparison is against your own past scores: a rising Wilks as your total climbs or your bodyweight holds steady is clear proof your relative strength is improving.",
      },
      {
        question: "Is Wilks the only scoring system in powerlifting?",
        answer: "No. Several systems exist, including the older Wilks formula used here, an updated Wilks revision, and the IPF GL points now used by some federations. Each uses different coefficients and can rank borderline cases slightly differently. The classic Wilks score remains widely recognised and is excellent for tracking personal progress and informal comparison. Check which system your federation uses if you need an official competition score for rankings or awards.",
      },
    ],
    relatedCalculators: ["one-rep-max-calculator", "calorie-burn-calculator", "running-pace-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Wilks coefficient (powerlifting)",
  },
  {
    id: "race-split",
    slug: "race-split-calculator",
    category: "Sports",
    categorySlug: "sports",
    title: "Race Split Calculator",
    shortDescription: "Find the split time for part of a race at even pace.",
    seoTitle: "Race Split Calculator — Even-Pace Split Times",
    metaDescription: "Free race split calculator. Enter your total distance, total time, and a split distance to find the time you should reach that point at an even pace.",
    primaryKeyword: "race split calculator",
    secondaryKeywords: ["split time calculator", "even pace split calculator", "race split times"],
    fields: [
      { id: "totalDistanceKm", label: "Total distance", type: "number", unit: "km", required: true, span: 1, min: 0 },
      { id: "totalTimeMinutes", label: "Total time", type: "number", unit: "min", required: true, span: 1, min: 0 },
      { id: "splitDistanceKm", label: "Split distance", type: "number", unit: "km", required: true, span: 2, min: 0, helpText: "The point in the race you want the split time for." },
    ],
    results: [
      { id: "splitTimeMinutes", label: "Split time", format: "number", decimals: 2, unit: "min", isPrimary: true },
    ],
    formula: "split time = total time ÷ total distance × split distance",
    formulaExplanation: "At an even pace, the time to reach any point in a race is proportional to how far into the race that point sits. Dividing the total time by the total distance gives the pace, the time spent per unit distance, and multiplying that pace by the split distance gives the time you should pass that marker. This linear scaling assumes a constant effort, so each split lands exactly on schedule for the target finish.",
    explanation: "This race split calculator tells you what time you should reach any point in a race if you run it at an even pace to your target finish. Enter the total distance, your goal total time, and the split distance you care about, and it returns the time you should hit that marker. It is the tool for building a pacing plan you can check against your watch on race day.\n\nSplit times matter because racing to a goal is really about pacing discipline, and the surest way to blow a time goal is to start too fast. By knowing in advance what your watch should read at 5, 10, or 21 kilometres, you can rein yourself in early and catch any drift before it costs you the finish. Many runners write these splits on a wristband or program them into a watch so they always know whether they are on schedule.\n\nThe calculation assumes even pacing, dividing your goal time proportionally across the distance, because a steady effort is usually the most efficient way to race and the easiest plan to follow. You can generate a whole set of checkpoints by running the calculator for each split distance you want. Whether you are targeting a marathon time or pacing a 10K, a race split calculator turns a single finish-time goal into a clear, checkable schedule for every stage of the race.",
    example: { inputs: { totalDistanceKm: 42.195, totalTimeMinutes: 240, splitDistanceKm: 21.0975 }, explanation: "240 ÷ 42.195 × 21.0975 = 120 minutes, the halfway split for a 4-hour marathon." },
    faqs: [
      {
        question: "Does this assume I run an even pace?",
        answer: "Yes. The split time is calculated by spreading your goal time evenly across the total distance, so each split reflects a constant pace throughout the race. Even pacing is generally the most efficient racing strategy and the simplest to follow, which is why it is the default here. If you plan a deliberate negative split, running the second half faster, treat these even-pace splits as an upper limit for the early checkpoints.",
      },
      {
        question: "How do I build a full pacing schedule?",
        answer: "Run the calculator once for each checkpoint you want, keeping the same total distance and total time but changing the split distance. Enter 5, 10, 15, and 20 kilometres in turn to get the target time at each, and note them down. Writing these splits on a pacing band or loading them into your running watch gives you a checklist to confirm you are on schedule at every stage of the race.",
      },
      {
        question: "Can I use this for a negative split plan?",
        answer: "The calculator produces even-pace splits, but you can adapt them for a negative split, where you run the second half faster. Aim to be slightly behind the even-pace time at halfway, then ahead by the finish. Use the even-pace splits as reference points and deliberately add a few seconds to the early ones, banking freshness to spend later. This approach reduces the risk of fading and often yields a stronger finish.",
      },
      {
        question: "Why is the split time shown in minutes?",
        answer: "The result is a decimal number of minutes to keep entry and further calculation simple. Convert the fractional part to seconds by multiplying by sixty: a split of 62.5 minutes is one hour, two minutes, and thirty seconds. For race day you will usually want the split as a clock time, so convert it into hours, minutes, and seconds to match what your watch or the course clocks will display as you pass each marker.",
      },
      {
        question: "Does the split distance have to be halfway?",
        answer: "No. You can enter any split distance up to the total, not just the halfway point. Common choices are every 5 kilometres, each 10-kilometre mark, or specific landmarks on the course. The formula scales the time proportionally to whatever split distance you enter, so you can plan checkpoints wherever they are useful, whether that matches the official timing mats or simply the spots where you plan to check your progress.",
      },
    ],
    relatedCalculators: ["running-pace-calculator", "target-pace-calculator", "race-finish-time-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard sports science (even-pace splits)",
  },
  {
    id: "cycling-calories",
    slug: "cycling-calories-calculator",
    category: "Sports",
    categorySlug: "sports",
    title: "Cycling Calories Calculator",
    shortDescription: "Estimate calories burned cycling using MET values.",
    seoTitle: "Cycling Calories Calculator — Calories Burned Cycling (MET)",
    metaDescription: "Free cycling calories calculator using MET values. Enter your weight, ride duration, and intensity to estimate the calories you burned on the bike.",
    primaryKeyword: "cycling calories calculator",
    secondaryKeywords: ["calories burned cycling", "bike calorie calculator", "cycling met calculator"],
    fields: [
      { id: "weightKg", label: "Body weight", type: "number", unit: "kg", required: true, span: 1, min: 0 },
      { id: "durationMinutes", label: "Ride duration", type: "number", unit: "min", required: true, span: 1, min: 0 },
      { id: "metValue", label: "Intensity (MET)", type: "number", unit: "MET", required: true, span: 2, min: 0, step: 0.1, defaultValue: 8, helpText: "About 4 for a gentle ride, 8 for moderate, 10+ for vigorous." },
    ],
    results: [
      { id: "caloriesBurned", label: "Calories burned", format: "number", decimals: 0, unit: "kcal", isPrimary: true },
    ],
    formula: "calories = MET × 3.5 × weight (kg) ÷ 200 × duration (min)",
    formulaExplanation: "This is the standard MET equation for energy expenditure. The MET value states how many times more oxygen an activity uses than rest, and multiplying it by 3.5 gives millilitres of oxygen per kilogram per minute. Scaling by bodyweight converts that to total oxygen use, and dividing by 200 turns litres of oxygen into kilocalories, since roughly five kilocalories are released per litre of oxygen. Multiplying by the ride's minutes yields the total calories burned.",
    explanation: "This cycling calories calculator estimates how much energy you burned on a ride from your bodyweight, the time you spent riding, and the intensity expressed as a MET value. It uses the standard metabolic equation that underpins most exercise calorie estimates, giving you a reliable ballpark for planning nutrition, managing weight, or simply understanding what a ride cost you.\n\nMET, short for metabolic equivalent of task, rates how hard an activity is compared with sitting quietly. Gentle cycling sits around four METs, a steady moderate ride around eight, and hard, fast riding ten or more. Because the equation also scales with bodyweight, a heavier rider burns more than a lighter one over the same ride, which is why the calculator asks for your weight and lets you choose an intensity that matches how hard you actually rode.\n\nThe formula works because energy use is closely tied to oxygen consumption, and the MET value, bodyweight, and duration together estimate the oxygen you burned, which converts to kilocalories at a known rate. Cyclists use this to plan an energy deficit for fat loss, to replace fuel after long rides so they recover well, and to compare the cost of easy spins against hard efforts. Remember it is an estimate: real burn shifts with wind, terrain, and efficiency, so treat the number as a well-founded guide rather than a precise measurement.",
    example: { inputs: { weightKg: 80, durationMinutes: 60, metValue: 8 }, explanation: "8 × 3.5 × 80 ÷ 200 × 60 = 672 kcal for an hour of moderate cycling at 80 kg." },
    faqs: [
      {
        question: "What MET value should I use for my ride?",
        answer: "Choose the MET that matches how hard you rode. Light, leisurely cycling under about 16 km/h is roughly four METs, a moderate effort around 19 to 22 km/h is close to eight, and vigorous riding above 22 km/h ranges from ten upward, with racing higher still. Mountain biking and strong headwinds raise the figure. Pick the closest match to your average effort, leaning higher for harder rides and lower for gentle ones.",
      },
      {
        question: "Why does the formula divide by 200?",
        answer: "The MET equation first estimates the oxygen your body consumed, in millilitres per minute, from the MET value, the constant 3.5, and your bodyweight. Dividing by 200 converts that oxygen use into kilocalories, because burning one litre of oxygen releases about five kilocalories and the arithmetic of the units works out to a division by two hundred. It is simply the conversion factor that turns oxygen consumption into the energy figure you want.",
      },
      {
        question: "How accurate is the MET method for cycling?",
        answer: "It gives a good estimate but not a precise measurement. Real energy use on a bike varies with wind, gradient, road surface, riding position, and mechanical efficiency, none of which a single MET value captures. Two riders of the same weight at the same average speed can burn different amounts. Treat the result as a planning guide, and if you want more accuracy, a power meter measuring your actual work output is the gold standard.",
      },
      {
        question: "Does bodyweight really affect cycling calories?",
        answer: "Yes, though its effect is smaller on the flat than in running, because the bike supports your weight. Still, a heavier rider burns more energy overall, especially when climbing or accelerating, which is why the equation scales with bodyweight. Entering your accurate weight keeps the estimate realistic. On long climbs the difference grows, since lifting extra mass against gravity is where bodyweight most strongly increases the energy a ride demands.",
      },
      {
        question: "Is a burned calorie the same as a food calorie?",
        answer: "Yes. The calories this tool reports are kilocalories, the same unit shown on food labels, even though everyday language just calls them calories. So a result of 672 means 672 kilocalories, directly comparable to the energy listed on your food packaging. This lets you weigh what you burned against what you eat without any conversion, which is exactly what you need when planning a deficit for weight loss or refuelling after a hard ride.",
      },
    ],
    relatedCalculators: ["cycling-speed-calculator", "running-calories-calculator", "power-to-weight-ratio-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Compendium of Physical Activities (MET method)",
  },
  {
    id: "stride-length",
    slug: "stride-length-calculator",
    category: "Sports",
    categorySlug: "sports",
    title: "Stride Length Calculator",
    shortDescription: "Estimate your stride length and steps per kilometre.",
    seoTitle: "Stride Length Calculator — Stride Length from Height",
    metaDescription: "Free stride length calculator. Enter your height and sex to estimate your walking stride length in centimetres and how many steps you take per kilometre.",
    primaryKeyword: "stride length calculator",
    secondaryKeywords: ["stride length from height", "steps per km calculator", "step length calculator"],
    fields: [
      { id: "heightCm", label: "Height", type: "number", unit: "cm", required: true, span: 1, min: 0 },
      { id: "sex", label: "Sex", type: "select", required: true, span: 1, options: [ { value: "male", label: "Male" }, { value: "female", label: "Female" } ] },
    ],
    results: [
      { id: "strideLengthCm", label: "Stride length", format: "number", decimals: 1, unit: "cm", isPrimary: true },
      { id: "stepsPerKm", label: "Steps per km", format: "number", decimals: 0, unit: "steps", isPrimary: false },
    ],
    formula: "stride = height × 0.415 (male) or × 0.413 (female)",
    formulaExplanation: "Stride length scales closely with height, so multiplying your height by a fixed factor gives a reliable personal estimate of the ground covered per step. The factor differs slightly by sex, 0.415 for men and 0.413 for women, reflecting small average differences in leg proportion and gait. Steps per kilometre then follow by dividing one hundred thousand centimetres, the length of a kilometre, by your stride length in centimetres.",
    explanation: "This stride length calculator estimates how far you travel with each step, and how many steps it takes you to cover a kilometre, from just your height and sex. Stride length is the distance from one footfall to the next of the same foot in everyday use here, and knowing it turns an abstract step count into real distance and helps you understand your own gait.\n\nStride length matters for anyone using a pedometer or fitness tracker, since converting steps into distance depends entirely on it. It is also useful for treadmill calibration, for runners analysing their form, and for setting realistic daily step goals. Because stride length varies with body size, a personal estimate based on your height is far more accurate than a one-size-fits-all average, which is why this tool asks for your height and applies a small sex-based adjustment.\n\nThe calculation rests on the well-established finding that walking stride length is close to a constant fraction of height, about 0.415 for men and 0.413 for women. Multiplying your height by that factor gives your stride in centimetres, and dividing the hundred thousand centimetres in a kilometre by your stride tells you how many steps a kilometre takes. It remains an estimate, since pace, terrain, and running versus walking all change your true stride, but it is a fast, personalised way to make sense of the numbers your tracker reports.",
    example: { inputs: { heightCm: 180, sex: "male" }, explanation: "180 × 0.415 = 74.7 cm stride, so 100,000 ÷ 74.7 ≈ 1,339 steps per kilometre." },
    faqs: [
      {
        question: "How is stride length estimated from height?",
        answer: "The calculator multiplies your height by a factor drawn from research showing stride length is roughly a constant fraction of height for walking, about 0.415 for men and 0.413 for women. A man 180 centimetres tall has an estimated stride near 74.7 centimetres. This gives a personalised figure without measuring your stride directly, though your true stride varies a little with pace, footwear, and whether you are walking or running.",
      },
      {
        question: "Why does the factor differ between men and women?",
        answer: "Men and women differ slightly in average leg length relative to overall height and in typical gait, so a small adjustment to the multiplier improves accuracy. The commonly used factors are 0.415 for men and 0.413 for women, a modest difference that nonetheless refines the estimate. Choosing the correct option tailors the result to your gait a little more closely, though your individual stride may still differ from the average for your sex.",
      },
      {
        question: "What is the difference between step and stride length?",
        answer: "A step is one foot moving forward, measured from one heel strike to the next of the opposite foot, while a stride is a full cycle from one heel strike to the next of the same foot, roughly two steps. Definitions vary between sources, so always check which one a tool uses. Here the value represents the distance advanced per step in the steps-per-kilometre count, keeping the conversion from steps to distance consistent.",
      },
      {
        question: "How can I measure my stride length more precisely?",
        answer: "For a direct measurement, walk a known distance such as twenty metres at your normal pace and count your steps, then divide the distance by the step count to get your average step length. Repeating this a few times and averaging improves reliability. Measuring on the surface and at the pace you usually walk gives a figure tailored to you, which can then replace the height-based estimate for more accurate distance tracking.",
      },
      {
        question: "Does running change my stride length?",
        answer: "Yes, considerably. Running typically lengthens your stride compared with walking, and the faster you run the longer it tends to become, so the walking-based factors here underestimate distance for runs. This calculator is tuned for walking, so for running either measure your running stride directly or rely on a GPS device that records distance from satellites. Using a walking stride to convert running steps would understate how far you actually travelled.",
      },
    ],
    relatedCalculators: ["steps-to-distance-calculator", "running-pace-calculator", "running-calories-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard sports science (height–stride ratio)",
  },
];
