import type { CalculatorDefinition } from "../types";

export const technologyWave3Calculators: CalculatorDefinition[] = [
  {
    id: "download-time",
    slug: "download-time-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Download Time Calculator",
    shortDescription: "Estimate how long a file takes to download.",
    seoTitle: "Download Time Calculator — File Size and Speed to Time",
    metaDescription: "Free download time calculator. Enter a file size in MB and your connection speed in Mbps to estimate the download in seconds and minutes. Fast and accurate.",
    primaryKeyword: "download time calculator",
    secondaryKeywords: ["file download time calculator", "download speed calculator", "how long to download"],
    fields: [
      { id: "fileSize", label: "File size", type: "number", unit: "MB", required: true, span: 1, min: 0 },
      { id: "speed", label: "Connection speed", type: "number", unit: "Mbps", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "seconds", label: "Download time", format: "number", decimals: 1, unit: "s", isPrimary: true },
      { id: "minutes", label: "In minutes", format: "number", decimals: 2, unit: "min", isPrimary: false },
    ],
    formula: "seconds = file size (MB) × 8 ÷ speed (Mbps)",
    formulaExplanation: "File sizes are quoted in megabytes but connection speeds in megabits, and one byte holds eight bits, so multiplying the size by eight converts it to megabits first. Dividing that figure by the speed in megabits per second yields the number of seconds the transfer needs. The eight-to-one factor is the whole reason a fast plan still moves large files more slowly than people expect.",
    explanation: "A download time calculator tells you how long a file will take to arrive over your connection, turning a file size and a speed rating into a clear answer in seconds and minutes. The tricky part is that storage is measured in megabytes while internet plans are advertised in megabits, and there are eight bits in every byte. This calculator handles that conversion for you, so a 100 MB file on a 100 Mbps line correctly comes out as eight seconds rather than one.\n\nKnowing the estimate helps in plenty of everyday situations: deciding whether a video will finish before a meeting, planning a large software update overnight, or judging if a mobile data plan can handle a game install. It also sets honest expectations, since real-world throughput is usually lower than the headline speed because of overhead, congestion, and shared links.\n\nThe formula works because transfer time is simply the amount of data divided by the rate it moves, once both are in matching units. Treat the result as a best-case floor and add a margin for latency and network conditions. Developers, gamers, and anyone waiting on a big file rely on a download time calculator to plan around slow transfers.",
    example: { inputs: { fileSize: 100, speed: 100 }, explanation: "100 MB × 8 = 800 megabits ÷ 100 Mbps = 8 seconds." },
    faqs: [
      {
        question: "Why multiply the file size by eight?",
        answer: "Storage is measured in megabytes (MB) but internet speed in megabits (Mbps), and each byte contains eight bits. To divide like by like, the calculator first converts the file size to megabits by multiplying by eight, then divides by the speed. Skipping this step would make the estimate eight times too optimistic, which is why quoted speeds so often feel slower than expected in practice.",
      },
      {
        question: "Why is my real download slower than the estimate?",
        answer: "The result is a best-case figure that assumes you get the full advertised speed with no losses. In reality, protocol overhead, network congestion, Wi-Fi interference, a busy server, and distance all reduce actual throughput. It is common to see only 70 to 90 percent of the rated speed. Treat the calculator's number as a floor and add a comfortable margin when planning around a large transfer.",
      },
      {
        question: "What units should I enter?",
        answer: "Enter the file size in megabytes (MB) and your connection speed in megabits per second (Mbps), which is how most internet plans are advertised. If your file is listed in gigabytes, multiply by 1,024 to get megabytes first. Keeping both inputs in these labelled units ensures the eight-bit conversion is applied correctly and the resulting seconds and minutes come out accurate.",
      },
      {
        question: "How do I estimate a large file in gigabytes?",
        answer: "Convert the size to megabytes before entering it, since one gigabyte equals 1,024 megabytes. For a 4 GB game, that is about 4,096 MB. Enter that figure with your speed to get the time. Large downloads are where the eight-bit conversion matters most, because a small error in units becomes minutes or hours of difference for multi-gigabyte files.",
      },
      {
        question: "Does upload speed work the same way?",
        answer: "Yes, the same formula applies to uploads if you swap in your upload speed in Mbps. Home connections are usually asymmetric, meaning upload speed is much lower than download, so sending a large file often takes far longer than receiving one of the same size. Check your plan's upload figure and enter it here to estimate how long a backup or video upload will take.",
      },
    ],
    relatedCalculators: ["hosting-bandwidth-calculator", "video-bitrate-calculator", "uptime-sla-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard networking",
  },
  {
    id: "hosting-bandwidth",
    slug: "hosting-bandwidth-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Hosting Bandwidth Calculator",
    shortDescription: "Estimate monthly bandwidth for a website.",
    seoTitle: "Hosting Bandwidth Calculator — Monthly Data Transfer",
    metaDescription: "Free hosting bandwidth calculator. Enter monthly visitors, average page size, and page views per visit to estimate the data transfer your website needs each month.",
    primaryKeyword: "hosting bandwidth calculator",
    secondaryKeywords: ["website bandwidth calculator", "monthly data transfer calculator", "server bandwidth estimate"],
    fields: [
      { id: "monthlyVisitors", label: "Monthly visitors", type: "number", unit: "visitors", required: true, span: 1, min: 0 },
      { id: "pageViewsPerVisit", label: "Page views per visit", type: "number", unit: "views", required: true, span: 1, min: 0 },
      { id: "pageSize", label: "Average page size", type: "number", unit: "MB", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "monthlyGb", label: "Monthly bandwidth", format: "number", decimals: 2, unit: "GB", isPrimary: true },
      { id: "monthlyMb", label: "In megabytes", format: "number", decimals: 0, unit: "MB", isPrimary: false },
    ],
    formula: "bandwidth = visitors × page views × page size",
    formulaExplanation: "Every page a visitor loads sends its full weight of data across the network, so the monthly total is the number of visitors multiplied by how many pages each one views multiplied by the average page size. That product gives megabytes, which the calculator divides by 1,024 to report gigabytes. The model works because bandwidth is simply the sum of all the individual page loads served in a month.",
    explanation: "A hosting bandwidth calculator estimates how much data your website will push to visitors over a month, helping you choose a hosting plan that will not throttle or bill you unexpectedly. It multiplies your monthly visitor count by the average number of pages each person views and by the typical size of a page, then reports the total in gigabytes and megabytes. That single figure is what hosts mean when they advertise a monthly transfer or bandwidth allowance.\n\nGetting the estimate right matters because underprovisioning leads to overage charges or a suspended site during a traffic spike, while overpaying for a huge allowance wastes budget. The calculation also highlights how much page weight drives cost: trimming image sizes or enabling compression can dramatically cut the data you serve without losing any visitors.\n\nThe formula works because total bandwidth is just the sum of every page load, and each load transfers roughly the page's full size. Real usage will vary with caching, returning visitors, and assets loaded from a content delivery network, so add a buffer of 50 percent or more for growth and traffic peaks. Site owners, developers, and anyone comparing hosting plans use a bandwidth calculator to size their infrastructure before committing.",
    example: { inputs: { monthlyVisitors: 10000, pageViewsPerVisit: 3, pageSize: 2 }, explanation: "10,000 × 3 × 2 MB = 60,000 MB ≈ 58.59 GB per month." },
    faqs: [
      {
        question: "What counts as average page size?",
        answer: "Average page size is the total weight of everything a browser downloads to render one page, including HTML, CSS, JavaScript, images, and fonts. Many modern pages sit between 1 and 4 MB, though image-heavy sites run larger. You can measure yours with your browser's developer tools under the network tab. Using an honest average is important, because page size multiplies directly into your monthly bandwidth total.",
      },
      {
        question: "Should I add a safety margin to the result?",
        answer: "Yes. The calculation gives a baseline for expected traffic, but real sites face spikes from marketing campaigns, viral posts, or search rankings. Bots and crawlers add load too. A common practice is to provision at least 50 percent above the estimate, and more if you anticipate rapid growth. Building in headroom prevents overage fees or downtime when a busy day arrives unexpectedly for your website.",
      },
      {
        question: "Does caching reduce my actual bandwidth?",
        answer: "It can, significantly. Browser caching lets returning visitors reuse files they already downloaded, and a content delivery network serves assets from its own edge servers rather than your origin. Both cut the data your host actually transfers. This calculator gives an unoptimised upper estimate, so if you use strong caching or a CDN, your real origin bandwidth may be considerably lower than the figure shown here.",
      },
      {
        question: "How do visitors differ from page views?",
        answer: "A visitor is a single person arriving at your site, while a page view is one page they load. Page views per visit captures how many pages the average person browses before leaving. Multiplying the two gives total page loads. A site with deep engagement has more views per visit and therefore uses more bandwidth than a landing page where most people view only one page.",
      },
      {
        question: "Why report both gigabytes and megabytes?",
        answer: "Hosting plans usually advertise their allowance in gigabytes, so the primary result is shown in GB to match. The megabyte figure is useful for smaller sites or for cross-checking against detailed usage logs, which are often reported in MB. Showing both lets you compare directly against whatever unit your provider or analytics dashboard uses, with 1 GB equal to 1,024 MB throughout.",
      },
    ],
    relatedCalculators: ["download-time-calculator", "uptime-sla-calculator", "video-bitrate-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard networking",
  },
  {
    id: "ip-subnet",
    slug: "ip-subnet-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "IP Subnet Calculator",
    shortDescription: "Find hosts and addresses from a CIDR prefix.",
    seoTitle: "IP Subnet Calculator — CIDR to Hosts and Addresses",
    metaDescription: "Free IP subnet calculator. Enter a CIDR prefix from 0 to 32 to find the number of usable hosts, total addresses, and host bits in an IPv4 subnet instantly.",
    primaryKeyword: "ip subnet calculator",
    secondaryKeywords: ["cidr calculator", "subnet host calculator", "ipv4 subnet calculator"],
    fields: [
      { id: "cidr", label: "CIDR prefix", type: "number", unit: "/n", required: true, span: 2, min: 0, max: 32, step: 1, helpText: "The prefix length after the slash, 0 to 32." },
    ],
    results: [
      { id: "usableHosts", label: "Usable hosts", format: "number", decimals: 0, unit: "hosts", isPrimary: true },
      { id: "totalAddresses", label: "Total addresses", format: "number", decimals: 0, unit: "addresses", isPrimary: false },
      { id: "hostBits", label: "Host bits", format: "number", decimals: 0, unit: "bits", isPrimary: false },
    ],
    formula: "total = 2^(32 − n)  ·  usable = total − 2",
    formulaExplanation: "An IPv4 address is 32 bits, and a CIDR prefix of n fixes the first n bits for the network, leaving 32 − n host bits. Each host bit doubles the count, so two raised to the power of the host bits gives every address in the block. Two are then reserved — the network and broadcast addresses — so usable hosts equal the total minus two, except for the special /31 and /32 cases.",
    explanation: "An IP subnet calculator turns a CIDR prefix, the number after the slash in an address like 192.168.1.0/24, into the practical figures a network engineer needs: how many total addresses the block contains, how many are usable for actual devices, and how many host bits remain. Because IPv4 addresses are 32 bits long, the prefix length directly determines the size of the subnet, and this tool does the powers-of-two arithmetic instantly.\n\nThis matters whenever you design or troubleshoot a network. Choosing the right prefix decides whether a subnet has enough addresses for every device with a little room to grow, without wastefully carving out a block far larger than needed. A /24, for example, gives 254 usable hosts, a familiar size for a small office, while a /30 gives just two, ideal for a point-to-point link.\n\nThe formula works because each host bit doubles the address count, so two raised to the host-bit power counts every address, and subtracting the reserved network and broadcast addresses leaves the usable hosts. The special cases /31 and /32 follow modern conventions for point-to-point links and single hosts. Network administrators, students studying for certifications, and anyone planning IP allocations rely on a subnet calculator to size blocks correctly.",
    example: { inputs: { cidr: 24 }, explanation: "A /24 has 2^(32−24) = 256 total addresses and 256 − 2 = 254 usable hosts." },
    faqs: [
      {
        question: "Why are two addresses subtracted for usable hosts?",
        answer: "In a normal subnet, the first address is the network identifier and the last is the broadcast address, and neither can be assigned to a device. That is why a block of 256 addresses, such as a /24, offers 254 usable hosts. The two reserved addresses let routers identify the subnet and send traffic to every host at once, so they are unavailable for individual machines.",
      },
      {
        question: "What is special about /31 and /32?",
        answer: "A /32 represents a single host, with exactly one usable address, and is common for loopbacks or host routes. A /31 has only two addresses, and modern practice allows both to be used on point-to-point links, so it reports two usable hosts rather than zero. These conventions avoid wasting addresses on links between just two routers, where a full subnet with reserved addresses would be inefficient.",
      },
      {
        question: "What does the CIDR prefix number mean?",
        answer: "The CIDR prefix is the number after the slash and states how many of the 32 bits in an IPv4 address are fixed as the network portion. A larger number means more network bits and fewer host bits, so a smaller subnet. A /24 fixes 24 bits and leaves 8 for hosts, while a /16 leaves 16 host bits and covers far more addresses.",
      },
      {
        question: "How do I pick the right subnet size?",
        answer: "Count the devices you need to address, then choose the smallest prefix that leaves enough usable hosts plus room to grow. For 50 devices, a /26 with 62 usable hosts fits comfortably. Avoid oversizing, which wastes address space, and undersizing, which forces renumbering later. The calculator lets you test prefixes quickly so you can match the block to your real host count.",
      },
      {
        question: "Does this work for IPv6 as well?",
        answer: "No, this calculator is built for IPv4, which uses 32-bit addresses and prefixes from 0 to 32. IPv6 uses 128-bit addresses and much larger prefixes, and it does not reserve network and broadcast addresses the same way, so subnet math differs. For IPv6 planning you would work with the vastly larger address counts and different conventions that its 128-bit structure allows.",
      },
    ],
    relatedCalculators: ["download-time-calculator", "hosting-bandwidth-calculator", "uptime-sla-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard IPv4 addressing (CIDR)",
  },
  {
    id: "screen-ppi",
    slug: "screen-ppi-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Screen PPI Calculator",
    shortDescription: "Find pixel density from resolution and size.",
    seoTitle: "Screen PPI Calculator — Pixels Per Inch from Resolution",
    metaDescription: "Free screen PPI calculator. Enter the horizontal and vertical resolution in pixels and the diagonal size in inches to find a display's pixel density in PPI.",
    primaryKeyword: "screen ppi calculator",
    secondaryKeywords: ["pixel density calculator", "ppi calculator", "pixels per inch calculator"],
    fields: [
      { id: "widthPx", label: "Horizontal resolution", type: "number", unit: "px", required: true, span: 1, min: 0 },
      { id: "heightPx", label: "Vertical resolution", type: "number", unit: "px", required: true, span: 1, min: 0 },
      { id: "diagonalInches", label: "Diagonal size", type: "number", unit: "in", required: true, span: 2, min: 0 },
    ],
    results: [
      { id: "ppi", label: "Pixel density", format: "number", decimals: 1, unit: "PPI", isPrimary: true },
    ],
    formula: "PPI = √(width² + height²) ÷ diagonal",
    formulaExplanation: "The diagonal resolution in pixels comes from the Pythagorean theorem, since the horizontal and vertical pixel counts form the two sides of a right triangle whose hypotenuse spans the screen corner to corner. Dividing that diagonal pixel count by the physical diagonal length in inches gives pixels per inch. The method works because the diagonal is the one line whose length is quoted both in pixels and in inches.",
    explanation: "A screen PPI calculator measures pixel density, the number of pixels packed into each inch of a display, from just three numbers: the horizontal resolution, the vertical resolution, and the diagonal size in inches. Higher PPI means finer detail and smoother text, which is why the same 1080p resolution looks razor-sharp on a phone but noticeably coarser stretched across a large monitor.\n\nPixel density matters when comparing displays, choosing a monitor for design or coding work, or deciding how close you can sit before individual pixels become visible. Manufacturers quote resolution and screen size separately, but neither alone tells you how crisp the picture will be. PPI combines them into a single, comparable figure, so a 27-inch 4K panel and a 24-inch 1080p panel can be judged fairly side by side.\n\nThe formula works by first finding the diagonal in pixels using the Pythagorean theorem on the width and height, then dividing by the diagonal in inches. Because the diagonal is measured in both pixels and inches, the division yields pixels per inch directly. Displays around 300 PPI or higher appear seamless at normal viewing distance. Shoppers, designers, and hardware reviewers use a PPI calculator to cut through marketing specs and compare screen sharpness honestly.",
    example: { inputs: { widthPx: 1920, heightPx: 1080, diagonalInches: 15.6 }, explanation: "√(1920² + 1080²) ÷ 15.6 ≈ 2202.9 ÷ 15.6 ≈ 141.2 PPI." },
    faqs: [
      {
        question: "What is a good PPI for a display?",
        answer: "It depends on viewing distance. Phones held close often exceed 400 PPI, while laptops look sharp around 200 to 300 PPI, and desktop monitors viewed further away read as crisp near 110 to 160 PPI. Beyond a certain density the eye cannot resolve individual pixels at normal distance, so higher numbers stop mattering. Judge PPI against how close you sit rather than chasing the largest figure.",
      },
      {
        question: "Why use the diagonal instead of width or height?",
        answer: "Screen sizes are always quoted by their diagonal measurement, so that is the one physical length you know in inches. To divide pixels by inches you need a matching pixel length along the same line, which the Pythagorean theorem provides from the width and height. Using the diagonal keeps the pixel measurement and the inch measurement aligned along the same axis for a correct density.",
      },
      {
        question: "Does higher PPI always look better?",
        answer: "Not necessarily. Once pixel density passes what your eye can distinguish at your viewing distance, extra PPI brings no visible improvement but can cost more and demand more graphics power. It can also make interface elements tiny unless the operating system scales them up. The right PPI balances sharpness, cost, and comfortable element sizes for how and where you actually use the screen.",
      },
      {
        question: "What is the difference between PPI and DPI?",
        answer: "PPI, pixels per inch, describes the density of a digital display. DPI, dots per inch, describes how many ink dots a printer lays down per inch on paper. The terms are often used interchangeably, but they refer to different media. For on-screen sharpness you want PPI; for print quality you want DPI. This calculator deals strictly with screen pixel density in PPI.",
      },
      {
        question: "Can I use this for any aspect ratio?",
        answer: "Yes. The formula uses the actual horizontal and vertical pixel counts, so it works for any aspect ratio, whether 16:9, 16:10, 4:3, or an ultrawide 21:9 panel. Just enter the true resolution and the diagonal size, and the Pythagorean calculation adapts automatically. That makes it equally valid for phones, tablets, laptops, standard monitors, and unusually wide or tall displays alike.",
      },
    ],
    relatedCalculators: ["aspect-ratio-calculator", "video-bitrate-calculator", "download-time-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard digital media",
  },
  {
    id: "video-bitrate",
    slug: "video-bitrate-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Video Bitrate Calculator",
    shortDescription: "Estimate video file size from bitrate.",
    seoTitle: "Video Bitrate Calculator — Bitrate and Length to File Size",
    metaDescription: "Free video bitrate calculator. Enter a video's duration in minutes and bitrate in Mbps to estimate the file size in gigabytes and megabytes. Ideal for encoding.",
    primaryKeyword: "video bitrate calculator",
    secondaryKeywords: ["video file size calculator", "bitrate to file size", "video size estimator"],
    fields: [
      { id: "durationMinutes", label: "Duration", type: "number", unit: "min", required: true, span: 1, min: 0 },
      { id: "bitrateMbps", label: "Bitrate", type: "number", unit: "Mbps", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "sizeGb", label: "File size", format: "number", decimals: 2, unit: "GB", isPrimary: true },
      { id: "sizeMb", label: "In megabytes", format: "number", decimals: 0, unit: "MB", isPrimary: false },
    ],
    formula: "size (MB) = bitrate (Mbps) × minutes × 60 ÷ 8",
    formulaExplanation: "Bitrate measures how many megabits of data each second of video carries, so multiplying it by the length in seconds gives the total megabits. The duration is in minutes, so it is multiplied by 60 first. Dividing by eight converts megabits to megabytes, because a byte holds eight bits. The result is then divided by 1,024 to express the size in gigabytes for larger files.",
    explanation: "A video bitrate calculator estimates how large a video file will be from two inputs: how long it runs and the bitrate it is encoded at. Bitrate, measured in megabits per second, is the amount of data used to represent each second of footage, so it is the single biggest lever on file size and visual quality. This tool multiplies bitrate by duration and handles the bit-to-byte conversion to report the size in gigabytes and megabytes.\n\nThe estimate is invaluable when planning storage, uploads, and streaming. Videographers checking whether footage fits a memory card, creators judging upload times, and streamers balancing quality against bandwidth all need to predict size before committing to an encode. It also makes the quality trade-off concrete: doubling the bitrate roughly doubles both the file size and the detail retained.\n\nThe formula works because total data equals rate multiplied by time, once units line up. Multiplying minutes by sixty gives seconds, multiplying by bitrate gives megabits, and dividing by eight converts to megabytes. Real encodes using variable bitrate will vary around this figure, since complex scenes consume more data than simple ones, so treat it as a close average. Editors, streamers, and anyone managing video files rely on a bitrate calculator to size projects accurately.",
    example: { inputs: { durationMinutes: 10, bitrateMbps: 8 }, explanation: "8 Mbps × 10 min × 60 ÷ 8 = 600 MB ≈ 0.59 GB." },
    faqs: [
      {
        question: "What bitrate should I use for good quality?",
        answer: "It depends on resolution and content. As a rough guide, 1080p at 30 frames per second looks good around 8 Mbps, while 4K often needs 35 to 45 Mbps. Fast motion and fine detail demand higher bitrates to avoid blocky artefacts. Streaming platforms publish recommended ranges. Enter a candidate bitrate here to see how the file size changes before committing to a full export.",
      },
      {
        question: "Why divide by eight in the formula?",
        answer: "Bitrate is quoted in megabits per second, but file sizes are measured in megabytes, and there are eight bits in a byte. After multiplying bitrate by the total seconds to get megabits, the calculator divides by eight to convert to megabytes. Forgetting this step would overstate the file size by a factor of eight, so the conversion is essential for a realistic estimate.",
      },
      {
        question: "Does variable bitrate change the estimate?",
        answer: "Yes, somewhat. Variable bitrate encoding spends more data on complex, fast-moving scenes and less on simple, static ones, so the true size fluctuates around the average. This calculator assumes a constant average bitrate, which is a good approximation for the final size. If your encoder targets a specific average bitrate, the result will be close; scene-by-scene it will vary above and below.",
      },
      {
        question: "How do I account for the audio track?",
        answer: "This calculator estimates the video stream from the bitrate you enter. If that bitrate already includes audio, the result covers the whole file. If it is video-only, add the audio separately: a typical stereo track adds about 128 to 320 kilobits per second, which over a long video can add tens of megabytes. For most estimates the audio contribution is small next to the video.",
      },
      {
        question: "Can I use this to plan upload time?",
        answer: "Yes. Once you have the file size from this calculator, pair it with a download or upload time calculator using your connection's upload speed to estimate how long sending the file will take. This two-step approach is handy for creators uploading to video platforms, since large high-bitrate files can take considerable time on typical asymmetric home connections with limited upload speed.",
      },
    ],
    relatedCalculators: ["download-time-calculator", "screen-ppi-calculator", "hosting-bandwidth-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard digital media",
  },
  {
    id: "uptime-sla",
    slug: "uptime-sla-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Uptime SLA Calculator",
    shortDescription: "Convert an uptime percentage into allowed downtime.",
    seoTitle: "Uptime SLA Calculator — Downtime per Year, Month, Day",
    metaDescription: "Free uptime SLA calculator. Enter a target uptime percentage to find the maximum allowed downtime per year, month, and day. Understand what 99.9% really means.",
    primaryKeyword: "uptime sla calculator",
    secondaryKeywords: ["sla downtime calculator", "availability calculator", "nines uptime calculator"],
    fields: [
      { id: "uptimePercent", label: "Target uptime", type: "number", unit: "%", required: true, span: 2, min: 0, max: 100, step: 0.001, helpText: "For example 99.9 for three nines." },
    ],
    results: [
      { id: "downtimeYearMinutes", label: "Downtime per year", format: "number", decimals: 1, unit: "min/yr", isPrimary: true },
      { id: "downtimeMonthMinutes", label: "Per month", format: "number", decimals: 1, unit: "min/mo", isPrimary: false },
      { id: "downtimeDayMinutes", label: "Per day", format: "number", decimals: 2, unit: "min/day", isPrimary: false },
    ],
    formula: "downtime = (1 − uptime%) × period",
    formulaExplanation: "Uptime and downtime always sum to one hundred percent, so the allowed downtime fraction is one minus the uptime fraction. Multiplying that fraction by the length of a period gives the outage budget for it: a full year is 365 × 24 × 60 minutes, a month is that year divided by twelve, and a day is 24 × 60 minutes. The method works because downtime is simply the leftover share of time the service may be unavailable.",
    explanation: "An uptime SLA calculator converts an availability percentage, the kind quoted in a service level agreement, into the concrete downtime it permits over a year, a month, and a day. Percentages like 99.9 percent sound reassuring but are hard to picture, so this tool translates them into minutes of allowed outage, which is far easier to plan against and to hold a provider accountable to.\n\nThis matters on both sides of an agreement. If you run a service, the figure tells you how tight your monitoring, redundancy, and on-call response must be to meet the promise. If you depend on a service, it reveals exactly how much disruption the SLA actually tolerates before penalties apply. The jump between tiers is dramatic: three nines allows over eight hours of downtime a year, while five nines permits barely five minutes.\n\nThe formula works because downtime is the share of time the service is not available, which is one minus the uptime fraction, multiplied by the length of the period. Real agreements may exclude scheduled maintenance or measure over specific windows, so read the fine print alongside this estimate. Site reliability engineers, IT managers, and anyone negotiating or auditing an SLA use an uptime calculator to make availability targets tangible.",
    example: { inputs: { uptimePercent: 99.9 }, explanation: "1 − 0.999 = 0.001, so 0.001 × 365 × 24 × 60 ≈ 525.6 minutes of downtime per year." },
    faqs: [
      {
        question: "What does 99.9% uptime actually allow?",
        answer: "Three nines, or 99.9 percent uptime, permits about 525.6 minutes of downtime per year, which is roughly 8.76 hours, or about 43.8 minutes each month. It sounds nearly perfect, but that is still enough time for several meaningful outages annually. Seeing the figure in minutes helps you judge whether a given SLA tier truly meets your tolerance for disruption or only appears to on paper.",
      },
      {
        question: "How much downtime does each extra nine remove?",
        answer: "Each additional nine cuts allowed downtime by a factor of ten. Two nines (99%) permits about 3.65 days a year, three nines about 8.76 hours, four nines about 52.6 minutes, and five nines only about 5.26 minutes. The cost and engineering effort to reach each higher tier rises steeply, so match the target to what your users genuinely need rather than chasing nines for their own sake.",
      },
      {
        question: "Does scheduled maintenance count against the SLA?",
        answer: "It depends on the agreement. Many SLAs exclude planned maintenance windows announced in advance, counting only unplanned outages against the uptime figure. Others count all unavailability. This distinction matters, because a provider with generous maintenance exclusions may deliver less real availability than the headline number suggests. Always read how the SLA defines downtime and what it excludes before comparing two providers' promises directly.",
      },
      {
        question: "Why show downtime per year, month, and day?",
        answer: "Different planning horizons need different views. The yearly figure is how SLAs are usually headlined, the monthly figure often matches the billing and reporting cycle providers use for credits, and the daily figure helps you gauge the impact of a single bad day. Showing all three lets you connect an abstract percentage to the operational reality of monitoring and incident response at each timescale.",
      },
      {
        question: "How is downtime calculated from the percentage?",
        answer: "The calculator subtracts your uptime percentage from 100 to get the downtime percentage, converts it to a fraction, and multiplies by the minutes in each period. A year is treated as 365 days, a month as one twelfth of that year, and a day as 24 hours. This gives the maximum minutes the service may be unavailable while still meeting the stated availability target.",
      },
    ],
    relatedCalculators: ["hosting-bandwidth-calculator", "download-time-calculator", "ip-subnet-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard networking",
  },
  {
    id: "aspect-ratio",
    slug: "aspect-ratio-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Aspect Ratio Calculator",
    shortDescription: "Reduce a width and height to a simple ratio.",
    seoTitle: "Aspect Ratio Calculator — Width and Height to Ratio",
    metaDescription: "Free aspect ratio calculator. Enter a width and height in pixels to get the simplified aspect ratio, such as 16:9, along with its decimal value. Fast and exact.",
    primaryKeyword: "aspect ratio calculator",
    secondaryKeywords: ["ratio calculator", "screen aspect ratio calculator", "image ratio calculator"],
    fields: [
      { id: "width", label: "Width", type: "number", unit: "px", required: true, span: 1, min: 0 },
      { id: "height", label: "Height", type: "number", unit: "px", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "ratio", label: "Aspect ratio", format: "text", isPrimary: true },
      { id: "decimal", label: "Decimal ratio", format: "number", decimals: 4, isPrimary: false },
    ],
    formula: "ratio = width ÷ gcd : height ÷ gcd",
    formulaExplanation: "An aspect ratio is width divided by height expressed in the smallest whole numbers. Dividing both dimensions by their greatest common divisor, the largest number that goes evenly into each, reduces the pair to that lowest form without changing the proportion. For example, 1920 and 1080 share a divisor of 120, giving 16:9. The decimal value is simply width divided by height, useful for direct comparison.",
    explanation: "An aspect ratio calculator reduces a width and a height to the simplest whole-number ratio that describes their proportion, such as turning 1920 by 1080 into a clean 16:9. It also reports the decimal equivalent, the width divided by the height, which is handy for sorting or comparing shapes numerically. Aspect ratio captures the shape of a rectangle independent of its actual size, so a phone thumbnail and a cinema screen can share the same ratio.\n\nThis matters across photography, video, web design, and print. Matching aspect ratios keeps images from being stretched or cropped unexpectedly when they move between a camera, a layout, and a display. Knowing the ratio helps you pick the right export preset, design responsive layouts, and choose media that fills a screen without letterboxing or distortion.\n\nThe calculation works by finding the greatest common divisor of the two dimensions and dividing both by it, which reduces the fraction to its lowest terms while preserving the exact proportion. Common results like 16:9, 4:3, 3:2, and 21:9 correspond to familiar screen and photo formats. Designers, photographers, video editors, and developers use an aspect ratio calculator to keep proportions consistent and avoid the awkward stretching that follows a mismatched ratio.",
    example: { inputs: { width: 1920, height: 1080 }, explanation: "The greatest common divisor of 1920 and 1080 is 120, so the ratio is 16:9 (decimal 1.7778)." },
    faqs: [
      {
        question: "What is an aspect ratio?",
        answer: "An aspect ratio describes the proportional relationship between a rectangle's width and its height, written as two numbers separated by a colon, such as 16:9. It captures shape rather than size, so any 16:9 image has the same proportions whether it is a tiny thumbnail or a huge television. Knowing the ratio lets you scale, fit, and compare images and screens without distorting them.",
      },
      {
        question: "How is the ratio simplified?",
        answer: "The calculator finds the greatest common divisor of the width and height, the largest whole number that divides both exactly, then divides each dimension by it. This reduces the pair to its smallest whole-number form while keeping the proportion identical. For 1920 by 1080 the divisor is 120, producing 16:9. Simplifying this way gives the familiar ratios people recognise instead of unwieldy large numbers.",
      },
      {
        question: "What are common aspect ratios?",
        answer: "Widespread ratios include 16:9 for modern televisions and most online video, 4:3 for older displays and some tablets, 3:2 for many still cameras and prints, 1:1 for square social media posts, and 21:9 for ultrawide monitors and cinematic film. Recognising these helps you choose export settings and crops that match your target display or platform without introducing black bars or stretching.",
      },
      {
        question: "Why does the decimal value help?",
        answer: "The decimal ratio, width divided by height, gives a single number you can compare directly, which is useful when two ratios look similar. For instance, 16:9 is about 1.78 and 16:10 is 1.60, so the decimals make the difference obvious. It is also handy in code and spreadsheets, where a numeric value is easier to sort, filter, or calculate against than a colon-separated pair.",
      },
      {
        question: "What if my numbers do not reduce neatly?",
        answer: "Some dimensions share no large common divisor and reduce to an unusual ratio with big numbers, which simply means the shape does not match a standard format. That is normal for arbitrary crops. You can still use the decimal value to compare it against common ratios, and if you need a standard shape, adjust the width or height slightly until it reduces to a familiar ratio like 16:9.",
      },
    ],
    relatedCalculators: ["screen-ppi-calculator", "video-bitrate-calculator", "download-time-calculator"],
    status: "active",
    lastReviewed: "2026-08-20",
    formulaSource: "Standard digital media",
  },
];
