import type { CalculatorDefinition } from "../types";

export const technologyR5Calculators: CalculatorDefinition[] = [
  {
    id: "password-entropy",
    slug: "password-strength-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Password Strength Calculator",
    shortDescription: "Estimate password entropy in bits from length and character set.",
    seoTitle: "Password Strength Calculator — Entropy in Bits",
    metaDescription: "Free password strength calculator. Enter a password length and character set to estimate its entropy in bits and see whether it rates as weak, fair, strong, or very strong.",
    primaryKeyword: "password strength calculator",
    secondaryKeywords: ["password entropy calculator", "password bits calculator", "how strong is my password"],
    fields: [
      { id: "length", label: "Password length", type: "number", unit: "chars", required: true, span: 1, min: 1, step: 1 },
      {
        id: "charsetSize",
        label: "Character set",
        type: "select",
        required: true,
        span: 1,
        defaultValue: "62",
        options: [
          { value: "26", label: "Lowercase only (26)" },
          { value: "52", label: "Mixed case (52)" },
          { value: "62", label: "Letters + digits (62)" },
          { value: "95", label: "All ASCII symbols (95)" },
        ],
      },
    ],
    results: [
      { id: "entropyBits", label: "Entropy", format: "number", decimals: 1, unit: "bits", isPrimary: true },
      { id: "crackLabel", label: "Strength rating", format: "text", isPrimary: false },
    ],
    formula: "entropy (bits) = length × log2(character set size)",
    formulaExplanation: "Entropy measures how many yes-or-no questions an attacker would need to guess a password, and each character drawn from a pool of a given size adds log base two of that pool size in bits. Multiplying by the length adds that contribution once per character, because the choices are independent. A larger pool or a longer password both raise the exponent on the number of possible combinations, which is why both length and variety strengthen a password.",
    explanation: "A password strength calculator estimates entropy, the mathematical measure of how unpredictable a password is, expressed in bits. Each bit doubles the number of guesses an attacker must try, so a password with 60 bits of entropy is over a thousand times harder to crack by brute force than one with 50 bits. This tool takes two inputs that drive entropy: the password length and the size of the character set it draws from.\n\nUnderstanding entropy helps you build passwords that resist modern cracking hardware, which can test billions of guesses per second. Length is the most powerful lever because it multiplies directly into the exponent, which is why a long passphrase of common words can outscore a short string of random symbols. The character set matters too: adding uppercase letters, digits, and symbols enlarges the pool each position is chosen from.\n\nThe formula works because a random password of length L from a pool of N characters has N to the power L possible values, and the base-two logarithm of that count is the entropy in bits. This calculator assumes each character is chosen randomly and independently; predictable patterns, dictionary words, or reused passwords reduce real strength far below the theoretical figure. Security-minded users, developers setting password policies, and anyone auditing their credentials use an entropy calculator to judge password quality objectively.",
    example: { inputs: { length: 16, charsetSize: 95 }, explanation: "16 × log2(95) ≈ 16 × 6.57 ≈ 105 bits, which rates as very strong." },
    faqs: [
      {
        question: "What is password entropy measured in bits?",
        answer: "Entropy in bits describes how unpredictable a password is, where each additional bit doubles the number of possible combinations an attacker must try. A password with 40 bits has about a trillion possibilities, while 80 bits has over a septillion. Higher entropy means exponentially more guessing effort. Because the scale is logarithmic, small increases in length or character variety produce large jumps in real-world cracking difficulty.",
      },
      {
        question: "How many bits of entropy are safe?",
        answer: "As a rough guide, under 40 bits is weak and crackable quickly, 40 to 60 is fair but vulnerable to determined attackers, 60 to 80 is strong for most purposes, and above 80 bits is very strong against brute force with current hardware. For sensitive accounts, aim for 80 bits or more. Remember these figures assume truly random characters, so patterns and reuse lower actual strength.",
      },
      {
        question: "Does a longer password beat a more complex one?",
        answer: "Usually yes. Because length multiplies directly into the entropy, adding characters raises strength faster than switching to a larger symbol set. A long passphrase of several random words can exceed the entropy of a short string of mixed symbols while being far easier to remember. This is why security guidance increasingly favours length, encouraging passphrases over cryptic but short passwords that are hard to recall.",
      },
      {
        question: "Why does the character set size matter?",
        answer: "The character set is the pool each position is chosen from, and a larger pool means each character carries more entropy. Lowercase letters alone give 26 options, adding uppercase reaches 52, adding digits reaches 62, and adding symbols reaches around 95. Enlarging the set raises the base of the exponent, so every character contributes more bits. Combined with length, it determines the total unpredictability of the password.",
      },
      {
        question: "Does this account for dictionary attacks?",
        answer: "No, the entropy figure assumes every character is chosen randomly and independently. Real passwords built from dictionary words, names, dates, or predictable substitutions are far weaker than their length suggests, because attackers try likely patterns first. Treat the result as an upper bound that applies only to genuinely random passwords. For real security, use a password manager to generate random strings rather than inventing memorable but guessable ones.",
      },
    ],
    relatedCalculators: ["ip-subnet-calculator", "uptime-sla-calculator", "download-time-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Shannon entropy (information theory)",
  },
  {
    id: "hex-rgb",
    slug: "hex-to-rgb-converter",
    category: "Technology",
    categorySlug: "technology",
    title: "Hex to RGB Converter",
    shortDescription: "Convert a hex color code into RGB values.",
    seoTitle: "Hex to RGB Converter — Hex Color Code to RGB",
    metaDescription: "Free hex to RGB converter. Enter a 3- or 6-digit hex color code such as #0EA5E9 to get its red, green, and blue channel values and a ready-to-use rgb() string.",
    primaryKeyword: "hex to rgb converter",
    secondaryKeywords: ["hex to rgb", "hex color converter", "hex code to rgb"],
    fields: [
      { id: "hex", label: "Hex color code", type: "text", placeholder: "#0EA5E9", required: true, span: 2, helpText: "A 3- or 6-digit hex code, with or without the leading #." },
    ],
    results: [
      { id: "rgb", label: "RGB value", format: "text", isPrimary: true },
      { id: "red", label: "Red", format: "number", decimals: 0, isPrimary: false },
      { id: "green", label: "Green", format: "number", decimals: 0, isPrimary: false },
      { id: "blue", label: "Blue", format: "number", decimals: 0, isPrimary: false },
    ],
    formula: "each channel = the two hex digits read as a base-16 number (0–255)",
    formulaExplanation: "A hex color packs three colour channels into six hexadecimal digits, two per channel. Each pair is a base-16 number, so the digits are read as sixteens and units: the left digit is multiplied by sixteen and added to the right digit, giving a value from 0 to 255. Shorthand three-digit codes double each digit first. The conversion works because hexadecimal is simply a compact way of writing the same 0-to-255 byte each channel uses.",
    explanation: "A hex to RGB converter translates a hexadecimal color code, the six-character strings like #0EA5E9 used throughout web and graphic design, into the red, green, and blue values that describe the same color numerically. Both formats represent identical colors; hex is compact and common in CSS and design tools, while RGB is easier to read, adjust, and use in contexts like image editing or programmatic color math.\n\nThis conversion is useful whenever you move between tools that prefer different notations. A brand guide might specify hex codes, but a spreadsheet, a native app, or an animation library might want separate R, G, and B numbers. Seeing the channel values also helps you understand and tweak a color: raising the red value warms it, while equal channels produce a grey. The tool accepts both full six-digit codes and three-digit shorthand.\n\nThe conversion works because each pair of hex digits encodes one channel as a number from 0 to 255, the range a single byte can hold. Reading each pair in base sixteen recovers that value directly, and the three together define the color. Web developers, designers, and anyone matching colors across applications use a hex to RGB converter to keep colors consistent when they cross between design systems, code, and content.",
    example: { inputs: { hex: "#0EA5E9" }, explanation: "0E = 14, A5 = 165, E9 = 233, giving rgb(14, 165, 233)." },
    faqs: [
      {
        question: "What is the difference between hex and RGB?",
        answer: "Hex and RGB describe the exact same colors in different notations. RGB lists three numbers from 0 to 255 for red, green, and blue. Hex encodes those same three values as pairs of base-16 digits in a single string prefixed with a hash. Hex is compact and dominant in web CSS, while RGB is easier to read and adjust arithmetically. Converting between them never changes the colour itself.",
      },
      {
        question: "Can I enter a 3-digit hex code?",
        answer: "Yes. Three-digit shorthand hex codes expand each digit by doubling it, so #0af becomes #00aaff. This shorthand only works when both digits of each channel are identical, which is why it can express fewer colours than the full six-digit form. The converter automatically detects and expands three-digit codes, then reads each resulting pair as a channel value, so either format returns the correct RGB result.",
      },
      {
        question: "Do I need to include the hash symbol?",
        answer: "No. The converter accepts codes with or without the leading hash, so #0EA5E9 and 0EA5E9 both work. The hash is a convention that marks a value as a hex color in CSS and design tools, but it carries no colour information itself. Whichever way you paste the code, the converter strips any hash and reads the remaining digits as the three colour channels.",
      },
      {
        question: "What do the red, green, and blue numbers mean?",
        answer: "Each of the three numbers ranges from 0 to 255 and states the intensity of that primary colour channel. Zero means the channel is off and 255 means it is at full strength. Screens mix these three lights additively, so all three at 255 make white, all at 0 make black, and equal middling values make grey. Adjusting one channel shifts the colour toward or away from that primary.",
      },
      {
        question: "Why is the range 0 to 255 for each channel?",
        answer: "Each channel is stored in one byte, which holds eight bits and therefore 256 distinct values from 0 to 255. Two hexadecimal digits express exactly that range, since sixteen times sixteen is 256. This eight-bit-per-channel scheme gives about 16.7 million possible colours across the three channels, enough that the eye perceives smooth gradients. It is the standard depth for web and most everyday digital colour.",
      },
    ],
    relatedCalculators: ["aspect-ratio-calculator", "screen-ppi-calculator", "image-file-size-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard digital media (sRGB)",
  },
  {
    id: "image-file-size",
    slug: "image-file-size-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Image File Size Calculator",
    shortDescription: "Estimate an uncompressed image's size from its dimensions.",
    seoTitle: "Image File Size Calculator — Pixels and Bit Depth to Size",
    metaDescription: "Free image file size calculator. Enter width, height, and bit depth to estimate an uncompressed image's size in megabytes and kilobytes. Ideal for planning storage.",
    primaryKeyword: "image file size calculator",
    secondaryKeywords: ["image size calculator", "uncompressed image size", "bitmap size calculator"],
    fields: [
      { id: "widthPx", label: "Width", type: "number", unit: "px", required: true, span: 1, min: 0 },
      { id: "heightPx", label: "Height", type: "number", unit: "px", required: true, span: 1, min: 0 },
      { id: "bitDepth", label: "Bit depth", type: "number", unit: "bits/px", required: true, span: 2, min: 1, defaultValue: 24, helpText: "24 for standard color, 32 with an alpha channel." },
    ],
    results: [
      { id: "sizeMB", label: "File size", format: "number", decimals: 2, unit: "MB", isPrimary: true },
      { id: "sizeKB", label: "In kilobytes", format: "number", decimals: 0, unit: "KB", isPrimary: false },
    ],
    formula: "size (MB) = width × height × bit depth ÷ 8 ÷ 1,048,576",
    formulaExplanation: "An uncompressed image stores a fixed number of bits for every pixel, so the total bits equal the pixel count, width times height, multiplied by the bit depth. Dividing by eight converts bits to bytes, and dividing by 1,048,576 (1,024 squared) converts bytes to megabytes. The method works because a raw bitmap has no compression, so its size is exactly the sum of the bits it dedicates to each of its pixels.",
    explanation: "An image file size calculator estimates how much space an uncompressed image occupies from three numbers: its width and height in pixels and its bit depth, the number of bits used to describe each pixel's colour. Because a raw bitmap stores a fixed amount of data per pixel, this gives a precise upper bound on size, which is exactly what formats like BMP or uncompressed TIFF produce and what a program holds in memory while editing.\n\nThe estimate helps when planning storage, memory use, and bandwidth. A photographer batching thousands of raw frames, a developer sizing a texture budget, or anyone deciding whether images fit a card or upload limit needs to know the worst-case footprint before compression. It also reveals how quickly dimensions inflate size: doubling both width and height quadruples the pixel count and the file.\n\nThe formula works by counting total bits as pixels multiplied by bit depth, then converting to bytes by dividing by eight and to megabytes by dividing by 1,048,576. Common bit depths are 24 bits for full colour and 32 bits when an alpha transparency channel is added. Real saved files are usually far smaller because formats like JPEG and PNG compress the data, so treat this as the uncompressed maximum. Designers, photographers, and developers use an image size calculator to plan storage and memory around raw image data.",
    example: { inputs: { widthPx: 1920, heightPx: 1080, bitDepth: 24 }, explanation: "1920 × 1080 × 24 ÷ 8 ÷ 1,048,576 ≈ 5.93 MB uncompressed." },
    faqs: [
      {
        question: "Why is my saved image much smaller than this?",
        answer: "This calculator estimates the uncompressed size, the raw data with no compression applied. Real formats like JPEG, PNG, and WebP compress images significantly, often shrinking them to a fraction of the raw figure. JPEG in particular can reduce a photo by ten times or more with little visible loss. The uncompressed number is useful for memory planning and worst-case storage, while the saved file reflects the compression your format applies.",
      },
      {
        question: "What bit depth should I use?",
        answer: "Standard full-colour images use 24 bits per pixel, eight bits each for red, green, and blue. Add an alpha transparency channel and it becomes 32 bits. High dynamic range or professional workflows may use 48 bits or more for finer gradation. Grayscale images use 8 bits. Choose the depth that matches your image: 24 is right for most colour photos, and 32 when you need transparency.",
      },
      {
        question: "How does resolution affect file size?",
        answer: "File size scales with the total pixel count, which is width times height. Because both dimensions multiply, doubling each one quadruples the pixels and therefore the size. A 4K image has four times the pixels of a 1080p image and roughly four times the raw size. This quadratic growth is why high-resolution images consume storage and memory so quickly, and why resizing is such an effective way to save space.",
      },
      {
        question: "Does this apply to images in memory too?",
        answer: "Yes, and that is one of its most useful applications. When a program opens an image to edit or display it, the image is typically held uncompressed in memory at roughly this size, regardless of how small the compressed file on disk is. This is why editing many large images can exhaust memory even when the saved files seem modest. The calculator estimates that in-memory footprint accurately.",
      },
      {
        question: "Why divide by 1,048,576 for megabytes?",
        answer: "In computing, a megabyte is often defined as 1,024 kilobytes, and a kilobyte as 1,024 bytes, so one megabyte equals 1,024 times 1,024, which is 1,048,576 bytes. This calculator uses that binary convention. Some storage manufacturers instead use 1,000,000 bytes per megabyte, which is why advertised drive capacities can look slightly larger than what an operating system reports for the same space.",
      },
    ],
    relatedCalculators: ["aspect-ratio-calculator", "screen-ppi-calculator", "video-bitrate-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard digital media",
  },
  {
    id: "px-rem",
    slug: "px-to-rem-converter",
    category: "Technology",
    categorySlug: "technology",
    title: "PX to REM Converter",
    shortDescription: "Convert pixels to rem and em for responsive CSS.",
    seoTitle: "PX to REM Converter — Pixels to REM and EM",
    metaDescription: "Free px to rem converter. Enter a pixel value and your root font size to get the equivalent rem and em units for responsive, accessible CSS. Fast and exact.",
    primaryKeyword: "px to rem converter",
    secondaryKeywords: ["pixels to rem", "px to em converter", "css unit converter"],
    fields: [
      { id: "pixels", label: "Pixel value", type: "number", unit: "px", required: true, span: 1, min: 0 },
      { id: "rootFontSize", label: "Root font size", type: "number", unit: "px", required: true, span: 1, min: 1, defaultValue: 16, helpText: "The browser default is 16px." },
    ],
    results: [
      { id: "rem", label: "In rem", format: "number", decimals: 4, unit: "rem", isPrimary: true },
      { id: "em", label: "In em", format: "number", decimals: 4, unit: "em", isPrimary: false },
    ],
    formula: "rem = pixels ÷ root font size",
    formulaExplanation: "The rem unit is defined as a multiple of the root font size, so converting a pixel value means asking how many root-font-size steps fit into it, which is simply the pixels divided by the root size. With the common 16-pixel default, 16px equals 1rem and 24px equals 1.5rem. The em unit uses the same division against its reference font size, so with a matching reference the numeric value is identical.",
    explanation: "A px to rem converter translates fixed pixel measurements into rem units, the scalable unit that underpins responsive and accessible CSS. A rem is defined relative to the root font size of the page, so sizing in rem lets an entire layout grow or shrink in proportion when a user changes their browser's base font size, something pixels ignore. This tool divides your pixel value by the root font size to give the exact rem equivalent, and the matching em value.\n\nUsing rem matters for accessibility and maintainability. Readers who increase their default font size, often because they need larger text, see rem-based layouts scale gracefully while pixel-based ones stay stubbornly fixed. Working in rem also makes global type scaling trivial: change the root size once and everything sized in rem follows. Designers usually think in pixels, so a converter bridges the gap between a mockup and the stylesheet.\n\nThe conversion works because one rem equals the root font size, so the number of rems is the pixel value divided by that root size. With the browser default of 16 pixels, 16px is 1rem and 24px is 1.5rem. The em unit follows the same arithmetic but is measured against its nearest sized ancestor rather than the root, so it can compound in nested elements. Front-end developers and designers use a px to rem converter to build layouts that respect user font preferences.",
    example: { inputs: { pixels: 24, rootFontSize: 16 }, explanation: "24 ÷ 16 = 1.5, so 24px equals 1.5rem." },
    faqs: [
      {
        question: "What is the difference between rem and em?",
        answer: "Both are relative units, but they measure against different references. A rem is always relative to the root element's font size, so it stays consistent across the whole page. An em is relative to the font size of its own element or nearest sized ancestor, so it can compound when elements nest inside one another. Rem is predictable for layout, while em is handy for spacing that should scale with local text.",
      },
      {
        question: "Why is the default root font size 16px?",
        answer: "Browsers ship with a default root font size of 16 pixels, which is why 16px equals 1rem out of the box. This default balances readability across typical screens and viewing distances. Users can change it in their browser settings, and designs sized in rem will honour that choice. Keeping the standard 16-pixel base, rather than overriding it, respects users who have set a larger size for comfortable reading.",
      },
      {
        question: "Should I use rem or px for font sizes?",
        answer: "Rem is generally preferred for font sizes because it scales with the user's chosen base size, improving accessibility for readers who enlarge text. Pixels stay fixed regardless of that preference, which can frustrate people who need bigger type. Many teams use rem for typography and spacing to keep layouts flexible, reserving pixels for details like fine borders where a fixed, non-scaling size is genuinely desirable.",
      },
      {
        question: "Does changing the root size break my layout?",
        answer: "If your layout is sized consistently in rem, changing the root font size scales everything together in proportion, which is the intended behaviour and a feature rather than a bug. Problems arise only when rem and fixed pixels are mixed carelessly, so some elements scale and others do not. Sizing consistently in rem lets you retune an entire design's scale from a single root declaration without touching individual rules.",
      },
      {
        question: "How do I convert rem back to pixels?",
        answer: "Multiply the rem value by the root font size. With the standard 16-pixel base, 1.5rem times 16 equals 24 pixels. This reverse conversion is useful when checking a design against a pixel-based mockup or communicating exact sizes to a designer. Just remember the result depends on the current root size, so if the base changes, the equivalent pixel value for the same rem changes with it.",
      },
    ],
    relatedCalculators: ["screen-ppi-calculator", "aspect-ratio-calculator", "image-file-size-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "CSS specification (W3C)",
  },
  {
    id: "typing-speed",
    slug: "typing-speed-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Typing Speed Calculator",
    shortDescription: "Measure gross and net words per minute with accuracy.",
    seoTitle: "Typing Speed Calculator — Words Per Minute and Accuracy",
    metaDescription: "Free typing speed calculator. Enter words typed, minutes, and errors to find your gross WPM, net WPM after mistakes, and typing accuracy percentage.",
    primaryKeyword: "typing speed calculator",
    secondaryKeywords: ["wpm calculator", "words per minute calculator", "typing accuracy calculator"],
    fields: [
      { id: "words", label: "Words typed", type: "number", unit: "words", required: true, span: 1, min: 0 },
      { id: "minutes", label: "Time taken", type: "number", unit: "min", required: true, span: 1, min: 0 },
      { id: "errors", label: "Errors made", type: "number", unit: "words", required: true, span: 2, min: 0, defaultValue: 0 },
    ],
    results: [
      { id: "netWpm", label: "Net speed", format: "number", decimals: 1, unit: "WPM", isPrimary: true },
      { id: "grossWpm", label: "Gross speed", format: "number", decimals: 1, unit: "WPM", isPrimary: false },
      { id: "accuracy", label: "Accuracy", format: "percentage", decimals: 1, isPrimary: false },
    ],
    formula: "net WPM = (words − errors) ÷ minutes  ·  accuracy = (words − errors) ÷ words × 100",
    formulaExplanation: "Gross speed is simply the words typed divided by the minutes taken, measuring raw pace. Net speed subtracts the error count from the words first, so mistakes cancel the credit for the words they spoiled, then divides by the time. Accuracy is the share of words typed correctly, the correct count over the total, as a percentage. The approach works because a fair typing score must reward speed and correctness together, not speed alone.",
    explanation: "A typing speed calculator turns a short typing test into three meaningful numbers: gross words per minute, net words per minute after accounting for mistakes, and accuracy as a percentage. Words per minute, or WPM, is the standard measure of typing pace, and separating gross from net reveals whether raw speed is being undermined by errors that would need correcting in real work.\n\nMeasuring this matters for anyone whose work involves the keyboard, from students and writers to data-entry staff and developers. Net WPM is the figure that best reflects productive output, because typing quickly but inaccurately means constant backtracking to fix mistakes. Tracking accuracy alongside speed helps you practise deliberately: pushing pace while accuracy holds up is progress, whereas speed that comes at the cost of errors is not.\n\nThe calculation works by dividing words typed by minutes for gross speed, subtracting errors before dividing for net speed, and expressing correct words as a share of total words for accuracy. A standard word is often counted as five characters, so if you are working from character counts, divide by five first. Average typists reach around 40 WPM, while proficient ones exceed 65. Learners, professionals, and anyone benchmarking their keyboarding use a typing speed calculator to measure and improve real, usable speed.",
    example: { inputs: { words: 400, minutes: 5, errors: 10 }, explanation: "Gross 400 ÷ 5 = 80 WPM; net (400 − 10) ÷ 5 = 78 WPM; accuracy 390 ÷ 400 = 97.5%." },
    faqs: [
      {
        question: "What is the difference between gross and net WPM?",
        answer: "Gross WPM is your raw typing speed, the total words divided by the time, with no penalty for mistakes. Net WPM subtracts your errors before dividing, so it reflects how many correct, usable words you produced per minute. Net WPM is the more meaningful measure of real productivity, because errors in actual work must be found and fixed, which costs time the gross figure ignores entirely.",
      },
      {
        question: "What counts as a word in typing tests?",
        answer: "Typing tests conventionally define a word as five characters, including spaces, rather than counting actual words which vary in length. This standard keeps scores comparable regardless of vocabulary. If your source gives a character count, divide by five to get standardised words before entering them here. If you are counting real words instead, the result still reflects your speed, just measured against natural word lengths.",
      },
      {
        question: "What is a good typing speed?",
        answer: "The average typist reaches roughly 40 words per minute. A speed of 60 to 70 WPM is considered proficient and is typical for people who type professionally. Above 80 WPM is fast, and competitive typists exceed 120. More important than raw speed is sustained accuracy, since a high net WPM depends on making few errors. Steady practice improves both speed and accuracy together over time.",
      },
      {
        question: "How is accuracy calculated?",
        answer: "Accuracy is the proportion of words you typed correctly, found by subtracting errors from total words and dividing by the total, then multiplying by 100 for a percentage. Typing 400 words with 10 errors gives 390 correct, or 97.5 percent accuracy. High accuracy matters because each mistake in real work requires stopping to correct it, which erodes the productive speed that net WPM is designed to capture.",
      },
      {
        question: "How can I improve my typing speed?",
        answer: "Focus first on accuracy, since errors are what drag net speed down, then let speed build naturally through regular practice. Learning touch typing, so you type without looking at the keys, is the biggest single improvement for most people. Practising in short, frequent sessions with proper finger placement and good posture helps. Track your net WPM over time here to confirm that faster typing is not simply producing more mistakes.",
      },
    ],
    relatedCalculators: ["download-time-calculator", "uptime-sla-calculator", "screen-ppi-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard typing measurement (5-char word)",
  },
  {
    id: "cloud-storage-cost",
    slug: "cloud-storage-cost-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Cloud Storage Cost Calculator",
    shortDescription: "Estimate monthly and total cloud storage bills.",
    seoTitle: "Cloud Storage Cost Calculator — Monthly and Total Price",
    metaDescription: "Free cloud storage cost calculator. Enter gigabytes stored, price per GB-month, and months to estimate your monthly and total cloud storage bill. Fast and clear.",
    primaryKeyword: "cloud storage cost calculator",
    secondaryKeywords: ["cloud storage pricing calculator", "s3 cost calculator", "storage cost estimate"],
    fields: [
      { id: "gigabytes", label: "Storage used", type: "number", unit: "GB", required: true, span: 1, min: 0 },
      { id: "pricePerGbMonth", label: "Price per GB-month", type: "number", unit: "$", required: true, span: 1, min: 0, defaultValue: 0.023, step: 0.001 },
      { id: "months", label: "Number of months", type: "number", unit: "months", required: true, span: 2, min: 0, defaultValue: 1 },
    ],
    results: [
      { id: "totalCost", label: "Total cost", format: "currency", decimals: 2, currency: "USD", isPrimary: true },
      { id: "monthlyCost", label: "Monthly cost", format: "currency", decimals: 2, currency: "USD", isPrimary: false },
    ],
    formula: "total = gigabytes × price per GB-month × months",
    formulaExplanation: "Cloud storage is billed per gigabyte for each month it is held, so the monthly charge is the amount stored multiplied by the per-gigabyte rate. Multiplying that monthly figure by the number of months gives the total over the period. The model works because storage pricing is linear in both size and time: doubling either the data kept or the duration doubles the corresponding part of the bill, with no fixed floor in this basic estimate.",
    explanation: "A cloud storage cost calculator estimates what keeping data in a service like Amazon S3, Google Cloud Storage, or Azure Blob will cost, from the amount stored, the per-gigabyte monthly rate, and how many months you keep it. Cloud providers price storage per gigabyte per month, so a clear estimate helps you budget and compare tiers before committing workloads or archives to the cloud.\n\nThe estimate matters because storage costs accumulate quietly. A few terabytes at a low per-gigabyte rate seems cheap monthly, but over a year across many buckets it adds up, and forgotten data keeps billing indefinitely. Seeing the monthly and total figures side by side helps you decide whether to move cold data to a cheaper archival tier, delete stale backups, or negotiate committed-use discounts.\n\nThe calculation is deliberately simple: storage cost is linear, so multiply gigabytes by the per-gigabyte-month price for the monthly figure, then by the number of months for the total. Real bills also include request charges, data-transfer (egress) fees, and tier differences, which this baseline does not model, so treat the result as the storage-at-rest portion. Engineers, finance teams, and anyone forecasting cloud spend use a storage cost calculator to size budgets and spot savings before the invoice arrives.",
    example: { inputs: { gigabytes: 1000, pricePerGbMonth: 0.023, months: 12 }, explanation: "1000 × $0.023 = $23 per month, and $23 × 12 = $276 for the year." },
    faqs: [
      {
        question: "What is a GB-month in cloud pricing?",
        answer: "A GB-month is the standard unit cloud providers bill storage in: one gigabyte kept for one month. If you store 100 GB for a full month, you are billed for 100 GB-months. Storing the same data for half a month bills roughly 50 GB-months, since most providers prorate by the hour. This unit lets pricing scale smoothly with both how much you store and how long you keep it.",
      },
      {
        question: "Does this include data transfer costs?",
        answer: "No, this calculator estimates only storage at rest, the charge for keeping data. Providers separately bill data transfer, especially egress, the cost of moving data out of the cloud to the internet or another region. Egress can rival or exceed storage costs for busy applications. There are also small per-request charges for operations. Add those separately when budgeting, as they depend heavily on your access patterns rather than volume stored.",
      },
      {
        question: "How can I reduce my cloud storage bill?",
        answer: "Move infrequently accessed data to cheaper archival or cold-storage tiers, which cost a fraction of standard storage in exchange for slower or costlier retrieval. Delete stale backups, logs, and orphaned data that no longer serve a purpose. Enable lifecycle policies to transition or expire objects automatically. For predictable long-term needs, committed-use discounts lower the rate. Regularly auditing what you store is often the largest single saving.",
      },
      {
        question: "Why do storage prices vary so much?",
        answer: "Prices differ by provider, region, and storage class. Standard tiers optimised for frequent access cost more per gigabyte than archival tiers meant for rarely touched data. Geographic region affects price because of local infrastructure costs. Redundancy options, such as storing copies across multiple zones, also raise the rate. Enter the specific per-gigabyte-month price for the exact tier and region you are using to get an accurate estimate.",
      },
      {
        question: "Is cloud storage cheaper than local storage?",
        answer: "It depends on scale, access needs, and time horizon. Cloud storage avoids upfront hardware costs and offers durability, redundancy, and easy scaling, which suits variable or growing needs. For very large, steady, long-lived datasets, owning hardware can be cheaper over years despite the maintenance burden. This calculator helps you project the cloud side of that comparison so you can weigh it against the total cost of running your own storage.",
      },
    ],
    relatedCalculators: ["hosting-bandwidth-calculator", "bandwidth-cost-calculator", "uptime-sla-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard cloud pricing model",
  },
  {
    id: "api-rate-limit",
    slug: "api-rate-limit-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "API Rate Limit Calculator",
    shortDescription: "Project total API requests from a per-second rate.",
    seoTitle: "API Rate Limit Calculator — Requests Over Time",
    metaDescription: "Free API rate limit calculator. Enter requests per second and a time window in hours to project total requests and the per-minute rate. Plan quotas with confidence.",
    primaryKeyword: "api rate limit calculator",
    secondaryKeywords: ["requests per second calculator", "api quota calculator", "rate limit calculator"],
    fields: [
      { id: "requestsPerSecond", label: "Requests per second", type: "number", unit: "req/s", required: true, span: 1, min: 0 },
      { id: "hours", label: "Time window", type: "number", unit: "hours", required: true, span: 1, min: 0, defaultValue: 24 },
    ],
    results: [
      { id: "totalRequests", label: "Total requests", format: "number", decimals: 0, unit: "requests", isPrimary: true },
      { id: "perMinute", label: "Per minute", format: "number", decimals: 0, unit: "req/min", isPrimary: false },
    ],
    formula: "total = requests per second × 3,600 × hours",
    formulaExplanation: "A steady request rate multiplied by the number of seconds in the window gives the total count of requests. One hour holds 3,600 seconds, so multiplying the per-second rate by 3,600 and then by the number of hours yields the total over the period. The per-minute figure comes from multiplying the per-second rate by 60. The approach works because at a constant rate, total volume is simply rate times elapsed time in matching units.",
    explanation: "An API rate limit calculator projects how many requests a steady per-second rate produces over a chosen window, and the equivalent per-minute rate. APIs are commonly governed by limits expressed per second, per minute, per day, or per month, and converting between these units is essential for staying under a quota, sizing a plan, or estimating the load a client will generate.\n\nThis matters on both sides of an API. If you consume an API, projecting your request volume tells you whether your usage fits within a provider's daily or monthly allowance before you hit throttling or overage charges. If you operate one, the figures help you set limits that protect your infrastructure while accommodating legitimate traffic. Converting a burst rate into daily and per-minute totals makes an abstract limit concrete and easy to plan against.\n\nThe calculation works because at a constant rate, total requests equal the rate multiplied by the elapsed time once units align. Multiplying requests per second by 3,600 gives requests per hour, and multiplying by the number of hours gives the window total; multiplying the per-second rate by 60 gives the per-minute figure. Real traffic is bursty rather than perfectly steady, so pair this baseline with headroom for peaks. Developers, platform engineers, and API product teams use a rate limit calculator to align usage with quotas.",
    example: { inputs: { requestsPerSecond: 10, hours: 24 }, explanation: "10 req/s × 3,600 × 24 = 864,000 requests per day; 10 × 60 = 600 per minute." },
    faqs: [
      {
        question: "How do I convert between rate limit units?",
        answer: "Multiply or divide by the number of seconds in the target period. Requests per second times 60 gives per minute, times 3,600 gives per hour, and times 86,400 gives per day. To go the other way, divide. This calculator handles the arithmetic so you can check whether a per-second client rate fits inside a provider's daily or monthly quota, which are often expressed in entirely different units.",
      },
      {
        question: "Should I plan for average or peak rate?",
        answer: "Both. Average rate tells you whether your total volume fits a daily or monthly quota, while peak rate determines whether you trip a per-second or per-minute burst limit during busy moments. Real traffic clusters, so a client averaging a modest rate can still exceed a per-second cap in a spike. Size against your realistic peak for burst limits and against your average for long-window quotas, leaving headroom for both.",
      },
      {
        question: "What happens when I exceed a rate limit?",
        answer: "Most APIs respond with an error, commonly HTTP status 429 Too Many Requests, and reject the excess calls until the window resets. Some queue or throttle instead, and others charge overage fees. Well-behaved clients respect a Retry-After header and back off. Projecting your volume with this calculator helps you stay under the limit, or request a higher tier in advance, rather than discovering the ceiling through failed requests in production.",
      },
      {
        question: "Why express the limit per minute as well?",
        answer: "Different providers publish limits in different units, so having both a per-minute and a total figure lets you compare directly against whatever a given API states. Per-minute is a common window for burst limits, while the total over hours matches daily quotas. Seeing your rate in several units at once makes it easy to line up your projected usage with the specific limit format each provider chooses to enforce.",
      },
      {
        question: "Does this assume a constant request rate?",
        answer: "Yes. The projection multiplies a steady rate by time, which gives an accurate total for uniform traffic but smooths over real-world bursts and idle periods. Actual clients send requests in clusters driven by user activity or batch jobs. Use the total for capacity and quota planning, but add a safety margin for peaks, since a burst can breach a short-window limit even when the long-run average sits comfortably within quota.",
      },
    ],
    relatedCalculators: ["hosting-bandwidth-calculator", "uptime-sla-calculator", "bandwidth-cost-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard rate arithmetic",
  },
  {
    id: "network-latency",
    slug: "network-latency-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Network Latency Calculator",
    shortDescription: "Estimate propagation delay over a distance and medium.",
    seoTitle: "Network Latency Calculator — Distance to Propagation Delay",
    metaDescription: "Free network latency calculator. Enter a distance in kilometres and the transmission medium to estimate the one-way and round-trip propagation delay in milliseconds.",
    primaryKeyword: "network latency calculator",
    secondaryKeywords: ["propagation delay calculator", "ping distance calculator", "fiber latency calculator"],
    fields: [
      { id: "distanceKm", label: "Distance", type: "number", unit: "km", required: true, span: 1, min: 0 },
      {
        id: "mediumFactor",
        label: "Transmission medium",
        type: "select",
        required: true,
        span: 1,
        defaultValue: "1.47",
        options: [
          { value: "1.47", label: "Fiber optic (×1.47)" },
          { value: "1.5", label: "Copper cable (×1.5)" },
          { value: "1.0", label: "Vacuum / radio (×1.0)" },
        ],
      },
    ],
    results: [
      { id: "oneWayMs", label: "One-way latency", format: "number", decimals: 3, unit: "ms", isPrimary: true },
      { id: "roundTripMs", label: "Round-trip (RTT)", format: "number", decimals: 3, unit: "ms", isPrimary: false },
    ],
    formula: "one-way (ms) = distance ÷ (speed of light ÷ medium factor) × 1000",
    formulaExplanation: "Light travels at about 299,792 kilometres per second in a vacuum, but slows in a physical medium by a factor tied to its refractive index, so the effective speed is the vacuum speed divided by that factor. Distance divided by this effective speed gives the one-way time in seconds, multiplied by 1,000 for milliseconds. Round-trip time doubles it, since a signal must travel there and back. The method captures the unavoidable delay set by physics alone.",
    explanation: "A network latency calculator estimates the propagation delay, the time a signal takes to travel a given distance through a transmission medium such as fibre-optic cable, copper, or open air. This is the floor on latency set by physics: no amount of bandwidth or optimisation can beat the speed at which a signal physically crosses the distance, which is why geography fundamentally limits how fast two points can communicate.\n\nUnderstanding this delay matters for anyone designing distributed systems, choosing data-centre locations, or troubleshooting slow connections. It explains why a server across the world always feels less responsive than one nearby, why content delivery networks place servers close to users, and why real-time applications like gaming and video calls are so sensitive to distance. Separating the physics-imposed minimum from other delays helps you know when latency can be improved and when it cannot.\n\nThe calculation works because signals in cable travel slower than light in a vacuum by a factor related to the material's refractive index, roughly 1.47 for fibre and about 1.5 for copper. Dividing the vacuum speed of light by that factor gives the effective speed, and distance divided by effective speed gives the one-way time, doubled for the round trip. Real latency adds routing, switching, queuing, and processing delays on top, so this is the theoretical best case. Network architects and engineers use a latency calculator to reason about the geographic limits of performance.",
    example: { inputs: { distanceKm: 1000, mediumFactor: 1.47 }, explanation: "Effective speed ≈ 203,940 km/s, so 1000 ÷ 203,940 × 1000 ≈ 4.90 ms one-way, 9.81 ms round-trip." },
    faqs: [
      {
        question: "Why is latency higher than the speed of light suggests?",
        answer: "Signals in fibre or copper travel slower than light in a vacuum, typically around two-thirds the vacuum speed, because the medium's refractive index slows them. On top of that physics floor, real networks add delays from routers switching packets, queues under load, and processing at each hop, plus the fact that cables rarely follow the shortest straight-line path. This calculator estimates only the propagation floor, so measured ping is always somewhat higher.",
      },
      {
        question: "What is the difference between one-way and round-trip time?",
        answer: "One-way latency is the time for a signal to travel from source to destination. Round-trip time, or RTT, is the time for it to go there and come back, which is what tools like ping measure. RTT is roughly double the one-way delay for a symmetric path. Many interactive applications care about RTT because a request and its response must both complete before the user sees a result.",
      },
      {
        question: "Which medium factor should I choose?",
        answer: "Use fibre optic, about 1.47, for modern long-haul and internet backbone links, which are overwhelmingly fibre. Choose copper, about 1.5, for older wired connections like traditional Ethernet over twisted pair. Select vacuum or radio, 1.0, for line-of-sight wireless, satellite, or free-space signals that travel at essentially the full speed of light. The factor reflects how much the medium slows the signal relative to light in a vacuum.",
      },
      {
        question: "How does distance affect application performance?",
        answer: "Because propagation delay scales linearly with distance, faraway servers add unavoidable latency to every interaction. This is why a video call or online game with a distant server feels laggy, and why content delivery networks cache data near users. For chatty protocols that require many round trips, distance compounds, since each exchange pays the delay again. Placing services close to users is often the single most effective latency improvement available.",
      },
      {
        question: "Can I reduce propagation latency?",
        answer: "You cannot beat the physics for a given distance and medium, but you can shorten the effective distance or improve the path. Moving servers closer to users, using content delivery networks and edge computing, and choosing more direct network routes all cut propagation delay. Reducing the number of round trips an application needs also helps, since fewer exchanges mean the distance penalty is paid fewer times. The medium itself offers little room, as fibre is already near optimal.",
      },
    ],
    relatedCalculators: ["download-time-calculator", "uptime-sla-calculator", "ip-subnet-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Speed of light and refractive index (physics)",
  },
  {
    id: "bandwidth-cost",
    slug: "bandwidth-cost-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Bandwidth Cost Calculator",
    shortDescription: "Estimate monthly and annual data transfer costs.",
    seoTitle: "Bandwidth Cost Calculator — Monthly and Annual Egress",
    metaDescription: "Free bandwidth cost calculator. Enter monthly gigabytes transferred and the price per GB to estimate your monthly and annual bandwidth or egress bill. Fast and clear.",
    primaryKeyword: "bandwidth cost calculator",
    secondaryKeywords: ["data transfer cost calculator", "egress cost calculator", "cdn bandwidth cost"],
    fields: [
      { id: "monthlyGb", label: "Monthly data transfer", type: "number", unit: "GB", required: true, span: 1, min: 0 },
      { id: "pricePerGb", label: "Price per GB", type: "number", unit: "$", required: true, span: 1, min: 0, defaultValue: 0.09, step: 0.001 },
    ],
    results: [
      { id: "monthlyCost", label: "Monthly cost", format: "currency", decimals: 2, currency: "USD", isPrimary: true },
      { id: "annualCost", label: "Annual cost", format: "currency", decimals: 2, currency: "USD", isPrimary: false },
    ],
    formula: "monthly cost = gigabytes transferred × price per GB",
    formulaExplanation: "Data transfer, or egress, is billed per gigabyte moved, so the monthly cost is simply the gigabytes transferred multiplied by the per-gigabyte price. Multiplying that monthly figure by twelve gives the annual cost, assuming steady traffic. The model works because bandwidth pricing is linear in volume: each additional gigabyte served adds the same fixed charge, so scaling traffic scales the bill in direct proportion with no fixed base in this simple estimate.",
    explanation: "A bandwidth cost calculator estimates what serving data over the internet will cost, from the gigabytes transferred each month and the price charged per gigabyte. This charge, often called egress or data-transfer cost, is one of the most significant and frequently underestimated line items in cloud and content-delivery bills, because it grows directly with how popular and data-heavy a service becomes.\n\nThe estimate matters because bandwidth costs can dominate a budget as traffic scales. A site serving large images, video, or downloads can rack up substantial egress fees, and cloud providers typically charge a premium for data leaving their network. Seeing the monthly and annual figures helps you decide whether to add a content delivery network, optimise asset sizes, negotiate committed pricing, or choose a provider with more generous transfer allowances.\n\nThe calculation is linear: multiply gigabytes transferred by the per-gigabyte price for the monthly cost, then by twelve for the annual figure at steady traffic. Real pricing often uses tiers where the rate drops as volume rises, and many providers include a free allowance before charging, so treat this as a straightforward baseline. Compression, caching, and CDNs can cut billable egress considerably. Developers, site operators, and finance teams use a bandwidth cost calculator to forecast transfer spend and find opportunities to reduce it.",
    example: { inputs: { monthlyGb: 1000, pricePerGb: 0.09 }, explanation: "1000 GB × $0.09 = $90 per month, and $90 × 12 = $1,080 per year." },
    faqs: [
      {
        question: "What is egress and why is it charged?",
        answer: "Egress is data leaving a provider's network, typically toward the internet or another region. Providers charge for it because moving data out consumes their network capacity and interconnection agreements have real costs. Inbound data, or ingress, is often free, while egress is billed per gigabyte. This asymmetry surprises many teams, since a service that receives little but serves a lot of data can face a large and steadily growing bandwidth bill.",
      },
      {
        question: "How can I reduce bandwidth costs?",
        answer: "Use a content delivery network to cache and serve assets from edge locations, which is often cheaper than direct egress and reduces load on your origin. Compress text and optimise images and video to shrink the bytes sent. Enable browser caching so returning visitors re-download less. Avoid unnecessary cross-region transfers. For steady high volume, committed-use or reserved bandwidth pricing can lower the per-gigabyte rate substantially compared with on-demand.",
      },
      {
        question: "Does the price per GB stay constant?",
        answer: "Often not. Many providers use tiered pricing where the per-gigabyte rate falls as monthly volume climbs, and most include a free allowance before any charge applies. Rates also vary by region and destination. This calculator uses a single flat rate for a clear baseline, so for large or tiered usage, check your provider's exact schedule and enter a blended or marginal rate that reflects the tier your traffic actually falls into.",
      },
      {
        question: "Why estimate annual as well as monthly cost?",
        answer: "Monthly figures can look small and easy to dismiss, but bandwidth is a recurring cost that compounds over a year into a meaningful sum. Seeing the annual total puts the expense in the context of a budget cycle and makes the return on optimisation clear: a change that saves a modest amount each month becomes a substantial annual saving. It also helps when comparing providers whose pricing you are evaluating over a longer horizon.",
      },
      {
        question: "Is CDN bandwidth cheaper than cloud egress?",
        answer: "Frequently, yes. Content delivery networks are built to serve large volumes of data efficiently and often price egress below cloud providers' standard rates, sometimes with better committed-use discounts. A CDN also offloads traffic from your origin, cutting the egress you pay there. The exact saving depends on your traffic pattern and the providers involved, so compare the per-gigabyte CDN rate against direct egress using this calculator for your expected volume.",
      },
    ],
    relatedCalculators: ["hosting-bandwidth-calculator", "cloud-storage-cost-calculator", "download-time-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard cloud pricing model",
  },
  {
    id: "gzip-savings",
    slug: "compression-ratio-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Compression Ratio Calculator",
    shortDescription: "Find the ratio and percentage saved after compression.",
    seoTitle: "Compression Ratio Calculator — Space Saved by Compression",
    metaDescription: "Free compression ratio calculator. Enter the original and compressed sizes to find the compression ratio, the percentage of space saved, and the kilobytes saved.",
    primaryKeyword: "compression ratio calculator",
    secondaryKeywords: ["gzip savings calculator", "file compression calculator", "space saved calculator"],
    fields: [
      { id: "originalKb", label: "Original size", type: "number", unit: "KB", required: true, span: 1, min: 0 },
      { id: "compressedKb", label: "Compressed size", type: "number", unit: "KB", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "savedPercent", label: "Space saved", format: "percentage", decimals: 1, isPrimary: true },
      { id: "compressionRatio", label: "Compression ratio", format: "number", decimals: 2, unit: ": 1", isPrimary: false },
      { id: "savedKb", label: "Kilobytes saved", format: "number", decimals: 1, unit: "KB", isPrimary: false },
    ],
    formula: "saved % = (1 − compressed ÷ original) × 100  ·  ratio = original ÷ compressed",
    formulaExplanation: "The compression ratio compares sizes before and after by dividing the original size by the compressed size, so a value of 4 means the data shrank to a quarter and is written as 4 to 1. The percentage saved is the share of the original that disappeared, one minus the compressed fraction, as a percentage. Kilobytes saved is the plain difference between the two sizes. Together these express the same shrinkage as a ratio, a percentage, and an absolute amount.",
    explanation: "A compression ratio calculator measures how effectively data was compressed, from the original size and the compressed size. It reports three complementary views: the compression ratio, the percentage of space saved, and the absolute kilobytes removed. Compression underpins fast websites, efficient storage, and quick transfers, so knowing how much a tool like gzip, Brotli, or an image optimiser actually saved helps you judge whether the effort paid off.\n\nThis matters across web performance and storage. A web developer enabling gzip or Brotli on a server wants to confirm that text assets shrink meaningfully, since smaller responses load faster and cost less bandwidth. Someone archiving files wants to know whether a format is worth the slower compression time. Expressing the result three ways suits different audiences: ratios for technical comparison, percentages for intuitive impact, and kilobytes for concrete transfer savings.\n\nThe calculation works because compression ratio is original divided by compressed, so 4:1 means the data is a quarter of its former size. The percentage saved is one minus the ratio of compressed to original, showing directly how much was eliminated. Highly compressible text can reach 70 to 90 percent savings, while already-compressed formats like JPEG or MP4 barely shrink. Developers, sysadmins, and anyone optimising files use a compression ratio calculator to quantify and compare how well their data compresses.",
    example: { inputs: { originalKb: 100, compressedKb: 25 }, explanation: "Ratio 100 ÷ 25 = 4:1; saved (1 − 25 ÷ 100) × 100 = 75%; 75 KB removed." },
    faqs: [
      {
        question: "What is a good compression ratio?",
        answer: "It depends entirely on the data. Plain text, HTML, CSS, and JavaScript compress extremely well, often reaching ratios of 4:1 to 10:1, meaning 75 to 90 percent savings. Already-compressed formats like JPEG images, MP3 audio, and MP4 video barely shrink further, since their redundancy is already removed. There is no universal target: judge a ratio against what is typical for that kind of content rather than against an absolute benchmark.",
      },
      {
        question: "How does the ratio relate to percentage saved?",
        answer: "They describe the same shrinkage differently. A ratio of 4:1 means the compressed file is one quarter the original, so three quarters, or 75 percent, was saved. A 2:1 ratio saves 50 percent, and 10:1 saves 90 percent. The ratio emphasises how many times smaller the data became, while the percentage emphasises the share removed. Use whichever framing communicates the result most clearly to your audience.",
      },
      {
        question: "Why do some files barely compress?",
        answer: "Compression works by removing redundancy and predictable patterns. Files that are already compressed, such as JPEG, PNG, MP3, MP4, and ZIP archives, have had most of their redundancy stripped, so little remains to remove and the ratio stays near 1:1. Encrypted data looks random and compresses even less. Trying to compress such files again wastes time and can occasionally make them slightly larger due to added container overhead.",
      },
      {
        question: "What is the difference between gzip and Brotli?",
        answer: "Both compress web assets, but Brotli, developed more recently, typically achieves higher ratios on text than gzip, especially at its stronger settings, thanks to a built-in dictionary and better modelling. Gzip is older, universally supported, and faster to compress. Many servers offer both and pick based on what the browser accepts. This calculator measures the actual saving from whichever tool you used, letting you compare their real results on your own files.",
      },
      {
        question: "Does higher compression always help performance?",
        answer: "Not always. Stronger compression shrinks files more but takes longer to compress and sometimes to decompress, which can matter for content generated on the fly. For static assets compressed once and served many times, maximum compression is usually worth it. For dynamic responses, a balanced level avoids adding server delay. Weigh the transfer time saved against the processing cost, using the space saved here as one side of that trade-off.",
      },
    ],
    relatedCalculators: ["download-time-calculator", "image-file-size-calculator", "bandwidth-cost-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard data compression",
  },
];
