import type { CalculatorDefinition } from "../types";

export const technologyR8Calculators: CalculatorDefinition[] = [
  {
    id: "data-usage",
    slug: "data-usage-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Data Usage Calculator",
    shortDescription: "Estimate monthly and yearly data use from streaming hours.",
    seoTitle: "Data Usage Calculator — Monthly Streaming Data",
    metaDescription: "Free data usage calculator. Enter your daily streaming hours and video quality to estimate how many gigabytes you use each month and year. Plan your data plan.",
    primaryKeyword: "data usage calculator",
    secondaryKeywords: ["streaming data calculator", "monthly data usage", "how much data does streaming use"],
    fields: [
      { id: "hoursPerDay", label: "Streaming per day", type: "number", unit: "hours", required: true, span: 1, min: 0, step: 0.5 },
      {
        id: "gbPerHour",
        label: "Video quality",
        type: "select",
        required: true,
        span: 1,
        defaultValue: "3",
        options: [
          { value: "1", label: "SD (1 GB/hour)" },
          { value: "3", label: "HD (3 GB/hour)" },
          { value: "7", label: "4K UHD (7 GB/hour)" },
        ],
      },
    ],
    results: [
      { id: "monthlyGb", label: "Monthly data", format: "number", decimals: 0, unit: "GB", isPrimary: true },
      { id: "annualGb", label: "Yearly data", format: "number", decimals: 0, unit: "GB", isPrimary: false },
    ],
    formula: "monthly GB = hours per day × GB per hour × 30",
    formulaExplanation: "Streaming consumes a roughly fixed amount of data for each hour watched, set by the video quality: standard definition uses about a gigabyte per hour, high definition around three, and 4K about seven. Multiplying the hours you watch each day by that per-hour rate gives daily use, and multiplying by thirty approximates a month. The yearly figure multiplies the monthly total by twelve, giving a clear picture of long-run consumption against a data cap.",
    explanation: "A data usage calculator estimates how many gigabytes your streaming habits consume each month and year, from two simple inputs: how many hours a day you watch and the video quality you stream at. Streaming video is by far the largest source of data use for most households, so translating viewing hours into gigabytes is the key to choosing a data plan, avoiding overage charges, or staying within a mobile cap.\n\nThe estimate matters because data allowances and streaming quality vary widely, and the difference between resolutions is dramatic. Watching in 4K uses roughly seven times the data of standard definition, so a household that streams several hours of ultra-high-definition video a day can burn through hundreds of gigabytes a month, while the same hours in SD stay modest. Seeing the monthly and yearly totals helps you decide whether to cap streaming quality, upgrade a plan, or rely on Wi-Fi rather than mobile data.\n\nThe calculation works because streaming data use is close to linear in both time and quality: each hour at a given resolution transfers a fairly steady number of gigabytes. Multiplying daily hours by the per-hour rate and by thirty approximates monthly use, and by twelve gives the year. Real use varies with the service, codec, and whether audio-only or downloads are involved, so treat this as a planning estimate. Households, travellers, and anyone on a metered connection use a data usage calculator to match their viewing to their allowance.",
    example: { inputs: { hoursPerDay: 4, gbPerHour: 3 }, explanation: "4 hours/day × 3 GB/hour × 30 = 360 GB per month, and about 4,320 GB per year." },
    faqs: [
      {
        question: "How much data does streaming actually use?",
        answer: "It depends heavily on resolution. Standard definition uses roughly one gigabyte per hour, high definition around three gigabytes, and 4K ultra-high-definition about seven gigabytes per hour. Music streaming uses far less, often under 150 megabytes per hour. These are typical averages; the exact figure varies by service and the video codec used. This calculator lets you pick a quality tier so your estimate reflects how you actually watch.",
      },
      {
        question: "Why does video quality change data use so much?",
        answer: "Higher resolutions pack far more detail into each frame, which means many more pixels and therefore more data to transmit every second. Moving from SD to HD roughly triples the data rate, and 4K roughly doubles it again over HD. Newer codecs claw some of that back through better compression, but the broad rule holds: the sharper the picture, the more gigabytes each hour consumes. Lowering quality is the fastest way to cut data use.",
      },
      {
        question: "How can I reduce my streaming data usage?",
        answer: "Lower the playback quality in each app's settings, since most default to the highest your connection allows. Download shows over Wi-Fi to watch later instead of streaming on mobile data. Turn off autoplay so videos do not keep loading unwatched. Stream music rather than music videos when you only want audio. On mobile, restrict streaming apps to Wi-Fi. These steps together can cut a heavy streamer's monthly data by more than half.",
      },
      {
        question: "Is 30 days an accurate month for this estimate?",
        answer: "Using 30 days gives a consistent, slightly conservative monthly figure that suits planning against a data cap. Actual months range from 28 to 31 days, so a 31-day month uses a little more and February a little less. The small difference rarely matters for budgeting against an allowance, where leaving headroom for busy weeks is wise anyway. The yearly figure multiplies by twelve, smoothing out these month-length variations.",
      },
      {
        question: "Does this include downloads and other apps?",
        answer: "No, this estimate covers streaming video at the quality you select. It does not add downloads, large file transfers, video calls, gaming updates, or background app data, which can each be significant. If your household does a lot of those, add their data separately when comparing against a cap. For most homes, though, streaming video dominates total usage, so this figure is a strong starting point for plan sizing.",
      },
    ],
    relatedCalculators: ["download-time-calculator", "bandwidth-cost-calculator", "cloud-storage-cost-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Typical streaming bitrates (industry averages)",
  },
  {
    id: "video-file-size",
    slug: "video-file-size-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Video File Size Calculator",
    shortDescription: "Estimate a video's file size from its bitrate and length.",
    seoTitle: "Video File Size Calculator — Bitrate and Duration to Size",
    metaDescription: "Free video file size calculator. Enter a video's duration in minutes and bitrate in Mbps to estimate its file size in gigabytes and megabytes. Plan storage and uploads.",
    primaryKeyword: "video file size calculator",
    secondaryKeywords: ["video size calculator", "bitrate to file size", "how big is a video file"],
    fields: [
      { id: "durationMinutes", label: "Video length", type: "number", unit: "min", required: true, span: 1, min: 0 },
      { id: "bitrateMbps", label: "Bitrate", type: "number", unit: "Mbps", required: true, span: 1, min: 0, step: 0.5, helpText: "Megabits per second — check your export settings." },
    ],
    results: [
      { id: "sizeGb", label: "File size", format: "number", decimals: 2, unit: "GB", isPrimary: true },
      { id: "sizeMb", label: "In megabytes", format: "number", decimals: 0, unit: "MB", isPrimary: false },
    ],
    formula: "size (GB) = bitrate (Mbps) × minutes × 60 ÷ 8 ÷ 1,024",
    formulaExplanation: "A video's size is set by how many bits it uses each second, the bitrate, multiplied by how many seconds it runs. Multiplying the bitrate in megabits per second by the duration in seconds gives total megabits; dividing by eight converts megabits to megabytes, since a byte is eight bits. Dividing megabytes by 1,024 gives gigabytes. The method works because at a constant bitrate, file size is simply the data rate times the running time.",
    explanation: "A video file size calculator estimates how large a video file will be from its bitrate and duration. Bitrate, measured in megabits per second, is the amount of data the video uses each second, and it is the single biggest factor in both file size and visual quality. Knowing the resulting size in advance helps you plan storage, gauge upload times, and confirm a file will fit within a platform's limits before you export or transfer it.\n\nThis estimate is valuable across video work. An editor choosing export settings wants to know whether a project will fit on a drive or under an email attachment limit. A creator uploading to a platform with a size cap needs to confirm the file qualifies. Anyone archiving footage can project how much storage a library will need. Because bitrate drives both quality and size, seeing the trade-off in gigabytes makes it concrete when deciding how aggressively to compress.\n\nThe calculation works because a constant-bitrate video's size equals its data rate multiplied by its length. Multiplying bitrate in megabits per second by the duration in seconds gives total megabits, dividing by eight converts to megabytes, and dividing by 1,024 gives gigabytes. Variable-bitrate encoding makes real files fluctuate around this figure, and container overhead adds a little, so treat the result as a close estimate. Editors, videographers, and anyone managing video use a file size calculator to plan storage and uploads with confidence.",
    example: { inputs: { durationMinutes: 60, bitrateMbps: 8 }, explanation: "8 Mbps × 60 min × 60 ÷ 8 = 3,600 MB, which is about 3.52 GB." },
    faqs: [
      {
        question: "What is bitrate and where do I find it?",
        answer: "Bitrate is the amount of data a video uses per second, measured in megabits per second (Mbps). You set it in your editor's or camera's export and recording settings, where it may be called target bitrate or data rate. Streaming services and cameras publish typical values: 1080p often uses 8 to 12 Mbps, while 4K may use 35 to 60 Mbps. Higher bitrate means better quality and a larger file.",
      },
      {
        question: "Why divide by 8 in the formula?",
        answer: "Bitrate is stated in megabits per second, but file sizes are measured in megabytes, and one byte equals eight bits. Dividing the total megabits by eight converts the figure into megabytes. This bits-versus-bytes distinction trips many people up: a connection rated at 80 megabits per second transfers only about 10 megabytes per second. Keeping the units straight is essential to getting an accurate file size from a bitrate.",
      },
      {
        question: "Does higher bitrate always mean better quality?",
        answer: "Up to a point. Higher bitrate preserves more detail and reduces compression artefacts, improving quality, but there are diminishing returns once the bitrate exceeds what the content needs. Beyond that, you add file size without any visible benefit. The ideal bitrate depends on resolution, frame rate, and how much motion the footage contains. Fast-moving or highly detailed video needs more bitrate than a static talking-head shot to look equally clean.",
      },
      {
        question: "Why is my actual file a slightly different size?",
        answer: "Most modern encoders use variable bitrate, which raises the data rate for complex scenes and lowers it for simple ones, so the real average differs from your target. The container format also adds a small amount of overhead for audio, metadata, and structure. This calculator assumes a constant bitrate for a clean estimate, so expect real files to land close to but not exactly on the predicted size.",
      },
      {
        question: "How do I make a video file smaller?",
        answer: "Lower the bitrate, which directly shrinks the file, though too low introduces visible artefacts. Reduce the resolution or frame rate if the target platform allows. Use a more efficient codec such as H.265 or AV1, which achieve the same quality at a lower bitrate than older H.264. Trimming unnecessary footage also helps. Balance these against acceptable quality, using this calculator to check the size each bitrate choice produces.",
      },
    ],
    relatedCalculators: ["download-time-calculator", "image-file-size-calculator", "compression-ratio-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard digital media (bitrate × duration)",
  },
  {
    id: "ssd-lifespan",
    slug: "ssd-lifespan-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "SSD Lifespan Calculator",
    shortDescription: "Estimate an SSD's life in years from its endurance rating.",
    seoTitle: "SSD Lifespan Calculator — Years From TBW Endurance",
    metaDescription: "Free SSD lifespan calculator. Enter your drive's TBW endurance rating and your daily writes to estimate how many years the SSD will last before wearing out.",
    primaryKeyword: "ssd lifespan calculator",
    secondaryKeywords: ["ssd life calculator", "tbw calculator", "ssd endurance calculator"],
    fields: [
      { id: "tbwRating", label: "Endurance rating (TBW)", type: "number", unit: "TB", required: true, span: 1, min: 0, helpText: "Terabytes written the drive is rated for — from its spec sheet." },
      { id: "dailyWriteGb", label: "Data written per day", type: "number", unit: "GB", required: true, span: 1, min: 0 },
    ],
    results: [
      { id: "lifespanYears", label: "Estimated lifespan", format: "number", decimals: 1, unit: "years", isPrimary: true },
    ],
    formula: "lifespan (years) = TBW × 1,000 ÷ (daily GB written × 365)",
    formulaExplanation: "An SSD is rated for a total number of terabytes that can be written to it, its TBW endurance, before its memory cells wear out. Converting that rating to gigabytes (multiplying by 1,000) gives the total writes the drive can absorb. Dividing by the gigabytes you write each day gives the number of days it lasts, and dividing that by 365 converts to years. The method assumes a steady daily write workload across the drive's life.",
    explanation: "An SSD lifespan calculator estimates how many years a solid-state drive will last before its flash memory wears out, based on its endurance rating and how much data you write to it each day. SSDs wear out through writes rather than time: each memory cell tolerates a limited number of write cycles, and manufacturers express this limit as TBW, the total terabytes that can be written over the drive's warranted life.\n\nThe estimate reassures users and informs planning. Many people worry that SSDs fail quickly, but the arithmetic usually shows the opposite: for typical workloads, a modern drive lasts far longer than the computer it lives in. Knowing your projected lifespan helps you decide whether a consumer drive suffices or whether a write-heavy task, such as video editing, database work, or continuous logging, justifies a higher-endurance model. It also frames the value of the manufacturer's warranty period.\n\nThe calculation works by treating TBW as a budget of writes. Converting the terabyte rating to gigabytes and dividing by your daily write volume gives the number of days the drive can sustain that rate, which divided by 365 gives years. Real endurance is affected by write amplification, how full the drive is kept, and temperature, so treat the figure as a planning guide rather than a guarantee. Enthusiasts, IT professionals, and anyone sizing storage use an SSD lifespan calculator to match a drive's endurance to their workload.",
    example: { inputs: { tbwRating: 600, dailyWriteGb: 50 }, explanation: "600 TBW × 1,000 ÷ (50 GB × 365) ≈ 32.9 years at 50 GB written per day." },
    faqs: [
      {
        question: "What is TBW and where do I find it?",
        answer: "TBW stands for terabytes written, the total amount of data a manufacturer guarantees you can write to an SSD over its warranted life before the flash cells wear out. It appears on the drive's specification sheet or product page, often alongside the warranty period. A typical consumer 1 TB drive might be rated for 300 to 600 TBW, while enterprise drives rate far higher. Enter that number to estimate lifespan.",
      },
      {
        question: "How much data do I write per day?",
        answer: "For most home and office users, daily writes are surprisingly low, often 10 to 50 gigabytes, covering documents, browsing caches, app updates, and the occasional download. Gamers installing large titles and video editors handling raw footage write much more. Monitoring tools and the drive's own SMART data can report your actual total bytes written over time, which divided by the days in use gives your real daily average for an accurate estimate.",
      },
      {
        question: "Will my SSD really last that long?",
        answer: "For typical workloads, the calculated lifespan often exceeds the useful life of the whole computer, which is reassuring. However, the figure assumes steady writes and ignores factors like write amplification, where the drive physically writes more than the data you send, and the effect of keeping a drive nearly full. Treat the result as an optimistic planning estimate. Most drives are replaced for capacity or speed long before they exhaust their write endurance.",
      },
      {
        question: "What happens when an SSD reaches its TBW?",
        answer: "Exceeding the TBW rating does not mean instant failure; it means the drive has passed the endurance the manufacturer guarantees, and the risk of worn cells rises. Many drives keep working well beyond their rating, while others enter a read-only mode to protect existing data once wear is severe. Because behaviour varies, back up important data and consider replacement as a drive approaches or passes its rated endurance, rather than waiting for errors.",
      },
      {
        question: "How can I extend my SSD's lifespan?",
        answer: "Leave some free space, since a fuller drive forces more internal rewriting and raises wear. Avoid unnecessary heavy write workloads, such as constant large temporary files, and enable TRIM so the drive manages unused blocks efficiently. Keep firmware updated, as manufacturers improve wear-levelling over time. Modern SSDs handle this automatically for the most part, so for everyday use the drive will comfortably outlast its practical usefulness without special effort.",
      },
    ],
    relatedCalculators: ["cloud-storage-cost-calculator", "image-file-size-calculator", "video-file-size-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Manufacturer TBW endurance model",
  },
  {
    id: "color-contrast",
    slug: "color-contrast-ratio-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Color Contrast Ratio Calculator",
    shortDescription: "Check WCAG contrast between two hex colors for accessibility.",
    seoTitle: "Color Contrast Ratio Calculator — WCAG Accessibility Check",
    metaDescription: "Free color contrast ratio calculator. Enter a foreground and background hex color to get the WCAG contrast ratio and see whether it passes AA for accessible text.",
    primaryKeyword: "color contrast calculator",
    secondaryKeywords: ["wcag contrast checker", "contrast ratio calculator", "accessibility color checker"],
    fields: [
      { id: "foregroundHex", label: "Text color", type: "text", placeholder: "#111111", required: true, span: 1, helpText: "Foreground hex code, with or without #." },
      { id: "backgroundHex", label: "Background color", type: "text", placeholder: "#FFFFFF", required: true, span: 1, helpText: "Background hex code, with or without #." },
    ],
    results: [
      { id: "contrastRatio", label: "Contrast ratio", format: "number", decimals: 2, unit: ": 1", isPrimary: true },
      { id: "wcagAA", label: "WCAG AA (normal text)", format: "text", isPrimary: false },
    ],
    formula: "ratio = (L_lighter + 0.05) ÷ (L_darker + 0.05)",
    formulaExplanation: "Each colour's relative luminance is found by converting its sRGB channels to a linear scale (dividing by 255, then applying the sRGB gamma curve) and weighting them 0.2126 red, 0.7152 green, and 0.0722 blue, matching how the eye perceives brightness. The contrast ratio then divides the lighter luminance plus 0.05 by the darker plus 0.05. The 0.05 offset models ambient screen glare, and the ratio ranges from 1:1 for identical colours to 21:1 for black on white.",
    explanation: "A color contrast ratio calculator measures how readable text is against its background by comparing two colours using the WCAG accessibility standard. It returns the contrast ratio, a number from 1:1 to 21:1, and tells you whether that ratio meets the Web Content Accessibility Guidelines Level AA threshold for normal text. Sufficient contrast is essential so that people with low vision or colour deficiencies, and anyone in bright sunlight, can read content comfortably.\n\nThis check matters for designers, developers, and content creators building accessible, compliant interfaces. Accessibility law and platform guidelines in many regions reference WCAG, so failing contrast can be both an exclusion of real users and a legal risk. Beyond compliance, good contrast simply makes products easier to use for everyone. Testing a text-and-background pair before shipping catches problems that are easy to fix in design but costly to retrofit later.\n\nThe calculation follows the WCAG formula precisely. Each colour is converted from its hex code to relative luminance by linearising the red, green, and blue channels through the sRGB gamma curve and weighting them by how sensitive human vision is to each. The ratio divides the lighter luminance plus a small glare offset by the darker plus the same offset. WCAG AA requires at least 4.5:1 for normal text and 3:1 for large text. Designers and developers use a contrast calculator to guarantee their colour choices are legible and accessible.",
    example: { inputs: { foregroundHex: "#767676", backgroundHex: "#FFFFFF" }, explanation: "Grey #767676 on white yields a ratio of about 4.54:1, just passing WCAG AA for normal text." },
    faqs: [
      {
        question: "What contrast ratio do I need to pass WCAG?",
        answer: "WCAG Level AA requires a contrast ratio of at least 4.5:1 for normal-size text and 3:1 for large text, defined as 18 point or 14 point bold and above. The stricter Level AAA asks for 7:1 normal and 4.5:1 large. This calculator checks the AA normal-text threshold of 4.5:1. Meeting or exceeding these ratios ensures text remains legible for users with moderate vision loss.",
      },
      {
        question: "How is the contrast ratio actually calculated?",
        answer: "Each colour is converted to a relative luminance value that reflects perceived brightness, by linearising its red, green, and blue channels and weighting green most heavily because the eye is most sensitive to it. The ratio then divides the lighter colour's luminance plus 0.05 by the darker's plus 0.05. That small offset accounts for screen glare. The result ranges from 1:1 for identical colours up to 21:1 for pure black on pure white.",
      },
      {
        question: "Why does green count more than red and blue?",
        answer: "The luminance weights, 0.2126 for red, 0.7152 for green, and 0.0722 for blue, mirror the sensitivity of human vision. Our eyes perceive green light as much brighter than the same intensity of red or blue, so green contributes most to how bright a colour appears. Weighting the channels this way makes the contrast ratio match perceived readability rather than raw numeric colour values, which is what accessibility requires.",
      },
      {
        question: "Does contrast apply to large text differently?",
        answer: "Yes. Because large text is easier to read, WCAG relaxes its contrast requirement to 3:1 at Level AA, compared with 4.5:1 for normal text. Large is defined as at least 18 point, or 14 point when bold. This calculator reports the AA normal-text result, so a pair that fails here at 4.5:1 might still pass for headings and large display text. Always test at the size the text will actually appear.",
      },
      {
        question: "What if I enter an invalid hex code?",
        answer: "The calculator needs valid three- or six-digit hexadecimal colour codes, optionally prefixed with a hash, such as #1A2B3C or #abc. If either field contains characters outside 0 to 9 and A to F, or the wrong number of digits, the result cannot be computed and shows a dash. Correct the code to a proper hex value and the ratio and pass or fail verdict will appear immediately.",
      },
    ],
    relatedCalculators: ["hex-to-rgb-converter", "screen-ppi-calculator", "aspect-ratio-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "WCAG 2.1 relative luminance (W3C)",
    sourceUrl: "https://www.w3.org/TR/WCAG21/#dfn-contrast-ratio",
  },
  {
    id: "number-base",
    slug: "binary-to-decimal-converter",
    category: "Technology",
    categorySlug: "technology",
    title: "Binary to Decimal Converter",
    shortDescription: "Convert numbers between binary, decimal, and hexadecimal.",
    seoTitle: "Binary to Decimal Converter — Binary, Decimal, Hex",
    metaDescription: "Free binary to decimal converter. Convert whole numbers between binary, decimal, and hexadecimal in any direction. Enter a value, choose the bases, get the result.",
    primaryKeyword: "binary to decimal converter",
    secondaryKeywords: ["number base converter", "decimal to binary converter", "hex converter"],
    fields: [
      { id: "value", label: "Value to convert", type: "text", placeholder: "1010", required: true, span: 2, helpText: "A whole number written in the source base." },
      {
        id: "from",
        label: "From base",
        type: "select",
        required: true,
        span: 1,
        defaultValue: "binary",
        options: [
          { value: "binary", label: "Binary (base 2)" },
          { value: "decimal", label: "Decimal (base 10)" },
          { value: "hex", label: "Hexadecimal (base 16)" },
        ],
      },
      {
        id: "to",
        label: "To base",
        type: "select",
        required: true,
        span: 1,
        defaultValue: "decimal",
        options: [
          { value: "binary", label: "Binary (base 2)" },
          { value: "decimal", label: "Decimal (base 10)" },
          { value: "hex", label: "Hexadecimal (base 16)" },
        ],
      },
    ],
    results: [
      { id: "result", label: "Converted value", format: "text", isPrimary: true },
    ],
    formula: "result = value interpreted in the source base, re-expressed in the target base",
    formulaExplanation: "Every positional number system represents a value as a sum of digits multiplied by powers of its base: binary uses powers of two, decimal powers of ten, and hexadecimal powers of sixteen. Converting first reads the input digits in their source base to recover the underlying integer value, then rewrites that same value using the target base's digits. The number itself never changes; only its written representation does, which is why any base can convert losslessly to any other for whole numbers.",
    explanation: "A binary to decimal converter translates whole numbers between the three number systems that dominate computing: binary (base 2), decimal (base 10), and hexadecimal (base 16). Computers store everything in binary, programmers often read memory and colours in hexadecimal, and humans think in decimal, so moving fluently between these bases is a constant need in software, electronics, and networking work.\n\nThe conversion is useful whenever numbers cross between how machines represent data and how people read it. A developer debugging a bitmask reads binary, a designer reads a hex colour, and a student learning computer science practises converting by hand. Hexadecimal is especially handy because each hex digit maps neatly to four binary bits, making it a compact shorthand for long binary strings. Seeing a value in all these forms builds intuition for how data is actually stored.\n\nThe conversion works on a simple principle: any positional base expresses a number as a sum of digits times powers of that base. The converter reads the input digits in their source base to recover the underlying integer, then rewrites that integer in the target base, using letters A to F for the hex digits ten through fifteen. The value is identical in every base; only its notation changes. Programmers, students, and engineers use a number base converter to move between binary, decimal, and hexadecimal quickly and without arithmetic slips.",
    example: { inputs: { value: "1010", from: "binary", to: "decimal" }, explanation: "Binary 1010 = 8 + 0 + 2 + 0 = 10 in decimal." },
    faqs: [
      {
        question: "How do I convert binary to decimal by hand?",
        answer: "Write the binary digits and assign each a power of two based on its position, starting at 2 to the power 0 on the right and doubling leftward. Add the powers of two wherever a digit is 1. For 1010, the positions holding 1 are the eights place and the twos place, so 8 plus 2 equals 10. This calculator does the same summation instantly and also handles the reverse and hexadecimal.",
      },
      {
        question: "Why is hexadecimal used so often in computing?",
        answer: "Hexadecimal is a compact way to write binary because each hex digit represents exactly four binary bits. A byte, eight bits, becomes just two hex digits, which is far easier to read and less error-prone than a long string of ones and zeros. This is why memory addresses, colour codes, and machine values are commonly shown in hex. It bridges human readability and the binary the machine actually uses.",
      },
      {
        question: "What do the letters A to F mean in hex?",
        answer: "Hexadecimal has sixteen digits, but our decimal system only supplies ten symbols, zero through nine. To represent the values ten through fifteen as single digits, hex borrows the letters A, B, C, D, E, and F. So A is ten, B is eleven, up to F which is fifteen. This lets each hex digit cover all sixteen possible four-bit combinations with a single character.",
      },
      {
        question: "Can this convert numbers with decimal points?",
        answer: "No, this converter handles whole numbers, or integers, only. Fractional values in different bases involve negative powers of the base and behave differently, and many fractions that are exact in one base repeat endlessly in another, which complicates conversion. For integer work such as bitmasks, addresses, colour values, and typical programming tasks, whole-number conversion is what is needed. Enter only digits valid for your chosen source base.",
      },
      {
        question: "Why does an invalid value show a dash?",
        answer: "Each base only permits certain digits: binary allows only 0 and 1, decimal allows 0 through 9, and hexadecimal allows 0 through 9 plus A to F. If your input contains a character that is not valid for the source base you selected, such as a 2 in a binary number, the conversion cannot proceed and the result shows a dash. Correct the value to valid digits and it converts immediately.",
      },
    ],
    relatedCalculators: ["ip-subnet-calculator", "subnet-hosts-calculator", "hex-to-rgb-converter"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Positional numeral systems (mathematics)",
  },
  {
    id: "subnet-hosts",
    slug: "subnet-hosts-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Subnet Hosts Calculator",
    shortDescription: "Find usable and total IP addresses from a CIDR prefix.",
    seoTitle: "Subnet Hosts Calculator — Usable IPs From CIDR Prefix",
    metaDescription: "Free subnet hosts calculator. Enter a CIDR prefix length to find the total number of addresses and how many are usable for hosts in an IPv4 subnet.",
    primaryKeyword: "subnet hosts calculator",
    secondaryKeywords: ["cidr calculator", "usable hosts calculator", "ip address count calculator"],
    fields: [
      { id: "cidrPrefix", label: "CIDR prefix length", type: "number", unit: "/bits", required: true, span: 2, min: 0, max: 32, step: 1, helpText: "The number after the slash, from 0 to 32 (e.g. 24 for /24)." },
    ],
    results: [
      { id: "usableHosts", label: "Usable hosts", format: "number", decimals: 0, unit: "hosts", isPrimary: true },
      { id: "totalAddresses", label: "Total addresses", format: "number", decimals: 0, unit: "addresses", isPrimary: false },
    ],
    formula: "total = 2^(32 − prefix)   ·   usable = total − 2",
    formulaExplanation: "An IPv4 address is 32 bits long. A CIDR prefix fixes the leftmost bits as the network portion, leaving 32 minus the prefix bits free to number hosts. Since each free bit doubles the count, the total addresses equal two raised to that many bits. Two of those addresses are reserved in a standard subnet: the all-zeros network address and the all-ones broadcast address, so the usable host count is the total minus two.",
    explanation: "A subnet hosts calculator tells you how many IP addresses a subnet contains and how many of them can be assigned to actual devices, from a single input: the CIDR prefix length. In modern networking, subnets are written in CIDR notation as an address followed by a slash and a prefix, such as /24, where the prefix says how many leading bits identify the network. The remaining bits are available to number hosts.\n\nThis matters whenever you plan or troubleshoot a network. Choosing the right subnet size means allocating enough addresses for current devices plus growth, without wastefully carving the address space into blocks far larger than needed. A /24 gives 254 usable addresses, comfortable for a typical office LAN, while a /30 gives just two, ideal for a point-to-point link between routers. Getting the size right keeps addressing efficient and routing tidy.\n\nThe calculation rests on binary arithmetic. An IPv4 address has 32 bits; the prefix fixes the network bits, and the 32 minus the prefix host bits each double the number of addresses, so the total is two to that power. A standard subnet reserves two addresses, the network identifier and the broadcast address, so usable hosts equal the total minus two. Very small prefixes like /31 and /32 are special cases used for links and single hosts. Network engineers, administrators, and students use a subnet hosts calculator to size IPv4 subnets correctly.",
    example: { inputs: { cidrPrefix: 24 }, explanation: "A /24 leaves 8 host bits, so 2^8 = 256 total addresses and 256 − 2 = 254 usable hosts." },
    faqs: [
      {
        question: "Why are two addresses subtracted from the total?",
        answer: "In a standard IPv4 subnet, two addresses are reserved and cannot be assigned to devices. The first, with all host bits set to zero, is the network address that identifies the subnet itself. The last, with all host bits set to one, is the broadcast address used to reach every device at once. Because these two are unusable for individual hosts, the usable count is always the total minus two.",
      },
      {
        question: "What does the CIDR prefix number mean?",
        answer: "The prefix, the number after the slash, counts how many of the 32 bits in an IPv4 address are fixed as the network portion. A larger prefix means more network bits and fewer host bits, so a smaller subnet. A /24 fixes 24 bits and leaves 8 for hosts, while a /28 fixes 28 and leaves only 4. Each additional prefix bit halves the number of addresses in the subnet.",
      },
      {
        question: "How do I choose the right subnet size?",
        answer: "Count the devices you need to address now and allow room for growth, then pick the smallest prefix that provides enough usable hosts. For a point-to-point router link, a /30 with two usable addresses suffices. A small office might use a /24 for 254 hosts. Oversizing wastes address space and can complicate routing, while undersizing forces renumbering later, so match the block to realistic need plus a margin.",
      },
      {
        question: "What are /31 and /32 subnets used for?",
        answer: "These are special cases. A /32 identifies a single host address, often used for loopbacks or host routes. A /31, defined by RFC 3021, provides exactly two addresses with no separate network or broadcast reservation, making it efficient for point-to-point links between two routers. Because they break the usual minus-two rule, treat them as purpose-built exceptions. This calculator applies the standard reservation, so verify special cases against your equipment's support.",
      },
      {
        question: "Does this apply to IPv6 as well?",
        answer: "No, this calculator is for IPv4, which uses 32-bit addresses. IPv6 uses 128-bit addresses and vastly larger subnets, typically a /64 for a single network, which holds an astronomically large number of addresses. IPv6 also does not reserve a broadcast address in the same way, so the minus-two rule does not apply. For IPv6 planning, use a dedicated IPv6 subnet tool rather than this IPv4-based calculator.",
      },
    ],
    relatedCalculators: ["ip-subnet-calculator", "binary-to-decimal-converter", "network-latency-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "CIDR / IPv4 addressing (RFC 4632)",
  },
  {
    id: "webpage-load-time",
    slug: "webpage-load-time-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Webpage Load Time Calculator",
    shortDescription: "Estimate how long a page takes to load at a given speed.",
    seoTitle: "Webpage Load Time Calculator — Page Size and Speed",
    metaDescription: "Free webpage load time calculator. Enter a page's size in megabytes and a connection speed in Mbps to estimate how many seconds it takes to download the page.",
    primaryKeyword: "webpage load time calculator",
    secondaryKeywords: ["page load time calculator", "website speed calculator", "download time calculator"],
    fields: [
      { id: "pageSizeMb", label: "Page size", type: "number", unit: "MB", required: true, span: 1, min: 0, step: 0.1 },
      { id: "connectionMbps", label: "Connection speed", type: "number", unit: "Mbps", required: true, span: 1, min: 0, helpText: "Megabits per second of the visitor's connection." },
    ],
    results: [
      { id: "loadSeconds", label: "Load time", format: "number", decimals: 2, unit: "seconds", isPrimary: true },
    ],
    formula: "load time (s) = page size (MB) × 8 ÷ connection speed (Mbps)",
    formulaExplanation: "Page size is measured in megabytes but connection speed in megabits per second, and one byte is eight bits, so the page size is multiplied by eight to convert it to megabits. Dividing those megabits by the connection speed in megabits per second gives the transfer time in seconds. The estimate captures the raw download time set by the amount of data and the bandwidth available, which is the dominant factor for a page's total weight.",
    explanation: "A webpage load time calculator estimates how long it takes to download a page from its total size and the visitor's connection speed. Page weight, the combined size of the HTML, images, scripts, styles, and fonts a page pulls in, has grown steadily, and on slower or mobile connections that weight translates directly into waiting time. Estimating it helps developers understand the experience real users have on connections far slower than an office network.\n\nThis estimate matters because load time shapes both user satisfaction and business outcomes. Visitors abandon slow pages, and search engines factor speed into rankings, so knowing how a page's weight plays out across connection speeds guides decisions about optimising images, deferring scripts, or trimming unused code. Testing a heavy page against a typical mobile speed often reveals that a design that feels instant on fast broadband is painfully slow for a large share of the audience.\n\nThe calculation converts units and divides. Page size in megabytes is multiplied by eight to become megabits, matching the megabits-per-second unit of connection speed, then divided by that speed to give seconds. This models the raw transfer time, which dominates for large pages. Real load time also includes DNS lookup, server response, connection setup, and the time to render and run scripts, so the actual experience is somewhat longer. Web developers, performance engineers, and site owners use a load time calculator to see how page weight affects users across different connection speeds.",
    example: { inputs: { pageSizeMb: 5, connectionMbps: 20 }, explanation: "5 MB × 8 = 40 megabits, and 40 ÷ 20 Mbps = 2 seconds to download." },
    faqs: [
      {
        question: "Why multiply the page size by 8?",
        answer: "Page size is measured in megabytes, but connection speed is quoted in megabits per second, and there are eight bits in a byte. To divide compatible units, you convert the megabytes to megabits by multiplying by eight. Skipping this step underestimates load time roughly eightfold. This bits-versus-bytes distinction is the most common mistake in bandwidth calculations, so keeping the units aligned is essential to a correct estimate.",
      },
      {
        question: "Does this include server and rendering time?",
        answer: "No, this calculator estimates only the raw download time for the page's data. Actual load time also includes DNS resolution, the server generating and sending the first byte, secure connection setup, and the browser's time to parse HTML, run JavaScript, and paint the page. Those steps can add meaningful delay, especially on script-heavy sites. Treat this figure as the network transfer portion, which dominates for large, image-heavy pages.",
      },
      {
        question: "What is a good page size to aim for?",
        answer: "Lighter is better, but a common guideline is to keep total page weight under a few megabytes, and ideally around one megabyte or less for fast mobile performance. Many pages far exceed this because of large images and heavy scripts. Test your page's weight against a realistic mobile speed here: if the download time feels long, optimising images, compressing assets, and removing unused code are usually the highest-impact fixes.",
      },
      {
        question: "Why does the same page load slower on mobile?",
        answer: "Mobile connections typically offer lower and more variable bandwidth than home or office broadband, and higher latency, so the same page takes longer to transfer. Signal strength, network congestion, and moving between cells all reduce effective speed. A page that downloads in a second on fast broadband might take many seconds on a weak mobile signal. Testing against slower speeds reveals the experience a large share of real visitors actually have.",
      },
      {
        question: "How can I make my pages load faster?",
        answer: "Reduce page weight first: compress and correctly size images, use modern formats like WebP or AVIF, and remove unused CSS and JavaScript. Enable server compression such as gzip or Brotli, and cache assets so returning visitors re-download less. Use a content delivery network to serve files from locations near users, cutting latency. Defer non-essential scripts so the page becomes usable sooner. Together these steps cut both transfer time and rendering delay.",
      },
    ],
    relatedCalculators: ["download-time-calculator", "compression-ratio-calculator", "bandwidth-cost-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard data transfer arithmetic",
  },
  {
    id: "email-storage",
    slug: "email-storage-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Email Storage Calculator",
    shortDescription: "Project how much storage your email will use over years.",
    seoTitle: "Email Storage Calculator — Mailbox Size Over Time",
    metaDescription: "Free email storage calculator. Enter emails received per day, average message size, and years to project how many gigabytes your mailbox will accumulate over time.",
    primaryKeyword: "email storage calculator",
    secondaryKeywords: ["mailbox size calculator", "email storage estimate", "inbox storage calculator"],
    fields: [
      { id: "emailsPerDay", label: "Emails per day", type: "number", unit: "emails", required: true, span: 1, min: 0 },
      { id: "avgSizeMb", label: "Average email size", type: "number", unit: "MB", required: true, span: 1, min: 0, defaultValue: 0.5, step: 0.1, helpText: "Include attachments; 0.1–2 MB is typical." },
      { id: "years", label: "Number of years", type: "number", unit: "years", required: true, span: 2, min: 0, defaultValue: 5 },
    ],
    results: [
      { id: "totalStorageGb", label: "Total storage", format: "number", decimals: 2, unit: "GB", isPrimary: true },
    ],
    formula: "storage (GB) = emails per day × average size (MB) × 365 × years ÷ 1,024",
    formulaExplanation: "The number of emails you receive each day multiplied by the average size of each gives the megabytes accumulated daily. Multiplying by 365 extends that to a year, and by the number of years to the full period. Dividing by 1,024 converts megabytes to gigabytes. The model assumes a steady arrival rate and that mail is kept rather than deleted, giving the total space a mailbox would occupy if nothing were ever removed over the span.",
    explanation: "An email storage calculator projects how much disk or cloud space a mailbox will accumulate over time, from how many emails you receive each day, their average size, and how many years you keep them. Email quietly becomes one of the largest personal and organisational data stores, and mailbox quotas are a common source of frustration when they fill up unexpectedly, so projecting growth helps you plan capacity before you hit a limit.\n\nThis estimate is useful for individuals and administrators alike. A user deciding whether a free mailbox quota will last, an IT team sizing storage for hundreds of employees, or a business setting retention policies all need to know how fast mail accumulates. Because attachments dominate size, the average message figure matters as much as the count. Seeing years of projected growth makes the case for archiving, cleanup, or a larger plan concrete rather than abstract.\n\nThe calculation multiplies daily email count by average size to get megabytes per day, scales that by 365 days and the number of years, then divides by 1,024 to express the total in gigabytes. It assumes a steady arrival rate and that nothing is deleted, giving a worst-case accumulation. Real mailboxes are pruned, and average sizes shift with attachment habits, so treat the result as a planning ceiling. Individuals, administrators, and anyone managing mailboxes use an email storage calculator to forecast growth and set retention and quota policies.",
    example: { inputs: { emailsPerDay: 50, avgSizeMb: 0.5, years: 5 }, explanation: "50 × 0.5 MB × 365 × 5 = 45,625 MB, which is about 44.56 GB over five years." },
    faqs: [
      {
        question: "What is a typical average email size?",
        answer: "A plain text email is only a few kilobytes, but most messages carry formatting, images, and signatures, and many include attachments. As a result, average sizes commonly fall between 0.1 and 2 megabytes once attachments are blended in. Business mailboxes with frequent document and image attachments trend higher. Check your mail client's storage report to find your real average, since it drives the projection far more than the raw message count.",
      },
      {
        question: "Do attachments dominate mailbox size?",
        answer: "Yes, almost always. The text of an email is tiny compared with a photo, PDF, spreadsheet, or presentation attached to it. A single large attachment can outweigh thousands of plain messages. This is why average message size is such a powerful lever in the projection: a mailbox that regularly receives big attachments grows far faster than one carrying mostly text. Reducing or offloading attachments is the most effective way to control growth.",
      },
      {
        question: "How can I reduce my email storage use?",
        answer: "Delete large attachments you no longer need, or save them elsewhere and remove them from the mailbox. Empty spam, trash, and sent folders regularly, as these accumulate quietly. Use search tools that sort by size to find the biggest space users. Set up archiving to move old mail off the primary quota. For organisations, retention policies that automatically expire aged mail keep storage predictable and bounded over time.",
      },
      {
        question: "Does this assume I never delete email?",
        answer: "Yes, the projection assumes a steady arrival rate with nothing deleted, so it represents a worst-case accumulation if you kept every message. In practice most people delete spam, newsletters, and large attachments over time, so real mailbox size grows more slowly. Use the figure as a planning ceiling for quota and storage decisions, then adjust downward for whatever proportion of mail you realistically expect to remove or archive.",
      },
      {
        question: "Why divide by 1,024 to get gigabytes?",
        answer: "The calculation works in megabytes, and in the binary convention used by most operating systems, one gigabyte equals 1,024 megabytes. Dividing the megabyte total by 1,024 converts it to gigabytes on that basis. Some providers instead use 1,000 megabytes per gigabyte, which yields a slightly larger gigabyte figure for the same data. The difference is minor for planning, but it explains small discrepancies between tools and quota displays.",
      },
    ],
    relatedCalculators: ["cloud-storage-cost-calculator", "image-file-size-calculator", "data-usage-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard storage accumulation model",
  },
  {
    id: "device-battery-life",
    slug: "device-battery-life-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Device Battery Life Calculator",
    shortDescription: "Estimate battery runtime from capacity and current draw.",
    seoTitle: "Device Battery Life Calculator — Runtime From mAh and Draw",
    metaDescription: "Free device battery life calculator. Enter a battery's capacity in mAh and the device's current draw in mA to estimate how many hours it will run on a charge.",
    primaryKeyword: "battery life calculator",
    secondaryKeywords: ["battery runtime calculator", "mah to hours calculator", "device battery calculator"],
    fields: [
      { id: "batteryMah", label: "Battery capacity", type: "number", unit: "mAh", required: true, span: 1, min: 0 },
      { id: "deviceDrawMa", label: "Current draw", type: "number", unit: "mA", required: true, span: 1, min: 0, helpText: "Average current the device draws while running." },
    ],
    results: [
      { id: "batteryHours", label: "Estimated runtime", format: "number", decimals: 1, unit: "hours", isPrimary: true },
    ],
    formula: "runtime (hours) = battery capacity (mAh) ÷ current draw (mA)",
    formulaExplanation: "Battery capacity in milliamp-hours states how much charge the cell holds: a milliamp-hour is the charge delivered by one milliamp flowing for one hour. Dividing the capacity by the current the device draws in milliamps gives the number of hours that current can flow before the charge is exhausted. The units cancel cleanly because milliamp-hours divided by milliamps leaves hours, making this a direct estimate of runtime at a steady draw.",
    explanation: "A device battery life calculator estimates how long a battery will power a device from two figures: the battery's capacity in milliamp-hours (mAh) and the device's average current draw in milliamps (mA). This simple ratio underlies runtime estimates for phones, tablets, wearables, drones, flashlights, and countless electronics projects, giving a quick sense of how long a charge should last under a given load.\n\nThe estimate is useful for consumers comparing devices and for makers designing their own. Someone choosing a power bank wants to know how many phone charges it delivers; a hobbyist building an Arduino or Raspberry Pi project needs to size a battery for a target runtime; a drone pilot estimates flight time before the pack runs down. Because runtime scales directly with capacity and inversely with draw, the calculator makes the trade-off between a bigger battery and a hungrier device immediately clear.\n\nThe calculation works because milliamp-hours measure stored charge and milliamps measure the rate charge is consumed, so dividing capacity by draw leaves a result in hours. Real batteries fall short of this ideal: efficiency losses in voltage conversion, capacity that fades with age and cold, and draw that varies with activity all reduce actual runtime, typically to 70 to 90 percent of the theoretical figure. Treat the result as an optimistic upper bound. Consumers, hobbyists, and engineers use a battery life calculator to estimate and compare device runtimes.",
    example: { inputs: { batteryMah: 4000, deviceDrawMa: 500 }, explanation: "4000 mAh ÷ 500 mA = 8 hours of runtime at a steady 500 mA draw." },
    faqs: [
      {
        question: "What does mAh mean on a battery?",
        answer: "mAh stands for milliamp-hours, a measure of how much electric charge a battery stores. One milliamp-hour is the charge delivered by a current of one milliamp flowing for one hour. A 4,000 mAh battery can, in theory, supply 4,000 milliamps for one hour, or 500 milliamps for eight hours. A higher mAh rating means more stored energy at a given voltage, and therefore longer runtime for the same device.",
      },
      {
        question: "Why is real battery life shorter than calculated?",
        answer: "Several losses reduce actual runtime below the theoretical figure. Voltage regulators and converters waste some energy as heat. A device's current draw varies with activity, often exceeding the average you enter during bursts. Batteries lose capacity as they age and in cold temperatures, and manufacturers rate capacity optimistically. Together these mean real runtime is usually 70 to 90 percent of the calculated value, so treat the result as an optimistic ceiling.",
      },
      {
        question: "How do I find my device's current draw?",
        answer: "Check the device's specifications or datasheet, which often list typical and peak current consumption. For electronics projects, a multimeter or USB power meter placed in the circuit measures actual draw directly, which is the most accurate method. Draw varies with what the device is doing, so use an average that reflects your real usage. If only power in watts is given, divide it by the battery voltage to estimate current.",
      },
      {
        question: "Does voltage matter for this calculation?",
        answer: "This simple formula assumes the battery and the device's rated draw share the same voltage, which holds when comparing a device to its own battery. If voltages differ, or you are converting between them, you should work in energy terms using watt-hours instead, found by multiplying capacity in amp-hours by voltage. For matched-voltage estimates, dividing mAh by mA gives hours directly, which covers most everyday comparisons.",
      },
      {
        question: "How can I extend my device's battery life?",
        answer: "Reduce the current draw, since runtime is inversely proportional to it. Lower screen brightness, disable unused radios like Bluetooth and GPS, close background apps, and enable power-saving modes. For projects, put microcontrollers into sleep between tasks, which slashes average draw dramatically. Keeping the battery at moderate temperatures preserves capacity. A larger-capacity battery also helps, but cutting the load is often the most effective and immediate improvement.",
      },
    ],
    relatedCalculators: ["cloud-storage-cost-calculator", "network-latency-calculator", "data-usage-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Battery capacity and current relationship (electronics)",
  },
  {
    id: "print-size",
    slug: "print-size-calculator",
    category: "Technology",
    categorySlug: "technology",
    title: "Print Size Calculator",
    shortDescription: "Find the print dimensions of an image at a given DPI.",
    seoTitle: "Print Size Calculator — Pixels and DPI to Inches",
    metaDescription: "Free print size calculator. Enter an image's pixel width and height and a DPI to find how large it prints in inches. Check resolution before printing photos.",
    primaryKeyword: "print size calculator",
    secondaryKeywords: ["dpi calculator", "pixels to inches calculator", "image print size calculator"],
    fields: [
      { id: "pixelsWide", label: "Image width", type: "number", unit: "px", required: true, span: 1, min: 0 },
      { id: "pixelsTall", label: "Image height", type: "number", unit: "px", required: true, span: 1, min: 0 },
      { id: "dpi", label: "Print resolution", type: "number", unit: "DPI", required: true, span: 2, min: 1, defaultValue: 300, helpText: "300 DPI is standard for quality photo prints." },
    ],
    results: [
      { id: "printWidthInches", label: "Print width", format: "number", decimals: 2, unit: "in", isPrimary: true },
      { id: "printHeightInches", label: "Print height", format: "number", decimals: 2, unit: "in", isPrimary: false },
    ],
    formula: "print inches = pixel dimension ÷ DPI",
    formulaExplanation: "DPI, dots per inch, states how many pixels are packed into each inch of a print. Dividing an image's pixel width by the DPI gives how many inches wide it prints, and dividing the pixel height by the DPI gives the printed height. A higher DPI squeezes the same pixels into a smaller area, producing a sharper but smaller print, while a lower DPI spreads them over more inches, giving a larger but coarser result.",
    explanation: "A print size calculator tells you how large an image will print, in inches, from its pixel dimensions and the print resolution in dots per inch (DPI). The same file can print at many sizes depending on how densely its pixels are packed, so knowing the relationship between pixels and DPI is essential to producing sharp prints and avoiding blurry, pixelated results from stretching an image too far.\n\nThis matters for photographers, designers, and anyone ordering prints. Photo labs and print shops recommend around 300 DPI for crisp results at normal viewing distance, so a given image has a maximum size at which it still looks sharp. Checking this before printing prevents the disappointment of a large print that reveals soft, blocky detail. It also works the other way: for a poster viewed from far away, a lower DPI is acceptable, letting the same file print much larger.\n\nThe calculation is a straightforward division. DPI defines how many pixels occupy each printed inch, so dividing the pixel width by the DPI gives the print width in inches, and the same for height. Halving the DPI doubles the print size but spreads the pixels thinner, reducing sharpness. Because the arithmetic is exact, the calculator makes the trade-off between print size and quality clear at a glance. Photographers, designers, and print buyers use a print size calculator to match image resolution to the size they intend to print.",
    example: { inputs: { pixelsWide: 3000, pixelsTall: 2400, dpi: 300 }, explanation: "3000 ÷ 300 = 10 inches wide and 2400 ÷ 300 = 8 inches tall, a sharp 10×8 print." },
    faqs: [
      {
        question: "What DPI should I use for printing?",
        answer: "For photo prints and detailed material viewed up close, 300 DPI is the standard for sharp, professional results. Fine art and high-end work sometimes use more. Large-format prints like posters and banners, viewed from a distance, look fine at 150 DPI or even lower, because the eye cannot resolve individual dots far away. Match the DPI to viewing distance: closer viewing demands higher DPI, while distant viewing tolerates less.",
      },
      {
        question: "What is the difference between DPI and PPI?",
        answer: "PPI, pixels per inch, describes the pixel density of a digital image or screen, while DPI, dots per inch, technically refers to the ink dots a printer lays down. In everyday use the terms are often used interchangeably for the pixels-per-inch of a print, which is how this calculator treats DPI. The key idea is the same: how many image pixels are mapped into each inch of the final print.",
      },
      {
        question: "Can I print an image larger than its native size?",
        answer: "You can, but quality suffers. Printing at a lower DPI spreads the existing pixels over more inches, and past a point the individual pixels become visible as softness or blockiness. Upscaling software can add pixels by interpolation, which helps modestly but cannot invent true detail that was never captured. For the sharpest result, keep the print size within what the pixel count supports at your chosen DPI, ideally around 300.",
      },
      {
        question: "How many megapixels do I need for a given print?",
        answer: "Multiply the desired pixel width by the height and divide by one million for megapixels. A sharp 10 by 8 inch print at 300 DPI needs 3000 by 2400 pixels, about 7.2 megapixels. A 4 by 6 print needs only around 2 megapixels. Larger prints need proportionally more, though the DPI can be relaxed for big prints viewed from afar. This calculator helps you check whether your file has enough pixels.",
      },
      {
        question: "Does the aspect ratio need to match the paper?",
        answer: "For the image to fill standard paper without cropping, its width-to-height ratio should match the paper's. A 3:2 photo fits a 6 by 4 print exactly, but printing it on 5 by 4 paper requires cropping or leaves borders. This calculator gives the print size at your image's own ratio; if that differs from your target paper, plan to crop, add borders, or choose a paper size that matches the ratio.",
      },
    ],
    relatedCalculators: ["screen-ppi-calculator", "aspect-ratio-calculator", "image-file-size-calculator"],
    status: "active",
    lastReviewed: "2026-08-30",
    formulaSource: "Standard print resolution (pixels ÷ DPI)",
  },
];
